### ISSUE TITLE
payments: is there a way to build in late fees?

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1005]
is there a way to build in late fees?

**Comment by jlyon** [comment]
So this would be something like:

Parking card payments are due on the 1st and are $5 more on the 10th, or something like that?  As long as the overdue date and amount (either $ or %) is the same for every person, we could build something out like this in JavaScript (kind of like what we did with the $4 off if you get > 3 parking cards).  This kind of stuff would be custom work, which I think we would bill at the same rate (not going back into the platform).

@kevindherman

**Comment by kevindherman** [comment]
@jlyon this came up with a prospect who gets a lot of revenue through their parks and rec dept like classes and facility rentals. However, it seems like this could be solved by needing to complete an transaction before the class or rental.

**Comment by jlyon** [comment]
@kevindherman cool, moving this to ready.
