### ISSUE TITLE
Dashboard: If you have more than 1 site, redirect to My Sites (rather than specific site) after login

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1008]
Once I login from my.proudcity.com my sites flashes and then the dashboard for french creek comes up:

https://my.proudcity.com/sites/58cb3a78210772005299fb40/dashboard
![screenshot 2017-06-12 12 51 31](https://user-images.githubusercontent.com/6032426/27045170-1d0eda26-4f6e-11e7-89e5-b2ba6522da26.png)

This is minor for me but I want to keep an eye on this if it persists or comes up for other users.

**Comment by jlyon** [comment]
This is by design. It goes to your first site.  Perhaps we should only do this if they have only one site, though @kevindherman ?

**Comment by kevindherman** [comment]
@jlyon I think that's a good distinction.
