### ISSUE TITLE
Dashboard: sporadic issues with embedded dashboard

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1009]
1. my sites
2. dashboard
3. click site URL, goes to homepage
4. click dashboard on edit bar from homepage
5. Page loads to the dashboard, where it is blank. When the page is loading the url path changes 2 times

- first https://www.cityofsanrafael.org/wp-admin/index.php
- second https://www.cityofsanrafael.org/wp-admin/admin.php?page=proud_dashboard
- third https://www.cityofsanrafael.org/wp-admin/admin.php?page=proud_dashboard#/sites/sanrafaelca/dashboard

6. Ends with blank page
![screenshot 2017-06-12 13 03 11](https://user-images.githubusercontent.com/6032426/27045638-81eff578-4f6f-11e7-8e88-274f30d94333.png)

**Comment by jlyon** [comment]
@kevindherman is this for you personally, or have others been reporting it too?  Are you able to replicate in an incognito window?

1. Login to my.proudcity.com
2. Click on one of the SR dashboard quicklinks
3. Click on DAshboard in WP.  Is the pg blank?

**Comment by kevindherman** [comment]
It's something with the dashboard link on the left sidebar. If I follow your steps and click on the dashboard link in the edit bar (top of the page), it works as it should. However, if I click the dashboard link in the side nav, it goes to a blank page. Once the blank page dashboard has loaded, I can no longer get the embedded view from the top nav. 

![screenshot 2017-06-12 13 03 11](https://user-images.githubusercontent.com/6032426/27046476-93e1fc74-4f72-11e7-9fe5-a5fbd3c113ae.png)

I tested this in incognito for San Rafael and Danvers.

**Comment by jlyon** [comment]
@kevindherman  I'll dig into this later today.  Can you post and errors from the console (R click > Inspect, click on Console in the top bar)

**Comment by kevindherman** [comment]
JQMIGRATE: Migrate is installed, version 1.4.1
icon.png Failed to load resource: the server responded with a status of 404 ()
icon.png Failed to load resource: the server responded with a status of 404 ()
rest.proudcity.com/v1/sites/sanrafaelca Failed to load resource: the server responded with a status of 403 ()
angular.min.js:4883 Error: invalid_token
    at app.min.js:75
    at processQueue (angular.min.js:5302)
    at angular.min.js:5302
    at Scope.$eval (angular.min.js:5956)
    at Scope.$digest (angular.min.js:5867)
    at Scope.$apply (angular.min.js:6034)
    at done (angular.min.js:4049)
    at completeRequest (angular.min.js:4212)
    at XMLHttpRequest.xhr.onload (angular.min.js:4218)
(anonymous) @ angular.min.js:4883
app.min.js:27 Error: invalid_token
    at app.min.js:75
    at processQueue (angular.min.js:5302)
    at angular.min.js:5302
    at Scope.$eval (angular.min.js:5956)
    at Scope.$digest (angular.min.js:5867)
    at Scope.$apply (angular.min.js:6034)
    at done (angular.min.js:4049)
    at completeRequest (angular.min.js:4212)
    at XMLHttpRequest.xhr.onload (angular.min.js:4218)
app.min.js:31 Sorry, there was an error fetching data.  Please try logging out and logging back in.  If that still does not work, please try again in a few minutes.
storage.googleapis.com/proudcity/sanrafaelca2016/11/cropped-Logo_on_white-192x192.png Failed to load resource: the server responded with a status of 403 ()
storage.googleapis.com/proudcity/sanrafaelca2016/11/cropped-Logo_on_white-32x32.png Failed to load resource: the server responded with a status of 403 ()

@jlyon ^

**Comment by jlyon** [comment]
@kevindherman I think I found the culprit. I pushed Hotfix 1.32.5 to fix it and add some debugging info in case anything similar pops up.

Included in Hotfix 1.32.5:
- Get rid of errant setcookie() that was wiping out value
- Decrease cookie lifetime to 24 hrs
- Add debugging code.

**Comment by kevindherman** [comment]
@jlyon cool, I'll keep an eye out.

**Comment by kevindherman** [comment]
@jlyon this is happening on San Rafael again. When I click into the embedded dashboard it comes up blank.
![pastedimage](https://user-images.githubusercontent.com/6032426/27455933-0ecc98b6-576d-11e7-96f4-b556d1920bd6.png)


I've tested a handful of customers and it appears to be isolated to SR.

**Comment by kevindherman** [comment]
This is not a problem in incognito. However, I did experience it on Danvers in a normal browser this morning. 

@jlyon is there something I can do for this?

**Comment by jlyon** [comment]
@kevindherman I think this was a problem with the cookie timing out if you had been logged in to the Wordpress site for a longtime.  I push Hotfix #1025 to hopefully fix this.  If users are still having issues with the dashboard they should be able to logout of Wordpress with the link in the top-right on the embedded keyboard, re-login at my.proudcity.com and see the dashboard. It should be fixed on any new sessions from now on.  

If you are able to replicate the issue, could you right click on the page, click view source, then File Save and send it to me in Slack?

**Comment by kevindherman** [comment]
@jlyon things look good so far. I'll report back if it comes up again.

**Comment by jlyon** [comment]
@kevindherman any more reports of this?

**Comment by kevindherman** [comment]
@jlyon not recently.
