### ISSUE TITLE
Dashboard: checklist and quicklink redirect issue

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1010]
logged in as support from standard and incognito window checklist and quicklinks pull up the homepage with this URL: https://www.colma.ca.gov/?message=TheredirectURIiswrong.Yousendhttps://www.colma.ca.gov,andweexpectedhttps://colma-ca.proudcity.com

This was originally reported by Port Orchard in Zendesk and I couldn't replicate but now it appears to be platform wide.

**Comment by jlyon** [comment]
@kevindherman I fixed this on Colma.  I still had the URL as the the test site.  I updated it to the live url. Sry that slipped through the cracks.

It looks like the PO url is properly set, so not sure what was happening there. I bet they were getting a similar error, but not the exact same thing. If they report it again, can you get a screenshot?

![Screenshot (8).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560b69d9fa23ba3d0063c62a/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec05b9d665043761260ea62864c7b96aea1422515e564da4150d5612fdad8b2da6b63b77835a03e9c3714d36976345f3e5db55ea43a82a994d83bcbd8e45c7eb3e2ce58d8b473d1c1755.png)
