### ISSUE TITLE
Dashboard: marketplace link on side nav goes to blank page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1013]
The marketplace link at the top of page works in the embedded dashboard but the side nav link goes to a blank page:
![screenshot 2017-06-15 12 41 59](https://user-images.githubusercontent.com/6032426/27192249-9faf123c-51c8-11e7-9e0a-77af711cbe35.png)

![screenshot 2017-06-15 12 44 29](https://user-images.githubusercontent.com/6032426/27192250-9fb46692-51c8-11e7-9ee3-3d363addecd4.png)

**Comment by jlyon** [comment]
will be pushing this shortly.

**Comment by jlyon** [comment]
@kevindherman pushed a fix for this.  It may require a hard refresh.
