### ISSUE TITLE
WC: no preview on documents

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1022]
The document preview is down on West Carrollton on several documents that are under the file limit. This happened a few months ago and it was fixed by re selecting the file from the document library per document. I believe @aschmoe did a search and replace which solved the issue. For some reason it's cropping back up, any ideas on what's going on? Alex, could you do another search and replace for them this morning?

Before I reselected the the file:

![screenshot 2017-06-26 10 22 47](https://user-images.githubusercontent.com/6032426/27544111-24f267e8-5a5a-11e7-97b5-2062bb229c69.png)

After: https://www.westcarrollton.org/documents/article-iv/
![screenshot 2017-06-26 10 28 57](https://user-images.githubusercontent.com/6032426/27544145-4215d012-5a5a-11e7-8163-781373f5be59.png)

The steps to reselecting was:

1- edit document
2- change document file
3- select previously uploaded file
4- insert into post
5- update document
6- success

I have asked for some additional examples since this one is fixed.

**Comment by jlyon** [comment]
@kevindherman Please let me know when there is another example.  Thanks!

**Comment by jlyon** [comment]
I clicked through the docs on the first page of https://www.westcarrollton.org/documents/ and the previews were showing up for all docs.

@kevindherman let me know if this one comes up again (before you fix it), and I can do a mass search and replace to fix all instances and look into the source.

**Comment by kevindherman** [comment]
@jlyon thank you.

She's looking through the site and will post back. It might not be as rampant as the last time.
