### ISSUE TITLE
Dashboard: logout goes to error page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1027]
If logged in to my.proudcity.com and you select logout you should be directed to the main login page. Instead you get a Oops@, something went wrong message:

URL:
https://proudcity.auth0.com/v2/logout?returnTo=https%3A%2F%2Fmy.proudcity.com
![screenshot 2017-06-27 12 15 54](https://user-images.githubusercontent.com/6032426/27598167-ac1703f4-5b32-11e7-9c21-5b069d0e7f02.png)

**Comment by jlyon** [comment]
Fixed this @kevindherman
