### ISSUE TITLE
WC: user not getting all content types in dashboard

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1029]
dwessling@westcarrollton.org is a publisher on West Carrollton but when he logs in from Chrome (normal and incognito browser) these are the editing options he's limited to in the dashboard:

![image001](https://user-images.githubusercontent.com/6032426/27657206-daf0aff8-5c19-11e7-9cb7-d001a471d3e9.png)

**Comment by jlyon** [comment]
@kevindherman sorry, I fixed this last week, but forgot to post back here.  This is what I see when I login now.
![Screen Shot 2017-07-06 at 12.37.01 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560b69d9fa23ba3d0063c62a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246454f56b7191a379ed0c2856415f4fbc21254d58eeb9cb74fce36f34985619e8d7645f75cf3e19f8ed8b49be55b8268b4f82b1b58c44c4fa2137a5dad11b61435c52dcbd4f3fb29b4dc259f242e84e53ad1b3e6aee71306e0a.png)

**Comment by kevindherman** [comment]
@jlyon thanks!
