### ISSUE TITLE
Social Aggregation: edited social posts are not replaced in the app.

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1035]
From ZenDesk:

1. we have a new social media account to add: https://twitter.com/SanRafaelDPW

2. i noticed that edited posts on social media don't get updated on the social wall. the attached screen shots show two posts "Let's go retro in the parks" with a June 8 date. They were edited to say July, but that edit isn't reflected on the social wall. Is there a way to remedy this?
![screenshot 2017-07-04 at 1 28 38 pm](https://user-images.githubusercontent.com/6032426/27865744-c2353b4e-6161-11e7-895a-59c345f15677.png)

**Comment by aschmoe** [comment]
@kevindherman added the additional account, the question about edit'd social posts requires additional thought.

Going to rename this issue to track that.

**Comment by kevindherman** [comment]
@aschmoe thanks.
