### ISSUE TITLE
Feedback button bug on BETA bar in mobile

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#104]
The feedback button overlays on the bottom icon menu on mobile. Might want to just remove the 'Welcome to our future website!' on phones.

**Comment by lukefretwell** [comment]
Screenshot: 

![screen shot 2016-02-03 at 4 50 16 pm](https://cloud.githubusercontent.com/assets/1569463/12802151/975afd04-ca96-11e5-80b4-671a78e80151.png)

**Comment by aschmoe** [comment]
@luke added fix for this
