### ISSUE TITLE
Auth0 token error

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1041]

**Comment by jlyon** [comment]
@kevindherman I am not seeing an Auth0 account for maryjo.csisma@ketteringoh.org.  Perhaps she created her account with another email address (Gmail)?

She should be able to set up a new password at https://my.proudcity.com/invite/5890494c6d53977d90792ca8/6c39177de530e57a8f17238618bd354b.

**Comment by kevindherman** [comment]
@jlyon it was a cache issue that I resolved. Sorry, I forgot to update the ticket once I figured it out.

**Comment by jlyon** [comment]
Pushed as hotfix 1.34.3 as part of #1042

**Comment by kevindherman** [comment]
This error has been mentioned by a couple Kettering users this morning:

![website error](https://user-images.githubusercontent.com/6032426/28125328-4b2398aa-66f4-11e7-92b1-633a6ea3d44f.png)

**Comment by jlyon** [comment]
Pushed Hotfix 1.34.5: Change Auth0 setting sso to 0 #1041 (wp-proudicty)
