### ISSUE TITLE
Gravityforms / google storage: support multiple file upload fields

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#1046]
![screenshot of forms community services wordpress](https://user-images.githubusercontent.com/1634686/28153766-2537b8a2-675c-11e7-990d-ee841de662c4.jpg)

**Comment by aschmoe** [comment]
see #981

**Comment by jlyon** [comment]
@aschmoe or just hide this option (for now?) with css in wp-proud-admin
