### ISSUE TITLE
"Your connection was interrupted", missing files

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#1047]
@jlyon was clicking around livelifelocally.org and was getting hit with errors intermittently.  To me seemed like possibly caching issue as seemed to most consistently happen when I was getting to a new page, though refreshing also sometimes caused issue.
![screenshot from 2017-07-12 23-18-48 copy](https://user-images.githubusercontent.com/1634686/28177171-d190252e-67ae-11e7-9cf9-9018c4a4c892.png)
![screenshot from 2017-07-12 23-18-20](https://user-images.githubusercontent.com/1634686/28177175-d38a0732-67ae-11e7-9aab-9b58938ddf21.png)

**Comment by jlyon** [comment]
@aschmoe Pretty sure this was the cluster resource issues.  Moving to Blocked.  Please reopen if you see it again.

**Comment by jlyon** [comment]
closing
