### ISSUE TITLE
Contact us updates

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1049]
A while back I was playing with the demo site and started creating a list of ways we can make this better, both on the public and admin sides. Placing it here for when we can get to it.

Admin

Add contact

* Change to 'Add New Staff Member' to 'Add New Contact'

Edit contact

* change 'Staff Member' to 'Contact' in all references
* Change 'Edit Staff Member' to 'Edit Page' and use this for all pages
* add more social media links (LinkedIn, Instagram)
* remove '**Note: HTML is allowed.' text
* move Yoast to bottom

General

* change 'People' to 'Contacts'
* would use the #f1f1f1 for background on non-highlighted tabs to make them more clickable (actually, just use same color scheme as service center tabs)
* little too much white space between tab and actual boxed content below (feels a little disjointed)

People directory (table view)

* reference: https://example.proudcity.com/people?filter_categories%5B%5D=58
* Change 'Position' to 'Title'
* Department header (change pills to just text links)
* remove phone/email icons
* change 'Social' header to 'Connect'
* search box here seems out of place (would move below tabs and change input text to 'search contacts')

Widget

* Change name from 'Content list' to 'Contacts'

Individual contact page

* Reference: https://example.proudcity.com/contacts/lukefretwell/
* Remove 'Contact' link/header
* h1 on this page is bold but should adhere to same h1 style elsewhere
* Change 'Job Title' header in sidebar to 'Title'
* Change 'Social media' header in sidebar to 'Connect'
* Link phone number (good UX practice for mobile users)
* Move h1 on own line
* Move photo to left (this will eliminate requisite for a bio - if someone doesn't have a bio, then information just flows align left - in general, I think the bio is unimportant for most use cases outside of political contacts)
* bio information in right column
* categories pills (add 'Related' header and make as standards <ul><li> links
* make sidebar headers h2
* square image size, max height/width 300px

Edit Group

* move slug edit to below description

Order contact

* Change 'Order Staff' to 'Order Contacts'
* Remove 'Simple Staff List' heading
* Change 'Simply drag the staff member up or down and they will be saved in that order.' to 'Drag the contact up or down and it will be saved in that order.'
* Change 'Position' to 'Title'

**Comment by jlyon** [comment]
@lukefretwell missing contents?
