### ISSUE TITLE
Payments: Subscriptions

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1052]
- Add support to PC Dashboard
- Make necessary changes to GravityForms
- Edit SR Parking Form to allow recurring payments

**Comment by jlyon** [comment]
@kevindherman I added support for Subscriptions in the Dashboard:
- View active subscriptions
- View subscription details, including past subscription payments
- Edit subscription amount, frequency
See: https://my.proudcity.com/sites/589046fc6d53977d90792ca6/payments/subscriptions


@todo:
- Send email to Stripe re: rates (see https://trello.com/c/6i571SEI/1607-contact-matt-stripe-re-rates-and-subscriptions)
- Add `application_fee`, or something similar to WP GF

Future enhancements:
- Filter Subscriptions list page to see Overdue subscriptions, Cancelled subscriptions, etc

**Comment by kevindherman** [comment]
@jlyon this is great.

**Comment by kevindherman** [comment]
@jlyon can the edit subscription have a calendar or date picker? Right now the option is frequency and dayly, weekly or monthly, it would be great to be able to set the recurrence to a date. 

![screenshot 2017-07-17 16 27 02](https://user-images.githubusercontent.com/6032426/28289478-bf65261e-6b10-11e7-9e83-c99ab99eb9c2.png)

**Comment by jlyon** [comment]
Not really easily.  You have to use a combo of recurring monthly with a
trial period when you make the call to Stripe's api.

On Jul 17, 2017 1:56 PM, "kevindherman" <notifications@github.com> wrote:

@jlyon <https://github.com/jlyon> can the edit subscription have a calendar
or date picker? Right now the option is frequency and dayly, weekly or
monthly, it would be great to be able to set the recurrence to a date.

[image: screenshot 2017-07-17 16 27 02]
<https://user-images.githubusercontent.com/6032426/28289478-bf65261e-6b10-11e7-9e83-c99ab99eb9c2.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/proudcity/wp-proudcity/issues/1052#issuecomment-315881950>,
or mute the thread

**Comment by kevindherman** [comment]
@jlyon hmmm, maybe as a work around on the admin side they can create a trial period manually to line up the payment timing.

**Comment by jlyon** [comment]
Last remaining issue:

Plans are not getting created in the correct connect account on live images (beta and sanrafaelca).  This does seem to be working for me locally, however.

**Comment by jlyon** [comment]
Released a fix for the Plans issue:

Hotfix 1.34.6: Payments: Subscriptions #1052 (wp-proud-core, gravityformsstripe)
Hotfix 1.34.7: Payments: Subscriptions: Add plan #1052 (wp-proud-core, gravityformsstripe)
