### ISSUE TITLE
Kettering: user with editor permissions has limited access

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1053]
The user andrew.aidt@ketteringoh.org had a typo in their email so I deleted the account and created a new one using the correct email address as an editor. The new account has limited permissions even though it's setup as an editor. I was able to confirm this by logging in through auth0.

![screenshot 2017-07-18 11 01 47](https://user-images.githubusercontent.com/6032426/28324323-0df04898-6ba9-11e7-9990-268f82d367b0.png)

When you click on a content type that is not listed on left it sends you to an error page:

![screenshot 2017-07-18 11 05 19](https://user-images.githubusercontent.com/6032426/28324337-1e5e6f48-6ba9-11e7-86e1-f6d58aaa7cb1.png)

**Comment by aschmoe** [comment]
As we discussed Kevin issue was mismatched user in WordPress

**Comment by kevindherman** [comment]
@aschmoe where would I check this if it comes up again so I can handle on my own?

**Comment by aschmoe** [comment]
Go in WordPress to the list of users.
