### ISSUE TITLE
Embedded dashboard displays mysites

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1055]
@jlyon the embedded dashboard is displaying the mysites view on all the dashboard options: dashboard, analytics, marketplace and payments. 

![screenshot 2017-07-27 11 01 44](https://user-images.githubusercontent.com/6032426/28677404-6a3b6088-72bb-11e7-8eaf-6fdf01d8b4f5.png)

![screenshot 2017-07-27 11 02 01](https://user-images.githubusercontent.com/6032426/28677403-6a37f6dc-72bb-11e7-96d1-d309985f2865.png)

It's displaying correctly from my.proudcity.com so it's isolated to the embedded dashboard on all instances.

**Comment by jlyon** [comment]
I noticed this right as I was leaving last night.  I think it must be release-related. I'll take a look this morning

**Comment by jlyon** [comment]
@kevindherman deployed fix:

Hotfix 1.35.3: Embedded Dashboard showing All Sites (wp-proud-core), #1055 July 27
