### ISSUE TITLE
Sonoma: user enters credentials from my.proudcity.com and page reloads

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1057]
@jlyon The user cmartin@sonomacity.org is having issues logging into their account. From my.proudcity.com they put in their credentials, submits and the login page just reloads without logging him in. He's tried clearing his cache and incognito window. His permissions are correct and the auth0 user details say he's been logging but he's not actually able to get into the dashboard/site:

![screenshot 2017-07-27 14 46 42](https://user-images.githubusercontent.com/6032426/28686794-72412f6e-72da-11e7-97a6-c0e79a7442a2.png)

I asked for him to refresh the test site after the login page reloads and that doesn't work either. This is isolated to this specific user.

**Comment by jlyon** [comment]
@kevindherman This should be fixed now.

It looks like originally, they created an account directly in the system (Auth0), then in a future visit they decided to click the Login with Google button.  We need to figure out a better way to deal with this. I created a separate issue to track: #1060
