### ISSUE TITLE
SR Parks: popup message

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1059]
@jlyon here are the details on the SR Parks popup feature and timing:

NOTE from @jlyon in ZenDesk:
Kevin, we can set this up with https://wordpress.org/plugins/popup-maker/. I installed this on livelifelocally.org: https://www.livelifelocally.org/wp-admin/edit.php?post_type=popup. Alex can help you set it up next week.

NOTE from customer in ZenDesk:

Hi, we’re now looking at the 7th for PerfectMind to go live but before that we’d like to announce that the system is coming and then we’ll change the text to what I sent to you previously when we go live. So could you please create a Pop up that says:

NEW ONLINE REGISTRATION SYSTEM COMING ON AUGUST 7

We’re excited to offer a more user friendly and convenient online registration system to better serve you. Everyone, including existing customers, will need to create a new account to be able to register online for Fall Classes. It’s a simple and quick process. Check back here on August 7 to create your new account.

(BUTTON) More Information

Please add this link to the button

https://www.livelifelocally.org/new-online-registration-system-coming-august-7/

After August 7th, the message should be:

Welcome to our new registration system!

Our improved system makes it easier to view and register for recreational programs, classes and activities and to request facility rentals. You’ll also be able to efficiently manage your online account. Please create your new account today, even if you had one with the old system. Just click the button below or click REGISTER HERE on the website. Look for an email with your log-in details.

Create an Online Account Now (Button)

**Comment by jlyon** [comment]
Set the coming soon popup up @kevindherman.
![screen shot 2017-07-27 at 2 12 57 pm](https://user-images.githubusercontent.com/550909/28692535-d46ad38e-72d5-11e7-84e8-99be8ac12a09.png)

Once you hit close it goes away forever. If you need to see it again, open the site in an incognito window.
