### ISSUE TITLE
Topnav issues on tablet

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#107]
Looks like there's an issue with the topnav break on tablets. See images.

**Comment by lukefretwell** [comment]
![placeit 1](https://cloud.githubusercontent.com/assets/1569463/12802820/69a3c158-ca9a-11e5-847d-c5468cebfa72.jpg)
![placeit 2](https://cloud.githubusercontent.com/assets/1569463/12802819/69a3907a-ca9a-11e5-8102-be8ba5213aa8.jpg)

**Comment by jlyon** [comment]
Hmm, Seems like a combination of the logo and adding a couple items to the topnav are causing probs.  Let's discuss on the huddle tom

**Comment by lukefretwell** [comment]
Suggestions:

* turn text nav into hamburger right of search icon on tablet and smaller
* for tablet, keep on right/topnav
* for mobile, move to left/bottomnav
* in general, think icons should all be together - confusing when they're separated and all are equally important

**Comment by jlyon** [comment]
Alex made a lot of changes to navbar functionality on mobile/tablet.  @lukefretwell thoughts?
