### ISSUE TITLE
SR Employees: table option in wysiwyg broken

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1070]
From ZenDesk:

I am working in the page linked below and when I select the 'tables' button it usually has a drop down option but nothing is appearing. I will say when I click the tables button the arrow changes from upside down to rightside up. Not much to show in a screen shot, but here are two shots of the arrows moving.

https://employees.cityofsanrafael.org/common-inquiries/

![capture](https://user-images.githubusercontent.com/6032426/29177076-b5210980-7dbb-11e7-9f78-3cade8ca784f.JPG)
![capture1](https://user-images.githubusercontent.com/6032426/29177075-b51d1e60-7dbb-11e7-9f36-a80943e15f7c.JPG)

When you select the table option it toggles between the up and down carrot as shown above ^

**Comment by kevindherman** [comment]
@jlyon @aschmoe this actually appears to be any WYWIWYG option that has that toggle feature: paragraph and color included.

**Comment by aschmoe** [comment]
@kevindherman @jlyon 

looks like this plugin https://wordpress.org/plugins/mce-table-buttons/#reviews hasn't worked since 4.8 and 

> Last updated: 3 years ago

**Comment by jlyon** [comment]
It actually looks like this issue is fixed in the release.  I added it to the release checklist so we can double-check after we push.

For the font color, it looks like you have to click on the arrow. Just clicking on the button doesn't do anything (this seems like it's an issue with WP Core).

**Comment by jlyon** [comment]
Verified that this is now fixed on SR Employees post-launch @kevindherman.
