### ISSUE TITLE
JS err in proud-accessibility.js breaking service center embedded form

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1081]
@jlyon @aschmoe 

Service Center forms on mobile and desktop, such as report an issue, don't go to a confirmation after submitting. The app loads but stays on the form that was filled out.

Example on Kettering report an issue (graffiti):
https://www.ketteringoh.org/#/city/report/embed/report-graffiti
![screenshot 2017-08-14 12 56 15](https://user-images.githubusercontent.com/6032426/29282210-ff75c124-80ef-11e7-8234-fd1deedce86c.png)

This is after submitting. The entry gets submitted and is in the forms dashboard so it's just a front-end user experience issue:
https://www.ketteringoh.org/wp-admin/admin.php?page=gf_entries&id=48

**Comment by jlyon** [comment]
JS err:

```
Uncaught TypeError: Cannot read property 'media' of undefined
```

It's because `window.wp` doesn't exist in this line:
```
;(function($, Proud) {
    $(document).ready(function() {
        if (window.wp.media && window.wp.media.view && window.wp.media.view.Button) {
      
    });
}
```

**Comment by jlyon** [comment]
Pushed as - Hotfix 1.36.2: JS err in proud-accessibility.js breaking service center embedded form #1081 (wp-proud-core), Aug 14

This may require a hard refresh (Shift+refresh) @kevindherman

**Comment by kevindherman** [comment]
@jlyon roger that.
