### ISSUE TITLE
Lucas: search+document search

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1082]
@aschmoe @jlyon I got this message from the contact at Lucas that approved the search+documents upgrade. I tested the search and didn't get any results either. 

Related, should the keyword search on this page search pdf's as well? https://www.lucastexas.us/agendas-minutes/

Their structure is much different than other customers so I wonder if that's creating unanticipated issues.

From email: 

Kevin,
 
I’ve been doing some tests on the City of Lucas website from the homepage and the minutes and Agenda page and I’m not coming up with any hits.  I’m using words that I know are in the minutes as well as on the agenda.  Below is an example of what I’m doing.
 
Keep Texas Beautiful is used frequently on our Parks and Open Space Board Agenda and Minutes and its not retrieving any information on my search.   

![image001](https://user-images.githubusercontent.com/6032426/29287539-cb793540-8103-11e7-8d9b-8d8c651f70d3.jpg)

**Comment by aschmoe** [comment]
@kevindherman looks like the whole search cluster went down with a corrupted server that recently fell apart.

We restarted everything, so issue should be resolved.

**Comment by aschmoe** [comment]
@kevindherman additionally looks like that search term doesn't actual exist in there

https://www.lucastexas.us/agendas-minutes?filter_keyword=Winningkoff

for instance has results, but not Beautiful

See https://github.com/proudcity/wp-proudcity/issues/1086 for additional issues
