### ISSUE TITLE
SR Employees: permanently deleted content showing up on google

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1083]
This contact on the SR Employees site was permanently deleted but still showing up on google searches. About how long should google continue to yield the deleted page in their results when you search his name?

![screenshot 2017-08-14 16 41 44](https://user-images.githubusercontent.com/6032426/29292066-bb335944-8113-11e7-8078-bc993ce8e8c6.png)

**Comment by jlyon** [comment]
@kevindherman This is on Google, and they don't give any firm timeline, but it is typically within two weeks.

Within their webmaster tools, you can temporarily (for 6 mos) exclude specific urls.  I just submitted this url on https://www.google.com/webmasters/tools/url-removal?hl=en&siteUrl=https://www.cityofsanrafael.org/ (I just shared access w you):
![screenshot 61](https://user-images.githubusercontent.com/550909/29302797-0f177270-813c-11e7-98a9-3fd909064b5b.png)

**Comment by kevindherman** [comment]
@jlyon thank you. This can be closed.
