### ISSUE TITLE
Document list incorrectly showing no content

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1088]
from Zendesk:

"Hi Kevin:
 
Documents are not showing up for a bunch of our pages.  For example: https://www.danversma.gov/budget-documents/ and https://www.danversma.gov/by-laws-and-forms/.  Can you check into it?
 
Thank you."

I checked and the document is added correctly: https://www.danversma.gov/documents/zoning-by-laws/ and the category shows that it has 1 (this document) assigned to it. However, on the page where the document list is embedded it is not displaying:

https://www.danversma.gov/by-laws-and-forms/

![screenshot 2017-08-15 15 32 51](https://user-images.githubusercontent.com/6032426/29332727-0748db86-81cf-11e7-81c3-5ceafed89184.png)

![screenshot 2017-08-15 15 30 24](https://user-images.githubusercontent.com/6032426/29332698-ec19b4a2-81ce-11e7-94a1-45df0c5d2cea.png)

The same issue is happening on this page: https://www.danversma.gov/budget-documents/

**Comment by kevindherman** [comment]
@jlyon @aschmoe this appears to be document list widgets platformwide:

https://www.cityofsanrafael.org/documents

![screenshot 2017-08-15 17 01 37](https://user-images.githubusercontent.com/6032426/29336351-79d419de-81db-11e7-9f9b-d17d7131aef5.png)

**Comment by aschmoe** [comment]
@kevindherman I fixed these last night... I think 2 of the indexes something just got corrupted when everything was failing.
