### ISSUE TITLE
Google translate

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#109]
When you click select a language the list opens and then the entire Google Translate box closes before you can select an option. 

This is happening on a pages.

**Comment by jlyon** [comment]
@kevindherman  Is this still happening for you on https://west-carrollton-oh.proudcity.com? Alex and I both can't replicate it

**Comment by jlyon** [comment]
closes w you click on select
chrome 48.0 mac (kevin)

**Comment by aschmoe** [comment]
@kevin fixed this

**Comment by kevindherman** [comment]
Thank you.

On Thu, Feb 4, 2016 at 6:15 PM, Alex Schmoe <notifications@github.com>
wrote:

> @kevindherman <https://github.com/kevindherman> fixed this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/109#issuecomment-180097755>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
