### ISSUE TITLE
Payments: Download payout report error

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1090]
When selecting the save report icon on the payout detail page the icon turns into arrows and continues to spin without downloading the CSV of the payout detail.

![screenshot 2017-08-17 14 34 53](https://user-images.githubusercontent.com/6032426/29427961-796a32d8-8359-11e7-9804-772a1ab1df31.png)

This is happening from the dashboard: https://my.proudcity.com/sites/589046176d53977d90792ca5/payments/payouts/po_1AqaScLkSimjtHmxUCL842nJ

**Comment by jlyon** [comment]
Fixed this bug, Kevin.
