### ISSUE TITLE
PO: ability to order (alphabetize) within document list widget

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1091]
It would be nice to be able to select an alphabetize check box within the document list widget interface. Currently you have to alphabetize manually using drag and drop but as a city has 100s of documents, alphabetizing for a specific document list widget can be tedious to find and reorder documents that could be very far apart once found. 

Not critical but a nice to have. 

Note to self, this came up with Port Orchard and should be communicated with them if added in a future release.

**Comment by jlyon** [comment]
@aschmoe this was part of your work with #1097 right?

**Comment by aschmoe** [comment]
@jlyon correct
