### ISSUE TITLE
Increase max file upload size (as addon)

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1096]
"I know you said we can’t put anything up over 100MB.  Is there any way to stretch that to maybe 105MB?  I have a 100.3MB plan set/bid docs I’d like to post on the site.  I understand if not, but thought I’d ask.”

**Comment by kevindherman** [comment]
@jlyon this can be isolated to Colma if easier and better for the servers.

**Comment by jlyon** [comment]
@kevindherman I might see if I can isolate it to a specific city so it could be an addon in the future.  it doesn't really matter, except for file storage costs for us, and increased support for file upload issues.

**Comment by jlyon** [comment]
Try to keep it isolated to Colma

**Comment by jlyon** [comment]
Adding `$UPLOAD_MAX_FILESIZE` env var that will default to `100M`. https://github.com/proudcity/wp-proudcity/commit/d90e767aa22d12ed2015a38e1762576918d239b8

**Comment by jlyon** [comment]
@kevindherman I verified the Colma now has a max filesize for uploads of 200 mb.
