### ISSUE TITLE
Add mailchimp to footer

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#11]
- [x] Need account info
- [ ] Load in WC contacts

**Comment by jlyon** [comment]
@kevindherman I added this to the green actions bar.  There wasn't space for additional fields (first/last name), so I just made it the email.  

It's set to require opt-in confirmation.  The email that gets sent is from Erica Mattingly, so we should prob change that too.

**Comment by kevindherman** [comment]
@jlyon I'm meeting with Erika at 11pst today. Can we spend a few minutes after our huddle on this?

**Comment by kevindherman** [comment]
created a Website Subscription list to collect these signups.

**Comment by kevindherman** [comment]
@jlyon  The submit button overlaps the email field. 

![screenshot 2016-02-08 14 07 00](https://cloud.githubusercontent.com/assets/6032426/12896606/d517b064-ce70-11e5-8e7f-32895a24b95f.png)

**Comment by lukefretwell** [comment]
Is this going to be a widget area? 

If not, let's add to the footer footer in one of the columns like we have on PC website.

**Comment by jlyon** [comment]
fixed this earlier this morn

**Comment by lukefretwell** [comment]
@jlyon can we change to:

* change 'Get updates' to 'Updates'
* change 'Enter email' to 'email'
* add space between 'Updates' and text field?
