### ISSUE TITLE
Kiosk setup

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1101]
@kevindherman  I started setting this up. The tablet they got is pretty nice (nice big screen), and I think it should work well.  I bought a lockdown app and I think we should spring for the remote monitoring ($1.60/mo) because it will save me a bunch of debugging hassle and will help us scale the kiosk in the future. Thoughts?

Purchased
- $8, one-time https://www.android-kiosk.com/#!

Want to purchase
- $1.60/mo https://www.kbremote.net/Home/Start

**Comment by kevindherman** [comment]
@jlyon seems reasonable if needed. Go ahead and purchase.
