### ISSUE TITLE
Large file uploads: Running out of memory

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1102]
Colma had this with files that were 72mb they were trying to upload that were running out of memory, even with max memory at 250mb.  I upped it to 500mb and it worked.

@aschmoe: Is there any document elasticsearch stuff that could be causing this, or is it just because the filez are huuuge?
```
[Fri Aug 25 21:37:22.213557 2017] [:error] [pid 41] [client 10.24.5.10:49076] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 98901144 bytes) in /app/wordpress/wp-content/plugins/wp-stateless/lib/Google/src/Google/Http/MediaFileUpload.php on line 245, referer: https://www.colma.ca.gov/wp-admin/media-new.php
```

@kevindherman I think maybe we should drop the default max filesize down to 50m (or something we test that works with our default memory allotment), and then offer larger file uploads as an addon. Thoughts?

**Comment by jlyon** [comment]
https://github.com/proudcity/wp-proudcity/issues/956
https://github.com/proudcity/wp-proudcity/issues/1109

**Comment by aschmoe** [comment]
@jlyon cutoff is 20 mb for the elastic stuff ... I can retest this to make sure.
