### ISSUE TITLE
my sites page: 503 error when selecting "view site option"

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1105]
Steps:

1. Login to my.proudcity.com
2. Select view site for Rio Blanco County
3. Get 503 error: https://rio-blanco-county.proudcity.com/index.php?auth0=1&error=access_denied&error_description=%7B%22statusCode%22%3A503%2C%22error%22%3A%22Service%20Unavailable%22%2C%22message%22%3A%22Failed%20to%20perform%20search.%22%7D&state=https%3A%2F%2Frio-blanco-county.proudcity.com%2F
![screenshot 2017-08-30 10 52 38](https://user-images.githubusercontent.com/6032426/29878908-b11e2d52-8d71-11e7-8482-ae8f76ab28c3.png)
4. If I select dashboard and then click the site link in the top right I get in

Notes:
- When I first login the my sites url is https://my.proudcity.com/sites?login=true instead of /sites and 
I noticed this happening when I first login and craete nsite and new site admin options aren't available
![screenshot 2017-08-30 10 58 39](https://user-images.githubusercontent.com/6032426/29879129-36b6e33c-8d72-11e7-9d38-4396c22cc0d4.png)
- if I click into the dashboard for any of the sites and then select mysites in the nav I am directed to /sites and everything works correctly, including the 503 issue mentioned above.
- @jlyon this isn't pressing because I found a work around but I'm not sure if a customer could have the same issue. Might just be a login redirect thing.

**Comment by jlyon** [comment]
@kevindherman I wasn't able to replicate this in a normal window or in incognito.  Are you still having issues?

**Comment by kevindherman** [comment]
@jlyon I'll just keep an eye on it. It's inconsistent and I have a work around.
