### ISSUE TITLE
Sonoma: large file upload error

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1109]
When uploading large files, about 50mb, through the media library I get a http error.

1- https://sonoma-ca.proudcity.com/wp-admin/upload.php
2- Select files
3- Loads
4- Get this http error:
![screenshot 2017-09-07 11 28 50](https://user-images.githubusercontent.com/6032426/30171538-48c1a6d0-93c0-11e7-8dbc-2f27aecbb109.png)
5- the file does appear in the media library though: https://sonoma-ca.proudcity.com/wp-admin/upload.php?item=5580
![screenshot 2017-09-07 11 29 04](https://user-images.githubusercontent.com/6032426/30171560-5b0cc036-93c0-11e7-8699-f2150b8a2583.png)
6- And I was able to use the file in a doc:
https://sonoma-ca.proudcity.com/documents/example-brazil-doc/
The preview is disabled in the doc since it's over 20MB.

Still, the http error is misleading.

**Comment by jlyon** [comment]
Large uploads should be done from the *Add New* page https://sonoma-ca.proudcity.com/wp-admin/media-new.php.  Can you send me the file via yousendit and i will test it.  It is likely https://github.com/proudcity/wp-proudcity/issues/1102

**Comment by jlyon** [comment]
nvm, I have the file.  I'll do some testing
