### ISSUE TITLE
Pull updates into Weston, Topeka & Example

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#111]
- [x] icons: https://example.proudcity.com/residents/#/city/answers, https://example.proudcity.com/businesses/#/city/answers, https://example.proudcity.com/visitors/
- [x] update agency header imgs
- [x] footer contact info

**Comment by jlyon** [comment]
@lukefretwell @kevindherman I updated https://topeka-ks.proudcity.com/ and https://weston-wi.proudcity.com/ with all of the latest functionality and IA from the example site (and the city-ia readme: https://github.com/proudcity/city-ia/). Updated the branding too.

**Comment by kevindherman** [comment]
Awesome. Meeting with Weston today and owe Topeka a phone call.

On Thu, Feb 11, 2016 at 2:08 AM, Jeff Lyon <notifications@github.com> wrote:

> @lukefretwell <https://github.com/lukefretwell> @kevindherman
> <https://github.com/kevindherman> I updated
> https://topeka-ks.proudcity.com/ and https://weston-wi.proudcity.com/
> with all of the latest functionality and IA from the example site (and the
> city-ia readme: https://github.com/proudcity/city-ia/). Updated the
> branding too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/111#issuecomment-182741709>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
