### ISSUE TITLE
Sonoma: blank issue

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1113]
There is one blank issue on Sonoma's service center: https://sonoma-ca.proudcity.com/#/city/report
![screenshot 2017-09-11 12 18 12](https://user-images.githubusercontent.com/6032426/30285237-78396870-96eb-11e7-803c-39d42280d4dd.png)

@jlyon @aschmoe do you know what's going on here?

**Comment by jlyon** [comment]
@kevindherman I think this is because the Type is empty on https://sonoma-ca.proudcity.com/wp-admin/post.php?post=5569&action=edit

![screenshot 42](https://user-images.githubusercontent.com/550909/30287348-4fc6a66a-96ea-11e7-8a9d-8070b8ab4ab9.png)

**Comment by kevindherman** [comment]
@jlyon yup, that solved it.
