### ISSUE TITLE
Improve, add additional alert bar colors

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1114]
How are the alert bar colors set? Port Orchard is set to the danger alert (red) and it's displaying as a pink.

![screenshot 2017-09-13 11 08 16](https://user-images.githubusercontent.com/6032426/30385109-1f2b5ace-9874-11e7-9ec2-096ef0633607.png)
![screenshot 2017-09-13 11 08 22](https://user-images.githubusercontent.com/6032426/30385105-1de8e6ae-9874-11e7-8aef-d3a3a054e55f.png)

**Comment by jlyon** [comment]
@kevindherman I think this is just a part of the theme, but I have been thinking (pretty much every time I see these) that they don't look great.  Should we tweak the colors @aschmoe ?  Maybe use the same shite as https://polaris.shopify.com/visuals/colors?

**Comment by kevindherman** [comment]
@jlyon @aschmoeThis feature is becoming more popular, I think your suggestion would be helpful.

**Comment by jlyon** [comment]
@kevindherman Do you think we should
a) just change the colors
b) change + add more colors
c) change + add more colors + give a "custom color" option

Maybe just start with a or b for now?

**Comment by kevindherman** [comment]
@jlyon I think B for now.
