### ISSUE TITLE
event detail doesn't display end time

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1115]
https://www.cityofsanrafael.org/event/city-council-meeting-2-2017-09-18/
![screenshot 2017-09-14 10 55 39](https://user-images.githubusercontent.com/6032426/30436904-4bc4583e-993b-11e7-8944-e1c9c0bfa114.png)

**Comment by jlyon** [comment]
@aschmoe you wanna look at this one?
