### ISSUE TITLE
Disabling full screen map doesn't work

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1116]
" Regarding the map:  I changed to the WordPress style and fixed my problem (I deleted the locations and location layers which prevented the map from rendering at all), but I still can't disable the "Render map with fullscreen options?" checkbox.  In fact, I think this is a bug because as soon as I save the page changes and edit the widget again the checkbox remains checked...  it's like the option is not being committed to the database."

https://goodrich-wi.proudcity.com/wp-admin/post.php?post=3186&action=edit
![screenshot 2017-09-18 10 18 14](https://user-images.githubusercontent.com/6032426/30546543-e2c2d8ba-9c5a-11e7-948e-7b87e82a56b8.png)

This is with the homepage services map. If you go in and uncheck the full screen checkbox, update the page and then reopen the widget the checkbox is selected.

**Comment by jlyon** [comment]
@aschmoe I fixed the issue with the value not saving.  Unchecking this box seems to hide the mouse icon, but the full-screen button still appears in the top-right:

**Comment by aschmoe** [comment]
This is actually coming from google, looking into how to disabled

**Comment by aschmoe** [comment]
This is going live.
