### ISSUE TITLE
Goodrich: editor permission not able to add users

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1117]
@jlyon @aschmoe the editor permission level should be able to add users, right? The user for Goodrich isn't able to add users:

![dashboard](https://user-images.githubusercontent.com/6032426/30546730-642338b4-9c5b-11e7-94a3-61fd97b3247c.jpg)

Is this a bug or am I confusing the editor with admin permissions?

**Comment by jlyon** [comment]
@kevindherman Fixed this.  They need to be admins to add users.
