### ISSUE TITLE
Sonoma: my services city hall hours

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1120]
@jlyon I'm setting the City Hall hours for Sonoma and they have a funky situation that's throwing off the my services hours. Essentially they close for an hour at noon for lunch which messes with the opening soon message. 

I've set it up to like this 
https://sonoma-ca.proudcity.com/wp-admin/admin.php?page=service-center-settings
![screenshot 2017-09-21 11 46 11](https://user-images.githubusercontent.com/6032426/30705206-d606c7de-9ec2-11e7-8923-f810f8c43180.png)

![screenshot 2017-09-21 11 45 20](https://user-images.githubusercontent.com/6032426/30705242-e46276ca-9ec2-11e7-89e4-0e089afeff72.png)

The opening soon message gets confused during that lunch hour. What do you think the best option for this situation? Could you just disable the opening soon message so it's either open or closed?

**Comment by kevindherman** [comment]
@jlyon do you think it's possible to have a solution by Thursday?

**Comment by jlyon** [comment]
@kevindherman yes, I think it will just be an on/off toggle probably though.

**Comment by kevindherman** [comment]
@jlyon cool, that works. I was just hoping for even a band-aid ahead of the beta.

**Comment by jlyon** [comment]
@kevindherman I fixed the handling for multiple hours on the same day, so this should now be working on Sonoma.

I also added a "Disable currently" checkbox to `/wp-admin/admin.php?page=service-center-settings` so you can disable this completely:
![screenshot 96](https://user-images.githubusercontent.com/550909/31257066-4817bad0-a9eb-11e7-9be0-87af2dda4ed8.png)
