### ISSUE TITLE
Determine working PHP_MEMORY_LIMIT and  UPLOAD_MAX_FILESIZE values

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1123]
Addon from #1122

Should be a solution for #1109

We need to do some testing with large files to find the sweet spot for PHP_MEMORY_LIMIT and UPLOAD_MAX_FILESIZE values that won't throw errors.

Once this is done, we should probably manually update the cities that we know like uploading huge files.  How does this list look, @kevindherman ?

- [ ] Sonoma: set max upload to 50mb
- [ ] SR: set max upload to 50mb
- [ ] PO: set max upload to 50mb
- [ ] Lucas: set max upload to 50mb

**Comment by jlyon** [comment]
@kevindherman do we want to try to do this in the next release?

**Comment by kevindherman** [comment]
@jlyon yeah. I think it's best to do with some communication planning, so next release would be wise since I just got back.

**Comment by jlyon** [comment]
sounds good

**Comment by jlyon** [comment]
Limits:
- 25M File preview
- 25M Search document index limit @aschmoe release
- 25M file uploads @jlyon release

If you occasionally need to upload large files, contact us and we can increase your file upload limit. We cannot increase the File preview or Search document index limit size.  

Settings to Kettering:
PHP_MEMORY_LIMIT: 300M
UPLOAD_MAX_FILESIZE: 150M

@kevindherman update documentation https://proudcity.zendesk.com/hc/en-us/articles/115002205974-File-Size-Guide

**Comment by jlyon** [comment]
2 possibilities i think

A. Default
25M File preview
25M Search document index limit 
25M file uploads 

B. Customer requests big uploads
25M File preview
25M Search document index limit 
100M file uploads - in this case, we set PHP_MEMORY_LIMIT: 300M, UPLOAD_MAX_FILESIZE: 100M

**Comment by jlyon** [comment]
@kevindherman the max filesize limit of 25mb was already in place.  We also included this communication in these release notes: https://github.com/proudcity/wp-proudcity/releases/tag/1.39.0.

Given this, I will not include this language in the release notes unless you feel strongly otherwise @kevindherman.

Should increase the limits for these cities (see first comment), or let them contact us?

**Comment by kevindherman** [comment]
@jlyon if it won't mess things up I would increase the limits just for those cities.

**Comment by kevindherman** [comment]
@jlyon dope.

**Comment by jlyon** [comment]
Related #1254

**Comment by jlyon** [comment]
this is pretty much done i think
