### ISSUE TITLE
back to News list button

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#113]
Add button from a news item linking back to full news list.

**Comment by jlyon** [comment]
I think we're good here with the list of recent events and the All events link #115.  Thoughts @kevindherman?

**Comment by kevindherman** [comment]
I think so too.

On Fri, Feb 5, 2016 at 5:47 PM, Jeff Lyon <notifications@github.com> wrote:

> I think we're good here with the list of recent events and the All events
> link #115 <https://github.com/proudcity/wp-proudcity/issues/115>.
> Thoughts @kevindherman <https://github.com/kevindherman>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/113#issuecomment-180607997>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
