### ISSUE TITLE
PO:  drag and drop feature for documents not working on older documents

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1137]
The drag and drop feature works for recent documents, about 100 most recent documents.

https://www.cityofportorchard.us/wp-admin/edit.php?s=resolution&post_status=all&post_type=document&action=-1&m=0&seo_filter&action2=-1&mode=list

However, the first 100-ish created, around "020-16" and earlier, the drag and drop doesn't work. You can drag the file but it doesn't actually drop into place. I tried changing the screen option to a lower number and that worked about halfway but getting into older documents the same issue with dropping came up.

**Comment by jlyon** [comment]
@kevindherman yeah i think the drag and drop is not the best for the documents list.  It's better for lists with smaller items (the service center ones).  Would it be possible to change the documents to be desc by published date for PO, or would that really mess things up?

**Comment by kevindherman** [comment]
@jlyon hold off for now. I'll reach out and see what's best.

**Comment by jlyon** [comment]
@kevindherman sounds good.

**Comment by jlyon** [comment]
@kevindherman any update?

**Comment by kevindherman** [comment]
@jlyon just leave for now. Apparently it works in FF for one of their admins and they're fine with doing it that way. Let's keep in the backlog since I'm assuming it will eventually come up.
