### ISSUE TITLE
Issues logging in from /wp-admin and with accounts that are both u/p AND Google

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1139]
There have been issues logging in from /wp-admin, and also with users who have logged in in the past with both a username/password AND with Google.

**Comment by jlyon** [comment]
@kevindherman all Auth0-related issues _should_ now be fixed.

**Comment by jlyon** [comment]
@kevindherman actually looks like maybe not. needs more testing.

**Comment by kevindherman** [comment]
@jlyon ok. Apparently the SR one from yesterday wasn't using google accounts but perhaps he just didn't remember from setting up a long time ago.

**Comment by jlyon** [comment]
@kevindherman That SR one did have Google Accounts on it (I can see from the Auth0 end)

**Comment by jlyon** [comment]
After looking into this more, it appears to be a proxy headers issue with the nginx 
ingress controller https://stackoverflow.com/questions/40289225/kubernetes-nginx-ingress-controller-returns-502-but-only-for-ajax-xmlhttprequest.

From https://github.com/kubernetes/ingress-nginx/blob/master/configuration.md:
```
ssl-buffer-size: Sets the size of the SSL buffer used for sending data. The default of 4k helps NGINX to improve TLS Time To First Byte (TTTFB). https://www.igvita.com/2013/12/16/optimizing-nginx-tls-time-to-first-byte/
```

I tried adding the following annotations:
```
    annotations:
      ingress.kubernetes.io/proxy-buffer-size: 16k
      ingress.kubernetes.io/ssl-buffer-size: 16k
```
This didn't fix it, though.  I think we need to alter the ConfigMap instead of using annotations: https://github.com/kubernetes/ingress-nginx/blob/master/configuration.md#allowed-parameters-in-configuration-configmap

I'll keep looking into this over the next couple days.

**Comment by jlyon** [comment]
Configmap example (this is really hard to find because links are broken): https://github.com/kubernetes/ingress-nginx/blob/master/examples/customization/custom-configuration/nginx-custom-configuration.yaml

**Comment by jlyon** [comment]
@kevindherman these issues with Auth0 should now be fixed.  There were issues with Auth0 returning too many headers for our nginx proxy to handle.  The nginx-controller we use has this set to 4kb, where the nginx default is 16k.  I bumped it up to 8k by configuring a ConfigMap, and the previous issues logging in from /wp-admin is now fixed.  I also assume that issues related to users having both a Google-connected account and u/p are also fixed.

Please let me know if there are any more reports of issues.

ConfigMap and nginx-controller deployment are in `proudcity/proudcity-kubernetes/nginx-ingress.yml`
