### ISSUE TITLE
Back to documen￼ GA click tracking
￼ Redirect when you go to https://west-carrollton-oh.proudcity.com/city/answers/jobs/?
￼ Redirect w you go to city/answers/jobs/what-benefits-does-the-city-offer?
￼ Redirect + formatting w you go to https://west-carrollton-oh.proudcity.com/question/what-benefits-does-the-city-offer/
￼ https://west-carrollton-oh.proudcity.com/city/payments/court-payments
￼ Do we need to do anything for JS app in google? (my thought=no)
@aschmoe, let's discuss today or tom
ts button on widget list docs

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#114]
@jeffreymlyon @alexschmoe If you go to a page that is using the content list widget like City Council Agendas and click on a doc the "back to documents" button on the specified doc page, it brings you back back to /documents and not the widget list.

For example:

Start at: 
https://west-carrollton-oh.proudcity.com/city-council-agendas/

and select https://west-carrollton-oh.proudcity.com/documents/january-12-2016-city-council-agenda/

Click back to documents and you are taken to https://west-carrollton-oh.proudcity.com/documents/ 
instead of /city-council-agendas/

**Comment by jlyon** [comment]
I made this button the same as clicking the browser Back button.  I feel like this might break in some instances (the only one I can think of is if you did a google search for the document and hit the back button, you would go back to the search results pg rather than /documents), so let's keep an eye on it.

**Comment by kevindherman** [comment]
Sounds good.

They will be utilizing the list widgets for jobs and news as well on
department pages, can you set up the back button for those lists widgets as
well?

On Thu, Feb 4, 2016 at 4:12 PM, Jeff Lyon <notifications@github.com> wrote:

> I made this button the same as clicking the browser Back button. I feel
> like this might break in some instances (the only one I can think of is if
> you did a google search for the document and hit the back button, you would
> go back to the search results pg rather than /documents), so let's keep an
> eye on it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/114#issuecomment-180052236>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by jlyon** [comment]
it will always go back to the previous page, so we should be set for jobs and news

**Comment by kevindherman** [comment]
Perfect, thank you.

On Thu, Feb 4, 2016 at 7:08 PM, Jeff Lyon <notifications@github.com> wrote:

> it will always go back to the previous page, so we should be set for jobs
> and news
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/114#issuecomment-180114002>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
