### ISSUE TITLE
Remove unnecessary items from HEAD

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#1142]
Site improve revealed we had broken shortlink meta items on every page.  There were additional items we can drop

**Comment by aschmoe** [comment]
@kevindherman only possible issue I can think of with this fix is I'm removing the wordpress emoji styles/scripts ... you think any sites are using emojis ?

**Comment by kevindherman** [comment]
@aschmoe peace out to the emojis.
