### ISSUE TITLE
Increase test site file upload maxsize

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1146]
@jlyon I'm getting an error when uploading this PDF file that is less than 5MB onto the Sherman site:

Here's the document I'm trying to add the file to: https://sherman-county-or.proudcity.com/documents/2017-sherman-county-budget/

Screenshot of http error:
![screenshot 2017-10-16 11 01 20](https://user-images.githubusercontent.com/6032426/31619008-7a83e484-b261-11e7-8159-fc05677d0b46.png)

File:
[Sherman County 2016 17 Budget.pdf](https://github.com/proudcity/wp-proudcity/files/1387919/Sherman.County.2016.17.Budget.pdf)

**Comment by jlyon** [comment]
@kevindherman This should be fixed. Sherman County is still on our Test infrastructure, and we had a limit of 2mb for file uploads there (with some of the server settings).  I increased that to match our prod servers. I will migrate them over to our prod soon.

**Comment by kevindherman** [comment]
@jlyon thanks. I just added the file without a problem.
