### ISSUE TITLE
Post date format for documents (add comma)

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1147]
There should be a comma between the day and year in the post date. Can this be added to the formatting platform-wide?

https://sherman-county-or.proudcity.com/documents/sherman-transit-program-policy/
![screenshot 2017-10-16 12 52 34](https://user-images.githubusercontent.com/6032426/31624573-280ab5b0-b271-11e7-8a24-82ee07bf4840.png)

**Comment by jlyon** [comment]
This will be in the next release @kevindherman. They are already formatted this way on /documents.

**Comment by kevindherman** [comment]
@jlyon I noticed the comma is in the wrong place.

![screenshot 2017-11-03 07 13 18](https://user-images.githubusercontent.com/6032426/32371250-8f4c4ad8-c066-11e7-9202-eac77399e039.png)

It should be be after the day.
