### ISSUE TITLE
Sonoma: page doesn't have background theme like the rest of the site

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1148]
This page isn't displaying the background image color like the rest of the site's theme:

https://sonoma-ca.proudcity.com/fire-recovery/

![screenshot 2017-10-16 23 17 31](https://user-images.githubusercontent.com/6032426/31645122-4369e1e4-b2c8-11e7-82b2-0542cb38df6f.png)

**Comment by jlyon** [comment]
@kevindherman looks like you got it.

**Comment by aschmoe** [comment]
@kevindherman that page is getting misclassified as a "full width" page for some reason.

I've made it into multiple rows which triggers the homepage style multiple white backgrounds.  Renaming to capture issue

**Comment by aschmoe** [comment]
Note see as counterpoint https://sonoma-ca.proudcity.com/government/ which gets styled into normal container appropriately.

**Comment by jlyon** [comment]
Can this be moved to ready @aschmoe ?
