### ISSUE TITLE
add ESRI map to another page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#115]
@jeffreymlyon can you embed the ESRI map to this Planning & Building Dept page: https://west-carrollton-oh.proudcity.com/codes/

**Comment by jlyon** [comment]
Added this.  You/they can do this in the future by editing /residents, clicking on the Text panel, copying the HTML code and pasting into a new text panel on the new page (https://west-carrollton-oh.proudcity.com/codes/).

This would prob be a good howto video for the future.
