### ISSUE TITLE
Manteo Test: https error

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1150]
@jlyon getting a not secure error for the Manteo test site. The site name didn't immediately populate when I created the test site (I added manually) so I'm thinking it might be related to that. 

https://manteo-nc.proudcity.com/

![screenshot 2017-10-19 09 37 57](https://user-images.githubusercontent.com/6032426/31774506-f6507600-b4b3-11e7-9434-4195f0f0057c.png)

**Comment by kevindherman** [comment]
@jlyon can this be a release item?

**Comment by jlyon** [comment]
@kevindherman Sorry, I think I overwrote this setting with some of the sonoma strong renaming. This is back up on https://manteo-nc.proudcity.com/
