### ISSUE TITLE
Sonoma County Recovers: site name question

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1151]
@jlyon is the admin panel the right place to make sure the sitename is consistent everywhere? I think the name is going to change again so I want to be able to scrub the old ones successfully when the time comes.

![screenshot 2017-10-19 10 12 54](https://user-images.githubusercontent.com/6032426/31775319-41546d30-b4b6-11e7-9eab-60044bd3764d.png)

**Comment by jlyon** [comment]
Currently:

- Editing Name here will update it in the dashboard.
- You will also need to edit the sitename withing WP Settings
