### ISSUE TITLE
Allow change "department" to "agency" on contact

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1152]
@jlyon is it possible to change "department" to "agency" for contacts:

https://sonomacountyrecovers.proudcity.com/get-help/

![screenshot 2017-10-19 11 35 43](https://user-images.githubusercontent.com/6032426/31779709-c3022b0a-b4c1-11e7-808f-e5c6e94866ea.png)

**Comment by jlyon** [comment]
I took care of this @kevindherman

**Comment by kevindherman** [comment]
@jlyon could you do a swearch and replace for departments that were created before the agency switch so that they have the correct URL path? They're getting some broken links.

If setting up redirects is the best/easiest I can set that up.

**Comment by jlyon** [comment]
@kevindherman I ran this search and replace. If they are still hvaing issues, can you post an example URL and I'll look into it?
