### ISSUE TITLE
Menu edit page: Hide Display Location

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1154]
Accidentally checking has pretty large consequences

https://www.cityofsanrafael.org/wp-admin/nav-menus.php?action=edit&menu=3

![screenshot](https://user-images.githubusercontent.com/550909/31783683-04fe1464-b4b4-11e7-8ec1-c94933463095.png)

**Comment by kevindherman** [comment]
@jlyon smart.

**Comment by jlyon** [comment]
@kevindherman hid this checkbox
