### ISSUE TITLE
Answers child taxonomy showing on /residents and /businesses

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#116]
On the /residents and /businesses pages the Answers open with the child topics in view:

![screenshot 2016-02-04 15 24 00](https://cloud.githubusercontent.com/assets/6032426/12828619/e6c9af08-cb53-11e5-915c-69c70e2ed005.png)

The homepage is loading correctly:
![screenshot 2016-02-04 15 24 11](https://cloud.githubusercontent.com/assets/6032426/12828636/f72ba040-cb53-11e5-8fea-dfd384c6c620.png)

**Comment by jlyon** [comment]
This is by design, to make the /residents page feel different/be a little more useful than the homepage.  If the client feels strongly that they would like the homepage version, they can uncheck "Expand Answers dropdowns" in the 311 Actions Box edit dialog.  If this is something we should discuss, let's talk about it when we start working on the IA stuff.

**Comment by kevindherman** [comment]
Good to know. I'll see what she thinks.

At first I was going to say I'll make it consistent but lets keep it as is
unless there's pushback. I think it could be an interesting test to see if
people use it differently.

On Thu, Feb 4, 2016 at 4:04 PM, Jeff Lyon <notifications@github.com> wrote:

> This is by design, to make the /residents page feel different/be a little
> more useful than the homepage. If the client feels strongly that they would
> like the homepage version, they can uncheck "Expand Answers dropdowns" in
> the 311 Actions Box edit dialog. If this is something we should discuss,
> let's talk about it when we start working on the IA stuff.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/116#issuecomment-180047900>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
