### ISSUE TITLE
Premont, TX: new test site yields 503 error

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1164]
A new test site I created is yielding the below 503 error:

 https://premont-tx.proudcity.com/
![screenshot 2017-10-23 15 47 24](https://user-images.githubusercontent.com/6032426/31909896-a49af354-b809-11e7-8bdb-529c424378b3.png)

**Comment by jlyon** [comment]
I tweaked the build script over the weekend with the launches, and it looks like it probably broke it. I'll look at it tonight @kevindherman

**Comment by jlyon** [comment]
@kevindherman fixed this adn rebuild the site: https://premont-tx.proudcity.com/

**Comment by kevindherman** [comment]
@jlyon thanks. Is everything squared away if I want to create other test sites this week?

**Comment by kevindherman** [comment]
@jlyon I was able to get in by signing in again but the message I got was a new one when clicking on view site from the dashboard:
![screenshot 2017-10-24 10 43 47](https://user-images.githubusercontent.com/6032426/31949947-8894609c-b8a8-11e7-987a-e99e27e19f72.png)

**Comment by jlyon** [comment]
hmm, I'm able to get in.
