### ISSUE TITLE
https error on test site

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1165]
@jlyon I keep getting this ssl cert error when creating a test site:

https://digital-transformation-exchange-ca.proudcity.com/index.php?auth0=1&code=UCzqxIV8zwo4JNZW&state=https%3A%2F%2Fdigital-transformation-exchange-ca.proudcity.com%2F

![screenshot 2017-10-24 15 30 09](https://user-images.githubusercontent.com/6032426/31963921-5de33b0c-b8d0-11e7-9a3a-bc973734ebf9.png)

**Comment by jlyon** [comment]
The subdomain was too long. I deleted and rebuilt at https://digital-transformation-exchange.proudcity.com/ and it's working @kevindherman

**Comment by kevindherman** [comment]
@jlyon thank you.

Is this a fix I can implement in the future?

**Comment by jlyon** [comment]
@kevindherman I just deleted the site and rebuilt it with a shorter name

**Comment by kevindherman** [comment]
@jlyon I am certainly capable of that!
