### ISSUE TITLE
Sonoma City: social account now displaying

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1166]
@aschmoe this facebook account is selected on Sonoma City but not displaying on the social wall on the homepage or /fire-recovery:

https://www.facebook.com/ExperienceSonomaValley/

**Comment by jlyon** [comment]
@aschmoe bump

**Comment by kevindherman** [comment]
@jlyon could you help with this item while AS is out?

**Comment by jlyon** [comment]
yeah ill look at this today/tomorrow

**Comment by kevindherman** [comment]
@jlyon thank you.

**Comment by kevindherman** [comment]
@jlyon is this still pending?

**Comment by jlyon** [comment]
@kevindherman yes, sorry.  @aschmoe could you look at it?

**Comment by aschmoe** [comment]
@kevindherman this was added
