### ISSUE TITLE
ability to add custom text within searchbox

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1167]
It would be nice to be able to edit the default text within the search box from "How can we help you?"

![screenshot 2017-10-25 13 36 37](https://user-images.githubusercontent.com/6032426/32013622-ab3a5138-b989-11e7-806c-a7c49fddd41e.png)

**Comment by jlyon** [comment]
```
[widget widget_name="SearchBox" placeholder="Ask Us Anything"]
```
