### ISSUE TITLE
[monitoring] Increase session lifetime to 14 days

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1168]
Rebecca mentioned that she seemed to be getting logged out more often than just every 12 hrs.

Also, if you are not logged in in the dashboard, but still on /sites, it should warn you

**Comment by kevindherman** [comment]
@jlyon I've been getting logged out a couple times a day for the past week or so.

**Comment by jlyon** [comment]
@kevindherman I will look at this as a hotfix

**Comment by jlyon** [comment]
@kevindherman I bumped this up from 24 hrs to 14 days.  We'll monitor it over the next release cycle and if it looks like it's better, we can publicize it in the next release.
