### ISSUE TITLE
share and font size in footer

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#117]
The font color is too light so it looks like an empty white box when you select the share or font size option in the footer. 
![screenshot 2016-02-04 15 31 47](https://cloud.githubusercontent.com/assets/6032426/12828819/d092497e-cb54-11e5-95d3-91caf8765b79.png)
![screenshot 2016-02-04 15 31 53](https://cloud.githubusercontent.com/assets/6032426/12828818/d0916838-cb54-11e5-8773-976ec3292c26.png)

**Comment by aschmoe** [comment]
@kevindherman this is fixed

**Comment by kevindherman** [comment]
Thank you, sir.

On Thu, Feb 4, 2016 at 6:02 PM, Alex Schmoe <notifications@github.com>
wrote:

> @kevindherman <https://github.com/kevindherman> this is fixed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/117#issuecomment-180093898>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
