### ISSUE TITLE
Lucas: editor user permissions

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1182]
I increased the user permissions for shenderson@lucastexas.us to editor on Lucas, TX so she could add users. However, she's not getting the user tab from the dashboard with the new permissions.

I logged in as the user through Auth0 and was able to confirm this from my.proudcity.com and the embedded dashboard:

![screenshot 2017-11-06 11 50 53](https://user-images.githubusercontent.com/6032426/32452909-dfc36ee0-c2e8-11e7-9397-20eb4b8f71f5.png)
![screenshot 2017-11-06 11 51 18](https://user-images.githubusercontent.com/6032426/32452911-e012f834-c2e8-11e7-84be-17f4f5df75d1.png)

@jlyon Is there another place I should be checking to make sure the permissions are sticking or manually update on my end?

**Comment by jlyon** [comment]
@kevindherman Users should have the Admin role if you want them to be able to mange users.

**Comment by kevindherman** [comment]
@jlyon duh.
