### ISSUE TITLE
Sonoma: google map incorrectly flagging a business as a park

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1184]
The homepage services map is showing a business as one of the parks:

https://www.sonomacity.org/#/maps-1/map/park/details/c8c62453266b111a44c011c93dd335061802159f
![screenshot 2017-11-09 12 24 11](https://user-images.githubusercontent.com/6032426/32619541-15317e8e-c549-11e7-98e2-601a551298c8.png)

Does this need to be reported to Google to have fixed since it's a pulling their data?

**Comment by jlyon** [comment]
@kevindherman hmm, that doesn't seem right. Plus how is a landscaping company in a Scientology church? Is that business not there at all?  I think they should be the ones to submit the form on https://www.google.com/maps/place/Landscape+Management+Associates/@38.282062,-122.461968,17z/data=!3m1!4b1!4m5!3m4!1s0x0:0xe09ca045fbe274da!8m2!3d38.282062!4d-122.4597793.

The types for that Place are coming across as
```
      "types" : [ "park", "general_contractor", "point_of_interest", "establishment" ],
```
I'll see if there is something we can do on our side to exclude any  "general_contractor" or "establishment"  records.

**Comment by kevindherman** [comment]
@jlyon how do you submit a correction?

**Comment by jlyon** [comment]
@kevindherman sorry forgot to mention that you need to click the Suggest an Edit link:
![screenshot](https://user-images.githubusercontent.com/550909/32632701-6f6a63ba-c559-11e7-9f84-94b365e2c8ab.png)

**Comment by kevindherman** [comment]
@jlyon thanks.
