### ISSUE TITLE
Sherman: permission issues

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1187]
@jlyon the Sherman County user countycourt@shermancounty.net is having some permission issues, even after I have increased their role to admin. I was able to confirm these issues signing in as the user via Auth0. 

On events they do not have access to create categories:

![screenshot 2017-11-14 10 18 42](https://user-images.githubusercontent.com/6032426/32787907-cf999bf0-c925-11e7-87fd-ac86cfa2f7c2.png)

All new events went to pending review rather than publishing:
![screenshot 2017-11-14 10 19 58](https://user-images.githubusercontent.com/6032426/32787927-ded6aee6-c925-11e7-825e-5a3b00fee0a9.png)

Also unable to create news categories:
![screenshot 2017-11-14 10 18 51](https://user-images.githubusercontent.com/6032426/32787949-ed06a674-c925-11e7-871a-58f01d7d8a46.png)

I'm assuming they're stuck as an author role for some reason. Could you make this a hotfix? I need them adding content to these areas asap. 

As an aside, I'll have all the pending events published by the time you look at this.

**Comment by kevindherman** [comment]
@jlyon shirley.ng@cityofsanrafael.org from San Rafael is reporting the same role issues as an editor. 

I was able to verify this logging in through Auth0.

**Comment by jlyon** [comment]
@kevindherman I fixed this.  It appears that there is an issue with changing user roles which I will look into later tongiht.

**Comment by jlyon** [comment]
@kevindherman I looked into this last night and wasn't able to replicate the weirdness. I'll need to dig into it more tonight/tomorrow.

**Comment by kevindherman** [comment]
@jlyon this can be closed.

**Comment by kevindherman** [comment]
@jlyon this is cropping up for a user on Danvers: jviel@danversma.gov

They're an editor but has limited permissions (just events) when I login in as Auth0.
![Screenshot 2017-12-12 13.33.55.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56981651a68a130e005c666c/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c36417753e7856e37a23cbb07bf1172e43434d0eee1e020a17b8eb8339a3b035708b5508e585385622c76913aab88218b808bc288f5d99a4fedb1294b7607caddecd5d340c041f83fe5834a3984bcb5ef24ee54950b65e.png)

**Comment by jlyon** [comment]
@kevindherman sorry I fixed this last night. It looks like I forgot to respond. I'm going to try to dig into what's causing this tomorrow.
