### ISSUE TITLE
Danvers: files submitted through webform not saving in entries

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1188]
Danvers is reporting that on their rebate form that the file upload feature is yielding an error when viewing entries.

Here's the front-end form: https://www.danversma.gov/documents/rebate-form/
Backend: https://www.danversma.gov/wp-admin/admin.php?page=gf_edit_forms&id=27
Entries: https://www.danversma.gov/wp-admin/admin.php?page=gf_entries&id=27

If you click into an entry detail and click on the "required documentation" it yields an error:
![screenshot 2017-11-14 13 55 19](https://user-images.githubusercontent.com/6032426/32798723-9a671cdc-c943-11e7-8184-49c1efb50284.png)

https://www.danversma.gov/index.php?gf-download=2017%2F10%2FShowerhead-Order-112-0769011-3045054.pdf&form-id=27&field-id=25&hash=f2f5422f4c1209e61e83b7b0c8f59092c424e133386d8e382d5abe446b795ef3
![screenshot 2017-11-14 13 56 34](https://user-images.githubusercontent.com/6032426/32798750-a693f110-c943-11e7-86f3-2a0b61495791.png)

@jlyon @aschmoe I believe this happened before after an update and all the files were lost. I'm not sure if this is the same problem but I do recall that happening a few months back.

**Comment by aschmoe** [comment]
@kevindherman we had that fixed up, but looks like an update to gravity forms has broken our fix.  Let them know its broken and we will get to fixing it.

**Comment by kevindherman** [comment]
@aschmoe thanks. Should I prepare them for the files being lost?

**Comment by aschmoe** [comment]
For tonight

> I will try to take a look tonight or something and see if we can't fix that (at the very least I will hide that option)

**Comment by aschmoe** [comment]
@kevindherman fix for this will be going up with release

**Comment by kevindherman** [comment]
@aschmoe will the fix allow for multiple uploads?

**Comment by kevindherman** [comment]
@aschmoe is the release this week?

**Comment by kevindherman** [comment]
@jlyon @aschmoe does the fix allow for multiple uploads or has that feature been removed?
