### ISSUE TITLE
upcoming events list icons

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#119]
The upcoming events list is inconsistent between the homepage and /residents.

Homepage (no icons):
![screenshot 2016-02-04 15 40 25](https://cloud.githubusercontent.com/assets/6032426/12829038/fa81c862-cb55-11e5-824e-d4658a683057.png)

/Residents page (overlapped icons):
![screenshot 2016-02-04 15 39 06](https://cloud.githubusercontent.com/assets/6032426/12829062/163818ae-cb56-11e5-90b0-4f111364143d.png)

**Comment by jlyon** [comment]
I changed these so they are both using the Mini List style (this can be done in the edit popup for the list panel).

Before
![screenshot from 2016-02-04 16 13 03](https://cloud.githubusercontent.com/assets/550909/12834153/4de1dc14-cb5a-11e5-86f9-35b7bec48345.png)

After fix
![screenshot from 2016-02-04 16 13 11](https://cloud.githubusercontent.com/assets/550909/12834150/4a31b9d6-cb5a-11e5-9570-74c32d6fd079.png)
