### ISSUE TITLE
"Do you really want to leave this page without updating" alert

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1191]
Alert when editing a content page if you navigate away without hitting "update" to confirm that you actually want to navigate away without saving.

**Comment by aschmoe** [comment]
@kevindherman like all edit pages or only those with page builder?

**Comment by kevindherman** [comment]
Let’s start with pagebuilder.

**Comment by kevindherman** [comment]
@jlyon @aschmoe could this be a release item? It has come up twice today with customers.
