### ISSUE TITLE
Customization bug

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1192]
A few times I got this page when using the CSS customization bug.

<img width="762" alt="screen shot 2017-11-14 at 8 29 51 pm" src="https://user-images.githubusercontent.com/1569463/32909181-c1fb3c4c-caba-11e7-8a5f-052feaf28ae9.png">

**Comment by jlyon** [comment]
@lukefretwell is this www.proudcity.com or one of our sites? All of this code is typically pushed to git and deployed that way because the hard drives on the server are wiped with every deployment. @aschmoe can you point Luke to the repo for www.pc.com?

**Comment by jlyon** [comment]
@aschmoe bump

**Comment by lukefretwell** [comment]
@jlyon @aschmoe closing this.
