### ISSUE TITLE
Require title/description

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1193]
Should we also require title and description for images?
<img width="1143" alt="screen shot 2017-11-14 at 7 03 30 pm" src="https://user-images.githubusercontent.com/1569463/32909217-e780f06a-caba-11e7-9fe6-02763edd3cbc.png">

**Comment by jlyon** [comment]
I personally don't think so because I think sometimes you just want to add a logo or something without typing out a description, but there would be a value for later searching. Thoughts @aschmoe ?

**Comment by jlyon** [comment]
@aschmoe Does Title have any Accessibility use?

**Comment by lukefretwell** [comment]
@jlyon @aschmoe this doesn't appear to be an issue, but ready this because there are some helpful tips as to when it's useful:

http://www.mediacurrent.com/blog/dont-rely-title-attribute-accessibility-seo

**Comment by aschmoe** [comment]
@lukefretwell I've heard alt over title (like https://developer.paciellogroup.com/blog/2016/02/short-note-on-use-of-alt-and-the-title-attribute/), but both have pitfalls.  I think alt is a safe-ish bet.
