### ISSUE TITLE
SR Employees: posting event

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1198]
San Rafael employee site is getting an index table error when trying to post an event that I haven't seen before. It's not letting them publish and is stuck as a draft.

Here's the event and screenshot of the error":

https://employees.cityofsanrafael.org/wp-admin/post.php?post=10913&action=edit

![screenshot 2017-11-17 13 44 20](https://user-images.githubusercontent.com/6032426/32963295-8ad2fe06-cb9d-11e7-87d7-0ec238c90d2d.png)

**Comment by jlyon** [comment]
@kevindherman can you retest and add some notes on how you were able to replicate:
- User
- Screenshot of form before you click submit
- Are you creating a new event or editing?

**Comment by kevindherman** [comment]
@jlyon this is working now. I'll keep an eye out for this with other customers.

**Comment by kevindherman** [comment]
@jlyon this is coming up on Sonoma for me and Laurie Decker's account.

I tried adding the City Hall location to this event: https://www.sonomacity.org/wp-admin/post.php?post=9014&action=edit
![screenshot 2017-11-21 09 54 56](https://user-images.githubusercontent.com/6032426/33079258-28d96d3a-cea3-11e7-9c34-5b2cd6b37e75.png)

![screenshot 2017-11-21 10 00 35](https://user-images.githubusercontent.com/6032426/33079273-3339818e-cea3-11e7-932d-c62721383b95.png)

And then got the error message
![screenshot 2017-11-21 09 55 02](https://user-images.githubusercontent.com/6032426/33079289-3ffbbae0-cea3-11e7-811f-7a3b8812046e.png)

I then tried doing with by checking that the event didn't have a location:
![screenshot 2017-11-21 10 01 54](https://user-images.githubusercontent.com/6032426/33079325-53635584-cea3-11e7-936c-07b904bb1306.png)

But still got an error:
![screenshot 2017-11-21 10 02 02](https://user-images.githubusercontent.com/6032426/33079347-5de1fab0-cea3-11e7-84ea-9fcf175d9546.png)

I went through these steps creating a new event and had the same issues. I also went into event locations and removed a bunch of extra City Hall locations that had typos in the address in case that was crossing up the index but that didn't help either. 

I was curious if the city hall address being a little odd was throwing things off so I created an example event with different address and it yielded the same results. I did notice that even before I entered an address there was a "location not found" message under the address form fields:

![screenshot 2017-11-21 10 09 22](https://user-images.githubusercontent.com/6032426/33079682-3ce428be-cea4-11e7-9f9a-4e4cc1905871.png)

I haven't noticed that message before so I wonder if that maybe has something to do with the bug that appears to be location related. 

Sorry I don't have a clear culprit but I'm hoping this helps point you in the right direction.

**Comment by kevindherman** [comment]
@jlyon Danvers just posted this item to ZenDesk: 

"https://www.danversma.gov/wp-admin/post.php?post=10792&action=edit

I'm trying to post this event and I keep getting an error message. Please advise"

At first glance, it looks to have the same location issue that's flagging the indexing error.
