### ISSUE TITLE
Improve Menu Quickedit interface

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#12]

**Comment by aschmoe** [comment]
![file 7](https://cloud.githubusercontent.com/assets/1634686/12208990/16d5c79a-b605-11e5-9395-35334df43717.png)

**Comment by jlyon** [comment]
I think this should work more like the Drupal menu interface (select menu from a dropdown)

**Comment by jlyon** [comment]
Other immediate style changes in #18

**Comment by jlyon** [comment]
I created a fork of wp-quick-menu, https://github.com/proudcity/wp-quick-menu, that does this.  Here's a before and after. This should make a big difference for SR.

BEFORE
![screenshot from 2016-09-21 10 51 47](https://cloud.githubusercontent.com/assets/550909/18722418/9cb37c14-7fe9-11e6-8ff1-e97e2b546414.png)

AFTER
![screenshot from 2016-09-21 10 50 56](https://cloud.githubusercontent.com/assets/550909/18722434/a4eedf5e-7fe9-11e6-84d4-9e1aa991553b.png)
