### ISSUE TITLE
events: featured image on /events

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#120]
Show featured images on event details on the /events page the same way that news posts do on /news

/news page:
![screenshot 2016-02-04 16 11 31](https://cloud.githubusercontent.com/assets/6032426/12829878/588b05f0-cb5a-11e5-817a-46fb6d2e611a.png)

/events page:
![screenshot 2016-02-04 16 14 37](https://cloud.githubusercontent.com/assets/6032426/12829891/6e1590ca-cb5a-11e5-818e-7faa1d5e5ae2.png)

**Comment by jlyon** [comment]
we decided when we were doing that pattern library that we didn't want imgs on events because it made them feel too busy.  is this a request from the client, or should we revisit?

**Comment by kevindherman** [comment]
That makes sense, let's keep as is.

On Thu, Feb 4, 2016 at 8:15 PM, Jeff Lyon <notifications@github.com> wrote:

> we decided when we were doing that pattern library that we didn't want
> imgs on events because it made them feel too busy. is this a request from
> the client, or should we revisit?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/120#issuecomment-180136635>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by lukefretwell** [comment]
Just as FYI WC did ask about this.

**Comment by kevindherman** [comment]
Thanks Luke, it was a Pilot question but not a request. I wasn't sure if it was a bug or left off on purpose. 

I still think we should hold off because with the large date button, details, add calendar & directions, it makes sense that the image would overcrowd things.
