### ISSUE TITLE
Sherman: adjusting services map doesn't zoom in or out

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1203]
@jlyon @aschmoe the changing the zoom on the services map on Sherman doesn't actually zoom in or out on the front-end: https://sherman-county-or.proudcity.com/

I have it set for 11 in the widget but it's still displaying at the standard 15:
https://sherman-county-or.proudcity.com/wp-admin/post.php?post=3186&action=edit

The hope is to zoom out since it's a county and not just be focused on Moro, the county seat where the lat and long are set to.

**Comment by aschmoe** [comment]
@kevindherman this is because the map fits automatically to marker results.

One solution would be an empty filter category "County" or something

**Comment by kevindherman** [comment]
@aschmoe just have an empty "county" filter?

**Comment by kevindherman** [comment]
@aschmoe the map is set to google not wordpress so there isn't an ability to select the filters. Is there something I'm missing?

**Comment by aschmoe** [comment]
@kevindherman not without making some locations and switching unfortunately.

**Comment by kevindherman** [comment]
@aschmoe got it. This can be closed.
