### ISSUE TITLE
Sonoma: allow for hyperlinks in event description

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1205]
@jlyon @aschmoe what are you thoughts on allowing hyperlinks within event details to work in the event teaser information? 

Here's an example:
https://www.sonomacity.org/events/
![screenshot 2017-11-30 12 05 37](https://user-images.githubusercontent.com/6032426/33443992-fe121b58-d5c6-11e7-851d-b20d40fbbe22.png)

https://www.sonomacity.org/event/community-services-environment-commission-2017-12-13/
![screenshot 2017-11-30 12 05 45](https://user-images.githubusercontent.com/6032426/33443993-fe1e756a-d5c6-11e7-9b61-9b9ec9ccca5d.png)

**Comment by jlyon** [comment]
`wp_trim_excerpt()` in wp-proud-core/proud-helpers.php

**Comment by jlyon** [comment]
PASSING: It would be more work than it should be because the html characters add to the text that we are truncating at, and we need to make sure we don't cut off in the middle of an html tag.
