### ISSUE TITLE
Make external url label more clear on Payment creation page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1212]
@jlyon if you click on make payment online now (set up as external link) it sends to a page not found:

https://white-sulphur-springs-wv.proudcity.com/#/city/payments/bail-bonds

Instead of sending to the external link it adds their primary url path in front of it:
https://white-sulphur-springs-wv.proudcity.com/www.whitesulphurspringspayments.com

**Comment by jlyon** [comment]
@kevindherman I think this is a set-up issue, so I don't think it was ever working properly.  Similar links on other sites (https://www.cityofsanrafael.org/#/city/payments/property-tax) are working fine. 

They need to include "http:" in these urls.  I added these to their three payments and the links are working now: https://www.ncourt.com/ncourtlanding/wvwhitesulphurspringslanding.aspx
![screenshot](https://user-images.githubusercontent.com/550909/33498234-7471afa2-d685-11e7-9952-937f2b689e8b.png).  I'll update that language in the next release so it's more clear.

**Comment by kevindherman** [comment]
@jlyon cool, good to know.
