### ISSUE TITLE
Sherman: broken link checker is missing

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1213]
@jlyon @aschmoe the link checker is missing from Sherman County: 
https://sherman-county-or.proudcity.com/wp-admin/admin.php?page=proudsettings
![screenshot 2017-12-05 13 33 36](https://user-images.githubusercontent.com/6032426/33624044-147fef48-d9c1-11e7-8ade-6b47e9698d72.png)

**Comment by jlyon** [comment]
Added and started a scan @kevindherman

**Comment by kevindherman** [comment]
@jlyon this can be closed.
