### ISSUE TITLE
Ability to increase logo in theme

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1215]
From Zendesk:

"Hi there, 
We had a new logo designed and I was able to upload it to our site just fine but the request has come from above to make it a little larger... Do you know where I can make that change?"

@aschmoe it would be great to have an option to display small logos in a larger format, this seems to come up more often with seals. At the least, some tinkering to make this instance look better would be helpful.

**Comment by aschmoe** [comment]
@kevindherman I've increased this slightly (without setting off a cascade of testing), but I think it makes a difference... it does seem to me that circular icons with no text are just going to look shitty

**Comment by kevindherman** [comment]
@aschmoe what do you think of being able to put that logo in the homepage search box so it can be big when a user first gets to the site?
