### ISSUE TITLE
Accessibility statement and page

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1216]
@aschmoe @jlyon let's figure out the best way to help governments generate accessibility statements. This will be key to explicitly stating our accessibility deliverable and what it means to end users. Would be ideal to just populate an /accessibility page when we launch a new site with a simple statement (probably could just pull one from here - see 'Policy template': https://www.w3.org/WAI/impl/pol) 

@kevindherman, good to put this in the accessibility part of onboarding process.

**Comment by aschmoe** [comment]
@kevindherman @lukefretwell made good progress last night on the checker tool.  Will do another session tonight, then that could be an embed / score we could draw from.

> Our Goal: 
> 100% AA - Last Week 92%
> 100% A - Last Week 100%

Type of thing.

**Comment by jlyon** [comment]
- [ ] Add form to submit accessibility issues (similar to Feedback)
- [ ] Add page to each site 
- [ ] Add link to footer of each site
- [ ] Add Issue (so it shows up in Service Center)

**Comment by aschmoe** [comment]
https://docs.google.com/document/d/19VaCTarTZTOhehn66iOmJ_wPAW67tOXqsGMLR4hjfsE/edit

**Comment by lukefretwell** [comment]
@aschmoe this text:

[Organization name] is committed to ensuring accessibility of its website and intranet to people with disabilities. New and updated web content produced by our organization will meet [link to standard] [version number], [level of conformance], by [compliance date].

Existing web content produced by our organization will meet our standard by [existing content compliance date].

Content provided for our site by third-party developers will meet [third-party content standard] [version number] by [third-party content compliance date]. This [does/does not] include user-generated content.

We aim to ensure that our authoring tools and processes meet [authoring tools standard] [version number] by [authoring tools compliance date]. By [preferential purchasing date] we will preferentially purchase authoring tools that meet or exceed our web accessibility policy.

This policy will be reviewed [review period] on or before the [policy review date]. This policy was last reviewed on [last review date], by [reviewer].
