### ISSUE TITLE
Document embed widget not displaying document preview

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1217]
On this page, the document embed widget is added correctly but it's not embedding the full document:
https://www.co.sherman.or.us/archive-county-election-results/
![screenshot 2017-12-12 10 52 39](https://user-images.githubusercontent.com/6032426/33893982-c9e93010-df2a-11e7-8029-f9361061d21a.png)

Edit page:
https://www.co.sherman.or.us/wp-admin/post.php?post=4024&action=edit
![screenshot 2017-12-12 10 52 51](https://user-images.githubusercontent.com/6032426/33893972-c19475d2-df2a-11e7-8e7f-94fd6ba8c608.png)

Document:
https://www.co.sherman.or.us/documents/upcoming-election-notice/
Doc edit page:
https://www.co.sherman.or.us/wp-admin/post.php?post=3944&action=edit

*the document list is working fine, it's the document embed above it that isn't embedding the full view which is the point of having that widget on top of the doc list widget.

@jlyon @aschmoe

**Comment by kevindherman** [comment]
@jlyon I'm still not getting the embedding view with the doc id number:

![screenshot 2017-12-12 14 59 54](https://user-images.githubusercontent.com/6032426/33905593-222e3d8e-df4d-11e7-982f-fd33290825d9.png)

This is in an incognito window for caching purposes.

**Comment by jlyon** [comment]
@kevindherman isn't this it?
![screenshot](https://user-images.githubusercontent.com/550909/33924660-e9811aee-df8b-11e7-8b97-20a7fea210cd.png)

**Comment by kevindherman** [comment]
@jlyon that is it, but shouldn't the embed document widget be displaying the pdf preview?

**Comment by jlyon** [comment]
@kevindherman right you are. Fixed this in the release.
