### ISSUE TITLE
WSS login from dashboard

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1225]
The auth0 redirect to login to White Sulphur Springs from the dashboard isn't firing correctly.

After clicking on view site button or the link circled below I get sent to this URL without login access:

![screenshot 2017-12-20 10 35 05](https://user-images.githubusercontent.com/6032426/34214899-c9b46112-e571-11e7-9478-d601cd3aad72.png)

Weird URL: https://www.whitesulphurspringswv.org/?message=TheredirectURIiswrong.Yousendhttps://www.whitesulphurspringswv.org,andweexpectedhttps://white-sulphur-springs-wv.proudcity.com

**Comment by jlyon** [comment]
Fixed @kevindherman
