### ISSUE TITLE
Improve Open Source Documentation

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1229]
@aschmoe any ideas?

I'm trying to test a blank install for India.  I updated the plugin list in https://github.com/proudcity/wp-proudcity/blob/master/docs/install.md.  

However when I try to install wp-proud-core, there is some kind of fatal error.  I'm not seeing it in my logs locally or on a test site I set up: 
https://starter.proudcity.com/ (admin:admin)
 `pc kube ssh test starter`

When you login and try to install via the plugins page, you get a blank error message `fatal error installing plugin`

**Comment by aschmoe** [comment]
@jlyon I think problem is theme + plugins all are interdependent.

**Comment by jlyon** [comment]
@aschmoe but we should be able to install wp proud core first, right?

**Comment by aschmoe** [comment]
@jlyon fixed this last night, there were a bunch of references to Gravity Forms classes.

**Comment by jlyon** [comment]
@aschmoe awesome thanks

**Comment by jlyon** [comment]
Bug is fixed.

New and improved: https://proudcity.com/developers
Full docs: https://github.com/proudcity/wp-proudcity/tree/master/docs
