### ISSUE TITLE
Feedback form

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#123]
- [x] form opens a new tab in addition to within the page, should only be in the page
- [ ] remove "create your own typeform" from bottom right corner.

**Comment by jlyon** [comment]
Fixed the new window issue. Removing the branding would require a typeform pro account ($35/mo). @kevindherman

**Comment by kevindherman** [comment]
Thanks. I think you already told me about the branding, sorry to duplicate
that.

On Fri, Feb 5, 2016 at 2:40 PM, Jeff Lyon <notifications@github.com> wrote:

> Fixed the new window issue. Removing the branding would require a typeform
> pro account ($35/mo). @kevindherman <https://github.com/kevindherman>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/123#issuecomment-180514262>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
