### ISSUE TITLE
Screen options not working

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1234]
On Google Chrome / Mac, the 'Screen options' tab doesn't work for me.

<img width="281" alt="screen shot 2018-01-03 at 7 39 04 pm" src="https://user-images.githubusercontent.com/1569463/34685669-06a11688-f45e-11e7-95ab-86ac1f96b033.png">

**Comment by kevindherman** [comment]
I'm able to use the screen option tool in chrome:

https://marin-recovers-ca.proudcity.com/wp-admin/edit.php?post_type=document
![Screenshot 2018-01-08 13.25.21.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56981651a68a130e005c666c/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6416763e795ce37a23cbb17df1102a43434d0eee1e020a17b8eb8339a3b035708b5508e585385622c76913aab88218b808bc288f5d99a4fedb1294b7607caddecd5d340c041083fe5834a59d48ce5ef24be04552b65e.png)

@lukefretwell what page/site are you trying to use the feature on?
