### ISSUE TITLE
SEO meta description not functioning as expected

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#1244]
Despite having added a meta description: 
![screenshot of view-source_https___example proudcity com](https://user-images.githubusercontent.com/1634686/35084880-f0bae98c-fbda-11e7-862b-e6d4765e9c0f.jpg)

**Comment by aschmoe** [comment]
from @lukefretwell 

Looks like there's an issue with the meta tag not displaying correctly.

Example:
```
<meta property="og:description" content="Government Digital Transformation Exchange Sharing the best ideas in digital government transformation. Search Site Search About DTE The Government Digital Transformation Exchange is a first in the nation partnership to accelerate adoption of new technologies and digital government platforms by empowering collaboration across government entities. About DTE Topics Health / Safety Security Data Mobility Latest &hellip; Continued" /> 
```
What is in the CMS is just this:

> The Government Digital Transformation Exchange is a first in the nation partnership to accelerate adoption of new technologies and digital government platforms by empowering collaboration across government entities.

**Comment by jlyon** [comment]
@aschmoe note: wordpress-seo has n update 6.1.1 to 6.2 in release 1.48.0 (tomorrow).

**Comment by lukefretwell** [comment]
@jlyon @aschmoe not sure if this is related, but where is the page title in the admin located? How can we change that? 

Example here: view-source:https://govtransformationexchange.org/illinois-introduces-secure-bring-device-program/

This:

<title>Illinois Introduces a Secure Bring-Your-Own-Device Program - Digital Transformation</title>
 
Should be:

<title>Illinois Introduces a Secure Bring-Your-Own-Device Program - Digital Transformation Exchange</title>

**Comment by jlyon** [comment]
@aschmoe I think we should try to get of yoast if possible.  This looks like a nicer, less obtrusive alternative: 
Details: https://wordpress.org/plugins/autodescription/
Migration path: https://theseoframework.com/docs/seo-data-migration/
Reference/comparision: https://pagely.com/blog/yoast-seo-alternatives/

**Comment by aschmoe** [comment]
@jlyon https://github.com/proudcity/wp-proud-core/commit/34f4611ec36f0e7b76c3d7a302c6ff56339b0c81 removed all the meta descriptions.  I've pushed a fix, confused still about the `get_post_field( 'post_name', get_post() );` call so commented that out

**Comment by jlyon** [comment]
@aschmoe sounds good. Let's hotfix

**Comment by aschmoe** [comment]
@jlyon @kevindherman @lukefretwell this has been hotfixed

**Comment by aschmoe** [comment]
@lukefretwell you can change the title pattern per post type https://govtransformationexchange.org/wp-admin/admin.php?page=wpseo_titles#top#post-types or on individual posts
