### ISSUE TITLE
right sidebar recent news

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#125]
The right sidebar recent news on a news item says "All events>>" at the bottom of the list instead of all or more news. It links to the right place though.

![screenshot 2016-02-05 14 54 24](https://cloud.githubusercontent.com/assets/6032426/12857503/906c1a7c-cc18-11e5-9f9b-0ac79f74bf17.png)

**Comment by jlyon** [comment]
Fixed this
