### ISSUE TITLE
Map pin special characters not displaying properly in hover title

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1250]
From Zendesk:

Hello, when hovering with a mouse over some of the locations on the department map (at the bottom of the main dept page) there is some jibberish. See screen shot below. Also, we need to remove one of the lots (Fifth/D St) as it no longer exists. Can you help advise? TY!

![screenshot 2018-01-23 10 25 20](https://user-images.githubusercontent.com/6032426/35284122-fba40dbe-0027-11e8-94f1-a75d7b8ae1c5.png)

@aschmoe said:
The special characters are getting converted in the title: "Parking Lot &#8211; 925 B Street" (looks fine in the details drawer)

Kevin said":
Yeah, it should read: Parking Lot - 5th & Lootens but the special character in example yields Parking Lot - 5th &#038; Lootens.

cc @jlyon

**Comment by jlyon** [comment]
@kevindherman ahh, I see it now.  I'll look at a fix.

**Comment by jlyon** [comment]
@kevindherman I pushed a fix for this to the service center and released it on SR.  It will be released platform-wide in the next release.

**Comment by kevindherman** [comment]
@jlyon ah, I misread at thought it was pushed to SR which is still reporting issues.

I'll let them know it'll be part of the release.
