### ISSUE TITLE
Meta tag issue

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1252]
Looks like there's an issue with the meta tag not displaying correctly.

Example:

`<meta property="og:description" content="Government Digital Transformation Exchange Sharing the best ideas in digital government transformation. Search Site Search About DTE The Government Digital Transformation Exchange is a first in the nation partnership to accelerate adoption of new technologies and digital government platforms by empowering collaboration across government entities. About DTE Topics Health / Safety Security Data Mobility Latest &hellip; Continued" />
` 

What is in the CMS is just this:

> The Government Digital Transformation Exchange is a first in the nation partnership to accelerate adoption of new technologies and digital government platforms by empowering collaboration across government entities.

**Comment by aschmoe** [comment]
@lukefretwell tracking this in #1244
