### ISSUE TITLE
Can't delete menu items

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1253]
Keep getting this message when trying to delete these menu items.

<img width="687" alt="screen shot 2018-01-25 at 6 31 55 pm" src="https://user-images.githubusercontent.com/1569463/35422570-3c96ed78-01fe-11e8-94e7-943279401304.png">

**Comment by kevindherman** [comment]
@lukefretwell if you click on the the highlighted pages it'll expand and you can then select remove menu item. That will then clear out the invalid menu alert at the top of the page.
