### ISSUE TITLE
Delete pages bug

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1254]
When I was deleting pages in DTE, kept getting varied page errors/bugs. See two examples.

<img width="836" alt="screen shot 2018-01-25 at 1 58 59 pm" src="https://user-images.githubusercontent.com/1569463/35422648-9bb2987a-01fe-11e8-8de6-a14c5ead0973.png">

This happened when I deleted a few pages, showed up above the list view of remainder pages:

<img width="1080" alt="screen shot 2018-01-25 at 1 57 22 pm" src="https://user-images.githubusercontent.com/1569463/35422674-bafe0552-01fe-11e8-941b-4b1770385caf.png">

**Comment by kevindherman** [comment]
@luke can you provide the steps you're taking to delete these pages? Are you doing it from a specific page's edit screen or another method?

**Comment by jlyon** [comment]
I'm able to replicate this in some instances on beta, but not on the live site. It seems pretty sporatic and no customers have complained about it, so I'm going to leave it for now because it would take some significant time to debug.
