### ISSUE TITLE
Change Google Analytics text box to text area

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1255]
Can we make this a text area? It's hard to see all of the code and you can pull the field down to expand.

<img width="1084" alt="screen shot 2018-01-25 at 2 05 59 pm" src="https://user-images.githubusercontent.com/1569463/35422735-0c8b9880-01ff-11e8-9a14-de669950135e.png">

**Comment by jlyon** [comment]
The tracking id is just a short code like UA-XXXXXXXX-X.

I changed the help text to `Copy the Tracking ID code that appears under Admin > Tracking info. Example: UA-XXXXXXXX-X.`

**Comment by lukefretwell** [comment]
@jlyon perfect. Thank you.
