### ISSUE TITLE
Sonoma: sitemap bug

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1257]
The Sonoma City sitemap has a lot of items under Emergency Preparedness that do not live under it's menu option:

https://www.sonomacity.org/sitemap
![screenshot 2018-01-26 14 47 19](https://user-images.githubusercontent.com/6032426/35457713-d881a2a6-02a7-11e8-8deb-b531346ff5ce.png)

https://www.sonomacity.org/wp-admin/nav-menus.php?action=edit&menu=207

**Comment by jlyon** [comment]
@aschmoe do you remember what we're using to set up this sitemap?

**Comment by jlyon** [comment]
@aschmoe bump

**Comment by aschmoe** [comment]
@jlyon this will be fixed in release
