### ISSUE TITLE
Add category hierarchy into filter results

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1259]
The category filter doesn't include hierarchy (category > subcategory) so all of the categories get listed together as one long list. Would be great to add the main categories for each with the subcategories below them.

<img width="302" alt="screen shot 2018-01-29 at 2 04 22 pm" src="https://user-images.githubusercontent.com/1569463/35537680-f81fa19e-04ff-11e8-8a40-08f466b28d37.png">

**Comment by jlyon** [comment]
Please always include a link to the page in question @lukefretwell .

**Comment by lukefretwell** [comment]
@jlyon here's an example: https://govtransformationexchange.org/explore/
