### ISSUE TITLE
311 wrench in top nav

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#126]
311 wrench in top nav should link to http://www.egovlink.com/westcarrollton/action.asp

Currently it opens the old support box.
![screenshot 2016-02-05 14 59 25](https://cloud.githubusercontent.com/assets/6032426/12857596/1cf008aa-cc19-11e5-8baa-842e103f6a33.png)

**Comment by jlyon** [comment]
Could you try refreshing?  I set this up yesterday so these two links both link to http://www.egovlink.com/westcarrollton/action.asp.
![home - west carrollton](https://cloud.githubusercontent.com/assets/550909/12861187/75f76f90-cc16-11e5-9639-4bb461605485.png)

**Comment by kevindherman** [comment]
Yeah, still having issues. It's not when clicking within the 311 box, that works. 

It's when clicking the wrench here:
![screenshot 2016-02-08 10 19 02](https://cloud.githubusercontent.com/assets/6032426/12889536/679c1142-ce4d-11e5-8a6f-f24641f6e67f.png)

**Comment by jlyon** [comment]
Ahh, sorry I didn't understand. @aschmoe, could you take a look at this?

**Comment by aschmoe** [comment]
Added override options to this link
