### ISSUE TITLE
Kettering jobs

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1263]
@aschmoe back in October we made these updates:

1. Apply now button is gone from all of your job posts.
2. Expiration date on posts will no longer auto populate.
3. No apply now button so no issue with contact email addresses.
4. Job posting options/ categories all updated per your preferences.

This week we got the below email about two of these items breaking and perhaps it was part of a release, see the below message:

"Stacy,

We are still having issues with the auto population of expiration dates and email addresses (#2 and #3) below.  The system is defaulting to the email address of whomever is posting the job.  Patti, Jenny and Tracy all report that every time they post a job it auto populates to their individual addresses again.  We like to see if that can be corrected again so that is either doesn't auto populate or if it does it is to ketthr.

Also, the expiration dates are auto populating again, which we would like get corrected.  For example, a job posted today will auto populate to expire 3/2/18.  Last year Tracy manually entered an expiration 2/31/18. When we didn't go back in and manually type in new dates at the end of the year every posting we had deleted and we had to re-post each individual posting.  Our preference is no expiration dates and then we are ready we will delete the posting off our page.

Can we please look at this again, maybe it was the recent update that deleted the corrections that were made in October?  Please let us know.  Thanks.

-Sara"

@aschmoe could you look into these items since you led the charge on the jobs changes?

**Comment by jlyon** [comment]
@kevindherman we will look at this early next week

**Comment by aschmoe** [comment]
@kevindherman was able to fix the expire issue, but the default account will be an additional development task.

**Comment by kevindherman** [comment]
@jlyon I connected with @aschmoe about this and can close this out.
