### ISSUE TITLE
Spin up test instances without state in domain

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1265]
Would it be possible to add the option to exclude the state in the domain name for test sites that Kevin or @lukefretwell spin up? So the domain name would be example.proudcity.com or example-test.proudcity.com.

I'm sure there aspects here that I'm overlooking but it would be nice for organizations, agencies, special districts, etc.

@jlyon @aschmoe

**Comment by jlyon** [comment]
@kevindherman just edit the App Host and Full URL manually on https://my.proudcity.com/sites/create/admin?type=proudcity

**Comment by kevindherman** [comment]
@jlyon got it. Thank you.
