### ISSUE TITLE
Post author box

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1266]
I'd like to have the option to add an author box to posts. 

I researched and 'Simple Author Box' appears to be the most elegant, active and updated:

https://wordpress.org/plugins/simple-author-box/

**Comment by jlyon** [comment]
@lukefretwell I added this to elgl.pc.com

**Comment by lukefretwell** [comment]
@jlyon 👍 

How did you end up doing? Marketplace?

**Comment by lukefretwell** [comment]
@jlyon I set it up a profile here: https://elgl.proudcity.com/momentum-progress-13percent-genderbalance/

Questions:

* How can admins update other author profiles?
* Where do you customize the author box style?
* I'd like to make some minor tweaks to the style. What's the best way for me to do this? Post CSS to an issue?
