### ISSUE TITLE
Update Romulus widget

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1268]

**Comment by jlyon** [comment]
@kevindherman replied to email thread.  Romulus was going to make the updates to the plugin (which just consists of updating doc language and a screenshot).

**Comment by kevindherman** [comment]
@jlyon RW followed up with about this item and I got the below message back:

Thanks for your patience. Engineering is updating the instructions and screenshots in the Romulus WordPress plugin: https://github.com/SenecaSystems/romulus-wordpress-form. 

Attached is the new logo (we have updated it again).

I will keep you posted on progress, let me know if you need further information!
![seneca-mark-01](https://user-images.githubusercontent.com/6032426/39325718-e6e763d0-4960-11e8-87d5-fab2a5754962.png)

**Comment by jlyon** [comment]
Alrighty then @kevindherman
