### ISSUE TITLE
SMS option in department contact

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1269]

**Comment by jlyon** [comment]
Added this to the backend:
![screenshot](https://user-images.githubusercontent.com/550909/36828706-4fe53da2-1cd0-11e8-8399-0ceba1fc1d5b.png)
It will look like this on the frontend:
![screenshot 1](https://user-images.githubusercontent.com/550909/36828708-575b8b4a-1cd0-11e8-8b14-b9902f5af325.png)


I tested the sms: links on my phone and they worked well @kevindherman
