### ISSUE TITLE
Padding and tables

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#127]
Erika said she's still having some issues with formatting between paragraphs and pointed to this page as an example. The table isn't formatting well either. 
https://west-carrollton-oh.proudcity.com/property-tax-information/

backend:
![screenshot 2016-02-05 15 00 55](https://cloud.githubusercontent.com/assets/6032426/12857688/88237d64-cc19-11e5-8511-fdc1d13eefe9.png)

Frontend
![screenshot 2016-02-05 15 01 05](https://cloud.githubusercontent.com/assets/6032426/12857693/8e006f44-cc19-11e5-9503-0910737e23c2.png)

**Comment by aschmoe** [comment]
@kevindherman @jlyon there isn't a table insert option is there?  Should we be adding one?

**Comment by kevindherman** [comment]
@aschmoe that probably explains it, she likely copy/pasted that table in. Table insert would be helpful.

**Comment by aschmoe** [comment]
OK, I've added the plugin for the table options.  

If they find themselves pasting in content with tables in it, it might be safer to manually create the table using the WYSIWYG plugin instead.  That way styles + cleanliness should be preserved.

**Comment by aschmoe** [comment]
@kevindherman also fixed the issue with paragraph padding

**Comment by kevindherman** [comment]
Looks good. I'll share with WC.

On Mon, Feb 8, 2016 at 9:58 PM, Alex Schmoe <notifications@github.com>
wrote:

> @kevindherman <https://github.com/kevindherman> also fixed the issue with
> paragraph padding
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/127#issuecomment-181682228>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
