### ISSUE TITLE
Remove '(city-wide)' text from social feed option

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1273]
Because there are non-cities using the platform, can we remove this text here (and anywhere else we encounter)?

<img width="705" alt="screen shot 2018-02-14 at 3 49 39 pm" src="https://user-images.githubusercontent.com/1569463/36234283-fe0cc2d4-119e-11e8-97d3-5a3d4d1501b8.png">

**Comment by jlyon** [comment]
Done @lukefretwell
