### ISSUE TITLE
Update dashboard bar logo/color to match PC

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1274]
The logo and color for the dashboard bar is using the wrong PC logo. Should be the one we use on the site. Also, the background color should be #0071BC.

<img width="1204" alt="screen shot 2018-02-12 at 9 32 30 am" src="https://user-images.githubusercontent.com/1569463/36234509-3a1f54fc-11a0-11e8-81ff-07a2e5556dd0.png">

**Comment by jlyon** [comment]
@lukefretwell just pushed these updates.
