### ISSUE TITLE
Sonoma: pull in iCal feed to post events on the site

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1277]
The ICS/iCal feature currently allows people to add events on the website to their personal calendars. Sonoma was wondering if they would be able to use iCompass (meeting management vendor) who has a new ICS/iCal feature for their meeting management was seeing if that could be a way for meetings posted there to also be fed onto our site.

So meetings posted to their meeting management here: https://sonomacity.civicweb.net/Portal/MeetingInformation.aspx?Org=Cal&Id=176

Posting to our events page via iCal here: 
https://www.sonomacity.org/meetings/

**Comment by jlyon** [comment]
@kevindherman ok to buy this?
https://www.wp-eventmanager.com/product/wp-event-manager-ical/.  We could
do a personal license initially for just Sonoma.

**Comment by jlyon** [comment]
If so, will take me about 2 hrs to set-up. I can do it this weekend
