### ISSUE TITLE
WC: search results descriptions

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1278]
The description text on the search results page is yielding odd results
https://www.westcarrollton.org/search-site/?term=jobs

Zendesk submission:
I’ve attached a screen shot of something we found today, that I don’t know how to fix. When you type ‘Jobs’ in search bar, this is the page that comes up. Even though there are jobs listed, it says “sorry no content found” under the title. Also, below that, under the Human Resources title, it lists a bunch of weird words. Please let me know if there’s something I need to do to fix. Thanks, Erika

![jobs error website](https://user-images.githubusercontent.com/6032426/36505071-680bb31c-1720-11e8-8dad-49889e2880f5.JPG)

**Comment by jlyon** [comment]
@aschmoe this (wp search results,  not from elastic) can be modified in wp-seo, right?
![screenshot 93](https://user-images.githubusercontent.com/550909/36522013-e08702f0-174e-11e8-9f4a-3322b56a5101.png)

**Comment by jlyon** [comment]
@aschmoe bump

**Comment by aschmoe** [comment]
@jlyon yup, you didn't try it?

![screenshot of search results - west carrollton 1](https://user-images.githubusercontent.com/1634686/37538107-d21fca88-290c-11e8-8c97-3ae075ffe2d8.jpg)
![screenshot of edit page west carrollton wordpress 1](https://user-images.githubusercontent.com/1634686/37538108-d36b92dc-290c-11e8-8a04-2cbb25d5b4b7.jpg)
