### ISSUE TITLE
PO: mobile service center bg color

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1280]
The background color on the port orchard service center in mobile is filling in solid:
https://www.cityofportorchard.us/#/city/payments
![screenshot 2018-02-22 11 02 51](https://user-images.githubusercontent.com/6032426/36549180-1c274682-17c0-11e8-9ef4-67c79ff6eab5.png)

**Comment by jlyon** [comment]
On https://www.cityofportorchard.us/wp-admin/post.php?post=3186&action=edit they had blue set as a bg color.  I changed it to white and this is now fixed @kevindherman.
![Screenshot.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560b69d9fa23ba3d0063c62a/125516c66e82c728ace21e0d46db978826878dba87e6ab01e81fe086264c22703d46f96925d3ba78ee1b28590b0a47fa400c5d42fcf98e2cafb03474984019af80330b2b9b645bf9fa9015ad03ba2a8a4a84bfb48e4cc8ea3d20e68d9d02.png)
