### ISSUE TITLE
PO: long table extended beyond the footer

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1289]
They are using an extremely long table on this page and it expands beyond the footer:
https://www.cityofportorchard.us/contracts/

![screenshot 2018-03-06 15 04 00](https://user-images.githubusercontent.com/6032426/37055397-a40d9964-214f-11e8-8379-2198e1bdda3b.png)

![screenshot 2018-03-06 15 01 41](https://user-images.githubusercontent.com/6032426/37055396-a3f756a4-214f-11e8-978d-55561bdce482.png)

**Comment by jlyon** [comment]
@kevindherman they had a `style="height: 6794px;"` attribute in their `<table>` html code (probably inadvertently added in the WYSIWYG) that was causing this.  It's fixed. I also moved this page out of a single text field in a page builder page, and back into a standard page (better revision history, and interface)
