### ISSUE TITLE
Sitemap updates

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1292]
Not sure if it's a bug or enhancement, but for ELGL, looks like sitemap is only pulling menu items:

https://elgl.proudcity.com/sitemap/

I do see San Rafael looks more comprehensive, so am confused as to how they're displaying differently:

https://www.cityofsanrafael.org/sitemap

**Comment by kevindherman** [comment]
@lukefretwell what's missing? In the page structure there doesn't appear to be any additional subpages on ELGL.

**Comment by lukefretwell** [comment]
@kevindherman just added a test page: https://elgl.proudcity.com/test/

and it doesn't show: https://elgl.proudcity.com/sitemap/

See how PC's auto-builds (it's also configurable to show less): https://proudcity.com/sitemap/

**Comment by kevindherman** [comment]
@lukefretwell sorry I didn't understand your point at first. 

Yes, the sitemap only pulls menu items and was done on purpose to force the good habit of adding pages to the architecture and not have random stuff floating out there. 

The ELGL sitemap will look the same when subpages are created. I changed the menu for the test page to fall under about which is reflected in the sitemap. 

![screenshot 2018-03-07 17 52 00](https://user-images.githubusercontent.com/6032426/37123161-31aca3d2-2231-11e8-9c8f-cbb46701939f.png)

Does that clarify things?
