### ISSUE TITLE
De Leon: contact page pills broken

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1297]
When you go the De Leon contact page the pills that should go to each select contact category lands on a page not found:
https://www.cityofdeleon.org/contact/
![screenshot 2018-03-22 10 38 38](https://user-images.githubusercontent.com/6032426/37777183-5703657a-2dbd-11e8-8e69-e78fbe7bede0.png)

Widget:
![screenshot 2018-03-22 10 38 27](https://user-images.githubusercontent.com/6032426/37777210-636000e4-2dbd-11e8-981d-a7fe4bc6d8ce.png)

Error:
https://www.cityofdeleon.org/people?filter_categories%5B%5D=58
![screenshot 2018-03-22 10 38 46](https://user-images.githubusercontent.com/6032426/37777242-6c76a9a8-2dbd-11e8-9e98-db12397ddde8.png)

@jlyon this appears to be unique to them for some reason. 

@lukefretwell take notes, this is how you submit a support ticket ; )

**Comment by jlyon** [comment]
Is this fixed now @kevindherman ?

![screenshot 66](https://user-images.githubusercontent.com/550909/37886658-8deb5348-3071-11e8-8d12-3964b67f5a42.png)

**Comment by kevindherman** [comment]
@jlyon looks good.

**Comment by kevindherman** [comment]
@jlyon she added another pill and it broke all of them again.
