### ISSUE TITLE
Perms: gravity forms

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#130]

**Comment by jlyon** [comment]
@kevindherman @lukefretwell I set this up so we you/erika have perms to use this. We should prob do a screenshare about this, maybe on the Mon dev call?

**Comment by kevindherman** [comment]
Great, Monday works.

On Wed, Feb 10, 2016 at 7:20 PM, Jeff Lyon <notifications@github.com> wrote:

> @kevindherman <https://github.com/kevindherman> @lukefretwell
> <https://github.com/lukefretwell> I set this up so we you/erika have
> perms to use this. We should prob do a screenshare about this, maybe on the
> Mon dev call?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/130#issuecomment-182651888>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
