### ISSUE TITLE
https://www.livelifelocally.org/ has a google analytics error

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#1300]
`Uncaught SyntaxError: Invalid or unexpected token` in what appears to be a 2nd analytics code... likely added by staff

**Comment by jlyon** [comment]
@kevindherman you see this?

**Comment by kevindherman** [comment]
@jlyon should I ask if they added an additional code? What should I followup with?

**Comment by kevindherman** [comment]
@aschmoe 
![screenshot 2018-04-10 12 40 51](https://user-images.githubusercontent.com/6032426/38570704-7d11caa0-3cbc-11e8-92ec-7d706f228af2.png)

**Comment by jlyon** [comment]
@kevindherman What is this screenshot from?

I fixed this (https://www.livelifelocally.org/wp-admin/admin.php?page=integrations):
![screenshot 97](https://user-images.githubusercontent.com/550909/38653517-050ea9e2-3dc0-11e8-94a3-4f62aaa358ac.png)

**Comment by kevindherman** [comment]
The screenshot is just the home edit view.
