### ISSUE TITLE
Sonoma City: events error

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1301]
The events have disappeared in the dashboard and if you select an event from the front-end it goes to a page not found. 

https://www.sonomacity.org/wp-admin/edit.php?post_status=publish&post_type=event&m=0&scope=all&event-categories=0&seo_filter&readability_filter&filter_action=Filter&paged=1
![screenshot 2018-03-29 13 42 38](https://user-images.githubusercontent.com/6032426/38104455-269e2c0e-3357-11e8-8e02-494d0a008ea8.png)

https://www.sonomacity.org/special-events-calendar/
![screenshot 2018-03-29 13 42 52](https://user-images.githubusercontent.com/6032426/38104456-26aab17c-3357-11e8-82a4-a9f0457a7358.png)

https://www.sonomacity.org/event/signature-sonoma/
![screenshot 2018-03-29 13 43 04](https://user-images.githubusercontent.com/6032426/38104457-26b77448-3357-11e8-94df-c760903ad123.png)

**Comment by aschmoe** [comment]
https://www.sonomacity.org/wp-admin/options-permalink.php

^^ 

Same events issue, resaved permalinks and events seem to be restored

**Comment by jlyon** [comment]
Deployed as Hotfix 1.53.1: Events plugin update, deal with timezones #1310 (wp-proud-core, wp-proud-theme, wp-proud-search-elastic, wp-proud-sr-theme) Apr 15 2018
