### ISSUE TITLE
PO: change "feedback" in footer to "contact us"

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1307]
@aschmoe can you change "Feedback" in the footer to "Contact Us" and still link to the same /feedback page?

This should only be done for https://www.cityofportorchard.us/

**Comment by jlyon** [comment]
@kevindherman this is hardcoded, so it wouldn't be super simple.

For reference: https://github.com/proudcity/wp-proud-core/blob/master/modules/proud-widget/widgets/contact-block/templates/contact-block.php

**Comment by kevindherman** [comment]
@jlyon I'll let them know it's a billable change request and post back with their response.

**Comment by kevindherman** [comment]
@jlyon they're going to pass on the custom dev so we can close out.
