### ISSUE TITLE
Events plugin update, deal with timezones

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#1310]
Events manager introduced new db structure, as a result _end_ts, _start_ts went away which we were relying on display search and elastic

**Comment by jlyon** [comment]
@kevindherman note: we pushed a fix to the timezone to every site on the Platform tonight.  For cities using Elasticsearch, this also included a reindexing.

**Comment by aschmoe** [comment]
@kevindherman @jlyon everyone should be good, except SR docs aren't currently fully indexed... memory issues keep taking things down when I try.  

Seems like we need dedicated solution for elastic that won't continually break and will permit enough memory for index operations.

**Comment by kevindherman** [comment]
Cool. I'll do some poking around and communicate back to customers. 

Does this also fix the recurring issues from here https://github.com/proudcity/wp-proudcity/issues/1305

@aschmoe @jlyon ^

**Comment by kevindherman** [comment]
@aschmoe @jlyon #1305 looks like it was taken care of in this. I'll do some additional testing but should be good.

**Comment by aschmoe** [comment]
@kevindherman yes all the events should be fixed, only remaining issue is elastic reliability and SR indexed document contents
