### ISSUE TITLE
Add card view to Contact list widget

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1311]
@jlyon @aschmoe there were two unintended widget updates to Warr Acres. Here's the message from Zendesk:

> "I have two pages that have made their own changes; 
> On the Economic Development page I only changed the photograph on the top right to be the new mayor, and his name at the bottom of the paragraph. Now both of the images at the right and left of the “Invitation from the Mayor” are tiny and will not show the proper size. Reference https://www.warracres-ok.gov/economic-development/
> 
> On the City Council page https://www.warracres-ok.gov/departments/city-council/ 
> I only changed the titles and images updating to the new Mayor and council persons, and it switched from a grid of 3 wide / 3 high to a single vertical column."

I'm not sure what happened in the first one. When on the edit screen for the images, the page looks different than the usual setup so I was hesitant to switch anything before one of you could take a look to see what caused the images to change.

For the contact list, I switched it back from list view to table view. However, from his note it sounds like maybe there was previously a card or media list view that he was using before. Do either of you remember if the contact list widget previously had that display option?

**Comment by kevindherman** [comment]
From @jlyon email:

He may be right, but I don't think so.  We have never had the Grid view with Contact posts.  You can select the generic "Content list" widget (attached, 16), but that does not allow you to select only the City Council Member category, so all Contacts are displayed in the grid (attached, 15).

We can add the grid view to the Contact list widget in the next release and set this page up for him.
![Screenshot (15).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56981651a68a130e005c666c/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0ca5dd6b0a65633b0ba92e7391a172fd172d585f5e47af490c0a4daaf8dd29a0b63c778d550de5d57f4366846c4ff8e7df46f554f832815d87b6b68b49c2ec3825e68e8d4d3b1f000ac4.png)
![Screenshot (16).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56981651a68a130e005c666c/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0ca6dd6b0a65633b0ba92e7391a172fd172d585f5e47af490c0a4daaf8dd29a0b63c778d550de5d57f4366846c4ff8e7df46f554f832815d84b1b68b49c2ec3825e68e8d4d3b1f000ac4.png)

@jlyon if this could be included in the release that would be great.

**Comment by jlyon** [comment]
will do @kevindherman
