### ISSUE TITLE
Agenda/Minutes content type

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1314]
Create agenda/minutes content type or widget that would format in a table like the below example:

![image001](https://user-images.githubusercontent.com/6032426/39475969-580c2116-4d28-11e8-9896-46b4354fd375.png)

**Comment by kevindherman** [comment]
@jlyon @aschmoe some additional notes after thinking through this some more.

I think the content type should be "meetings" and then it has the below fields:
- Meeting name
- Date
- agenda (document)
- packet (document) - this one might be optional
- Minutes (document)
- Video (youtube/link out)

The content type would also need the following:
- page to display all the fields
- meeting list widget (table view like the original post)
- meeting categories (this would be so you can drop the meeting list widget on different pages for council, committees, etc.)

**Comment by kevindherman** [comment]
@jlyon this mockup was created by the clerk at Lucas. Let me know if you have any questions/thoughts on this. It seems aligned with the widget strategy we have been discussing. 

[Webpage example for Proud City.pdf](https://github.com/proudcity/wp-proudcity/files/2325039/Webpage.example.for.Proud.City.pdf)

**Comment by kevindherman** [comment]
@jlyon I have added attachments to the media types and updated the meeting content but the file is not attaching (saving) to the meeting. If I navigate away and come back the attachment area is a blank:

![screenshot 2018-09-25 09 59 47](https://user-images.githubusercontent.com/6032426/46019411-f8bde280-c0a9-11e8-8dbc-4e4c19ab40c0.png)

**Comment by kevindherman** [comment]
@jlyon 

1- can you add a media field for audio that works with SoundCloud? Like video this tab should only display if they have entered information
2- will the widget have a table view that displays name, agenda, minutes, video, audio?

**Comment by jlyon** [comment]
Closing in favor of https://github.com/proudcity/wp-proudcity/issues/1401 @kevindherman
