### ISSUE TITLE
Elastic: category filter with ampersand breaks request

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#1320]
https://www.lucastexas.us/documents?filter_categories[]=Elections vs https://www.lucastexas.us/documents?filter_categories[]=Planning+%26+Zoning+Commission

**Comment by jlyon** [comment]
Workaround for now: Use "and" in place of "&" in category names.

**Comment by kevindherman** [comment]
@jlyon @aschmoe I've updated the categories in the dashboard but it's not reflecting on the frontend. I checked in an incognito window and the frontend still shows &. 

Can you clear the site cache and see if that does it?
