### ISSUE TITLE
SR: events expiration

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1321]
Events are slow to expire on events list widget on the homepage. Today is June 14th but the top event is listing a meeting from 4pm yesterday:

https://www.cityofsanrafael.org/
![screenshot 2018-06-14 12 54 16](https://user-images.githubusercontent.com/6032426/41426741-8ef535ec-6fd2-11e8-9078-5c69e880a542.png)

Event detail: https://www.cityofsanrafael.org/event/fire-commission-meeting-2018-06-13/
![screenshot 2018-06-14 12 58 10](https://user-images.githubusercontent.com/6032426/41426763-9bece3ee-6fd2-11e8-8888-3805e1245192.png)

Has it not expired because it's within 24 hours or should it go away when the calendar flips to a new day?

cc @jlyon @aschmoe

**Comment by kevindherman** [comment]
@jlyon @aschmoe I checked this morning and the event expiration lag is occurring on the homepage AND /events so it's not isolated to the homepage app.

**Comment by jlyon** [comment]
Verified that I am seeing this too
