### ISSUE TITLE
Typo on /accessibility page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1324]
The word guidElines is misspelled as "guidlines" on the universal accessibility page in the lower section "Accessibility Links":

![screenshot 2018-06-27 12 56 16](https://user-images.githubusercontent.com/6032426/41988338-c6206582-7a09-11e8-99dc-b316c5150243.png)

@jlyon @aschmoe

**Comment by jlyon** [comment]
Pushed as Hotfix 1.57.1, Jun 28 2018: Typo on /accessibility page #1324 (wp-proud-core)
