### ISSUE TITLE
Color checker

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1327]
@aschmoe would be great to see how this could fit into the color customization tool. @kevindherman at minimum adding to checklist for onboarding and in help with a short 'Accessibility checklist.'

Reference: http://jxnblk.com/colorable/

**Comment by kevindherman** [comment]
@lukefretwell I think that's smart. When I setup basic test sites I'm guilty of going at it blind and likely making sub optimal ada/design decisions.
