### ISSUE TITLE
SR: contact detail showing blank page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1329]
If you select a contact detail the page comes up blank. For example, if you click on Mayor Gary Philips from https://www.cityofsanrafael.org/people-elected/ his page is blank:

https://www.cityofsanrafael.org/contacts/mayor-gary-phillips/
![screenshot 2018-07-12 11 45 15](https://user-images.githubusercontent.com/6032426/42644245-1b77fbc4-85c9-11e8-88ac-4a515e5f1b5a.png)

@aschmoe @jlyon

**Comment by kevindherman** [comment]
@jlyon @aschmoe This is now displaying but pushed way down in the page.

**Comment by aschmoe** [comment]
@kevindherman this issue is platform wide, working on deploying fix, but for now pulled on SR directly
