### ISSUE TITLE
Danvers: search results formatting

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1331]
When using site search on Danvers the results page pulls the footer over the results:

![screenshot 2018-07-17 09 41 47](https://user-images.githubusercontent.com/6032426/42821228-15411408-89a6-11e8-873e-4acabe9996eb.png)

This issue seems to be isolated to Danvers. 

I also noticed a phantom search box coming up on all sites as a tested to see if this was  a universal problem or not:

![screenshot 2018-07-17 09 42 45](https://user-images.githubusercontent.com/6032426/42821267-29275266-89a6-11e8-957b-e83dded89a31.png)

@aschmoe @jlyon

**Comment by jlyon** [comment]
Pushed as hotfix
