### ISSUE TITLE
Search input click leaves chrome autocomplete hanging

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#1332]

**Comment by aschmoe** [comment]
![Screen Shot 2018-07-17 at 11.36.11 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56215ad6772f923f0097540b/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246455f46b7191a379ee0c2857415e4fbc21254d58eeb9cb74fce36f34985619e8d7645f75cf3e19f8ed8b49be55b8268b4f82b1b58c44c4fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e0455ca11b3763ef7f346e0a.png)

@kevindherman noting this little UI bug you brought up

**Comment by jlyon** [comment]
probably just needs a focus on there (@aschmoe )
