### ISSUE TITLE
ELGL: homepage icons

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1333]
Would it be a quick item to make the icons be able to display three across instead of four?

@aschmoe @jlyon

**Comment by lukefretwell** [comment]
@kevindherman see what I did below the four across section:

https://elgl.proudcity.com/

Unless @jlyon @aschmoe have a better idea, I'd just create separate ones for each row instead of all in one widget.

**Comment by kevindherman** [comment]
@lukefretwell yeah, that looks better.

**Comment by lukefretwell** [comment]
@kevindherman done cc @jlyon @aschmoe

**Comment by jlyon** [comment]
@kevindherman I dont think so, and there would be lots of ramifications for other clients.

**Comment by kevindherman** [comment]
@jlyon no worries, we figured out another way.
