### ISSUE TITLE
Add option to hide phone column from /contact

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1334]
Can the phone column be removed from the contact block on this page: https://elgl.proudcity.com/contact-2/

@jlyon @aschmoe

**Comment by jlyon** [comment]
@kevindherman Phone has been added to the "Hide field" list for the table view of the contact page.

**Comment by jlyon** [comment]
@kevindherman updated https://elgl.proudcity.com/contact-2/
