### ISSUE TITLE
ELGL: homepage jumbotron text

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1335]
I have the jumbotron text entered as such:

![screenshot 2018-07-23 11 30 39](https://user-images.githubusercontent.com/6032426/43086644-dc848f8a-8e6b-11e8-9132-8fb5b8a8eeaf.png)

However, on the frontend, "minds" gets bumped down a line:
![screenshot 2018-07-23 11 27 57](https://user-images.githubusercontent.com/6032426/43086577-ae04aa6e-8e6b-11e8-9d83-7786b9ac8d71.png)

Is there a way to get minds on the top line while keeping the header type as "header" and not "full height"?

@aschmoe @jlyon

**Comment by lukefretwell** [comment]
@kevindherman this isn't really a great way to think about fonts and spacing as position will differ based on device type, especially phone, where it's going to bump down regardless. I can probably edit the CSS on the width of the box and you'll want the code to look like this:

<h2>
Engaging the Brightest Minds
<br>
in Local Government
</h2>

cc @jlyon @aschmoe

**Comment by kevindherman** [comment]
@lukefretwell that would be great. I think if it could _generally_ format like that on desktop that's ideal, doesn't have to be 100% with resizing.

**Comment by lukefretwell** [comment]
@kevindherman this is part of the template in a .col so I can't fix using CSS. Will pass to @jlyon @aschmoe, but seems like a crazy thing to alter for something like this. Maybe use a different hero setting (see the one below I added (+ fixed the h2 break):

https://elgl.proudcity.com/

**Comment by kevindherman** [comment]
@lukefretwell let's just go with the lower option.

**Comment by lukefretwell** [comment]
@kevindherman done cc @jlyon @aschmoe
