### ISSUE TITLE
Lucas: search filter issues

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1336]
When on the agendas and minutes page, if I check "Parks & Open Spaces" which shows (80) files and then select filter, it yields zero results. 

https://www.lucastexas.us/agendas-minutes/
![screenshot 2018-07-26 18 39 33](https://user-images.githubusercontent.com/6032426/43292511-a07eeb58-9103-11e8-81aa-0c1d88f9e8d5.png)

Yielding no results
![screenshot 2018-07-26 18 39 52](https://user-images.githubusercontent.com/6032426/43292522-b003929a-9103-11e8-9a25-134fa770c4ef.png)

@aschmoe could this be related to this ticket? https://github.com/proudcity/wp-proudcity/issues/1320

**Comment by aschmoe** [comment]
@kevindherman pushed a hotfix for this, lemme know if problem is resolved

**Comment by kevindherman** [comment]
@aschmoe appears to be working!
