### ISSUE TITLE
Accessibility: change PAT to PAC

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1339]
@aschmoe Can you change PAT to PAC in the body text?

![screenshot 2018-07-30 10 15 10](https://user-images.githubusercontent.com/6032426/43402879-b46adac4-93e1-11e8-88ca-80c9f4fe7f3a.png)

cc @lukefretwell

**Comment by aschmoe** [comment]
@kevindherman resolved, also removed the help tab for now
