### ISSUE TITLE
Contact bio not displaying on front end

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1341]
When you click on a person (contact) from https://elgl.proudcity.com/contact-2/ you are brought to their contact detail page such as: 
https://elgl.proudcity.com/contacts/melissa-bridges/

This page should display their bio but it's missing.

![screenshot 2018-07-31 10 07 19](https://user-images.githubusercontent.com/6032426/43464645-9c5b7952-94a9-11e8-82c5-c435c966f4dc.png)
![screenshot 2018-07-31 10 07 32](https://user-images.githubusercontent.com/6032426/43464646-9c81acb2-94a9-11e8-8a98-5233ffb401fe.png)

CC @jlyon @aschmoe

**Comment by kevindherman** [comment]
@jlyon @aschmoe this is actually occurring platform wide, Sonoma just reported the bug as well. 

This contact has bio information and it's not displaying:
https://www.sonomacity.org/contacts/steve-akre/

**Comment by jlyon** [comment]
Note to self: this template now lives in sslp-templates/single-staff-member.php

**Comment by jlyon** [comment]
It appears that upgrading to simple-staff-list version 2.1.1  solves the issue, which we will do in this release (and then test).

**Comment by jlyon** [comment]
Verified that this is fixed on ELGL (below), SR (https://www.cityofsanrafael.org/contacts/councilmember-kate-colin), others
![Screenshot (91).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560b69d9fa23ba3d0063c62a/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec04a1dd6b0a65633b0ba92e7391a172fd172d585f5e47af490c0a4daaf8dd29a0b63c778d550de5d57f4366846c4ff8e7df46f554f832815d84bfb68b49c3ec392de3828c4c381f060ac4.png)

@kevindherman
