### ISSUE TITLE
Fairfax: social wall issues

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1342]
The social wall on Fairfax doesn't appear to be displaying posts correctly:

https://www.facebook.com/townoffairfax
![screenshot 2018-07-31 10 20 39](https://user-images.githubusercontent.com/6032426/43465476-6b851016-94ab-11e8-8f14-0a0c07cb41be.png)

https://fairfax-ca.proudcity.com/
![screenshot 2018-07-31 10 20 45](https://user-images.githubusercontent.com/6032426/43465484-709be2d2-94ab-11e8-9a8e-51e5055324dc.png)

@aschmoe

**Comment by aschmoe** [comment]
@jlyon @kevindherman converted to wall format, which fixed the formatting.  The posts look bad because all their facebook posts are just them updating phone number and the like https://www.facebook.com/townoffairfax.

split out some solutions: 

#1362 for front end
#1363 for back end
