### ISSUE TITLE
SR: font change

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1347]
From Zendesk:
"The font changed and we much prefer the font we had previously. This one is hard to read. Can you see in the screenshots below? I think this happened once before when you did an update."
![pastedimage 1](https://user-images.githubusercontent.com/6032426/43541734-1cdbbd90-9599-11e8-8172-15c307d0bc1f.png)
![pastedimage](https://user-images.githubusercontent.com/6032426/43541735-1cecc612-9599-11e8-907d-8e57989d6f10.png)

@jlyon @aschmoe I'm viewing the usual fonts on my end so I'm not sure what's going on. I feel like their fonts got changed one before following a release, was there any font related stuff done in the last update?

**Comment by jlyon** [comment]
@kevindherman I'm seeing the same fonts as your screenshot in the header, but I'm seeing this in the footer, which I think might be what she's talking about. 
![screenshot 70](https://user-images.githubusercontent.com/550909/43698299-112f5aa2-98fe-11e8-9d1a-45d9483f8294.png)
I found a backup on archive.org from March, and it looked the same https://web.archive.org/web/20180712133224/https://www.cityofsanrafael.org/

**Comment by kevindherman** [comment]
@jlyon thanks, I'll pass along.

**Comment by kevindherman** [comment]
@jlyon I'm confused with this one. Could this change have happened even earlier than the backup? They're pretty adamant that it's different and not prefered.

**Comment by kevindherman** [comment]
@jlyon this is potentially a local network issue for them and google fonts. They're looking into it on their end.
