### ISSUE TITLE
ELGL: embedded dashboard missing

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1350]
This appears to be isolated to ELGL for some reason but I can't see the embedded dashboard, analytics, marketplace, etc. 
https://elgl.org/wp-admin/admin.php?page=proud_dashboard#/sites/elgl/dashboard

![screenshot 2018-08-09 11 07 27](https://user-images.githubusercontent.com/6032426/43908014-dfe68dca-9bc4-11e8-827d-8cb8f63b0542.png)

I've logged out from my.proudcity.com and back in. Viewed the dashboard from my sites, then clicked elgl.org in the top right, selected dashboard from the edit bar and it's a blank page as shown above. I've also entered the site from hitting view site to see if that had a different result but that was also the same. 

I can access the dashboard tools from my.proudcity.com, it's just an issue on the embedded version.

**Comment by jlyon** [comment]
I fixed this @kevindherman
