### ISSUE TITLE
Fairfax: add broken link checker

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1351]

**Comment by jlyon** [comment]
I just enabled this @kevindherman 

You can do this if you want in the future
1. login as info@
2. Go to plugins
3. Search for "broken"
4. Click Activate
![screenshot 85](https://user-images.githubusercontent.com/550909/44073813-a43f4968-9f4a-11e8-95b5-0bbc6db3aa40.png)

**Comment by kevindherman** [comment]
@jlyon thank you for teaching me to fish. I'll take care of this in the future.
