### ISSUE TITLE
Fairfax: contact page pills issue

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1352]
Additional pills displaying on contact page even though the category is not selected in the widget:

https://fairfax-ca.proudcity.com/people/
![screenshot 2018-08-10 12 12 23](https://user-images.githubusercontent.com/6032426/43969146-3b63eeea-9c97-11e8-993c-5952c404bdbb.png)

Planning and Building is not selected in the widget but displaying on the frontend
![screenshot 2018-08-10 12 14 09](https://user-images.githubusercontent.com/6032426/43969147-3b7288ba-9c97-11e8-88ab-b73bd2a16d2f.png)

cc @jlyon @aschmoe

**Comment by jlyon** [comment]
@kevindherman if all of the categories are unchecked, then they will all be shown:
![screenshot 84](https://user-images.githubusercontent.com/550909/44073699-0869a2ae-9f4a-11e8-85f8-fc8e81ad1a36.png)

When I checked just the first category, it was the only one that displayed. I'm not sure that there's a great solution that wouldn't break other sites.

I was just in Fairfax mountain biking yesterday https://www.youtube.com/watch?v=QFeoHXDyeU8

**Comment by kevindherman** [comment]
@jlyon got it. I was looking at the contact list widget and not the filter widget. Marking this as done.
