### ISSUE TITLE
ELGL: analytics

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1353]
@jlyon the view ID and tracking code are correct for me but it's not tracking data. Could you take a look?

**Comment by jlyon** [comment]
Verified that this is fixed
![Screenshot (90).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560b69d9fa23ba3d0063c62a/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec04a0dd6b0a65633b0ba92e7391a172fd172d585f5e47af490c0a4daaf8dd29a0b63c778d550de5d57f4366846c4ff8e7df46f554f832815d84bfb68b49c3ec392de68e8e4e3f17040ac4.png)
