### ISSUE TITLE
Twitter link bug in (contacts) directory

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1365]
The Twitter icon link in contacts doesn't include 'https://www.twitter.com' in the href for city staff or elected officials.

See here:

https://example.proudcity.com/people?filter_categories%5B%5D=57

It does, however work in the bio:

https://example.proudcity.com/contacts/jeff-lyon/

See icon link in right column on bio page:

https://example.proudcity.com/contacts/jeff-lyon/

**Comment by jlyon** [comment]
Fixed this for the release
