### ISSUE TITLE
display post category within post

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1366]
Post categories could be more useful if we displayed the categories as pills or links within the post. That way end users could click on the category links/pills to find more content from that category. This could be helpful for documents and events as well. Having said that, I think posts are the priority and most useful. 

I think the placement could be at the bottom or top.

@jlyon @aschmoe is that an easy update?

**Comment by jlyon** [comment]
Goal is to redirect:
https://elgl.org/news to https://elgl.org/exclusives, and hope that the filter_categories retain

https://elgl.org/news/?filter_categories[]=1

**Comment by jlyon** [comment]
holding off until we can get clarity for elgl. will be in the next release, or could be a hotfix this weekend @kevindherman
