### ISSUE TITLE
IE formatting: top nav showing in footer

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#137]
The top nav is in the footer in IE. I'm trying to get the version that the bug is coming up in.

@jlyon @aschmoe This is happening on Erika's browser so likely an issue across their office.

Screenshot:
[screen_shot_-_ie.docx](https://github.com/proudcity/wp-proudcity/files/123148/screen_shot_-_ie.docx)

**Comment by aschmoe** [comment]
That looks correct to me: if the screen size is small we break to that view

**Comment by kevindherman** [comment]
That makes sense.

If you go lower down in the attachment the social wall is funky too.

On Tue, Feb 9, 2016 at 9:44 AM, Alex Schmoe <notifications@github.com>
wrote:

> That looks correct to me: if the screen size is small we break to that view
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/137#issuecomment-181896773>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by jlyon** [comment]
@aschmoe do we need to do something here?

**Comment by kevindherman** [comment]
We talked about it on our call and it's only happening in IE for her. Same
browser size is is formatting as intended in Chrome.

On Wed, Feb 10, 2016 at 2:51 PM, Jeff Lyon <notifications@github.com> wrote:

> @aschmoe <https://github.com/aschmoe> do we need to do something here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/137#issuecomment-182550259>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by aschmoe** [comment]
K will figure this out today

**Comment by aschmoe** [comment]
@kevindherman I'm unable to get that menu mayhem to happen... could she send over more info on what specifically her OS/Browser versions are?

**Comment by kevindherman** [comment]
It was IE 11 and I'll need to get back to you on the version of Windows. It
was isolated to her so I don't think we need to focus too much on it.

Alex, can you remind me of why we moved the main nav to the footer on the
tablet view?

On Wed, Feb 10, 2016 at 11:48 PM, Alex Schmoe <notifications@github.com>
wrote:

> @kevindherman <https://github.com/kevindherman> I'm unable to get that
> menu mayhem to happen... could she send over more info on what specifically
> her OS/Browser versions are?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/137#issuecomment-182704964>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by aschmoe** [comment]
> It was IE 11 and I'll need to get back to you on the version of Windows. It
> was isolated to her so I don't think we need to focus too much on it.

My Guess would be that she increased the font size or something which would throw off the responsive calculations.

> Alex, can you remind me of why we moved the main nav to the footer on the
> tablet view?

We decided this was the most appropriate way to handle the responsive fixed menu since it left room at the top of the page for the logo, ect... and now as our menu items have slowly grown, the width requirement to fully display the top menu has gotten wider.

> If you go lower down in the attachment the social wall is funky too.

I've completely re-done the social wall stuff and ended having to do a couple fun hours of bug-fixing last night for a seperate IE issue... everything looking fine for me now, so she should check again.

**Comment by kevindherman** [comment]
Thanks, we can close this out.

On Thu, Feb 11, 2016 at 2:38 PM, Alex Schmoe <notifications@github.com>
wrote:

> It was IE 11 and I'll need to get back to you on the version of Windows. It
> was isolated to her so I don't think we need to focus too much on it.
>
> My Guess would be that she increased the font size or something which
> would throw off the responsive calculations.
>
> Alex, can you remind me of why we moved the main nav to the footer on the
> tablet view?
>
> We decided this was the most appropriate way to handle the responsive
> fixed menu since it left room at the top of the page for the logo, ect...
> and now as our menu items have slowly grown, the width requirement to fully
> display the top menu has gotten wider.
>
> If you go lower down in the attachment the social wall is funky too.
>
> I've completely re-done the social wall stuff and ended having to do a
> couple fun hours of bug-fixing last night for a seperate IE issue...
> everything looking fine for me now, so she should check again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/137#issuecomment-183029013>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
