### ISSUE TITLE
Answers tab doesn't show in service when it's the only selection

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1377]
When I select just 'Answers' in the Service Center configuration here:

<img width="1219" alt="screen shot 2018-09-07 at 11 27 41 am" src="https://user-images.githubusercontent.com/1569463/45236671-6045f680-b291-11e8-858d-721122fe00f8.png">

It doesn't show the tab on the front-end:

<img width="1229" alt="screen shot 2018-09-07 at 11 27 57 am" src="https://user-images.githubusercontent.com/1569463/45236698-75228a00-b291-11e8-8260-e3872ce37b60.png">

**Comment by kevindherman** [comment]
@lukefretwell I believe this was done on purpose when there is only tab so it doesn't have an empty look across the top. I created a ticket a few weeks ago that is kind of related to see if the tabs can fill the space better depending on if there are less than the standard four tabs: 

https://github.com/proudcity/wp-proudcity/issues/1357
