### ISSUE TITLE
Pilot Feedback: clicking back within 311 box

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#138]
"When on the Get Answers tab I clicked on a sub category and it worked great. However when I hit back to take me back the sub categories don't populate or reload without me clicking on the 
Get Answers tab again. Might be how the site was intended but it feels like it should repopulate 
again on its own."

I was able to replicate this. So instead of getting this page (if you click the icon):
![screenshot 2016-02-09 15 50 00](https://cloud.githubusercontent.com/assets/6032426/12930208/e029dd90-cf44-11e5-96ef-918e7ea8b2fd.png)

Clicking the back button in your browser loads a blank view:
![screenshot 2016-02-09 15 49 22](https://cloud.githubusercontent.com/assets/6032426/12930221/f80a77bc-cf44-11e5-896d-aeed7357177d.png)

**Comment by jlyon** [comment]
@aschmoe weird, im getting this too.  seems like it only happens on https://west-carrollton-oh.proudcity.com/#/city/answers.  I can also go back one more level and then hit Forward, and the list of categories will appear on #/city/answers.

**Comment by aschmoe** [comment]
@kevindherman @jlyon  wasn't really a back button issue so much as a failure to react.  I've pushed fixes to WC
