### ISSUE TITLE
Screen goes black on live editor

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1382]
When editing using the Live Editor, the live view goes black after you add a few widgets in.

<img width="1238" alt="screen shot 2018-09-10 at 9 19 14 am" src="https://user-images.githubusercontent.com/1569463/45398948-17789f80-b5fb-11e8-995c-c8559e99158f.png">

**Comment by kevindherman** [comment]
@lukefretwell it might be better to disable the live editor for now. It's buggy/inconsistent so I advise customers to not use it.
