### ISSUE TITLE
SR: news filter not yielding results when it should

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1385]
When you select a news filter the results are coming with no articles when there are 200+ for From the City Manager's Desk.

https://www.cityofsanrafael.org/news/
![screenshot 2018-09-13 13 17 03](https://user-images.githubusercontent.com/6032426/45504264-5e7ba780-b757-11e8-9c56-9bc6ff1735ab.png)

Results after filtering: https://www.cityofsanrafael.org/news/?filter_categories[]=From+the+City+Manager%5C%27s+Desk
![screenshot 2018-09-13 13 14 58](https://user-images.githubusercontent.com/6032426/45504196-33915380-b757-11e8-83d0-2d2125f9a2d8.png)

**Comment by jlyon** [comment]
An elastic thing @aschmoe?

**Comment by aschmoe** [comment]
Encoding of the apostophe @jlyon got a fix

**Comment by aschmoe** [comment]
@kevindherman @jlyon deployed hotfix to SR

**Comment by kevindherman** [comment]
@aschmoe this can be closed, right?
