### ISSUE TITLE
Pilot Feedback: large file preview broken

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#139]
This doc is a large file (23MB) and was uploaded correctly but the preview gets a "whoops! There was a problem previewing this document"

https://west-carrollton-oh.proudcity.com/documents/2014-final-audit-report/

Is this a file size thing?

**Comment by jlyon** [comment]
yep, it looks like the max is 25mb.  https://productforums.google.com/forum/#!topic/drive/HGJDq-NAm9g.  I'll hide the preview if it's over 25mb.

**Comment by jlyon** [comment]
well, that 23mb file should have worked, so I guess I'm not sure exactly what the number is.  I'm hiding the preview if the pdf is larger than 25mb for now, which fixes the issue on https://west-carrollton-oh.proudcity.com/documents/2014-final-audit-report/ @kevindherman

**Comment by kevindherman** [comment]
It must be larger than 25mb then because it's hidden on that page.

On Tue, Feb 9, 2016 at 6:37 PM, Jeff Lyon <notifications@github.com> wrote:

> well, that 23mb file should have worked, so I guess I'm not sure exactly
> what the number is. I'm hiding the preview if the pdf is larger than 25mb
> for now, which fixes the issue on
> https://west-carrollton-oh.proudcity.com/documents/2014-final-audit-report/
> @kevindherman <https://github.com/kevindherman>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/139#issuecomment-182134362>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by jlyon** [comment]
i hid it if it's over 10mb

**Comment by kevindherman** [comment]
Ah, now that makes sense.

On Wed, Feb 10, 2016 at 1:30 PM, Jeff Lyon <notifications@github.com> wrote:

> i hid it if it's over 10mb
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/139#issuecomment-182517694>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
