### ISSUE TITLE
Vote bug

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1397]
@jlyon looks like the address search is working, but the submit isn't?

https://example.proudcity.com/vote#/city/vote/address

**Comment by jlyon** [comment]
![Screen Shot 2019-01-26 at 1.54.55 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560b69d9fa23ba3d0063c62a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77226456f56b7191a379f1172f4f5a5a5ecc3c4a4356bcbbd671f3e57862804e0eebd86d5e7dc53545f9b1d41eeb03bc208b4882bfba8248d2f42f67b6d5db1063474f4dcbed5727a19041c95df243e44e5ca3133263e6752431.png)

**Comment by lukefretwell** [comment]
Dupe of #2182
