### ISSUE TITLE
Pilot feedback: services map missing data poitns

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#140]
The services map isn't showing any West Carrollton schools, police station and only one fire station and one park. 

It's list the surrounding services options though.

**Comment by jlyon** [comment]
we're getting data from foursquare, so there must not be any foursquare entries for these in WC.  Not sure there's much we can do outside of a major structural overhaul of the map.

**Comment by kevindherman** [comment]
Maybe Erika (or someone on her staff) can create those entries on
Foursquare.

On Wed, Feb 10, 2016 at 1:56 PM, Jeff Lyon <notifications@github.com> wrote:

> we're getting data from foursquare, so there must not be any foursquare
> entries for these in WC. Not sure there's much we can do outside of a major
> structural overhaul of the map.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/140#issuecomment-182530035>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by jlyon** [comment]
We should probably figure out a good long-term solution for this. Maybe a location post type in wordpress..

**Comment by kevindherman** [comment]
Yeah because right now the map isn't serving a purpose. We talked about
disabling if we can't get those data points.

On Wed, Feb 10, 2016 at 2:27 PM, Jeff Lyon <notifications@github.com> wrote:

> We should probably figure out a good long-term solution for this. Maybe a
> location post type in wordpress..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/140#issuecomment-182539779>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by jlyon** [comment]
it's a big change, so it wouldn't happen for a few weeks

**Comment by kevindherman** [comment]
Lets talk about where it stacks up on the priority list on the dev call and
plan accordingly.

On Wed, Feb 10, 2016 at 2:49 PM, Jeff Lyon <notifications@github.com> wrote:

> it's a big change, so it wouldn't happen for a few weeks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/140#issuecomment-182548968>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by jlyon** [comment]
@kevindherman I added a new Location content type to WC.  There's a taxonomy for the layers, and then you just create a new location for each spot.  I set up the layers with what we're currently using on the automatic map from Foursquare.

There's the Google autocomplete, which will autopopulate the address and hours, so adding the locations is actually pretty quick, but if Erika wants, I can automatically load in all of the Locations currently on the map later today.  I will switch the map over to pull from the locations entered later this morning.

**Comment by kevindherman** [comment]
Sweet.

Why don't you load in the locations currently on the map and then she can
spot check/add missing locations later today.

On Mon, Feb 22, 2016 at 12:34 PM, Jeff Lyon <notifications@github.com>
wrote:

> @kevindherman <https://github.com/kevindherman> I added a new Location
> content type to WC. There's a taxonomy for the layers, and then you just
> create a new location for each spot. I set up the layers with what we're
> currently using on the automatic map from Foursquare.
>
> There's the Google autocomplete, which will autopopulate the address and
> hours, so adding the locations is actually pretty quick, but if Erika
> wants, I can automatically load in all of the Locations currently on the
> map later today. I will switch the map over to pull from the locations
> entered later this morning.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/140#issuecomment-187282420>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by jlyon** [comment]
OK, I will work to get these loaded in in the next 2-3hrs.

**Comment by jlyon** [comment]
@kevindherman I pushed the map and loaded in all of the West Carrollton-specific points from the fourquare map, and a few others.  If we decide we want to include services in the surrounding towns, we can load them in pretty quickly in the morning.

**Comment by jlyon** [comment]
@todo:
- [ ] for top-level featured map, show icons for the marker type (fire, police, etc)

**Comment by kevindherman** [comment]
@jlyon Erika has started to add data points, starting with Fire, however, the new locations aren't making it to the frontend. I'm unable to test if it's admin error, cache or a bug because of issue #167. 

Can you take a look since she's currently working on it?

**Comment by jlyon** [comment]
@kevindherman It looks like the lat/lng isn't getting set. Is she using the autocomplete?   At any rate, I think I'll need to make a change.  I need to get a little rest, but I'll take care of this after our huddle call and fix any entries she has added (she can continue adding them).

- [ ] Geocode on the server if lat/lng isn't getting set

**Comment by kevindherman** [comment]
Sounds good. Thanks Jeff.

On Tue, Feb 23, 2016 at 11:04 AM, Jeff Lyon <notifications@github.com>
wrote:

> @kevindherman <https://github.com/kevindherman> It looks like the lat/lng
> isn't getting set. Is she using the autocomplete? At any rate, I think I'll
> need to make a change. I need to get a little rest, but I'll take care of
> this after our huddle call and fix any entries she has added (she can
> continue adding them).
>
>    - Geocode on the server if lat/lng isn't getting set
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/140#issuecomment-187765159>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by jlyon** [comment]
I added a little fix to the map display so it doesn't break.  It looks like all  of the schools she added got plotted on the map correctly, it's just the fire stations that didn't get the correct lat/lng.  Could you ask her if she was adding the address manually?

At any rate, I'm working on the geocoder now, so that will be all set soon.

**Comment by jlyon** [comment]
Set up the server-side geocoding and geocoded all of the locations Erika had entered that weren't appearing on the map.  All of the pins are appearing now. I'm working on setting up different pins on the Featured map and then we'll be all done here.

**Comment by jlyon** [comment]
Cleaned up the icon and color logic. We should be all set here.

**Comment by kevindherman** [comment]
Great, I'll post back if anything else comes up.

On Tue, Feb 23, 2016 at 3:14 PM, Jeff Lyon <notifications@github.com> wrote:

> Cleaned up the icon and color logic. We should be all set here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/140#issuecomment-187883773>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by jlyon** [comment]
Also, if they have any text (about parks, schools, etc) or photos, they should add them and they'll appear in the sidebar. @kevindherman
