### ISSUE TITLE
SR: missing widget bug

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1406]
Hi,

I've updated the URL for the image in the "Missing Widget" on our Events page (https://www.cityofsanrafael.org/events/) and the URL continues to revert back to the old URL.

Here is the old URL for the "Missing Widget" widget that I am trying to update: https://storage.googleapis.com/proudcity/sanrafaelca/uploads/2017/08/CitySR_EventsFullPg@072517-Fall2017-1.jpg

Here's the new URL that I've changed it to that doesn't stay: https://storage.googleapis.com/proudcity/sanrafaelca/uploads/2018/10/2018-Events.pdf

Here's the page with the issue: https://www.cityofsanrafael.org/events/

![screenshot 10-08-2018 2](https://user-images.githubusercontent.com/6032426/46676189-fed5b800-cbad-11e8-84c1-28fb1c981c08.png)

![screenshot 10-08-2018 1](https://user-images.githubusercontent.com/6032426/46676270-2a58a280-cbae-11e8-8c77-e82c65ebdb7c.png)

![screenshot 10-08-2018](https://user-images.githubusercontent.com/6032426/46676279-2e84c000-cbae-11e8-8199-4b3453b38d21.png)

**Comment by jlyon** [comment]
@kevindherman I removed the old "Missing Widget" and replaced it with an "Image" widget with the 2018-Events.jpg image. This seemed to fix it.
![screenshot 39](https://user-images.githubusercontent.com/550909/46719645-4fd3c380-cc23-11e8-9609-4c5d6ba93557.png)
