### ISSUE TITLE
Danvers: recurring event not displaying

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1407]
Events are not displaying in the event list widget on this page even though the widget and events are setup correctly. The events do display correctly in the calendar view at the bottom of the page so I think it's something with the event list widget in particular. 

Page:
https://www.danversma.gov/departments/veterans-services/

Setup:

![screenshot 2018-10-09 16 52 46](https://user-images.githubusercontent.com/6032426/46698697-c520a380-cbe5-11e8-8e02-98f2aa93ffb3.png)

![screenshot 2018-10-09 16 53 07](https://user-images.githubusercontent.com/6032426/46698699-c5b93a00-cbe5-11e8-823a-ed57cb8c8527.png)

![screenshot 2018-10-09 16 53 57](https://user-images.githubusercontent.com/6032426/46698700-c5b93a00-cbe5-11e8-8cbd-71aab0a0ea95.png)

![screenshot 2018-10-09 16 54 15](https://user-images.githubusercontent.com/6032426/46698701-c5b93a00-cbe5-11e8-9e64-bb1847c1abac.png)

**Comment by jlyon** [comment]
@aschmoe could this be related to the wp-event-manager update awhile ago?  It didn't seem to be anything with my updates to teaser-widget in wp-proud-core (I tried reverting to version 1.60.0)

**Comment by aschmoe** [comment]
@kevindherman this was an issue with elastic not getting the updated tags I think.

**Comment by aschmoe** [comment]
addressed in #1474
