### ISSUE TITLE
Danvers: mailchimp integration bug

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1410]
@jlyon this specific form isn't feeding into mailchimp because the double opt in confirmation email isn't going out. Their other mailchimp forms are working correctly and all the settings on this specific form match the others.

https://www.danversma.gov/smith-school-subscribe-to-emails/

https://www.danversma.gov/wp-admin/admin.php?page=gf_edit_forms&view=settings&subview=gravityformsmailchimp&id=33&fid=7
![screenshot 2018-10-11 10 36 55](https://user-images.githubusercontent.com/6032426/46811875-99b2cb80-cd41-11e8-8526-3b2a06921b45.png)

**Comment by jlyon** [comment]
@kevindherman I verified that the config looked the same in https://www.danversma.gov/wp-admin/admin.php?page=gf_edit_forms&view=settings&subview=gravityformsmailchimp&id=33&fid=7 and the Get Updates list https://www.danversma.gov/wp-admin/admin.php?page=gf_edit_forms&view=settings&subview=gravityformsmailchimp&id=1&fid=2.  This makes me think that there must be something different in the Mailchimp settings, probably that double opt-in is not enabled on that list.  Do we have, or can you get access to the Mailchimp admin?

**Comment by kevindherman** [comment]
@jlyon your PC email was granted access on Thursday so you should be able to get in there. LMK if you didn't get access.

**Comment by jlyon** [comment]
@kevindherman I didn't get an invite it doesn't look like, maybe because I didn't have a Mailchimp account for my jeff@ email address. Are you able to login to Mailchimp, and can you share that login info with me?  If not, can we have them share the account with info@ (similar to what SR ended up doing)?

**Comment by kevindherman** [comment]
@jlyon I just slacked you my information so you can get in.

**Comment by jlyon** [comment]
ok it was the address field
it needs to be an address field on the gravity form, not a single text box
should i remove it from the mailchimp integration, or replace the address text box with a full address/city/state/zip box?
The alternative would be to change the property type in mailchimp from an address to a single text field on https://us15.admin.mailchimp.com/lists/settings/merge-tags?id=162145

For now, I deleted the address field from the gravity form and made that property no longer required in mailchimp.
