### ISSUE TITLE
SR Payments: payment description listing invoice number instead of name

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1412]
The payment description is listing invoice number instead of name this month. Previous months display the name.

**Comment by kevindherman** [comment]
@jlyon they added checkbox form fields for "are you a current Monthly Parking Cardholder" last month. I'm curious if that change is what changed the description area.

**Comment by jlyon** [comment]
@kevindherman it seems like something changed in the way that Stripe sets these descriptions. I think most of these entries are recurring subscriptions that have already been sent from gravityforms to Stripe, so I doubt that a change to the form would have affected all of these legacy payments. 

The good news is we still have access to the Name. I don't think we should add to the dashboard view, but I can add the source payment name (which seems to be what the old description was) to the report in the next release.

**Comment by kevindherman** [comment]
@jlyon sounds good. I'll report back.

**Comment by jlyon** [comment]
@kevindherman it seemed like it should be in the export, but it wasn't for some reason and it was going to be more work to get it in the csv export, so I just changed Description to Name on the payout exports.  The names are now appearing on the Monday, October 15, 2018 SR Parking payout.
