### ISSUE TITLE
Goshen: Array ( ) showing at the top of posts

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1415]
https://goshen-ma.proudcity.com/special-town-meeting-thursday-march-8th-2018/

<img width="1323" alt="screenshot 2018-10-19 09 10 20" src="https://user-images.githubusercontent.com/6032426/47220136-e9ffde00-d37e-11e8-9fc4-afe18f8165f5.png">

**Comment by jlyon** [comment]
Will be pushed as hotfix 1.63.1 shortly.
