### ISSUE TITLE
ELGL: page not found language

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1418]
Can the language on the ELGL page not found be updated to this:

"This page was not found. We recently migrated thousands of pages from our old site, try using our site search to find the page you're looking for and you might have more luck!"

![screenshot 2018-10-22 11 41 17](https://user-images.githubusercontent.com/6032426/47302873-909ee580-d5f0-11e8-9ff9-a40f4aa2aee7.png)

**Comment by jlyon** [comment]
@kevindherman set this up https://elgl.org/uyhghgh

**Comment by kevindherman** [comment]
@jlyon perfect.
