### ISSUE TITLE
Mobile formatting

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#142]
https://west-carrollton-oh.proudcity.com/departments/fire-department/

When in mobile the text wrapping around the image makes one line float:

Mobile:
![screenshot 2016-02-10 14 58 27](https://cloud.githubusercontent.com/assets/6032426/12959983/e530640e-d006-11e5-8aab-2523477a09c1.png)

Desktop:
![screenshot 2016-02-10 14 58 38](https://cloud.githubusercontent.com/assets/6032426/12959995/f0137e92-d006-11e5-8e42-44ba997b440c.png)

**Comment by aschmoe** [comment]
@kevindherman added fix for this
