### ISSUE TITLE
Lucas: outside images being added to the media library

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1423]
From Zendesk:

Do you know why I’m finding random jpegs like the one below from Singapore, some are from Dubai in our media/documents folder?

![unnamed](https://user-images.githubusercontent.com/6032426/47445966-228d2680-d788-11e8-8c3c-20035f2039a3.jpg)

**Comment by jlyon** [comment]
Hmm, I don't have any idea where these would be coming from.  Do you know if they just started appearing when we enabled the media folder plugin?

**Comment by kevindherman** [comment]
@lukefretwell I have no clue. She deleted them now so I'm trying to find an example.

**Comment by lukefretwell** [comment]
@kevindherman do you mean @jlyon re: ☝️ ?

**Comment by kevindherman** [comment]
@lukefretwell yup, meant to tag @jlyon.

It could also be the spam that was coming in from the suggest an event feature.

**Comment by jlyon** [comment]
> It could also be the spam that was coming in from the suggest an event feature.
yes that would make sense.  

Examples would be great if you can dig them up.

**Comment by kevindherman** [comment]
@jlyon they're back!

Here are two examples: 

- https://www.lucastexas.us/wp-admin/upload.php?item=12119 
- https://www.lucastexas.us/wp-admin/upload.php?item=12115

I noticed another place where the add your event widget comes up still. At the bottom of the upcoming events list that displays on an event detail, the widget still shows:
https://www.lucastexas.us/event/city-council-meeting-2019-01-03/
![screenshot 2018-12-07 09 53 49](https://user-images.githubusercontent.com/6032426/49654516-05de4280-fa06-11e8-9b9d-e1d40f379e61.png)

@jlyon @aschmoe

**Comment by jlyon** [comment]
@kevindherman I disabled this form for anonymous users https://www.lucastexas.us/add-event
