### ISSUE TITLE
Email notifications on post change

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1426]
https://wordpress.org/plugins/email-posts-to-subscribers/

**Comment by kevindherman** [comment]
Here's a sample message that Sonoma sends out for council meeting subscriptions:

<img width="915" alt="screenshot 2018-10-30 18 35 40" src="https://user-images.githubusercontent.com/6032426/47754899-c1c38980-dc72-11e8-8549-0b12c737c7d3.png">

@jlyon

**Comment by jlyon** [comment]
Need to support subscriptions per category type (for project updates)

**Comment by jlyon** [comment]
Maybe better to do w Mailchimp? https://mailoptin.io/article/new-post-notification-mailchimp-email-list/

**Comment by jlyon** [comment]
Sonoma uses Constant Contact https://mailoptin.io/article/connect-mailoptin-with-constant-contact/

**Comment by jlyon** [comment]
OK to buy plugin

**Comment by jlyon** [comment]
docs: https://mailoptin.io/docs/
