### ISSUE TITLE
Pilot feedback: contact categories

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#143]
They created a contact category for the the planning and building department so they could utilize the contact list widget on that agency page. Two unintended things happened:

First, it created a tab on the /contact page. If they created a category for each agency that would create too many tabs.

![screenshot 2016-02-10 15 03 12](https://cloud.githubusercontent.com/assets/6032426/12960110/770e1042-d007-11e5-9714-cf0cd389bf93.png)

Second, the widget did not list the categorized contacts as it should on https://west-carrollton-oh.proudcity.com/staff-contacts/

![screenshot 2016-02-10 15 04 45](https://cloud.githubusercontent.com/assets/6032426/12960156/bf4d1768-d007-11e5-9233-05f70274a521.png)

**Comment by jlyon** [comment]
re 1:  This was as it was designed, but I guess we need to create the ability to select the Contact categories that you can select from.

re 2: She needed to select the Table display style:
![screenshot from 2016-02-11 12 24 56](https://cloud.githubusercontent.com/assets/550909/12989447/801bee6c-d0ba-11e5-923a-867287668286.png)
Fixed this on https://west-carrollton-oh.proudcity.com/staff-contacts/.  Maybe some formatting stuff we have to do to that table tho.

@kevindherman @aschmoe

**Comment by aschmoe** [comment]
Should we format a nice "Mini List" for contacts that is a simple concise list?

**Comment by kevindherman** [comment]
@aschmoe yeah, you can hide agency to save space.

**Comment by kevindherman** [comment]
@jlyon re: #1, that makes sense.
