### ISSUE TITLE
Add media (select files) not responding

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1434]
https://employees.cityofsanrafael.org/wp-admin/post-new.php?post_type=document
When adding a file to a document content type on SR Employees, the select file button (see below), is non responsive. 

![screenshot 2018-11-02 12 06 28](https://user-images.githubusercontent.com/6032426/47926787-d6cd3200-de97-11e8-98b6-ba6eec386957.png)

I got reports for Lucas and ELGL that the drag and drop feature was not working earlier this morning.

**Comment by jlyon** [comment]
@kevindherman it appears to be an issue with the new version of wp-seo.  I disabled it on employees.sr.org.  And the select files button now works on the url above. I'll try to hotfix a push downgrading the version shortly.

**Comment by jlyon** [comment]
Deployed as Hotfix 1.64.1, Nov 18 2018: Downgrade wp-seo to 8.4 - JS errors breaking file uploads (wp-proudcity) #1434

**Comment by aschmoe** [comment]
@jlyon tracked down the problem https://github.com/Yoast/wordpress-seo/issues/10800#issuecomment-443091107

looking at how we could fix... our version of lodash-compat  is old enough that simply manually doing that fix isn't  possible... looking into it
