### ISSUE TITLE
Meetings: preserve line breaks in Agenda, Minutes

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1435]
@jlyon  The formatting on the visual editor for meetings isn't translating to the front-end. Any recommendations or is this a bug on our end?

https://fairfax-ca.proudcity.com/meetings/town-council-meeting-november-7-2018/

![screenshot 2018-11-05 11 33 15](https://user-images.githubusercontent.com/6032426/48011839-b6e37b80-e0ee-11e8-94c8-ce0489226e90.png)
![screenshot 2018-11-05 11 33 23](https://user-images.githubusercontent.com/6032426/48011841-b6e37b80-e0ee-11e8-9023-837fb1c0be52.png)

**Comment by jlyon** [comment]
Pushed as Hotfix to Fairfax, Lucas @kevindherman 

Hotfix 1.64.2, Nov 6 2018: Add Time to list of hide-able columns for meetings table view #1401; Meetings: preserve line breaks in Agenda, Minutes #1435 (wp-proud-core, wp-proud-theme)
