### ISSUE TITLE
Meetings feedback

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1438]
- [ ] Add default meetings categories
- [x] Change 'Agenda Packet' tab to just 'Agenda'
- [x] Change 'Contact information' tab to just 'Contact'
- [x] Change 'Content Available' heading in table list view to 'Content'
- [x] Change 'Media' text description in table list view to 'Video'
- [ ] Add 'Copy draft' for meetings
- [x] Change 'Meeting' icon in left admin sidebar to 'gavel'
- [x] Remove document file name (see image below), place download button and date/file size/file type above document and put the entire document in a full-width column

<img width="1088" alt="screen shot 2018-11-06 at 5 02 21 pm" src="https://user-images.githubusercontent.com/1569463/48104983-76692800-e1ea-11e8-87cf-9c3c6345fb09.png">

**Comment by kevindherman** [comment]
@lukefretwell 

- "Agenda Packet" was requested by both customers we worked with on this
- "Media" is the label so that cities like Lucas who are using YouTube for audio don't have a misleading 'video' label when that's technically what is it.

**Comment by jlyon** [comment]
@kevindherman @lukefretwell 

> Add default meetings categories
What should these categories be?

> Add 'Copy draft' for meetings
Seems like we should evaluate all plugins where this should be added. Created https://github.com/proudcity/wp-proudcity/issues/1443.

**Comment by kevindherman** [comment]
Default categories:
![screenshot 2018-11-14 11 37 42](https://user-images.githubusercontent.com/6032426/48497227-b9865500-e801-11e8-888f-bbf0155dacaf.png)

**Comment by jlyon** [comment]
Added these default categories to the new city template.  Existing cities that we add meetings to will have to manually create these (there isn't a super-simple way to set up the default categories when a new plugin is enabled).

**Comment by lukefretwell** [comment]
@jlyon thank you! 💪

**Comment by jlyon** [comment]
Changed the icon in the left sidebar to `fa-gavel` (will be pushed in the next release).
