### ISSUE TITLE
Meetings minutes tab not showing

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1441]
Meetings minutes tab isn't showing even when there's text and attached PDF added.

Example here:

https://example.proudcity.com/meetings/city-council-meeting-november-2-2020/

**Comment by jlyon** [comment]
Minutes only appear for meetings that have already happened, not for upcoming meetings.

![screenshot 2](https://user-images.githubusercontent.com/550909/48430266-c46ab800-e723-11e8-831f-8901435ab548.png)
