### ISSUE TITLE
Forms 'paragraph text' field shows as single line

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1442]
The forms 'paragraph text' field shows as single line and is also not expandable.

Example (see 'Message'): https://example.proudcity.com/feedback/

**Comment by lukefretwell** [comment]
@jlyon can we 🔪 that height requirement there? Previously, the textarea field display like a normal one (larger box), so this is the first time I've seen it look like a normal text field.

Note when I remove the 40px, the forms looks like it should:

<img width="1212" alt="screen shot 2018-11-16 at 3 54 50 am" src="https://user-images.githubusercontent.com/1569463/48620061-86ec7180-e953-11e8-8a01-2a89f81452ec.png">

See admin:

<img width="872" alt="screen shot 2018-11-16 at 3 58 19 am" src="https://user-images.githubusercontent.com/1569463/48620198-0f6b1200-e954-11e8-8ae3-fa5a59b4d542.png">

**Comment by jlyon** [comment]
Removed the textarea height defn
