### ISSUE TITLE
Logout = 'Oops' page 

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1444]
When logging out of dashboard, I'm getting this page:

<img width="1192" alt="screen shot 2018-11-15 at 3 03 46 pm" src="https://user-images.githubusercontent.com/1569463/48587651-d6498800-e8e8-11e8-9684-71c27e79acf6.png">

cc @jlyon

**Comment by jlyon** [comment]
This is now fixed on https://paradiserecovers.org/ (assuming that was the site you were working on)
