### ISSUE TITLE
Default meetings buttons to 'Link color'

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1446]
The meetings 'Content Available' buttons don't pass WCAG AA. 

Can we update the CSS to:

* use the primary color selected in customization (see below)
* hover to either be the same as above bullet or the highlight color
* make font not bold

Update this part of the CSS:

`label-default {
    background-color: #;
}
.label {
    font-weight: normal;
}`

Reference:

<img width="1230" alt="screen shot 2018-11-16 at 10 40 24 am" src="https://user-images.githubusercontent.com/1569463/48646475-cd66be00-e99d-11e8-8e3e-971dfa25572f.png">

Color to use:

<img width="335" alt="screen shot 2018-11-16 at 10 50 59 am" src="https://user-images.githubusercontent.com/1569463/48641263-0bf47c80-e98e-11e8-94ff-71972793f15c.png">

**Comment by jlyon** [comment]
@luke, I made these `.label-primary` instead of `.label-default`, which will make them the same bg color as the left side menu. Will be pushed in the next release.

**Comment by lukefretwell** [comment]
@jlyon just seeing this! Thank you!
