### ISSUE TITLE
Add badge CSS classes to ProudCity stylesheet

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1449]
I'd like to add [badge styles](https://getbootstrap.com/docs/4.1/components/badge/
) to the main ProudCity style sheet, so we can use these in certain instances like here (where I used custom CSS to implement) and particularly the recovers theme we've discussed:

https://paradiserecovers.org/milestones

Code to add:

```
/* Badges */

.badge-primary {
	background: #0071bc;
	color: #fff;
}
.badge-secondary {
	background: #aeb0b5;
	color: #fff;
}
.badge-success {
	background: #2e8540;
	color: #fff;
}
.badge-danger {
	background: #cd2026;
	color: #fff;
}
.badge-warning {
	background: #f9c642;
	color: #000;
}
.badge-info {
	background: #00a6d2;
	color: #fff;
}
.badge-light {
	background: #fff;
	color: #000;
}
.badge-dark {
	background: #000;
	color: #fff;
}

```

**Comment by jlyon** [comment]
@luke, we're using bootstrap 3, so this is what we currently have. It looks like badges don't have the color subclasses, and this kind of thing is usually done with labels (which don't have the full rounded corners). https://www.tutorialrepublic.com/twitter-bootstrap-tutorial/bootstrap-labels-and-badges.php

**Comment by lukefretwell** [comment]
Thanks @jlyon. Closing.
