### ISSUE TITLE
Event categories not appearing on /calendar

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#145]
I was able to change this url to /events: https://west-carrollton-oh.proudcity.com/events/

**Comment by aschmoe** [comment]
@jlyon the reason this doesn't work is the pager... if we can figure out how to remove the url path handling from the EM plugin certainly the right thing to do.

**Comment by jlyon** [comment]
i think we definitely want (need?) event categories to appear on this page, so let's figure out a way to make it happen.

> if we can figure out how to remove the url path handling from the EM plugin certainly the right thing to do.
I think this should be done. There was a setting in EM. /events is pulling from the panels config on https://west-carrollton-oh.proudcity.com/wp-admin/post.php?post=3057&action=edit.

**Comment by kevindherman** [comment]
I agree that it's a need.

**Comment by jlyon** [comment]
http://wordpress.stackexchange.com/questions/41988/redeclare-change-slug-of-a-plugins-custom-post-type

**Comment by aschmoe** [comment]
This is done
