### ISSUE TITLE
Update Dashboard Guide and Docs links

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1451]
Should all point to help.proudcity.com

**Comment by jlyon** [comment]
@kevindherman where does the Launch Guide live now? https://proudcity.zendesk.com/hc/en-us/articles/222351267-Launch-Guide

**Comment by jlyon** [comment]
Should this link point to help.proudcity.com, or a subsection?
![Screenshot (12).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560b69d9fa23ba3d0063c62a/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0ca2dd6b0a65633b0ba92e7391a172fd172d585f5e47af490c0a4daaf8dd29a0b63c778d550de5d57f4366846c4ff8e7df46f554f832815d84beb68b49c4ea3521e38a86483916050ac4.png)

**Comment by jlyon** [comment]
Also need to update this
![Screenshot (13).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560b69d9fa23ba3d0063c62a/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0ca3dd6b0a65633b0ba92e7391a172fd172d585f5e47af490c0a4daaf8dd29a0b63c778d550de5d57f4366846c4ff8e7df46f554f832815d84b1b68b49c4ea3521e3898b4d3b1d050ac4.png)

**Comment by kevindherman** [comment]
@lukefretwell what do you think for where the links should point at this time?

**Comment by kevindherman** [comment]
@lukefretwell before we do that have all of the zendesk articles been moved over to help.proudcity.com?

**Comment by lukefretwell** [comment]
@kevindherman I'll have those moved next week.

**Comment by jlyon** [comment]
For Now I changed 'Guides' to 'Knowledge base' with a book icon and link to help.proudcity.com.

I also changed Docs in the topnav to point to help.proudcity.com.

I'll hold off on other changes till you post back here @kevindherman @lukefretwell
