### ISSUE TITLE
Meetings: keep file labels in column rather than sliding over

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1452]
When a file type has not been adding to a meeting, such as minutes, but the audio or video has, the media label slides into the place of the minutes rather than staying in it's usual column. Can agenda, minutes and media always stay in that order and have a gap if something is missing?

![screenshot 2018-11-26 16 40 51](https://user-images.githubusercontent.com/6032426/49043919-54841500-f19a-11e8-9234-59adc7c545f9.png)

**Comment by jlyon** [comment]
This now looks like this
![screenshot 30](https://user-images.githubusercontent.com/550909/49264948-26eed400-f405-11e8-8286-2abca8ecd9b9.png)
