### ISSUE TITLE
Meetings: additional agenda download shows up when text is added to visual editor

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1453]
https://www.lucastexas.us/meetings/parks-and-open-space-board-meeting-april-26-2016/

![screenshot 2018-11-27 16 50 06](https://user-images.githubusercontent.com/6032426/49113880-a5f8d680-f264-11e8-8f5e-4c6ca6065062.png)

**Comment by jlyon** [comment]
@kevindherman I added this as part of a bunch of updates I made to the meetings display as a hotfix in this release: Hotfix 1.65.1, Nov 26 2018: Meetings: soundcloud not embedding
#1438

I agree that this looks weird with a really short agenda. I added a check so this will only appear on really long agendas where any reference to the download would be buried at the bottom of the page.

I also fixed an issue where the horizontal bar was appearing even if there was no agenda/meeting text.
