### ISSUE TITLE
SR: police widget on /news broken

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1469]
Links on the Police News widget are not directing correct:

https://www.cityofsanrafael.org/news/

From zendesk:

The news integration with SRPD.org is broken. I think this is due to a name change in the srpd.org link structure.

https://www.cityofsanrafael.org/news/

If you click the Police News on the left the links lead to an internal server error.

The link is looking for :https://www.srpd.org/press/full.php?id=501

But it looks like the path has been changed to: https://www.srpd.org/press-release.php?id=501

Then the response from the SRPD admin:

Sean,

Yes, that is correct. I thought we updated that before the old one was eventually removed. I can’t remember - are you pulling the headlines from our RSS feed or is the code that generates the links on your server?

Also, our archive is now: https://www.srpd.org/news.php and general press information is: https://www.srpd.org/press

Alex

**Comment by kevindherman** [comment]
@aschmoe following our side chat:

Thanks for the info. I see the issue now. That was the old version of the headlines_json file. I updated that file temporarily, but when you get a chance can you update your system to point to:

https://srpd.org/includes/apps/news/headlines_json.php

instead of /programs/press_headlines/headlines_json.php

Thanks!
Alex Holm

**Comment by jlyon** [comment]
@kevindherman I updated the json file we're using to https://srpd.org/includes/apps/news/headlines_json.php

**Comment by kevindherman** [comment]
@jlyon @aschmoe I got this message through Zendesk about this ticket:

We missed a bad link when fixing the Police News Feed on the News Page. https://www.cityofsanrafael.org/news/

Can you change the link on the button to "See All?" It should link to:

https://www.srpd.org/news.php

**Comment by jlyon** [comment]
@kevindherman this was unrelated to the reverts, it just needed to be fixed. Updated the See all button to link to https://www.srpd.org/news.php.

**Comment by kevindherman** [comment]
@jlyon this is from SR, could it be a network thing?:

I still see the error on https://www.cityofsanrafael.org/news/ (https://www.cityofsanrafael.org/news/)

The button still goes to https://www.srpd.org/beinformed/pressreleases.php (https://www.srpd.org/beinformed/pressreleases.php)

Instead of https://www.srpd.org/news.php

I tried clearing cache and viewing in another browser.

**Comment by jlyon** [comment]
@kevindherman Sorry, I think I restarted the image after pulling those changes, which made the changes go away.  I re-pulled and the button should be fixed.  It seemed to require a hard refresh from me.

**Comment by kevindherman** [comment]
@jlyon thank you. This can be closed.
