### ISSUE TITLE
Social wall filter masonry column issue

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#147]
To repro:
1) https://weston-wi.proudcity.com/#/city/answers
2) Click on Facebook filter
3) Goes into one column (items cut off)
4) Click on all networks icon and nothing happens (no js err)

**Comment by aschmoe** [comment]
This was part of a part of a fun IE adventure I took last night (https://github.com/tristanguigue/angular-dynamic-layout/issues/36)...  this is all fixed up.

**Comment by aschmoe** [comment]
As for the content/tabs: 

Fixed the tab issue, twitter was struggling since there no images, and I had been naively processing.

That content is a little messy since that twitter account hasn't been used lately, so switching between the main view + facebook is the same set of data, which was failing to trigger layout reset.  Fixed now/

**Comment by jlyon** [comment]
I noticed that topeka-ks.proudcity.com is in 2 columns on a call today. Is that just because there are so few items, or do we just need to pull on that (I think I might have this morning). @aschmoe

**Comment by aschmoe** [comment]
@jyon it wasn't pulled, but now is

On Thu, Feb 11, 2016 at 12:34 PM, Jeff Lyon <notifications@github.com>
wrote:

> I noticed that topeka-ks.proudcity.com is in 2 columns on a call today.
> Is that just because there are so few items, or do we just need to pull on
> that (I think I might have this morning). @aschmoe
> <https://github.com/aschmoe>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/147#issuecomment-183050858>
> .
>



-- 
Alex Schmoe
Senior Web Developer
Albatross Digital

www.albatrossdigital.com | alex@albatrossdigital.com | W 720.663.0581 | C
206.240.1801

**Comment by jlyon** [comment]
werd
