### ISSUE TITLE
Restructure dashboard UI

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1481]
I think we should air out the dashboard and:

* remove the right sidebar
* delete the 'Did you know' box
* for ProudCity Care, I'd also remove or put below the dashboard items under a 'Help' section. I'd remove this altogether and place this UI somewhere else (I think it's in the nav).

Screenshot:

<img width="1280" alt="screen shot 2018-12-15 at 10 33 44 am" src="https://user-images.githubusercontent.com/1569463/50192480-4f247100-02e7-11e9-8096-2fce1d316b14.png">

**Comment by jlyon** [comment]
How does this look @lukefretwell ?
![Screenshot (28).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560b69d9fa23ba3d0063c62a/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0fa8dd6b0a65633b0ba92e7391a172fd172d585f5e47af490c0a4daaf8dd29a0b63c778d550de5d57f4366846c4ff8e7df46f554f832815d84b1b68b49c4ef3d24e18b8f463618020ac4.png)

**Comment by lukefretwell** [comment]
@jlyon beautiful. ❤️

**Comment by kevindherman** [comment]
@jlyon can the support ticket link go here instead: https://help.proudcity.com/submit/

**Comment by jlyon** [comment]
@kevindherman i think we're all set here now,. right?
