### ISSUE TITLE
Answers not displaying if there are over 100 Answers categories

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1482]
Answers topics that are selected for the homepage widget are not displaying on the homepage. The homepage is only displaying 3 categories when more are selected:

![screenshot 2018-12-20 11 27 50](https://user-images.githubusercontent.com/6032426/50297373-a5f68b80-044a-11e9-8c90-2d8c68fc3eac.png)

Here's an example of an piece of answers content that is setup correctly but for some reason isn't displaying on the homepage:
![screenshot 2018-12-20 11 29 45](https://user-images.githubusercontent.com/6032426/50297375-a5f68b80-044a-11e9-929a-59b125c6235d.png)

@jlyon

**Comment by jlyon** [comment]
@kevindherman so this is kind of a combination of issues:
Our service center code is really only built for up to 100 FAQ Topics (top level and children). Bedford has a ton of categories under `Business Directory`, which gives them 138 total categories.  The service center is only loading the first 100 categories, which happen to mostly be in the Business Directory, which are all being hidden anyways.  The last 38 categories are the one's we're actually interested in, but they are never being loaded, so only three top-level categories appear.

We have a couple of options for fixing.

1. Preferred: Filter out the categories we're not using in the query to the rest-api `https://bedford-oh.proudcity.com/wp-json/wp/v2/faq-topic?per_page=100&...`

2. Fix the sort.  I dragged Business Directory to the bottom on https://bedford-oh.proudcity.com/wp-admin/edit-tags.php?taxonomy=faq-topic&post_type=question, thinking that that would move it to the end of the list, but the sort didn't seem to do anything for this list. @aschmoe do you know if any of the stuff you did around WP5 would have affected our sort for categories? (it might have also been some of the rest-api updates in rest-api).

Both options will take some refactoring, but we can def get it fixed before the thurs 1/3/19 launch.

**Comment by kevindherman** [comment]
@jlyon got it. 

I feel like there are other cities like San Rafael that use the answers list widget to build out FAQs and they doin't have this problem but perhaps it's just because they don't exceed 100. 

Let me know if you need anything from me to determine which route. @jlyon

**Comment by kevindherman** [comment]
@jlyon @aschmoe Ruston is also having issues with their homepage answers content and I'm not sure if it's related to this or not: https://ruston-wa.proudcity.com

Their categories list but they aren't opening even though they're setup correctly.

**Comment by jlyon** [comment]
@kevindherman Bedford Answers are now fixed

**Comment by kevindherman** [comment]
@jlyon awesome, looks good!

**Comment by kevindherman** [comment]
@jlyon @aschmoe this got the top level or parent categories displaying again, however, a bunch of answer content assigned correctly to sub-categories are not displaying:

https://bedford-oh.proudcity.com/#/city/answers/safety/
![screenshot 2019-01-11 10 21 34](https://user-images.githubusercontent.com/6032426/51042595-b18d2c00-158a-11e9-9011-c6418601285a.png)

This should display there: https://bedford-oh.proudcity.com/wp-admin/post.php?post=4189&action=edit
![screenshot 2019-01-11 10 22 17](https://user-images.githubusercontent.com/6032426/51042659-d2558180-158a-11e9-9a5c-c00655850705.png)

**Comment by jlyon** [comment]
@kevindherman I fixed this with the same hack I used to fix the top-level issue.

**Comment by jlyon** [comment]
We're all set here now, right @kevindherman ?

**Comment by kevindherman** [comment]
@jlyon yup!
