### ISSUE TITLE
Deleted documents still indexing

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1483]
@jlyon @aschmoe 
On Danvers but also being reported on Paradise documents are being moved to the trash but still showing up in site search.

For example on Danvers, there are multiple Change of Address forms in the Document trash and only one that is published but all show up in the site search.

I am waiting on Paradise to provide examples of this coming up for them but I received the below email from them late last night:

Hi Kevin and Luke – we are having an issue when we try to replace files on the website. We thought that if we deleted a media file and then reloaded the updated file with the same name, the URL would remain the same the updated content would be available. We have had issues deleting files from the media folder. To get around this issue we have changed file names and re-linked them to the correct place. It also seems that files are still accessible once we delete them from the media folder – is there somewhere else we need to clear to have them deleted?

**Comment by jlyon** [comment]
I set this setting for Butte on https://buttecountyrecovers.org/wp-admin/upload.php?page=stateless-settings
![screenshot 25](https://user-images.githubusercontent.com/550909/50845249-442a9280-1321-11e9-93b9-ebb26d7f87eb.png)

**Comment by jlyon** [comment]
Seems like there might be some sort of cache thing messing things up here.

**Comment by jlyon** [comment]
@kevindherman So it looks like there's just a cache of about 1hr on files that have been uploaded and then deleted.  I just checked the test file I uploaded above and it updated now.  I think you can communicate that this is fixed to Butte with the 1-hour cache caveat above.

I'm leaving this issue open for the Danvers part of it, and changing the title.

**Comment by jlyon** [comment]
Can you provide an example of a document that has been deleted on Danvers that is still appearing in search?

**Comment by kevindherman** [comment]
@jlyon if you do a front end site search for "address change form" you'll see several results. However, if you do a search from dashboard > all documents you'll notice there is only 1-2 in that list but several in the trash.
