### ISSUE TITLE
event list widget

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1484]
Lucas: homepage event list widget says no events but there are active events: 

https://www.lucastexas.us/

Danvers reported recurring event issues being a problem again on their site which was previously fixed. @aschmoe could this be an elastic thing again?

**Comment by jlyon** [comment]
@kevindherman I'm seeing 2 events on there
![Screenshot (19).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560b69d9fa23ba3d0063c62a/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0ca9dd6b0a65633b0ba92e7391a172fd172d585f5e47af490c0a4daaf8dd29a0b63c778d550de5d57f4366846c4ff8e7df46f554f832815d84beb68b49c4ee3521e5838c4c3e18010ac4.png)

**Comment by kevindherman** [comment]
@jlyon @aschmoe she just wrote to me that it's the recurring events that aren't posting. Since they also have elastic I'm assuming this is the same problem as Danvers.
