### ISSUE TITLE
Add LinkedIn to 'Staff contact'

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1486]
Would be great to include LinkedIn in the staff contact under 'Staff member info.'

<img width="774" alt="screen shot 2019-01-09 at 10 11 28 am" src="https://user-images.githubusercontent.com/1569463/50920130-727ba100-13f9-11e9-952d-4acafe4ed254.png">

**Comment by curtismchale** [comment]
Done with https://github.com/proudcity/wp-proudcity/issues/1968
