### ISSUE TITLE
Remove example bar on example.proudcity.com

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1492]
@jlyon can we remove the EXAMPLE bar on example.proudcity.com?

![screen shot 2019-01-14 at 4 04 07 pm 2](https://user-images.githubusercontent.com/1569463/51149341-7d2da000-1816-11e9-9a20-7ec82fe35e09.png)

**Comment by jlyon** [comment]
Removed this @lukefretwell @kevindherman
