### ISSUE TITLE
Refine footer to include connect/contact/subscribe

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#150]
The first two columns after the city seal are redundant with the the persistent navigation. Let's use that real estate to promote base social media accounts, newsletter subscribe and base contact info.

So:

* column 1: seal
* column 2: Connect (with social media icons)
* column 3: subscribe form
* column 4: contact info

**Comment by aschmoe** [comment]
@lukefretwell first version of this ready on WC

**Comment by lukefretwell** [comment]
@aschmoe this is :muscle:. Comments:

* Don't think you need 'Find us on ...' text. Just 'Twitter,' 'Facebook,' etc.
* Don't think you need 'Get updates' text under subscribe. 
* Contact seems like it could be standardized and include links to 'Directory' and 'Feedback.' That way the engagement footer is easier to set up rather than having to set up a contact widget when we already have that functionality in /contact. Plus, good for us to make feedback ubiquitous and seems like that's the best place for it.

**Comment by lukefretwell** [comment]
@aschmoe see #154

**Comment by jlyon** [comment]
@aschmoe see https://san-ramon-ca.proudcity.com/#/city/answers
- [ ] How can we automate the footer social media links so we don't need to manually change them every time
- [ ] What's happening with the button below contact us?

**Comment by aschmoe** [comment]
@jlyon 

>  Is there a function we can call when we save the social media to update that widget output?

Should work with default, will make sure example (and san romon) are set properly

> What's happening with the button below contact us? 

This was just a gravity forms reference, is there an easy way to set the default without having mailchimp, ect tied into it.
