### ISSUE TITLE
Footer widget link bug

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1504]
When adding a 'Custom HTML' widget in the footer, the links are retaining 'example.proudcity.com' in the links, even thought they're hardcoded (ex: https://proudcity.com/solutions is linking to https://example.proudcity.com/proudcity.com/solutions).

See middle column of footer here: https://example.proudcity.com/

Here's the HTML code:

```
<ul class="list-unstyled">
<li><a href="https:/proudcity.com/solutions">Solutions</a></li>
<li><a href="https:/proudcity.com//meetings">Meetings</a></li>
	<li><a href="https:/proudcity.com//websites">Websites</a></li>
<li><a href="https:/proudcity.com//forms">Forms</a></li>
<li><a href="https:/proudcity.com//payments">Payments</a></li>
</ul>
```

Screenshot:

<img width="1073" alt="screen shot 2019-01-17 at 2 24 52 pm" src="https://user-images.githubusercontent.com/1569463/51353283-0d612480-1a65-11e9-8a49-1b174d812a5b.png">

**Comment by aschmoe** [comment]
@lukefretwell `https:/p` needs to be `https://p`

**Comment by lukefretwell** [comment]
@aschmoe guess I needed to sleep on it. 😆
