### ISSUE TITLE
Meetings: Do not show Agenda Packet tab if no agenda exists

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1505]
@jlyon @lukefretwell @aschmoe this feedback came in from Fairfax for posting meetings. What do you guys think is the best way to address this?

It has come to my attention that when I create a meeting it automatically says that there is an agenda, especially if I enter any text in the "Agenda Text" box. We are require by law to state that the agenda will be posted 72 hours in advance of the meeting, so I have to use that text box even before I have an agenda to post. Can you please look into an option that would allow us to decide when it shows "Agenda" as a media/content item - such as when we upload the PDF of the agenda, then it will show in the Content column?

In the short term, I have hidden the column for "Content" but this is not a long term option for all new meetings that I set up.

Thank you!

**Comment by lukefretwell** [comment]
I'd just not show the tab unless there's content, like we do for video/audio (and minutes?).

**Comment by jlyon** [comment]
I adjusted this so the Agenda Packet tab only shows if agenda text or an agenda pdf exist:

before:
![before](https://user-images.githubusercontent.com/550909/51696750-07b29400-1fbb-11e9-87f9-83245f282dad.png)


after:
![after](https://user-images.githubusercontent.com/550909/51696746-041f0d00-1fbb-11e9-980d-7b0552d51091.png)

**Comment by kevindherman** [comment]
@jlyon they still use that text box to make a legal statement that agendas will be posted 72 hours in advance so if they did that, the agenda pill would show. 

Could there be a hide pill option that they would select until they actually enter agenda info and/or attach a file.
