### ISSUE TITLE
Dashboard: create a ticket and request a feature link update

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1508]
![screenshot 2019-01-24 15 13 41](https://user-images.githubusercontent.com/6032426/51705986-24ff5680-1feb-11e9-9cca-cda5c7b04a01.png)

Goes to page not found: https://proudcity.com/support/create

But should go here: https://help.proudcity.com/submit/

Request a feature has the same problem, should it link to the same form or duplicate the support form and change to "request a feature".

**Comment by jlyon** [comment]
@kevindherman updated in the Help menu:
Create a Ticket
Suggest a feature - pre-checks the appropriate checkbox

And in topnav:
Feature request
