### ISSUE TITLE
Meetings: create recurring meetings option

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1512]
Fairfax and Lucas both mentioned having the ability to have recurring meetings as a feature like recurring events. I know that that plugin has been challenging so I'm assuming adding that feature wouldn't be super easy, however, the recurring events was setup with meetings in mind so something we should have on our radar. 

@jlyon @aschmoe what do you think?

**Comment by jlyon** [comment]
Yeah, probably wouldn't be super simple.  It doesn't seem like we could use the event plugin we're currently using and just extend it to recurring meetings without hacking around.  And that plugin isn't that great anyways. But good to have on the radar.
