### ISSUE TITLE
city-template.proudcity.com keeps showing up

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1513]
https://www.townoffairfax.org/meetings/town-council-special-meeting-budget-workshop-may-25-2018/
![screenshot 2019-01-29 14 25 34](https://user-images.githubusercontent.com/6032426/51934518-c7478180-23d1-11e9-8135-1481099943db.png)

Links to https://city-template.proudcity.com/?post_type=agency&p=2790

Even though there is a Town Council Dept on the Fairfax site: https://www.townoffairfax.org/departments/town-council/

This isn't an emergency because they will be removing contacts within the meetings, however, this is likely a platform issue. I will look around for other instances.

**Comment by jlyon** [comment]
Also showed up on Bedford

**Comment by jlyon** [comment]
@kevindherman I fixed the issue with the Johnson City broken link checker  https://johnson-city-tx.proudcity.com/wp-admin/tools.php?page=view-broken-links.

I also put together a migration to run on every site to fix this.  I'll also run the same command when we spin up sites (changing the url from city-template.pc.com to my-city.pc.com) so this shouldn't pop up again.

**Comment by kevindherman** [comment]
@jlyon dope.
