### ISSUE TITLE
SR + SR Parks: events not displaying

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1517]
On both San Rafael an their parks subsite they are reporting that events created are not being displayed on their event list widgets which I verified:

https://www.livelifelocally.org/events

<img width="1203" alt="screenshot 2019-02-02 13 35 14" src="https://user-images.githubusercontent.com/6032426/52167862-b6f41700-26ef-11e9-9fef-38b3b187dbb9.png">
<img width="1247" alt="screenshot 2019-02-02 13 35 21" src="https://user-images.githubusercontent.com/6032426/52167863-b6f41700-26ef-11e9-9b40-876ebcd5cae0.png">

**Comment by aschmoe** [comment]
@kevindherman re-indexed these, seems to be working ok.
