### ISSUE TITLE
Application field filled but application button/link doesn't appear on jobs listing

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1518]
The job application button/link does not appear on the job listing even though the field for application is filled out to go to: https://example.proudcity.com/documents/general-job-application/

Job posting:
https://example.proudcity.com/job/proudcity-city-manager/

Dash view:
![screenshot 2019-02-05 10 39 39](https://user-images.githubusercontent.com/6032426/52284592-b5666100-2932-11e9-8a9f-e58bfcfb3bfc.png)

I noticed this is also happening on Kettering: https://www.ketteringoh.org/jobs

They use that field to link to an email address rather than a page in the example above.

**Comment by jlyon** [comment]
@aschmoe do you remember doing anything with this?  It looks like we're just not drawing the Apply button anywhere in `wp-content/themes/wp-proud-theme/templates/content-single-job_listing.php`.  I think we need to call `get_the_job_application_method()` from `wp-content/plugins/wp-job-manager/wp-job-manager-template.php`, or maybe (from `wp-content/plugins/wp-job-manager/templates/content-single-job_listing.php`):
```
		<?php if ( candidates_can_apply() ) : ?>
			<?php get_job_manager_template( 'job-application.php' ); ?>
		<?php endif; ?>

```
