### ISSUE TITLE
Lucas: missing files in media library

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1520]
@aschmoe @jlyon A bunch of old newsletter files on Lucas aren't showing in the preview or if you select download. 
https://www.lucastexas.us/documents/newsletter-january-2014/
![screenshot 2019-02-12 13 08 55](https://user-images.githubusercontent.com/6032426/52657820-7eaac080-2ec7-11e9-878d-a348ab10df9f.png)

It's several of the 2014 and 2015 newsletters from this page: https://www.lucastexas.us/newsletters?pager=3&

Here are some additional file examples that the customer shared:
https://storage.googleapis.com/proudcity/lucastx/uploads/2016/09/November-2014-Newsletter.pdf

https://storage.googleapis.com/proudcity/lucastx/uploads/2016/09/August-2014-Newsletter.pdf

https://storage.googleapis.com/proudcity/lucastx/uploads/2016/09/May-2014-Newsletter.pdf

https://storage.googleapis.com/proudcity/lucastx/uploads/2016/09/March-2014-Newsletter.pdf

https://storage.googleapis.com/proudcity/lucastx/uploads/2016/09/February-2014-Newsletter.pdf

https://storage.googleapis.com/proudcity/lucastx/uploads/2016/09/January-2014-Newsletter.pdf

**Comment by jlyon** [comment]
@kevindherman All of these files exist on the server and have a filesize (for example I am able to download https://www.lucastexas.us/documents/newsletter-january-2014/, and it is 250kb big, but I cannot open it), so this appears to be an issue with the files that were uploaded originally, and not an issue with ProudCity.

I tried a couple of online converter tools and none of them could open the files, so there isn't much we can do unfortunately.
