### ISSUE TITLE
Lucas: analytics dashboard pulling from other instances

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1521]
The analytics dashboard for Lucas is pulling page results from other instances:

You can see a result for Ruston and Warr Acres in this screenshot:
<img width="1191" alt="screenshot 2019-02-12 18 13 54" src="https://user-images.githubusercontent.com/6032426/52674641-305ee700-2ef2-11e9-842f-e7433e1910bc.png">

I did a quick site search and those pages don't exist on the site so it's just something odd with those analytics getting crossed up. Those are the only ones I caught because they say the city name in the title so it's hard to know how pervasive the issue is. 

@jlyon

**Comment by jlyon** [comment]
@kevindherman I fixed the view ID in the Analytics settings within the dashboard and this should now be fixed.

**Comment by kevindherman** [comment]
@jlyon looks good.
