### ISSUE TITLE
ELGL: enable reCAPTCHA

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1522]

**Comment by jlyon** [comment]
@kevindherman is this for gravityforms, or something else? I set up the Gravityforms recaptcha keys on https://elgl.org/wp-admin/admin.php?page=gf_settings.

**Comment by kevindherman** [comment]
@jlyon this is for gravity forms. Is this something I can do? I'm not sure where you get that key information on that page.

Since it's for gravity forms, does anything else need to happen?

**Comment by jlyon** [comment]
@kevindherman I enabled it, so I _think_ they should be set, but it might need to be enabled on each form.

**Comment by kevindherman** [comment]
@jlyon this is firing on all forms. Ready to close.
