### ISSUE TITLE
PC.com service center missing icon

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#1523]
![screen shot 2019-02-20 at 1 11 34 am](https://user-images.githubusercontent.com/1634686/53080053-ae039380-34ac-11e9-998b-c60f081ee159.png)

**Comment by aschmoe** [comment]
[Uploading Screen Shot 2019-02-20 at 1.11.34 AM.png...]

**Comment by aschmoe** [comment]
@jlyon you know how to fix this?

**Comment by jlyon** [comment]
hmm, I thought it was here, but that didnt seem to fix it. I'll dig into it a little later
![screenshot 95](https://user-images.githubusercontent.com/550909/53112164-871c8000-34f3-11e9-96d8-2ad71f5f97c3.png)
