### ISSUE TITLE
Marin Recovers: stylized password protection

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1525]
Create a more stylized password protected page to include:

- Color
- Logo
- Login to view site
- Text area that can be edited by site admin to provide context. Here's is the placeholder content:

“The Marin Recovers website is currently dormant. It will be activated in the event of a multi-jurisdictional disaster with up-to-date information from local governments, public safety agencies and public information officers about response and recovery efforts. If you are seeking information about a specific incident, please contact your local jurisdiction for information. ”

@jlyon

**Comment by jlyon** [comment]
@kevindherman I played around with this for awhile. It seems like we can add a pass protect page with a logo (see below).  Probably the easiest way to add the above language is to just create a logo with the text right below it (which I can do).
![Screen Shot 2019-02-26 at 10.26.36 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560b69d9fa23ba3d0063c62a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77216456f56b7191a379ef0c2957415c48bc21254d58eeb9cb74fce36f34985619e8d7645f75cf3e19f8ed8b49be55b8268b4f82b1b58c44c4fa2137a5dad11b61435c52dcbd4f3fb29843c259f34ee04f51ad113262ee70376e0a.png)

**Comment by kevindherman** [comment]
@jlyon if there's a quick way to have a text editor I think it would be helpful to limit dependency.

**Comment by jlyon** [comment]
@kevindherman this plugin i was using didn't make it easy to add text. I'll try to try again in the morning.

**Comment by kevindherman** [comment]
@jlyon was the banner approach weird or is there a conflict because they'll probably be using the banner in the case of an emergency>?
