### ISSUE TITLE
Update service center Federal holidays

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1526]
https://www.redcort.com/us-federal-bank-holidays/

**Comment by jlyon** [comment]
@kevindherman I updated these for 2019 (based on the above link), and pushed to SR.  The rest of the platform will get it with the release.

I think it's better to keep one master copy of this rather than make it editable by each city, because then they would each have to remember to update them every year.  I created a cal invite and invited you and me.

**Comment by kevindherman** [comment]
@jlyon I'm not getting the 2019 content on SR (incognito window). The release is a fine ETA if needed.
