### ISSUE TITLE
Department: Allow contact link to be a url or email

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1532]
When editing/setting up a department, can the "contact name link" be an email address? When it's an email on this page it redirects to the homepage rather than popping out an sendto link.

https://www.danversma.gov/departments/council-on-aging/

https://www.danversma.gov/wp-admin/post.php?post=3436&action=edit
![screenshot 2019-03-07 11 43 17](https://user-images.githubusercontent.com/6032426/53973299-80cefc00-40ce-11e9-9fb0-5b6cf07afc04.png)

**Comment by jlyon** [comment]
This is fixed @kevindherman
