### ISSUE TITLE
ELGL social wall showing IG when not selected

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1534]
The social wall on the homepage is displaying IG even though the service is deselected on the back end. 

https://elgl.org/

![Screen Shot 2019-03-23 at 4 29 12 PM](https://user-images.githubusercontent.com/6032426/54931246-06381600-4eef-11e9-9ee8-79fbf98cb2c8.png)
![Screen Shot 2019-03-23 at 4 29 37 PM](https://user-images.githubusercontent.com/6032426/54931247-06381600-4eef-11e9-8f96-2cccc479a180.png)

**Comment by jlyon** [comment]
@aschmoe should we just delete all insta posts in the db for now?

See #1293 for the potential long-term path forward.
