### ISSUE TITLE
Default icon colors to primary color

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1535]
Can we default the icon colors to the primary customized color? Many of the secondary colors aren't as accessible as we'd like.

<img width="1427" alt="Screen Shot 2019-03-26 at 9 07 22 AM" src="https://user-images.githubusercontent.com/1569463/55018647-8d00f780-4fb0-11e9-870a-b9587737926c.png">

**Comment by jlyon** [comment]
@lukefretwell @aschmoe @kevindherman 

I made the button color the topnav color.  Here's a list of all of the colors in the customizer:
<img width="242" alt="Screen Shot 2019-03-28 at 7 11 47 PM" src="https://user-images.githubusercontent.com/550909/55204757-719f1380-518d-11e9-93c9-de008aa3ef0b.png">
