### ISSUE TITLE
SR: PAC report not running

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1536]
I'm also not able to get the report to run as outlined in the support ticket below:
![Screenshot 2019-03-27 12 37 58](https://user-images.githubusercontent.com/6032426/55094646-2998c780-508d-11e9-964c-c587a14a29b5.png)

Accessibility test works with homepage but is hanging on interior pages.

I have tried running a test of our new center and on a page on the Community Development site. www.cityofsanrafael.org/news
www.livelifelocally.org/departments/programs
The test results haven't shown up after 30+ minutes of running. I have tried twice to get these links to report.

Thanks in advance,

Sean

**Comment by aschmoe** [comment]
@kevindherman @lukefretwell @jlyon database was full (free tier) I deleted results past 1/1/2019 so new results can now be created.

We should probably delete results older than 3months every couple months.

**Comment by aschmoe** [comment]
Last run for all sites seems to be March 15th 2019.

**Comment by aschmoe** [comment]
Other fun fact: we have 34 "orgs" in the db (each one is separate) with 34 watches set, so not many sites are leveraging.
