### ISSUE TITLE
/feedback page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#154]
Create /feedback page for LIVE sites.

**Comment by aschmoe** [comment]
@kevindherman @jlyon created this https://west-carrollton-oh.proudcity.com/feedback/, but could maybe use some love.  Maybe pass to the client for copy Kevin?

**Comment by kevindherman** [comment]
Thanks for setting this up @aschmoe. Content should be standardized so let's hold off on pilot feedback until we have this page in a good place.

I think Philadelphia's alpha does a good job getting feedback/bug reporting: https://alpha.phila.gov/feedback/

**Comment by jlyon** [comment]
@aschmoe were you going to set this up, or should I?

**Comment by aschmoe** [comment]
Yeah I'll get this set up tonight.

**Comment by kevindherman** [comment]
@aschmoe in Chrom the radio buttons are slightly cut off on the left side.

**Comment by aschmoe** [comment]
Mac?

**Comment by kevindherman** [comment]
Yeah

**Comment by aschmoe** [comment]
Which OS version are you on ?  Not seeing that in any chrome versions on browserstack

**Comment by kevindherman** [comment]
Mac OS X El Capitan version 10.11.2 (15C50)

On Tue, Feb 23, 2016 at 1:19 PM, Alex Schmoe <notifications@github.com>
wrote:

> Which OS version are you on ? Not seeing that in any chrome versions on
> browserstack
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/154#issuecomment-187827806>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by kevindherman** [comment]
It's when I'm on a large monitor. When I dragged the page over to my laptop
and resized the browser the problem went away.

On Tue, Feb 23, 2016 at 2:38 PM, Kevin Herman <kevin@proudcity.com> wrote:

> Mac OS X El Capitan version 10.11.2 (15C50)
>
> On Tue, Feb 23, 2016 at 1:19 PM, Alex Schmoe <notifications@github.com>
> wrote:
>
>> Which OS version are you on ? Not seeing that in any chrome versions on
>> browserstack
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/proudcity/wp-proudcity/issues/154#issuecomment-187827806>
>> .
>>
>
>
>
> --
> Kevin Herman
> ProudCity
> 917.873.4666
> ProudCity.com
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by aschmoe** [comment]
@kevindherman I can't really test that, but added a little margin so hopefully fixed.  Lemme know

**Comment by kevindherman** [comment]
That did the trick.

On Tue, Feb 23, 2016 at 5:28 PM, Alex Schmoe <notifications@github.com>
wrote:

> @kevindherman <https://github.com/kevindherman> I can't really test that,
> but added a little margin so hopefully fixed. Lemme know
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/154#issuecomment-187943688>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
