### ISSUE TITLE
Color customization fix

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1541]
Can we make these changes to the customization tool to ensure it's more bullet-proof and clear on what's actually being changed?

* Change 'Link color' description to 'Primary color.'
* Make links, icon color and service center tabs the 'Primary color' (There are situations where the top bar will be white, which will make the icons white. Defaulting to the 'Primary color' will ensure this will never happen.).
* Change 'Highlight' color description to 'Secondary color' and make hover links and service center highlighted tabs the 'Secondary color.'

![Screen Shot 2019-04-09 at 2 59 18 PM (2)](https://user-images.githubusercontent.com/1569463/55838739-4cd66480-5ada-11e9-863c-a788144c0f81.png)

**Comment by jlyon** [comment]
color_highlight = Secondary
color_link = Primary

**Comment by jlyon** [comment]
Here's an example of how this looks now:

<img width="1440" alt="Screen Shot 2019-04-11 at 9 17 30 PM" src="https://user-images.githubusercontent.com/550909/56012347-f10a0800-5ca0-11e9-8067-8baccb0c072e.png">

**Comment by jlyon** [comment]
@lukefretwell @kevindherman @aschmoe after more testing in the release, we reverted this change. We will need to do more testing/planning before pushing this probably.

new background buttons
![Screenshot of Home - City of Warr Acres](https://user-images.githubusercontent.com/550909/56016400-fa02d580-5cb0-11e9-9ea2-cac108825076.jpg)

vs old …
![Screenshot of Home - City of Warr Acres (1)](https://user-images.githubusercontent.com/550909/56016409-00914d00-5cb1-11e9-8dec-9021919b5652.jpg)
