### ISSUE TITLE
Meetings: address line 2 not showing on front-end

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1544]
Address line 2 for the meeting location is not displaying on the front-end. This line is often used for a meeting room location so it's actually pretty important.
Meeting: https://scscroundtable.org/meetings/sc-sc-roundtable/

Location detail: https://scscroundtable.org/wp-admin/post.php?post=4862&action=edit

<img width="966" alt="Screenshot 2019-04-17 22 03 02" src="https://user-images.githubusercontent.com/6032426/56332165-3b85fb80-615d-11e9-8301-fa6ab2d52a5c.png">

<img width="559" alt="Screenshot 2019-04-17 22 07 25" src="https://user-images.githubusercontent.com/6032426/56332166-3b85fb80-615d-11e9-8d99-0a462a458d34.png">

**Comment by jlyon** [comment]
Fixed this. Will go up in the next release @kevindherman

**Comment by kevindherman** [comment]
@jlyon awesome.
