### ISSUE TITLE
Feedback: remove list category button from list

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#155]
We've received feedback from two different end user's that they are unable to download documents. Both instances the user was trying to click on the document category on pages uses the doc list widget: https://west-carrollton-oh.proudcity.com/city-council-minutes/

Since there's only one category on those pages the buttons are confusing, can the category button view be disabled on the widget?

X's in screenshot show which buttons don't link to a download:
![screenshot 2016-02-17 14 36 32](https://cloud.githubusercontent.com/assets/6032426/13122564/8adac7ae-d585-11e5-8e40-4c0399cd5128.png)

**Comment by jlyon** [comment]
Downloads: Could we get browser information from the users that had problems with the buttons?  Did they have issues downloading it on the document page (https://west-carrollton-oh.proudcity.com/documents/december-15-2015-council-minutes/).

Removing category label: Not super simple since this widget is supposed to be reusable. I'll have to think about the best way to do it.

**Comment by kevindherman** [comment]
It was reported in IE and Chrome and I was able to replicate in Chrome as
well. There isn't any issue with the download buttons it's that for some
reason some users are clicking on the category button to initiate the
download. Maybe making it less button looking will deter people from
clicking on it.

Happy to talk through some ideas.


On Wed, Feb 17, 2016 at 7:04 PM, Jeff Lyon <notifications@github.com> wrote:

> Downloads: Could we get browser information from the users that had
> problems with the buttons? Did they have issues downloading it on the
> document page (
> https://west-carrollton-oh.proudcity.com/documents/december-15-2015-council-minutes/
> ).
>
> Removing category label: Not super simple since this widget is supposed to
> be reusable. I'll have to think about the best way to do it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/155#issuecomment-185467681>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by jlyon** [comment]
Hid the category buttons in lists where all of the documents are of the same category (ex: /city-council-minutes/). @kevindherman

**Comment by jlyon** [comment]
do you think making the labels smaller would help?
![screenshot from 2016-02-22 18 22 01](https://cloud.githubusercontent.com/assets/550909/13239721/3b52e6b6-d991-11e5-9ce0-a0c8df7bc8dd.png)

**Comment by kevindherman** [comment]
It helps in the doc library but still should hide it on the widget.

**Comment by kevindherman** [comment]
This looks good.

On Mon, Feb 22, 2016 at 10:09 PM, Kevin Herman <kevin@proudcity.com> wrote:

> It helps in the doc library but still should hide it on the widget.
>
> Sent from my iPhone
>
> On Feb 22, 2016, at 9:22 PM, Jeff Lyon <notifications@github.com> wrote:
>
> do you think making the labels smaller would help?
> [image: screenshot from 2016-02-22 18 22 01]
> <https://cloud.githubusercontent.com/assets/550909/13239721/3b52e6b6-d991-11e5-9ce0-a0c8df7bc8dd.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/155#issuecomment-187488346>
> .
>
>


-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
