### ISSUE TITLE
Oakwood: Services Map (wordpress) yielding spinning circle rather than location results

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1551]
After switching the services map to wordpress and adding custom/manual locations and layers the map is producing a spinngin wheel instead of the pins.

https://oakwood-oh.proudcity.com/community/
![Screenshot 2019-05-06 14 19 58](https://user-images.githubusercontent.com/6032426/57246095-749de700-700a-11e9-859d-c2764ee89e20.png)

**Comment by jlyon** [comment]
@kevindherman it looks like the lat/lng was not getting set.
![Screenshot (1)](https://user-images.githubusercontent.com/550909/57270454-2f94a780-7040-11e9-9ae3-98b180e27c1e.png)

Typically this gets added automatically by using the google places selector

You can verify that it is set by checking the "Manually set" checkbox.

If they are using the places selector and the lat/lng is not getting set, or if they aren't seeing the places selector, there is most likely a Javascript error. Try to get a browser/version (and OS), and we can see if we can replicate it.

I updated their 5 locations and I'm not seeing the issue anymore.

**Comment by kevindherman** [comment]
@jlyon wouldn't you only need the custom lat/long if you don't have an address?

**Comment by jlyon** [comment]
No the pins are placed using the lat long values.  The values are just
usually set because people select the address from the Google places
autocomplete.
