### ISSUE TITLE
WC: Add West Carrollton under logo in the footer

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#156]

**Comment by jlyon** [comment]
We removed this text a week or two ago (I think we discussed it on a huddle and decided it would be best to remove it). Is this a request from the client? Can we do it across all sites?

**Comment by kevindherman** [comment]
It was a request from the client because they have pretty strict rules
about having the name under the logo and she said it comes across as
hypocritical with it removed.

On Wed, Feb 17, 2016 at 7:06 PM, Jeff Lyon <notifications@github.com> wrote:

> We removed this text a week or two ago (I think we discussed it on a
> huddle and decided it would be best to remove it). Is this a request from
> the client? Can we do it across all sites?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/156#issuecomment-185468287>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by jlyon** [comment]
Should we just let cities choose an optional footer logo (default it to the main logo), and we can use the version of the WC logo with the text?

**Comment by kevindherman** [comment]
That makes sense to me.

On Thu, Feb 18, 2016 at 3:52 PM, Jeff Lyon <notifications@github.com> wrote:

> Should we just let cities choose an optional footer logo (default it to
> the main logo), and we can use the version of the WC logo with the text?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/156#issuecomment-185914112>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by aschmoe** [comment]
@jlyon you taking care of this, or should I?

**Comment by jlyon** [comment]
@kevindherman set this up

**Comment by kevindherman** [comment]
I've refreshed a few times and tried in other browsers and still not seeing
the update. I'll clear my caches and try again.

On Tue, Feb 23, 2016 at 3:01 AM, Jeff Lyon <notifications@github.com> wrote:

> @kevindherman <https://github.com/kevindherman> set this up
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/156#issuecomment-187593115>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by kevindherman** [comment]
Working for me now. Thanks Jeff.

On Tue, Feb 23, 2016 at 8:19 AM, Kevin Herman <kevin@proudcity.com> wrote:

> I've refreshed a few times and tried in other browsers and still not
> seeing the update. I'll clear my caches and try again.
>
> On Tue, Feb 23, 2016 at 3:01 AM, Jeff Lyon <notifications@github.com>
> wrote:
>
>> @kevindherman <https://github.com/kevindherman> set this up
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/proudcity/wp-proudcity/issues/156#issuecomment-187593115>
>> .
>>
>
>
>
> --
> Kevin Herman
> ProudCity
> 917.873.4666
> ProudCity.com
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
