### ISSUE TITLE
File upload webform field error

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1560]
The upload file field on webform is yielding an error when uploading a file. 

https://www.goshen-ma.us/feedback
<img width="891" alt="Screenshot 2019-05-12 11 31 50" src="https://user-images.githubusercontent.com/6032426/57584484-d4ccd700-74a9-11e9-94b4-add208341d7b.png">

Here's the file I was trying to upload:
![IMG_1539](https://user-images.githubusercontent.com/6032426/57584485-dd251200-74a9-11e9-90e9-bb1b35b4d1ee.jpg)

This is an item a couple of the cities I'm onboarding are using for report an issue so it may become a higher priority if it's not a one off item.

**Comment by jlyon** [comment]
This should be working in wp-stateless 
![Screenshot (15)](https://user-images.githubusercontent.com/550909/58282423-8ac1dc00-7d5a-11e9-83ec-d6c1f5ffb9a9.png)

related:
https://github.com/wpCloud/wp-stateless/issues/2

**Comment by jlyon** [comment]
@kevindherman we determined on the call that the fix for this was to disable the multi-upload field. The forms upload only works for the single field instances.
