### ISSUE TITLE
Update nav button 'on' background color CSS

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1562]
Looks like the 'on' background color for the main tab when it's set to a white background isn't accessible.

Suggestion for all 'on' buttons in the navigation: 

* Make background the 'Secondary' color
* Make text color (+hover) white

<img width="288" alt="Screen Shot 2019-05-14 at 8 34 20 AM" src="https://user-images.githubusercontent.com/1569463/57739390-46528400-7668-11e9-8a88-cf7aa1b33c91.png">

**Comment by kevindherman** [comment]
@aschmoe as of now, the specific concern for this is on Jackson.

**Comment by kevindherman** [comment]
- https://www.johnsoncitytx.org/
- https://www.warracres-ok.gov/
- https://www.jacksonms.gov/

@aschmoe

**Comment by aschmoe** [comment]
@kevindherman deployed a "fix" for this, most look good, I'm sure that some do not quite

**Comment by kevindherman** [comment]
@aschmoe definitely better on the white bg main nav sites.

I'll keep an eye out for weird ones.

**Comment by lukefretwell** [comment]
I think this can be closed @kevindherman @aschmoe .
