### ISSUE TITLE
Equal columns height bug

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1565]
@aschmoe how can we add CSS to make these equal height. 

Looks like this isn't working: http://getbootstrap.com.vn/examples/equal-height-columns/

@kevindherman mentioned this may not be added for certain areas?

https://getbootstrap.com/docs/4.0/utilities/flex/

Can we get this updated so P can add CSS for equal column heights?

Example here:

<img width="1358" alt="Screen Shot 2019-05-16 at 1 37 25 PM" src="https://user-images.githubusercontent.com/1569463/57885452-d1a25580-77df-11e9-8a56-eb83e33ad279.png">

**Comment by aschmoe** [comment]
@lukefretwell we're on bootstrap 3, so not surprising whatever snippets you're pasting aren't working (also it looked like to me in pagebuilder you had pasted `.js-equal` into the class box when it is expecting `js-qual`).  

We have similar utility, I've extended it to a class, feel free to use: `class="equalize-columns"`
