### ISSUE TITLE
Fix Save meeting save calendar button timezone

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1569]
When you download an event it doesn't save as pacific timezone even though that's what the site is set to and displays as on the website:

<img width="1406" alt="image001 (1)" src="https://user-images.githubusercontent.com/6032426/58112295-39321980-7bc1-11e9-9518-c91a2c0bd6e6.png">

https://scscroundtable.org/

**Comment by kevindherman** [comment]
@jlyon it looks like this item is a Meetings content type to help narrow down the troubleshooting.

**Comment by jlyon** [comment]
@kevindherman fixed this for the next release. This was limited only to meeting posts. Fixed this in the List Teaser view and the full page detail view.
