### ISSUE TITLE
Sonoma: clone page option missing from pages

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1570]
The ability to clone pages is not available in the dashboard from the all pages list:

![Screenshot 2019-05-23 11 51 56](https://user-images.githubusercontent.com/6032426/58267278-4ed64900-7d51-11e9-887b-506ccb501129.png)

This is the case on sonoma when logged in as an admin level. 
https://www.sonomacity.org/
@jlyon

**Comment by jlyon** [comment]
Use the bulk operations
<img width="482" alt="Screen Shot 2019-05-23 at 12 50 01 PM" src="https://user-images.githubusercontent.com/550909/58281976-513ca100-7d59-11e9-8630-864ebd24be55.png">

**Comment by kevindherman** [comment]
@jlyon got it.
