### ISSUE TITLE
Petaluma: full width featured image on card view widgets

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1576]
[preview-full-card.view.notes2 (1).pdf](https://github.com/proudcity/wp-proudcity/files/3288107/preview-full-card.view.notes2.1.pdf)

@aschmoe is it an easy fix to have the card view have a full width featured image with a color bg for the text area?

**Comment by lukefretwell** [comment]
@kevindherman I played with this. Looks like @aschmoe will need to figure out how to remove the 'absolute position left ...' code from the template (@aschmoe is there a way to move that to the CSS). If yes, the rest can be done with CSS.

I'm not sure how we're getting the text, but I think they're  'text pulled from title' is dependent upon what is placed in the post itself.

Overall, I think this is too much of an effort unless they want to add additional resources to develop it out more. Even then, it's kind of putting a square peg into a round hole.

**Comment by kevindherman** [comment]
@lukefretwell @aschmoe her example image isn't great since it has writing on it. The top part is a featured image from a news post. The bottom is the news post title with a color background.

What's the level of effort to just have the featured image me full width if the color bg is problematic.

**Comment by jlyon** [comment]
This is done pending some issues with the widths on the 1-1-2-1 row from https://github.com/proudcity/wp-proudcity/issues/1578 @kevindherman

**Comment by kevindherman** [comment]
@jlyon thanks for the update. @aschmoe implemented the 1-1-2-1  earlier in the week so he can probably help you close out if needed.

**Comment by jlyon** [comment]
This has been fully deployed to https://petaluma-ca.proudcity.com/ @kevindherman. It applies to pretty much every `.card` class, so there might be some cases where we don't want the brown bg (like the social wall cards maybe?). LMK if you notice anywhere where it doesn't look right and I can tweak the css code.

**Comment by jlyon** [comment]
This has been deployed @kevindherman. I just added some custom CSS and JS code to make the default Image widget work for them.  Setup steps:

1. Upload an appropriately large image to use - for tall images 450 x 715px; for the smaller horizontal images 450 x 260px)
![Screenshot (22)](https://user-images.githubusercontent.com/550909/59568687-0a2d8d00-9033-11e9-8406-661fc5800937.png)

**Comment by kevindherman** [comment]
@jlyon example news list widget card view not on dept page: https://petaluma-ca.proudcity.com/training-dept-news/

**Comment by jlyon** [comment]
@kevindherman this is working as designed.  We don't want massive images for those thumbnails because it will slow down page load speeds.  Because the site is full-width, the'll see the border around the cards if the content is too big.  I suggest only using the cards if there is a left sidebar or the some kind of page builder 50%/50% style like what is on https://petaluma-ca.proudcity.com/training-dept-news/ now.  They can also use the Content List for news with the first item featured, like SR do.

**Comment by aschmoe** [comment]
@kevindherman recommendations around this have shifted slightly: 

the two smaller images (columns 3+4) should be using the new size setting "Medium Square (600pxx600px)"
