### ISSUE TITLE
Petaluma: card view changes

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1578]
Using the template page and PDF mockups below to make changes to card view to have a brown background with white font and hopefully increase the size of the image as well. @aschmoe you also mentioned using this strategy for the images they are using on the dept template. If you could provide some notes on that so I can let them know what you're going to implement that would be helpful. 

Thanks again.

https://petaluma-ca.proudcity.com/template-department-1/

[preview-full-card.view.notes2 (1).pdf](https://github.com/proudcity/wp-proudcity/files/3288105/preview-full-card.view.notes2.1.pdf)

**Comment by jlyon** [comment]
- New widget for image and link and title
- All card views (news, events)

**Comment by aschmoe** [comment]
- Title text box with brown text background
- resize the teaser image widget to square, a bit larger

**Comment by jlyon** [comment]
@kevindherman I set most of this up, but there is still something weird going on with our CSS. I'll talk to @aschmoe about it in the morning.

**Comment by kevindherman** [comment]
@jlyon great, thanks for the update.

**Comment by jlyon** [comment]
This has been fully deployed to https://petaluma-ca.proudcity.com/ @kevindherman. It applies to pretty much every `.card` class, so there might be some cases where we don't want the brown bg (like the social wall cards maybe?). LMK if you notice anywhere where it doesn't look right and I can tweak the css code.

**Comment by kevindherman** [comment]
@jlyon this is great. I think the social wall is the only place to omit the brown bg.

**Comment by jlyon** [comment]
@kevindherman updated css so social wall cards have white bgs

**Comment by kevindherman** [comment]
@jlyon looks good.
