### ISSUE TITLE
IE Testing

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#158]
WC:
 chrome is 42% of their traffic, ie is only 23%
ie breakdown: 11=82% (1075), 10=9% (119), 9=6% (78), 8=1% (16), 7=1% (11)

**Comment by aschmoe** [comment]
Everything is doing pretty good

IE8 - problematic but appears ok; message is displayed
IE9 - looks great, a couple errors, social wall struggling; message is displayed
IE10 - Looks perfect to me
