### ISSUE TITLE
Petaluma: mobile main nav menu

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1580]
Petaluma main nav has weird white area next to the icons when resizing down to mobile:

![Screenshot 2019-06-13 15 30 30](https://user-images.githubusercontent.com/6032426/59461866-5fc62780-8df0-11e9-8156-2d035ceb6e43.png)

**Comment by jlyon** [comment]
I am now hiding the "Official city website" text on mobile:

![Screenshot (23)](https://user-images.githubusercontent.com/550909/59568764-fe8e9600-9033-11e9-95cc-01497780d16a.png)

@kevindherman
