### ISSUE TITLE
Petaluma: move dept menu under hero unit on dept pages in mobile view

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1581]
The dept menu on this page (what will be the dept template) is buried at the bottom of the page in mobile view: https://petaluma-ca.proudcity.com/template-department-1/

@jlyon please default the menu to be under the hero unit (or top image) in mobile view so it looks like SR: https://www.cityofsanrafael.org/departments/city-managers-office/

**Comment by jlyon** [comment]
@kevindherman I set this up so the mobile menu appears below the main menu when you click on the menu icon in the bottom right:
<img width="472" alt="Screen Shot 2019-06-16 at 12 38 06 PM" src="https://user-images.githubusercontent.com/550909/59568736-aeafcf00-9033-11e9-9444-46e163d41b6b.png">


The menu still appears on the mobile page where it normally would. Let me know if you think we should remove it:
![Screenshot (23)](https://user-images.githubusercontent.com/550909/59568745-c25b3580-9033-11e9-95e1-b4362950927b.png)

**Comment by aschmoe** [comment]
@kevindherman, I will leave this edit for now, but I've also added a second approach just hiding / showing the row on mobile / larger views since the other pages will have the mobile menu.... seems confusing to have in multiple places

**Comment by kevindherman** [comment]
@aschmoe thanks.
