### ISSUE TITLE
Calendar category shows pantone number

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1585]
Calendar categories display pantone number next to event category name.

https://rye-brook-ny.proudcity.com/departments/parks-recreation/ (bottom left column)
![Screenshot 2019-06-26 13 08 05](https://user-images.githubusercontent.com/6032426/60200291-d6611d00-9813-11e9-9d69-ed37ec636691.png)

**Comment by kevindherman** [comment]
@aschmoe this page has the calendar embedded on the left side column https://rye-brook-ny.proudcity.com/departments/senior-services/

**Comment by jlyon** [comment]
@aschmoe fixed this in teh release
