### ISSUE TITLE
Warr Acres: white main nav and white font issue

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1587]
![Screenshot 2019-06-27 16 33 05](https://user-images.githubusercontent.com/6032426/60298849-662cc700-98f9-11e9-81f1-92d1dc9b7ce1.png)

**Comment by jlyon** [comment]
@kevindherman I wasn't able to replicate this testing in
IE 10
IE 11
IE 9
Edge 14

I did change the topnav background back to white and I added CSS to force the text color to be black, so the issue _should_ be fixed for him, but there's no way for me to test for sure.
