### ISSUE TITLE
Add page builder breadcrumb widget

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1588]
Create dept breadcrumb widget.

This is being done with the division layout strategy in mind: 

https://jackson-ms.proudcity.com/purchasing-division/

**Comment by aschmoe** [comment]
@kevindherman 

Added this breadcrumb widget, it now has the similar rules as the "Hero" widget where if it is item 1 in the page builder, and the "Override page header?" is checked, the mobile menu will be hidden.  I think this gives us the most flexibility for controlling whether a department menu is output on the page or elsewhere.

Possibly related: #1576 

from @jlyon 
> @kevindherman this is working as designed. We don't want massive images for those thumbnails because it will slow down page load speeds. Because the site is full-width, the'll see the border around the cards if the content is too big. I suggest only using the cards if there is a left sidebar or the some kind of page builder 50%/50% style like what is on https://petaluma-ca.proudcity.com/training-dept-news/ now. They can also use the Content List for news with the first item featured, like SR do.

I'm assuming this was the intended behavior, where department menu / contact lives in sidebar, and cards live on the right.  I've updated that https://petaluma-ca.proudcity.com/training-dept-news/ to mirror this approach, if it isn't what was attended, just drop the top row, etc
