### ISSUE TITLE
Service center holiday hours

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1589]
@aschmoe @jlyon the service center my services tab isn't generating the correct dates for holidays:

![Screenshot 2019-07-09 10 17 59](https://user-images.githubusercontent.com/6032426/60895644-03112d80-a233-11e9-9397-f188d10f9668.png)

It's saying today is closed for Independence Day and lists Tuesday, July 4th 2019 which is also incorrect.

**Comment by jlyon** [comment]
@kevindherman fixed the day of the week issue for holidays platform-wide.

Added the ability to set custom holidays on the Service Center settings page (/wp-admin/admin.php?page=service-center-settings): 
![Screenshot (44)](https://user-images.githubusercontent.com/550909/62418193-fe188180-b618-11e9-9076-c297f4ed2093.png)
