### ISSUE TITLE
Jackson: increase file upload to 100MB

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1592]
I thought this was already done but we're still getting messages like below:

![image (5)](https://user-images.githubusercontent.com/6032426/61462857-6260f300-a941-11e9-89d1-7ae0a338895e.png)

@aschmoe ^

**Comment by jlyon** [comment]
Maximum upload file size is 50mb (see above screenshot). We really want to avoid going higher than that, but it it's really going to be a common thing, we can try to make a one-off exception for them.

**Comment by kevindherman** [comment]
@jlyon it's for their agenda packets that they're uploading now. Once that's done we can lower it back down.

**Comment by jlyon** [comment]
@kevindherman I upped this to 100mb, but didn't test it with a massive upload. lmk if they run into any issues.

**Comment by jlyon** [comment]
@kevindherman I upped this to 100mb, but didn't test it with a massive upload. lmk if they run into any issues.
