### ISSUE TITLE
Payment: Add External link option

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1593]
Similar to issues content type that allows for a text only content entry, it would great for the payments content type to also have this option. After talking to @aschmoe I think either of these approaches would work fine:

1- Like issues, have an additional option that's text only
2- Include flexibility on the "external link option" that allows the user to change the "pay now" button or hide it so only text displays.

**Comment by aschmoe** [comment]
@kevindherman went with option 2
