### ISSUE TITLE
Service center 311 tab redirect mode

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1595]
I created a custom tab for 311 for https://jackson-ms.proudcity.com/

@jlyon could you make the 311 service center tab open in a new tab or window. Can this experience be replicated for the report an issue icon in the top nav?

<img width="1259" alt="Screenshot 2019-08-01 14 38 01" src="https://user-images.githubusercontent.com/6032426/62318683-59584180-b46a-11e9-937e-14fdb0a84239.png">

Please test the custom tab in those places and where the service center is being used on this addtional pages:

1. https://jackson-ms.proudcity.com/community/
2. https://jackson-ms.proudcity.com/residents
3. https://jackson-ms.proudcity.com/businesses/

**Comment by jlyon** [comment]
This now take you to a new tab, but the experience isn't ideal.  From @aschmoe on Slack:

I couldn’t figure out a way to get this https://github.com/proudcity/wp-proudcity/issues/1595 to work on the service center icon
was adding some custom js in https://jackson-ms.proudcity.com/wp-admin/admin.php?page=integrations
but it wasn’t hittin
I would maybe say just leave it, but kind of bad experience if you click the tab, go out to the link, then hit back
https://jackson-ms.proudcity.com/#/city/tab/311
you get to this and are redirected again

**Comment by kevindherman** [comment]
@jlyon @aschmoe what about changing the custom tab from external link to content and then dropping an icon in there that sends them out to a new tab? 

It would be an extra click but maybe a lesser evil? I would just need a little help making that text area look ok. @aschmoe could you help with that?

**Comment by jlyon** [comment]
@kevindherman I fixed the handling of this so the redirect links are just direct redirects. The Jackson 311 tab now links directly to https://jacksonms.citysourced.com. Let me know if you think this should open in a new tab.

**Comment by kevindherman** [comment]
@jlyon perfect.
