### ISSUE TITLE
Payment form label redundant

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1597]
Payment content type items that use the webform option display the webform title. The form title should be hidden because it's redundant with the payment label:

![Screenshot 2019-08-12 10 28 22](https://user-images.githubusercontent.com/6032426/62872899-67208900-bcec-11e9-9fa6-1f3d5f13b20a.png)

@aschmoe @jlyon

**Comment by kevindherman** [comment]
city-template link: https://city-template.proudcity.com/#/city/report/embed/fire-hazards

**Comment by jlyon** [comment]
@kevindherman I removed the first title so this matches the issues behavior in the above link:
<img width="834" alt="Screen Shot 2019-08-18 at 9 03 00 PM" src="https://user-images.githubusercontent.com/550909/63238488-a0c92680-c1fb-11e9-92e9-a36cb250d4c2.png">

**Comment by kevindherman** [comment]
@jlyon looks great.
