### ISSUE TITLE
Parks map Javascript error

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1599]
When you select the "parks" layer on this map it generates a JS error:
https://petaluma-ca.proudcity.com/parks-recreation-parks-map

TypeError: Cannot read property 'setMap' of undefined
    at m.$scope.clearMarkers (app.min.js?ver=5.2.2:3)
    at m.$scope.addMarkers (app.min.js?ver=5.2.2:3)
    at app.min.js?ver=5.2.2:3
    at m.$digest (?w3tc_minify=8ab41.js:216)
    at m.$apply (?w3tc_minify=8ab41.js:219)
    at ?w3tc_minify=8ab41.js:232
    at e (?w3tc_minify=8ab41.js:118)
    at ?w3tc_minify=8ab41.js:121

**Comment by aschmoe** [comment]
@jlyon the old `missing array key wtf happened here` thing.  Probably just convert to a forEach?

```
$scope.markers[i].setMap(null);
...
0: Marker {__gm: {…}, gm_accessors_: {…}, id: 8888, gm_bindings_: {…}, icon: {…}, …}
2: Marker {__gm: {…}, gm_accessors_: {…}, id: 8885, gm_bindings_: {…}, icon: {…}, …}
3: Marker {__gm: {…}, gm_accessors_: {…}, id: 8884, gm_bindings_: {…}, icon: {…}, …}
4: Marker {__gm: {…}, gm_accessors_: {…}, id: 8883, gm_bindings_: {…}, icon: {…}, …}
5: Marker {__gm: {…}, gm_accessors_: {…}, id: 8882, gm_bindings_: {…}, icon: {…}, …}
6: Marker {__gm: {…}, gm_accessors_: {…}, id: 8881, gm_bindings_: {…}, icon: {…}, …}
7: Marker {__gm: {…}, gm_accessors_: {…}, id: 8880, gm_bindings_: {…}, icon: {…}, …}
9: Marker {__gm: {…}, gm_accessors_: {…}, id: 8878, gm_bindings_: {…}, icon: {…}, …}
10: Marker {__gm: {…}, gm_accessors_: {…}, id: 8877, gm_bindings_: {…}, icon: {…}, …}
11: Marker {__gm: {…}, gm_accessors_: {…}, id: 8876, gm_bindings_: {…}, icon: {…}, …}
13: Marker {__gm: {…}, gm_accessors_: {…}
```

**Comment by aschmoe** [comment]
@kevindherman this is fixed
