### ISSUE TITLE
City-template: four column footer

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1600]
Add ability to have a more flexible, four column footer.

**Comment by lukefretwell** [comment]
@jlyon @aschmoe thoughts on what they've done here re: making the footer column adaptive based on number of widgets?

https://themetry.com/flexible-footer-widgets/

**Comment by kevindherman** [comment]
@jlyon @aschmoe @lukefretwell should this item be pulled into this issue: https://github.com/proudcity/wp-proudcity/issues/1604
