### ISSUE TITLE
Prepare production enviornment

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#161]

**Comment by jlyon** [comment]
- [ ] set up server, migrate WC
- [ ] Daily backups
- [ ] SSL (lets encrypt)

**Comment by jlyon** [comment]
@kevindherman I moved https://west-carrollton-oh.proudcity.com over to the production server.  

Everything is setup and ready for the Tue switchover.  Right after the switch, I'm going to need to make two changes:

Launch tasks:
- [ ] SSL (lets encrypt)
- [ ]  site url replace

**Comment by jlyon** [comment]
@kevindherman Google Analytics for
```
West Carrollton BETA(UA-71593638-3)
```
are setup.  Do they want us to add tracking codes for the accounts that also used to be on the live site that we didn't have access to (UA-49098330-1 and UA-1150778-2)?

**Comment by kevindherman** [comment]
Tom ran their GA accounts, could you ask him and Erika in the DNS thread?

On Tue, Feb 23, 2016 at 10:34 AM, Jeff Lyon <notifications@github.com>
wrote:

> @kevindherman <https://github.com/kevindherman> Google Analytics for
>
> West Carrollton BETA(UA-71593638-3)
>
> are setup. Do they want us to add tracking codes for the accounts that
> also used to be on the live site that we didn't have access to
> (UA-49098330-1 and UA-1150778-2)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/161#issuecomment-187748263>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
