### ISSUE TITLE
Sonoma: links to Civic Web shows broken when not

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1610]
The broken link checker on Sonoma is flagging all of their Civic Web (meetings portal) as broken when they're not. They keep needing to go into the broken link checker to fix the slash through. Here's an example of a link that's being reported as broken that isn't:

https://sonomacity.civicweb.net/Portal/MeetingInformation.aspx?Org=Cal&Id=511

@jlyon can you create a rule that passes those links in the checker?

**Comment by jlyon** [comment]
I excluded `civicweb.net` from Sonoma and Rye Brook
