### ISSUE TITLE
Petaluma: gap between menu and dept contact info

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1611]
There is a large gap between the dept menu and the dept contact information: https://petaluma-ca.proudcity.com/departments/city-clerk/

![Screenshot 2019-09-03 14 45 14](https://user-images.githubusercontent.com/6032426/64199984-8f1d8b00-ce59-11e9-896b-02d2153133f0.png)

@aschmoe mentioned that this could be that the level-2 menu is longer.

**Comment by jlyon** [comment]
@kevindherman I removed this (might require a hard refresh)

**Comment by kevindherman** [comment]
@jlyon thank you!
