### ISSUE TITLE
Add sort to contact list widget

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1612]
@jlyon Petaluma entered a lot of contacts into the site in alphabetical order so all of the dept directory pages they setup are displaying in reverse alphabetical order. Since we don't have an alphabetize sort for the contact list widget, is it possible to reverse the order for the contact list widget for the Petaluma site?

Example page:
https://petaluma-ca.proudcity.com/police-staff-directory/

**Comment by jlyon** [comment]
@kevindherman we are able to affect the sort of the draggable order. Pushing a hotfix to enable this option, and allow us to sort of title in the future:
![Screenshot (8)](https://user-images.githubusercontent.com/550909/64494281-b4d2d780-d23f-11e9-999a-32072c13f81e.png)

**Comment by kevindherman** [comment]
@jlyon that's great news. We'll do the sort order to start and then guide them to update the naming,.

**Comment by jlyon** [comment]
I updated https://petaluma-ca.proudcity.com/police-staff-directory.  Someone will have to go through and update all of the other lists.

**Comment by kevindherman** [comment]
@jlyon thank you, that's on my list this morning.
