### ISSUE TITLE
Petaluma: map layer cache

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1613]
On this map page if you click on the parks layer it still displays all of the Dog Run locations instead of just Parks. I checked the location layers and this is setup correctly.

https://petaluma-ca.proudcity.com/parks-recreation-parks-map
![Screenshot 2019-09-03 15 30 49](https://user-images.githubusercontent.com/6032426/64202767-eb83a900-ce5f-11e9-8f7c-7dc0d0eb741a.png)

I noticed that if I copy the parks layer URL into an incognito window it does display correctly (the lonely dog run pin is assigned to both layers):

https://petaluma-ca.proudcity.com/parks-recreation-parks-map#/maps-1/map/parks
![Screenshot 2019-09-03 15 31 05](https://user-images.githubusercontent.com/6032426/64202745-dc046000-ce5f-11e9-916d-076d39ea7921.png)

Since it display correctly in a private browser, it leads me to think it's a caching thing but that's an educated guess. @jlyon @aschmoe

**Comment by kevindherman** [comment]
@aschmoe the jackson homepage services map might be a better example to work off of since it has a lot of data points: https://jackson-ms.proudcity.com/

**Comment by aschmoe** [comment]
@kevindherman this is fixed
