### ISSUE TITLE
Add Sort to Meeting list widget 

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1614]
Meeting list widgets are missing the ability to order:

https://jackson-ms.proudcity.com/planning-board/
See edit widget:
![Screenshot 2019-09-05 12 45 53](https://user-images.githubusercontent.com/6032426/64361793-3fff6380-cfdb-11e9-9914-c7ddb78879eb.png)

**Comment by kevindherman** [comment]
@jlyon here is a live example of the meeting list widget displaying in the correct order: https://www.townoffairfax.org/departments/meetings-agendas/

**Comment by jlyon** [comment]
@kevindherman the ordering on Fairfax didn't seem correct (below). I switched the ordering on this widget to do date ascending (the next one first). It _was_ doing order descending (the oldest first). It seems like this fixed the issue on https://jackson-ms.proudcity.com/planning-board/, but _may_ cause issues elsewhere.

<img width="689" alt="Screen Shot 2019-09-18 at 10 29 43 PM" src="https://user-images.githubusercontent.com/550909/65217496-09105f80-da69-11e9-9807-35244502aad3.png">

**Comment by kevindherman** [comment]
@jlyon thanks! Is it possible to have the functionality to choose between ascending and descending? 

For the current or active year it's helpful to be most recent first, whereas an archive is the opposite.

**Comment by jlyon** [comment]
@kevindherman I added a sort option to the meetings list widget that will sort by the Meeting date. I set the order to Ascending on https://jackson-ms.proudcity.com/planning-board/,  and that seemed to fix that page.

**Comment by kevindherman** [comment]
@jlyon this is perfect.

**Comment by jlyon** [comment]
Great it will be pushed platform-wide in the next release.

**Comment by kevindherman** [comment]
@jlyon one issue has come up with the ordering for Jackson. When a meetings list select multiple categories, it will list each category in order rather than all of the selected categories in the select order. 

In the upcoming meetings list on the below page,  it seems like it is in chronological order but we're having two issues 1. The meetings are in order but they're also listed by category first than date. So we have all the Planning Board meetings then the Historic Preservation meetings:

https://jackson-ms.proudcity.com/departments/planning-and-development/

**Comment by jlyon** [comment]
I'll take a look at this for the release @kevindherman

**Comment by kevindherman** [comment]
@jlyon  Examples and screenshots:

https://www.townoffairfax.org/agendas-town-council/
![Screenshot 2019-10-03 15 02 36](https://user-images.githubusercontent.com/6032426/66156024-da5cc200-e5ee-11e9-91d5-1c3fdf786c13.png)

https://www.townoffairfax.org/2018-meeting-archive/
![Screenshot 2019-10-03 15 03 17](https://user-images.githubusercontent.com/6032426/66156079-f3fe0980-e5ee-11e9-829e-fe84e574d7d6.png)

https://www.colma.ca.gov/city-council-meetings/
![Screenshot 2019-10-03 15 03 55](https://user-images.githubusercontent.com/6032426/66156119-109a4180-e5ef-11e9-9919-f22628cd78e8.png)

https://www.colma.ca.gov/2017-city-council-meetings/
![Screenshot 2019-10-03 15 04 35](https://user-images.githubusercontent.com/6032426/66156159-23147b00-e5ef-11e9-93cc-9fe6918d443c.png)

https://www.johnsoncitytx.org/2018-minutes-and-agendas-2/
![Screenshot 2019-10-03 15 05 20](https://user-images.githubusercontent.com/6032426/66156219-3c1d2c00-e5ef-11e9-8220-347b07d90eb5.png)

https://www.lucastexas.us/city-council-meetings/
![Screenshot 2019-10-03 15 06 31](https://user-images.githubusercontent.com/6032426/66156313-6cfd6100-e5ef-11e9-9cfd-66097b392c5a.png)

https://oakwoodohio.gov/city-council-meetings/
![Screenshot 2019-10-03 15 07 22](https://user-images.githubusercontent.com/6032426/66156361-856d7b80-e5ef-11e9-9856-2fd06f477e80.png)

**Comment by jlyon** [comment]
I tried digging into https://jackson-ms.proudcity.com/departments/planning-and-development/, but they only have one category selected on the admin. It also looks like they have maybe made changes to this page.  Is this still an issue @kevindherman. If so, I'll probably need to dig in a little more.

**Comment by jlyon** [comment]
@kevindherman I looked into this more, and it seems like grouping by category is happening somewhere at the WordPress core level, and I'm not seeing an immediate path forward. I think the best workaround for now is to create a separate shared category that these posts can also be assigned to.

**Comment by kevindherman** [comment]
@jlyon thanks for looking into this. 

Is the issue at the parent level? So selecting multiple parent categories, means sorting within each parent category? 

I want to make sure I'm coaching correctly for sub categories, here's a potential scenario:

The Planning Board sets up a parent category for Special Projects. Each project has its own sub-category. If the Planning Board wants a feed for all special meetings they should select just the parent and that will allow all of the sub categories to display (regardless of the child-categories, right? In other words, does selecting just the parent, remove the ordering by subcategory within the parent?

**Comment by jlyon** [comment]
> Is the issue at the parent level? So selecting multiple parent categories, means sorting within each parent category?

I _think_ this might be the case (it seemed like that's what I was getting when I tested it locally last week, but I wasn't able to verify it last night.

In your example, yes, I think the best solution would be to set up a new Parent category "Special Projects". In the meetings list widget, only select the parent-level item.  That should display all children, and _should_ fix the sorting issue as well. I did not test this, so test it before you suggest it to the client.

**Comment by kevindherman** [comment]
@jlyon That would make sense since in this case they have selected multiple parents:
![Screenshot 2019-10-07 12 24 23](https://user-images.githubusercontent.com/6032426/66329965-78a59c00-e8fd-11e9-9f37-467e707ac551.png)

**Comment by kevindherman** [comment]
@jlyon dammit, if I de-select the children and ONLY have the parent, it still lumps them together.

**Comment by jlyon** [comment]
@kevindherman I messed with this for awhile and couldn't figure out wtf is going on.  @aschmoe do you have any ideas (we can discuss this if it's not clear).

@kevindherman it _should_ work to create a new top-level category called "Widget List", and adding all meeting posts that you want to appear in that list to that category in addition to their other categories.  Then only select the "Widget List" category from the block editor.  I tried setting this up locally, though and it seemed like I was still having weird sort issues.

**Comment by kevindherman** [comment]
@jlyon upon further review they're not posting correctly. However, it may be because they're displaying in menu order even though meeting date order is selected. 

![Screenshot 2019-10-10 13 02 36](https://user-images.githubusercontent.com/6032426/66590224-45157c80-eb5e-11e9-8c0b-061cb0bf8360.png)
![Screenshot 2019-10-10 13 02 43](https://user-images.githubusercontent.com/6032426/66590225-45157c80-eb5e-11e9-99e6-026ccc54cebd.png)

**Comment by jlyon** [comment]
@aschmoe this is the query
```
{
  "post_type": "meeting",
  "post_status": "publish",
  "update_post_term_cache": false,
  "update_post_meta_cache": true,
  "posts_per_page": "5",
  "orderby": "datetime",
  "order": "ASC",
  "tax_query": [
    {
      "taxonomy": "meeting-taxonomy",
      "field": "term_id",
      "terms": [
        284
      ],
      "operator": "IN"
    }
  ],
  "no_found_rows": true
}
```

**Comment by jlyon** [comment]
@kevindherman Thanks for your digging.  The issue in the end was that we weren't properly sorting by the meeting date (we were still sorting by the post date). I pushed this as a hotfix platform-wide.  It's looking good on https://jackson-ms.proudcity.com/departments/planning-and-development/ now.

**Comment by kevindherman** [comment]
@jlyon Yassss! So satisfying.

**Comment by jlyon** [comment]
@kevindherman I think we're all set here, right?

**Comment by kevindherman** [comment]
@jlyon yup!
