### ISSUE TITLE
platform: webform entries should list submission date/time in the entry view

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1618]
A couple of customers have mentioned that it would be helpful for webforms to display both the date and time of a form entry. 

Using Oakwood's "No solicitation request form" as an example: https://oakwoodohio.gov/wp-admin/admin.php?page=gf_entries&id=13

Some are showing a date and none show the time. 

When I look at Oakwood's feedback form entries the times are showing odd results:
![Screenshot 2019-09-12 10 23 21](https://user-images.githubusercontent.com/6032426/64792681-cb32a900-d547-11e9-96c4-ef99fab8ddb2.png)

It would be ideal for the submission date to display consistently and be included in the notification emails that replicate the display of the entry detail:
![Screenshot 2019-09-12 10 27 43](https://user-images.githubusercontent.com/6032426/64792800-fc12de00-d547-11e9-8407-76f50f99c0b7.png)

Thinking out loud here, submission date and time should probably be a default if possible. 

@jlyon

**Comment by jlyon** [comment]
@kevindherman I set this up on https://oakwoodohio.gov/wp-admin/admin.php?page=gf_entries&id=13

From https://docs.gravityforms.com/entries/:
```
One of the features of the Entries screen is the ability to pick and choose which columns should appear in the list based on available form fields. To select the columns, simply click the Edit icon on the right of the entries list table header. This will display the Select Columns window.
```
This icon is hard to find:
![Screenshot (17)](https://user-images.githubusercontent.com/550909/65217864-0feba200-da6a-11e9-95d9-54d617bc85a8.png)

**Comment by kevindherman** [comment]
@jlyon awesome.
