### ISSUE TITLE
Contact us appearing twice

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#162]

**Comment by jlyon** [comment]
url: https://west-carrollton-oh.proudcity.com/contact/

It's appearing in an `<h2>` above the `<h1>`.

@aschmoe did you made some changes that could have caused this, or is this because of some menu restructuring that we need to look into?

**Comment by jlyon** [comment]
Also looks like it's happening on https://west-carrollton-oh.proudcity.com/city-council-minutes/

**Comment by aschmoe** [comment]
Cool I'll take a look, did some modifying of when widgets are printed, will
fix

**Comment by jlyon** [comment]
Cool thx

**Comment by aschmoe** [comment]
@jlyon forgot to mention this is fixed last night
