### ISSUE TITLE
Footer text widget bug?

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1620]
When I go to edit the text widget (for ELGL) it strips out the content. This has happened a number of times. What I do is copy/paste from source code, edit in Sublime, then paste and mark 'Done.'

What's supposed to be in there:

<img width="824" alt="Screen Shot 2019-09-16 at 9 45 39 AM" src="https://user-images.githubusercontent.com/1569463/64985082-eb7ca380-d878-11e9-85fa-a922e4d33e80.png">

What it looks like when I open it up:

<img width="886" alt="Screen Shot 2019-09-16 at 9 40 29 AM" src="https://user-images.githubusercontent.com/1569463/64985099-f59ea200-d878-11e9-8553-56fc10d0eac3.png">

**Comment by aschmoe** [comment]
@lukefretwell when I do this:

1. as soon as I make edits done is removed from my options (and "Saved" turns to "Save")
1. I hit save 
1. icons spins
1. done re-appears 

and everything works as expected.  Let me know if there are different steps to reproduce

**Comment by lukefretwell** [comment]
@aschmoe looks like it's working fine now. Closing this issue.
