### ISSUE TITLE
Petaluma: search + docs setup

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1621]

**Comment by aschmoe** [comment]
@kevindherman this was done, the full upgrade to the search docs has not been completed yet, but that will not hold back Petaluma.

**Comment by aschmoe** [comment]
https://petaluma-ca.proudcity.com/search-site/?term=city&filter_post_type=document&filter_index=all

**Comment by kevindherman** [comment]
@aschmoe thank you.
