### ISSUE TITLE
San Rafael: recurring meeting displaying event form 1969

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1624]
There is a recurring event on SR for "Design Review Board Meeting" that is working correctly. However, there is an old recurring event "Design Review Board Meetings" (plural) that doesn't exist in dashboard > events or dashboard > recurring events (in draft, trash, etc. either). 

Still, the plural version is displaying and dating back to 1969: https://www.cityofsanrafael.org/events/?filter_keyword=review+board&filter_categories[]=Public+Meetings
![Screenshot 2019-10-09 09 35 17](https://user-images.githubusercontent.com/6032426/66487822-f8a54080-ea7a-11e9-86ca-9d5fc36b1be6.png)

It's coming up in site search or if you go to events and search design board meetings. The event detail goes to page not found so I can't track down where it's coming from.

@jlyon @aschmoe it just needs to be deleted but I'm not sure how to do that since I can't find it. Thoughts?

**Comment by aschmoe** [comment]
@kevindherman re-ran elastic for SR, should be good for now
