### ISSUE TITLE
oakwood: update PHP version

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1625]
![unnamed (1)](https://user-images.githubusercontent.com/6032426/67035271-5a9f1f00-f0e7-11e9-880d-116280c1ef08.png)

**Comment by jlyon** [comment]
We are in fact running php 7.2.23, which is the latest version of php 7.2.x which is has security support until 30 Nov 2020 ( https://www.php.net/supported-versions.php)
