### ISSUE TITLE
social wall DB cap

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1627]

**Comment by jlyon** [comment]
We set this up on Thursday

**Comment by kevindherman** [comment]
@jlyon @aschmoe https://www.townoffairfax.org/ social wall still isn't showing the most up to date FB posts.

**Comment by jlyon** [comment]
It looks like our Facebook app failed the review process. I just re-initiated the review, and hopefully we'll get approved, but barring that, it looks like we might have to do something along the lines of what we had to do for instagram unfortunately @kevindherman
