### ISSUE TITLE
New spinups?

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#163]

**Comment by jlyon** [comment]
- [ ] Manhatten KS
- [ ] Forest Grove OR
- [ ] San Jose CA
- [ ] Anchorage AK

**Comment by kevindherman** [comment]
Still confirming, however, all were gov folks except San Jose.

On Mon, Feb 22, 2016 at 3:12 PM, Jeff Lyon <notifications@github.com> wrote:

>
>    - Manhatten KS
>    - Forest Grove OR
>    - San Jose CA
>    - Anchorage AK
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/163#issuecomment-187365091>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
