### ISSUE TITLE
Meetings datepicker: use AM/PM instead of 24-hour military time

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1630]
Current the time picker when creating a meeting piece of content is in military time. Can that picker be a 12 hour clock? 

![Screenshot 2019-10-28 15 03 55](https://user-images.githubusercontent.com/6032426/67709435-518a3980-f994-11e9-8d25-7f034da90beb.png)

**Comment by jlyon** [comment]
Putting this off for a bit because the string is sorted alpha in the views. Nice to have.

**Comment by jlyon** [comment]
Got this working. Will be in the next release.

**Comment by kevindherman** [comment]
@jlyon thank you!
