### ISSUE TITLE
Fix Meeting Contact Department link url

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1631]
@jlyon the meeting contact link is sending people to city-template instead of the city council dept page. 

https://www.jacksonms.gov/meetings/city-council-regular-meeting-september-17-2019/
<img width="1141" alt="Screenshot 2019-10-29 18 21 04" src="https://user-images.githubusercontent.com/6032426/67813825-ef573480-fa78-11e9-9206-ed54c23eb81d.png">

Goes to: https://city-template.proudcity.com/?post_type=agency&p=2790

**Comment by jlyon** [comment]
Pushed a hotfix for this @kevindherman

**Comment by kevindherman** [comment]
@jlyon thank you.
