### ISSUE TITLE
Meetings: add ability to remove a document

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1632]
Here is a use case that has come up before:

 Angela from the Clerk's Office accidentally uploaded the Oct. 15th minutes to the Oct. 29th page. I couldn't figure out how to remove the attachment without adding another one. She doesn't have anything to replace it with, yet. She just wants to remove the attachment.

https://www.jacksonms.gov/meetings/city-council-regular-meeting-october-29-2019/

**Comment by jlyon** [comment]
Added this in the release @kevindherman
