### ISSUE TITLE
Add breadcrumb widget to Division Layout page builder template

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1635]
Currently the "Division Layout" on Jackson doesn't include the breadcrumb widget on it's own row like this page:

https://www.jacksonms.gov/engineering/

@aschmoe can you add this to the layout option?

**Comment by jlyon** [comment]
@jlyon can look. Prob involves redoing the layout option.

**Comment by jlyon** [comment]
@kevindherman updated the Division Template to include the breadcrumbs. New pages created with that template will look like this:
<img width="1197" alt="Screen Shot 2019-12-12 at 8 39 40 PM" src="https://user-images.githubusercontent.com/550909/70769762-a654fa00-1d1f-11ea-9efd-6945dc1af504.png">

**Comment by aschmoe** [comment]
@kevindherman looks like the "Division Layout" _does_ "include the breadcrumb widget on it's own row" now... let me know if I'm misunderstanding.

**Comment by aschmoe** [comment]
@kevindherman nvm just saw jeff's closing

**Comment by kevindherman** [comment]
@jlyon @aschmoe great.
