### ISSUE TITLE
Platform: google maps option on services map not pulling category data

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1637]
Sites that use the google map default for the service center map are not showing pins for the different default categories:

https://ryebrook.org/
![Screenshot 2019-11-26 10 13 08](https://user-images.githubusercontent.com/6032426/69646308-90fc8200-1035-11ea-9a26-73c4f239ffbd.png)
![Screenshot 2019-11-26 10 13 19](https://user-images.githubusercontent.com/6032426/69646309-90fc8200-1035-11ea-9898-869bb82366d9.png)

**Comment by jlyon** [comment]
@kevindherman this was related to the issue with the Google maps key from a week or so ago that caused the high bill.  I went through all of our production sites, and this should now be fixed.  There is still some lingering cleanup work to do, but all of the prod sites (including rye brook) should show these pins now.

**Comment by kevindherman** [comment]
@jlyon thanks!
