### ISSUE TITLE
Petaluma: contact detail in mobile issues

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1642]
Contact detail page on Petaluma gets wonky on mobile: https://cityofpetaluma.org/contacts/teresa-barrett/

If you shrink down contact details are hidden and the email link doesn't select. 
![Screenshot 2019-12-16 13 09 53](https://user-images.githubusercontent.com/6032426/70931417-69318600-2005-11ea-8219-e8333721d172.png)

**Comment by curtismchale** [comment]
@kevindherman @lukefretwell this is an issue from 2019 and I don't see it happening now. Moving to QA and if it's still happening give me browser dimensions to test. I tried all mobile devices in developer tools, plus dragged through the whole size range and tested the devices I have at home. None of them did this.

**Comment by kevindherman** [comment]
@curtismchale I think you can close this.
