### ISSUE TITLE
Petaluma: doc search results

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1644]
@aschmoe searching for "approved tree list" on Petaluma yields several results but not the document titled "approved tree list":

Doc: https://cityofpetaluma.org/documents/approved-tree-list/

Results:
<img width="848" alt="Screenshot 2020-01-09 12 51 43" src="https://user-images.githubusercontent.com/6032426/72091782-f1dad380-32de-11ea-9b73-a18e936874e2.png">

**Comment by kevindherman** [comment]
@aschmoe here's another ticket on this issue:

"i have two documents - Development Impact Fee Matrix and Development Impact & Connection Fee Booklet - that are not coming up when I search for development impact fee. 
https://cityofpetaluma.org/documents/development-impact-and-capacity-fees-booklet/

https://cityofpetaluma.org/documents/development-impact-fee-matrix/

Can you tell me why and/or make an adjustment so the documents come up?"

**Comment by aschmoe** [comment]
@kevindherman pushed some re-weighting in hotfix.  This should be mostly fixed up now

**Comment by kevindherman** [comment]
@aschmoe I tested the three documents from this ticket and it looks good.

**Comment by kevindherman** [comment]
@aschmoe Danvers has reported similar issues with the document: https://www.danversma.gov/documents/2020-recycling-calendar/

If you do a site search it's not in the mix. Was your hotfix for the platform or specifically to Petaluma?

**Comment by aschmoe** [comment]
@kevindherman deployed a fix for this on danvers

**Comment by kevindherman** [comment]
@aschmoe I tried the same search on Danvers after clearing my cache and using an incognito window with the same search results: https://www.danversma.gov/search-site/?term=2020+recycling+calendar

**Comment by aschmoe** [comment]
@kevindherman think I just didn't deploy an image.  Looking good now
