### ISSUE TITLE
Customer ability to edit page not found page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1645]
Ability to edit the page not found page:

<img width="1373" alt="Screenshot 2020-01-09 12 54 24" src="https://user-images.githubusercontent.com/6032426/72091885-35354200-32df-11ea-9d21-859819d1b698.png">

**Comment by jlyon** [comment]
Currently not editable. It's hardcoded in wp-proud-theme/404.php.  We _could_ possibly make this editable in the UX, but it would be pretty easy to throw something in the Petaluma custom theme for now.

**Comment by kevindherman** [comment]
@jlyon here is the unpublished page they would like to use as the page not found page: https://cityofpetaluma.org/page-not-found/

The tricky part for this layout is inserting the search bar where they say "INSERT SEARCH BAR". Is that possible? Any other issues?

**Comment by kevindherman** [comment]
@jlyon any way this could be added as a hot fix since it's a one off?

**Comment by jlyon** [comment]
@kevindherman sorry, I set this up after the release but didn't configure the plugin. This is all set. If it's valuable to other cities, we can add the plugin to our platform and set up the default page on city-template.

To get the "INSERT SEARCH BAR" to be the search bar, I broke the text into multiple text blocks and added the search widget inbetween.

Example: https://cityofpetaluma.org/asdf

**Comment by kevindherman** [comment]
@jlyon dope, thank you.

I think there are aspects of this that are helpful that we may want to consider for everyone down the road.

Even just this language followed by the search is nice:

PAGE NOT FOUND HELP
UH OH...WE CAN'T FIND THE PAGE YOU WANT
 

If you've landed on this page, it might be because you were looking for a page from our old website. Or, we might have a broken link. Here are a few ways to find what you need:
