### ISSUE TITLE
Mixed http / https content https://west-carrollton-oh.proudcity.com/residents/

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#165]
Map is calling non ssl content

**Comment by jlyon** [comment]
damn, that seems new. Not sure if there's a good solution.

**Comment by aschmoe** [comment]
@jlyon perhaps something can be done with login?  https://doc.arcgis.com/en/arcgis-online/administer/configure-security.htm

**Comment by jlyon** [comment]
@kevindherman could you ask Erika if she can track down a login to the ArcGis admin interface.  Or better yet, if they have someone that administers their account, could we have them login and configure the security settings so that HTTPS is required for all transactions https://doc.arcgis.com/en/arcgis-online/administer/configure-security.htm?

**Comment by kevindherman** [comment]
@jlyon Erika said they configured it for us. Let me know if we need them to do anything else.

**Comment by jlyon** [comment]
Hmm, doesn't seem like they're changes made a difference. I'll dig into it more later today.

**Comment by jlyon** [comment]
@kevindherman it looks like their arcgis map is still loading some tiles from an http connection.  It's not a huge deal, but it will produce a popup on older browsers (old versions of IE).  Could you have her ask them to poke around the account a little more.  Or, if you can get credentials, I can poke around.

**Comment by kevindherman** [comment]
Sent and email, will post back with more info when it comes.

On Mon, Feb 29, 2016 at 7:26 PM, Jeff Lyon <notifications@github.com> wrote:

> @kevindherman <https://github.com/kevindherman> it looks like their
> arcgis map is still loading some tiles from an http connection. It's not a
> huge deal, but it will produce a popup on older browsers (old versions of
> IE). Could you have her ask them to poke around the account a little more.
> Or, if you can get credentials, I can poke around.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/165#issuecomment-190467119>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by kevindherman** [comment]
@jlyon this is what their GIS guy said, sounds like they're fine with the occasional popup. 

 
All,
 
The GIS Viewer is working but the County Engineer's layers are not. These layers include: Parcels, Contours and Record Plans.
 
Just close the warning windows and you can still use the viewer just without the layers mentioned above.
 
Andy

**Comment by jlyon** [comment]
ok, marking as done.
