### ISSUE TITLE
Meetings: improve the handing and sorting for Upcoming and Recently Completed meetings

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1650]
Meeting are sorting correctly by date but out of order by time:

https://citiesassociation.org/meetings/

<img width="1125" alt="Screenshot 2020-01-31 15 53 31" src="https://user-images.githubusercontent.com/6032426/73574782-91a20200-4444-11ea-9fc9-2f212e6ae527.png">

**Comment by kevindherman** [comment]
@jlyon this is happening on Montclair:

Meetings on the same day not ordering by time. A factor might be that they are multiple meeting categories

https://www.cityofmontclair.org/departments/public-meetings/
<img width="714" alt="Screen Shot 2021-03-15 at 1 48 46 PM" src="https://user-images.githubusercontent.com/6032426/111197777-3faf3380-8595-11eb-8d11-7594dfce5110.png">

**Comment by kevindherman** [comment]
@jlyon I forgot that Montclair had brought this up and just sent a followup.

You can see that meetings on the same day don't show in time order and I think it's when there are multiple meeting categories being displayed that the order gets wonky: https://www.cityofmontclair.org/departments/public-meetings/

**Comment by jlyon** [comment]
@kevindherman Alex and I spent a fair amount of time looking into this last night, but couldn't find the solution. I'll continue looking at it over the weekend.

**Comment by kevindherman** [comment]
@jlyon thank you. I appreciate it.

**Comment by jlyon** [comment]
@kevindherman I adjusted the way that the Sort by Date Time options work so they work as expected:
> Sort By Meeting Date and use the Ascending Sort Order to to show upcoming meetings. Use the Descending option to display recently completed meetings.
I have deployed this to Montclair only 

This should fix most instances, however I think you mentioned that some cities were doing some weird things with meetings (perhaps using post date), and this might have some ramifications for those sites.

One last thing we could do is only show completed events if the sort order is Descending (currently you'll see upcoming and completed events if you sort by Descending).

**Comment by kevindherman** [comment]
@jlyon thank you!

I am going to pass this along to Montclair who is a helpful bunch and see what their feedback/experience is. This should do the trick.

**Comment by jlyon** [comment]
@kevindherman I left this out of this release, but re-deployed it on Montclair

**Comment by kevindherman** [comment]
explicit guidance on using ascending and descending for archive vs upcoming.

**Comment by jlyon** [comment]
@kevindherman I think I got this working well.  There are now three sort by options in the Meeting List widget:

- Only Upcoming Meetings by Date
- Only Completed Meetings by Date
- All Meetings by Date

We then have these instructions at the top of the widget:
"The default is to show upcoming meetings by sorting by "Only Upcoming Meetings by Date" with the Ascending Sort Order. To show recently completed meetings, sort by "Only Completed Meetings by Date" with the Descending Sort Order. To show an annual archive of meetings, sort by "All Meetings by Date" and use whichever sort order you prefer."

I updated the Upcoming and Recently completed meetings lists on Montclair on these pages.  We should probably update other Meetings users that you know about:
- https://www.cityofmontclair.org/departments/public-meetings/
- https://www.cityofmontclair.org/

**Comment by kevindherman** [comment]
@jlyon it looks like the "only completed meetings by date" is still out of order:

https://www.cityofmontclair.org/departments/public-meetings/
![Screen Shot 2021-08-06 at 7 45 48 AM](https://user-images.githubusercontent.com/6032426/128505976-2af84688-5d03-4d27-9eb9-051da5b6b539.png)

**Comment by kevindherman** [comment]
@jlyon Holyoke reported a similar issue https://www.holyoke.org/departments/public-meetings/
