### ISSUE TITLE
Stripe: Add city name to statement descriptors

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1651]
Currently the descriptors are just "PROUDCITY", which is confusing for citizens making payments.  Add statement_desciptor so the statements will include the city name in their descriptions, `PROUDCITY* {CITYNAME}`.

https://stripe.com/docs/statement-descriptors

**Comment by kevindherman** [comment]
@jlyon once this is complete, could you mark the update as done in the Stripe dashboard? https://dashboard.stripe.com/connect-update
