### ISSUE TITLE
ELGL: pager just reloads page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1653]
@aschmoe the pager button for more posts on the news list widget on the below page just refreshes the page rather than produce older posts: https://elgl.org/exclusives/

I tested list view since it's displaying cards and that didn't produce the intended outcome. I also tested changing the list from 12 to 0 and that didn't help either.

**Comment by aschmoe** [comment]
Deployed this @kevindherman

**Comment by kevindherman** [comment]
@aschmoe thank you.
