### ISSUE TITLE
Prioritize translate option from the footer

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1658]
We've talked about this in the past but haven't done anything yet so I wanted to start the conversation again. 

How can we prioritize translate and the font size tool instead of it being buried in the footer? I think the translate option is the most important to move up in the theme. 

Could it replace the answers icon in the header? 

What do you guys think? @aschmoe @jlyon @lukefretwell

**Comment by lukefretwell** [comment]
@aschmoe let's discuss on our Monday call.

As we need to do for a few other features, we should evaluate whether this is something we should keep given that Google has deprecated the tool, but also that this is now a standard browser feature.

**Comment by kevindherman** [comment]
@lukefretwell thanks for the reminder, for at least the second time, on google translate being supported on the browser side. 

It's definitely a challenge in that local gov site users don't necessarily use or know that they have the translate feature. Do we alter the site to accommodate that type of user or help push good behavior by not depending on a tool that will go away sooner than later.

**Comment by lukefretwell** [comment]
@kevindherman did you know this is a browser default now? 😆 

@aschmoe and I talked and he's going to add icons to the main nav so folks will have the option to include those. Once it's done we can write a blog post explaining:

- [ ] What we did.
- [ ] Why we did it.
- [ ] How you can set it up.
- [ ] Why it's not that necessary to have as part of the website.

**Comment by aschmoe** [comment]
@kevindherman @lukefretwell deployed this as hotfix

How to enable
![Screen Shot 2020-06-15 at 9 47 03 PM](https://user-images.githubusercontent.com/1634686/84732972-e062bb00-af51-11ea-881d-1a4757a52144.png)

I completed the development to get font size up there too, but that utility is not very effective in its current form, so I dropped it from the options.

**Comment by aschmoe** [comment]
Lets try to "keep it" to max 3 items in the bar either by convention or policy.

**Comment by kevindherman** [comment]
@aschmoe dope! 

Totally agree on keeping to three.
