### ISSUE TITLE
Feedback: hide agency category on top  /contacts page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#166]
I couldn't find this issue so I'm sorry if it's duplicated in here but it's still unresolved.

**Comment by kevindherman** [comment]
![screenshot 2016-02-23 08 13 40](https://cloud.githubusercontent.com/assets/6032426/13252607/b1d57e60-da05-11e5-8109-c9af8464759b.png)

**Comment by jlyon** [comment]
oops, i think this slipped through the cracks somehow. I'll take a look at this today.

**Comment by kevindherman** [comment]
I forgot to repost this on Friday so I'll share the blame on that.

On Tue, Feb 23, 2016 at 10:36 AM, Jeff Lyon <notifications@github.com>
wrote:

> oops, i think this slipped through the cracks somehow. I'll take a look at
> this today.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/166#issuecomment-187749865>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by jlyon** [comment]
I added a checkbox field to select the contact categories that should appear here.


I hid the last term.

**Comment by kevindherman** [comment]
Perfect.

**Comment by kevindherman** [comment]
Not out of the woods yet...

If you click on Elected Officials or City Staff Contacts the URL path changes from /contacts to /people and then Planning and Building category button reappears.

![screenshot 2016-02-23 16 33 51](https://cloud.githubusercontent.com/assets/6032426/13267450/4805ac6c-da4b-11e5-9b89-0d7980ef5a56.png)

**Comment by jlyon** [comment]
Fixed this by editing the contact submenu block on https://www.westcarrollton.org/wp-admin/post.php?post=2889&action=edit.

**Comment by kevindherman** [comment]
Adios Planning & Building Category view.
