### ISSUE TITLE
Live youtube video embed

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1661]
@jlyon @aschmoe I got a zendesk ticket about embedding livestream youtube videos and guided the person to try using the iframe widget and the add media URL embed. Neither of these worked and I have confirmed on my end as well. 

Is there a plugin update for livestream youtube videos or perhaps a specific widget is needed?

Here's the zendesk ticket:

The iframe widget just causes the URL to appear on the page. Adding the Video widget and the URL causes this error message; "Sorry, we can't load the video at the supplied URL. Please check that the URL is for a supported video file (.mp4, .m4v, .webm, .ogv, .flv) or stream (e.g. YouTube and Vimeo)."

Link to the page I am working on is warracres-ok.gov/live
YouTube link to live stream is https://www.youtube.com/channel/UC12p4_toc0mcYZqaOWUqUtA/live

**Comment by kevindherman** [comment]
@jlyon @aschmoe this has also come up for SR who wants to use YouTube livestream for their council meetings.

**Comment by jlyon** [comment]
@kevindherman see https://webcam.io/support/howto-embed-youtube-live/.  It sounds like it is possible, but requires a some special configuration on their end: https://webcam.io/support/howto-embed-youtube-live/:
```
Requirements
The features Live streaming and Embed live streams need to be enabled in https://www.youtube.com/features. Please follow the instructions there.

To embed into your website, a linked AdSense account seems to be required.
```

Assuming these settings are correct for WA, the embed code (to be added in a code widget) is:
```
<iframe width="560" height="315" src="https://www.youtube.com/embed/live_stream?channel=UC12p4_toc0mcYZqaOWUqUtA" frameborder="0" allowfullscreen></iframe>
```
I added this to https://www.warracres-ok.gov/live/, but I get an error when I click play on that video. 

---

If SR can figure this all out by next Tue, I can def help set up a meeting for them with this embed code. If that works well, we can figure out a way to build this into the meetings content type.

**Comment by kevindherman** [comment]
@jlyon awesome.

I have passed this along to WA and will now coordinate with SR.

**Comment by kevindherman** [comment]
@jlyon I know this item is closed but I want to go over what you found and in context of San Rafael:

YouTube channel:
https://www.youtube.com/channel/UCaQDlHi5fD6sByZUw5FOg9A/featured

Live Commenting pilot page: 
https://www.cityofsanrafael.org/live-commenting-pilot/

**Comment by jlyon** [comment]
Embed code for SR @kevindherman 
```
<iframe width="560" height="315" src="https://www.youtube.com/embed/live_stream?channel=UCaQDlHi5fD6sByZUw5FOg9A" frameborder="0" allowfullscreen></iframe>
```

**Comment by jlyon** [comment]
live chat embed might be possible: https://www.peggyktc.com/2016/05/embed-livestream-and-chat.html#chat

**Comment by jlyon** [comment]
https://beta.proudcity.com/live/. Not sure how to enable chat on a livestream, but i _think_ the link above has details?  The login part of this shouldn't be an issue. If you're logged into gmail/youtube in your browser, you'll be logged in in the embed.

**Comment by kevindherman** [comment]
@jlyon I think just embedding the video without chat is great for now.
