### ISSUE TITLE
ELGL: upload file on gravity form disappearing

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1662]
ELGL has a webform that uses the file upload tool on this page:
https://elgl.org/covid-19

The form is COVID-19 Resources: https://elgl.org/wp-admin/admin.php?page=gf_entries&id=27

It looks like it's setup correctly but if you upload a file it is not being stored on the entries page or in the entry detail:
<img width="1131" alt="Screenshot 2020-03-12 10 59 25" src="https://user-images.githubusercontent.com/6032426/76534955-8df49880-6450-11ea-9d53-d32d129d9ef8.png">
or 
<img width="1146" alt="Screenshot 2020-03-12 10 55 31" src="https://user-images.githubusercontent.com/6032426/76534953-8df49880-6450-11ea-9be2-b3af53c99221.png">

@jlyon @aschmoe

**Comment by aschmoe** [comment]
@kevindherman the same form works on other sites, I'm guessing a plugin they have going is messing things up, but unclear.  Its not javascript / analytics so don't know what it would be.

We can investigate further, but honestly not sure what we'd discover.

**Comment by kevindherman** [comment]
@aschmoe I can ask.

**Comment by kevindherman** [comment]
@aschmoe could it be this business directory plugin? https://elgl.org/wp-admin/plugins.php

**Comment by aschmoe** [comment]
@kevindherman if you think there are a couple culprit plugins I could try downloading them onto beta and seeing what happens.

**Comment by kevindherman** [comment]
@aschmoe those are the only two to test. Could you give a go?

**Comment by kevindherman** [comment]
@aschmoe let's just close this since it's isolated.
