### ISSUE TITLE
Update font awesome to include covid-19 icons

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1665]
https://fontawesome.com/icons?q=covid-19&s=solid

**Comment by aschmoe** [comment]
![Screen Shot 2020-03-30 at 8 29 03 PM](https://user-images.githubusercontent.com/1634686/77984078-77aa6180-72c5-11ea-93cf-10148744d63f.png)

Added

**Comment by kevindherman** [comment]
@jlyon dope! thank you.
