### ISSUE TITLE
logging in as support redirect issues

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#167]
After logging in with the support@ account the URL path goes to:

https://www.westcarrollton.org/?message=TheredirectURIiswrong.Yousendhttps://www.westcarrollton.org,andweexpectedhttps://west-carrollton-oh.proudcity.com#/city/answers

The dashboard and editing bar don't show up on this page. 

I think something got crossed up with the redirect.

**Comment by jlyon** [comment]
Sorry, the new url for logging in as support should have the full url:
https://my.proudcity.com#https://www.westcarrollton.org

**Comment by kevindherman** [comment]
Still no dice, here's the error:

![screenshot 2016-02-23 11 02 30](https://cloud.githubusercontent.com/assets/6032426/13257500/06917d5c-da1d-11e5-983b-f52483120b12.png)

**Comment by jlyon** [comment]
Hmm, That just worked for me twice.  Please be sure to enter enter after pasting in the full url (including everything after the #) above.  

You should also be automatically logged in if you go to https://www.westcarrollton.org/wp-admin

**Comment by kevindherman** [comment]
wp-admin got me in, will test the others later. Sounds like I'm the issue.

On Tue, Feb 23, 2016 at 11:06 AM, Jeff Lyon <notifications@github.com>
wrote:

> Hmm, That just worked for me twice. Please be sure to enter enter after
> pasting in the full url (including everything after the #) above.
>
> You should also be automatically logged in if you go to
> https://www.westcarrollton.org/wp-admin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/167#issuecomment-187765752>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
