### ISSUE TITLE
Icon set: Make icon optional

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1670]
@jlyon @aschmoe I don't know if this would be a setting on the current iconset and/or icon link or it's own widget but it would be great to be able to have a solid color with text option in addition to white box with icon and text. 

For example, the option would replace the traditional iconset being used below and with color boxes, pulling from the same source as the simple heading above, it could also display white text on a dark background. I'm thinking a limited color option would help with maintaining contrast requirements and consistency with the site color customization.
<img width="1206" alt="Screenshot 2020-04-02 10 24 24" src="https://user-images.githubusercontent.com/6032426/78260735-4cde2a00-74cc-11ea-8036-885714c03413.png">

@jlyon @aschmoe what do you think?

**Comment by jlyon** [comment]
I made it so you can just leave the icon field empty. It will look like this:
<img width="829" alt="Screen Shot 2020-06-11 at 9 18 06 PM" src="https://user-images.githubusercontent.com/550909/84464353-20136500-ac29-11ea-9b28-b1cbd0261c8f.png">
