### ISSUE TITLE
Meetings: youtube bookmark editor

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1671]
@jlyon The youtube bookmarking tool uses seconds to pick the timestamp on the youtube video which can be kind of annoying to convert since the videos are long and display by minute + seconds on the front-end. This makes matching the bookmarks in seconds more tedious.

It's not a huge deal but would definitely make the experience better.

**Comment by jlyon** [comment]
We now have this language (not sure if it's new or not)
<img width="462" alt="Screen Shot 2020-05-07 at 7 39 24 PM" src="https://user-images.githubusercontent.com/550909/81364438-804b4000-909a-11ea-82c5-53a4b434c2ae.png">
