### ISSUE TITLE
/connect page layout

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1672]
@jlyon can you make the /connect page a layout for the platform: https://demo.proudcity.com/connect/

**Comment by kevindherman** [comment]
@jlyon pause on this until the heading option is done on this issue: https://github.com/proudcity/wp-proudcity/issues/1673

**Comment by jlyon** [comment]
just deployed this as a hotfix @kevindherman

**Comment by kevindherman** [comment]
@jlyon dope.

Thanks for remembering the widget titles.
