### ISSUE TITLE
Add title to Facebook and Twitter feed widgets

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1673]
@jlyon can you add a title to the Facebook/Twitter widgets like we have for the others? Make them an h2?

**Comment by lukefretwell** [comment]
@jlyon @aschmoe @kevindherman looks like the width is not mobile friendly. I doubt, but is there a way to make them 100%?

<img width="829" alt="Screen Shot 2020-04-02 at 9 58 47 AM" src="https://user-images.githubusercontent.com/1569463/78277152-e1468d80-74c8-11ea-9461-7c9ffb8283ca.png">

**Comment by jlyon** [comment]
@lukefretwell the fb widget adjusts width on page load to be responsive, but it won't adjust if you resize your browser width. I think the twitter widget works similarly.  There isn't a way to make the fb widget wider than 500px (you can play around w it on https://developers.facebook.com/docs/plugins/page-plugin/).

**Comment by jlyon** [comment]
just deployed the title addition this as a hotfix
