### ISSUE TITLE
Redirect WP login to my.proudcity

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1674]
Can we redirect the traditional WordPress login URL (/wp-login.php + anything else?) to my.proudcity.com.

**Comment by curtismchale** [comment]
Something like this should work for users that arrive at `wp-login.php`

```php
// REDIRECT THE DEFAULT WORDPRESS LOGIN PAGE
// =============================================================
add_action('init','custom_login');
function custom_login(){
 global $pagenow;
 //  URL for the HomePage. You can set this to the URL of any page you wish to redirect to.
 $blogHomePage = get_bloginfo('url');
 //  Redirect to the Homepage, if it is login page. Make sure it is not called to logout or for lost password feature
 if( 'wp-login.php' == $pagenow && $_GET['action']!="logout" && $_GET['action']!="lostpassword") {
     wp_redirect('/login/');
     exit();
 }
}
```

We likely also want to filter `login_url` so that in WP it always points to the location we want it to.
- https://developer.wordpress.org/reference/hooks/login_url/

**Comment by kevindherman** [comment]
@lukefretwell does that work for you?

**Comment by lukefretwell** [comment]
@kevindherman @curtismchale yes (I think so) 😆

**Comment by kevindherman** [comment]
@curtismchale @lukefretwell I'm following your guys' lead here.

**Comment by curtismchale** [comment]
@jlyon @aschmoe I need some feedback on this code please: https://github.com/proudcity/wp-proud-core/blob/6163db8812890236acb8c6e0729ae3f40d24d1e3/modules/proud-authentication/proud-authentication.php#L57

Specifically, will I need to exclude anything with Auth0 queries so that people are logged in as expected? This should **only** push people using standard WordPress login/password reset and send them to my.proudcity.com

**Comment by curtismchale** [comment]
@kevindherman @lukefretwell This is ready to go for the next release pending the answer from Jeff or Alex to [this comment](https://github.com/proudcity/wp-proudcity/issues/1674#issuecomment-1118896331) above.

**Comment by jlyon** [comment]
@curtismchale this looks good to me at a glance, but I'll test it tonight or tomorrow night to be sure.

**Comment by jlyon** [comment]
@curtismchale this worked without any issues.
