### ISSUE TITLE
Add accounts to Social Feed

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#168]
Alex, how do you add different social accounts to the social feed? Erika wants to make sure Parks & Rec is on there like the Fire Dept is.

Here's their FB page that she wants to pull from: 
https://www.facebook.com/WCparksandrec/?ref=hl

Sorry if this is a silly question, I don't see the option under settings > social feed

**Comment by jlyon** [comment]
for now we're doing it manually, so we'll add this.

**Comment by kevindherman** [comment]
Cool.

Post back when it's added and I'll close out with the client.

On Tue, Feb 23, 2016 at 1:08 PM, Jeff Lyon <notifications@github.com> wrote:

> for now we're doing it manually, so we'll add this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/168#issuecomment-187821608>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by kevindherman** [comment]
@jlyon when you add this to the feed can you also add their Farmer's Market FB page:

https://www.facebook.com/West-Carrollton-Farmers-Market-492270000826837/?ref=hl

**Comment by jlyon** [comment]
```
im trying to add those two accts 
```
curl -u proudCity -X POST -H "Content-Type: application/json" -d '{
    "name": "West_Carrollton,_Ohio",
    "agencies": [
        {
            "facebook": {
                "feeds": [
                    {
                        "type": "account",
                        "query": "WCparksandrec"
                    },
                    {
                        "type": "account",
                        "query": "West-Carrollton-Farmers-Market-492270000826837"
                    }
                ]
            }
        }
    ]
}' 'http://feeds.proudcity.com:8084/user/update'
```
and get
{"error":"message"}
```

**Comment by kevindherman** [comment]
@jlyon does the above post need anything from me?

**Comment by aschmoe** [comment]
No these were added last night.

**Comment by kevindherman** [comment]
Great.

I'll update in ZenDesk.

On Wed, Feb 24, 2016 at 12:33 PM, Alex Schmoe <notifications@github.com>
wrote:

> No these were added last night.
> On Feb 24, 2016 9:14 AM, "kevindherman" <notifications@github.com> wrote:
>
> > @jlyon <https://github.com/jlyon> does the above post need anything from
> > me?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/proudcity/wp-proudcity/issues/168#issuecomment-188357902
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/168#issuecomment-188368753>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by aschmoe** [comment]
#180
