### ISSUE TITLE
Meetings+Search+Docs

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1683]
- [x] Add meetings to search + docs.
- [x] Maintain filter capabilities with table view for meetings
- [x] Create page layout for meetings search

**Comment by aschmoe** [comment]
@kevindherman https://www.cityofsanrafael.org/meetings-search/?filter_keyword=ownership

**Comment by kevindherman** [comment]
@aschmoe thanks.

So the table view is for the archive and then it switches to list view for the search results? This should be fine but I want to confirm that experience is on purpose.

**Comment by kevindherman** [comment]
@aschmoe @jlyon 

Once a meeting a meeting has passed the primary search needs are minutes which are uploaded as a pdf file and finding staff reports which live in the plain text editor for the agenda packet.

The staff reports are hyperlinks that go to pdf files in the media library. The reports themselves do not need to be searchable. However, they need to be found by doing a search of the "topic line" or section within that plain text. 

Using this meeting as an example: https://www.cityofsanrafael.org/meetings/city-council-may-4-2020

Someone looking for the staff report in the section 6a "a. CDBG-Cares Act Funding Recommendations for FY2019-20" might put CDBG into the meetings search to find the staff report that lives in that section. 

Does this make sense? Let me know if you have any questions or concerns about these two use cases.
