### ISSUE TITLE
Rye Brook: cc statement line adjustments

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1686]
@jlyon we're still have some confusion with the credit card statement line but almost entirely with the Village of Rye Brook. Still, I'm getting calls and cancellations which costs us money so I'm hoping we can make adjustments, at least for them.

Maybe changing to [Account Name] Gov Payments by ProudCity will help.

This might just be on the webform side, but it would probably smart to add in the confirmation "this charge will appear as _______________ on your state". Any other ways to make this more dummy proof?

**Comment by jlyon** [comment]
Current statement descriptor: `PROUDCITY* RYE BROOK`: https://dashboard.stripe.com/payments/ch_1GfvYfK3yBBQrr5CB4akLHT1

Statement descriptor requirements: https://stripe.com/docs/statement-descriptors#requirements

We're using the Dynamic suffix: https://stripe.com/docs/statement-descriptors#dynamic
