### ISSUE TITLE
Make "Report an Issue" tab label translatable

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1694]
Change report an issue in the service center on https://bayside-wi.proudcity.com/ to "Service Request". They have SeeClickFix and use it for more than just issues but it's kind of misleading to the other services as "report an issue"

cc @jlyon

**Comment by jlyon** [comment]
@kevindherman this is all queued up on Bayside. I'll check that the language is correct after the deploy.

**Comment by jlyon** [comment]
Verified that this says Service Request now @kevindherman
