### ISSUE TITLE
Meetings: Add Agenda Packet tab

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1695]
@jlyon everything looks great on the individual meetings: https://bayside-wi.proudcity.com/meetings/board-of-trustees-meeting-april-16-2020/

But the meeting list widget still needs to display the agenda packet:
https://bayside-wi.proudcity.com/board-of-trustees-meetings/

**Comment by jlyon** [comment]
@kevindherman pushed to Bayside for testing.

**Comment by jlyon** [comment]
@kevindherman I added this. Settled on Just "Packet":
<img width="314" alt="Screen Shot 2020-05-21 at 9 02 29 PM" src="https://user-images.githubusercontent.com/550909/82630058-7818f780-9ba6-11ea-84bb-cb32e85bc5a5.png">

**Comment by kevindherman** [comment]
@jlyon this might be isolated to Bayside but I'm not seeing packet show up in table view when there is content: 
https://bayside-wi.proudcity.com/board-of-trustees-2019-meetings/
<img width="1214" alt="Screenshot 2020-05-22 10 57 41" src="https://user-images.githubusercontent.com/6032426/82681068-34aca080-9c1b-11ea-9e93-4518b2f6a70c.png">

Could it be that they're just doing attachment for the packet and not text? @jlyon

**Comment by jlyon** [comment]
@kevindherman yes, this was what was happening.  I pushed a fix for this to Bayside and SR.

**Comment by kevindherman** [comment]
@jlyon looks good.
