### ISSUE TITLE
Meetings: Add metafields to post_content so their content is searchable

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1696]

**Comment by jlyon** [comment]
@aschmoe I set this up. You'll just need to tie in here to do the file upload indexing https://github.com/proudcity/wp-proud-meeting/blob/8ecf0caf36eddefb29de0998b23d1d47082e7a0c/wp-proud-meeting.php#L145

**Comment by aschmoe** [comment]
@jlyon attachment indexing is handled in wp_proud_search_elastic, so nothing to do here.
