### ISSUE TITLE
Holyoke: add location error.

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1697]
As soon as I start entering information I get this error:
<img width="1425" alt="Screenshot 2020-05-21 15 22 51" src="https://user-images.githubusercontent.com/6032426/82597605-36bd2380-9b77-11ea-91ca-28bc67328f0c.png">

**Comment by kevindherman** [comment]
- https://www.nagd.com/

- https://www.holyoke.org/

**Comment by jlyon** [comment]
@kevindherman I fixed this for holyoke and these sites. I also updated the trello launch template:
<img width="521" alt="Screen Shot 2020-05-21 at 8 51 23 PM" src="https://user-images.githubusercontent.com/550909/82629584-05f3e300-9ba5-11ea-9b24-0f46ebb847df.png">
