### ISSUE TITLE
Fairfax Meetings: Agenda information posts several times within one meeting

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1701]
@jlyon this meeting on Fairfax is posting the agenda multiple times: https://www.townoffairfax.org/meetings/town-council-special-meeting-may-27-2020/

This happened after the release.

I don't know if it's related to this but the meeting list widget is also displaying teaser text from the agenda which is new and potentially related: https://www.townoffairfax.org/departments/meetings-agendas/
<img width="760" alt="Screenshot 2020-05-26 07 53 05" src="https://user-images.githubusercontent.com/6032426/82897664-f3233a80-9f25-11ea-9cdb-aed71c9a7b1f.png">

**Comment by kevindherman** [comment]
@jlyon it looks like the meeting list feed is just showing the teaser text on the first item. Jackson is reporting it too:

<img width="1209" alt="Screenshot 2020-05-26 11 39 25" src="https://user-images.githubusercontent.com/6032426/82920723-a3ed0200-9f45-11ea-8ebc-53d1d61ec531.png">

**Comment by jlyon** [comment]
@kevindherman pushing this platform-wide as Hotfix 1.90.2: Agenda information posts several times within one meeting #1701

**Comment by kevindherman** [comment]
@jlyon SR is reporting that this is still an issue: https://www.cityofsanrafael.org/meetings/city-council-may-18-2020/
