### ISSUE TITLE
Contact list widget: list view include more information

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1705]
https://belmont-nc.proudcity.com/meet-your-city-council/

- include bio text or at least a teaser
- exclude post on date
- include title

**Comment by jlyon** [comment]
Went with the full bio and a right sidebar w contact info:
<img width="1089" alt="Screen Shot 2020-06-10 at 11 05 43 PM" src="https://user-images.githubusercontent.com/550909/84350868-00b80180-ab6f-11ea-8b29-6d8e7575cd88.png">
