### ISSUE TITLE
Delete old events from template sites

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1712]
Old events are showing up in search even though they have either passed or have been deleted. 

https://marinrecovers.com/search-site/?term=office
<img width="1202" alt="Screenshot 2020-07-01 15 14 46" src="https://user-images.githubusercontent.com/6032426/86282686-b6de9c00-bbad-11ea-81bb-e42cdbefda49.png">

I went to events in the dashboard and tried to view past events and it didn't yield any results. The trash wasn't an option to permanently delete so I'm not sure how to get rid of the lingering event. 

This comes up pretty consistently since we're cloning city template and need to delete some stuff like events before launching. 

@jlyon @aschmoe

**Comment by jlyon** [comment]
@aschmoe to come up w list of events on pc.com.
@jlyon to write migration to apply to all sites

**Comment by aschmoe** [comment]
@jlyon the post ids seem consistent... not sure if deleting across the board is wise?

- https://demo.proudcity.com/event/dodgeball-tourney/ - 2193
- https://demo.proudcity.com/event/national-night-out/ - 2549
- https://demo.proudcity.com/event/presidents-day-city-offices-closed/ - 3086
- https://demo.proudcity.com/event/gingerbread-house-decorating-workshop/ - 2603
- https://demo.proudcity.com/event/citizen-police-academy/ - can't find this one, but exists here - https://demo.proudcity.com/event-sitemap.xml
- https://demo.proudcity.com/event/bza-meeting/ - 341
- https://demo.proudcity.com/event/planning-commission/ - 339

**Comment by jlyon** [comment]
citizen-police-academy = 3577

**Comment by jlyon** [comment]
This one still needs some work (rebuild and re-run). I should be able to run this platform-wide sometime in the next couple days @kevindherman

**Comment by jlyon** [comment]
@kevindherman I ran this on marinrecovers.com and demo.proudcity.com. Deleted these files:
Deleted 2193 dodgeball-tourney
Deleted 2549 national-night-out
Deleted 3086 presidents-day-city-offices-closed
Deleted 2603 gingerbread-house-decorating-workshop
Deleted 341 bza-meeting
Deleted 339 planning-commission

Could you double-check and if everything looks good on these 2 sites, we'll run it platform-wide in the next release?
