### ISSUE TITLE
Standalone service center broken logo

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1714]
@jlyon @aschmoe the standalone service center has a broken image where the logo goes:

https://www.cityofbelmont.org/standalone
<img width="1150" alt="Screenshot 2020-07-07 09 28 41" src="https://user-images.githubusercontent.com/6032426/86791445-88dadb00-c037-11ea-9a74-34356f2437cf.png">

**Comment by aschmoe** [comment]
@kevindherman hotfixed this.  Only complication I can see is maybe with Kiosk `/kiosk` views... but SR is only one I'm aware of and looks ok.
