### ISSUE TITLE
Add 'Search help' to Help dropdown

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1718]
I'd like for us to think about a better way direct folks to help when deeper in the admin.

Ideas:

* Add 'Search help' link to the 'Help' dropdown that links to https://help.proudcity.com. Would also make the order this: 'Search help' / 'Create a ticket' / 'Live chat'
* Add a 'Help' link to the blue PC bar in the admin that directs to a 'Help' page (like we have for 'Analytics'). Ideally, it would have a search bar there, but fine to just have three icons ('Search help' / 'Create a ticket' / 'Live chat').
* When we do the above bullet, remove the support chat box.

**Comment by jlyon** [comment]
Changed "Docs & Guides" to "Search help" and updated the order to your list @lukefretwell.  Here's what this menu looks like now:
<img width="298" alt="Screen Shot 2020-07-16 at 10 47 08 PM" src="https://user-images.githubusercontent.com/550909/87752980-7179bb80-c7b6-11ea-883e-61ad5dc9b279.png">


Updating the admin bar is more difficult. Created a new issue to track this: https://github.com/proudcity/wp-proudcity/issues/1722

**Comment by lukefretwell** [comment]
@jlyon @kevindherman I'm still seeing this (+ the 'Support' button in the lower right):

<img width="1146" alt="Screen Shot 2020-07-20 at 2 37 18 PM" src="https://user-images.githubusercontent.com/1569463/87989378-c8bdab80-ca96-11ea-83f2-7b6cb5c307a1.png">

**Comment by jlyon** [comment]
@lukefretwell yep the support button is still on the dashboard and on the site admin. Once we take care of the steps in #1722 I'll work on removing the support pill globally.  This should get in the next release
