### ISSUE TITLE
Add a 'Help' link to the blue PC bar in the admin that directs to a 'Help' page

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1722]
From https://github.com/proudcity/wp-proudcity/issues/1718
- Add a 'Help' link to the blue PC bar in the admin that directs to a 'Help' page (like we have for 'Analytics'). Ideally, it would have a search bar there, but fine to just have three icons ('Search help' / 'Create a ticket' / 'Live chat').
- When we do the above bullet, remove the support chat box.

**Comment by jlyon** [comment]
@lukefretwell @kevindherman Just want make sure that we're setting this up as intended. Questions:
1. Do we want to remove the support pill everywhere (like when you're editing pages), or just on the dashboard pages (both standalone and embedded)?
2. Do we want to add anything to the topnav like when you're editing pages?

![Screenshot - 2020-07-23T213747 652](https://user-images.githubusercontent.com/550909/88361289-5fa39580-cd2d-11ea-8fb1-5d0ca69968d1.png)
![Screenshot - 2020-07-23T214559 239](https://user-images.githubusercontent.com/550909/88361466-ebb5bd00-cd2d-11ea-9101-0d6b72071f77.png)

**Comment by kevindherman** [comment]
@jlyon this looks right to me but I'd like @lukefretwell to confirm. @lukefretwell can you chime in to make sure it's what you had in mind?

**Comment by lukefretwell** [comment]
@jlyon @kevindherman my suggestion would be to:

1. Remove the pill everywhere.
2. Add 'Help' link to the top or somewhere universal. Ideally, the help would include a dropdown like what we have in the first screen.

**Comment by kevindherman** [comment]
@jlyon you are correct with your screenshots.

**Comment by kevindherman** [comment]
@lukefretwell the dropdown option in the blue bar is posing challenges but a direct link is fine. Should it link to the help.proudcity.com homepage or directly to submitting a ticket?

**Comment by lukefretwell** [comment]
@kevindherman @jlyon let's do help.proudcity.com. @kevindherman we'll just need to make it prominent how to submit a ticket once they get there.

**Comment by jlyon** [comment]
I was able to get the menu going, so I set that up. I didn't get a change to add it to the dashboard, but I'll try to get that setup this weekend @kevindherman @lukefretwell
