### ISSUE TITLE
Agenda packet label in table view links to agenda not packet

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1724]
@jlyon the label for agenda packet in the meeting list widget links to the agenda rather than the agenda packet information in the meeting details.

https://www.cityofsanrafael.org/city-council-meetings/
<img width="858" alt="Screenshot 2020-07-17 09 36 46" src="https://user-images.githubusercontent.com/6032426/87792039-4c666680-c811-11ea-87dc-88ad9560a233.png">

If you select "agenda packet" it sends to the agenda tab: https://www.cityofsanrafael.org/meetings/city-council-june-1-2020/#/tab-agenda

Minutes and video label/tab linking works correctly.

**Comment by jlyon** [comment]
Done, will be in the next release
