### ISSUE TITLE
Kettering: file upload to webform not showing in entries

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1726]
Webforms that use the file upload feature are not capturing the files. I tested by filling out the form and attached a file but when I looked at the form entries the file was not there.

https://www.ketteringoh.org/#/city/report/embed/report-property-maintenance-concern

https://www.ketteringoh.org/wp-admin/admin.php?page=gf_entries&id=34

Could this be related to the open issue: https://github.com/proudcity/wp-proudcity/issues/1561

**Comment by aschmoe** [comment]
@kevindherman looks like they had the gravity forms <> stateless module enabled, I've made our handling smart enough to not process if that is enabled.  

Also looks like they have the constant contact plugin enabled, so will have to see if that is also interfering after release

**Comment by aschmoe** [comment]
@kevindherman looks good far as I can tell... probably worth it to check in on ELGL to see if also fixed there

![Screen Shot 2020-07-30 at 11 08 06 PM](https://user-images.githubusercontent.com/1634686/89005542-97748500-d2b9-11ea-9028-e62e3460cc08.png)
