### ISSUE TITLE
Give slideshow component background like other hero/jumbotron displays

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#1729]
![Screen Shot 2020-07-30 at 10 29 08 PM](https://user-images.githubusercontent.com/1634686/89003230-1797ec00-d2b4-11ea-9c16-2b8584d5da8f.png)

**Comment by aschmoe** [comment]
@kevindherman @lukefretwell deployed as hotfix to test (not prod yet)

**Comment by aschmoe** [comment]
https://santa-ana-ca.proudcity.com/ looks good

**Comment by kevindherman** [comment]
@aschmoe @lukefretwell dope! I really like how Santa Ana used this mid page slideshow.

**Comment by lukefretwell** [comment]
@aschmoe thank you! Looks gooood!
