### ISSUE TITLE
Times aren't displayed on /events

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#173]
https://www.westcarrollton.org/event/planning-commission-meeting-3-2016-03-03/
https://www.westcarrollton.org/events/

**Comment by kevindherman** [comment]
Erika reported this morning that the add event to calendar feature is not posting the correct date. I'm waiting to get more information on this one.

**Comment by jlyon** [comment]
Hmm, we're not displaying times on http://pattern.getproudcity.com/#sg-event-list either.

**Comment by aschmoe** [comment]
You think display time on the main page, not on the list?  Or both?

**Comment by kevindherman** [comment]
Thanks, will pass along to WC.

On Fri, Feb 26, 2016 at 2:25 PM, Jeff Lyon <notifications@github.com> wrote:

> Closed #173 <https://github.com/proudcity/wp-proudcity/issues/173>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/173#event-568054616>.
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
