### ISSUE TITLE
Fairfax: webform, file upload field PDF files view as broken link in email notification + entries

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1730]
After the release last week I'm getting feedback on two bugs on the webform file upload feature:
1- PDF files appear as broken when you view entries
2- The link to each file in the email submission just links to the homepage
Here's an example entry with a funky PDF: https://www.townoffairfax.org/wp-admin/admin.php?page=gf_entries&view=entry&id=37&lid=1593&order=ASC&filter&paged=1&pos=0&field_id&operator

**Comment by jlyon** [comment]
@kevindherman is this now fixed with https://github.com/proudcity/wp-proudcity/issues/1752?

**Comment by kevindherman** [comment]
@jlyon I think but depends on the question I left in #1752 because that gravity form compatibility is no longer an option from the media/stateless settings.
