### ISSUE TITLE
Dupe answers don't show drop-down information on second question

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1736]
When there's a repeat of a question (from 'Answers') on a page, it doesn't show information when you click on the second drop-down.

Screenshot:

<img width="486" alt="Screen Shot 2020-08-24 at 6 07 14 PM" src="https://user-images.githubusercontent.com/1569463/91111309-0fbe3400-e635-11ea-86d5-21f1ab2b2fed.png">

**Comment by kevindherman** [comment]
@lukefretwell can you post a link to where this is happening?

**Comment by kevindherman** [comment]
@lukefretwell I found the page: https://solanocountyrecovers.org/agencies/active-incidents/

However the answer isn't listed in two categories anymore. 

Here's the specific answers content: https://solanocountyrecovers.org/wp-admin/post.php?post=8278&action=edit

If you add it to 'Electricity' in addition to water, you can test what @lukefretwell is describing.
