### ISSUE TITLE
Dashboard updates

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1739]
I'd love to think about how we can update the dashboard. Adding my thoughts here for future discussion.

* When you click on the icons on the main dashboard after logging in, it opens a new window. Can we remove that?
* Re-order icons:
Pages
News
Answers
Departments
Contacts
Events
Jobs
Documents
Payments
Forms
Issues
Media
* Add 'Guides' h2/section with these icons/links: https://help.proudcity.com/guides/
* Make nav have 'Help' dropdown' like on admin section where we added to the right of 'Dashboard' link. Doesn't matter if it's in the same place (thought mimicking that navbar would be great), but would be great to have it just say 'Help' with same dropdown links then consolidate 'Support,' 'Docs,' 'Feedback' links int that. If we can do this, I would remove the 'Help' tab/dropdown to the right of the 'Dashboard | Analytics | Marketplace | Payments' nav.
* Remove 'Support' button on bottom right like we did on inside admin pages.

**Comment by aschmoe** [comment]
> Re-order icons:

Done, was pretty cached for me, so be patient if not working for you.

> Add 'Guides' h2/section with these icons/links: https://help.proudcity.com/guides/

Added

**Comment by aschmoe** [comment]
> Remove 'Support' button on bottom right like we did on inside admin pages

Never saw this anywhere

**Comment by aschmoe** [comment]
> When you click on the icons on the main dashboard after logging in, it opens a new window. Can we remove that?

Think this logic is pretty baked into the login process.  Going to skip for now
