### ISSUE TITLE
Style/improve /add-event

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#174]
- [x]  Fix field formatting (css), esp date section
- [ ]  Hide Booking section
- [ ]  Use select2 for category selection?
- [ ]  Verify submission workflow (email gets sent, etc)

**Comment by aschmoe** [comment]
@jlyon should we just be disabling booking completely?

**Comment by jlyon** [comment]
i think so, probably. want to isolate the correct option and we can either hotfix it or deploy it in the automated steps in release 1.9.0?
