### ISSUE TITLE
Sonoma: mailoptin campaigns not loading

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1741]
@jlyon when you go to edit an automation the page doesn't load to configure the email:
<img width="1391" alt="Screen Shot 2020-09-09 at 5 42 46 PM" src="https://user-images.githubusercontent.com/6032426/92658108-00411b00-f2c4-11ea-8d39-c6c535b52388.png">

Here's the Zendesk issue:

Hello - I have run into this issue before and don't recall how to work around it. I am trying to add an email auto notification. I created the form, the contact list in constant contact and the e-news category, but am having (and have had difficulty in the past) with the final step of adding a new, or editing a copy of an existing email automation (https://www.sonomacity.org/wp-admin/admin.php?page=mailoptin-email-automations).

When I attempt to "add new" - it just doesn't save. When I try to go in an edit a copy of an existing, it is just blank (https://www.sonomacity.org/wp-admin/customize.php?mailoptin_email_campaign_id=26). What am I missing?

**Comment by jlyon** [comment]
@kevindherman this has been fixed with https://mailoptin.io/article/fixing-wordpress-customizer-not-loading/

**Comment by jlyon** [comment]
I also fixed this on the other 3 sites using the plugin.
