### ISSUE TITLE
Holyoke: location errors

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1745]
@jlyon @aschmoe Holyoke is getting map errors in several places: vote lookup, my services and maps. See attachment:

![mapbug](https://user-images.githubusercontent.com/6032426/93240351-031f8e00-f752-11ea-9cd7-44253a0f9e7b.PNG)

I'm assuming this is a Google API bug but I'm not sure. Can you take a look and let me know if you need anything to resolve?

**Comment by jlyon** [comment]
@kevindherman I fixed this

**Comment by kevindherman** [comment]
@jlyon https://www.holyoke.org/vote#/city/vote/42.2110582,-72.6290009/536%20Dwight%20St,%20Holyoke,%20MA%2001040,%20USA/how
