### ISSUE TITLE
News widget: add excerpt to news posts

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1746]
Add excerpt field on visual editor to be able to customize excerpt text on new list widgets. 

https://rutherfordton-nc.proudcity.com/news/

**Comment by kevindherman** [comment]
@jlyon it looks like events allows for this functionality. 

See https://www.cityofsanrafael.org/event/san-rafael-day-of-the-dead-memories-of-altars-past-2013/

**Comment by kevindherman** [comment]
@jlyon @aschmoe is there a reason to block hyperlinks in the excerpt? I noticed that was the case on this news list widget:

https://williams-county-nd.proudcity.com/road-updates/

**Comment by aschmoe** [comment]
@kevindherman 

![Screen Shot 2020-12-03 at 12 53 54 PM](https://user-images.githubusercontent.com/1634686/101087416-08c58c80-3567-11eb-98e0-ce98a2fe4fe2.png)
