### ISSUE TITLE
Events: stay within event list widget through day of event rather than time of event

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1747]
events cycle off event list widget at the start time of the event. It would be helpful if they stayed posted in the event list widget for the entire day.

This is a problem for events that are promoting online meetings. People show up a little late and then can't find the meeting links.

**Comment by kevindherman** [comment]
@jlyon this was brought up by another city. I thought that events were being cycled off the event list at the time of the event but both Fairfax and San Rafael are saying that events are removed from the event list two hours before their start time which seems problematic. 

Let's bump this up to see if there is something that can be done so events stay on the event list until after the event passes.

**Comment by aschmoe** [comment]
@kevindherman going out with release
