### ISSUE TITLE
Image uploads are pixelated

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1750]
Looks like the background image is pixelating, perhaps due to the sizing constraints added to the end of the image file name.

See Slack for video.

Example: https://proudcity.com/test-home/

**Comment by aschmoe** [comment]
Issue

like: 

> https://storage.googleapis.com/proudcity/wwwproudcity/uploads/c8f2de70-895becbec1a5bc1d2bcf5af739dc70b4.png

instead of:

> https://storage.googleapis.com/proudcity/wwwproudcity/uploads/2020/10/c8f2de70-895becbec1a5bc1d2bcf5af739dc70b4.png

see: https://github.com/udx/wp-stateless/issues/560

**Comment by kevindherman** [comment]
customer examples:

- https://newfairview.org/
- https://williams-county-nd.proudcity.com/

**Comment by jlyon** [comment]
Fixed this with the commit ^^.
