### ISSUE TITLE
Add 'starred' option in webform entries list

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1751]
On the webform entries page there is a bulk action to filter by 'starred' entries. How do you star an entry and can we add a column for starred items?

<img width="472" alt="Screen Shot 2020-10-15 at 10 50 42 AM" src="https://user-images.githubusercontent.com/6032426/96146651-86a8d800-0ed4-11eb-917e-e9752d4b9c9f.png">

I'm not seeing the starred option as a column option in this view:
<img width="777" alt="Screen Shot 2020-10-15 at 10 52 52 AM" src="https://user-images.githubusercontent.com/6032426/96146758-a5a76a00-0ed4-11eb-965b-97d225786073.png">

**Comment by jlyon** [comment]
@kevindherman doesn't look like what we did for this one solved it. I'll look to hotfix it over the weekend.

**Comment by jlyon** [comment]
@kevindherman A fix for this is going up in this release.

![Screenshot (57)](https://user-images.githubusercontent.com/550909/99031572-45840200-252c-11eb-8d42-2ae151ea5a72.png)
