### ISSUE TITLE
Files being saved to the media library adds random numbres/letters to the front of the file name.

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1754]
After I added this file to the Fairfax media library it added a bunch of random numbers to the front of the file name in storage:

https://storage.googleapis.com/proudcity/fairfaxca/uploads/2020/10/519922a4-screen-shot-2020-10-16-at-8.45.45-am.png

Changing the file name to 519922a4-screen-shot-2020-10-16-at-8.45.45-am.png from Screen Shot 2020-10-16 at 8.45.45 AM

This seems to be a google storage thing. 

It's a front end issue because for things like meetings or documents it shows the weird new name above the download button:
https://www.townoffairfax.org/meetings/climate-action-committee-meeting-october-20-2020/

**Comment by jlyon** [comment]
@kevindherman fixed this on fairfax. We'll push it platform-wide in the next release. If you need to set it up for specific sites before then, you can set Cache Busting to Disabled on /wp-admin/upload.php?page=stateless-settings:
![Screenshot (33)](https://user-images.githubusercontent.com/550909/96957719-41763e80-14b0-11eb-946b-5e3f3f6bf21d.png)

**Comment by kevindherman** [comment]
@jlyon thanks!
