### ISSUE TITLE
Mystery event

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1757]
On newly created sites (potentially more), there is a single event that shoes  in a red circle on the event dashboard but when you look at all events or any other filters it cannot be found:

<img width="712" alt="Screen Shot 2020-10-19 at 9 35 45 AM" src="https://user-images.githubusercontent.com/6032426/96458473-f679d400-11ee-11eb-95b1-187abc556aa5.png">

It's originating from City Template but I'm not sure what the event is or where it is to remove it.

@jlyon @aschmoe

**Comment by kevindherman** [comment]
https://montgomery-oh.proudcity.com/

**Comment by jlyon** [comment]
Culprit (I think): https://montgomery-oh.proudcity.com/wp-admin/post.php?post=2551&action=edit

I deleted this on montgomery, but I'm still seeing the red dot next to Events.  Also deleted in citytemplate, and will be deleted platform-wide in the next release @kevindherman

**Comment by kevindherman** [comment]
@jlyon I'm still seeing the red event dot as well. Because it's also on city-template and new instances I'm not sure it's a Montgomery specific event.
