### ISSUE TITLE
Replace More Jobs feed with a Jobs button on the Jobs detail page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1759]
Remove more jobs feed from job detail page:

https://montgomery-oh.proudcity.com/job/community-development-director/

**Comment by jlyon** [comment]
Do this
```
<div class="card-wrap"> <a href="/documents" class="card text-center card-btn card-block" style="height: 117px;"> <i aria-hidden="true" class="fa far fa-newspaper fa-3x"></i>        <div class="h4">More Job Postings</div> </a>      </div>
```
<img width="1440" alt="Screen Shot 2020-11-05 at 12 45 59 PM (1)" src="https://user-images.githubusercontent.com/550909/98294661-2b16bb00-1f65-11eb-85fb-61b8df7e638b.png">

**Comment by jlyon** [comment]
Set this up @kevindherman. Note: the button's url is hardcoded to /jobs.
![Screenshot (56)](https://user-images.githubusercontent.com/550909/99031417-e1f9d480-252b-11eb-8e0b-419f9a83b3f8.png)
