### ISSUE TITLE
White banner and "1" under blue banner

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#176]
@aschmoe @jlyon Between the main blue banner and the jumbo image there is a white bar with the number 1. This is happening in Chrome and FF on my mac and has also been reported by Erika on her pc.

![screenshot 2016-02-24 09 41 16](https://cloud.githubusercontent.com/assets/6032426/13288724/409ee232-dadb-11e5-9fbe-243d236df6aa.png)

When you scroll down and the banner shrinks the white bar goes away.

![screenshot 2016-02-24 09 42 27](https://cloud.githubusercontent.com/assets/6032426/13288746/5cc06a80-dadb-11e5-9002-271e3ee0b9e6.png)

**Comment by jlyon** [comment]
Fixed this.
