### ISSUE TITLE
Williams: bottom of dept menu cutoff

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1760]
https://williams-county-nd.proudcity.com/job-openings/

<img width="287" alt="Screen Shot 2020-10-20 at 2 40 05 PM" src="https://user-images.githubusercontent.com/6032426/96629961-4d140a80-12e2-11eb-98c4-ed6c035b1b66.png">

**Comment by aschmoe** [comment]
@kevindherman think we have solution for this (release)
