### ISSUE TITLE
Update online quote content

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1761]
@aschmoe could you add "ProudCity Documents" linking here: https://proudcity.com/documents to the online quote tool between ProudCity Forms and ProudCity Payments in the top section?

<img width="1081" alt="Screen Shot 2020-10-26 at 8 23 20 AM" src="https://user-images.githubusercontent.com/6032426/97206872-b044e780-178f-11eb-95e3-6f5d337f31e5.png">

**Comment by aschmoe** [comment]
@kevindherman this is done

**Comment by kevindherman** [comment]
@aschmoe thank you, looks good.

cc @lukefretwell ^
