### ISSUE TITLE
platform: remove mobile app submission from service center settings

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1769]
Remove dedicated Mobile App option from the Service Center settings:

<img width="1339" alt="Screen Shot 2020-11-05 at 2 48 23 PM" src="https://user-images.githubusercontent.com/6032426/98289373-15f65800-1f76-11eb-9d1d-9101a87d5e19.png">

@jlyon

**Comment by jlyon** [comment]
@kevindherman Removed all reference to the mobile app in the service center.
