### ISSUE TITLE
Digital Marin: submit form buttons

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1770]
@aschmoe @lukefretwell this is from the Marin accessibility folks on the submit button on the contact form. Should the button match the secondary color which they have tested? What do you think is best, probably worth baking this into the product.

> I still need to test the form fields, but already noticed a problem with the colors for the Submit button. The button background color is #428bca and text is white; this is only a 3.6:1 contrast ratio. The ratio is even worse when I hover over the button and the colors change to #3276b1 and #333333 where the ratio is only 2.6:1.

Here's the contact form: 
https://digitalmarin-ca.proudcity.com/contact

**Comment by lukefretwell** [comment]
@aschmoe @kevindherman looks like the `background-color` should be the primary color:

`.gform_wrapper .button, .gform_button`

Also needs to be the same for the hover state.

Checklist:

- [ ] Make `.gform_wrapper .button, .gform_button` `background-color` as primary color

- [ ] Make hover CSS same as above bullet

**Comment by aschmoe** [comment]
@lukefretwell should be good (release)

**Comment by aschmoe** [comment]
Looks like iframe gravity form buttons were missed in this
