### ISSUE TITLE
Change Department sub-page Back menu behavior

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1771]
https://williams-county-nd.proudcity.com/inmate-information/
<img width="1257" alt="Screen Shot 2020-11-10 at 2 15 42 PM" src="https://user-images.githubusercontent.com/6032426/98722690-5cc1c480-235f-11eb-91b3-3b6f3712a762.png">

When on this division page for inmate information, the back menu item opens up the previous menu section for the correctional center but doesn't load the correctional center page. Would it be possible for that back button to load the previous menu item instead of just toggling to it?

@aschmoe

**Comment by jlyon** [comment]
Completed: Make parent menu click on slider menu go to parent
