### ISSUE TITLE
platform: search results page heading structure

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1779]
I got this message about the search results page heading structure. @aschmoe could you update the search shortcode for the platform to following the heading structure outlined below:

In doing a deep dive into the accessibility of our new Digital Marin site, I found a problem with the heading structure on the Search Results page that is not under our control to fix. I believe that Proud City has to fix the level of the “Results” heading that appears just above the list of search results. When I use the editor to view this page, it just has “[proud_search_shortcode]" as the contents.

 

Currently heading structure is this after I search for “canal”:

<h1>Search Results</h1>

<h3>Results</h3>

<h3>Canal WiFi Project...</h3>

<h3>Agencies / Organizations...</h3>

<h2>Welcome</h2>

<h2>Engage</h2>

<h2>Help</h2>

 

But the structure would be much improved if “Results” was an h2, not an h3.

**Comment by aschmoe** [comment]
@lukefretwell this will go out with release
