### ISSUE TITLE
Add option to allow hiding of document post date per-site

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1783]
The files being added to Cherry Township's meetings have November 25,2020.pdf being added to the file name:
https://cherry-township-pa.proudcity.com/meetings/board-of-supervisors-regular-meeting-december-1-2020/
<img width="1116" alt="Screen Shot 2020-12-02 at 4 12 23 PM" src="https://user-images.githubusercontent.com/6032426/100932189-7fa44c00-34b9-11eb-8af7-8e5e8e85e8f1.png">

The name of the file is the first part. 

Same thing happens on this meeting item:
https://cherry-township-pa.proudcity.com/meetings/board-of-supervisors-regular-meeting-november-4-2020/

Interesting enough it's only an issue on the agenda not the minutes.
@jlyon

**Comment by jlyon** [comment]
This is just the date the document was added and seems to be displaying platform-wide (see https://www.cityofsanrafael.org/meetings/bicycle-pedestrian-advisory-committee-december-2-2020/). Should we remove this date?

**Comment by kevindherman** [comment]
@jlyon yeah, I think the date should be removed.

**Comment by jlyon** [comment]
@kevindherman I set `wp option update proud_document_show_date 0 --alllow-root` and this date is no longer showing on https://cherrytownship.com/meetings/board-of-supervisors-regular-meeting-december-1-2020/.

**Comment by jlyon** [comment]
@kevindherman set this value on city template for all new sites going forward.
