### ISSUE TITLE
Glossary feature

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1786]
Source: MC

Here's a note from Digital Marin after creating a glossary page: 
https://digitalmarin-ca.proudcity.com/glossary/

They were considering using the Answers list widget for a faq but just used the text widget with some support from their end. Check out their suggestion:

Something to add to your someday list for accessibility.   As you recall we had our glossary on text widgets.   I decided not to go with the FAQ solution and save that for our eventual FAQ section.  Anyway, our Accessibility team requested using ‘Description’ HTML tags to help people with readers or navigation aids.   Description List, Description Term, and Description Definition.   Here is an example. 

 

<dl>

               <dt>Bandwidth</dt>

               <dd>The amount of data transmitted in a given amount of time; usually measured in Megabits per second (Mbps).</dd>

               <dt>Broadband</dt>

               <dd>High-speed Internet access that allows users to access the Internet and Internet-related services at significantly higher speeds than those available through "dial-up" services; current Federal speed requirements are 25/3 Mbps - a download speed of 25 Mbps and an upload speed of 3 Mbps.</dd>

</dl>

 

  Cathy updated the stylesheet for me and we are implementing it using the text editor.    I think other users would like a glossary template that handled this for them.

**Comment by lukefretwell** [comment]
Looks like there are a few plugins we should review:

* https://wordpress.org/plugins/glossary-by-codeat/
* https://wordpress.org/plugins/heroic-glossary/
