### ISSUE TITLE
Contact list widge: add Title in display for list view

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1793]
Right now the list display in the contact list widget displays everything except the contact position field, can this be included in the display? I think under the name or on the right where the contact info is: https://new-buffalo-mi.proudcity.com/city-council/

<img width="862" alt="Screen Shot 2020-12-09 at 11 49 45 AM" src="https://user-images.githubusercontent.com/6032426/101659989-a7913380-3a14-11eb-8648-84e5b15cd930.png">

**Comment by kevindherman** [comment]
@jlyon what would also be nice if the list view displays all. Is that if they omit a field like email or phone that the label is hidden. That could be a way to give flexibility like the hide column option on the table view for this display.

**Comment by jlyon** [comment]
Added Title. I also made it so the label doesn't show if there is no value for Title, Phone, Email fields.
![Uploading Screenshot (94).png…]()
