### ISSUE TITLE
Platform: form confirmation message yields "Oops! We could not locate your form."

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1797]
This form gets a confirmation message of "oops! we could not locate your form".

The data is entered into entries and everything else fires correctly, but the confirmation is an error:

https://www.montgomeryohio.org/dinner-around-the-world-recipe-form/

The same issue is happening on this form on Lucas: 

https://www.lucastexas.us/firefighter-commendation-complaint-comment-form/

I noticed on both that they both had a mistake in the notification section that the send to email was set to {admin_email}. I changed this on both sites hoping that that was causing some sort of issue on the confirmation side but it doesn't appear to have made a difference (tested in incognito).

Montgomery confirmed that this is not on all all forms so I'm really not sure what's causing the issue after not getting better results after changing the notification item above.

@jlyon @aschmoe any ideas?

**Comment by jlyon** [comment]
Looked into this one @kevindherman, but couldn't get to to the bottom of it. I'll look at fixing it as a hotfix.

**Comment by kevindherman** [comment]
@jlyon thanks, keep me posted.

**Comment by jlyon** [comment]
@kevindherman I couldn't get to the bottom of this, but I was able to fix the form at https://www.montgomeryohio.org/dinner-around-the-world-recipe-form/ by switching out the ProudCity Forms block with a Text block with the Gravityforms shortcode `[gravityform id="27"]`:
<img width="1161" alt="Screen Shot 2021-01-28 at 9 44 40 PM" src="https://user-images.githubusercontent.com/550909/106236610-1d628180-61b2-11eb-88b4-5f9eacc53fcb.png">

It looks like the Lucas form no longer exists.

**Comment by kevindherman** [comment]
@jlyon thanks for finding that work around which I think is fine since this seems to be mostly isolated.

I've communicated this to Montgomery and have reached out to Lucas to see if the page exists somewhere else or if they've moved on. I see how you set this up so I can test it out on Lucas if it's still a thing.
