### ISSUE TITLE
Backend styles

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#18]
- [x] Style form builder popup
- [x] Hide SEO link in header
- [x] Quickmenu box
- [x] Field labels
- [x] Hide "Add pg element"
- [x] Clean up side menu
- [x] Responsive admin toolbar (hide icons+positioning)
- [x] Link logo to PC
- [x] Collapse Yoast fieldset

**Comment by jlyon** [comment]
- [ ] Link logo (frontend)

**Comment by jlyon** [comment]
@aschmoe, noticed 2 things after your pattern lib changes (just because the menus are different on proud-admin). Maybe we should add a class to body or html in the frontend theme?

- [ ] at large: extra padding up top:

- [ ] at sm: proudbar isn't all the way at the bottom

**Comment by jlyon** [comment]
@aschmoe, noticed 2 things after your pattern lib changes (just because the menus are different on proud-admin). Maybe we should add a class to body or html in the frontend theme?

- [ ] at large: extra padding below the topnav:
![screenshot from 2016-02-03 21 25 09](https://cloud.githubusercontent.com/assets/550909/12806676/f83565e4-cabc-11e5-8df1-515661c9fae0.png)

- [ ] at sm: proudbar isn't all the way at the bottom
![screenshot from 2016-02-03 21 24 56](https://cloud.githubusercontent.com/assets/550909/12806678/009b3ba0-cabd-11e5-99dc-d52a45055e7c.png)

**Comment by aschmoe** [comment]
Should the proudbar even print on the back-end?

**Comment by aschmoe** [comment]
@jlyon moved some of that code into front end only stuff.  Need to restructure probably but will work for now.

**Comment by aschmoe** [comment]
Looks like some of the mobile backend needs to be cleaned up

**Comment by jlyon** [comment]
>Should the proudbar even print on the back-end?
We talked about this on a call last week and decided it should.

> Looks like some of the mobile backend needs to be cleaned up
added to checklist above. I'm going to move some stuff (top admin bar) into pattern lib

**Comment by jlyon** [comment]
@aschmoe i think i cleaned up the backend mobile responsive.  Add checkbox items up above if you notice anything
