### ISSUE TITLE
Allow alternate label for Issue

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1800]
Change "report issue:" to "Service Request: "

https://williams-county-nd.proudcity.com/issues/vector-control-spray-request/

**Comment by jlyon** [comment]
Changed this prefix to "Service Request:".

Also change Issue to Service request throughout the admin by adding these translation strings to https://williams-county-nd.proudcity.com/wp-admin/tools.php?page=say_what_admin&orderby=domain&order=asc:
![Uploading Screen Shot 2021-01-14 at 8.49.58 PM.png…]()
