### ISSUE TITLE
Platform Support TLS 1.3

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1803]
https://github.com/kubernetes/ingress-nginx/issues/2384

- Probably need to upgrade kubernetes nginx-ingress image
- Add flag like
```
nginx.ingress.kubernetes.io/ssl-protocols: "TLSv1.3 TLSv1.2"
```

**Comment by kevindherman** [comment]
@jlyon the report you requested:

[report.pdf](https://github.com/proudcity/wp-proudcity/files/5822202/report.pdf)
