### ISSUE TITLE
Issues with event calendar widget not displaying

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1805]
The calendar widget is not displaying on https://www.lucastexas.us/events/ even though it's setup correctly and has events to display.

![Screen Shot 2021-01-19 at 10 57 32 AM](https://user-images.githubusercontent.com/6032426/105059500-59c10f80-5a45-11eb-924e-374a7f9a8a44.png)

I have added the event list below with the same categories selected and events do list.

Other calendars on the platform appear to be working as they should.

**Comment by kevindherman** [comment]
@jlyon @aschmoe this appears to be platform wide now. Williams County is also reporting the issue.

**Comment by aschmoe** [comment]
@kevindherman @jlyon update:

Looked like maybe issue was with w3-total-cache, so I updated that plugin, because when unminified in w3-total-cache things seemed to work fine.  It did not fix the problem.

Might need to roll back that jQuery migrate plugin

**Comment by kevindherman** [comment]
@jlyon to run jqueery migration on next release. Reference https://github.com/proudcity/wp-proudcity/issues/1798 for additional info.
