### ISSUE TITLE
Warr Acres: mobile menu

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1810]
Warr Acres has contrast issues being too dark just in mobile: https://www.warracres-ok.gov/

<img width="499" alt="Screen Shot 2021-01-25 at 8 33 53 AM" src="https://user-images.githubusercontent.com/6032426/105712783-4c45d280-5ee8-11eb-9112-dd788ea3568b.png">

**Comment by kevindherman** [comment]
They have dropdowns enabled which may be playing a role in this issue.

**Comment by aschmoe** [comment]
@kevindherman looks like this piece of css was added to the customizer.

![Screen Shot 2021-02-04 at 8 50 12 PM](https://user-images.githubusercontent.com/1634686/106991454-147e2c80-672b-11eb-95a8-213dd31763ce.png)

I've commented it out for now.  @lukefretwell did you add this or was that the client?

**Comment by lukefretwell** [comment]
@aschmoe not sure if you resolved, but I most likely did that when we first started using the white background and there was a bug in the text color?
