### ISSUE TITLE
petaluma: iframe in mobile help

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1812]
@aschmoe @jlyon I got this message about helping adjust an iframe on Petaluma. We made some minor adjustments for them before but I'm not sure how to address this issue. Any suggestions or quick fixes?

Hey Kevin,

Here are the two pages were having problems with.  Each is an iframe with an embedded mapping application.  The first is coming from the City’s own GIS web application (Districts) and the other is from LexusNexus (Crime).  When you open these on your desktop, you’ll notice that both maps employ a disclaimer popup that must be clicked before the map loads.  When resize the window, or view either page on a phone screen, the iframes don’t resize in way that moves that disclaimer box to the middle of the screen.  The user therefore can’t get to it to click the continue button and load the map.

https://cityofpetaluma.org/police-district-assignments/

https://cityofpetaluma.org/police-crime-map/

**Comment by kevindherman** [comment]
- so when I load this on my phone the popup is off the screen
- the refresh doesn't work

This is URL from the iframe: https://xara1-4.cityofpetaluma.net/jsviewers/policemap/

When I go to that link directly from my phone is works correctly.

@jlyon @aschmoe could this the full width settings of the Petaluma site?

**Comment by kevindherman** [comment]
Jeff was fine on Android so it might be a mobile safari thing.

**Comment by aschmoe** [comment]
@kevindherman added some css seems to work

![Screen Shot 2021-02-04 at 9 03 07 PM](https://user-images.githubusercontent.com/1634686/106992060-6ffcea00-672c-11eb-9296-b659e2aca0da.png)
