### ISSUE TITLE
Johnson City: location error when creating a new location

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1814]
@jlyon @aschmoe when creating a new location on Johnson City it pretty immediately throws an error:
![Screen Shot 2021-02-08 at 2 31 47 PM](https://user-images.githubusercontent.com/6032426/107271668-8f409380-6a1a-11eb-82df-ac07cc3c6ae9.png)

@jlyon as a reminder, this is the site that replaced a previous version of itself so I'm wondering if there's a weird database or google map thing throwing off their locations since this is isolated.

**Comment by jlyon** [comment]
@kevindherman Fixed this.
