### ISSUE TITLE
platform: are you sure you want to leave alert

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1815]
The message popup that used to only show if you navigate away from a page without saving your changes "are you sure you want to leave?" is now showing up even after updating. 

Are you sure you want to leave?

**Comment by aschmoe** [comment]
@kevindherman is this on a given content type, pagebuilder active, normal editor?

**Comment by kevindherman** [comment]
@aschmoe I've gotten tickets for pages and documents but in some quick testing I'm just getting it when editing pages (visual and pagebuilder).

**Comment by jlyon** [comment]
looked into this a little
- It's not jquery migrate (disabled it, still got the error)
- No updates to so-pagebuilder in the last release
- Might be something w the last wp core update https://github.com/woocommerce/woocommerce/issues/28557 `Hi, It's seems like some part have a problem with update 5.6.1 for me now works fine a had a problem with this bug in previous versions before update.` 4 days ago

**Comment by jlyon** [comment]
Downgrading WordPress core (reverting the 5.6.1 maintenance release) fixed this issue.
