### ISSUE TITLE
Time view for "all day" events

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1816]
On "all day" events, could the time of the event just say "All Day" or have no time at all instead of "All Day - 11:59 pm"?

**Comment by jlyon** [comment]
Removed the `- 11:59 pm` for all day events. I also increased the padding between the time and the buttons. Will go up in the next release.
![Screenshot - 2021-02-11T213905 031](https://user-images.githubusercontent.com/550909/107734194-af3db480-6cb1-11eb-8091-82ec3224f89a.png)
 @kevindherman
