### ISSUE TITLE
Danvers: all contacts changed

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1817]
All contacts and emails listed on departments for Danvers have changed from @danversma.gov to @www.danversma.gov.

See this dept:

https://www.danversma.gov/departments/accounting-department/

And each individual contact:

https://www.danversma.gov/contacts/daniel-c-bennett/

@jlyon @aschmoe I dont know how this happened and appears to be unique to them. Is there a script that can be run to switch them so they don't have to be individually updated?

**Comment by kevindherman** [comment]
@jlyon here's some following that might have to do with cloudflare stuff with Danvers:

> A resident called and said that she tried this around the first of the month and it didn’t work. She tried again today and decided to call us. Additionally, we had some links break at the beginning of the month where it added www to the beginning of some sub domains (ie. The water bill payment link) and those didn’t forward. Those have all been adjusted though as far as I know.
> 
> * Bryan

**Comment by jlyon** [comment]
@kevindherman I fixed the email issue by doing a search and replace on @www.danversma.gov `wp --allow-root search-replace "@www.danversma.gov" "@danversma.gov"` 494 updates.

Is there anything to do for the second item? It sounds like that was fixed.

**Comment by kevindherman** [comment]
No, their IT person fixed that I just wanted you to have all the information.

Thanks!
