### ISSUE TITLE
Add underline to links in <main>

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1828]
Per convo with @aschmoe @kevindherman, would be great to add underline to text links inside `<main>`, not including:

* cards
* service center
* other?

**Comment by aschmoe** [comment]
Added

```
p a,
h1 a,
h2 a,
h3 a,
h4 a,
h5 a,
h6 a {
  text-decoration: underline;
}
```

There will likely be issues on both sides (underlined when undesirable, not underlined when desirable) so lets just track those
