### ISSUE TITLE
Disable File URL Replacement wp-stateless setting

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1829]
We were seeing some serious performance issues that appear to be this issue. https://github.com/udx/wp-stateless/issues/265#issuecomment-453946157

> Ok, so to fix performance problem need to use Disable or Enable Editor options for File URL Replacement setting.

**Comment by kevindherman** [comment]
@jlyon this seems to be helping so far. What does it actually do when enabled or disabled?

**Comment by jlyon** [comment]
Ran migration in `wp-proudcity/updates/release-1.105.0.sh`.

Set constant in wp-config.php
