### ISSUE TITLE
Services map: Google maps api not pulling data details

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1830]
If you select a pin in the services map it doesn't show location detail with a sorry message:

https://demo.proudcity.com/community/
https://www.cityofmontclair.org/community

<img width="1141" alt="Screen Shot 2021-03-10 at 1 04 02 PM" src="https://user-images.githubusercontent.com/6032426/110688717-e53a5f80-81af-11eb-9261-7c09e7e5211f.png">

**Comment by jlyon** [comment]
@kevindherman I pushed a fix for this. It might require a hard refresh (Shift+Refresh) for you to see the updates: https://demo.proudcity.com/community/#/maps-1/map/fire_station/details/ChIJtSjQ9klrYogRphJRbe-DauU
