### ISSUE TITLE
Meetings: Add External Video option

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1834]
In ProudCity, at the ability for the video pill that opens up a YouTube embed directly in the page will instead open a new tab/window going to swaggit such as: https://lucastx.new.swagit.com/videos/114068

That video link would be entered into the video field in the backend of creating a meeting.

**Comment by kevindherman** [comment]
@jlyon I noticed for the folks who have youtube videos already on their meetings information, the pill is not displaying on the meeting list widget. 

https://www.holyoke.org/city-council-meetings/
<img width="999" alt="Screen Shot 2021-03-26 at 10 42 12 AM" src="https://user-images.githubusercontent.com/6032426/112652066-625a0b80-8e23-11eb-932f-00140088edc5.png">

Event though the meetings detail does have youtube videos:
https://www.holyoke.org/meetings/holyoke-city-council-meeting-8/
<img width="1073" alt="Screen Shot 2021-03-26 at 11 07 20 AM" src="https://user-images.githubusercontent.com/6032426/112652193-84538e00-8e23-11eb-8101-62851a88dd13.png">

@jlyon I wonder if this is because legacy videos do not have the the selection of "youtube" when they were originally created, they just pasted into the field.

This is platform wide for people using meetings.

**Comment by jlyon** [comment]
Fixed this in Hotfix 1.106.2: Meetings: Add External Video option - fix missing Video link for existing meetings #1834 (wp-proud-theme)
