### ISSUE TITLE
Add to Calendar does not add event details when click from an Event List

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1840]
Using the add to calendar feature add all information, including event description when using the add to calendar feature on an event detail: https://www.cityofmontclair.org/event/easter-eggstravaganza-drive-thru-event/

But when you use the same tool directly from the event list widget it does add to the calendar but not with the details in the event description:

https://www.cityofmontclair.org/events/

**Comment by aschmoe** [comment]
@kevindherman going out with release
