### ISSUE TITLE
Forms: checkbox being used as conditional logic in webform displaying large

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1841]
The checkbox formatting is very large for the conditional logic checkbox: https://www.montgomeryohio.org/independence-day-parade-application/

Choose Vehicle for type of parade unit. Then the insurance question will appear which an oversized checkbox (bottom of the form)

<img width="687" alt="Screen Shot 2021-03-26 at 2 52 50 PM" src="https://user-images.githubusercontent.com/6032426/112684032-d6f37100-8e48-11eb-837c-7b089c2f7952.png">

**Comment by aschmoe** [comment]
@kevindherman going out with release
