### ISSUE TITLE
Improve Email Deliverability

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1846]
Got this ticket from West Carrollton:

"Hi - We've noticed several emails - submitted forms - have not reached us. After looking at them I noticed a SMTP error showing at the bottom of the form entry. Could you advise please? You can reference "Park Shelter Reservation Form : Entry # 3896" as an example.
Thanks."

I noticed that their WP Mail SMTP did have an error message:
https://www.westcarrollton.org/wp-admin/admin.php?page=wp-mail-smtp
<img width="1315" alt="Screen Shot 2021-04-27 at 3 05 06 PM" src="https://user-images.githubusercontent.com/6032426/116298400-68b50d80-a76a-11eb-8a13-26909c763260.png">

**Comment by jlyon** [comment]
@kevindherman Switching our SMTP provider to Mailgun has been pushed platform-wide as  Hotfix 1.109.1: Improve Email Deliverability #1846 - 2021-05-20 @kevindherman

**Comment by kevindherman** [comment]
@jlyon awesome
