### ISSUE TITLE
San Rafael - Answers taxonomy structure not quite correct?

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#1852]
![Screen Shot 2021-05-13 at 11 08 14 PM](https://user-images.githubusercontent.com/1634686/118229114-47c60b00-b440-11eb-8f30-bfb115d96c8e.png)

San Rafael the only one I'm seeing where clicking into a category isn't showing sibling categories... probably an issue with Answer category depth?

**Comment by kevindherman** [comment]
@aschmoe seems isolated.

See this here shows the siblings:

https://mebane-nc.proudcity.com/#/city/answers/city-hall/
![Screen Shot 2021-05-14 at 9 05 27 AM](https://user-images.githubusercontent.com/6032426/118274769-8f29b700-b493-11eb-892e-90a1db5c6486.png)
