### ISSUE TITLE
Calendar: more option on single day with lots of events yields an error

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1854]
Within the calendar, on days where there are lots of events there is an option for "more..."

https://www.danversma.gov/events
![Screen Shot 2021-05-18 at 10 36 27 AM](https://user-images.githubusercontent.com/6032426/118671339-61ab7900-b7c5-11eb-8529-d44a604217cd.png)

That links to a page not found with a URL like this (/event/year-month-day): https://www.danversma.gov/event/2021-04-28/

**Comment by jlyon** [comment]
@kevindherman I couldn't figure out how to fix this more link,  so I just made the limit per day super high (10) on https://www.danversma.gov/wp-admin/options-general.php?page=wp-fullcalendar, so the more link never appears.  Here's how it looks.

I only added this to Danvers and citytemplate (new sites going forward). LMK if you think it needs to be released to every existing site as a migration.

**Comment by jlyon** [comment]
@kevindherman I also updated citytemplate for new sites going forward with a little bit nicer theme, and i disabled the tooltips, because they don't seem very helpful on Danvers. lmk what you think: https://demo.proudcity.com/calendar

**Comment by kevindherman** [comment]
@jlyon thanks this works for both danvers and city template. 

I think it's worth deploying platform wide since more people are using it.
