### ISSUE TITLE
Fix Facebook share url in Proudbar

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1856]
The the share to facebook option in the proud-bar opens up in Facebook but you're not actually able to submit the share once the share page open sin FB:
https://redistricting.solanocounty.com/
![Screen Shot 2021-05-23 at 10 02 15 AM](https://user-images.githubusercontent.com/6032426/119263686-1a026400-bbae-11eb-9fab-6ed1f8584c09.png)

From Zendesk:
Benton and I were able to replicate the issue on Google Chrome.  Attached are the screenshots showing the difference between Firefox and Chrome. 

In chrome, the URL only gets the main URL and doesn't post. 
![2021-05-21_15-44-07](https://user-images.githubusercontent.com/6032426/119263638-e8899880-bbad-11eb-95ad-5c993e901961.jpg)

@jlyon @aschmoe

**Comment by jlyon** [comment]
@kevindherman pushed a fix to solanocaredistricting to fix this immediately, which will be pushed platform-wide in the next release.
