### ISSUE TITLE
Update Gravity Forms to latest

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1859]
Details: https://www.gravityforms.com/two-five-form-editor/

Todos:
- [ ] Update wp-proud-admin styling.  It seems like removing Bootstrap from this is the best way to fix the unusable new Gravityforms styles
- [ ] Prepare documentation for the Gravityforms update and include it in the release notes one cycle before we release these updates
- [ ] verify that the code in `wp-proud-ip-block/gravity-forms.php` in the `check_country` function works with the new filter that was introduced in 2.7 and retire the "old" code that was written to work with our older version of Gravity Forms
- [ ] Deploy

These updates to gravityforms kinda redid the entire form building experience.  We'll need to update the admin styling so it doesn't look as bad as it currently does, and we'll probably want to warn folks about the upcoming change @kevindherman

From Alex: We should probably also verify that the new column formatting doesn't break anything with bootstrap gravity forms (it probably does)

**Comment by kevindherman** [comment]
@jlyon @aschmoe yeah the quick look that I had on the updated version after the last release was a pretty significant difference and definitely needed some theming love. 

Let's discuss this in the meeting next week.
