### ISSUE TITLE
Demo: answers box blank

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#186]

**Comment by kevindherman** [comment]
After spinning up a demo from proudcity.com the answers area is blank:

![screenshot 2016-02-29 15 08 20](https://cloud.githubusercontent.com/assets/6032426/13407471/949fbafe-def6-11e5-8119-54760721eff0.png)

If I think click on answers or payments the box fills in as it should:

![screenshot 2016-02-29 15 08 34](https://cloud.githubusercontent.com/assets/6032426/13407490/a7aa08a2-def6-11e5-8616-296835e10f54.png)

This is happening in Chrome and FF.

**Comment by aschmoe** [comment]
This is not true for me, would you mind giving me exact steps?

Thanks!

**Comment by kevindherman** [comment]
1- find your city from proudcity.com homepage
2- entered Great Barrington, MA (Luke had this issue with another city)
3- Great Barrington demo comes up
4- answers box is empty

On Mon, Feb 29, 2016 at 3:12 PM, Alex Schmoe <notifications@github.com>
wrote:

> This is not true for me, would you mind giving me exact steps?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/186#issuecomment-190363663>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by jlyon** [comment]
Hmm, seems to be specific to Great Barrington, MA or a few other cities.  Seems like it's related to the map maybe.

**Comment by aschmoe** [comment]
This is fixed.  Please reload the window on the demo to get new JS

**Comment by kevindherman** [comment]
Working for me. Thanks Alex.

On Mon, Feb 29, 2016 at 5:01 PM, Alex Schmoe <notifications@github.com>
wrote:

> This is fixed. Please reload the window on the demo to get new JS
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/186#issuecomment-190416816>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
