### ISSUE TITLE
Add popout option for documents/meeting files that are too large to preview

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1865]
Create option next to download button to popout a new window to the media file link when the google PDF previewer displays too large of a file to display.

Here's an example of an agenda packet that is displaying the too large to preview error (review agenda packet tab):
https://cityofmebanenc.gov/meetings/city-council-meeting-july-12-2021/
![Screen Shot 2021-07-22 at 4 10 28 PM](https://user-images.githubusercontent.com/6032426/126703224-00e58138-0bde-43ba-9caa-f90169684a8a.png)

The popout in the previewer goes to another too large to preview page.

As an alternative, adding a button in these scenarios next to or under the download button on the left would be helpful.

**Comment by jlyon** [comment]
@kevindherman I'm seeing the preview on the document on https://cityofmebanenc.gov/meetings/city-council-meeting-july-12-2021/. Maybe it's something browser-specific that's preventing the embed from working? Are you still getting the error on this document?

I have the popout updates in progress, but they're not quite ready for the release.

**Comment by kevindherman** [comment]
Don't forget to look at the agenda packet tab.

**Comment by jlyon** [comment]
@kevindherman the issue with the agenda packet tab on  https://cityofmebanenc.gov/meetings/city-council-meeting-july-12-2021/ is that the file that the download button links to is not found for some reason: https://cityofmebanenc.gov/wp-content/uploads/2021/07/July-12-2021-Packet.pdf.

The file that you linked to with the Agenda Packet link just appears to be the agenda (it's really small and is only 1 page), attached. If you can get them to send you the agenda packet, I can play around with it and see if there is a specific issue.

For now, I'm holding off on adding the "Popout" button.

**Comment by kevindherman** [comment]
@jlyon got it.  I removed and re-added the July 12 packet file and it's still yielding the funny preview issue. Take a look and let me know if this helps make the adjustments.

**Comment by kevindherman** [comment]
@jlyon add button for "view" for the pop out option.

**Comment by jlyon** [comment]
Unchecked the `Show the embedded document preview` checkbox to hide the document viewer
![Screen Shot 2021-08-12 at 12 55 42 PM](https://user-images.githubusercontent.com/550909/129261142-78b398a2-63e4-4c7f-a4fd-6f68434eb368.png)
