### ISSUE TITLE
top bar on Marin DPW is centered.

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1868]
Marin DPW site has the topbar activated with a menu called "top bar" and two things are being funky:

1- the action icons are centered
2- the topbar menu isn't displaying even though it's activated and selected

Worth noting, this is using the Recovers theme so that could have something to do with the difference. 

https://marin-dpw-ca.proudcity.com/

<img width="1281" alt="Screen Shot 2021-08-12 at 9 37 47 AM" src="https://user-images.githubusercontent.com/6032426/129206623-72c26810-e5cb-4a1d-9097-3f0fcc3cbf1a.png">
<img width="1394" alt="Screen Shot 2021-08-12 at 9 37 53 AM" src="https://user-images.githubusercontent.com/6032426/129206629-bc019a2d-e37c-4f44-b0cf-e1fa0eae75b0.png">
<img width="992" alt="Screen Shot 2021-08-12 at 9 38 00 AM" src="https://user-images.githubusercontent.com/6032426/129206632-082ac077-af7b-4b4c-a973-e0dfb76d73e6.png">

**Comment by jlyon** [comment]
I fixed this with some custom css in the theme customization settings for this site. @aschmoe we should probably look at adding this to the theme if you think this code makes sense

```
@media screen and (min-width: 911px) {
	.flexbox .navbar-topbar .menu-box {
		right: 0;
		position: absolute;
	}
}
```
