### ISSUE TITLE
Allow custom link for topbar logo or text

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1869]
https://marin-dpw-ca.proudcity.com/

Link the words "An official website of Marin County" in the topbar to https://www.marincounty.org/

It should pop out in a new window.

**Comment by jlyon** [comment]
I ran into some issues setting up my local environment to work on this so I didn't get to it @kevindherman

**Comment by jlyon** [comment]
@kevindherman I deployed this on Marin DPW as a hotfix, it will be deployed to the platform in the next release. You can set the link on https://marin-dpw-ca.proudcity.com/wp-admin/customize.php?return=%2Fwp-admin%2Fthemes.php.
<img width="297" alt="Screen Shot 2021-09-22 at 9 56 48 PM" src="https://user-images.githubusercontent.com/550909/134456540-9aac5ce4-14e0-4671-b3dd-0a14e4a34c77.png">

**Comment by kevindherman** [comment]
@jlyon this is great.

@lukefretwell what are your thoughts on this for an in between for an official gov option?

**Comment by kevindherman** [comment]
@jlyon add field for hover to replace "home".

**Comment by jlyon** [comment]
@kevindherman I added an additional field "Top Bar accessibility title" for the `title` attribute that shows on hover.  This has been deployed to Marin DPW only.
![Uploading Screen Shot 2021-09-23 at 10.29.04 PM.png…]()
