### ISSUE TITLE
GA not showing in dashboard

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#187]
GA not showing up in the dashboard when logged in as support@

![screenshot 2016-02-29 16 58 34](https://cloud.githubusercontent.com/assets/6032426/13410468/ef92ccb2-df05-11e5-9588-43907c279796.png)
![screenshot 2016-02-29 16 58 42](https://cloud.githubusercontent.com/assets/6032426/13410467/ef922d34-df05-11e5-8125-edcb14d45661.png)

**Comment by jlyon** [comment]
Hmm, they were there when I logged in to support, but they were pulling from the old BETA analytics account.  I updated it so it pulls from the new account and added Erika's email and your email to the GA account.  It it showing up for your now?

**Comment by jlyon** [comment]
Hmm, it's still hidden for me when I logged in in an incognito window.  I think it maybe requires an account that's logged into Google Analytics.  Let me know if it's working for you now.

**Comment by kevindherman** [comment]
Yeah it's still not working for me.


On Mon, Feb 29, 2016 at 5:37 PM, Jeff Lyon <notifications@github.com> wrote:

> Hmm, it's still hidden for me when I logged in in an incognito window. I
> think it maybe requires an account that's logged into Google Analytics. Let
> me know if it's working for you now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/187#issuecomment-190431146>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by jlyon** [comment]
ok ill look into it

**Comment by jlyon** [comment]
need to look at this after we push the release

**Comment by jlyon** [comment]
Note to self: permission settings for the dashboard widget are on /wp-admin/admin.php?page=gadash_backend_settings.

@kevindherman tried looking into this some more today without luck.  Will continue looking at it tom.

**Comment by kevindherman** [comment]
Godspeed @jlyon

**Comment by jlyon** [comment]
I think I'm gonna get rid of that plugin once we launch Calypso, so I'm going to put this one to bed.

**Comment by kevindherman** [comment]
Ok, I'll let WC know. The timing for that is next release, right?

**Comment by jlyon** [comment]
Yah, they'll be able to preview it (see the analytics dashboard) next week

**Comment by kevindherman** [comment]
Great, I'll pass this info along.

On Tue, Mar 22, 2016 at 1:25 PM, Jeff Lyon <notifications@github.com> wrote:

> Yah, they'll be able to preview it (see the analytics dashboard) next week
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/187#issuecomment-199917376>
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by jlyon** [comment]
Releasing the new dashboard today.

**Comment by kevindherman** [comment]
@jlyon this is still an issue on WC.
