### ISSUE TITLE
Williams county: Unable to submit a form after making corrections

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1875]
Unable to submit a form after making corrections. Seems to only be happening in non-Chrome browsers.

Form: https://www.williamsnd.com/township-loan-application/
password is townships123

If you complete part of it, submit, and get errors, then correct the errors and submit, all responses are wiped out and the form reloads.

I think the browser gets confused by the URL change when it changes to /#/error/ maybe?

I took the password off in case that was part of the issue, but I don't think that made a difference.

@jlyon @aschmoe

**Comment by jlyon** [comment]
@kevindherman I wasn't able to replicate this issue with this form in Chrome, Safari or Firefox. What browser + version were you able to replicate it in?
