### ISSUE TITLE
Review and add to layout template library

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1876]
## To do

- [ ] Review templates for accessibility and general aesthetics
- [ ] Reach out to community about layout template ideas

**Comment by lukefretwell** [comment]
@jlyon @aschmoe @kevindherman I'll follow up with specifics, but this may be a request for a new theme.

**Comment by kevindherman** [comment]
@lukefretwell is this part of or related to this issue: https://github.com/proudcity/wp-proudcity/issues/1880

**Comment by lukefretwell** [comment]
@kevindherman mostly yes. I'm just going to close this one.
