### ISSUE TITLE
Update accessibility statement text to specify 2.0

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1879]
@aschmoe should we update the statement to include 2.0?

Change first bullet to:

> Fully compliant with Section 508 and conformance to WCAG 2.0 Level AA.

Reference: https://proudcity.com/accessibility-statement

**Comment by jlyon** [comment]
I made this update, but I'm going to just leave it to get picked up in the next release @kevindherman

**Comment by kevindherman** [comment]
@lukefretwell sorry to be late on this one, is there any language we should borrow from this Digital Marin site that was written by their accessibility team for our statement: https://godigitalmarin.org/accessibility-statement/
