### ISSUE TITLE
Montclair: meetings list pager widget bugs

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1882]
There are two issues with the event list widget:

- The 'Previous' and 'Next' buttons are not working in some instances.
- The button color contrast need to be updated to be more accessible.  

## To-do

- [ ] Fix bug
- [ ] Make buttons accessible

**Comment by kevindherman** [comment]
This was flagged with a meetings list for Montclair:

https://www.cityofmontclair.org/departments/public-meetings/
![Screen Shot 2021-09-16 at 3 28 40 PM](https://user-images.githubusercontent.com/6032426/133673637-b5925496-930e-4a3c-8f48-2473adec0e69.png)

**Comment by kevindherman** [comment]
@aschmoe this appears to be meetings and event list widgets but not news.

**Comment by aschmoe** [comment]
@kevindherman this is a weird one, can't replicate locally or with a test.

Check this unpublished meeting (you'll have to publish it)
https://www.cityofmontclair.org/meetings-test/

Might have something to do with our W-3 caching layer or perhaps some other conflict.  Bit at a loss.

**Comment by kevindherman** [comment]
@aschmoe huh, I'll keep an eye out for other instances.

**Comment by kevindherman** [comment]
@aschmoe going through the backlog, do you think this issue is related: https://github.com/proudcity/wp-proudcity/issues/1430

**Comment by curtismchale** [comment]
@lukefretwell @kevindherman I took a look at this after #2000 but I don't even see the previous/next buttons on the meeting list.

Were they removed since as a stop gap fix or...?

**Comment by kevindherman** [comment]
@curtismchale take a look here: https://www.cityofmontclair.org/all-upcoming-meetings

I think it's actually working now.

**Comment by curtismchale** [comment]
@kevindherman can we close this issue now?

**Comment by kevindherman** [comment]
@curtismchale yeah, you can,.
