### ISSUE TITLE
Gravity Forms Export doesn't work if site has multiple replicas

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1887]
The Gravity Forms integration in  wp-stateless uploads form file uploads to Google Cloud Storage, but CSV exports of form entries are still downloaded directly from the server.

This is problematic if the site has multiple replicas in Kubernetes, because any single request might hit any one of multiple servers, and only one server will have the CSV export file expected.

Path forward:
- Integrate exports with wp-stateless so these files are uploaded to Google Cloud and then requested from there
- Or see if the export can be served up directly without being saved and then redirected to the file
- See if wp-stateless devs can help (they've been responsive in the past). Not seeing this issue yet on https://wordpress.org/search/gravity+forms+intext%3A%22Plugin%3A+WP-Stateless+-+Google+Cloud+Storage%22/

To replicate:
Export entries from a Gravity Form on a site with multiple Kubernetes replicas (prod santaanaca). The file should download.  Try multiple times and ensure that you don't get a 404 error on any of your attempts.

---
Original ticket:

https://www.montgomeryohio.gov/wp-admin/admin.php?page=gf_entries&id=46

When you export the form and leave the date range blank for all entries, the download is blank. The export does work if you put in a date range. 

This is less alarming once I learned that leaving the range blank was the issue, however, that should still work.

**Comment by kevindherman** [comment]
Now I am unable to export data at all. I have no clue what changed so this is a higher priority now.

**Comment by jlyon** [comment]
https://docs.gravityforms.com/resolving-issues-gravity-forms-exports/

**Comment by jlyon** [comment]
This is a larger issues with multiple replicas.  Able to replicate on SR.

**Comment by kevindherman** [comment]
@jlyon what do you mean by replica? I want to make sure I can spot these scenarios.

**Comment by kevindherman** [comment]
@jlyon SR is reporting this for the "Pre-Application for Notice of Funding Availability" form.

**Comment by kevindherman** [comment]
@jlyon mentioned that since @curtismchale has been looking at stateless and webform stuff that he may have insight on taking this one over.

**Comment by kevindherman** [comment]
@jlyon @curtismchale We got a support ticket today that seems like it's related to this card:

`Good morning – I am trying to export the entries from two separate forms: 1. Third Street Rehab Public Meetings (form is all the way down at the bottom of the webpage) (https://www.cityofsanrafael.org/third-st-rehab/) and 2. COVID-19 Outdoor Dining and Retail - Permit Application (https://www.cityofsanrafael.org/covid-outdoor-dining/) .

To do so, I go to the “Forms” tab, I click on “Import/Export” -> Select a form from the dropdown menu (i.e. Third Street Rehab Public Meetings )-> select the fields I want to export -> click on “download export file”. However, this always downloads a blank csv file (please see attached). The same thing happens when I try it for the COVID-19 Outdoor Dining and Retail - Permit Application (https://www.cityofsanrafael.org/wp-admin/admin.php?page=gf_edit_forms&id=105) form.`

I was able to replicate this.

@curtismchale @jlyon

**Comment by curtismchale** [comment]
@kevindherman this appears to be fixed, at least I just downloaded CSV entries from Montgomery without a date set and the `.csv` file had stuff in it.

I'm marking this as "ready for release" unless I hear different from you.

**Comment by kevindherman** [comment]
@curtismchale sounds good,
