### ISSUE TITLE
Desert Hot Springs: right align navbar icons in the topnav when there is not a topbar menu

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1888]
https://desert-hot-springs-ca.proudcity.com/

Currently when the navbar icons are moved to the topbar and there is not a topbar menu, the icons are centered. 
![Screen Shot 2021-10-04 at 3 30 59 PM](https://user-images.githubusercontent.com/6032426/135913086-6813095d-5d3f-41ea-8b1f-65709b45aa14.png)

Can the default when this is the case, be that they are right aligned like Marin DPW: https://marin-dpw-ca.proudcity.com/
<img width="1335" alt="Screen Shot 2021-10-04 at 3 34 18 PM" src="https://user-images.githubusercontent.com/6032426/135913206-f2502e06-bfe6-470a-b6e3-7d67e7b997d8.png">

**Comment by aschmoe** [comment]
@kevindherman added the 1-off styling to this site.  Prioritize this in the weekly for a global fix.

**Comment by kevindherman** [comment]
@aschmoe thank you!
