### ISSUE TITLE
Service center icon

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1893]
> An icon, whose meaning is not commonly known, is used in multiple places within the Service Center. Recommend adding visible link text next to each icon. A simple underlined link of "Return to previous" is probably best in all cases.

![Screenshot 2021-10-25 at 12-09-25 Answers - ProudCity Help Center](https://user-images.githubusercontent.com/1569463/138755399-2d768e8a-1756-471a-a7db-f078231a8e07.png)

## Suggestion

Use the `<` icon instead and don't show until it's able to go back. If link text is required then accompany with 'Back.'

**Comment by jlyon** [comment]
We had "sr-only" tags next to most of these `fa-th` icons with screen reader-only text.  I started showing this text.  It Return to previous" in all instances, but rather describes the page ("Select category", etc).

![Screenshot - 2021-11-04T222543 909](https://user-images.githubusercontent.com/550909/140462770-d0df5004-10c7-49bc-8348-b67f77670150.png)
