### ISSUE TITLE
Service center lists mark-up

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1898]
> Some elements are incorrectly coded as lists which may confuse some users. 

> Example: the first element under each Service Center tab (e.g., "Select question type" under "Get Answers") is identified as an ordered list of one item. `<ol class="breadcrumb clean"><li class="active"><i aria-hidden="true" class="fa fa-th"></i>` 

> Select question type`</li></ol>`. 

> Recommend changing these elements to paragraphs.

**Comment by jlyon** [comment]
We rely on Bootstrap as much as possible. In this case we are using the breadcrumb component which uses this <ol> markup https://getbootstrap.com/docs/3.3/components/#breadcrumbs.  We could add `aria-label="breadcrumb"` and `aria-current="page"` attributes to this markup, but I don't think we want to fully implement their suggestion to replace this with <p>s. @kevindherman
