### ISSUE TITLE
Frontend style tweaks

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#19]
- [x] papragraphs need margin
- [x] Add min-height to content
- [x] Favicon (edit in Appearance?)
- [x] Change default topnav icon to use //my.proudcity.com/images/IconWhite.png  (https)
- [x] Change topnav icon to West Carrollton (can this be done in the Appearance section?)
- [x] Whitespace between topnav and header image, map and footer (padding is getting added on element -- is this pagebuilder?)
- [x] Make aside width 25%
- [x] Hide aside with menu icon on mobile (see http://pattern.getproudcity.com/?v=&page=agency-content)
- [x] Fix padding on icon buttons so they look like http://demo.proudcity.com/get/Oregon/Corvallis/answers, break to two columns on mobile 
- [x] fat topnav that shrinks onscroll
- [x] Make menu css tweaks only apply to sidebars (not 311 box) @jlyon
- [x] Add breakpoints for the hero headers for 1280px desktops, landscape tablets (laptop screen) 
- [x] Add hero header style that is 1/2 height, make this default for new sections
- [x] rm padding/margin below .page-footer
- [x] clean up agency offcanvas interaction (bg color or...)
- [x] need to add padding to map close button - can't close map w logged in after activating it
- [x] footer h3 color
- [x] make header not as tall (can't see buttons w demo bar > 1200px wide)
- [x] Horizontal scroll
- [x] Calendar stuff w style tweaks https://west-carrollton-oh.proudcity.com/residents/#/city/answers
- [x] Rm min-width on .card (help metabox on dashboard)
- [x] Incr site name font size
- [x] Make active topnav style better (5px margin top, highlight color)
- [x] reduce the padding on cards https://west-carrollton-oh.proudcity.com/govenment/

**Comment by jlyon** [comment]
- [ ] Make a Payment breaks in a weird way on tablet (iPad screenshot)
![screenshot from 2016-01-14 17 13 22](https://cloud.githubusercontent.com/assets/550909/12342729/25e73020-bae2-11e5-9207-409b2b83943c.png)

**Comment by aschmoe** [comment]
> "Favicon (edit in Appearance?)"

Looks like we're hiding the appearance options completely.  I can add these options in the theme if we get a path to it.... where are you modding all that @jylon?   

Currently possible under customize->site identity

> Change topnav icon to West Carrollton 
> (can this be done in the Appearance section?)

Ditto to above, will start adding the settings

> Fix padding on icon buttons so they look like 
> http://demo.proudcity.com/get/Oregon/Corvallis/answers, 
> break to two columns on mobile

Fixed padding, I think its safer with some of the larger titles if we leave 1 col for mobile

**Comment by jlyon** [comment]
> Looks like we're hiding the appearance options completely. I can add these options in the theme if we get a path to it.... where are you modding all that @jylon?

I don't think I'm hiding anything in the settings. I added the color settings in functions.php in the theme, i think we'd want to add them there. I think the topnav icon could happen in the site icon field in the customizer (http://localhost:8080/wp-admin/customize.php?return=%2Fwp-admin%2Fthemes.php).

**Comment by jlyon** [comment]
Looks like changing the icon (post above) changes the favicon, so i guess we just need to add another field like that maybe..
