### ISSUE TITLE
Accessibility: Carousel pause/play

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1903]
> There is no way to pause, stop, or hide the carousel. 
> Recommend adding an accessible Pause/Play button. See W3C’s Carousel Concepts for help.

## Comments

@kevindherman I'd recommend they not use the carousel if they're adamant about being 100% inclusive on all of the sections of the page. Pause/play is a must include, but in general carousels aren't great for accessibility. 

Here's a great post related to this: https://thegood.com/insights/ecommerce-image-carousels/

**Comment by lukefretwell** [comment]
@aschmoe would be great to take care of #1725 if it's not too much extra work.

**Comment by aschmoe** [comment]
@kevindherman @lukefretwell  bootstrap doesn't seem to have a pause button built in.  I was able to add the slide controls but not sure that gets to the core of the request.

![Uploading Screen Shot 2021-12-02 at 8.59.06 PM.png…]()

**Comment by kevindherman** [comment]
@aschmoe that definitely helps. Please deploy when you get a chance.
