### ISSUE TITLE
Service center tabbing

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1906]
> Some links in Service Center tab panels remain in the tab order even when they are no longer visible. This occurs with both "Report an Issue" as well as “Get Answers”. Example: if a keyboard-only user selects "Unsafe road conditions," they then must tab through hidden "Parking related," "Illegal dumping", "Flooding," etc. links before reaching the unsafe road conditions form fields. Recommend removing non-visible links from the tab order.

**Comment by aschmoe** [comment]
@kevindherman @lukefretwell this is deployed
