### ISSUE TITLE
Auth0 updates

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1917]
**What feature would you like to improve**

Auth0

- [ ] Email messages
- [ ] Web interface (sign-in/out) (also: https://github.com/proudcity/wp-proudcity/issues/1910)
- [ ] Remove login with Google?
- [ ] Remove Sign-up functionality

**Describe the solution you'd like**

It would be helpful to talk through this with @jlyon or @aschmoe just to understand what's available for us to modify and where that can be done.

**Additional context**

This is one of the screens, but there are a few others that would be great to unify the design to match the brand more.

![Screen_Shot_2021-11-04_at_5 09 42_PM](https://user-images.githubusercontent.com/1569463/140826537-9706ceda-78c1-4f7b-8fee-9caec820faa1.png)

**Comment by curtismchale** [comment]
This duplicates many other specific issues that are linked above already.
