### ISSUE TITLE
Empty bullets showing below logo/navbar (proudcity.com)

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1918]
**Describe the bug**

The empty bullets issue we fixed last week is still showing on proudcity.com (in normal and incognito). I cleared/purged the caches via admin and they're still showing up.

NOTE: I don't see them when I'm logged into MyProudCity.

**To Reproduce**
1. Go to https://proudcity.com
2. Look below logo in navbar.

**Expected behavior**

To not see empty bullets.

**Screenshots**

![Screenshot 2021-11-08 at 16-20-35 ProudCity - ProudCity](https://user-images.githubusercontent.com/1569463/140839428-710c3407-53a2-46a0-9c33-8d85976cc064.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Firefox

**Comment by jlyon** [comment]
The issue on www.proudcity.com appeared to be the CloudFlare cache.  I purged that and the three dots are now gone @kevindherman @lukefretwell

**Comment by lukefretwell** [comment]
@kevindherman do you still see this? I do on Chrome and Firefox even after clearing browser cache.

**Comment by kevindherman** [comment]
No bullets in firefox but I still see them in Chrome after clearing my cache and viewing in incognito. @lukefretwell @jlyon

**Comment by lukefretwell** [comment]
I'm still seeing them in Firefox even with a new computer and first time visiting proudcity.com.
