### ISSUE TITLE
New payments not saving payment information

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#192]
When creating a new payment it is not saving the payment information: URL or icon.

When you publish that option it is not showing on front end and when you click edit to add it again it is also missing from backend.

**Comment by kevindherman** [comment]
![screenshot 2016-03-01 13 37 40](https://cloud.githubusercontent.com/assets/6032426/13437637/497a6372-dfb3-11e5-9019-00c678c251e2.png)

![screenshot 2016-03-01 13 36 27](https://cloud.githubusercontent.com/assets/6032426/13437635/496ed976-dfb3-11e5-93e0-d4c263ca24c5.png)

![screenshot 2016-03-01 13 37 57](https://cloud.githubusercontent.com/assets/6032426/13437636/496fa0fe-dfb3-11e5-819c-61201ccb296d.png)

**Comment by jlyon** [comment]
ahh, ok ill look at this

**Comment by jlyon** [comment]
I applied this as a hotfix, updated the link to http://www.egovlink.com/westcarrollton/payment.asp?paymenttype=536 and set the icon as the building. @kevindherman

**Comment by kevindherman** [comment]
Thank you @jlyon. I'll let Erika know.
