### ISSUE TITLE
Clean up GitHub operations

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1921]
- [x] add to repository so issue templates can be used
- [x] does the ready list have automations or considerations as part of releases? 
- [x] are there changes that could be made to help the development workflow in getting releases out? 
- [x] can we delete UX hitlist?
- [x] delete longterm in progresss?
- [x] delete icebox?
- [x] Release issue template?
- [x] Set up issue templates https://github.com/proudcity/wp-proudcity/issues/templates/edit
- [x] re-organize to do list
- [x] re-organize doing list
- [x] Delete old project board: https://github.com/orgs/proudcity/projects/1
- [x] Schedule recurring backlog/prioritization review meeting

**Comment by kevindherman** [comment]
@lukefretwell I've organized the to-do and doing list to transition off of the old project so I don't need that view anymore for tracking issues. If reviewing third party apps isn't connected to the project I'm fine with deleting it.
