### ISSUE TITLE
Close old/irrelevant issues

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1922]
@lukefretwell and I went through and cleaned up a lot of the backlog. @jlyon @aschmoe can you take a pass on the backlog? We've been able to cut quite a bit with limited knowledge so I think you guys could really help get a lot of stuff closed.

**Comment by kevindherman** [comment]
@lukefretwell would you like the honors of a bulk close of anything older than a year, excluding items with customer label?

**Comment by lukefretwell** [comment]
@kevindherman yep 🥳

**Comment by lukefretwell** [comment]
@jlyon @kevindherman @curtismchale @aschmoe I closed most of these out. There are a few that are a11y related as well as still relevant.

Started doing it in a dumdum way so some of them don't have the don't fix label. 🤷
