### ISSUE TITLE
form submissions appearing as draft posts

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1928]
**Source**
Marin DPW

**Describe the bug**
There are about 15 draft posts from the admin user all assigned to the news post category "Accessibility Guidance Bulletins" since the DPW site launched that all appear to be different form submissions. However, it is not clear why they are displaying as draft posts to this specific category, by the admin and where they are being submitted from. 

**To Reproduce**
1. posts
2. drafts
3. view all the untitled posts by admin since 11/1

**Screenshots**

![image (14)](https://user-images.githubusercontent.com/6032426/143141869-afae26fa-26da-42fe-9ef0-c2b09ed35ee0.png)
![weird_drafts_appearing](https://user-images.githubusercontent.com/6032426/143141873-5bed7f12-7c7a-489b-bc4a-d50d8f11b53e.jpeg)

**Additional context**
I've never seen this before. It doesn't appear to be spam but form entries that are turning into draft posts by admin. 

cc @jlyon @aschmoe

**Comment by lukefretwell** [comment]
@jlyon @aschmoe we figured it out!

They were doing this:

![Screenshot 2021-12-02 at 13-29-43 Forms ‹ ProudCity — WordPress](https://user-images.githubusercontent.com/1569463/144506256-b2b21d68-477a-41ff-8a25-94da5542e838.png)
