### ISSUE TITLE
Add link to user profile for admin to edit

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1941]
**Source**

In the dashboard, the 'Users' tab.

**Is your feature request related to a problem? Please describe.**

No.

**What feature would you like to improve**

Admin link to edit user profile.

**Describe the solution you'd like**

It would be great to have a link to edit the user profile from the 'Users' dashboard page. Currently, you have to go to the admin leftnav and it would be great to make it easier to get to.

**Additional context**

None.

**Comment by kevindherman** [comment]
@lukefretwell is this for ProudCity admins to edit the WP profile or for ProudCity customer admins to edit their users? 

There are two separate but related user administrations: my.proudcity.com which customers have access to and then an additional layer which is WP users which only PC admin can access. This sounds like you're talking about WP access but we've had discussions about customer user management which is a different experience. Could you clarify which one you're speaking to here?
