### ISSUE TITLE
Editing /wp-admin/widgets.php yields error

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1943]
**Source**
This appears to be platform wide but I spotted it when working on Santa Ana. 

**Describe the bug**
It appears that a WP update has changed the widget system to a new version of WP which is yielding errors. 

**To Reproduce**
Go to https://santa-ana-ca.proudcity.com/wp-admin/widgets.php
And you will see several errors:
![Screen Shot 2022-01-07 at 12 11 30 PM](https://user-images.githubusercontent.com/6032426/148581050-ee392c4f-1c5e-456d-b69a-f7bcda21c669.png)

I went to remove the 'department contact info' widget from the agency sidebar for pages with the goal of department/agency subpages to only have the menu + breadcrumbing and not all the contact information. When going to remove those widgets from the page template, I just get a spinning wheel and the error messages mentioned above. Here's the spinning wheel view:

![Screen Shot 2022-01-07 at 12 17 12 PM](https://user-images.githubusercontent.com/6032426/148581472-0bddb680-d850-4622-b180-2a90132fc24a.png)

**Expected behavior**
I would default to the previous widget management or figure out why widget management isn't working at all so we can customize content templates. If this is a bigger item, it would be great to just get the department contact widget removed from the agency sidebar.

**Comment by jlyon** [comment]
Looks like the solution here is to add this plugin: https://wordpress.org/plugins/classic-widgets/. Preparing a hotfix now that I will push to santa-ana-ca.proudcity.com today @kevindherman

**Comment by kevindherman** [comment]
@jlyon awesome. Thank you.

**Comment by lukefretwell** [comment]
@jlyon could you also push to help.proudcity.com?

**Comment by jlyon** [comment]
@kevindherman @lukefretwell I deployed to https://santa-ana-ca.proudcity.com/wp-admin/widgets.php and https://help.proudcity.com/wp-admin/widgets.php. I'll deploy it platform-wide later today (after the meat of the business day).

**Comment by kevindherman** [comment]
@jlyon thanks, this allowed me to fix my Santa Ana issue.

**Comment by lukefretwell** [comment]
Yep, worked for me on help. Thank you!
