### ISSUE TITLE
Add Nextdoor, Snapchat, and TikTok to department social media widget options

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1945]
**Source**
Santa Ana

**What feature would you like to improve**
Add fields/options for Nextdoor, Snapchat, and TikTok for the Department social media widget. This information would be added from department content type > social media fields.

**Comment by lukefretwell** [comment]
Looks like NextDoor still isn't part of the Font Awesome icon list, but we could just use the home icon for that.

**Comment by kevindherman** [comment]
@curtismchale looks good to me!

**Comment by curtismchale** [comment]
@kevindherman okay it's integrated and should roll out with the next release.

**Comment by kevindherman** [comment]
@curtismchale awesome.
