### ISSUE TITLE
Custom fields should be hidden 

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1948]
**Source**
Platformwide

**Describe the bug**
If you edit content (page, event, contact, department, etc.) at the bottom of the edit screen is a section called custom fields that previously was hidden but is not in view of customers. 

**To Reproduce**
1. Go to any page or content type when logged in
2. Edit [type of content]
3. Scroll down to bottom of the edit screen
4. See custom fields

**Expected behavior**
Custom fields should be hidden on all content types. 

**Screenshots**
<img width="929" alt="Screen Shot 2022-01-18 at 2 36 57 PM" src="https://user-images.githubusercontent.com/6032426/150006991-1912ee9c-f39b-43f7-88a1-4e5367410afa.png">

**Comment by lukefretwell** [comment]
Related custom fields issue that may be addressed with this one: https://github.com/proudcity/wp-proudcity/issues/1364

**Comment by curtismchale** [comment]
Resolved with: https://github.com/proudcity/wp-proud-core/pull/11 once it's merged.

**Comment by kevindherman** [comment]
Hit close by accident and moved it back to QA. @curtismchale please move to the right list if QA is incorrect. Sorry about that.

**Comment by curtismchale** [comment]
@kevindherman this is deployed if I understand @aschmoe correctly with this: https://github.com/proudcity/wp-proudcity/commit/f40edb5b6e3797dc07c84e2d775408323d86d221

I'll need to get together and make sure I understand when to hotfix things and how the process should be done.

**Comment by kevindherman** [comment]
@curtismchale it's a good question that I'll post to slack because I can speak to customer management side but don't have all the information for when it's worthwhile from a deployment perspective. Lets get some more insights and discuss on Friday to see how we would like to consider it moving forward.

**Comment by aschmoe** [comment]
@kevindherman @curtismchale this is now deployed to beta + marin-county-ca.proudcity + https://publicworks.marincounty.org/
