### ISSUE TITLE
Add address option to contact content type

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1949]
**Source**
Williams County and Holyoke, MA

**Is your feature request related to a problem? Please describe.**
Some contacts could use a physical address like elected officials or if contacts are being used for agencies/divisions. 

**Describe the solution you'd like**
Add an address field to the content type contact to display under contact details. 

**Additional context**

- Here's the widget being used for contacts: https://wordpress.org/plugins/simple-staff-list/
- @lukefretwell  pinged the dev in the WP Slack asking if they would consider adding address as an enhancement.

**Comment by lukefretwell** [comment]
@kevindherman @jlyon @aschmoe I pinged Brett (the maintainer) and here's his response:

```
Adding custom fields isn't quite as easy as I'd like it to be yet (I've got almost zero time to add features to this plugin anymore), but it is possible. You'll need to add a custom meta box to the staff-member post type with add_meta_box(). You'll use that to add your fields (you'll also need to hook into save_post to actually save the meta fields to the database). Check out admin/class-simple-staff-list-admin.php for how I'm adding/saving the existing fields. Then, to display the fields, I think you can use the sslp_single_loop_markup_filter filter to do a search/replace for a custom "tag" that you're going to use to display your custom data. So, for example, if you want the custom address field in the staff loop template, you could add a [staff-address] tag. Then in that filter, you'd search/replace that tag with the formatted data. For the single staff member pages (using templates), you'd hook into where ever you want the address displayed and display the data. (Sorry for the long-winded answer :grin:)

> Is that something you'd consider incorporating as an enhancement

Short answer is "yes." Slightly longer answer is that it's been something I've wanted to do for a while but have never gotten around to it.
```

**Comment by kevindherman** [comment]
@lukefretwell is this something we should consider for the WP milestone even though it's not technical a bug?

**Comment by lukefretwell** [comment]
@kevindherman I'd leave this out for now. Looks like there are a number of Williams requests that we might want to cluster into a milestone to show LH we've knocked them all out.

**Comment by kevindherman** [comment]
@lukefretwell the address item has come up with two other customers recently which is why I was bumping it up. Does that change things for you?

**Comment by kevindherman** [comment]
Duplicate of #1968
