### ISSUE TITLE
Staging site

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1950]
**Source**
San Rafael and enterprise level customers. 

**Is your feature request related to a problem? Please describe.**
Ability to test and push large menu changes. The ability to test and push page designs. 

**Describe the solution you'd like**
Consider: https://wpstagecoach.com/

**Comment by jlyon** [comment]
We have the infrastructure to easily set up a staging server for them to play around on, but would probably not use https://wpstagecoach.com/, but rather our own tooling.  Let me know if they would like us to set up a clone of their site.

**Comment by kevindherman** [comment]
@jlyon would that have the abilities to push updates from the clone to the live site, including menu changes?

If yes, I think it's worth setting up for @lukefretwell and I to tinker with before sharing with them. If you could also set this up for the Marin test site that was just created that would be helpful to test ahead of their demo too. 

@lukefretwell what do you think?

**Comment by kevindherman** [comment]
@jlyon it would be helpful to also have this on the Marin County test instance, perhaps as a more immediate item if possible.
