### ISSUE TITLE
password protect with landing page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1956]
@jlyon could you make [MarinRecovers](https://marinrecovers.com/) password protected again with this landing page center justified:

[LOGO]

The Marin Recovers website is currently dormant.

This site will be activated in the event of a multi-jurisdictional disaster or emergency with up-to-date information from local governments, public safety agencies, and public information officers about response and recovery efforts.  If you are seeking information about a specific incident, please contact your local jurisdiction for information. You can also monitor local news for alerts and notifications and follow directions of local emergency officials.

If you are seeking COVID-19 pandemic response and recovery information, please visit Coronavirus.MarinHHS.org or any of the following shortcuts:

[Local Data](https://coronavirus.marinhhs.org/surveillance) | [Health Orders](https://coronavirus.marinhhs.org/health-orders)| [Business Resources](https://coronavirus.marinhhs.org/Business) | [Status Updates](https://coronavirus.marinhhs.org/Business)

**Comment by jlyon** [comment]
This can be edited on https://marinrecovers.com/wp-admin/admin.php?page=seedprod_lite#/
