### ISSUE TITLE
Remove 'Sign up' option from MyProudCity

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1960]
**Source**
Customer support

**Is your feature request related to a problem? Please describe.**

New users are going to MyProudCity and signing up for their accounts. Because this function doesn't gel with account creation, we should disable the 'Sign up' functionality.

**What feature would you like to improve**

MyProudCity login/sign-up

**Describe the solution you'd like**

Disable 'Sign-up' functionality.

**Additional context**

![Screenshot 2022-02-07 at 14-44-12 Sign In with Auth0](https://user-images.githubusercontent.com/1569463/152884862-8a6d7fbf-1608-4577-8f8c-6109c9b927df.png)

**Comment by curtismchale** [comment]
See these forum posts:

- https://community.auth0.com/t/dont-show-sign-up-option-on-new-universal-login/52568/3
- https://community.auth0.com/t/how-do-i-disable-new-user-sign-ups/45177

**Comment by lukefretwell** [comment]
Closing this. Thank you @jlyon! @curtismchale @lukefretwell
