### ISSUE TITLE
Improve breadcrumb accessibility

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1962]
**Source**
Platformwide

**Is your feature request related to a problem? Please describe.**
The breadcrumb has a h2 to usually links back to the department that is extraneous and breaks the content structure. Removing the top item and just having breadcrumbs at the top would resolve this. 

"City Council" h2 at the top of the breadcrumb:

<img width="948" alt="Screen Shot 2022-02-15 at 1 49 19 PM" src="https://user-images.githubusercontent.com/6032426/154129573-fd821c7d-69d3-4761-9aea-4a63ce18f47a.png">

**What feature would you like to improve**
Breadcrumb

**Describe the solution you'd like**

Remove this code 
```
<div class="page-header">
<a id="offcanvas-toggle" href="#" class="btn btn-primary visible-xs pull-right"><i class="fa fa-bars"></i></a><h2><a href="https://www.montgomeryohio.gov/departments/administration/" title="Administration">Administration</a></h2></div>
```

**Comment by curtismchale** [comment]
@kevindherman removing this code would remove that heading from **all** pages that have it. Is there any scenario in which you want that heading to be on a Page?

This is only for WordPress pages, other custom post types will **not** be affected.

**Comment by kevindherman** [comment]
@curtismchale I might not fully understand the question but I'll do my best to provide additional context to limit unintended consequences.

A subpage within a department menu structure is the most common use:
https://demo.proudcity.com/administration-resources/
<img width="1169" alt="Screen Shot 2022-02-23 at 4 38 34 PM" src="https://user-images.githubusercontent.com/6032426/155412975-11576d18-da53-48d9-816f-dda2579e3f25.png">

Another use which is more custom using the breadcrumb widget rather than a default template might be the other use you're referring to. Here's an example of the breadcrumb widget being dropped into a custom page that's part of the primary navigation: https://publicworks.marincounty.org/environmental/
<img width="1363" alt="Screen Shot 2022-02-23 at 4 34 42 PM" src="https://user-images.githubusercontent.com/6032426/155412522-8f3d3ca3-3d42-49f9-80e6-ced3cfe9724d.png">

widgets:
<img width="889" alt="Screen Shot 2022-02-23 at 4 34 50 PM" src="https://user-images.githubusercontent.com/6032426/155412572-fea649de-9897-4c13-8f41-0180024a2aa8.png">


breadcrumb widget: 
<img width="1369" alt="Screen Shot 2022-02-23 at 4 34 55 PM" src="https://user-images.githubusercontent.com/6032426/155412601-bc15740f-f426-4ca8-8ef1-c50b2f062c51.png">


This option overrides the header so that the side menu is removed from the secondary page template (like the department example) and a full width hero unit can be added to the top of the page. 

When this isn't done, the standard secondary page displays with the left side menu and breadcrumb at the top: https://publicworks.marincounty.org/divisions/
<img width="1279" alt="Screen Shot 2022-02-23 at 4 34 34 PM" src="https://user-images.githubusercontent.com/6032426/155412662-00bc716f-0ef7-4e13-8213-5600f1aa00df.png">

This could be unrelated but being thorough, contact and document content types use a heading.
Example contact: https://demo.proudcity.com/contacts/jane-doe/
<img width="1184" alt="Screen Shot 2022-02-23 at 4 40 22 PM" src="https://user-images.githubusercontent.com/6032426/155413439-98715417-2c13-4458-b1e0-a72c7c72bbfc.png">

Example document: https://demo.proudcity.com/documents/example-pdf/
<img width="1331" alt="Screen Shot 2022-02-23 at 4 42 36 PM" src="https://user-images.githubusercontent.com/6032426/155413542-da318e42-e877-48db-95bf-7a2271da53f9.png">

**Comment by kevindherman** [comment]
@curtismchale removing that code snippet doesn't need to be the solution. @lukefretwell flagged that snippet when we were talking about the issue to help describe what aspect we would like to remove so if there's a better way to achieve the goal of not having that header, that's totally cool.

**Comment by curtismchale** [comment]
@kevindherman this is ready for deploy with the next releas.

**Comment by kevindherman** [comment]
@curtismchale wow, that's awesome.

Could you take a quick screenshot of a department subpage and/or the environmental example from above so I can get a sneak peek?
