### ISSUE TITLE
Contact content type email field to allow for link

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1968]
**Source**
Santa Ana

**Is your feature request related to a problem? Please describe.**
Department contact fields allow you to insert a link in the email field to redirect to a page/webform. This should also be allowed for email fields in contact content types to hide emails when needed. 

**What feature would you like to improve**
Contact content type 

**Describe the solution you'd like**
Contact content type email field to allow for link to page/webform to hide emails. Department contact field currently does this, the contact content type should replicate the strategy. 

**Additional context**
Department list with contact instead of email because it's a link: https://publicworks.marincounty.org/contact/
<img width="1100" alt="Screen Shot 2022-02-16 at 1 12 16 PM" src="https://user-images.githubusercontent.com/6032426/154329205-9770b657-9fe2-4c32-8c7c-08d43c9aa194.png">

Displays "contact us" on the department: https://publicworks.marincounty.org/agencies/accounting/
<img width="796" alt="Screen Shot 2022-02-16 at 1 12 29 PM" src="https://user-images.githubusercontent.com/6032426/154329310-98a0ab00-4375-4220-8276-ad3dc52ff2e0.png">

Fields when editing department to be replicated on a contact content type:
<img width="595" alt="Screen Shot 2022-02-16 at 1 12 48 PM" src="https://user-images.githubusercontent.com/6032426/154329468-fb0fbf12-aa02-4cef-9a53-de07854d7067.png">

**Comment by curtismchale** [comment]
@kevindherman we can do this, but I have a question out to the developer. I don't want to "hack" the plugin so that we have to maintain our own copy of it. 

You can see the question here: https://wordpress.org/support/topic/conditional-contact-fields/

The plugin developer does seem to be fairly responsive so I'll give it a day or so to hear back from them first.

**Comment by lukefretwell** [comment]
@curtismchale this might be related: https://github.com/proudcity/wp-proudcity/issues/1949

See comments from the maintainer (I pinged him in WP Slack community)

@kevindherman we should combine any contact field issues as they're all probably related.

**Comment by kevindherman** [comment]
@lukefretwell Thanks for catching that. 

@curtismchale would you prefer for issues like this and #1949 to be combined or separate? 

With the email/contact being used in all list displays I thought it was different but I can see how if this was part of the other issue it would've connected you to the plugin developer faster. More than happy to organize whichever way makes sense to you.

**Comment by curtismchale** [comment]
@kevindherman Yes they are related, or at least in the same discussion with the developer. We could certainly devote my time to helping him roll out those extra features on his plugin so we can use them?

**Comment by kevindherman** [comment]
Email, address and website would be nice.

If you don't think it's too much time I think it's worthwhile. It's come up in feedback from 4-5 customers in the past three months. 

@lukefretwell thoughts?

**Comment by lukefretwell** [comment]
@curtismchale @kevindherman definitely. Always game for supporting plugin updates! We should probably document all the fields we want to add in the [first comment](https://github.com/proudcity/wp-proudcity/issues/1968#issue-1140390865).

I think LinkedIn would be a nice addition.

**Comment by curtismchale** [comment]
@kevindherman @lukefretwell 

So the fields we want to add are:

- [ ] email address (exsists) 
- [ ] URL 
- [ ] From #1949 we want an address as an option
- [ ] Linkedin

We can already customize the frontend templates so just having the fields in the admin means we can make them look as we want (conditional contact fields between email/URL/Address)

Is there any other fields we want?

**Comment by kevindherman** [comment]
@curtismchale @lukefretwell  I'd distinguish contact URL (for replacing email) and website URL as an additional option. 

That would be it for additional fields

**Comment by curtismchale** [comment]
@kevindherman you mean that there is only 1 way to contact and we make it either one of those things or that we display any of the fields that are added as options in their listings?

I'd vote that we just show any of the fields that have information in them. That would let customers show as many contact options as they want.

**Comment by curtismchale** [comment]
@kevindherman I've reached out to Brett in the WP Slack group about adding the features he said he was interested in per @lukefretwell in #1949 .

Link to conversation for my reference: https://wordpress.slack.com/archives/D036JJDL77B/p1646765294678019

**Comment by curtismchale** [comment]
Added the two actions that were verbally approved by Brett in Slack.

https://github.com/brettshumaker/Staff-List-Plugin/pull/111

I'll add them manually to our version of the plugin and then we can build out our feature while we wait for the new 2.2.2 release with any other changes Brett ends up adding to the plugin before release.

**Comment by curtismchale** [comment]
@kevindherman this is all ready, except I'll have to spend more time to finish off the CSS to align the text field. See the screenshot to know what it currently looks like in the WordPress Admin.

<img width="1374" alt="CleanShot 2022-03-15 at 15 31 12@2x" src="https://user-images.githubusercontent.com/74561/158483194-a9777115-8b6f-41ad-8289-fc66d6bbb004.png">

If we're good with how it looks now, then I can push it all and we can have this ready for the next release.

You can see what the frontend looks like in the screenshot below.

<img width="505" alt="CleanShot 2022-03-15 at 15 33 12@2x" src="https://user-images.githubusercontent.com/74561/158483339-3c3293f4-a222-4ddf-97de-1c14c149182d.png">

**Comment by curtismchale** [comment]
Revamped and resubmitted the PR for the fields and CSS changes.

https://github.com/brettshumaker/Staff-List-Plugin/pull/112

**Comment by lukefretwell** [comment]
@curtismchale comments:

* Would use either URL or link to be consistent (I suggest 'link').
* The Twitter field says username but looks like you're asking for the link.

**Comment by kevindherman** [comment]
@curtismchale @lukefretwell how would contact link work if they want to display a website? Sometimes this is an internal contact link and other times it would go to an outside website altogether to show their organization. 

Would a second contact link for "website" do the trick?

**Comment by kevindherman** [comment]
@curtismchale yeah, that makes sense. I'm thinking of a specific use case and contact or contact link would work.

**Comment by curtismchale** [comment]
@kevindherman so is this ready to go from your end?

**Comment by kevindherman** [comment]
@curtismchale good for me.
