### ISSUE TITLE
Table builder in visual editor is gone

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1972]
**Source**
Platform 

**Describe the bug**
The table builder in the visual editor is no longer an option platform wide:
<img width="884" alt="Screen Shot 2022-02-17 at 10 34 04 AM" src="https://user-images.githubusercontent.com/6032426/154515498-edbfa0a4-eb03-4ab5-88cc-06290f8c2534.png">

This appears to have happened after the release last night. I'm curious to if it has something to do with the text editor default to resolve the save your work message.

**Comment by curtismchale** [comment]
@jlyon I wrote a script to activate this for `1.120.1` release here: https://github.com/proudcity/wp-proudcity/commit/11dad4a5e4bfda3ecf9887330c8f5bad42c2069f

**Comment by lukefretwell** [comment]
FYI we have a community member that reported this bug. Possible to push as a hot fix? @curtismchale @jlyon @aschmoe

**Comment by jlyon** [comment]
@lukefretwell @kevindherman I believe this should have been pushed with Hotfix 1.120.1 last Thurs. What are some sites that are not seeing this button?

**Comment by kevindherman** [comment]
@jlyon San Rafael, Santa Ana, Streetsboro. I'll keep looking but each time I check I don't see the tool.

**Comment by lukefretwell** [comment]
@jlyon also don't see it on proudcity.com, help.proudcity.com or proudlyservingbook.com.

**Comment by kevindherman** [comment]
I added the plugin to San Rafael and Santa Ana manually but the rest of the platform still needs it.

**Comment by curtismchale** [comment]
@kevindherman according to @jlyon here (https://proudcity.slack.com/archives/C0AH683JQ/p1645635012753099?thread_ts=1645566642.120059&cid=C0AH683JQ) this has been rolled out. You confirmed it there so I'll close this.

**Comment by kevindherman** [comment]
@curtismchale excellent.
