### ISSUE TITLE
Wordpress update alert shows for customers

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1973]
**Source**
Williams County

**Describe the bug**
Customer was editing a page and then received this message:
![wordpressalert](https://user-images.githubusercontent.com/6032426/154516471-bf79369d-ebe7-4c68-ae80-6967633c8cd5.png)

**To Reproduce**
I have not reproduced yet but here are the steps from the customer
I’m logged into Proud City. Went to https://www.williamsnd.com/blacktail-dam/ (https://www.williamsnd.com/blacktail-dam/) and then clicked “Edit Page” in the blue admin toolbar. Then the alert appears.

**Expected behavior**
Wordpress updates should be hidden from customers.

**Comment by jlyon** [comment]
@kevindherman this should now be resolved.
