### ISSUE TITLE
New news post not showing on news feeds?

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1976]
**Source**

LF

**Describe the bug**

New news post aren't showing in the news list feed. The post is published, but it's not showing in the feed. @curtismchale and I both replicated this issue.

Example:

* Post: https://proudcity.com/proudcity-1-120-release/
* News list: https://proudcity.com/releases

**To Reproduce**

1. Go to https://proudcity.com/releases
2. Latest post isn't displayed

**Comment by aschmoe** [comment]
@lukefretwell seeing that on there for me.  Probably some sort of caching issue

<img width="2721" alt="Screen Shot 2022-02-18 at 1 57 17 PM" src="https://user-images.githubusercontent.com/1634686/154766777-709685d7-b23c-4c36-a120-b92e74866999.png">

**Comment by curtismchale** [comment]
@lukefretwell is this an actual issue or was it a caching issue and we can close this issue?

**Comment by lukefretwell** [comment]
@curtismchale I'm going to close and keep note of it. Seems like it's a proudcity.com issue.
