### ISSUE TITLE
Hide WordPress and plugin messages messages from admins

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1979]
**Source**

LF

**Is your feature request related to a problem? Please describe.**

No

**What feature would you like to improve**

The WordPress and plugin messages for end users seems distracting and potentially confusing. 

**Describe the solution you'd like**

Would be great if we could only show these for ProudCity super admins.

**Additional context**

![Screenshot 2022-02-18 at 12-42-00 Dashboard ‹ Proudly Serving — WordPress](https://user-images.githubusercontent.com/1569463/155420845-0e05d59b-697c-479a-bbae-2ece44e1174f.png)
![Screenshot 2022-02-22 at 16-53-42 Marketplace ‹ City of Santa Ana — WordPress](https://user-images.githubusercontent.com/1569463/155420851-1d3272d1-89ef-4ee0-9e2b-1dfc7d795c04.png)

**Comment by curtismchale** [comment]
@lukefretwell do we ever actually give users the "Admin" role or are they always editor, author...something else?

**Comment by kevindherman** [comment]
Consider removing for everyone accept for WP-admins or even just limit to local develop servers.

**Comment by curtismchale** [comment]
@lukefretwell @kevindherman 

I've removed the default notifications for WordPress and the plugin notices I found. By default it's set to be removed on `production` sites. This is the default setting so we can set our Beta site to be `staging` and then you'd see notices there.

I do anticipate finding other notices and needing to circle back on this. I found a couple plugins that were being sneaky with their notices and needed to find where they loaded them so I could remove them.

**Comment by lukefretwell** [comment]
@curtismchale thank you!

**Comment by lukefretwell** [comment]
@curtismchale you were right, there's another one. 😄 

![Screenshot 2022-03-11 at 15-39-45 Recurring Events ‹ Your City — WordPress](https://user-images.githubusercontent.com/1569463/157990215-8ac06566-0615-4411-baed-0f6937a900dc.png)

**Comment by lukefretwell** [comment]
@curtismchale it's on both proudcity.com and help.proudcity.com.

**Comment by lukefretwell** [comment]
Per conversation closing this and creating new ticket for events message. https://github.com/proudcity/wp-proudcity/issues/2022
