### ISSUE TITLE
Gravity Forms Constant Contact Add-On failure

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1980]
**Source**
Sonoma and Montclair
cityofmontclair.org
https://www.sonomacity.org/

**Describe the bug**

Gravity Forms Constant Contact Add-On plugin won't authenticate and have unhooked the API. 

**To Reproduce**

When you go through the steps to authenticate a new API you get a fatal error about the client id:
<img width="1277" alt="Screen Shot 2022-02-24 at 3 05 42 PM" src="https://user-images.githubusercontent.com/6032426/155599213-d707965a-1633-4bfb-a1d2-d68b29a8abf5.png">

When I go to the plug settings I get this message which seems related:
Fixed a PHP fatal error which can occur during form submission if the contact exists request fails.
<img width="1162" alt="Screen Shot 2022-02-24 at 3 00 24 PM" src="https://user-images.githubusercontent.com/6032426/155599373-404405ec-b10c-4d14-9587-7f9256054341.png">

**Expected behavior**
After submitting API key and secret it should authenticate between gravity forms and constant contact.

**Comment by curtismchale** [comment]
@kevindherman it wouldn't suprise me if we need to move to the new Gravity Forms to get this working again. I don't know that, but there is no good reason it should break unless something changed.

The ticket for new gravity forms is: https://github.com/proudcity/wp-proudcity/issues/1859

**Comment by kevindherman** [comment]
@jlyon got this working on Sonoma using this article: https://developer.constantcontact.com/api_guide/auth_update_apps.html @curtismchale
