### ISSUE TITLE
Update to Font Awesome 6

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#1993]
**Source**

SA

**Is your feature request related to a problem? Please describe.**

No

**What feature would you like to improve**

A new version of Font Awesome has been released. Would be great to include the additional fonts.

**Describe the solution you'd like**

Upgrade to v6.

**Additional context**

* https://fontawesome.com/download
* https://wordpress.org/plugins/font-awesome/

**Comment by lukefretwell** [comment]
@kevindherman @curtismchale I sent an email to Font Awesome.

**Comment by lukefretwell** [comment]
@curtismchale @kevindherman looks like we could add this as a plugin in our marketplace and let folks activate it. Then they could sign up with FA directly and input their info.

Seems like that would be the easiest thing to do.

https://wordpress.org/plugins/font-awesome/#installation

```

Access Font Awesome Plugin Settings

Once you activate the Font Awesome plugin, you will see Font Awesome in the Settings menu in your WordPress admin area, or you can click “Settings” on the plugin listing on the Plugins page.

The plugin is set to serve Font Awesome Free icons as a Web Font via the Font Awesome CDN by default. You can change the CDN settings right in the plugin. If you want just the basic Free icons, you probably don’t need to make any changes to the default configuration.

Using Pro Icons and Features
To enable Pro icons with the CDN, you will need to add your domain to the list allowed domains on your [Font Awesome CDN Settings page](https://fontawesome.com/account/cdn). To configure a Kit, get your [API Token from your Font Awesome account page](https://fontawesome.com/account#api-tokens).
```

**Comment by kevindherman** [comment]
@curtismchale just labeled this as a priority since the contact label item is pretty much done. 

Upgrading to 6 will be a good start for the larger upgrade conversation we're discussing. 

cc @lukefretwell

**Comment by curtismchale** [comment]
@kevindherman @lukefretwell 

Looking at this, it's not a drop in thing. We will have to
- [ ] rebuild the `gulp` processes in a few spots (theme, wp-proud-admin, wp-proud-core)
- [ ] update how we do FA in our CSS because they changed it with V6
- [ ] upgrade our icon picker because the old one is no longer supported at all
- [ ] probably some other stuff I'm missing

Really just FYI, it's not going to be as quick as it seemed when we talked yesterday.

**Comment by kevindherman** [comment]
@curtismchale @lukefretwell all of our customers rely on the icon system so I think this remains a priority with the extra work. In upgrading the picker, I'd keep an eye on how this would effect people who upgrade to the supermax accounts since that's hopefully around the corner as an option.

**Comment by lukefretwell** [comment]
@curtismchale we do a lot of this in the background but FYI: https://uxdesign.cc/make-your-design-system-accessible-part-2-icons-f3f7bd0b4b5a
