### ISSUE TITLE
Locations with custom Latitude/Longitude displaying unnecessary comma

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1998]
**Source**
Petaluma
https://cityofpetaluma.org/cip-projects-map#/maps-1/map/cip-projects/details/42832

**Describe the bug**
Locations that do not have a physical address and use custom latitude and longitude coordinates are displaying the comma that is usually placed in an address. It should just be blank above the "get directions" button. 

Display: https://cityofpetaluma.org/cip-projects-map#/maps-1/map/cip-projects/details/42832
![Screen Shot 2022-03-24 at 9 31 10 AM](https://user-images.githubusercontent.com/6032426/159927701-c8ba08bb-a94f-4d37-8566-9b6f69b6dbe3.png)

Location with custom lat/long:
https://cityofpetaluma.org/wp-admin/post.php?post=42832&action=edit

Display with address:
![Screen Shot 2022-03-24 at 9 36 11 AM](https://user-images.githubusercontent.com/6032426/159928006-6622376c-3149-4d90-b790-d16f335e3d5a.png)

Location with address: 
https://cityofpetaluma.org/planning-major-developments/#/maps-1/map/major-development-projects/details/7328 (scroll down)
https://cityofpetaluma.org/wp-admin/post.php?post=7328&action=edit

**Comment by curtismchale** [comment]
@kevindherman this is a bit more complicated than I thought because it's part of the service center. I've talked with Alex and made a change but he's going to have to roll the change out to beta for proper testing.

You can see the PR here: https://github.com/proudcity/service-center/pull/2

**Comment by kevindherman** [comment]
@curtismchale thanks for the update and thank you @aschmoe for the support.

**Comment by curtismchale** [comment]
@kevindherman clicking the links above and they are no longer returning the map. I looked around and have no idea how to bring up the map at all.

Can you check to make sure that this is deployed properly, or provide a link that does work to bring up the map with a map that has no address.

**Comment by kevindherman** [comment]
@curtismchale try this link: https://cityofpetaluma.org/cip-projects-map#/maps-1/map/cip-projects/details/42832

I still see the comma.

**Comment by curtismchale** [comment]
@kevindherman thanks.

@aschmoe we need to do a bit more to get this comma gone it would seem.

**Comment by aschmoe** [comment]
@curtismchale @kevindherman this is deployed
