### ISSUE TITLE
Pare down widget options (normal customize interface for footer/sidebar)

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#20]

**Comment by jlyon** [comment]
leave question marks out for now

iconset
jumbotron
jumbotron header
accordion
carousel?
image
list?
share?
tab
text
video?
button?
button bar?
table?

agency menu
proudcity map
searchbox
social feed
mailchimp sign up form?
agency social media *change title to "agency social media links"
agency hours
agency contact info
311 actions box
submenu?
google translate drop down?
share dropdown?
font size dropdown?
icon link?
Content list

**Comment by aschmoe** [comment]
@jlyon we leaving this open for reference, or you think this has been taken care of?

**Comment by jlyon** [comment]
i think we want to leave it open to revisit, but it's pretty much donezo. ill clear the assignment
