### ISSUE TITLE
Improve pager

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2000]
**Source**
Petaluma
https://cityofpetaluma.org/job-descriptions
![Screen Shot 2022-03-25 at 9 44 08 AM](https://user-images.githubusercontent.com/6032426/160132317-c8ec32f4-a9bd-4b37-b81c-43119848c2a5.png)

**Is your feature request related to a problem? Please describe.**
The previous and next default for the pager can be confusing depending on the content list. It's especially confusing for large lists with multiple pages. 

From ticket:
`Can we get a permanent fix to the way "Next" & "Previous" show up on multi-page Content Lists? This has been an issue since we launched the website. Our HR dept has a list of job descriptions that spans multiple pages. The first page is at https://cityofpetaluma.org/job-descriptions. But you need to click "Previous" to get to the second page, here: https://cityofpetaluma.org/job-descriptions?pager=2. These seems like it should be an easy fix on the back end. Help!`

**What feature would you like to improve**
Improve pager for all content lists. 

**Describe the solution you'd like**
I'm not sure what the best solution is and I wonder if @curtismchale and @lukefretwell have best practices that they like and can suggest. 

One suggestion has been to reverse previous and next but I'm concerned that would solve the problem in this use case and create issues in others. Perhaps numbers and arrows would be better.

@lukefretwell @curtismchale is there an obvious, simple approach you would go with?

**Comment by lukefretwell** [comment]
Here's the Bootstrap pagination code that would be ideal to use for this:

https://getbootstrap.com/docs/4.0/components/pagination/#overview

**Comment by kevindherman** [comment]
@lukefretwell @curtismchale the client suggestion is to just reverse the current behavior so next is highlighted on page one and previous would bring you back. Here's a page with the pager being used: https://cityofpetaluma.org/job-descriptions

**Comment by curtismchale** [comment]
@kevindherman @lukefretwell I was thinking something along the lines of the image below which matches up with the Bootstrap example luke gave us.

<img width="751" alt="CleanShot 2022-05-26 at 08 32 08@2x" src="https://user-images.githubusercontent.com/74561/170521641-cbb6d35a-bb94-4c52-a50d-6ef1b67bffd3.png">

I think that giving some feedback on the number of pages helps set user expectations as well.

### Notes for me

This code is found in `wp-proud-core/modules/proud-teasers/templates/pagination-default.php`

We can use the `paginate_links` function built into WordPress to make this work. I'll need to get the query values for the job listing and use that in the `base` argument to make the query work as expected.

**Comment by kevindherman** [comment]
@curtismchale yeah, I agree with using numbers to help understand where in the pager the user is. 

@lukefretwell what do you think?

**Comment by lukefretwell** [comment]
@kevindherman @curtismchale agree on numbers.

**Comment by kevindherman** [comment]
@curtismchale if you think there is a clear path forward on this, feel free to knock out.

**Comment by kevindherman** [comment]
@curtismchale another pager: https://cityofpetaluma.org/documents

**Comment by curtismchale** [comment]
@lukefretwell @kevindherman are we good with the style for the page as shown below?

<img width="752" alt="CleanShot 2022-06-21 at 15 24 53@2x" src="https://user-images.githubusercontent.com/74561/174906966-40bf69ce-4f8c-4de7-89c7-1bccd2b8cbbe.png">

I couldn't get the standard CSS stuff to build so I used the same 'quick' method we used in the Proud Admin plugin a few weeks back to load a new CSS file for current updates to the site.

**Comment by kevindherman** [comment]
@curtismchale that works for me. Would the default starting point be "1" with "Previous" not able to link until on 2 or higher?

@lukefretwell thoughts?

**Comment by lukefretwell** [comment]
@curtismchale @kevindherman works for me.

**Comment by curtismchale** [comment]
@kevindherman yes the https://cityofpetaluma.org/job-descriptions page works the same way.

**Comment by lukefretwell** [comment]
@curtismchale @kevindherman looks good to me.
