### ISSUE TITLE
Dashboard not showing in admin

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2003]
**Source**

LF

**Describe the bug**

The dashboard page inside of the admin isn't showing for me. It appears this only happens for info@.

**To Reproduce**
1. Login to MyProudCity
2. Navigate to admin
3. Select dashboard in leftnav admin
4. See blank page

**Expected behavior**

To see dashboard items.

**Screenshots**

What I see: 

![Screenshot 2022-03-25 at 11-27-56 Dashboard ‹ Your City — WordPress](https://user-images.githubusercontent.com/1569463/160180326-9f0d9b79-55af-4c0d-ae1f-132ff0b842a8.png)

What I expect:

![Screenshot 2022-03-25 at 11-35-39 Dashboard ‹ Proudly Serving — WordPress](https://user-images.githubusercontent.com/1569463/160181370-79060d0c-e070-4cbc-aa1e-237e97e7a891.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Firefox

**Comment by curtismchale** [comment]
We revamped and dropped this dashboard entirely.
