### ISSUE TITLE
New address field for contacts editing bug

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2007]
**Source**
Sonoma, CA
https://www.sonomacity.org/contacts/art-escape-sonoma/

**Describe the bug**
If you enter an address, it displays on the front end but the information that displays in the address field when you go back to edit is wp code. 

This relates to the new address field from https://github.com/proudcity/wp-proudcity/issues/1968

**To Reproduce**
1. Go to https://www.sonomacity.org/contacts/art-escape-sonoma/
2. edit contact
3. view address field
4. See wp code

**Expected behavior**
It should just display the address that was entered.

**Screenshots**

Enter address and publish:
![art escape 2](https://user-images.githubusercontent.com/6032426/162441439-0f414921-19ab-4ccc-a4e5-d1d7c4eb8b78.PNG)

Front end view:
![art escape 3](https://user-images.githubusercontent.com/6032426/162441441-df6fed09-3856-4717-8222-2b11f991ee92.PNG)

Then editing shows the wp code:
![art escape 1](https://user-images.githubusercontent.com/6032426/162441433-06f8b5d4-372b-488b-a213-f395f9e9ca14.PNG)

**Comment by curtismchale** [comment]
@kevindherman another quick fix. I applied this manually to their site as well because I was seeing different behaviour on my local install than they showed on the live site. 

This will roll out with the next release to everyone.

**Comment by kevindherman** [comment]
@curtismchale thank you!

**Comment by kevindherman** [comment]
@curtismchale @lukefretwell what are you guys' thoughts on the link text saying "contact" in the hyperlink text? Shouldn't it just be the hyperlink without the word contact?

**Comment by curtismchale** [comment]
@kevindherman @lukefretwell I don't care what it says really, but I think it needs to say something. Does just a name with a link indicate what it is? Would the title "Contact Link" instead of just "Link" as it is now be descriptive enough?

**Comment by curtismchale** [comment]
@kevindherman @lukefretwell I've moved the discussion about this heading change off to a new issue for the next deploy. You can find it here: https://github.com/proudcity/wp-proudcity/issues/2012

**Comment by kevindherman** [comment]
@curtismchale thank you.
