### ISSUE TITLE
Event with "does not have physical location" checked should hide the directions link on frontend

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2008]
**Source**
Santa Ana
https://beta.santa-ana.org/event/fitness-and-basketball-court-ribbon-cutting-ceremony-at-el-salvador-park/

**Describe the bug**
Event with "does not have physical location" checked should hide the directions link on frontend

**To Reproduce**
1. Go to https://beta.santa-ana.org/event/fitness-and-basketball-court-ribbon-cutting-ceremony-at-el-salvador-park/
2. Click directions and you get an error
3. If you edit the event you'll see the checkbox that there isn't a physical location is checked

**Expected behavior**
If the option is selected that there is not a physical location, the directions button should be hidden on the frontend.

**Comment by curtismchale** [comment]
@kevindherman this was a super quick fix so I rolled it into the next release.
