### ISSUE TITLE
MARKETING: Quote app

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#201]
- [x] Add share to quote @aschmoe 
- [x] Add expires to quote 
- [x] Setup homepage mockup
- [x] Add header to comparison split-screen
- [ ] Add responsive menus to demo @aschmoe 
- [x] Form submissions + test
- [x] GA click events
- [x] integrate into dev.proudcity.com
- [ ] push live

Known issues:
- [ ] x-frame-origin options http://demo-api.proudcity.com/calc/side-by-side/?city=Houston&state=TX&fullstate=Texas
- [x] baltimore: no data found
- [ ] follow https:// redirects (https://louisvilleky.gov/)
- [ ] clicking one of the responsive mode links for PC, dragging the window width divider, then clicking on one of the responsive mode links for the city yields strange sizes

**Comment by jlyon** [comment]
Alright, @lukefretwell @kevindherman @aschmoe what do you think of these:

* for proudcity.com: https://demo-api.proudcity.com/calc
* for proudcity.com/plans: https://demo-api.proudcity.com/calc/calc.html

**Comment by lukefretwell** [comment]
Looks great to me. :muscle:

**Comment by kevindherman** [comment]
Strong.

@jlyon can you add the phone number under the address on the quote page: (510) 671-0593

We should also add either an email capture after someone clicks "get quote" or "accept quote" at the bottom of the quote page so we don't lose conversion opportunities.

**Comment by jlyon** [comment]
Added a checklist above the compare: http://demo-api.proudcity.com/calc/side-by-side/?city=Corvallis&state=OR&fullstate=Oregon. Thoughts?

**Comment by kevindherman** [comment]
Really cool. The browser sizes is a nice touch too.

**Comment by aschmoe** [comment]
Yeah looks sweet.  Clicking the desktop one seems a little jarring since it essentially hides the other window, but I think its fine... don't have another suggestion.

**Comment by jlyon** [comment]
Cool, I added the claim input and a print button on the quote page.

@aschmoe it looks like the bottom bar isn't set up on demo. Was it ever?

**Comment by jlyon** [comment]
Tweaks
 -[ ] Compare goes below
- [ ] Link Balt to their website, demo to ProudCity
- [ ] Compare ProudCity to the current website
- [ ] Line item for url
- [ ] Add phone, info@ email on proudcity.

**Comment by kevindherman** [comment]
@jlyon When I click on the quote link from the email notifications I get a page not found message. 

Quote: https://proudcity.com/quote?state=CA&city=San_Francisco

**Comment by jlyon** [comment]
To us
```
Email: jeff@proudcity.com
City: San Francisco, CA
Demo: https://demo.proudcity.com/get/California/San_Francisco
Quote: https://proudcity.com/quote?state=CA&city=San_Francisco
```

To them:
```
Thank you for your interest in using ProudCity in San Francisco.  You can view, share and print your customized quote at https://proudcity.com/quote?state=CA&city=San_Francisco.

We're building a better platform for today’s government that includes a BETA website, where you can customize and build out your website for free.

More about ProudCity
* How it works: https://proudcity.com/how-it-works
* Getting started: https://proudcity.com/getting-started
* Guides: https://proudcity.com/guides

Want to learn more? Respond to this email to send us a note at info@proudcity.com.

Team ProudCity
http://proudcity.com

Subscribe: https://proudcity.com/subscribe
Follow: https://twitter.com/getproudcity
```

**Comment by jlyon** [comment]
Pushed this live at https://proudcity.com and https://proudcity.com/plans.  @aschmoe @kevindherman @lukefretwell please test

**Comment by kevindherman** [comment]
Get a quote from the compare page goes to a drupal page not found.

http://demo-api.proudcity.com/compare/?city=Oakland&state=CA
![screenshot 2016-03-08 14 50 13](https://cloud.githubusercontent.com/assets/6032426/13614153/17adf5c2-e53d-11e5-805d-dcb22a53092c.png)

http://demo-api.proudcity.com/quote?city=Oakland&state=CA
![screenshot 2016-03-08 14 49 51](https://cloud.githubusercontent.com/assets/6032426/13614137/09001fb4-e53d-11e5-8684-ce87e31e555b.png)

**Comment by jlyon** [comment]
Fixed this, thx

**Comment by kevindherman** [comment]
You don't need to enter your email address to get a quote from the compare page. Lets leave this functionality for now but if we decide to add email collection to all get quote buttons and not just the primary one, we need to remember the compare page too.

**Comment by jlyon** [comment]
Sounds good
