### ISSUE TITLE
Check Simple Staff List for updates

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2010]
We have changes integrated into the plugin and we're waiting for release so we can move back to the Simple Staff List plugin. We are currently running our own accepted modified version so we have the changes we need.

SSLP: https://wordpress.org/plugins/simple-staff-list/
Looking for version above 2.2.1

**Comment by kevindherman** [comment]
@curtismchale I'm catching up, can you let me know what needs to happen for this to be unblocked?

**Comment by kevindherman** [comment]
@curtismchale right, thank you. Helpful to have this note in here since it's in the blocked list.

**Comment by curtismchale** [comment]
@kevindherman I just checked and setup our move back to the official one so that we can get off our own version.

**Comment by kevindherman** [comment]
@curtismchale awesome.
