### ISSUE TITLE
XML Sitemaps has been closed

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2013]
**Source**
Curtis

**Describe the bug**
The [XML sitemap](https://wordpress.org/plugins/google-sitemap-generator/#description) plugin we're using has been closed and doesn't work in our build process anymore.

We should look at just using all of [Yoast's features including it's XML sitemap build feature](https://yoast.com/help/xml-sitemaps-in-the-wordpress-seo-plugin/).

This would let us drop the plugin that isn't really available anymore.

**To Reproduce**
None

**Expected behavior**

**Comment by curtismchale** [comment]
@kevindherman @lukefretwell we need to move this one up in priority so that we can roll out a better solution for the next release.

We (I) need to investigate the Yoast features and what it will take to script any updates that become required when we move.

**Comment by kevindherman** [comment]
@curtismchale I moved up to the top of the backlog.

**Comment by curtismchale** [comment]
@kevindherman this was released in hotfix 1.123.1 on April 20
