### ISSUE TITLE
DEMO: report an issue type detail not showing map

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#203]

**Comment by kevindherman** [comment]
On the demo after selecting an issue type from this page the detail isn't not showing the map:

Select an issue:
![screenshot 2016-03-04 14 05 34](https://cloud.githubusercontent.com/assets/6032426/13537307/5415f088-e212-11e5-86a2-683b510aeb69.png)

Detail without map view:
![screenshot 2016-03-04 14 05 21](https://cloud.githubusercontent.com/assets/6032426/13537331/7238da6c-e212-11e5-9a4d-9ccf6403d98d.png)

Here's the link to the detail page on the demo: https://demo.proudcity.com/get/Connecticut/New%20Haven/report/7502

**Comment by jlyon** [comment]
Fixed this @kevindherman @lukefretwell.  Needed to update the Mapbox key.

**Comment by jlyon** [comment]
Moved this back to in progress. Need to figure out why the next button isnt working here.

**Comment by jlyon** [comment]
@aschmoe On Demo, the Next button appears in the top-right, but it isn't clickable (it's behind the breadcrumb div).  On Example, no next button appears for some reason  3 fixes 

- [ ] Make Next button appear on Example
- [ ] Make Next button clickable (zindex)
- [ ] Automatically go to next step if user clicks on map or enters an address?

**Comment by aschmoe** [comment]
> Make Next button clickable (zindex)

This is just disabled until a position on the map is entered.  On the demo for me no map appears, so this is not possible.

**Comment by aschmoe** [comment]
@jlyon @kevindherman fixed various issues for this on Demo + Example

**Comment by aschmoe** [comment]
@jlyon 

> Automatically go to next step if user clicks on map or enters an address?

Feel like ability to change marker is nice.. click in front of your house, then change to middle of street for pothole or something

**Comment by jlyon** [comment]
Agreed, do we need to make the next button more prominent?
