### ISSUE TITLE
How do I increase resources for a site?

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2030]
**Source**
Curtis

We need to document how to increase resources for a customer so that Curtis can do this.

This should be included in the ProudCity handbook.

**Comment by jlyon** [comment]
Added to https://docs.google.com/document/d/1-HyCKfRXVVLtSIDagllW2jmLhct3k7qCWKETyC6Fmmg/edit#heading=h.6uae0tp0s5qv
