### ISSUE TITLE
Document development on ProudCity Dashboard

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2033]
**Source**
Curtis

We need some better docs on the Dashboard so we can do development on it. See this comment in docs: https://docs.google.com/document/d/1-HyCKfRXVVLtSIDagllW2jmLhct3k7qCWKETyC6Fmmg/edit?disco=AAAAZBuEPjQ

**Comment by jlyon** [comment]
Added details: https://docs.google.com/document/d/1-HyCKfRXVVLtSIDagllW2jmLhct3k7qCWKETyC6Fmmg/edit#heading=h.fx4zzb74zzxw

**Comment by jlyon** [comment]
@curtismchale Development docs for the dashboard and service center added:
- Dashboard/API: https://docs.google.com/document/d/1-HyCKfRXVVLtSIDagllW2jmLhct3k7qCWKETyC6Fmmg/edit#heading=h.fx4zzb74zzxw
- Service Center: https://docs.google.com/document/d/1-HyCKfRXVVLtSIDagllW2jmLhct3k7qCWKETyC6Fmmg/edit#heading=h.yaymk6k5zgli
