### ISSUE TITLE
Wrong time displaying in calendar widget

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2035]
**Source**
Santa Ana: https://www.santa-ana.org/library-calendar/

**Describe the bug**
The calendar widget displays the publish time rather than the event time in the calendar display. This seems isolated to Santa Ana which makes me believe it's a WP-Rocket setting. 

View https://www.santa-ana.org/library-calendar/ and you'll see event times per event. If you click on one you'll notice a different time is displayed.
https://www.santa-ana.org/event/wilshire-square-neighborhood-meeting-wednesday-may-4/

If you edit the event you'll notice the time on the calendar is the time the event was published. 

**Expected behavior**
If you look at an example without WP Rocket enabled the calendar times display correctly: https://www.williamsnd.com/calendar

**Screenshots**
Incorrect time display: 
https://www.santa-ana.org/library-calendar/
<img width="1043" alt="Screen Shot 2022-05-09 at 9 27 55 AM" src="https://user-images.githubusercontent.com/6032426/167420884-75af40fd-f89e-4db2-b744-76dfe2fe75ce.png">

Event shows correct time (different from calendar widget)
<img width="977" alt="Screen Shot 2022-05-09 at 9 31 49 AM" src="https://user-images.githubusercontent.com/6032426/167421079-10d8d044-a698-4a13-b67c-968f607c65de.png">

Time in the calendar widget matches published on time:
<img width="1185" alt="Screen Shot 2022-05-09 at 9 28 49 AM" src="https://user-images.githubusercontent.com/6032426/167421128-c678f5c7-162d-429b-9726-58a8571c03ab.png">

Correct display: https://www.williamsnd.com/calendar (not using wp-rocket)
<img width="1356" alt="Screen Shot 2022-05-09 at 9 27 46 AM" src="https://user-images.githubusercontent.com/6032426/167420907-46f2bf8c-ac4f-4552-bf06-ca1452765cd1.png">

**Comment by aschmoe** [comment]
@curtismchale 

<img width="1936" alt="Screen Shot 2022-05-12 at 12 53 18 PM" src="https://user-images.githubusercontent.com/1634686/168157304-e52c21a8-ce4f-4a3f-b831-d97deeea4feb.png">


looks like we could probably just init something like

```
if (typeof WPFC == 'undefined') {
  var WPFC = {};
}```

up in the header or whatever.  The offending code is coming from the plugin in `wp-fullcalendar.php`

**Comment by aschmoe** [comment]
@curtismchale though I am seeing on the Williams site:

```
<script id=wp-fullcalendar-js-extra>
  var WPFC = {"ajaxurl":"https:\/\/www.williamsnd.com\/wp-admin\/admin-ajax.php?action=WP_FullCalendar","firstDay":"0","wpfc_theme":"jquery-ui","wpfc_limit":"10","wpfc_limit_txt":"more ...","timeFormat":"h(:mm)t","defaultView":"month","weekends":"true","header":{"left":"prev,next today","center":"title","right":"month,basicWeek,basicDay"},"wpfc_qtips":""};
</script> 
<script src='https://www.williamsnd.com/wp-content/plugins/wp-fullcalendar/includes/js/main.js?ver=1.4.1' id=wp-fullcalendar-js></script>
```

which I'm not seeing in the markup on santa ana... so not sure whats up with that.

**Comment by jlyon** [comment]
Setting these Never cache urls on https://www.santa-ana.org/wp-admin/options-general.php?page=wprocket#advanced_cache didn't seem to fix it.

**Comment by jlyon** [comment]
Here's more details on the calendar options with wp-events-manager.  The non-fullcalendar version looks pretty bad...  https://wp-events-plugin.com/documentation/calendars/

**Comment by kevindherman** [comment]
@jlyon @curtismchale @aschmoe I'm looking at https://www.santa-ana.org/library-calendar/ and it's displaying the correct times. Could there just have been a delay?

**Comment by aschmoe** [comment]
@curtismchale https://github.com/wp-plugins/wp-fullcalendar/blob/master/wp-fullcalendar.php#L145 this is what was missing from the dom in the full calendar case, fyi.

**Comment by curtismchale** [comment]
After review we've resolved this with a change to the JS settings in WP Rocket. Everything appears to work fine now.
