### ISSUE TITLE
Add ProudCity messages to admin

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2037]
**Source**

LF

**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

It would be great to add a message panel of some sorts to the admin or dashboard, so that we can provide updates/information directly into the CMS so that they're front and center.

**Comment by curtismchale** [comment]
To do this we'll need to find a way "around" our shutdown of notifications here: https://github.com/proudcity/wp-proud-core/blob/master/modules/notification-shut-down.php

Maybe, I could change the priority of the removal to 98 and then add our messages back at 99? Not sure.

**Comment by curtismchale** [comment]
Closing in favour of this new version: https://github.com/proudcity/wp-proudcity/issues/2566
