### ISSUE TITLE
Icon picker doesn't appear in existing iconsets after selecting "add another" button

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2041]
**Source**
[The source of the issue (ex: Customer: #CustomerName#).](https://www.santa-ana.org/)

https://www.santa-ana.org/housing-resources/

**Describe the bug**
Icon picker doesn't appear in existing iconsets after selecting "add another" button. However, if you leave the added icon area blank, update the page and then go back to the iconset the new icon picker appears. Sometimes the new picker will show after a few seconds. If it doesn't appear after 5-10 seconds, the save and return to the edit widget view works. 

**To Reproduce**

**Screenshots**
Edit widget > add another icon
![Screen Shot 2022-05-17 at 9 16 39 AM](https://user-images.githubusercontent.com/6032426/168820814-a869cad2-fee7-4858-8051-85eedd0e5361.png)

New picker not showing
![Screen Shot 2022-05-17 at 9 16 46 AM](https://user-images.githubusercontent.com/6032426/168820819-c5c756f1-855b-43b2-b8af-29bf82c245ba.png)

Leave blank, update the page, return to the widget and the picker appears:
![Screen Shot 2022-05-17 at 9 18 36 AM](https://user-images.githubusercontent.com/6032426/168820963-dcfe2895-538a-44b2-a796-6914ab005816.png)

**Comment by curtismchale** [comment]
We resolved this by adding a trigger to the JavaScript that runs when you add a row. Then we can target a new row being added and we can run the icon picker JS after the new row has been added.
