### ISSUE TITLE
Media library everywhere

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2045]
Provide media library folder upgrade everywhere @jlyon

**Comment by jlyon** [comment]
@curtismchale we just need to add this command to the next release's `install.sh` file:
```
wp plugin activate --allow-root wp-media-folder
```

**Comment by curtismchale** [comment]
@jlyon done: https://github.com/proudcity/wp-proudcity/commit/faa9fde0c3612dd6fff3cbb85e66f4f045f87634

**Comment by kevindherman** [comment]
@curtismchale @jlyon I'm not seeing the new media library on sites using the Recovers theme. Here are a few examples:

- https://marin-watershed-program-ca.proudcity.com/
- https://regis.solanocounty.com/
- https://redistricting.solanocounty.com/
- https://www.mvrma.com/
- https://publicworks.marincounty.org/

**Comment by curtismchale** [comment]
@kevindherman let's create a new ticket for this.
