### ISSUE TITLE
Image gallery images display file name instead of caption

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2054]
**Source**
Williams County

**Describe the bug**
Images displaying in the gallery widget show the file name instead of the caption in lightbox. Displays correctly in tile view. 

**To Reproduce**
1. Go to https://www.williamsnd.com/kota-ray-dam
2. Scroll down to image gallery
3. Click image
4. See text is the file name instead of caption in lightbox

**Expected behavior**
Display caption and not the file name. This is what happens on the tile view. 

**Screenshots**
Tile view displaying caption correctly:
![Screen Shot 2022-06-06 at 12 10 18 PM](https://user-images.githubusercontent.com/6032426/172200579-b1bcc48e-4c54-4f67-a710-4173be3231c6.png)

Lightbox displaying file name instead of caption:
![Screen Shot 2022-06-06 at 12 10 26 PM](https://user-images.githubusercontent.com/6032426/172200584-0fa045ae-9045-4382-a591-a5d40b47c673.png)

Hover over combines file name AND caption: https://www.williamsnd.com/mcgregor-dam/
![Screen Shot 2022-06-06 at 12 16 01 PM](https://user-images.githubusercontent.com/6032426/172201858-c3ff7c03-fbc4-43ee-ba17-06ad137451be.png)

**Related issue**
This may relate to this issue: https://github.com/proudcity/wp-proudcity/issues/1851

**Comment by curtismchale** [comment]
@kevindherman it's not displaying the `filename` it's displaying the Title of the image. The title is derived from the filename to start. That means the user needs to change the Title of images if they want something different to display as the title of the image in the gallery.

![CleanShot 2022-10-13 at 14 17 01@2x](https://user-images.githubusercontent.com/74561/195712615-1ce9611a-9df9-47a8-a0d4-8e56ec3ebea9.png)

I think this can simply be resolved then from a development perspective as there is nothing for me to do.
