### ISSUE TITLE
How do we manage private plugin repositories in our google repositories?

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2059]
**Source**
curtis

**Feedback**
I need information on how to add a private paid plugin to our deploy scripts because we don't have them in our standard `composer.json` file.

- [x] how do you add a plugin to repositories and the build process
- [x] how do you update the plugin when it needs to be updated

**Comment by jlyon** [comment]
Added a section: https://docs.google.com/document/d/1-HyCKfRXVVLtSIDagllW2jmLhct3k7qCWKETyC6Fmmg/edit#heading=h.jn6q69rd379p
