### ISSUE TITLE
How do we add new wp cli packages to the deploy process

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2060]
**Source**
Curtis

**Feedback**
We are now adding the wp rocket cli stuff, how do I add other tools if we need those in the future?

- [x] where do we place the package
- [x] what commands need to be issued to make sure that it's installed properly
- [x] how do I run a test once the commands are done to make sure that they worked and I can expect it to be there in the next deploy

**Comment by jlyon** [comment]
Added a paragraph and a link: https://docs.google.com/document/d/1-HyCKfRXVVLtSIDagllW2jmLhct3k7qCWKETyC6Fmmg/edit#heading=h.szsxn67r5oeu
