### ISSUE TITLE
How do we add new global environment variables to wp-config.php

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2061]
**Source**
Curtis

**Feedback**
- [x] where does the variable declaration go?
- [x] which `wp-config.php` file do we edit so that every site gets this new variable with `getenv`
- [x] where do we put a "secret" item so that the whole platform has access to the information

**Comment by jlyon** [comment]
Added these details to https://docs.google.com/document/d/1-HyCKfRXVVLtSIDagllW2jmLhct3k7qCWKETyC6Fmmg/edit#heading=h.hdnj4j1s3jhh
