### ISSUE TITLE
How do we add environment variables to single sites

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2062]
**Source**
Curtis

**Feedback**
- [x] where does the variable go?
- [x] how do we edit the `wp-config.php` file for a single site?
- [x] what if there is a "secret" item. How do we add that to the single site?

**Comment by jlyon** [comment]
Added these details: https://docs.google.com/document/d/1-HyCKfRXVVLtSIDagllW2jmLhct3k7qCWKETyC6Fmmg/edit#heading=h.hdnj4j1s3jhh
