### ISSUE TITLE
Media library everywhere not deployed to non-city template instances

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2067]
**Describe the bug**
@curtismchale  The new media library was meant to be deployed everywhere but I'm not seeing it on sites using the Recovers theme. 

Here's the closed ticket for media library everywhere: https://github.com/proudcity/wp-proudcity/issues/2045

**Source**
Some examples:

https://marin-watershed-program-ca.proudcity.com/
https://regis.solanocounty.com/
https://redistricting.solanocounty.com/
https://www.mvrma.com/
https://publicworks.marincounty.org/

**Expected behavior**
The new media library should be on all instances.

**Comment by curtismchale** [comment]
Per discussion today the activation commands were added again to 1.129.0
