### ISSUE TITLE
Search and replace subdomain and test site URL

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2068]
**Source**
(https://www.santa-ana.org/)

**Describe the bug**
occassionally seeing old subdomain and test site URL:
beta.santa-ana.org
santa-ana-ca.proudcity.com

Should do a search and replace to correct them.

**Comment by kevindherman** [comment]
@curtismchale Port Orchard recent changed their primary domain and has flagged similar issues. Could you include this search and replace when you update Santa Ana:

portorchardwa.gov is the primary domain and should replace cityofportorchard.us (old) links .

**Comment by kevindherman** [comment]
[west-carrollton-oh.proudcity.com](http://west-carrollton-oh.proudcity.com/) should go to https://www.westcarrollton.org/

**Comment by kevindherman** [comment]
@curtismchale this might be something worth considering for the launch checklist if wp-rocket is making the redirects a little wonky.

**Comment by curtismchale** [comment]
@kevindherman done for these two sites.

If we're going to do this then we should look at getting our own license of [WP Migrate](https://aff.deliciousbrains.com/idevaffiliate.php?id=21138). I used my own copy this time, but if we're using it regularly my license won't fit all the sites we have.
