### ISSUE TITLE
Gravity forms, WP Rocket, media folder files missing and breaking plugins

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2077]
**Source**
Platform 

**Describe the bug**
Gravity forms, WP Rocket, media folder files missing and deactivating plugins

**Comment by kevindherman** [comment]
@jlyon can you adjust the info to what has been done to resolve this? Feel free to adjust the description to be more accurate.

**Comment by curtismchale** [comment]
Closing because this is duplicated here: https://github.com/proudcity/wp-proudcity/issues/2079
