### ISSUE TITLE
Reformat People / Contact us

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#208]
Is the 'Contact us' heading hardcoded on people pages?

Like here: 

https://www.westcarrollton.org/contacts/jeffery-w-sanner/

We might want to make the person's name the bold h1 and not have the contact heading. Alternative would be to change main heading to 'People.'

Other thoughts:

* make photo/contact on left side (see: https://cio.gov/author/tony-scott/)
* link phone
* display 'Title' in area where email/phone/etc is
* move 'Elected officials' tag to below contact info

**Comment by jlyon** [comment]
Will play around in pattern library for this too.

**Comment by jlyon** [comment]
Also: Add HTML filter so line breaks appear (https://www.westcarrollton.org/contacts/jeffery-w-sanner/).

**Comment by jlyon** [comment]
@lukefretwell thoughts?
before: https://www.westcarrollton.org/contacts/jeffery-w-sanner/
after: http://pattern.getproudcity.com/?v=&page=staff-content

**Comment by lukefretwell** [comment]
Perfect @jlyon.
