### ISSUE TITLE
Add label change functions to ProudCity Quick Menu

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2080]
Take the updated PC Quick Menu plugin and allow the user to edit the label that displays in the menu from the post/page/thing that they are currently viewing.

**Comment by curtismchale** [comment]
@kevindherman @lukefretwell did you get a chance to look at the updated label function on Beta?

**Comment by kevindherman** [comment]
@curtismchale @lukefretwell functionality-wise it's good. This is a common item so I'm comfortable releasing and then cleaning up shortly after. 

If we're putting in UX feedback I think the edit label should be more available. What do you think of the current menu that's highlighted in blue being expanded so the edit label is visible. This is closer to the current option and my concern is that the gear isn't enough for people to find. 

@lukefretwell's contrast concerns for the blue and indication for the page title is also important.

**Comment by curtismchale** [comment]
You should see the contrast (per @lukefretwell feedback) as shown in the screenshot below. White when we're on a blue "current" page. I did also make the page name a link per our discussion yesterday.

<img width="327" alt="CleanShot 2022-08-10 at 11 27 51@2x" src="https://user-images.githubusercontent.com/74561/183989202-60dba300-bc38-4c92-bd6f-1e0e39095c4a.png">

@kevindherman I just added (and deployed to staging) that the menu does show the edit form opened for the current menu item.

Take a look and I can deploy this tomorrow if it's good.
