### ISSUE TITLE
Handle a page/post in multiple menus

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2084]
If a page/post/thing is in multiple menus we should show each one that it is a part of.

You should be able to add a page/post/cpt to multiple menus.

**Comment by curtismchale** [comment]
@kevindherman I guess we would. Currently, WordPress allows you to have an item in multiple menus so I'd just do what it said. We're not doing anything but allowing it to be added to a menu.

What do we do currently if an item is in multiple menus?

We could also drop this feature, though it was one that is in the original plugin.

**Comment by kevindherman** [comment]
@curtismchale  I'm actually fine with dropping it. It's usually an outlier situation when a page is in multiple menus and when that's the case I'll use the custom link option in the advanced editor so the page maintains it's true home.
