### ISSUE TITLE
Menu items freeze

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2085]
**Source**
- Streetsboro
- Kettering
- West Carrolton
- Cities Association
- Holyoke

**Describe the bug**
While the menu HTML appears to be intact, clicking the links does nothing but recycle you to the main page of the site. Clearing the cache seems to resolve this issue.

**To Reproduce**
- we currently do **not** have steps to reproduce this 

**Expected behavior**

**Comment by curtismchale** [comment]
@kevindherman @lukefretwell I added logging to the sites listed above so that hopefully we can gather more information and find a common set of actions that causes the menu to freeze.

**Comment by kevindherman** [comment]
anecdotal feedback here. None of those examples are using the top bar navigation or using labels for their service center nav bar icons (service center settings)

<img width="405" alt="Screen Shot 2022-08-11 at 12 20 50 PM" src="https://user-images.githubusercontent.com/6032426/184181740-c447e935-76e3-4833-ae18-95012e49cd23.png">

Those options are more common on newer sites and there has been code added to make sure the topbar plays nicely. Could that be affecting older instances that aren't using the topbar? Just an idea @curtismchale

**Comment by curtismchale** [comment]
The current temporary fix is to stop caching unless the site actually needs it. The issue comes from some conflict with site caching and JS. We can't test this well due to the build process for CSS and JS being hard to run (old and mostly broken).

https://github.com/proudcity/wp-proudcity/issues/2094 Is about resolving the build process so we can work on the CSS and JS without a bunch of headache to get the process running again.
