### ISSUE TITLE
Allow site users to clear cache

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2086]
Site users should be allowed to use clear the WP Rocket cache as this resolves the menu freeze in: https://github.com/proudcity/wp-proudcity/issues/2085

@lukefretwell I assume we don't want all users to be allowed to clear the cache so is there a specific type of user (role in WordPress) that can clear the cache? Based on the users I see on Streetsboro it looks like `Editor` may be the user role to choose.

**Comment by kevindherman** [comment]
@curtismchale can we just give editors the ability to clear the cache but not configure settings for now?

cc @lukefretwell

**Comment by curtismchale** [comment]
Resolved here: https://github.com/proudcity/wp-proud-admin/commit/be37f41f0020341031f8a203f0334bd2979dd4f6

**Comment by kevindherman** [comment]
@curtismchale an admin for Santa Ana said they're not able to clear their cache and provided this screenshot:

![Capture (2) (1)](https://user-images.githubusercontent.com/6032426/194881470-41e800f8-14c9-4822-ab59-07d050e96b72.PNG)

Should I reopen this ticket or create a new one?

**Comment by kevindherman** [comment]
@curtismchale disregard the above. I see the option under settings.
