### ISSUE TITLE
Double Departments on Contact Page

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2089]
**Source**
Jarrell TX

**Describe the bug**
On the [Contact](https://www.cityofjarrell.com/contact) page we see `Departments` twice. The first instance is a link directly to the `/departments` CPT. The second is a taxonomy filter for the contacts shown below.
![CleanShot 2022-08-12 at 09 15 40@2x](https://user-images.githubusercontent.com/74561/184399093-a5fb07d2-fbb7-44a9-acba-0d951814a452.png)

**To Reproduce**
1. Go to the contact page: https://www.cityofjarrell.com/contact
2. Scroll down to the contacts filter
4. See duplicated Departments heading

**Expected behavior**
We should only see the second item as a taxonomy filter. The first item should not be showing.

**Comment by kevindherman** [comment]
This is resolved.
