### ISSUE TITLE
Highlight tab

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#209]
Can we change this to a light grey?

**Comment by lukefretwell** [comment]
<img width="938" alt="screen shot 2016-03-07 at 4 40 17 pm" src="https://cloud.githubusercontent.com/assets/1569463/13588287/6b9fb6e4-e483-11e5-93f8-4f13a2a0297e.png">

**Comment by jlyon** [comment]
Updated the styleguide so this is a lighter gray than the active (will be pushed in release 1.1.0)
