### ISSUE TITLE
Update 'Publish' box

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2090]
**Source**
LF

**What feature would you like to improve**

The 'Publish' box is currently defaulted to closed. 

**Describe the solution you'd like**

Would be great to have it default to open (see screenshot) and located at the top of the right admin column.

**Additional context**

![Screenshot 2022-08-12 at 12-18-56 Edit Page “Local government digital solutions” ‹ ProudCity — WordPress](https://user-images.githubusercontent.com/1569463/184428517-f3511657-3221-4f09-8e9f-685805bd351b.png)

**Comment by curtismchale** [comment]
Deployed 2022.11.07
