### ISSUE TITLE
Give admins permission to manage site icon

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2091]
**Source**
LF

**Describe the solution you'd like**

Give site admins access to manage their site icon.

**Describe alternatives you've considered**

Currently, this is just a ProudCity admin permission. Would be great to open it up to site admins so they could self-manage.

**Additional context**

![Screenshot 2022-08-12 at 12-23-00 Customize Local government digital solutions - ProudCity](https://user-images.githubusercontent.com/1569463/184429446-cdfb2f54-8b43-4bd0-b3d8-b32f459ff5bd.png)

**Comment by curtismchale** [comment]
@lukefretwell this is deployed now so that editors can edit the site icon.
