### ISSUE TITLE
New Build Process for JS and CSS

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2094]
The current gulp build process is almost always problematic to get running and it's using out-of-date libraries and methods. We need to modernize our JavaScript and CSS and part of that is modernizing the build process we use to render the final product of JS and CSS.

- [ ] decide new build process system (webpack, laravel mix, postcss...)
- [ ] get code building again
- [ ] verify with the few customers that have "custom" child themes for compatibility

**Comment by kevindherman** [comment]
Danvers uses the transparent heading: https://www.danversma.gov/

However, I don't know if they also use the slider option in the hero unit anywhere which is where the above bug is coming up.
