### ISSUE TITLE
Add 'Connect' header above department social

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#210]
Can we add a 'Connect' header above department social media in the left column?

**Comment by lukefretwell** [comment]
<img width="1159" alt="screen shot 2016-03-07 at 4 46 07 pm" src="https://cloud.githubusercontent.com/assets/1569463/13588406/5e747d96-e484-11e5-8ed5-7fb4d48b34d4.png">

**Comment by jlyon** [comment]
Trying 
```
dwp search-replace '"title";s:0:"";s:11:"panels_info";a:5:{s:5:"class";s:12:"AgencySocial"' '"title";s:0:"Connect";s:11:"panels_info";a:5:{s:5:"class";s:12:"AgencySocial"' --allow-root
```
but it doesn't like the colins

**Comment by jlyon** [comment]
Unfortunately there wasn't an easy way to automate this. Manually updated all example. depts and the three w social on WC.  All new BETAs will have this.

Created an issue to look into larger automated infrastructure changes like this in the future #216.
