### ISSUE TITLE
Post release 1.132 CSS bugs

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2106]
- [x] Dropdown menus
- [x] Fonts defaulting to arial > https://www.townoffairfax.org/ + https://www.santa-ana.org/ + https://oakwoodohio.gov/
- [x] Meeting list table view tabs
- [x] Boarder issue on department menus
- [x] Underlining menu items (only on primary department menus, nested was not underlined)> https://beta.proudcity.com/departments/testing-menu-department/
- [x] Answers list content accordion view
- [x] Answers content service center
- [x] slideshow directions not working (directions and dots) https://beta.proudcity.com/visitors/
- [x] iFrames not displaying (saw a ticket but didn't verify so this may be nothing)

**Comment by lukefretwell** [comment]
@curtismchale notes/questions:

* For the slider, it looks like it's sliding through the transparent navigation, which makes sense, but another reason why we should get rid of that feature.
* Should we create a template for this type of issue? I know it's in the QA column in the project board, but think it would be helpful to have a link to the widget page, a QA label. I also think that we should think about adding a QA channel to Slack.

cc @kevindherman

**Comment by kevindherman** [comment]
@lukefretwell this all sounds like a smart idea.

**Comment by lukefretwell** [comment]
@curtismchale @kevindherman here's what I did:

* Added a `qa' label for issues
* Created a #qa Slack channel to discuss release QA
* Created a [new issue template](https://github.com/proudcity/wp-proudcity/issues/new?assignees=curtismchale%2C+kevindherman%2C+lukefretwell&labels=qa&template=qa-proudcity-release.md&title=QA%3A+Release+%5BNUMBER%5D) for the QA checklist

@curtismchale feel free to edit the template if you think there is anything to add that would be helpful for you.
