### ISSUE TITLE
Add to calendar from meeting content type doesn't insert event details

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2117]
**Source**
Holyoke reported but it's a platform bug.

**Describe the bug**
When a user uses the add to calendar feature from meetings content (not event) the event comes up blank in Google calendar. 

**To Reproduce**
1. Go to https://www.holyoke.org/meetings/charter-and-rules-committee-meeting-october-24-2022/
2. Click on add to calendar
3. Add to google calendar
4. See blank event in google calendar

**Expected behavior**
Should insert event details like event content type does.

**Screenshots**
![CalendarEntry2](https://user-images.githubusercontent.com/6032426/197586781-0d4075a2-64fb-4182-9d15-997bd3c26ec5.jpeg)
![CalendarEntry3](https://user-images.githubusercontent.com/6032426/197586798-56458526-b14e-4c6d-9d13-c261973f450f.jpeg)

**Related**
This is related to https://github.com/proudcity/wp-proudcity/issues/2111

**Comment by curtismchale** [comment]
@kevindherman this is partially solved. I did find a bug with the addition of time parameters that I have submitted to the project: https://github.com/add2cal/add-to-calendar-button/issues/228

**Comment by kevindherman** [comment]
@curtismchale do you think it's best to hold off until you get info back from the project or push updating with what you have?

**Comment by curtismchale** [comment]
@kevindherman nope I've got a fix in already and will be deploying this shortly.
