### ISSUE TITLE
MARKETING: multiple loading zen desk, some other scripts

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#213]
https://proudcity.com/ seems to be loading scripts multiple times.

**Comment by aschmoe** [comment]
![screenshot from 2016-03-08 11-32-36](https://cloud.githubusercontent.com/assets/1634686/13614106/ba6cbefc-e523-11e5-9476-30c27c14b26e.png)

You can see multiple calls here

**Comment by jlyon** [comment]
@aschmoe, you wanna look into this? The js code is only getting added once (in `/var/www/proudcity/wp-content/plugins/proudcity-custom/assets/tracking-code.php`).  You can play around on dev.proudcity.com if you like.

Only things I can think of are:
* Maybe something in /var/www/proudcity/wp-content/plugins/proudcity-custom/assets/script.js?
* Maybe something with how we're including the Google Place API code (also in proudcity-custom, although this looks like it's only getting added once
* Maybe something with caching (caching is turned off on dev.proudcity.com).
