### ISSUE TITLE
Meetings location display bug

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2130]
**Source**

RW

**Describe the bug**

The meeting location on the individual meeting page is diplaying the field name and not the location name. 

**To Reproduce**
1. Go to https://mountpocono-pa.gov/meetings/borough-council-work-session-november-15-2022/
2. See 'borough-building'

**Expected behavior**

Should display the location name.

**Screenshots**

![Screenshot 2022-11-15 at 19-27-55 Borough Council Work Session November 15 2022 - Mount Pocono PA](https://user-images.githubusercontent.com/1569463/202076590-fd457717-a667-435d-9cb8-d9f7ffb9f169.png)

**Comment by curtismchale** [comment]
@lukefretwell fixed and deploying
