### ISSUE TITLE
Meetings contact informaton showing form field

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2132]
**Source**

LF

**Describe the bug**

The meetings contact information is showing a form field when it looks like it should be text.

**To Reproduce**
1. Go to https://www.cityofmontclair.org/meetings/city-council-november-21-2022/
2. Click on 'Contact information'
3. See error

**Expected behavior**

Text that explains better what that link is.

**Screenshots**

![Screenshot 2022-11-17 at 16-44-33 City Council - November 21 2022 - Montclair CA](https://user-images.githubusercontent.com/1569463/202591033-48a531b0-9af8-4862-9dd0-f21e68f3d319.png)

**Comment by curtismchale** [comment]
@lukefretwell this is resolved and deployed. It ended up being that I needed to change how I escaped the text.
