### ISSUE TITLE
MARKETING: /start not spinning up demo or quote widget

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#214]
/start page not spinning up demo or quote widget after you type in city. 

![screenshot 2016-03-08 15 22 14](https://cloud.githubusercontent.com/assets/6032426/13615093/ae548366-e541-11e5-9ffb-de27c3d25791.png)

**Comment by jlyon** [comment]
Fixed this so it just loads up the demo directly. thx
