### ISSUE TITLE
Site health: You should use a persistent object cache

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2142]
**Source**

LF

**Feedback**

> A persistent object cache makes your site’s database more efficient, resulting in faster load times because WordPress can retrieve your site’s content and settings much more quickly.
> 
> Your hosting provider can tell you if a persistent object cache can be enabled on your site. Your host appears to support the following object caching services: Redis.

**Comment by curtismchale** [comment]
Closing in favour of #2401
