### ISSUE TITLE
Add author to dashboard all meetings list

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2143]
@curtismchale flagged that this would be easy to add in Slack: https://proudcity.slack.com/archives/C02DU8U8FPZ/p1669759466871809

Ticket 6179 text:
Perhaps I'm just missing the option to make this feature visible and I'll be happy to be instructed how to do so. When I look at the list of events that have been created, there are several columns: Title, Location, Date and Time (of the event), Owner, along with a few SEO related columns. When I go to listing for meetings, I have the title, Date (it was published), and some SEO columns. It would be helpful if the meetings had the additional columns, especially the owner column. There are some instances when I may need to make changes to a meeting listing or have questions about one and it's not always obvious who has published a meeting.

**Comment by curtismchale** [comment]
@kevindherman custom admin columns showing the meeting host are now available. This is "behind" our PHP 8 upgrade at this point and not rolled out to everyone. See PHP 8 here: #2124 .

See commit: https://github.com/proudcity/wp-proud-meeting/commit/b57e8b3e7c345dcf7e2647e8d11ea5cf45b38be2
