### ISSUE TITLE
Upgrade Font Awesome to 6.2.0

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2146]
**Source**
Curtis/Kevin

Currently we're running 6.0.0 for Font Awesome. We want the hurricane icon which means we'll need 6.2.0. Need to update the version string in our `fa_build` function and test the API to make sure that it's still working the same and we're getting the icons as expected.

**Comment by curtismchale** [comment]
@kevindherman we can't actually get 6.2.0 as it's not available in the Font Awesome plugin. Upgrading to 6.1.1 does get us the hurricane icon though. Unless I hear otherwise, I'm upgrading to 6.1.1

**Comment by curtismchale** [comment]
@kevindherman this got pushed a while ago so let them know hurricane is available.

**Comment by kevindherman** [comment]
@curtismchale awesome!
