### ISSUE TITLE
Add migration tool(?)

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2156]
**Source**
The source of the issue (ex: Customer: #CustomerName#).

PC conversation (https://github.com/proudcity/wp-proudcity/issues/2068#issuecomment-1171709517)

**Is your feature request related to a problem? Please describe.**

* See conversation link above.
* Opportunity to help migrate government sites using WordPress to ProudCity.

**Describe the solution you'd like**

[WP Migrate](https://deliciousbrains.com/wp-migrate-db-pro/)?

**Describe alternatives you've considered**

N/A

**Additional context**

* [Pricing](https://deliciousbrains.com/wp-migrate-db-pro/pricing/)

**Comment by curtismchale** [comment]
We do this as part of a launch, or relaunch, with Better Search Replace and the step is detailed in the launch checklist.
