### ISSUE TITLE
Footer widget customizer not saving

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2160]
**Source**
The source of the issue (ex: Customer: #CustomerName#).

LF 

**Describe the bug**

When trying to update the footer widget, it is not saving after selecting 'Publish'. Just spins.

**To Reproduce**
1. Go to 'Customize'
2. Click on 'Widgets'
3. Click on 'Footer'
4. Modify and select 'Publish'
5. See error

**Expected behavior**

Widget saves

**Screenshots**
![Screenshot 2022-12-23 at 18-55-34 Customize Local government digital solutions - ProudCity](https://user-images.githubusercontent.com/1569463/209418947-5887721b-1f91-43ba-9459-92181faff1cf.png)

**Comment by kevindherman** [comment]
@curtismchale @lukefretwell this happens when adding a new "navigation menu" to the footer customization. @curtismchale I'm not sure where else the "navigation menu" is used so it might not have been considered with the quick menu update.

**Comment by curtismchale** [comment]
Now that I've looked at this it seems to save fine. It's possible that one of the plugin updates in the last bit resolved the PHP error that was likely stopping the JSON response in the AJAX call from returning properly.

When something is "stuck" spinning without completing the save process, an improper JSON response is usually the culprit. The most likely thing that causes it is a PHP debugging error being thrown somewhere.
