### ISSUE TITLE
Gravity Forms UI review (or default to 'Enable legacy mark-up')

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2162]
## Builds

- [staging](https://console.cloud.google.com/cloud-build/builds;region=global/d8e527b5-d1d1-4e72-a83f-f37c782aa098?project=proudcity-1184)
- [master](https://console.cloud.google.com/cloud-build/builds;region=global/1f63225e-19af-41be-89f8-2a0a03e69afb?project=proudcity-1184)

**Source**

LF

**Related**

https://github.com/proudcity/wp-proudcity/issues/2399

**Describe the bug**

Gravity Forms upgrade is causing UI issues. 

To-do:

- [ ] Test Gravity Forms on blank non-ProudCity Theme site

Next steps:

* If UI issues are related to Gravity Forms, then 'Enable legacy mark-up' short-term.
* Then we update our Bootstrap code.

**Screenshot**
![Screenshot 2023-01-05 at 12-41-38 Forms ‹ ProudCity — WordPress](https://user-images.githubusercontent.com/1569463/210876737-103e8aaf-23ed-49a9-ac53-dfcec86facbb.png)

## Current Build
Staging: https://console.cloud.google.com/cloud-build/builds;region=global/7fc3b769-7cf5-4202-b0a6-edaaecbdb728;tab=artifact?project=proudcity-1184

**Comment by curtismchale** [comment]
We can force enable Legacy markup with this filter: https://docs.gravityforms.com/gform_enable_legacy_markup/

**Comment by curtismchale** [comment]
@lukefretwell this is out on `test` sites now. Create a few forms and check.

**Comment by curtismchale** [comment]
Deployed with: https://github.com/proudcity/proud-recipes/releases/tag/2023.10.24.1330

**Comment by lukefretwell** [comment]
@curtismchale sorry, we discussed in passing on a dev call. I verified that it's not defaulting to legacy markup.

Source: https://proudcity.zendesk.com/agent/tickets/6811

**Comment by curtismchale** [comment]
Deployed:

Composer: https://github.com/proudcity/wp-proudcity/releases/tag/2024.03.07.1018
Builds: https://github.com/proudcity/proud-recipes/releases/tag/2024.03.07.1018
