### ISSUE TITLE
Add Sweep tool to all sites

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2170]
**Source**
LF

**Is your feature request related to a problem? Please describe.**
The 'Leave page' bug #2096 seems to be caused by number of revisions exceeding a certain limit. Using Sweep will help clear this issue if we're not able to find a better resolution.

**Describe the solution you'd like**

Would be great to have Sweep installed for all sites or be easily added via plugins/marketplace

**Describe alternatives you've considered**

Auto clear revisions after a certain number.

**Additional context**
N/A

**Comment by curtismchale** [comment]
@lukefretwell WP Sweep is on all sites, it's just not active. You can activate it from the plugins menu and then use it as needed on any site.
