### ISSUE TITLE
Service center admin main page not working?

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2172]
**Source**
The source of the issue.

LF

**Describe the bug**

* Not displaying on phone display
* Might need clean-up

**To Reproduce**
1. Go to 'Service center' > 'Service center' in admin
2. See issue

**Expected behavior**

It used to display in each of the display types. Now just an empty page.

**Screenshots**

![Screenshot 2023-01-05 at 15-25-53 Service Center ‹ ProudCity — WordPress](https://user-images.githubusercontent.com/1569463/212445214-3a971364-3244-46cc-80eb-837af6e7397c.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Suggest we delete this page or change it up to simplify. Not sure we need the interactive display.

**Comment by kevindherman** [comment]
@lukefretwell this appears to only be on proudcity.com.

**Comment by curtismchale** [comment]
We no longer have this page in the new WP dashboard.
