### ISSUE TITLE
Forms upgrade CSS issues

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2175]
**Source**
The source of the issue.

* LF
* https://proudcity.zendesk.com/agent/tickets/6247

**Describe the bug**

The new forms CSS seems off. 

Examples:

* Checkboxes display: When I start a new form, it displays the checkboxes to the right of the label on a new row.
* `gfield_description`: Removed `margin-bottom` spacing
* `fieldset` spacing: Needs more `margin-bottom`

New CSS:

```
/* Forms */

.ginput_container input, .ginput_container select, .ginput_container textarea {
display: inline;
width: auto;
}

.gform_wrapper .gfield_description {
	margin-bottom: 0;
}

.gfield, .gform_wrapper.gravity-theme fieldset {
	margin: 0 0 1.5rem 0;
}

```

When deselecting these CSS styles in inspector, it displays as intended.

The display also works fine for older forms or forms that have been copied from an older form where there's this message:

> This form has legacy markup enabled, which may prevent some new features from functioning.

**To Reproduce**

I'm seeing this for the ProudCity Academy form: 

https://proudcity.com/academy/

**Expected behavior**

Boxes to left of label (or way to edit that)

**Screenshots**

<img width="1144" alt="Screenshot 2023-01-17 at 1 09 32 PM" src="https://user-images.githubusercontent.com/1569463/213013615-95e348ad-f4d4-4c06-a061-f0b361529300.png">
<img width="1155" alt="Screenshot 2023-01-17 at 1 09 17 PM" src="https://user-images.githubusercontent.com/1569463/213013619-6254ca34-d94d-48a2-b92e-0ee3e4352575.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lukefretwell** [comment]
Note: I modified the custom settings on proudcity.com to override the current CSS, which is why it's now displaying correctly there.

**Comment by kevindherman** [comment]
@lukefretwell here's additional detail from the customer since they said it looks like the issue resolved and you mentioned in slack that it could be caching:

> Ah ok – last night I was working on my laptop and they were both goofy (I created two of them last night) and then this morning after we initially talked, one was fine and the other wasn’t. Now they both are. The only change I made was that I turned on the “legacy markup” button.

**Comment by kevindherman** [comment]
@lukefretwell @curtismchale is part of the CSS updates listed in the Gravity Forms 2.7.2 [Release Notes](https://www.gravityforms.com/blog/brand-new-release-gravity-forms-2-7-2/).
