### ISSUE TITLE
Update national holidays

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2176]
The default holidays can be set in code here https://github.com/proudcity/wp-proud-core/blob/master/proud-helpers.php#L478.

@curtismchale this needs to be updated at the beginning of the year for customers who use the default.

Individual sites can customize these holidays under Service Center > Holidays (https://beta.proudcity.com/wp-admin/admin.php?page=service-center-settings).  Once a city has customized the holidays, they will not automatically be updated when we change the code above (they'll need to update that field every year).

![Screenshot - 2023-01-17T130519 050](https://user-images.githubusercontent.com/6032426/213278547-1d5c5945-ad52-40bf-9c9b-f1f584355ee0.png)

**Comment by curtismchale** [comment]
@kevindherman check that the national holidays are proper.

https://github.com/proudcity/wp-proud-core/commit/faefd1266a1257e08c86d5dbe0416a97ef647b03

**Comment by kevindherman** [comment]
@curtismchale looks good.
