### ISSUE TITLE
Delete Disqus

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2178]
**Source**

LF

**Feedback**

We have Disqus installed on proudcity.com, but are not using it. I don't believe any customers are using it, and we don't promote it, so we should just remove this from the platform.

**Comment by curtismchale** [comment]
@lukefretwell this has been removed from the PC site. It was editing the `yaml` file for the deploy and when I save it the pod rebuilds without the custom plugin installed.

**Comment by lukefretwell** [comment]
@curtismchale this can still stay closed as there's another issue related to the admin bar, but I still see Disqus in the admin.

Related: #2110

**Comment by lukefretwell** [comment]
@curtismchale I still see this on help in the leftnav so opening this back up. My suggestion is to remove Disqus from all of ProudCity, as I don't think anyone is using it.

**Comment by curtismchale** [comment]
@lukefretwell where on the leftnav? Are you logged in as `info` or `support`?

**Comment by lukefretwell** [comment]
@curtismchale info
