### ISSUE TITLE
Google map api issue 

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2183]
**Source**
Lowell

* (https://proudcity.zendesk.com/agent/tickets/6253)

**Describe the bug**
When adding a new location (dashboard > locations > add new

**To Reproduce**
1. Go to dashboard
2. Click on locations
3. add new
4. Type in name of location alert block the google map autopopulate
![Screen Shot 2023-01-24 at 3 32 40 PM](https://user-images.githubusercontent.com/6032426/214403145-1dc6c213-5819-43cd-b112-664b08583118.png)

**Expected behavior**
If you do the same thing on another customer site it's fine.
https://madeirabeachfl.gov/wp-admin/post-new.php?post_type=proud_location
![Screen Shot 2023-01-24 at 3 34 20 PM](https://user-images.githubusercontent.com/6032426/214403480-d5c10db3-2bb9-4f71-b5e8-f8c673fb3cd9.png)

**Additional context**
I checked Lowell's google api in the site settings and it appears to be correct but @curtismchale maybe it's off in console in the launch prep steps.

**Comment by curtismchale** [comment]
@kevindherman there domain wasn't allowed on our API key calls. I added their domain here: https://console.cloud.google.com/apis/credentials/key/6a91d1af-0c59-4054-8e5f-509881810590?project=small-production-sites

It seems to work now.

This is a step in the launch Trello card as well so not sure why the domain wasn't on here.

**Comment by kevindherman** [comment]
@curtismchale thank you. I looked at their launch card and it was checked off so I don't know either. Thanks for the fix.
