### ISSUE TITLE
Remove <strong> from sitename

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2188]
**Source**
The source of the issue (ex: Customer: #CustomerName#).

LF

**Feedback**

Not sure why we're using `strong` in the sitename, but suggest we remove and add to style sheet. This will allow us to better manage display on that but also change in custom settings.

<img width="1078" alt="Screenshot 2023-01-24 at 3 53 26 PM" src="https://user-images.githubusercontent.com/1569463/214447889-2f67a432-7810-4596-b63e-9c4d73ea91fe.png">

**Comment by curtismchale** [comment]
@lukefretwell this was deployed via the following commits:

Core plugin bump: https://github.com/proudcity/wp-proudcity/commit/9d356158e5f790e1ea6820c612842c318c82c0b4
Removed strong tag from nav bar: https://github.com/proudcity/wp-proud-core/commit/ef4ac31769d8f3148c9cb99d60b82b4f6a5422ac
New CSS on San Rafael theme: https://github.com/proudcity/wp-proud-sr-ca-theme/commit/bd44759983ee0317ac548e12bd2f3a54639eb45e
updated styles on Petaluma theme: https://github.com/proudcity/wp-proud-petaluma-ca-theme/commit/5b22e7a2256c40a874d92a6e0ca87fca84dd49e2
updated build file that was deployed: https://github.com/proudcity/proud-recipes/commit/e944ce63390a9cd4366cbce9c09d3478beb2d137
