### ISSUE TITLE
Replace Intiutive Custom Post Type Order

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2193]
**Source**
Curtis

Recently the plugin was [closed](https://wordpress.org/plugins/intuitive-custom-post-order/) on the wordpress.org repository. This is most likely due to a [security issue](https://wordpress.org/support/topic/wordfence-flagged-critical-security-issue-removed-from-wordpress/). WP won't say it's a security issue so that they don't leak possibly harmful information to hackers.

[See other security issue notes here](https://wpscan.com/plugin/intuitive-custom-post-order).

Someone created a [pull request to fix the problem on Github](https://github.com/hijiriworld/intuitive-custom-post-order/pull/48) but given the lack of response to previous pull requests and lack of updates at all from the author I find it unlikely that they'll update this.

There are two options.

1. Fix the issues as shown in the plugin. 

[This part of the problem](https://wpscan.com/vulnerability/8f900d37-6eee-4434-8b9b-d10cc4a9167c) can be fixed easily with a `current_user_can` check set to editor level (or whatever user level we want). [This part](https://wpscan.com/vulnerability/734064e3-afe9-4dfd-8d76-8a757cc94815) can be fixed by adding `nonce` checking to the ajax action.

This would mean we take the plugin over or fork it. I'd have to see if the Plugin team would give us access to the plugin or take our pull request.

I do note other security issues with the database queries that would need proper sanitization.

[There is a prescribed method for taking the plugin over if we wanted to follow that](https://developer.wordpress.org/plugins/wordpress-org/take-over-an-existing-plugin/).

2. Find another plugin(s) that does the same feature.

We tried [Post Types Order](https://en-ca.wordpress.org/plugins/post-types-order/) but it messes with our standard queries and stops the ability to change `ASC` and `DESC` queries as well as some of our other sorting features. It also doesn't do taxonomies to change their `term_order`. They have a `term_order` plugin as well, but given the issues with the version above I'm doubtful this is the right option.

**Comment by curtismchale** [comment]
@kevindherman @lukefretwell The plugin dev updated the plugin with the security fixes in place. It's not released on wordpress.org yet as a revised plugin so I've forked it with the security fixes in place and I'm pushing it out to test again on beta.

The things to test would be that our Editors (most of our users) can still order posts as they expect.

**Comment by kevindherman** [comment]
@curtismchale I'm not seeing ordering options for posts or custom content types on BETA. Am I missing something?

**Comment by curtismchale** [comment]
Secured version pushed with this deploy: https://github.com/proudcity/proud-recipes/releases/tag/2023.02.08.1049
