### ISSUE TITLE
Can't create new content categories (documents, events, etc.)

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2194]
**Source**

Platform
Added: https://proudcity.zendesk.com/agent/tickets/6277

**Describe the bug**
You can't create a new category or type for different types of content such as documents, events, news, etc. 

**To Reproduce**
1. Go to document types https://cityofnewbuffalo.org/wp-admin/edit-tags.php?taxonomy=document_taxonomy&post_type=document
2. Add new
Wheel keeps spinning. 

**Expected behavior**
A new document type or category should be created. 

**Screenshots**
Loading wheel keeps spinning
<img width="1247" alt="Screen Shot 2023-02-02 at 3 01 43 PM" src="https://user-images.githubusercontent.com/6032426/216437899-eb5d240a-e9c7-4b57-8ba0-b89b566f767e.png">

**Additional context**
@curtismchale this came up after making sorting edits yesterday.

**Comment by kevindherman** [comment]
@curtismchale @lukefretwell I've updated this issue with a ticket we received in not being able to create document categories. This will factor into priority conversations.

**Comment by curtismchale** [comment]
@kevindherman I took a second to look at this and the fix was quick. It's deploying to BETA now and in my local testing also resolves the media issue from https://github.com/proudcity/wp-proudcity/issues/2195

Give it a test and I *might* be able to deploy today to live sites.

**Comment by kevindherman** [comment]
@curtismchale this worked for me as well.
