### ISSUE TITLE
Adding new folder to media library bug

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2195]
**Source**

[* [LINK TO TICKET]](https://proudcity.zendesk.com/agent/tickets/6274)

**Describe the bug**
There currently appears to be an issue with creating new folders in the media library. I have attached two images. The first image shows the attempt to create a folder. The seconds shows that after I select the Create button, the folder does not get created and there is a small message box in the upper right corner that says "Adding folder..." but the folder never gets added. After experiencing this, I attempted to create a folder in a different place and experienced the same result. I also searched through the other departments' folders to see if it got put into a different location than the one I'm in- which does occasionally happen when I upload a media file. I also cleared the cache, logged out, closed my browser, logged back in, and the same result after I attempted it again.

**To Reproduce**
1. Go to the media library
2. Click on add new folder
3. The screen prompts adding new folder (top right) but nothing happens

**Expected behavior**
New folder is created.

**Screenshots**

![Folder-add-1](https://user-images.githubusercontent.com/6032426/216439988-b394d913-f397-44a5-bebc-41eed15e1265.jpeg)
![Folder-add-2](https://user-images.githubusercontent.com/6032426/216439989-5ce5328a-34f9-4420-b01f-e03205e59a8b.jpeg)

**Comment by kevindherman** [comment]
@curtismchale could this be related to configurations here: https://github.com/proudcity/wp-proudcity/issues/2192

**Comment by curtismchale** [comment]
@kevindherman see https://github.com/proudcity/wp-proudcity/issues/2194 for what fixes this.
