### ISSUE TITLE
Update site icon text in site identity tool

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2198]
**Source**
The source of the issue (ex: Customer: #CustomerName#).

LF

**Is your feature request related to a problem? Please describe.**

N/A

**What feature would you like to improve**
A clear and concise description of the current feature.

The site icon section would be great to clean up a little.

**Describe the solution you'd like**

Text change recommendation:

```
Site icon

Site icons, or [favicons](https://help.proudcity.com/favicons-and-local-government-websites/), are what you see in browser tabs, bookmark bars, and within the WordPress mobile apps. Site icons should be square and at least 512 × 512 pixels.
```

**Additional context**

N/A

**Comment by curtismchale** [comment]
At this point I don't see a filter to just change the text. I'll need to remove the control and then add it again (with the same data save points) with our text: https://stackoverflow.com/questions/37953058/how-do-i-remove-the-ability-to-change-the-site-icon-in-wordpress

**Comment by curtismchale** [comment]
@lukefretwell this has been deployed to BETA for testing.

Staging Build: https://console.cloud.google.com/cloud-build/builds;region=global/4bb4ab21-91fb-4b97-9fa8-502b409d43d6;tab=artifact?project=proudcity-1184

**Comment by lukefretwell** [comment]
@curtismchale this looks great. Thank you.
