### ISSUE TITLE
Job list table view not displaying the right fields

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2199]
**Source**

[* [LINK TO TICKET]](https://proudcity.zendesk.com/agent/tickets/6291)

**Describe the bug**
The published table display shows "position" and "phone" columns, but when I'm creating a new job, I don't see anywhere to name the position or list a phone number. Am I missing something?

Example job listing: https://www.cityofsanrafael.org/job/help-a-city-department/

Displayed jobs widget: https://www.cityofsanrafael.org/?page_id=76392&preview=true
Link to page with this issue
https://www.cityofsanrafael.org/?page_id=76392&preview=true

I also tested this on BETA, scroll to the bottom of the widget test page and there is an additional message about the jobs version been outdated: https://beta.proudcity.com/test-new-menu-and-widgets/
<img width="1021" alt="Screen Shot 2023-02-09 at 2 25 34 PM" src="https://user-images.githubusercontent.com/6032426/217916840-8387a9ff-87ed-4a41-862d-178fd43cd4ff.png">

**Additional context**
The example from beta seems to give a hint that we need to update the plugin and then it'll hopefully snap into place.

**Comment by curtismchale** [comment]
@kevindherman it doesn't show any place to add the phone number and position because it's pulling that information from the Contacts entered under the Contact custom post type.

I also don't see a way to set the contact so that the data would get pulled in the UI nor do I see how it would show up in the code. So how do we want this to work? Should a user just be able to put in any Phone number to contact for the position?

Is the position name for the job in question, or for the person to contact (this is what it currently would be doing).

On the "old" functions. I've got those fixed and will push a build to Beta shortly.

**Comment by kevindherman** [comment]
@curtismchale I'll review the "old functions" on beta when they're ready and then answer the table view question. I think those columns are new/inadvertent from the bug. I forget what the columns were before, is there a way to look in past logs to see what the table view in the job list widget used to display? What that was is the goal.

**Comment by curtismchale** [comment]
@kevindherman You can see all the changes made in 8 years for this file here: https://github.com/proudcity/wp-proud-core/blame/master/modules/proud-teasers/templates/teaser-table.php

Alex added the meta calls to the Staff List plugin 8 years ago and then I labelled the template with an HTML comment a while ago so templates are easier to find.

It has always called those two parameters.

The table headers themselves have a similar history found here: https://github.com/proudcity/wp-proud-theme/blame/master/templates/teaser-items/teaser-job_listing-table-header.php

As far as I can tell this information was always being called as it is being called now.

Going forward, how do we want to populate that information? We can add fields to an individual job listing that then get displayed on the frontend of the site in the table if we want.

**Comment by kevindherman** [comment]
I think your suggestion is simpler and better: add fields that people enter directly into individual job listings. @curtismchale

**Comment by curtismchale** [comment]
@kevindherman I took a shot at this with some time today. We now have the position and phone fields in the admin.

I do wonder about the text/language we use to describe the fields though. It was originally the position of the person to contact, which field odd to me. I changed it to the position of the job...which may not be right. It's a simple set of text changes to get it to say whatever you want.

See it on beta here: https://beta.proudcity.com/test-new-menu-and-widgets/

<img width="1122" alt="CleanShot 2023-02-17 at 13 46 05@2x" src="https://user-images.githubusercontent.com/74561/219800055-4788b273-cb25-4f77-a9cc-b99112ac9721.png">

**Comment by kevindherman** [comment]
@curtismchale that is odd. 

What if it just displays the label (part time, full time, volunteer, etc.) which still makes sense for "Job position.

Otherwise this looks good to me.

**Comment by curtismchale** [comment]
@kevindherman here is the revised look of the table. I removed the field for Job Position in the admin area as we're not using it now. I'll be pushing this to Beta today.

<img width="1181" alt="CleanShot 2023-02-20 at 08 06 01@2x" src="https://user-images.githubusercontent.com/74561/220154558-4b5adcc2-fed8-4f38-8d9a-368fc4bb14de.png">

**Comment by kevindherman** [comment]
@curtismchale this looks great.

**Comment by kevindherman** [comment]
@curtismchale testing looks good. Good to go from me.

**Comment by curtismchale** [comment]
Deployed with: https://github.com/proudcity/proud-recipes/releases/tag/2023.02.20.1212
