### ISSUE TITLE
MARKETING: Make footer behave like homepage header

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#220]

**Comment by jlyon** [comment]
@lukefretwell I'm not going to get to this before i take off, but I'll take care of it first thing next week. Maybe we can see how the two forms compare..

**Comment by aschmoe** [comment]
@jlyon is this the same work I did last week?

**Comment by jlyon** [comment]
@lukefretwell set this up.

I also tweaked the analytics reporting and added an overview to the header of `/var/www/proudcity/wp-content/plugins/proudcity-custom/assets/scripts/script.js` @aschmoe
