### ISSUE TITLE
Community Development Page breaking out of template

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2203]
## Source

See @kevindherman original report here: https://github.com/proudcity/wp-proudcity/issues/2190#issuecomment-1421389279

## Describe the bug
At the following URL: https://madeirabeachfl.gov/community-development-documents/

View the template and see that it breaks out of the flow of the page.

![](https://user-images.githubusercontent.com/6032426/217355819-3c0e405d-375b-4ff4-b5ff-cd6b8dfa4e44.png)

In order to view the edit page you have to go through the dashboard: dashboard > pages > find the page > edit
Pages, the item shows site origin/pagebuilder: https://madeirabeachfl.gov/wp-admin/edit.php?s=development+documents&post_status=all&post_type=page&action=-1&m=0&seo_filter&readability_filter&paged=1&action2=-1

![](https://user-images.githubusercontent.com/6032426/217355650-2ea12834-05db-4726-bc77-da1611669825.png)

## Expected behavior
Content should **not** break out of page.

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment]
Fixed with this tag: https://github.com/proudcity/wp-proudcity/releases/tag/2023.02.14.1300

**Comment by curtismchale** [comment]
@kevindherman the issue was with the Icon Set widget. Similar to other recent errors, PHP 8 is more strict than PHP 7.4 was. I added a check to make sure that the variable was present in the page content before I tried to use it.

You can see the Icon Set working at the bottom of the demo page: https://beta.proudcity.com/test-new-menu-and-widgets/

**Comment by kevindherman** [comment]
@curtismchale interesting. Why would some icon sets work and others break the theme?

This does work for me if you want to push the fix or push it to Madeira Beach to see if it fixes it.
