### ISSUE TITLE
Analytics dashboard not showing data

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2205]
## Source

LF

## Describe the bug

Looks like analytics data may not be pulling into the dashboard in the admin.

The main dashboard analytics page is pulling the data, however.  

## To reproduce
1. Go to leftnav 'Dashboard'
2. Click on 'Analytics
3. See error

## Expected behavior

Data from Google Analytics would show.

## Screenshots

![Screenshot 2023-02-17 at 11-44-25 Analytics ‹ City of Santa Ana — WordPress](https://user-images.githubusercontent.com/1569463/219817151-01ef1d1e-00e4-4a8c-84d2-b406fc3c285f.png)

## QA

Notes:

* 

Links:

*

**Comment by kevindherman** [comment]
This is specifically the embedded dashboard on a website, my.proudcity.com dashboard is behaving as expected.

@curtismchale would PHP8 block that view?

**Comment by lukefretwell** [comment]
Ideally, there would be only one location for this (in the CMS part of the admin). Not a big deal right now, but something we need to consider when looking at the MyProudCity dashboard.

**Comment by curtismchale** [comment]
@lukefretwell @kevindherman no PHP 8 is likely not the culprit.

What user were you logged in as (info/support) because logged in as info on De Leon (and I spot checked a few other sites) I see the Analytics on the site.

What browser were you using?

**Comment by kevindherman** [comment]
Jeff mentioned it could be an add blocker.

**Comment by curtismchale** [comment]
@lukefretwell closing this as we're dropping analytics with the new PC Dashboard
