### ISSUE TITLE
Feb 20 Plugin/Theme/Core Update

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2208]
**Plugins**
- Gravity Forms 2.6.9 -> 2.7.1.1
- Gravity Forms MailChimp 5.1 -> 5.2
- Popup Maker 1.17.1 -> 1.18.0
- WP Media Folder 5.5.3 -> 5.5.4

## QA

**Gravity Forms**
Find the [release notes](https://docs.gravityforms.com/gravityforms-change-log/). Nothing jumps out to me from 2.7 or 2.7.1 as areas of concern. I do note that they "fixed" an issue with JavaScript naming conflicts. This may/may not impact our JS issues. 

- [x] CM: test minify/combine again to see if these settings are now fixed in WP Rocket

**Gravity Forms MailChimp**
See [release notes](https://docs.gravityforms.com/mailchimp-change-log/#5-2-2023-02-15). Nothing jumps out at me initially as areas of concern.

**Popup Maker**
[Release notes](https://wordpress.org/plugins/popup-maker/#developers). The only possible issue I see is that they tweaked their Font Awesome 6 setup and we should check to make sure we have no conflicts.

- [x] CM: they updated Font Awesome 6 so check that everything is working right with FA still

**WP Media Folder**
[Release notes](https://www.joomunited.com/changelog/wp-media-folder-changelog). Nothing should impact us.

**Comment by kevindherman** [comment]
@curtismchale I had to activate the media folder manager plugin to take a look. Not sure if it wasn't activated before or if the update deactivated it but worth noting.

**Comment by curtismchale** [comment]
@kevindherman I end up deactivating things in Beta sometimes for testing. I doubt that it was deactivated by the update and it was probably me at some point testing if it was the issue with some media gallery thing.

**Comment by curtismchale** [comment]
Tested combine again and it still **creates issues** so we'll be leaving that off.

Created [new popup test page](https://beta.proudcity.com/popup-test-page/) and added an FA 6 icon. Seems to work fine and our icons still show without issue.

**Comment by kevindherman** [comment]
@curtismchale sounds good on all fronts.

**Comment by curtismchale** [comment]
Deployed with: https://github.com/proudcity/proud-recipes/releases/tag/2023.02.20.1212
