### ISSUE TITLE
Accordions not working on pages with textmygov widget

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2209]
## Source

* https://proudcity.zendesk.com/agent/tickets/6305

## Describe the bug

On pages with the textmygov widget, looks like accordion open but don't show the text information.

Exampe: https://cityofpalmview.com/solid-waste-faqs/

## To reproduce
1. Go to https://cityofpalmview.com/solid-waste-faqs/
2. Click on any accordion
3. See error

## Expected behavior

Accordions would work.

## QA

Notes:

* 

Links:

*

**Comment by kevindherman** [comment]
thank you both, this is super helpful @curtismchale @lukefretwell .

I have passed along the detail and will close the issue as suggested.
