### ISSUE TITLE
2023.03.6 Plugin Update

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2215]
# Updated Plugins

- Gravity Forms 2.7.1.1 -> 2.7.2
- Intuitive Custom Post Type Order 3.1.3 -> 3.1.4.1
- Site Origin Panels 2.20.4 -> 2.20.5
- Post Expirator 2.8.3 -> 2.9.2
- SO Widgets Bundle 1.46.5 -> 1.46.6
- WordPress SEO 20.1 -> 20.2.1

**Gravity Forms 2.7.2**

[Release Notes](https://www.gravityforms.com/blog/brand-new-release-gravity-forms-2-7-2/).

Nothing looks major here.

**Intuitive Custom Post Type Order 3.1.4.1**

[Release Notes](https://wordpress.org/plugins/intuitive-custom-post-order/#developers).

Should just fix the security issues previously identified.

**Site Origin Panels 2.20.5**

[Release Notes](https://github.com/siteorigin/siteorigin-panels/releases).

No big changes here.

**Post Expirator 2.9.2**

[Release Notes](https://en-ca.wordpress.org/plugins/post-expirator/#developers).

No major changes that should affect us I can see.

**SO Widgets Bundle 1.46.6**

[Release Notes](https://github.com/siteorigin/so-widgets-bundle/releases).

No major changes just bug fixes.

**WordPress SEO 20.2.1**

[Release Notes for 20.2](https://developer.yoast.com/changelog/yoast-seo/20.2/).
[Release Notes for 20.2.1](https://developer.yoast.com/changelog/yoast-seo/20.2.1/)

 Nothing jumps out at me as a possible issue though I do note that `2.2.1` was a security fix which puts it higher priority to update this.

**Comment by kevindherman** [comment]
@curtismchale post type ordering looks good along with the other testing I've done.

@lukefretwell posted a concern with mailchimp hooking into GF. @curtismchale I'm not sure if that's plugin upgrade issue or using our standard account which is used on other sites to test here too. What do you think?

That's the only reason for pause ahead of the release.

**Comment by lukefretwell** [comment]
Getting this message when trying to sync MailChimp:

> Could not authenticate with Mailchimp.

**Comment by curtismchale** [comment]
deployed: https://github.com/proudcity/proud-recipes/releases/tag/2023.03.14.1131
