### ISSUE TITLE
Broken Link Checker 2.0

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2216]
Was originally part of #2215 but after a brief look, we need to make bigger decisions about using `2.0` of this plugin.

This is a big update and has a bunch of breaking changes including online services. The [support forum](https://wordpress.org/support/plugin/broken-link-checker/reviews/) is full of annoyed/angry posts about 2.0. 

I haven't looked deeply at this yet.

**Comment by curtismchale** [comment]
@kevindherman @lukefretwell 

Broken Link Checker 2.0 moves it's menu item to the top level of our WordPress menu. I can probably change this though.

![CleanShot 2023-03-08 at 11 09 41@2x](https://user-images.githubusercontent.com/74561/223815183-1d0888cd-7983-4416-b525-41df86d5ef06.png)

You can still use the "old" version if you want but it's buried down a menu.
<img width="382" alt="CleanShot 2023-03-08 at 11 10 26@2x" src="https://user-images.githubusercontent.com/74561/223815700-815ddae2-fb26-48d3-bdf0-f0ec629596cd.png">

I wonder how long this old functionality will be supported.

## Options

1. We could fork the "old" version and run it ourselves.

This puts more work on our plates so I don't love that idea. As long as no issues come up with the “old” version we forked though it could mean nothing more than forking it and installing it on the sites. Then we let it sit and do it’s job. We won’t get any development/free features via upgrades unless we start building them though.

2. Find other plugins that may do the same thing?

The [W3C link checker](https://validator.w3.org/checklink) has a [version we can download and run](https://github.com/w3c/link-checker). This means we could include it in a future dashboard though I’d have to look at what it would mean to our server costs and where exactly we’d run it. We may need a new type of server to run this for our customers.

[Google Search Console provides data on broken links](https://search.google.com/search-console/about) and [has an API](https://developers.google.com/webmaster-tools). I’m more keen on this than forking the old version. We could likely interface with the API via a plugin we write. I believe search console is only going to show you broken links on your site, not external links that are broken.

[Yoast SEO](https://yoast.com/wordpress/plugins/seo/) (WordPress SEO which we use) will automatically redirect/move links as you use your content. This is available in Premium which costs $99/site. We already have this feature with the Safe Redirect plugin, though it’s a manual feature in this case.

I looked around for other plugins and found some but they didn’t seem like good options for various reasons. Some were discontinued and used an “outside service” to scan your sites. Some were really SEO/Web services that wanted you to run their whole suite/dashboard for SEO purposes.

I’ve also reached out to some other devs I know to see if they are aware of other options we could use.

**Comment by lukefretwell** [comment]
@curtismchale agree that the W3C or Google options are better with the latter being a simpler option, though the external link check is an important consideration.

**Comment by curtismchale** [comment]
@kevindherman @lukefretwell then our path forward is likely to use the the “old” version which we’ll fork and put a redevelopment issue in for a new link checker.

**Comment by curtismchale** [comment]
Also came across this option recommended from a friend. We may be able to run this on deploy and generate a list of links that we display in the admin of the site. We may be able to have a customer run it on the server when they make some fixes to the links.

https://github.com/raviqqe/muffet

**Comment by kevindherman** [comment]
@curtismchale if the last one is a strong candidate and customer validation confirms the choice, I'm currently on a project with a repeat customer who gives strong feedback. So I can present the idea to them and do this on the side. 

@lukefretwell this would be with Williams County.

I'd only want to do this if this is strongly being considered otherwise I don't want to loop a customer to test something we're lukewarm on.

**Comment by curtismchale** [comment]
It also requires a cloud connection to use the new one.

![CleanShot 2023-07-06 at 12 50 42](https://github.com/proudcity/wp-proudcity/assets/74561/c362f701-9a8c-4078-87c4-e04efbe3bc1e)

**Comment by curtismchale** [comment]
Resolved for now by grabbing the "old" version and putting it on our GitHub so that it drops off the update notices.
