### ISSUE TITLE
Style gravityforms frontend

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#222]
General
- [x] Add max width to form
- [x] In general, make form look more like 
- [ ] create form with as many types as possible, test them on the frontend
- [ ] test fields sets
- [ ] look into pagebreaks: https://www.gravityhelp.com/documentation/article/page-break/

https://www.westcarrollton.org/payment-example/
see on backend: https://www.westcarrollton.org/wp-admin/admin.php?page=gf_edit_forms&id=5
- [x] Format credit card
- [x] date selects
- [ ] name fields inline

https://www.westcarrollton.org/building-permit-example/
see on backend: https://www.westcarrollton.org/wp-admin/post.php?post=3450&action=edit
- [x] address field
- [x] padding on list fields
- [ ] make number fields less wide than text fields?

Admin (in wp-proud-admin)
URL: https://www.westcarrollton.org/wp-admin/admin.php?page=gf_edit_forms&id=5
- [x] Edit field, `?` icon needs to be floated next to the field title

When these look good, let's apply them to WC as a hotfix.

**Comment by jlyon** [comment]
@kevindherman if you notice anything else that needs to be styled as you go through forms, add it here plz

**Comment by aschmoe** [comment]
- [ ] Make advanced table fields (address, list ect) work with responsive
