### ISSUE TITLE
Form upload with same file name showing previous entry 

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2224]
## Source
Corning
[* [LINK TO TICKET]](https://proudcity.zendesk.com/agent/tickets/6346)

## Describe the bug
Job Recruiting - we created a form for Lifeguards to apply for pool jobs online. We have a file upload option for the resume. It turns out, that if they name the pdf the same "resume.pdf" then the document we see is the original upload of that file name. Please look in our City of Corning webpage under Forms -> Employment Application Form - Seasonal Lifeguards -> and reference entry [#966](https://proudcity.zendesk.com/agent/tickets/966) and entry [#947](https://proudcity.zendesk.com/agent/tickets/947). Different dates of submission, different IP addresses, but document uploaded was named "resume.pdf" for both

## Additional context
@curtismchale This came up in the previous gravity forms so I wonder if it's the same thing as this closed issue: https://github.com/proudcity/wp-proudcity/issues/1974 

## QA

Notes:

* 

Links:

*

**Comment by kevindherman** [comment]
I was hoping to see something about this item in the release notes from the plugin update but I didn't see anthing.

Referencing: https://github.com/proudcity/wp-proudcity/issues/2215

Specifically Gravity Forms 2.7.2

[Release Notes](https://www.gravityforms.com/blog/brand-new-release-gravity-forms-2-7-2/).

**Comment by kevindherman** [comment]
@curtismchale is it still creating scrambled names in the submission?

**Comment by curtismchale** [comment]
@kevindherman we never rolled it out to every site. I did just manually change the setting Corning and it is now adding text before files so this issue should be resolved for them.

I can set the `cache busting` constant to `true` for all sites so that they all will have this fix in place, or we can roll it out as needed.

I'll set Corning up to have it done for them regardless of what else we do.

**Comment by kevindherman** [comment]
@curtismchale great. 

For now lets keep as a need be basis for all sites but I’d like to make a more standard decision to likely push this everywhere soon.

**Comment by curtismchale** [comment]
@kevindherman closing this and opening a specific issue to deal with the overall bug here: https://github.com/proudcity/wp-proudcity/issues/2232
