### ISSUE TITLE
Add instructions for login/out to stock wp-login.php page

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2235]
**Source**
CM, LF, KH

**Is your feature request related to a problem? Please describe.**
When a user is at the login/out screen that WP ships with we should give them instructions about heading to `my.proudcity.com` to deal with their account.

@lukefretwell @kevindherman do you want to provide some text for what this should say please.

**Comment by lukefretwell** [comment]
@curtismchale @kevindherman does this work?

Login:

`<a href="#">Login to MyProudCity.</a>`

Logout:

`<a href="#">Logout of MyProudCity.</a>`

**Comment by kevindherman** [comment]
If they are seeing the logout screen, it's probably because they've timed out and need to logout of my.proudcity.com and back in.

I'd make sure the language suggests or tells them to take those steps. @curtismchale @lukefretwell 

"If you're seeing this screen you have been logged out of your website. Please go to my.proudcity.com and log out and back in for best security practices." Or something like that.

**Comment by kevindherman** [comment]
@lukefretwell could you help spruce up that language? I think it would be helpful to get this added this week if it's an easy one. @curtismchale

**Comment by curtismchale** [comment]
@kevindherman how about this to start.

> You've been logged out of your WordPress site. To remedy this you need to return to my.proudcity.com and **logout**. Then log back in to my.proudcity.com and click "Manage Site"

**Comment by kevindherman** [comment]
@curtismchale thank you. Let's start there and can adjust the language if needed.

**Comment by curtismchale** [comment]
@kevindherman @lukefretwell how is this for the login screen if/when the user is presented with the default wordpress login? I've changed the text and removed the login form (via CSS so I can also bring it back easily if we need to login for some reason).

I did take into account Colma, which needs the default WP login experience. They get the default text since logging into `my.proudcity.com` wouldn't work for them and the login form is still displayed.

![CleanShot 2023-07-07 at 11 39 12](https://github.com/proudcity/wp-proudcity/assets/74561/776215b2-4ecb-4d1c-9bd7-621c4e358ec5)

**Comment by curtismchale** [comment]
Deployed to beta for testing: https://console.cloud.google.com/cloud-build/builds;region=global/78ed7956-773a-4269-8754-28a4e0c766d7;tab=artifact?project=proudcity-1184

**Comment by kevindherman** [comment]
@curtismchale @lukefretwell works for me.

**Comment by lukefretwell** [comment]
@curtismchale perfect. Thank you.

**Comment by curtismchale** [comment]
This has been migrated to the master branch and can be deployed with the next release.
