### ISSUE TITLE
Answers list accordion quickly closes

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2239]
Answers list widgets using the accordion display open but close shortly thereafter. They should stay expanded.

See onboarding faq section: https://proudcity.com/onboarding

After clicking on a question to view an answer it opens and then shut within a second. @curtismchale 

## Tasks

To be done once we verify that this doesn't come back with changes made a week or two ago. 

- [ ] grab proudcity.com `wp rocket` configuration and roll it out to everyone

**Comment by lukefretwell** [comment]
@curtismchale @kevindherman this works fine in Firefox, but seems to now be an issue in Chrome.

**Comment by lukefretwell** [comment]
Got feedback that someone using Firefox is having the issue. 🤦

**Comment by kevindherman** [comment]
@lukefretwell which site?

**Comment by lukefretwell** [comment]
@kevindherman looks like it's just proudcity.com (I also checked help.proudcity.com)

**Comment by kevindherman** [comment]
@lukefretwell yeah, it does seem isolated to those in FF. I just cleared the site cache to see if that moved the needle but no dice.

**Comment by lukefretwell** [comment]
@kevindherman I don't have the issue in Firefox, but do in Chrome. The person who reported it was using Firefox.

**Comment by kevindherman** [comment]
@lukefretwell @curtismchale I think the issue is for anonymous users. 

LF uses FF as his primary browser and was probably logged in when testing and had no issue then did in Chrome which is secondary. I had the opposite problem. I then checked https://proudcity.com/onboarding in incognito and had the error.

**Comment by lukefretwell** [comment]
Feedback:

`Windows 11. Tried it in Edge and Chrome - same result.`

**Comment by lukefretwell** [comment]
@curtismchale works for me on Mac OS in FF + Chrome.

**Comment by lukefretwell** [comment]
@curtismchale works for me on Windows 11, so I think we're good to close this once deployed to all sites.

**Comment by curtismchale** [comment]
Released: https://github.com/proudcity/proud-recipes/releases/tag/2023.05.18

**Comment by lukefretwell** [comment]
@curtismchale @kevindherman these pages (nav and accordions) work fine when I'm logged in to MyProudCity.

**Comment by lukefretwell** [comment]
@curtismchale @kevindherman closing as it seems to be resolved. Will re-open if it's still an issue.

**Comment by lukefretwell** [comment]
@curtismchale @kevindherman someone notified me that this doesn't open on PC/Chrome and it's not working for me on Mac/Firefox, so I re-opened and moved to to-do as a priority.

**Comment by curtismchale** [comment]
I've tested now in all macOS browsers I have available plus the browsers on my Linux machine and a 2nd macOS machine at my house and it all works for me. I did reboot the pod and flush the cache in WP Rocket.

**Comment by curtismchale** [comment]
The solution currently was to remove the `wp-content/cache` folder manually as WP Rocket tools to clear the cache didn't solve the issue.

At this moment I'd kind of expect the issue to happen again once WP Rocket has its way with caching.

**Comment by curtismchale** [comment]
Deployed with: https://github.com/proudcity/proud-recipes/releases/tag/2023.08.10.1455
