### ISSUE TITLE
Home page refinements

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#224]
Think we should tighten up the homepage with the following:

- [x] change search box text to 'How can we help you?' (can is more affirmative)
- [x] action box highlight color to #f1f1f1 (make it more subtle)
- [x] Add 'Services' or 'Government' heading above icons
- [x] unify the coloring of the icons/text/hover in actions box and bigger icons area
- [x] font size in big icons box could be smaller
- [x] there seems to be left/right padding on the 'News' and 'Events' sections so they don't align with the items on the rest of the page
- [x] change 'Recent news' and 'Upcoming events' to just 'News' and 'Events' to match nav
- [x] make heading links below 'News' and 'Events' h4 or bigger size
- [x] add 'Connect' heading about social wall (needs some context)
- [x] think the social icons and related info in the cards should be on top of the cards and the background should be all the same color (with white text/links)

**Comment by jlyon** [comment]
#216 might be relevant

**Comment by aschmoe** [comment]
@kevindherman @lukefretwell @jlyon Ok re: "unify the coloring of the icons/text/hover in actions box and bigger icons area"

please just choose one you like:

1: how we have it currently (icon buttons match highlight color)
![west carrollton 3](https://cloud.githubusercontent.com/assets/1634686/13794242/2c03ac94-eab8-11e5-9bee-8d3710d555a7.png)

2: match actions box (both match actions)
![west carrollton 4](https://cloud.githubusercontent.com/assets/1634686/13794285/5b9f2bfe-eab8-11e5-8122-f7f05cbf2c4f.png)

3: Icons as link color (leave actions box, ignore highlight)
![west carrollton 5](https://cloud.githubusercontent.com/assets/1634686/13794295/7830b6b6-eab8-11e5-8263-f9c9c86fc9cc.png)

4. Match both icon stlyes as link color
![west carrollton 6](https://cloud.githubusercontent.com/assets/1634686/13794356/a651eefc-eab8-11e5-97e3-4ad331b25615.png)

5. Match both as highlight
![west carrollton 7](https://cloud.githubusercontent.com/assets/1634686/13794404/c847d06c-eab8-11e5-8b1b-020e8fb920a8.png)

**Comment by aschmoe** [comment]
@lukefretwell 

Here are social cards modifications, look better?

1. how we have it

![west carrollton 9](https://cloud.githubusercontent.com/assets/1634686/13794518/76a264a6-eab9-11e5-91ac-0505896c17ee.png)
2. card title switched to top

![west carrollton 8](https://cloud.githubusercontent.com/assets/1634686/13794520/786c824e-eab9-11e5-8b64-a051dfa71180.png)

**Comment by lukefretwell** [comment]
Of the icons, #1 looks cleanest to me.

On the social media, top is better, but there's not the grounding it needs. I don't know, maybe the date/username need to be associated below in the content and the headers are just the social media channels. That might simplify the look and ground it more.

**Comment by kevindherman** [comment]
For the icons I was going back and forth between 1 and 2. I leaned towards #2 because the icons in the Actions box and below are consistent. I also thought that route made the highlight color stand out more as a highlight color since it's used more sparingly.

**Comment by jlyon** [comment]
@aschmoe I'm not going to make any homepage db tweaks during this release.
