### ISSUE TITLE
Hide Page Attributes by Default

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2241]
## Source

CM

## Describe the bug
Currently users see the Page Attributes metabox by default which often gets confused with the Menu Metabox.

We need to move Page Attributes to be hidden by default. We're **not** removing it as a supported feature of a post type, it should just default to hidden.

This code should do it: https://wordpress.stackexchange.com/a/145550

### Notes

Currently some users have this activated so there is a 2 step process.

Step 1: Remove `pageparentdiv` by accessing the user_meta setting for `metaboxhidden_page`. We can do this via `wp user list --field=ID` and piping that into `wp user meta update $userid metaboxhidden_page $value --format=json`

`wp user meta update`: https://developer.wordpress.org/cli/commands/user/meta/update/
`wp user list`: https://developer.wordpress.org/cli/commands/user/list/
json example formatting: https://github.com/proudcity/wp-proudcity/blob/master/updates/release-2023.01.31.sh

**Step 2**: Set default to **not** show the `pageparentdiv` with code like [this](https://wordpress.stackexchange.com/questions/145496/how-to-hide-and-not-to-remove-the-attributes-metabox/145550#145550):

```php
function hide_meta_box_attributes( $hidden, $screen) {

    $hidden[] = 'pageparentdiv';
    return $hidden;

} 
add_filter('hidden_meta_boxes', 'hide_meta_box_attributes', 10, 2);
```

## Release

- [ ] add following command to release file
```bash
wp user list --field=ID --format=ids --allow-root | xargs -0 --d ' ' -I % wp user meta update % metaboxhidden_page '["pageparentdiv", "revisionsdiv", "postcustom", "slugdiv", "authordiv"]' --format=json --allow-root
```

## QA

Notes:

* 

Links:

*

**Comment by kevindherman** [comment]
@curtismchale this should be closed, right?

**Comment by curtismchale** [comment]
@kevindherman yes
