### ISSUE TITLE
PHP error on quote page

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2244]
## Source

LF

## Describe the bug

Getting PHP errors on quote page: https://proudcity.com/quote/

## To reproduce
1. Go to https://proudcity.com/quote/
2. See error

## Expected behavior

No errors.

## Screenshots

![Screenshot 2023-04-28 at 11 37 50 AM](https://user-images.githubusercontent.com/1569463/235227805-b42c113f-53a2-4d45-8a1f-c00feb097578.png)

**Comment by curtismchale** [comment]
See slack conversation: https://proudcity.slack.com/archives/C0AH683JQ/p1682705957727909

**Comment by curtismchale** [comment]
Checking to make sure that `city` and `state` are set before we try and use the values.

See: https://github.com/proudcity/proudcity-custom/commit/c32acf11a4e580d3ea8da213710028706f1a54dc

**Comment by lukefretwell** [comment]
Thank you @curtismchale!
