### ISSUE TITLE
May 16 2023 Updates

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2248]
**WordPress 6.2 -> 6.2.1 - [release notes](https://wordpress.org/news/2023/05/wordpress-6-2-1-maintenance-security-release/)**
- the issue around embed detection is one that likely applies to us as we use oembeds for videos being added to the site. There should be no impact on functionality of the site though once we update.

**Classic Editor 1.6.2 -> 1.6.3 - [release notes](https://wordpress.org/plugins/classic-editor/#developers)**
- only minor updates that relate to things we don't use. This should have no impact on our sites.

**Default Featured Image 1.7.2.1 -> 1.7.3 - [release notes](https://wordpress.org/plugins/default-featured-image/#developers)**
- minor updates for older PHP versions that we don't use

**Gravity Forms 2.7.4 -> 2.7.6 - [release notes](https://docs.gravityforms.com/gravityforms-change-log/)**
- I don't see anything that should impact us

**Site Origin Panels 2.21.1 -> 2.22.1 - [release notes](https://wordpress.org/plugins/siteorigin-panels/#developers)**
- I don't see anything I feel impacts us

**SO Widgets Bundle 1.49.1 -> 1.50.0 [release notes](https://wordpress.org/plugins/so-widgets-bundle/#developers)**
- should confirm that embedded YouTube videos with this widget continue to work as expected

**WP Job Manager 1.39.0 -> 1.40.1 - [release notes](https://wordpress.org/plugins/wp-job-manager/#developers)**
- I don't see anything here I believe impacts things we use

**WP Rocket 3.13.1 -> 3.13.2 - [release notes](https://wp-rocket.me/changelog/)**
- should check that YouTube thumbnails still work as expected since they've changed the way the image is delivered via the cache

**WordPress SEO 20.6 -> 20.7 - [release notes](https://wordpress.org/plugins/wordpress-seo/#developers)**
- none of the updates should affect us

**Comment by kevindherman** [comment]
@curtismchale the only thing I picked up on is in gravity forms and it may be a separate issue:

Description text overlaps the bottom of the field weirdly and checkbox formatting is off, see test form page: 
https://beta.proudcity.com/form-test/

Description text:
<img width="598" alt="Screen Shot 2023-05-17 at 11 04 07 AM" src="https://github.com/proudcity/wp-proudcity/assets/6032426/7a4b5bda-63e4-4c8c-8be2-905e4ac37405">


Checkboxes:
<img width="581" alt="Screen Shot 2023-05-17 at 11 03 56 AM" src="https://github.com/proudcity/wp-proudcity/assets/6032426/02de663b-b0c3-4647-9ee3-b8c80d07677b">

**Comment by curtismchale** [comment]
@kevindherman yes that looks like it matches this one: https://github.com/proudcity/wp-proudcity/issues/2246

**Comment by kevindherman** [comment]
Duh, thank you @curtismchale. If that could be included, great. If it's a larger thing, we can keep as separate.

**Comment by curtismchale** [comment]
Released: https://github.com/proudcity/proud-recipes/releases/tag/2023.05.18
