### ISSUE TITLE
WATCH: Gravity forms widget in pagebuilder breaks page when using advanced field

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#225]
Related: https://siteorigin.com/thread/issue-with-page-builder-gravity-forms-pagination/

**Comment by aschmoe** [comment]
Spent like 2 hours trying to figure out wtf was happening, no real progress except for realizing that using the short code instead of their widget fixed the bug.

see #226

**Comment by jlyon** [comment]
Huh wtf, just make a widget ourselves that uses do_shortcode() to see if
that fixes it?
