### ISSUE TITLE
Remove chat

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2250]
**Source**

LF/KH

**Is your feature request related to a problem? Please describe.**

N/A

**What feature would you like to improve**

Remove chat from admin.

**Describe the solution you'd like**

Remove chat in these locations:

- [x] MyProudCity sites dashboard: https://github.com/proudcity/proudcity-dashboard/commit/fa484ec68ab4455b5e8d9ee28fbe7f07514948b7
  - waiting for J/A to deploy
- [x] 'Live chat' link in 'Help' dropdown in top admin navbar - https://github.com/proudcity/proudcity-dashboard/commit/71ca230cab2d375c0085fda30ce8746f9b48883d
  - J/A need to deploy this to my.proudcity.com
  - Jeff finished fully removing it: https://github.com/proudcity/proudcity-dashboard/commit/f92db3b7c03ba6217f48357cc57f57482b2ff610
- [x] 'Live chat' link in 'Help' dropdown in top menu on main dashboard page (for each site) - https://github.com/proudcity/wp-proud-admin/commit/e01884926f692b613c074472771086ba4f44eb7a
  - tag: https://github.com/proudcity/wp-proud-admin/releases/tag/2023.06.22.1329

**Comment by curtismchale** [comment]
@lukefretwell I'm waiting on Jeff/Alex to deploy the changes to my.proudcity.com as I've not done that.

I'm doing a build now to remove the link in the dropdown in WP on each site.

The only question I have is where specifically the first item is located. Can you send me a screenshot/link so I can look at removing that as well

**Comment by curtismchale** [comment]
My item for WP sites was deployed live and staging: https://github.com/proudcity/proud-recipes/releases/tag/2023.06.22.1655

**Comment by curtismchale** [comment]
@lukefretwell there should be no live chat options anymore.
