### ISSUE TITLE
Deprecate old analytics dashboard, related fields in settings/integration, marketplace

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2261]
**Builds**
- [staging](https://console.cloud.google.com/cloud-build/builds;region=global/02174130-93be-449f-a881-f9d5de61b6bc?project=proudcity-1184)
- [prod](https://console.cloud.google.com/cloud-build/builds;region=global/2bf35984-f859-40c8-a2fc-8b9d841ed565?project=proudcity-1184)

## Source
The source of the issue (ex: Customer: #CustomerName#).

PC

- [ ] remove link to analytics dashboard in my.proudcity.com
  -  maybe we should redirect that to start and provide information to customers about it being gone in case they use it
 
![CleanShot 2023-12-12 at 09 49 45](https://github.com/proudcity/wp-proudcity/assets/74561/25f6b7d9-02c4-41dd-b7b1-6628c6914b29)

## QA

Notes:

* 

Links:

*

**Edited**
CM - 2023.05.26
- included checklist of tasks that will need to be done

**Comment by curtismchale** [comment]
@jlyon will take care of the main heading item but I need to remove the WP Admin Menu item and then get back to him so that he removes all the code that produces the page.

**Comment by curtismchale** [comment]
Deployed

Composer: https://github.com/proudcity/wp-proudcity/releases/tag/2024.01.03.1010
Build: https://github.com/proudcity/proud-recipes/releases/tag/2024.01.03.1010
