### ISSUE TITLE
Refine EXAMPLE

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#227]
Think we need to refine the example site and align it more with the process.

Thoughts:

- [x] change EXAMPLE to DEMO
- [x] change 'Get started with ProudCity Claim your city' to just 'Get your free BETA" button
- [x] add PC social media to social wall @aschmoe 
* extend height of DEMO bar

**Comment by jlyon** [comment]
maybe not height

**Comment by jlyon** [comment]
Leaving out height for now.  Pushed the first two items as hotfix 1.1.6.
