### ISSUE TITLE
Deleted event still displays in calendar widget

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2277]
## Sonoma

* [[LINK TO TICKET]](https://proudcity.zendesk.com/agent/tickets/6484)

## Describe the bug
Event was successfully deleted but it still shows in calendar widget

## To reproduce
1. Go to https://www.sonomacity.org/calendar
2. See July 5th city council meeting (cannot click on it because it doesn't actually exist)
3. Does not exist in backend

## Expected behavior
The event label should not display in the calendar widget. When you add the event list widget to the page, it does not display the the July 5 city council meeting. 

## Screenshots
<img width="1045" alt="Screen Shot 2023-06-14 at 2 33 28 PM" src="https://github.com/proudcity/wp-proudcity/assets/6032426/dc765337-21f9-4d2a-868f-962119ae173c">

## Additional context
This specific July 5 council meeting event was part of a recurring event thread. The specific July 5 event was deleted. I'm not sure if the label is stuck in the calendar view because it was recurring or not but worth noting. 

Database at current state available here: https://drive.google.com/file/d/1baXbohWSgCl0qSUwRBc0uPkJ1NQLskTr/view?usp=drive_link

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment]
The issue is that we have orphaned data in the `wp_em_events` table. So the Custom Post entry was removed but the metadata that Events Manager uses is still there, thus it thinks the event is still there.

We need to run a custom SQL query to remove the entry. Discussions are in progress about the best way to do this as it's currently undocumented.

**Comment by curtismchale** [comment]
Done and documented the process for future: https://github.com/proudcity/developers/blob/main/ProudCity%20Developers/How%20To/Fix%20Orphaned%20Events%20in%20Events%20Manager.md
