### ISSUE TITLE
DEMO: Forms permission

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#228]
@aschmoe Massachusetts is reporting that they don't have permissions to access the forms feature.

Could you address this first thing today?

![forms permission screenshot](https://cloud.githubusercontent.com/assets/6032426/13705325/4d4731a2-e76e-11e5-807d-0c7654439b4c.png)

**Comment by aschmoe** [comment]
This was because in the last release gravity forms failed to git enabled for some reason.  Appears as if a fix was not completed.

Fixed on Massachusetts, will fix the other Demos today.

**Comment by aschmoe** [comment]
@kevindherman @jlyon @lukefretwell

**Comment by kevindherman** [comment]
Got it.

Thank you.
