### ISSUE TITLE
New or edited events stuck in DRAFT [BUG]

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2297]
## Source
Holyoke
Oakwood

* https://proudcity.zendesk.com/agent/tickets/6503 
* https://proudcity.zendesk.com/agent/tickets/6504

## Describe the bug

When I attempt to create a new event, or even edit an existing event, after clicking the publish or update button, the event is appearing as a draft rather than as a published event. The issue appears to only be impacting the posting of events. I was able to post a meeting and a new post this morning with no issue.

With the 2 images, the first shows an event that was previously published but after I went in to edit some of the information, it became a draft after I clicked update. The second image shows a new event I created today and remains as a draft after I clicked publish. In both instances, when I click the edit option next to the status label in the publish box, the drop down box only shows "pending review" and "draft" options. As an additional detail, while I was typing out this bug report, another employee called me to let me know she was also having the same issue.

## Expected behavior
Can publish new or editing events from event detail. 

## Screenshots
![Event-bug-1](https://github.com/proudcity/wp-proudcity/assets/6032426/efdfdbfb-466a-4b2c-a649-3945bc8577a7)
![Event-bug-2](https://github.com/proudcity/wp-proudcity/assets/6032426/310bb148-c8ee-4f29-a76e-7f321f9602a3)

## Additional context

You can work around to publish the event from the full event list quick edit option. 
Also, I noticed several of the draft events had a start date of 1970 which seemed odd: https://www.holyoke.org/wp-admin/edit.php?post_type=event

I'm not sure if that's related but could be a clue or just something to cleanup.

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment]
Something seems to have been corrupted with the latest update in the user capabilities. User capabilities are shown in the [plugin settings page](https://www.effinghamil.com/wp-admin/edit.php?post_type=event&page=events-manager-options#general). Once you visit this page and save it the permissions are fixed.

Kevin and Curtis went through each site saving these settings to reset the permissions.
