### ISSUE TITLE
PILOT: department menu option not on add new page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#230]
When adding a new page to a department, the select Dept Menu widget is no longer showing.

I think this happened with the latest update.

**Comment by kevindherman** [comment]
It's actually for all pages, not just adding new. This existing page doesn't have the menu option either: https://www.westcarrollton.org/wp-admin/post.php?post=2230&action=edit

There used to be a menu option on the right side.

![screenshot 2016-03-14 12 10 01](https://cloud.githubusercontent.com/assets/6032426/13750855/b270d81e-e9dd-11e5-877d-9a274e0f7bf6.png)

**Comment by jlyon** [comment]
wp-quick-menu wasn't in package.json, so it got disabled after the last update.  I re-added this as hotfix 1.1.2 across the whole platform.  This box now appears on https://www.westcarrollton.org/wp-admin/post.php?post=2230&action=edit again @kevindherman.
