### ISSUE TITLE
Location content not displaying address or contact info [BUG]

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2307]
**Builds**
- [staging](https://console.cloud.google.com/cloud-build/builds;region=global/345e8b07-13f6-4643-869d-20f9856f3f8e?project=proudcity-1184)
- [master](https://console.cloud.google.com/cloud-build/builds;region=global/0ff155e2-8b15-4cf5-8e25-8db24b173df1?project=proudcity-1184)

## Williams County

* [Ticket](https://proudcity.zendesk.com/agent/tickets/6519)

## Describe the bug
Location content not display address (location) information, only featured image. 

The location pages are only coming up with their feature image and not the actual location information. For one of our facilities, the location page is getting picked up in search results and then essentially leading the user to a page with a picture.
Link to page with this issue
https://www.williamsnd.com/locations/northwest-youth-assessment-center/

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment]
@lukefretwell @kevindherman this file has never displayed the address data as far as I can tell from the [history](https://github.com/proudcity/wp-proud-theme/commits/master/templates/content-single-location.php). 

I'll get the address in there along with map and get it marked up with the proper schema so it's read properly as an address.

**Comment by curtismchale** [comment]
@lukefretwell I've added address information to the locations now which you can see here: https://beta.proudcity.com/locations/freitas-las-gallinas-intersection-improvements/

I'd like to push this live today.

**Comment by curtismchale** [comment]
Deployed

Build: https://github.com/proudcity/proud-recipes/releases/tag/2023.12.21.0939
Composer: https://github.com/proudcity/wp-proudcity/releases/tag/2023.12.21.0939
