### ISSUE TITLE
Verify we're using MySQL 8x

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2308]
**Source**
CM

MySQL 5.7 looses support in Oct and we need to check which version we currently use and make a plan to upgrade.
https://wpengine.com/blog/preparing-for-mysql-8-0/

**Comment by jlyon** [comment]
Steps:
- Duplicate test database
- On duplicate db: Upgrade Mysql version (click upgrade button on https://console.cloud.google.com/sql/instances/proudcity-dev/edit?authuser=1&project=proudcity-1184)
- Update beta clone config to use ip of new Mysql database
- Test beta
- Update Mysql version on original test database
- Test test sites
- Update Mysql version on prod database

**Comment by curtismchale** [comment]
All databases have been upgraded. I have cloned copies of `prod` and `santaana` around for a week or so just in case but the data there will continue to get more stale so I'll delete them eventually.
