### ISSUE TITLE
PILOT: add new user

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#231]
WC would like to add a new content admin:

Connie Lewis at clewis@westcarrollton.org

**Comment by kevindherman** [comment]
Is there an  easy way for me to manage this?

**Comment by kevindherman** [comment]
This person is in the planning and building department, not sure if it's set up yet but if possible we should limit her access to that Dept.

**Comment by jlyon** [comment]
I added clewis@westcarrollton.org as an author (see explanation or roles below) @kevindherman.  Lmk if they should be a contributor instead.  They can login at my.proudcity.com.

* Editor – somebody who can publish and manage posts including the posts of other users.
* Author – somebody who can publish and manage their own posts.
* Contributor – somebody who can write and manage their own posts but cannot publish them.

You/they will be able to manage users once we launch with Calypso (hopefully next release).

**Comment by kevindherman** [comment]
@jlyon sorry for the delay. Just confirmed that the author permissions is appropriate.
