### ISSUE TITLE
July 26 WP Updates

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2314]
**Admin Menu Editor - 1.11 -> 1.11.1**

[Release Notes Link](https://wordpress.org/plugins/admin-menu-editor/#developers)

- bugfixes should have no impact

**Events Manager - 6.4.2 -> 6.4.4**

[Release Notes](https://wordpress.org/plugins/events-manager/#developers)

- if we're using the built-in calendar display we should check it at responsive sizes

**Font Awesome - 4.3.2 -> 4.4.0**
[Release Notes](https://wordpress.org/plugins/font-awesome/#developers)

- nothing major just bug fixes
- check to make sure icons still work as expected

**Gravity Forms 2.7.9 -> 2.7.10.1**
[Release Notes](https://docs.gravityforms.com/gravityforms-change-log/)

- just bug fixes

**MailOptin - 2.2.60.0 -> 2.2.61.0**
[Release notes](https://wordpress.org/plugins/mailoptin/#developers)

- bugfixes should have no impact

**Site Origin Panels - 2.24.0 -> 2.25.0**
[Release Notes](https://wordpress.org/plugins/siteorigin-panels/#developers)

- just bugfixes should have no impact

**Post Expirator - 3.0.3 -> 3.0.5**
[Release notes](https://wordpress.org/plugins/post-expirator/#developers)

- bug fixes and UI tweaks should have no impact for us

**Google Site Kit - 1.104.0 -> 1.105.0**
[Release notes](https://wordpress.org/plugins/google-site-kit/#developers)

- bugfixes should have no impact

**SO Widgets Bundle - 1.50.1 -> 1.52.0**
[Release notes](https://wordpress.org/plugins/so-widgets-bundle/#developers)

- bug fixes and minor enhancements. Should have no impact

**WP Job Manager - 1.40.2 -> 1.41.0**
[Release Notes](https://wordpress.org/plugins/wp-job-manager/#developers)

- bug fixes should have no impact

**WP Mail SMTP - 3.8.0 -> 3.8.2**
[Release notes](https://wordpress.org/plugins/wp-mail-smtp/#developers)

- minor enhancements and bugfixes should have no impact

**WP Media Folder - 5.5.11 -> 5.5.13**
[Release notes](https://www.joomunited.com/changelog/wp-media-folder-changelog)

- bug fixes and minor enhancements. Should have no impact.

**WordPress SEO - 20.10 - 20.12**
[Release notes](https://wordpress.org/plugins/wordpress-seo/#developers)

- bug fixes and minor enhancements. Should have no impact.

## Curtis Test

- [x] font awesome icons
- [x] check built in calendar display for Events manager at mobile sizes

**Comment by curtismchale** [comment]
First staging test build: https://console.cloud.google.com/cloud-build/builds;region=global/0c79c9a7-24f1-4d2b-b9f0-c9b42c8967e3;tab=artifact?project=proudcity-1184

**Comment by kevindherman** [comment]
@curtismchale @lukefretwell 

In testing in beta I noticed that some icons weren't displaying. You can see this on the homepage service center and the widget test page (department list icon display): https://beta.proudcity.com/test-new-menu-and-widgets/

I'm not entirely sure if the icons went missing with this update or if they were missing before. Past updates could've removed the icon display and we didn't add them back. @curtismchale I think the easiest test is for when this goes to the next phase and is deployed to city template and/or test instances. If icons are missing from /government/ and homepage service center then we'll know how innocent the icon update is or isn't. 

@curtismchale does that seem like a good next step for the icons?

Everything else looked good to me.
