### ISSUE TITLE
PILOT: docs widget broken for City Council Minutes

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#233]
The City Council Minutes page on the CIty Council Dept Page is not pulling in the city council doc widget: https://www.westcarrollton.org/city-council-minutes/

**Comment by kevindherman** [comment]
City Council Minutes page:
![screenshot 2016-03-14 12 26 49](https://cloud.githubusercontent.com/assets/6032426/13751333/111daa2a-e9e0-11e5-9247-bbc7a2dc0295.png)

Documents list widget edit view from the above page:
![screenshot 2016-03-14 12 28 17](https://cloud.githubusercontent.com/assets/6032426/13751398/596e6f62-e9e0-11e5-9bf2-09b20d6ba980.png)


Document Library:
![screenshot 2016-03-14 12 24 13](https://cloud.githubusercontent.com/assets/6032426/13751354/214b5b86-e9e0-11e5-822c-8df8cc0dcb1a.png)

**Comment by aschmoe** [comment]
Github commit auto-closed
