### ISSUE TITLE
Predictive search results bug

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2332]
## Source
KH

## Describe the bug
On a handful but not all sites when you use the search function, the predictive search results do not format as expected. 

## To reproduce
1. Go to https://swansboro-nc.org/
2. Go to the search box in middle of the homepage and type "police" 
4. Do NOT hit enter
5. See search results formatted incorrectly

See stripped out formatting
![Screen Shot 2023-08-17 at 3 13 33 PM](https://github.com/proudcity/wp-proudcity/assets/6032426/2777fa0c-975e-4bd0-9afe-821af64a76d3)

## Expected behavior
Search results should format with icons and larger text like below:
![Screen Shot 2023-08-17 at 3 12 43 PM](https://github.com/proudcity/wp-proudcity/assets/6032426/04e11cd5-1c12-4403-8e93-a18b345aa073)

## Additional context
I noticed this on a handful of sites
- West Milton
- Swansboro
- Streetsboro
- Montgomery

But normal on others:

- Test sites
- Santa Ana
- San Rafael
- Jackson
- Petaluma

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment]
The issue was with WP Rocket configs and the setting to clear unused CSS. WP Rocket has no insight into what is produced in the Service Center and Search as they come from external angular app resources. Thus it cleared out icons and other styles that were used by the apps but WP Rocket couldn't see.

**Comment by kevindherman** [comment]
@curtismchale nice find! Glad this is resolved.

cc @lukefretwell
