### ISSUE TITLE
Migrate PC dashboard to WP dashboard

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2345]
**Source**
The source of the issue (ex: Customer: #CustomerName#).

LF

**Is your feature request related to a problem? Please describe.**

Allows us to better leverage WP dashboard functionality.

**Describe the solution you'd like**

Items to consider:

Where to move:
* Accessibility
* User management
* Payments
* Marketplace
* My Sites
* Settings (domains, etc.)
* How to add links to content types (do we want to do this?)
* How to incorporate guide/help info
* What else do we want to add to this (PC created or WP plugins)?

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by curtismchale** [comment]
Closing as we've just revamped the WP dashboard and are about to revamp the PC dashboard
