### ISSUE TITLE
Remove <strong> from 'Official government website'

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2353]
**Builds**
- [staging](https://console.cloud.google.com/cloud-build/builds;region=global/03898d9f-4684-43e9-888b-71e27cd6f16f?project=proudcity-1184)
- [prod](https://console.cloud.google.com/cloud-build/builds;region=global/c26e0ef9-d958-446f-82e2-18102db27a3f?project=proudcity-1184)

## Source
The source of the issue (ex: Customer: #CustomerName#).

LF

## Feedback

Can we remove the strong tag from official government website in top left bar?

![Screenshot 2023-09-13 at 10-35-20 Welcome - Somerville NJ](https://github.com/proudcity/wp-proudcity/assets/1569463/7c16cd77-c564-48c1-b9c5-f985f79e6bba)

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment]
@lukefretwell I just spot checked 5 sites and don't see this. We need a link to a site when you're submitting an issue like this.

**Comment by lukefretwell** [comment]
@curtismchale city template defaults to this now: https://demo.proudcity.com/

**Comment by curtismchale** [comment]
Deployed

Composer: https://github.com/proudcity/wp-proudcity/releases/tag/2024.01.02.1257
Build: https://github.com/proudcity/proud-recipes/releases/tag/2024.01.02.1257
