### ISSUE TITLE
Deprecate accessibility dashboard

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2356]
**Source**
The source of the issue (ex: Customer: #CustomerName#).

LF

**Is your feature request related to a problem? Please describe.**

N/A

**Describe the solution you'd like**

Time for us to rethink the need for this and deprecate if usage is low.

**Describe alternatives you've considered**

* Adding other accessibility tools and third-party partnership.

**Additional context**

**Comment by curtismchale** [comment]
We won't build this with #2567 so we can close this.

**Comment by lukefretwell** [comment]
@curtismchale by deprecating, also thinking we can delete Pa11y code, redirect links to new dashboard.
