### ISSUE TITLE
Deprecate or hide marketplace

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2358]
**Source**
The source of the issue (ex: Customer: #CustomerName#).

LF

**Is your feature request related to a problem? Please describe.**

N/A

**Describe the solution you'd like**

We should revisit the marketplace UI/UX, but for now hide, remove or just make it available in admin section.

**Describe alternatives you've considered**

https://github.com/proudcity/wp-proudcity/issues/2357

**Additional context**

**Comment by curtismchale** [comment]
There is no marketplace in the new PC Dashboard so this won't matter.
