### ISSUE TITLE
Rethink dashboard functionality

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2360]
**Source**
The source of the issue (ex: Customer: #CustomerName#).

https://docs.google.com/document/d/1EYmTbHUiCoqGrp3HziottWQJ-4E1yDqv_aWs3YiNSe0/edit?usp=sharing

**Is your feature request related to a problem? Please describe.**

N/A

**Describe the solution you'd like**

Rather than having a custom dashboard when users login to their sites, we should just use the default WP dashboard.

Phases:

* Think about short and long-term.
* Short-term: Keep PC dashboard, but just have links to certain functionality and resources, add-ons.
* Long-term: Move to WP dashboard, think about what widgets we'd display and user functionality would be.

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by lukefretwell** [comment]
Reference: https://wordpress.org/documentation/article/dashboard-screen/ 

Thoughts:

* First row panel: Welcome!
  * Content (Pages / News / Events
* Second row/panels: Academy + Clean-up
* Third row panel: Help
  * Links (ProudCity Help Center / Submit a support ticket)
  * Topics (Accounts / Other? / All)

**Comment by lukefretwell** [comment]
## Questions

* What's the best way to provide text changes?
* Should we add new issue for 'Share'?

## Feedback

* Ordered how I think would be good.
* Bold button text.
* Text seems slightly too small.
* Remove styling in the news box (looks weird).
* News: Remove 'The post [FYI from ProudCity (May 2024)](https://proudcity.com/fyi-from-proudcity-may-2024/) appeared first on [ProudCity](https://proudcity.com/).'
* Non-ProudCity widgets aren't great.
* Share can wait.

@curtismchale @kevindherman

**Comment by kevindherman** [comment]
@lukefretwell agree with your changes.

Suggestions:
- Would slide training to the right column so everything on that side are services. 
- @lukefretwell for services, not sure if it should be the heading or buttons, but it should be actionable. "Get training" "Order clean up" "Subscribe to review".
- Only if it's quick, since we're only posting one news item (maybe consider two), would be nice if the text under the headline is short description text. 

@curtismchale @lukefretwell

**Comment by curtismchale** [comment]
@lukefretwell 

I'll be deploying the changes listed in a minute. The "small" font size is the thing I've been seeing and can't track down in the CSS as it all seems to be the proper size compared to other dashboard pages.

@kevindherman adding a new widget is a few minutes for me (plus build and deploy time) so it's not a big deal if we want to add a few.

**Comment by lukefretwell** [comment]
@curtismchale add updated text for widgets here?

**Comment by curtismchale** [comment]
@lukefretwell yes if you want text changes put it here

**Comment by curtismchale** [comment]
@kevindherman @lukefretwell the changes are up for you to check including the move of the Dashboard menu item. I'm ready to launch if this is approved.

**Comment by lukefretwell** [comment]
@curtismchale can we:

* add #fef0c8 to entire box for both
* bump the news heading font down a size
* change 'Support news' to 'News'
* would be awesome if we could change the footer text to what's in the prototype

Screenshot:

![Screenshot 2024-05-23 at 15-12-54 Dashboard ‹ PC Beta — WordPress](https://github.com/proudcity/wp-proudcity/assets/1569463/09c57ec7-ed76-4af4-b50e-92fb5b49d24b)

**Comment by curtismchale** [comment]
@lukefretwell if we change the `Support News` heading to simply `News` we have two widgets with the same headings which feels confusing to me.

All the other updates are made for you to see on Beta.

**Comment by lukefretwell** [comment]
Looks great. I don't see a problem with having two news headings as it just looks like an alert and the differentiation may not be apparent to the user. But I'm fine either way.

Can we:
- [ ] change 'Support News' to 'Help news' (we use sentence case)
- [ ] make the news links `target="blank"` (like the buttons)
- [ ] remove the 'home' leftnav (goes to same place as dashboard)

Etc:

Would love to experiment with adding color to the icons so they each stand out more.

**Comment by lukefretwell** [comment]
Icon colors:

* News: #1b1b1b
* Support news: #4a50c4
* ProudCity training: #3f57a6
* Site clean-up: #146947
* Help center: #e52207
* Plain language training: #07648d
* Support: #2c608a
* Site review: #a88f48
* Payments: #0f6460
* Users: #c05600

**Comment by curtismchale** [comment]
@lukefretwell the action scheduler doesn't mean anything as we don't visit Beta enough for all actions to be run all the time. Just dismiss it.

The new dashboard is up on ProudCity now for a final check on a live site.

**Comment by lukefretwell** [comment]
This looks great, though I think we want to display SiteKit at a future date.

I don't love the colors of the news icons. Can we just make them both #0071bc.

**Comment by kevindherman** [comment]
@curtismchale @lukefretwell change payment widget to: 
ProudCity Payments
Manage payments and reports

**Comment by kevindherman** [comment]
The word “dashboard” is no longer in blue edit bar and the logo links to https://presentation-ca.proudcity.com/wp-admin/about.php instead of https://presentation-ca.proudcity.com/wp-admin/index.php. 

So if you're logged in and navigating around, you don't have a way to get into the dashboard directly. Would need to edit and then click dashboard. 

Without the update, "dashboard" goes to https://www.santa-ana.org/wp-admin/admin.php?page=proud_dashboard


![Image](https://github.com/proudcity/wp-proudcity/assets/6032426/3b1f33cb-3262-477a-8ebb-281fb6cf6c5b)

Ideally, the "dashboard" link should go to /wp-admin/index.php

**Comment by curtismchale** [comment]
Deployed

Composer: https://github.com/proudcity/wp-proudcity/releases/tag/2024.05.28.1300
Builds: https://github.com/proudcity/proud-recipes/releases/tag/2024.05.28.1300
