### ISSUE TITLE
/documents cleanup (style/layout tweaks)

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#238]
Thoughts on the docs main and filter pages:
- [ ] In search box would change 'Categories' to 'Filter' and 'Filter' button text to 'Go' (https://www.westcarrollton.org/documents/).
- [ ]  Think OK to not have the 'City Council Meeting Agendas' tag under the doc title or place below the date. Similar to sequence recommended in #206 (https://www.westcarrollton.org/city-council-agendas/?filter_categories[]=79).
- [x] Think the download button could be size smaller on /documents and filtered pages. #342
- [x]  Would link the document icon (or just get rid of it).

**Comment by jlyon** [comment]
took care of a couple of these in #236
