### ISSUE TITLE
Site caching permission error

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2386]
## Source
Platform
https://www.santa-ana.org/wp-admin/admin.php?page=caching

* [LINK TO TICKET]
KH

## Describe the bug
If you select caching from site tools you get a permissions error logged in as support@ or info@:
![Screen Shot 2023-10-02 at 3 15 42 PM](https://github.com/proudcity/wp-proudcity/assets/6032426/4934e5e5-0fc5-4423-9444-d33414904c21)

## To reproduce
1. Go to dashboard
2. Tools
3. Cashing
5. 

## Expected behavior
Go to simple site caching page with button to clear site cache. 

## Screenshots
![Screen Shot 2023-10-02 at 3 15 42 PM](https://github.com/proudcity/wp-proudcity/assets/6032426/ec34e94d-567b-47c7-a055-b30f04f2bf4e)

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment]
Fixed: https://github.com/proudcity/wp-proudcity/issues/2548
