### ISSUE TITLE
PILOT: Export form duplicate all fields

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#239]
Under forms, on the export entries page if you select all fields each one is duplicated in the export.

**Comment by kevindherman** [comment]
![screenshot 2016-03-18 14 13 03](https://cloud.githubusercontent.com/assets/6032426/13888752/813a5510-ed19-11e5-9095-48b26e9de779.png)


[building-permit-application-2016-03-18.xlsx](https://github.com/proudcity/wp-proudcity/files/180223/building-permit-application-2016-03-18.xlsx)

**Comment by jlyon** [comment]
Can't replicate. 

1. Go to https://www.westcarrollton.org/wp-admin/admin.php?page=gf_export&view=export_entry
2. Select Building Permit Application
3. Click Select All
4. Click Export
Result: csv with 3 rows, columns to BB and only one column for each value (search for "Residential or Commercial"): https://drive.google.com/a/albatrossdigital.com/file/d/0B1w0s_pQVmyXZ1VCelVOdm9TQ28/view?usp=sharing

**Comment by kevindherman** [comment]
@jlyon I had a successful (normal) export yesterday as well. Not sure what happened with the duplicates last week, perhaps the updates fixed something. 

This can be closed out.
