### ISSUE TITLE
Default admin menu displaying on De Leon [BUG]

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2398]
## Source
KH
De Leon
https://www.cityofdeleon.org/

## Describe the bug
If you view the website dashboard it displays the WP default instead of PC:
https://www.cityofdeleon.org/wp-admin/admin.php?page=proud_dashboard#/sites/deleontx/dashboard
![Screen Shot 2023-10-09 at 4 08 40 PM](https://github.com/proudcity/wp-proudcity/assets/6032426/66240fe5-6c94-417c-9fb5-fd061bf53550)

## To reproduce
1. Go to my.proudcity.com
2. Click on manage site for De Leon

## Expected behavior
Should have new admin menu on left.

## Additional context
I was looking at Google console and saw heavy wp_option activity from De Leon so I went to take a look and noticed the admin menu. This may be relate to the following issues:

- https://github.com/proudcity/wp-proudcity/issues/2397
- https://github.com/proudcity/wp-proudcity/issues/2219
- https://github.com/proudcity/wp-proudcity/issues/2387

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment]
@kevindherman the new Admin plugin wasn't activated.

![Screenshot from 2023-10-09 13-15-22](https://github.com/proudcity/wp-proudcity/assets/74561/1d42cc23-8481-4309-8497-23285cf128ec)

I turned it on and the expected menu is back.

**Comment by kevindherman** [comment]
@curtismchale easy, great.
