### ISSUE TITLE
Add Google Analytics dashbaord

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#24]
In calypso?

**Comment by jlyon** [comment]
Need to set perms

**Comment by jlyon** [comment]
@kevindherman finally fixed the perms so this appears below the checklist.

**Comment by kevindherman** [comment]
Looks good.

On Wed, Feb 10, 2016 at 7:18 PM, Jeff Lyon <notifications@github.com> wrote:

> @kevindherman <https://github.com/kevindherman> finally fixed the perms
> so this appears below the checklist.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/24#issuecomment-182650989>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
