### ISSUE TITLE
Turn off Attachment Pages?

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2405]
**Source**
CM

[WP 6.4 turns off attachment pages by default for new sites](https://make.wordpress.org/core/2023/10/16/changes-to-attachment-pages/). This is because these pages show up in search results and get indexed, but don't add any meaningful content.

We should look at turning them off for all our customer sites as well so we don't have to deal with the SEO issues that can be inherent with the attachment pages.

**Comment by curtismchale** [comment]
@lukefretwell For this all new sites will have the field `wp_attachment_pages_enabled` turned off. That will result in pages like [this one](https://proudcity.com/what-they-say/sally-wilkinson/) no longer existing. These pages don't really serve any purpose and simply came along with the stock WordPress media library/attachments from the beginning.

I vote that we deploy 6.4.1 with the value set to false so that all of our sites now have their attachment pages turned off.

The only impact I expect any customer would see is that their site Analytics may change as the attachment pages drop off because users won't be able to access them anymore.

**Comment by lukefretwell** [comment]
@curtismchale I concur.
