### ISSUE TITLE
Upgrade ElasticPress

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2428]
**Source**
CM

**Is your feature request related to a problem? Please describe.**
ElasticPress is running 2.8.2 from 2019 and we need to upgrade it as part of our PHP 8.2 upgrade.

After discussion with Alex, there was a bunch of work to do the upgrade back in 2019...and here we are today.

## Tasks

- [ ] create `test` site for San Rafael to test elasticpress
  -  the use the current staging site so we can't just use that

**Comment by aschmoe** [comment]
@curtismchale update:

https://github.com/proudcity/wp-proudcity/pull/2453
https://github.com/proudcity/wp-proud-search-elastic/pull/3

I have the new version of elasticpress working.  Now I need to figure out the infrastructure portion of the project.  This will have to continue next week unfortunately.

**Comment by kevindherman** [comment]
@aschmoe @curtismchale elastic is turned off on both San Rafael and Petaluma for when you deploy and test.

This issue includes a page on Petaluma that's good to test if elastic is activated and scanned: https://github.com/proudcity/wp-proudcity/issues/2596

**Comment by aschmoe** [comment]
@curtismchale @kevindherman the elastic upgrade has been deployed for all the sites that use elastic.

```
beta
lucas-tx
ketteringohparks
ketteringoh
play-miamisburgoh
miamisburgoh
marin-dpw-ca
somervillenj
proudcity-help
wwwproudcity
santaana-ca
san-rafael-ca
petaluma-ca
```

Everything is looking good from my end.
