### ISSUE TITLE
Event location map isn't returning correct coordinates

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2429]
## Source

* https://proudcity.zendesk.com/agent/tickets/6659

## Describe the bug

The map for event locations isn't showing correct location.

Example: https://proudcity.com/location/test/

## To reproduce
1. Go to 'Events'
2. Click on 'Locations'
3. Add location
4. View location

## Expected behavior

Should see a map of exact location.

## Additional context

This appears to work on some locations, such as this one: https://www.cityofsanrafael.org/location/san-rafael-city-plaza/

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment]
It looks like [Google changed](https://stackoverflow.com/questions/75179573/how-to-fix-loading-the-google-maps-javascript-api-without-a-callback-is-not-sup) how we can call maps and we need to update it. I'm not sure at this point if it's with the Events plugin or with our own maps code running elsewhere that's causing an issue here.

**Comment by curtismchale** [comment]
@lukefretwell the address provided was invalid so it couldn't find the location. I searched the address and then copied out the address listed in Maps information and it worked.
