### ISSUE TITLE
Remove Zendesk script from admin

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2449]
**Builds**

- [staging](https://console.cloud.google.com/cloud-build/builds;region=global/3a02dffe-f7e3-43ff-9994-16f650570d85?project=proudcity-1184)
- [master](https://console.cloud.google.com/cloud-build/builds;region=global/0713d9cd-be1e-4100-b943-bdb8d5f15ef2?project=proudcity-1184)

## Source
The source of the issue (ex: Customer: #CustomerName#).

LF

## Feedback

Looks like we still have Zendesk script in the admin side of the code. Since we're not using it there, good to remove.

1. Login to dashboard
2. Select proudcity.com
3. In dashboard, view code and search 'Zendesk'
4. See code

Code:

```
<!-- Start of proudcity Zendesk Widget script -->
<script>/*<![CDATA[*/window.zEmbed||function(e,t){var n,o,d,i,s,a=[],r=document.createElement("iframe");window.zEmbed=function(){a.push(arguments)},window.zE=window.zE||window.zEmbed,r.src="javascript:false",r.title="",r.role="presentation",(r.frameElement||r).style.cssText="display: none",d=document.getElementsByTagName("script"),d=d[d.length-1],d.parentNode.insertBefore(r,d),i=r.contentWindow,s=i.document;try{o=s}catch(c){n=document.domain,r.src='javascript:var d=document.open();d.domain="'+n+'";void(0);',o=s}o.open()._l=function(){var o=this.createElement("script");n&&(this.domain=n),o.id="js-iframe-async",o.src=e,this.t=+new Date,this.zendeskHost=t,this.zEQueue=a,this.body.appendChild(o)},o.write('<body onload="document._l();">'),o.close()}("https://assets.zendesk.com/embeddable_framework/main.js","proudcity.zendesk.com");
/*]]>*/</script>
<!-- End of proudcity Zendesk Widget script -->
```

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment]
Deployed

Build: https://github.com/proudcity/proud-recipes/releases/tag/2023.12.21.1358
Composer: https://github.com/proudcity/wp-proudcity/releases/tag/2023.12.21.1357
