### ISSUE TITLE
Custom Redis Error Message

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2460]
**Build**
- [staging](https://console.cloud.google.com/cloud-build/builds;region=global/9768e751-f461-44ec-83eb-e094e8172af6?project=proudcity-1184)
- [master](https://console.cloud.google.com/cloud-build/builds;region=global/c6c9fb88-89d7-48fd-909f-24a6e8249089?project=proudcity-1184)

**Source**
Fairfax

* [6727](https://proudcity.zendesk.com/agent/tickets/6727)

**Is your feature request related to a problem? Please describe.**
If we have a momentary drop in the Redis connection it presents the user with an ominous message when 99% of the time all we need to do is refresh.

**Describe the solution you'd like**
Provide a message that tells the user refresh the page and things should resolve or if they don' contact support.

Should we bug Slack about this as it's just a temporary issue or would that create too many notices in `dev-alerts`.

We can add a custom file in `WP_CONTENT_DIR . /redis-cache.php` with a custom message. See `redis-cache/includes/object-cache.php` line `2905`.

**Comment by lukefretwell** [comment]
@curtismchale suggested message:

```
# Refresh your browser

Looks like we've experienced a minor hiccup while updating this website.

Simply refresh your browser and everything should work just fine. 
```

Thoughts:

* Add a script to refresh page automatically.
* #dev-alerts would be good. If it's too much we can turn it off or create another channel just for this. Having awareness that this is a potential issue for some is helpful.

**Comment by curtismchale** [comment]
This has been deployed for a week and we have now moved our messages over to a custom channel.

Composer: https://github.com/proudcity/wp-proudcity/releases/tag/2024.01.30.0858
Build: https://github.com/proudcity/proud-recipes/releases/tag/2024.01.30.0858
