### ISSUE TITLE
Quote tool not returning data

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2461]
## Source

https://proudcity.slack.com/archives/C0AH683JQ/p1703098221756009

## Describe the bug
The quote tool is not returning results.

## To reproduce
1. Go to https://proudcity.com/pricing/
2. Type a city 
3. JS is broken so nothing returns

## Expected behavior
We should get a returned value for the city.

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment]
@lukefretwell we could look at deprecating the reliance on Angular here and build it in PHP/HTML/JS in WordPress.

**Comment by aschmoe** [comment]
@curtismchale @lukefretwell https://github.com/proudcity/proudcity-custom/commit/c948180cc820c09e792b37758f99c221f61a1b41 commit here, waiting for deploy

**Comment by aschmoe** [comment]
@curtismchale @lukefretwell that has been deployed, seems from my brief testing.
