### ISSUE TITLE
Remove popup maker plugin

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2475]
## Builds

- [staging](https://console.cloud.google.com/cloud-build/builds;region=global/0d566d5e-03f0-427e-89f9-b5b7821275c7?project=proudcity-1184)
- [master](https://console.cloud.google.com/cloud-build/builds;region=global/de1a9e79-fab0-473d-92ad-5a8dc250c19d?project=proudcity-1184)

## Source

[Ticket](https://proudcity.zendesk.com/agent/tickets/6742)

**Comment by curtismchale** [comment]
Deployed

Composer: https://github.com/proudcity/wp-proudcity/releases/tag/2024.01.30.0858
Build: https://github.com/proudcity/proud-recipes/releases/tag/2024.01.30.1515

**Comment by lukefretwell** [comment]
@curtismchale I still see this plugin available for Petaluma.
