### ISSUE TITLE
Error message (Redis?) + auto browser refresh

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2478]
**Builds**
- [master](https://console.cloud.google.com/cloud-build/builds;region=global/22ca931c-0cf3-4ea4-a1e6-1d1857886b11?project=proudcity-1184)
- [staging](https://console.cloud.google.com/cloud-build/builds;region=global/bf20dd58-be3a-4d7a-ac78-823348ac5661?project=proudcity-1184)

## Source

LF

## Describe the bug

When this error displays (Redis?), the countdown just keeps going and the browser is refreshing continuously:

```
An error was encountered

Looks like we've encountered a minor hiccup.

Refresh your browser and this should resolve. If the problem persists please get in touch with support.

The browser will refresh in -146
```

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment]
Deployed with the new error message that sends users to the main URL instead of just refreshing the browser.

Composer: https://github.com/proudcity/wp-proudcity/releases/tag/2024.02.09.1544
Build: https://github.com/proudcity/proud-recipes/releases/tag/2024.02.09.1544
