### ISSUE TITLE
Change 'Users' to 'Accounts'

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2483]
**Source**
The source of the issue (ex: Customer: #CustomerName#).

LF

**Is your feature request related to a problem? Please describe.**

N/A

**What feature would you like to improve**
A clear and concise description of the current feature.

Change terminology from 'Users' to 'Accounts' in admin.

**Describe the solution you'd like**

**Additional context**

**Comment by curtismchale** [comment]
@lukefretwell @kevindherman this is ready to be deployed to the PC dashboard, but I'm going to connect with Jeff to make sure that the deploy goes as expected and that he's around to help if not.

No ETA at this time about when it gets deployed.

**Comment by curtismchale** [comment]
Deployed: https://github.com/proudcity/proudcity-dashboard/releases/tag/2024.05.01.1509
