### ISSUE TITLE
CSS not loading sometimes

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2487]
## Source

* [6807](https://proudcity.zendesk.com/agent/tickets/6807)

## Describe the bug
Sometimes the CSS doesn't load. It appears this is because in a multi-pod environment the cached CSS file isn't present on all pods and thus sometimes it doesn't load the cached CSS. See [WP Rocket load balance docs](https://docs.wp-rocket.me/article/55-use-wp-rocket-with-load-balancing), which is essentially what multi-pod environments are.

We can define a [custom cache location](https://docs.wp-rocket.me/article/1118-specify-a-custom-cache-folder) which we could put in `wp-stateless` and then serve the cached version out of stateless all the time which would be available to all pods in a network.

Others have reported a [similar problem](https://github.com/udx/wp-stateless/issues/561)

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment]
@kevindherman Check in with the customer now as this may be solved since WP Rocket no longer wants to concatenate all the CSS/JS thus it shouldn't be present only on a single pod in the `cache` folder.

**Comment by kevindherman** [comment]
Cool.

I'll followup.

**Comment by kevindherman** [comment]
@curtismchale I think we can close this until reports come back of it being broken.
