### ISSUE TITLE
Launch Williamston, MI

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2492]
https://trello.com/c/CLLjMaSE/4022-launch-prep-williamston-mi

- [ ] increase replicas to 2

**Comment by curtismchale** [comment]
@kevindherman this is done outside of MailChimp and Site Kit. The subdomain worked as expected.

**Comment by kevindherman** [comment]
@curtismchale thank you.

I'm meeting with them on Thursday to finish up Mailchimp so this will be completed then.
