### ISSUE TITLE
Upgrade to production button not working

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2493]
from my.proudcity.com domain settings, the upgrade to production button doesn't actually execute a command to move to production.

**Comment by curtismchale** [comment]
I ran `pc kube rocket test williamstonmi williamston-mi.proudcity.com` but hadn't updated to the latest Docker version. @jlyon said he'd clean up the migration (because it won't connect to the DB now).

**Comment by curtismchale** [comment]
Jeff got Williamston back up as they launch and is working on the `launch` button in the dashboard.

https://proudcity.slack.com/archives/C0AH683JQ/p1710272747068299
