### ISSUE TITLE
Events sequence of headings is not in sequential order from H1-H6

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2497]
## Source

https://airtable.com/appRFUc45sF4yWFut/tbl51inE74gEWlB0x/viwG9G4vAjsjQEh4g/recO93Nbf5CaQrRdQ?blocks=hide

## Describe the bug

The sequence of headings is not in sequential order from H1-H6.  Headings in a sequential order better support creating an understanding via audio of the important elements of the page.  Notice that H4 is skipped in the sequence.	

## Screenshots

![Heading Sequence](https://github.com/proudcity/wp-proudcity/assets/1569463/de24011a-e3ad-44db-a222-53c2ed96379b)

**Comment by curtismchale** [comment]
@lukefretwell this is easy from a code perspective. If we want to make the time an `h4` I can do that. If we want to revamp the heading structure...thats' a longer discussion but the implementation is still easy from a code perspective.

**Comment by lukefretwell** [comment]
@curtismchale making it an `h4` is the easiest and probably what we should do for now. Don't love that it's a heading.

**Comment by curtismchale** [comment]
@lukefretwell if we don't love that it's a heading then let's make it something else. We could use the `<time>` element as shown [here](https://www.w3schools.com/tags/tag_time.asp).

If I'm changing it changing it to something else is just as easy.

**Comment by lukefretwell** [comment]
@curtismchale anything we can do to add semantic HTML is always a win. For the HTML, it will still need some style (`p` or `ul`) for the date and time and seems like `ul` would be more accessible.

**Comment by curtismchale** [comment]
@lukefretwell you can find an event list on the homepage: https://www.adapacific.org/

**Comment by curtismchale** [comment]
Deployed

Composer: https://github.com/proudcity/wp-proudcity/releases/tag/2024.08.20.1153
Build: https://github.com/proudcity/proud-recipes/releases/tag/2024.08.20.1153
