### ISSUE TITLE
Footer actions bar background color

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#250]
![screenshot from 2016-03-22 22 14 04](https://cloud.githubusercontent.com/assets/550909/13976287/a950fba2-f07b-11e5-81cc-aba8d8a7033a.png)
I like the white action bar on most pages except where the map juts up against the map.  I think change this to the highlight color maybe?

**Comment by aschmoe** [comment]
@jlyon theres not really a good way to account for this unfortunately.

**Comment by jlyon** [comment]
Create new setting in functions.php for this
