### ISSUE TITLE
Clear red indicator for West Milton

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2516]
## Builds

- [staging](https://console.cloud.google.com/cloud-build/builds;region=global/b6682b15-5f1f-4450-9d21-5992420e1552;tab=artifact?project=proudcity-1184)
- [master](https://console.cloud.google.com/cloud-build/builds;region=global/6a021b05-d53f-4da0-ad24-6b0a95ba8da5?project=proudcity-1184)

## Source

* [6828](https://proudcity.zendesk.com/agent/tickets/6828)
* [Slack](https://proudcity.slack.com/archives/C05517XBZ3P/p1710510917318389)

## Describe the bug
There is a red indicator with a 1 beside the Event tab

![CleanShot 2024-03-17 at 11 16 23](https://github.com/proudcity/wp-proudcity/assets/74561/7f79b8f7-1f25-460f-a825-fbc08817c442)

**Comment by lukefretwell** [comment]
@curtismchale was going to add an issue for this. Might be good to think about removing this for all non-PC admins.

**Comment by kevindherman** [comment]
@lukefretwell @curtismchale this should probably be WP admin not PC admin.

**Comment by curtismchale** [comment]
Deployed.

Composer: https://github.com/proudcity/wp-proudcity/releases/tag/2024.03.19.1722
Builds: https://github.com/proudcity/proud-recipes/releases/tag/2024.03.19.1722
