### ISSUE TITLE
Expiration date picker on a job listing won't save

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2518]
## Source

* [Support ticket](https://proudcity.zendesk.com/agent/tickets/6829)

## Describe the bug
Expiration date picker on a job listing won't save. 

## To reproduce
1. Go to ['[...'](https://www.montgomeryohio.gov/wp-admin/post.php?post=22348&action=edit)](https://www.montgomeryohio.gov/wp-admin/post.php?post=22348&action=edit)
2. Use date picker in "Listing Expiry Date" field in "Job data" section
3. Update
4. "Listing Expiry Date" field is empty once the update loads

## Expected behavior
The expiration date should be saved. Job listing should expire after set date.

## Screenshots
<img width="1732" alt="Screenshot-2024-03-18-110145" src="https://github.com/proudcity/wp-proudcity/assets/6032426/4d8a3581-8946-42c7-b1f0-1f30332a3a11">

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment]
@kevindherman the date does save it just doesn't show due to a bug in WP Job Manager which I reported here: https://wordpress.org/support/topic/expiration-date-not-visible-in-admin/

There is nothing for me to fix.

**Comment by kevindherman** [comment]
@curtismchale since this is closed. Do you think something like this would get resolved with one of their plugin updates?

**Comment by kevindherman** [comment]
@curtismchale thank for the clarity.

Lets just keep an eye out for this item in their releases and if you can flag when you do our release notes that would be perfect.

**Comment by curtismchale** [comment]
They [say](https://wordpress.org/support/topic/expiration-date-not-visible-in-admin/#post-17527166) this has been [fixed](https://github.com/Automattic/WP-Job-Manager/pull/2779) now but version 2.2.3 hasn't been rolled out yet so we're still waiting.

**Comment by kevindherman** [comment]
@curtismchale super helpful. Thanks for the update. 

I passed along to the customer since they're interested in this stuff. 

Fingers crossed they roll out the version soon.
