### ISSUE TITLE
title of the page reads twice when navigating with a screen reader

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2519]
## Source

https://airtable.com/appRFUc45sF4yWFut/tbl51inE74gEWlB0x/viwG9G4vAjsjQEh4g/recpnq4B1ImcYSnk5?blocks=hide

## Describe the bug

The title of the page reads twice when navigating with a screen reader. See image.  The "title" has Pacific ADA written twice.

## Recommendation

Remove site title from `<title>`? 

## Screenshots

![title twice](https://github.com/proudcity/wp-proudcity/assets/1569463/f4d3d48f-91a0-46b5-9449-2b1e2a5c11be)

**Comment by kevindherman** [comment]
@curtismchale thanks for flagging. In most cases the homepage title is "welcome" and not the site name. I'll keep this in mind for others.
