### ISSUE TITLE
Update "footer actions" markup

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2523]
## Builds

- [staging](https://console.cloud.google.com/cloud-build/builds;region=global/43fb270b-fde0-47cc-8a48-fe9a278097f3?project=proudcity-1184)
- [prod](https://console.cloud.google.com/cloud-build/builds;region=global/31aade19-0eed-450e-82f0-2ebea39048f0?project=proudcity-1184)

## Source

https://airtable.com/appRFUc45sF4yWFut/tbl51inE74gEWlB0x/viwG9G4vAjsjQEh4g/recd14Upjqv9m58Co?blocks=hide

## Describe the bug

The "footer actions":  Helpful, Share, Size, Translate are contained in a NAV region.  A screen reader user hears "Navigation region".  However, the four actions are not navigation related. 

## Recommendations

One option is to leave the "nav" element, but give an aria-label to name the nav region so that it is clear what the four elements are for.  For example, aria-label="Page customization options"

2.) One can simply present them as a list with a name for the list that identifies the purpose.

3.) See other implementations of similar tools: 

https://www.whitehouse.gov/

https://developer.mozilla.org/en-

4.) Other possible ways to address: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/toolbar_role

## Screenshots

![navigation region](https://github.com/proudcity/wp-proudcity/assets/1569463/d8b9d40c-e2be-4d74-a47f-463e6df35540)

**Comment by curtismchale** [comment]
deployed

Composer: https://github.com/proudcity/wp-proudcity/releases/tag/2024.09.03.1549
Builds: https://github.com/proudcity/proud-recipes/releases/tag/2024.09.03.1549
