### ISSUE TITLE
Rewrite title on "Who We Serve" page

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2525]
## Source

https://airtable.com/appRFUc45sF4yWFut/tbl51inE74gEWlB0x/viwG9G4vAjsjQEh4g/rec9CpkoKHOIKifJM?blocks=hide

## Describe the bug

When the tester navigating with a screen reader selected "Nonprofits" under the heading: "Understand Your Responsibilities", he was directed to a page with the H1: "Nonprofits".

His comment was that the heading "Understand Your Responsibilities" had led him to expect a more specific page, not a general page for nonprofits.  

https://www.adapacific.org/who-we-serve/

## Recommendation

It is worth considering rewriting the title on the page "Who We Serve" - "Understand Your Responsibilities" to something more generic like "Important information for Organizations" or something along those lines.  But this is not critical and users who come to the site more than once are likely to work past this issue.

## Screenshots

![Heading 1](https://github.com/proudcity/wp-proudcity/assets/1569463/677007ea-cc12-4001-a579-2d26beffee20)
![Heading 2](https://github.com/proudcity/wp-proudcity/assets/1569463/0d4516a7-0269-4b7d-8d1a-d8dd001b16c9)

**Comment by curtismchale** [comment]
@lukefretwell @kevindherman this is a user issue with their content titles not a code issue. Closing.
