### ISSUE TITLE
Add number of items found to search results

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2526]
## Builds

- [staging](https://console.cloud.google.com/cloud-build/builds;region=global/fa31f77e-2195-44eb-b987-965fba09ab0c?project=proudcity-1184)
- [master](https://console.cloud.google.com/cloud-build/builds;region=global/ccff3cb5-a885-4694-a74a-ac539e15ced0?project=proudcity-1184)

## Source

https://airtable.com/appRFUc45sF4yWFut/tbl51inE74gEWlB0x/viwG9G4vAjsjQEh4g/rec23wYvmup0S2QaY?blocks=hide

## Describe the bug

When navigating with a screen reader and typing in a search term into the Search box at the top of any page, a Search Results page is reached.  The user tester commented that it would be good to have the number of search results stated.  This helps all users, but for users who are blind it is especially helpful to get a sense of how many results have been delivered.   This is not required, but a best practice for search results pages. 

## Screenshots

![Search Results Number](https://github.com/proudcity/wp-proudcity/assets/1569463/64bf6530-63e7-4f8b-8932-f32ad611cb99)

## Tasks

- [x] check custom themes for SR, Peta to make this work
- [x] check ElasticSearch site to see if this works there too

**Comment by curtismchale** [comment]
this one looks easy so we could tackle it next week.

**Comment by curtismchale** [comment]
@lukefretwell @kevindherman  How does this look?

![CleanShot 2024-03-27 at 07 32 22](https://github.com/proudcity/wp-proudcity/assets/74561/9715e08c-b963-4756-ab22-776bb347214f)

**Comment by curtismchale** [comment]
Released

Composer: https://github.com/proudcity/wp-proudcity/releases/tag/2024.03.27.1057
Build: https://github.com/proudcity/proud-recipes/releases/tag/2024.03.27.1057
