### ISSUE TITLE
Name field is too general

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2529]
## Source

https://airtable.com/appRFUc45sF4yWFut/tbl51inE74gEWlB0x/viwG9G4vAjsjQEh4g/recCKePPJHspDhJDS?blocks=hide

## Describe the bug

On the Ask Us form, the first name and last name have visual labels that are below the form fields.  This can be confusing for users who are navigating with arrow keys.  m They will not hear the form field name until after the input field.   It is also more consistent with all the other form fields which is important. 

https://www.adapacific.org/request-a-training-form/

## Recommendation

Recommend moving the form field name before the two input fields using "First Name" and "Last Name" rather than having a general category for "Name"

## Screenshots

![visual labels](https://github.com/proudcity/wp-proudcity/assets/1569463/0dce3116-2383-4515-b0c5-2df977d6145a)

**Comment by curtismchale** [comment]
@lukefretwell this is something the customer can adjust in their forms so maybe we add a recommendation about it, but there is nothing for us to do codewise. We could change our form on City Template to meet this requirement.

**Comment by lukefretwell** [comment]
@curtismchale thank you. I've changed from `form` to `content` label.

**Comment by curtismchale** [comment]
@lukefretwell @kevindherman closing this at it's something the customer can update and not us.
