### ISSUE TITLE
Add Horizontal Pod Autoscaling

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2536]
**Source**
CM

Pertinent to https://github.com/proudcity/pc-dev-issues/issues/9 we need to add horizontal pod autoscaling to sites. This will track CPU usage and if we hit 80% it will add more pods. Minimum 2 max 4 is likely a good place to start. First we'll need to make sure that the `CPU` scale is set so that the site can run at 2 pods most of the time as some sites have never had this metric changed.

## Sites

- [x] alvordtx
  - [x] CPU setting
  - [x] add scaling 
- [x] baysidewi
  - [x]  CPU setting
  - [x] add scaling
- [x] bedfordoh
  - [x]  CPU setting
  - [x] add scaling
- [x] belmontnc
  - [x]  CPU setting
  - [x] add scaling
- [x] belevederca
  - [x]  CPU setting
  - [x] add scaling
- [x] boroughofmountpoconopa
  - [x]  CPU Setting
  - [x] add scaling
- [x] buttecountycarecovers
  - [x]  CPU setting
  - [x] add scaling
- [x] cambridgetownshippa
  - [x]  CPU setting
  - [x] add scaling
- [x] carnationwa
  - [x]  CPU setting
  - [x] add scaling
- [x] cherrytownshippa
  - [x]  CPU setting
  - [x] add scaling
- [x] cliftonheightspa
  - [x]  CPU setting
  - [x] add scaling
- [x] colmaca
  - [x] CPU setting
  - [x] add scaling
- [x] corningca
  - [x] CPU setting
  - [x] add scaling
- [x] crawfordcountypa
  - [x] CPU setting
  - [x] add scaling
- [x] deleontx
  - [x] CPU setting
  - [x] add scaling
- [x] deserthotspringsca
  - [x] CPU setting
  - [x] add scaling
- [x] digitalmarinca
  - [x] CPU setting
  - [x] add scaling
- [x] easthamptonvillageny
  - [x]  CPU setting
  - [x] add scaling
- [x] effinghamil
  - [x] CPU setting
  - [x] add scaling
- [x] elatownshipil
  - [x] CPU setting
  - [x] add scaling

**Comment by curtismchale** [comment]
Went through all sites today and we should be good. We maybe should look at them all 2x yearly as I moved some sites down in CPU usage or memory because they don't need it.

**Comment by kevindherman** [comment]
@curtismchale that's great. Does this mean that the Kubernetes bill should be more consistent rather than the incremental creep we've been seeing throughout the year with the pods being added?

**Comment by curtismchale** [comment]
@kevindherman yes it should be more consistent. We have our sites set to add pods if they see enough traffic, but unless we launch a new site, we're not adding to anything currently. I'll likely go back over sites from time to time to check that we're running lean without setting resources too low though.

**Comment by kevindherman** [comment]
@curtismchale perfect, thank you.
