### ISSUE TITLE
Deleted event still displays in calendar

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2538]
## Source

* [Support ticket](https://proudcity.zendesk.com/agent/tickets/6861)

## Describe the bug

There is an event showing on July 3rd (City Council Meeting) that needs to be removed. It does not show up in the backend listings of events, and when I click on it, nothing happens (ie, it doesn't lead to an event listing page). It appears to show in a slightly different color than the other City Meetings. Can you please remove it? You need to navigate to the July 2024 calendar to see it. screen capture attached.
Link to page with this issue
https://www.sonomacity.org/calendar

![calendar-issue](https://github.com/proudcity/wp-proudcity/assets/6032426/45204db2-8a0e-48b4-95c9-1c3e7fc1e178)

## Additional context
This came up before for Sonoma and was resolved with this issue: https://github.com/proudcity/wp-proudcity/issues/2277

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment]
@kevindherman it was an orphaned event. We can [delete theme here](https://www.sonomacity.org/wp-admin/edit.php?post_type=event&page=events-manager-options#general) clicking the `Removed Orphaned Events` button pictured below is the first fix then if that doesn't work there is more DB stuff I could do.

![Image](https://github.com/proudcity/wp-proudcity/assets/74561/de78cd21-1afe-4ffa-a897-fc05e1ea6b0c)

I've done this and the event doesn't show up anymore.

**Comment by kevindherman** [comment]
@curtismchale that's great and super helpful so I can do it in the future.
