### ISSUE TITLE
PA BETA: wrong map on /residents

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#254]
https://palo-alto-ca.proudcity.com/residents/ has the West Carrollton ESRI map instead of the Palo Alto servics map that is on the other pages.

**Comment by jlyon** [comment]
Updated this on palo alto. Here's a video of what I did so you can do it in the future (sorry I was talking to Luke, so you can ignore the audio).  Do you want to try following the steps in the screenshare on example?

**Comment by jlyon** [comment]
did you update example?

**Comment by kevindherman** [comment]
Example had the correct map so I closed this out.

**Comment by jlyon** [comment]
k

**Comment by kevindherman** [comment]
And thanks for the video, that's super easy. I didn't realize it was part of the widgets.
