### ISSUE TITLE
Use the same grey as documents category label for job type label 

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2542]
## Builds

- [staging](https://console.cloud.google.com/cloud-build/builds;region=global/a6b7bb32-28a9-463e-acd5-689e2541a9ed?project=proudcity-1184)
- [master](https://console.cloud.google.com/cloud-build/builds;region=global/b37ad989-3db5-417e-85e8-ab8029c4b8cb?project=proudcity-1184)

## Source

Santa Ana Zoo https://santa-ana-zoo-ca.proudcity.com/work-at-the-zoo/ 

## Describe
Poor contrast on job type label in job list widget with orange font in green label. Change labels to same standards as documents (grey). 

## Details
https://santa-ana-zoo-ca.proudcity.com/work-at-the-zoo/
Job list widget: 
![Screen Shot 2024-04-17 at 10 04 12 AM](https://github.com/proudcity/wp-proudcity/assets/6032426/2decf463-53c7-4942-a3bf-16e472e11455)

Individual job listing has white font on green label: https://santa-ana-zoo-ca.proudcity.com/job/program-leader/
![Screen Shot 2024-04-17 at 10 04 26 AM](https://github.com/proudcity/wp-proudcity/assets/6032426/1000a224-a044-45ba-b1a7-2dd432f3b34d)

## Update
Use the same grey as documents category label for job type label as a standard.

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment]
@kevindherman this is up for testing on the links above now and going to all staging sites as we speak.

**Comment by curtismchale** [comment]
@kevindherman updated to the grey. I'm going to deploy this to the live sites as well.

**Comment by kevindherman** [comment]
@curtismchale awesome.

**Comment by curtismchale** [comment]
Deployed

Composer: https://github.com/proudcity/wp-proudcity/releases/tag/2024.04.25.0918
Build: https://github.com/proudcity/proud-recipes/releases/tag/2024.04.25.0918
