### ISSUE TITLE
WP Rocket license disconnected

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2547]
## Source
https://www.munford.com/

* [Support ticket](https://proudcity.zendesk.com/agent/tickets/6924)

## Describe the bug
WP rocket having an issue validating license for this instance:

https://www.munford.com/wp-admin/options-general.php?page=wprocket
![Screen Shot 2024-05-06 at 12 34 28 PM](https://github.com/proudcity/wp-proudcity/assets/6032426/78e38289-a2e0-4fb7-ace7-bf6c87c81eae)

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment]
@kevindherman I just clicked the button to validate the license and it works now. Was there any other issue that needed to be resolved?

I also spot checked 3 other sites and they continue to work as expected.

**Comment by kevindherman** [comment]
Clearing the site cache for the customer got a permission error: 

![Screen Shot 2024-05-06 at 2 10 45 PM](https://github.com/proudcity/wp-proudcity/assets/6032426/88232e0d-88b0-40ba-bd66-213870b755c2)
![Screen Shot 2024-05-06 at 2 10 57 PM](https://github.com/proudcity/wp-proudcity/assets/6032426/db092afb-14cd-4cfd-ac09-27456880a8e9)

**Comment by kevindherman** [comment]
@curtismchale can create a new issue if that's preferred?

**Comment by kevindherman** [comment]
created a new one: https://github.com/proudcity/wp-proudcity/issues/2548
