### ISSUE TITLE
Clear site cache menu option permission issue

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2548]
## Builds

- [staging](https://console.cloud.google.com/cloud-build/builds;region=global/1d7063c1-2fb0-4032-809c-968db0c86084?project=proudcity-1184)
- [master](https://console.cloud.google.com/cloud-build/builds;region=global/7475e742-4311-4300-84da-70339d276a86?project=proudcity-1184)

## Source
https://www.munford.com/

* [Support ticket](https://proudcity.zendesk.com/agent/tickets/6924)

## Describe the bug
When you click on clear site cache from tools, you get permission error:
Clearing the site cache for the customer got a permission error: 

![Screen Shot 2024-05-06 at 2 10 45 PM](https://github.com/proudcity/wp-proudcity/assets/6032426/88232e0d-88b0-40ba-bd66-213870b755c2)
![Screen Shot 2024-05-06 at 2 10 57 PM](https://github.com/proudcity/wp-proudcity/assets/6032426/db092afb-14cd-4cfd-ac09-27456880a8e9)

## Additional context
Notified as part of: https://github.com/proudcity/wp-proudcity/issues/2547
This worked before: https://github.com/proudcity/wp-proudcity/issues/2086

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment]
Deployed

Composer: https://github.com/proudcity/wp-proudcity/releases/tag/2024.05.30.1110
Builds: https://github.com/proudcity/proud-recipes/releases/tag/2024.05.30.1110
