### ISSUE TITLE
PA BETA: footer match example.proudcity.com

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#255]

**Comment by kevindherman** [comment]
@jlyon can you have the footer for https://palo-alto-ca.proudcity.com match example.proudcity.com

PA
![screenshot 2016-03-23 17 46 48](https://cloud.githubusercontent.com/assets/6032426/14001985/5af983d0-f11f-11e5-88dd-c297c32226f5.png)

Example
![screenshot 2016-03-23 17 46 58](https://cloud.githubusercontent.com/assets/6032426/14001986/5afcadf8-f11f-11e5-863d-9f289f6b2219.png)

**Comment by jlyon** [comment]
Updated this. In the future, the widgets in the footer can be edited at Customize > Widgets > Footer (https://palo-alto-ca.proudcity.com/wp-admin/customize.php?return=%2Fwp-admin%2Fadmin.php%3Fpage%3Dgf_edit_forms)

![screenshot from 2016-03-23 15 01 17](https://cloud.githubusercontent.com/assets/550909/14002336/9ce51712-f108-11e5-8cba-0092a908de67.png)
