### ISSUE TITLE
Go .gov panel

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2561]
**Source**
The source of the issue (ex: Customer: #CustomerName#).

LF

**Is your feature request related to a problem? Please describe.**

Would be great to start nudging non .gov customers to move to .gov.

**What feature would you like to improve**
A clear and concise description of the current feature.

N/A

**Describe the solution you'd like**

- [ ] Add panel to dashboard (would be great if this was conditional based on if they don't have .gov)

Panel:
* Icon: https://fontawesome.com/icons/building-columns?f=classic&s=solid
* Color: Black?
* Head: Go .gov
* Description: Get an official government domain.
* Button text: Go .gov
* Link: https://help.proudcity.com/dotgov

**Additional context**

**Comment by curtismchale** [comment]
This is done with #2588
