### ISSUE TITLE
my.proudcity.com my sites homepage tiles are not updating

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2563]
## Source
KH and Williams County

## Describe the bug
The image of the homepage that displays for each site are not updating and in new sites, are broken.

## To reproduce
1. Go to my.proudcity.com
2. Click refresh on top of homepage image
3. New image never loads
4. Or see new sites have broken image

## Expected behavior
Homepage image should load newest version

## Screenshots
<img width="1258" alt="Screen Shot 2024-06-06 at 10 32 39 AM" src="https://github.com/proudcity/wp-proudcity/assets/6032426/e2f54066-509a-4cc0-a358-0701caa9f742">

## Additional context
It would be great if there was a quick fix so that the image would update. If there is an alternative that's faster to just display the site's logo or another determined image, I'm fine with a faster alternative.

## QA

Notes:

* 

Links:

*

**Comment by kevindherman** [comment]
@jlyon do you think this is a quick thing to update or do you recommend coming up with an alternative?

**Comment by curtismchale** [comment]
@kevindherman we're sort of going to talk about this in our meeting today as we talk about the issue with updating Auth0.

**Comment by curtismchale** [comment]
@kevindherman I'm closing this since we're updating the PC dashboard and the tech that updates the images won't even be the same.
