### ISSUE TITLE
Create starter child theme (wp-proud-theme-starter)

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#258]
Ties into #251.

Docs: https://codex.wordpress.org/Child_Themes

**Comment by jlyon** [comment]
https://github.com/proudcity/wp-proud-theme-starter

**Comment by jlyon** [comment]
@aschmoe let's talk about this w you get back.

@todos:
- [ ] Get gulpfile watching
- [ ] Refine enqueus in functions.php

**Comment by jlyon** [comment]
@aschmoe also if we could throw this in the release that would be dopeee

**Comment by jlyon** [comment]
ties into #251, https://docs.google.com/document/d/1oMqr6QJhUkWdV6E3poxLTaOvGyY0SccKd5irDFJKCFw/edit#

**Comment by jlyon** [comment]
@aschmoe did this all make it into release 1.3.0 or does it still need work?

**Comment by aschmoe** [comment]
Good to go


On Tue, Apr 5, 2016 at 5:14 PM, Jeff Lyon <notifications@github.com> wrote:

> @aschmoe <https://github.com/aschmoe> did this all make it into release
> 1.3.0 or does it still need work?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/258#issuecomment-206043349>
>



-- 
Alex Schmoe
Senior Web Developer
Albatross Digital

www.albatrossdigital.com | alex@albatrossdigital.com | W 720.663.0581 | C
206.240.1801

**Comment by jlyon** [comment]
:thumbsup:
