### ISSUE TITLE
Remove post field options from gravity forms across platform

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2580]
## Builds

- [staging](https://console.cloud.google.com/cloud-build/builds;region=global/df2bc9fe-319d-4c97-b12d-2efe7eff5348?project=proudcity-1184)
- [prod](https://console.cloud.google.com/cloud-build/builds;region=global/535718ba-ecc6-4c29-9ccb-50f55a645d66?project=proudcity-1184)

Post fields aren't used for our customers. Some customers are unintentionally using post fields in gravity forms which then creates a draft news post for each entry. 

[Palmview](https://cityofpalmview.com/) struggles with this the most and has 4000 draft news posts because of it. 

If post fields can be disabled across the platform that would be awesome.

**Comment by kevindherman** [comment]
@curtismchale want to put this on your radar, if it's a quick item it would be a good one to knock off. I'm hoping it's a setting change.

**Comment by curtismchale** [comment]
@kevindherman I can disable creation of a new post easily with the [`gform_disable_post_creation`](https://docs.gravityforms.com/gform_disable_post_creation/) filter. That doesn't remove the fields but does stop any posts from being created if someone puts a Post field in by accident.

It also doesn't look too hard to remove fields [with this code](https://community.gravityforms.com/t/i-would-like-to-remove-the-name-field-from-the-form-editor/16077/2). I was planning on doing the #2581 ticket tomorrow so I could bundle this in to the same update and push both at the same time.

**Comment by curtismchale** [comment]
@kevindherman this is on beta for testing now. I won't be deploying it until I get the icons tomorrow.

**Comment by curtismchale** [comment]
Deployed

Composer: https://github.com/proudcity/wp-proudcity/releases/tag/2024.07.25.1035
Builds: https://github.com/proudcity/proud-recipes/releases/tag/2024.07.25.1035
