### ISSUE TITLE
Add X (formerly Twitter) icon

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2581]
## Builds

- [staging](https://console.cloud.google.com/cloud-build/builds;region=global/df2bc9fe-319d-4c97-b12d-2efe7eff5348?project=proudcity-1184)
- [prod](https://console.cloud.google.com/cloud-build/builds;region=global/535718ba-ecc6-4c29-9ccb-50f55a645d66?project=proudcity-1184)

## Source

**Is your feature request related to a problem? Please describe.**

Don't see the X logo icon in the icon picker. Good to add now that there's more adoption.

* https://fontawesome.com/icons/x-twitter?f=brands&s=solid
* https://fontawesome.com/icons/square-x-twitter?f=brands&s=solid

**What feature would you like to improve**
A clear and concise description of the current feature.

Icon widget

**Describe the solution you'd like**

Add X icon.

**Additional context**

**Comment by curtismchale** [comment]
@lukefretwell this is relatively quick and I can do it tomorrow morning before the site launch since this is a week I should be looking at Github issues.

**Comment by curtismchale** [comment]
Deployed

Composer: https://github.com/proudcity/wp-proudcity/releases/tag/2024.07.25.1035
Builds: https://github.com/proudcity/proud-recipes/releases/tag/2024.07.25.1035
