### ISSUE TITLE
Create script exception for Wilmington OH

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2584]
## Source

* [Slack](https://proudcity.slack.com/archives/C04MEBVAV2L/p1722019200176749)

## Describe the bug
[This page](https://wilmingtonohio.gov/job-opportunities/) has a script that is being blocked by CloudFlare and we need to create an exception for it.

**Comment by kevindherman** [comment]
@curtismchale looks good for me. I'll confirm with the client.

**Comment by kevindherman** [comment]
Good with them too.
