### ISSUE TITLE
Add new dashboard widget

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2586]
## Builds

- [staging](https://console.cloud.google.com/cloud-build/builds;region=global/329f9e72-8f14-4f1b-9b18-1a2be436c6f9?project=proudcity-1184)

## Issue
 
- Title: Concierge
- Description: On-demand one-on-one time with ProudCity.
- Icon: https://fontawesome.com/icons/bell-concierge?f=classic&s=solid 
- Color ([reference](https://designsystem.digital.gov/design-tokens/color/system-tokens/)): #c2850c
- Button text: Order concierge
- Button link: https://proudcity.com/concierge

**Comment by curtismchale** [comment]
@lukefretwell @kevindherman what position do you want this in?

**Comment by kevindherman** [comment]
@lukefretwell if we want it to be even I would swap out ProudCity Review and then place the ProudCity Concierge above or below "Site Clean up". What do you think?

cc @curtismchale

**Comment by curtismchale** [comment]
@kevindherman @lukefretwell this is up on `beta` now. I have **not** change the order or removed any other widgets at this point.

**Comment by kevindherman** [comment]
@curtismchale thank you.

@lukefretwell I trust your judgement here, let us know what you think.

**Comment by curtismchale** [comment]
Deployed

Composer: https://github.com/proudcity/wp-proudcity/releases/tag/2024.08.21.1343
Builds: https://github.com/proudcity/proud-recipes/releases/tag/2024.08.21.1343
