### ISSUE TITLE
Add dashboard widget (ProudCity DotGov)

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2588]
## Builds

- [staging](https://console.cloud.google.com/cloud-build/builds;region=global/b474ebb2-66d8-4158-9482-0675dbb0171d?project=proudcity-1184)
- [prod](https://console.cloud.google.com/cloud-build/builds;region=global/e8c27d4b-6425-422e-ac88-13466988e5cd?project=proudcity-1184)

## Plugins

- `wp-proud-dashboard`
- `wp-proud-admin-theme`

## Issue
- [x] Title: Go .gov
- [x] Description: Get your .gov domain.
- [x] Icon: `<i class="fa-solid fa-landmark"></i>`
- [x] Color: #005ea2
- [x] Button text: Go .gov
- [x] Button link: https://help.proudcity.com/dotgov
- [x] Location: Below concierge

**Comment by curtismchale** [comment]
@lukefretwell @kevindherman Is this the layout you want for the widgets? This is **not** on beta and only running locally at the moment.

![image](https://github.com/user-attachments/assets/b469ae1b-3d37-4e5c-98c3-5b2d8244b419)

**Comment by curtismchale** [comment]
Deployed

Composer: https://github.com/proudcity/wp-proudcity/releases/tag/2024.08.21.1343
Builds: https://github.com/proudcity/proud-recipes/releases/tag/2024.08.21.1343
