### ISSUE TITLE
Document list widget not displaying content

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2596]
## Source

* [[LINK TO SUPPORT TICKET](https://proudcity.zendesk.com/agent/tickets/7081)] (Add 'Customer' label to this issue)

## Describe the bug
Something is wrong with the Documents List widget. See https://cityofpetaluma.org/human-resources-employee-agreements/. Document tables are not showing the checked documents. I tried to fix by deleting the existing table & adding the document list back in. I tried it in MOU 1, and received different error messages. Ultimately, the "fix" worked but it definitely looks like there is a bug. I don't want to have to go into every document list to fix. Thank you!
Link to page with this issue
https://cityofpetaluma.org/human-resources-employee-agreements/

## QA

Notes:

* 

Links:

*

**Comment by kevindherman** [comment]
@curtismchale turning off Elastic solves the issue. I have turned it off temporarily for Petaluma.

**Comment by aschmoe** [comment]
@kevindherman this has been deployed, I'm unclear if every doc that we'd expect to see is here, but looks good to me.

**Comment by kevindherman** [comment]
@aschmoe it does appear to be working as expected .
