### ISSUE TITLE
Data pollution issue with Elastic

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2605]
## Builds

- [staging](https://console.cloud.google.com/cloud-build/builds;region=global/da7a4945-bfc0-4c6f-be52-cd65118e3fc8?project=proudcity-1184)
- [prod](https://console.cloud.google.com/cloud-build/builds;region=global/61bebdec-3de3-42e0-8bdb-747b8f3ba2d4?project=proudcity-1184)

## Source

* [7089](https://proudcity.zendesk.com/agent/tickets/7089)

## Describe the bug
The events page has some events that were not created by a known user and have the date 1969. When we look into the Elastic index the `post_type` is not labelled correctly which means there is no date information and it seems to default to Unix epoch time.

- https://www.santa-ana.org/
- https://www.santa-ana.org/event/fiestas-patrias-parade

## QA

Notes:

* 

Links:

*

**Comment by kevindherman** [comment]
Petaluma is having a similar issue with old page content rather than locations. Here's the support ticket: https://proudcity.zendesk.com/agent/tickets/7090

**Comment by curtismchale** [comment]
This has ended up being a content pollution issue with Elastic search seeing content as the incorrect `post_type` thus it shows as an event. @aschmoe [suggested](https://proudcity.slack.com/archives/C05517XBZ3P/p1726525923242779?thread_ts=1726333296.892769&cid=C05517XBZ3P) the following places as ideas for where we need to modify teaser code as follows.

```
Probably would need halting (if you’re in save_post or doing an autosave) in a couple places:
1. Prevent the WP-Query from happening at all? https://github.com/proudcity/wp-proud-core/blob/master/modules/proud-teasers/proud-teasers.php#L176
2. Prevent the content from being printed https://github.com/proudcity/wp-proud-core/blob/master/modules/proud-teasers/proud-teasers.php#L979
3. Maybe prevent filters from bring printed https://github.com/proudcity/wp-proud-core/blob/master/modules/proud-teasers/proud-teasers.php#L1016
```
I wonder why Elastic is involved at all in showing content in the Event List widget as it has no option to show content from other sites thus shouldn't have elastic involved at all.
