### ISSUE TITLE
Custom pagebuilder layout for Petaluma

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2609]
**Source**
https://cityofpetaluma.org/

* [Support ticket](https://proudcity.zendesk.com/agent/tickets/7103)

**Describe the solution you'd like**
Use this draft page to add to custom pagebuilder layouts as FAQ template

https://cityofpetaluma.org/?page_id=76641&preview=true

**Additional notes**
@curtismchale Petaluma has a couple custom pagebuilder layouts that are just on their site. This would be to add a new one to their layouts. 

Beyond adding this layout request, we do need to update platform layouts so this could help get that process moving.

**Comment by curtismchale** [comment]
@kevindherman If you create the page you want with the widgets you want then send me the link. I need to download it, and add it to their theme and then deploy the change with the new layout available.

**Comment by kevindherman** [comment]
@curtismchale this draft page is the one they want to use: https://cityofpetaluma.org/?page_id=76641&preview=true

**Comment by curtismchale** [comment]
@kevindherman the new template is on the site.
