### ISSUE TITLE
Santa Ana + Petaluma event list bug

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2614]
## Source
Santa Ana https://www.santa-ana.org/events/
* [Santa Ana ticket](https://proudcity.zendesk.com/agent/tickets/7115)
* [Petaluma ticket](https://proudcity.zendesk.com/agent/tickets/7117)
- likely related to #2428  and #2605 as we "fixed" the query to remove the data pollution issue

## Describe the bug
Event list is not displaying in correct order: https://www.santa-ana.org/events/
See event admin dashboard: https://www.santa-ana.org/wp-admin/edit.php?post_type=event
![Screenshot 2024-09-30 at 2 42 54 PM](https://github.com/user-attachments/assets/5de8f46c-afeb-43d2-8975-ecf471414391)

## Additional context
It seems like the recurring events are throwing off the list. I tried to edit one and got database errors. I'm not sure if this is because a specific recurring event is doing something loco or if the entire recurring events tool is off.

## QA

Notes:

* 

Links:

*

**Comment by kevindherman** [comment]
@curtismchale it seems to be specific to event list list widget.

The content list widget displaying events is fine.

**Comment by curtismchale** [comment]
@aschmoe fixed the broken indexing and this seems to be resolved now.
