### ISSUE TITLE
Issue reporting with Gravityforms

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#262]
- [ ] New issue type post type: Title, icon, form
- [ ] Integrate Gravityforms with 311 app
- [ ] Backend: Assign submission to user
- [ ] Create form on plugin install https://www.gravityhelp.com/forums/topic/create-form-programmatically
- [ ] Enable api access on http://localhost:8080/wp-admin/admin.php?page=gf_settings&subview=gravityformswebapi

**Comment by jlyon** [comment]
Workflow tutorial: https://www.stevenhenty.com/gravity-forms-approvals/

**Comment by aschmoe** [comment]
@jlyon re: editing form entires, not seeing easy way to edit from the listing screen, but if we undo the ```display: none;``` on the "view entry" sidebar, we are presented with an edit option

![entries west carrollton wordpress](https://cloud.githubusercontent.com/assets/1634686/14124734/08d13b74-f5bc-11e5-80d7-36fc2a365209.png)

**Comment by jlyon** [comment]
Fixed the hidden edit button with #267.

**Comment by jlyon** [comment]
Made good progress on this in this release. It should be ready in Release 1.4.0.

**Comment by aschmoe** [comment]
@jlyon this is mostly/completely done yes?
