### ISSUE TITLE
Custom pagebuilder layout for Petaluma

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2629]
https://cityofpetaluma.org/

[Support ticket](https://proudcity.zendesk.com/agent/tickets/7211)

@curtismchale Petaluma updated this page and are hoping to have the custom layout template you 

You recently added a new custom layout to Petaluma: https://github.com/proudcity/wp-proudcity/issues/2609

They'd like to update that layout with this updated page: https://cityofpetaluma.org/new-faq-page-template/

**Comment by curtismchale** [comment]
Deployed
