### ISSUE TITLE
MONITORING: Chat button a little large on backend

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#265]

**Comment by aschmoe** [comment]
![edit page west mead township wordpress](https://cloud.githubusercontent.com/assets/1634686/14116977/4bc297e0-f597-11e5-840d-9df26755fdc1.png)

**Comment by jlyon** [comment]
Noticed this yesterday too.  Just a little...

**Comment by aschmoe** [comment]
@jlyon can't replicate this now, locally or on server... weird

**Comment by jlyon** [comment]
@kevindherman have you seen this at all recently?

**Comment by kevindherman** [comment]
@jlyon have not.
