### ISSUE TITLE
Style gravityforms frontend (cont...)

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#268]
- [x] See #222, are there item we still need to do from that list?
- [x] Date popup
- [x] For AJAX form submits, should we tweak the formatting on error/success msgs (attached)?
- [x] Time field colin (attached)
- [x] in a field collection, after editing a field, it get's more padding (attached from https://www.westcarrollton.org/building-permit-example/)

![screenshot from 2016-03-28 13 55 24](https://cloud.githubusercontent.com/assets/550909/14127324/d13d4544-f5cb-11e5-9726-12f03bc4e168.png)

![screenshot from 2016-03-29 16 15 41](https://cloud.githubusercontent.com/assets/550909/14127331/d5b5dd48-f5cb-11e5-91fd-b169f7ffe9f0.png)

![screenshot from 2016-04-04 17 59 49](https://cloud.githubusercontent.com/assets/550909/14268388/3051bf16-fa8f-11e5-8eb9-17956128ca5f.png)

**Comment by jlyon** [comment]
@aschmoe think we can get this into the release tom?

**Comment by aschmoe** [comment]
Yeah should be able to get these

**Comment by aschmoe** [comment]
> See #222, are there item we still need to do from that list?

Moved responsive into separate #277 so feel comfortable closing
