### ISSUE TITLE
/start quote recs

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#269]
Here's some recommendations on cleaning up the start page:

Sequence order:

* Get free BETA
* Pricing
* Compare
* Get started
* Questions?

Recommendations:

* change heading to 'Make #cityname# proud#
* change 'CMS' to 'Updated'
* remove (WordPress)
* change 'initial dev costs' to Set-up
* change 'mobile-responsive' to 'mobile-friendly'
* Secure: removed 'forced'
* Get started: 'Request free city BETA (we'll send in 24 hours)
* Under 'Current' change 'Visit website' to their URL and our to '#cityname DEMO'
* Pricing: make 'Get quote' button bigger
* Quote page: consolidate share and print together
* Buttons: keep consistent without city name in

**Comment by aschmoe** [comment]
> change heading to 'Make #cityname# proud#
done

> change 'CMS' to 'Updated' + remove (WordPress)
Used "software up-to-date"

> change 'initial dev costs' to Set-up
done
> change 'mobile-responsive' to 'mobile-friendly'
done
> Secure: removed 'forced'
changed to "Secure everywhere"

> Get started: 'Request free city BETA (we'll send in 24 hours)
@lukefretwell was a little confused about this

> Under 'Current' change 'Visit website' to their URL and our to '#cityname DEMO'
Done

> Pricing: make 'Get quote' button bigger
Done, changed to Print Quote
