### ISSUE TITLE
Google analytics dashboard widget

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#270]
https://example.proudcity.com/analytics/

The GA dashboard widget doesn't embed the analytics like the backend. It would be great to be able to create an /analytics page so the public can view this info.

![screenshot 2016-04-01 16 25 23](https://cloud.githubusercontent.com/assets/6032426/14219121/798e3cce-f826-11e5-9131-ffb965983306.png)

**Comment by jlyon** [comment]
Will take some work, but definitely something we can do once we launch calypso.
