### ISSUE TITLE
SO page builder Add new popup errors

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#273]
I think these two are related. JS err:
```
Uncaught TypeError: Cannot read property 'title' of null
```

- [x] Search not working
- [x] First widget is blank

**Comment by jlyon** [comment]
hmm, this doesn't seem to be happening for me locally. @aschmoe did you do anything for this?

**Comment by aschmoe** [comment]
@jlyon where can I find this?

**Comment by jlyon** [comment]
@aschmoe sorry, I mean site origin page builder (changed issue title).  Click Add Widget on https://www.westcarrollton.org/wp-admin/post.php?post=3478&action=edit.  I can dig into this more tomorrow. I think I might have actually fixed it earlier this sprint w you were gone and just forgotten.

**Comment by jlyon** [comment]
Fixed this. It was MC4WP_Form_Widget (the old Mailchimp plugin pre-gravityforms)
