### ISSUE TITLE
Search: Clicking on autocomplete should bring up Actions box

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#28]
1. Search for Water
2. Click on Pay water bill answer
Result: https://west-carrollton-oh.proudcity.com/?post_type=question#/038;p=272

Expected: Should bring up 311 box

**Comment by jlyon** [comment]
noticed that the right sidebar isn't pulling correctly when you click these links

**Comment by aschmoe** [comment]
yeah looks like parent terms are getting a little confused, only some of the links act this way (BMV links for instance)... will investigate.

**Comment by aschmoe** [comment]
Figured this out, was using parent term as slug, now using child.
