### ISSUE TITLE
Proud Admin: whitespace at top where messages should be

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#286]
Seems like prob the Bootstrap code is hiding this 

- [ ] Make messages show
- [ ] Force hide messages for some roles?

**Comment by aschmoe** [comment]
I noticed there are some persistent ones from cache plugin on the examples, ect

**Comment by jlyon** [comment]
Hid this for non-admin roles with this css.  We may want to revisit if this causes issues.
```
// Hide the update messages
body:not(.role-admin) {
  .update-nag,
  .updated {
    display: none;
  }
}
```
