### ISSUE TITLE
WC: mailchimp integration issues

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#289]
The two newest entries on the "get updates" form did not feed into mailchimp.

**Comment by kevindherman** [comment]
https://www.westcarrollton.org/wp-admin/admin.php?page=gf_entries&id=1

![screenshot 2016-04-08 17 00 15](https://cloud.githubusercontent.com/assets/6032426/14397477/8b9c7040-fdab-11e5-9f1d-c1a635c0fd47.png)

**Comment by kevindherman** [comment]
@jlyon the first submission to not make it over to mailchimp was on 4/4 as a reference point.

**Comment by jlyon** [comment]
@kevindherman is this still an issue, or can we close?

**Comment by kevindherman** [comment]
@jlyon close.
