### ISSUE TITLE
WC: add editor account

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#290]
New editor account to manage forms:
cdamron@westcarrollton.org

**Comment by kevindherman** [comment]
@jlyon  This person is going to managing the building application forms and their payments. They would need editor level permissions to manage those services, correct?

**Comment by kevindherman** [comment]
@jlyon @aschmoe can one of you add this first thing this morning? They have a meeting scheduled at 1pm eastern to test their internal workflow.

**Comment by jlyon** [comment]
Created this, sent email to her.

**Comment by kevindherman** [comment]
Thank you.

On Mon, Apr 18, 2016 at 12:40 PM, Jeff Lyon <notifications@github.com>
wrote:

> Created this, sent email to her.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/290#issuecomment-211463827>
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
