### ISSUE TITLE
Come up with solution for page titles

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#3]

**Comment by jlyon** [comment]
Make it so titles are hidden and pages are full-width for all SO pages.

**Comment by jlyon** [comment]
q for alex: do we want to get rid of this file and do this all in the theme?

**Comment by jlyon** [comment]
I think this is all set (we hide titles, set it to full width if SO is enabled).  Any thoughts @aschmoe, or should we close?
