### ISSUE TITLE
WC: GA not tracking users

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#300]
I don't think GA is tracking users. They're showing no traffic and tax season is usually a busy time on the website.

**Comment by kevindherman** [comment]
Here's a screenshot of the dashboard:

![screenshot 2016-04-15 14 32 58](https://cloud.githubusercontent.com/assets/6032426/14571828/6326bc56-0319-11e6-9446-a0a98ba61127.png)

**Comment by jlyon** [comment]
I think you're looking at the wrong account.  The correct account is UA-74236029-1, which is under the West Carrollton account, not the ProudCity account.
![screenshot from 2016-04-15 12 14 09](https://cloud.githubusercontent.com/assets/550909/14572431/a428dab0-0303-11e6-903d-37edb0f720da.png)

You and Erika are both members:
![screenshot from 2016-04-15 12 14 09](https://cloud.githubusercontent.com/assets/550909/14572436/ad1849d0-0303-11e6-9501-3796e79df6c6.png)

Here's a PDF report. You can see the traffic has been up this week.
[Analytics All Web Site Data Audience Overview 20160315-20160414.pdf](https://github.com/proudcity/wp-proudcity/files/221605/Analytics.All.Web.Site.Data.Audience.Overview.20160315-20160414.pdf)

**Comment by kevindherman** [comment]
@jlyon she was definitely looking at and getting email alerts from the old accounts so I think we should delete them.

That's great the new dashboard is going out next week.

Re-assigning to you, this can be closed out.
