### ISSUE TITLE
WC: same day event not posting to /events

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#301]
WC created the event "Tax Day Extended Hours" which shows in the dashboard but not on the /events page.

https://www.westcarrollton.org/wp-admin/post.php?post=3655&action=edit

**Comment by kevindherman** [comment]
@jlyon @aschmoe this is a high priority item since it's a tax day announcement.

**Comment by jlyon** [comment]
This was because the event started at 7:30am (which was in the past), and we are currently filter out events that have already started.  @aschmoe perhaps we should change this logic. I'll create another issue.
