### ISSUE TITLE
Show events that have already started but aren't over yet

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#302]
See #301

- [ ] Show events that have already started but aren't over yet 
- [ ] Alter time format on event list teasers from "06:00 pm" to "6:00 pm"

**Comment by kevindherman** [comment]
@jlyon @aschmoe the event that WC created that started this issue has disappeared again  from the front-end. It's supposed to expire at 6pm est so I'm not sure what's going on.

**Comment by aschmoe** [comment]
Switched over to use end time wp-proud-core tag 1.3.3

**Comment by aschmoe** [comment]
@kevindherman fixed this for now by setting end date until tonight.  @jlyon I think we have some issues with server timezone on WC prod server

**Comment by aschmoe** [comment]
#308 is spiritual successor to this issue

**Comment by jlyon** [comment]
#308 is about payments. Did you mean something else?

**Comment by jlyon** [comment]
#307 is spiritual successor to this issue

**Comment by aschmoe** [comment]
So spiritual
