### ISSUE TITLE
Add elected official template

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#304]

**Comment by lukefretwell** [comment]
For mayors, council members.

**Comment by jlyon** [comment]
Example: http://myreps.datamade.us/

**Comment by jlyon** [comment]
@kevindherman @lukefretwell  do people want something more than  the Contact post type (ie https://www.cityofsanrafael.org/contacts/mayor-gary-phillips/)?

**Comment by lukefretwell** [comment]
@jlyon I think you can close. I did add some thoughts on the contact page:

https://github.com/proudcity/wp-proudcity/issues/1049

**Comment by kevindherman** [comment]
@jlyon I agree with @lukefretwell
