### ISSUE TITLE
Event listings need to work well with all day events

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#307]
Currently all-day-events defaults to 12:00am start and end times, which makes it difficult to query for.   A fix was pushed in proud-core 1.3.5 that compares end of event to greater than 12:00am (just checks if event ends past the beginning of the day).  This is mostly acceptable but will show events that have passed that day.

Notes
- Attempts to add conditional meta_query "or" statements led to impossibly slow inner joins... possibly investigate
- Can write sql query manually, but will need to figure out paging
-  Probably easiest would be to modify all-day to use 11:59:59 as end time

**Comment by jlyon** [comment]
@aschmoe is this still an issue? move to backlog?
