### ISSUE TITLE
WC: amount in payment link not working

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#308]
Erika changed the amount in this payment link to .25 but when you navigate to the payment page the price is $150 (plus fees).

**Comment by jlyon** [comment]
@kevindherman I can't replicate this.

![screenshot from 2016-04-19 12 18 27](https://cloud.githubusercontent.com/assets/550909/14652377/dfb94420-0628-11e6-8b79-47c556f4a0df.png)

**Comment by kevindherman** [comment]
@jlyon must be a cache thing because when I use the link provided in chrome I get $150 but it worked correctly in FF.

Realized I didn't provide their link, sorry about that:


https://www.westcarrollton.org/application-payment/?amount=.25&type=Building+Permit&fname=Erika&lname=Matt&url=https://www.westcarrollton.org/wp-admin/admin.php?page=gf_entries%26view=entry%26id=4%26lid=21

**Comment by jlyon** [comment]
Hmm, I'm seeing .25 with the link above in both Chome (incognito) and FF. Asking Alex now. We might need to do a screenshare.

**Comment by jlyon** [comment]
Is this still an issue @kevindherman

**Comment by kevindherman** [comment]
@jlyon you realized that when copy/pasting the payment link from the notification email into a new email correspondence with an end-user that the hyperlink wasn't the same as the unique payment link. I directed WC to make sure that the payment link and the hyperlink are in fact the same which solved the problem.

This issue should have a better fix with the upcoming workflow logic.

**Comment by jlyon** [comment]
Ahh, right. Remember this now.
