### ISSUE TITLE
Event details shows blank page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#315]
When you select an event from the homepage or /events page the event detail is a blank page. 

This is happening across the platform.

**Comment by kevindherman** [comment]
![screenshot 2016-04-20 16 01 37](https://cloud.githubusercontent.com/assets/6032426/14688575/4a3f529c-0711-11e6-95e0-ae6c114571dd.png)
![screenshot 2016-04-20 16 01 25](https://cloud.githubusercontent.com/assets/6032426/14688576/4a3f81d6-0711-11e6-9e47-7c6dbe0809e5.png)

**Comment by aschmoe** [comment]
This was an errant debug call from the release.  Hotfix wp-proud-theme:1.4.1
