### ISSUE TITLE
Documents preview on webform

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#317]
When preview is selected from a webform and the PDF shows up change "preview" button to "form". I think this will make the toggling feature more clear.

https://de-leon-tx.proudcity.com/documents/rv-park-registration/#

*This is a suggestion not a bug fix

**Comment by kevindherman** [comment]
![screenshot 2016-04-26 10 36 55](https://cloud.githubusercontent.com/assets/6032426/14822002/e1cee504-0b9a-11e6-9b0f-8a8d01738505.png)

![screenshot 2016-04-26 10 36 46](https://cloud.githubusercontent.com/assets/6032426/14822003/e1cf843c-0b9a-11e6-86d5-99ee44425ded.png)

**Comment by jlyon** [comment]
@aschmoe i can take care of this one.
