### ISSUE TITLE
WC: radio buttons cut off on forms

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#322]
radio buttons are cut off slightly on the left on webforms:

![screenshot 2016-04-27 12 38 17](https://cloud.githubusercontent.com/assets/6032426/14860091/1c361c6e-0c75-11e6-9ab2-06801cf1e917.png)

https://www.westcarrollton.org/documents/electrical-permit/

**Comment by aschmoe** [comment]
@kevindherman I tested this on a couple different os/browsers... assuming its mac, but could I get more info?

**Comment by kevindherman** [comment]
@aschmoe looked into this some more. The buttons cutting off only happens when logged in so I think we should figure it out but not the highest priority.

**Comment by aschmoe** [comment]
@kevindherman could I still get browser / os info?

**Comment by kevindherman** [comment]
@aschmoe chrome Version 50.0.2661.102 (64-bit)

OS X El Capitan 10.11.5 (15F34)

**Comment by aschmoe** [comment]
@kevindherman testing this locally + on the link provided: logged in on chrome 50 + 51 (latest on Mac) on browser stack, and not seeing issue.

Going to mark as resolved.  Can reopen if needed

**Comment by kevindherman** [comment]
@aschmoe This can be resolved. I think I mentioned it in another issue but I finally figured out that the radio buttons were only being cut-off in Chrome when logged in and fine when anon.
