### ISSUE TITLE
Broken icon image on /documents page when item is only a form

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#325]
When a document is only a form (and not a document) on the /documents page the doc icon shows as broken file. 

This happens in FF as anon user. 

https://de-leon-tx.proudcity.com/documents/?filter_categories[]=76

![screenshot 2016-04-27 15 10 14]
(https://cloud.githubusercontent.com/assets/6032426/14864992/85948c76-0c8a-11e6-8915-85a09ab27d5f.png)

**Comment by kevindherman** [comment]
@jlyon @aschmoe the download button doesn't apply here either. Perhaps in these instances that button is either hidden or says "view" or "fill out".

**Comment by jlyon** [comment]
Fixed in #236 (will push next release)
