### ISSUE TITLE
Integrate with Romulus API

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#328]
- [ ] We want to pull the contact ID's from their actual API
- [x] Settings interface

**Comment by jlyon** [comment]
Set this up on WC @kevindherman and wrote a Zendesk article describing how to set it up. We should probably post this as a blog post too. https://proudcity.zendesk.com/hc/en-us/articles/226334587

**Comment by kevindherman** [comment]
@jlyon this is great, I'll review everything this morning. 

One thing, do you mean SR instead of WC?

**Comment by jlyon** [comment]
Yes, sorry SR
