### ISSUE TITLE
Example: content updates

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#330]
- [x] Fix seeclickfix
- [x] Set up payments w forms
- [ ] Add documents?
- [ ] Add documents to example agency
- [x] Rm test1
- [x] Favicon
- [ ] News from blog - 5 to watch
- [ ] Events: our webinars
- [ ] Answers: claim you beta
- [ ] Add icon format to /govt
- [ ] Look thru agencies
- [ ] Popup
- [ ] somthing weird w search page (see below)

**Comment by aschmoe** [comment]
https://example.proudcity.com/search-site/?term=how+do+I+have#/city/answers

**Comment by jlyon** [comment]
@aschmoe is this still an issue (I dont think so) https://example.proudcity.com/search-site/?term=how+do+I+have#/city/answers?

**Comment by jlyon** [comment]
Moving to Ready - this was done in 775
