### ISSUE TITLE
WM: Adjust lat/long default view on map

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#333]
The lat/long for the services map is too far east. 

Might need to co-work on this for a minute or two to get right.

**Comment by kevindherman** [comment]
Where they want the default should be with Meadville in the top left:

![screenshot 2016-05-04 18 09 24](https://cloud.githubusercontent.com/assets/6032426/15033768/7a6b575a-1223-11e6-924b-e35121e7e894.png)

**Comment by jlyon** [comment]
this should be done for now.

**Comment by kevindherman** [comment]
@jlyon this looks good and can be resolved.
