### ISSUE TITLE
WM: center iconset when there are less than 4

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#334]
Can the iconsets on /residents, /visitors and /businesses be centered if they have less than the usual 4 options? Is this something I can accomplish with some coaching?

https://west-mead-pa.proudcity.com/residents/

![screenshot 2016-05-04 18 12 17](https://cloud.githubusercontent.com/assets/6032426/15033799/ed6bb36c-1223-11e6-9343-d1e6ad4f34ce.png)

**Comment by aschmoe** [comment]
Dupe #371
