### ISSUE TITLE
Workflow: GravityFlow

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#335]
I think this is probably our best best for add the workflow stages for payments with registrations https://github.com/proudcity/proud-roadmap/issues/25 and 311 issue requests https://github.com/proudcity/proud-roadmap/issues/4 with our forms: https://gravityflow.io/.

License fees: 
* 1 site: $97
* 5 sites: $227
* 20 sites; $337
* 50 sites + addl features: $397 https://gravityflow.io/extensions/advanced-extensions/
Annual renewals: 30% off

@kevindherman to look at budget to see if/when we can afford this.

**Comment by kevindherman** [comment]
@jlyon if you think it's the right move for the product, lets do it.

**Comment by jlyon** [comment]
Sent to them:

Hello,

Is it possible to upgrade accounts if we try the single site license and decide we want to upgrade to the Ultimate plan (and only want to pay the $300 difference)?

Thanks,
Jeff

**Comment by jlyon** [comment]
Hi Jeff,

Absolutely! You can do this any time from your account page and the amount you paid will be deducted from the price of the new license.

Do let me know if you have any further questions or comments.

Cheers,
Steve

**Comment by kevindherman** [comment]
Cool.

**Comment by jlyon** [comment]
@kevindherman: this is enabled on  SR. Go to the form edit page, click on Settings > Workflow.  I set up an example workflow on https://san-rafael-ca.proudcity.com/wp-admin/admin.php?page=gf_edit_forms&view=settings&subview=gravityflow&id=5.

demo videos: https://gravityflow.io/
Full docs: http://docs.gravityflow.io/

**Comment by jlyon** [comment]
@kevindherman I updated the permissions.  I only gave Editors access, but basically gave them access to everything.  We'll want to refine gravityflow permissions when we tackle #340.

@todo: Put gravityflow permissions into code @jlyon

**Comment by jlyon** [comment]
Still need to put permissions in code, but otherwise this is good to go.

**Comment by kevindherman** [comment]
@jlyon been playing around with it and it's pretty robust. I want to get more familiar with it before I show Erika because I think they're definitely going to want it.

**Comment by jlyon** [comment]
@kevindherman cool. Lmk if you have any questions

**Comment by jlyon** [comment]
I added the above permission definitions in code.  Further fleshing out of perms can happen in #340.  Marking this as ready.
