### ISSUE TITLE
WM: strange alert when adding new location

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#341]
![screenshot 2016-05-06 16 12 24](https://cloud.githubusercontent.com/assets/6032426/15116417/3efb6582-15d1-11e6-9e44-244061250ae0.png)

**Comment by jlyon** [comment]
fixed this

**Comment by jlyon** [comment]
Released platform-wide as hotfix 1.5.3

**Comment by kevindherman** [comment]
@jlyon was the strange alert because of the zoom level?
