### ISSUE TITLE
On /documents change download button to link to doc detail

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#342]
https://www.westcarrollton.org/documents/?filter_categories[]=77

On ^ page some of the forms are PDF only while others are an online form and PDF. The download button automatically downloads the PDF while the link in the doc title which isn't as obvious goes to the documents detail where the webform is. Because the link in the title isn't as obvious, users are missing the webform opportunity. 

Erika mentioned there has been some confusion over this since the webforms have gone live. I think having the download link go to the document detail rather than automatically downloading would help.

**Comment by jlyon** [comment]
I made the following changes:
* with #236, we show a globe icon if there is a  form version of the document
* if there is a form version of the document, the title when you hover over the icon or the document name is "Complete this form online" (attached)
* The file icon is now linked (it wasn't before).


This will be pushed w the next release

**Comment by kevindherman** [comment]
@jlyon The document link, icon and download button all automatically download the doc now across the platform. 

Before when you clicked the document link it would go to the document detail, now it immediately downloads. 

![screenshot 2016-05-19 13 30 17](https://cloud.githubusercontent.com/assets/6032426/15403199/dc6751fe-1dc5-11e6-87d6-b8110ad1d060.png)

Related, the document detail isn't displaying the PDF at all:

![screenshot 2016-05-19 13 29 15](https://cloud.githubusercontent.com/assets/6032426/15403176/bb092d20-1dc5-11e6-9e1a-376aa59346a0.png)

![screenshot 2016-05-19 13 29 06](https://cloud.githubusercontent.com/assets/6032426/15403177/bb0a27de-1dc5-11e6-8cc4-ac7d3322e3e5.png)

**Comment by kevindherman** [comment]
I also just noticed that the downloads failed:

![screenshot 2016-05-19 16 11 59](https://cloud.githubusercontent.com/assets/6032426/15408119/876d72f2-1ddc-11e6-920f-ea069f5ad88e.png)

**Comment by jlyon** [comment]
Fixed this and applied it platform-wide as hotfixes 1.6.2 and 1.6.3.
