### ISSUE TITLE
WC: Adding new editor

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#343]
![image001](https://cloud.githubusercontent.com/assets/6032426/15122806/c0ee8142-15ee-11e6-8e65-bd7a2b868a38.png)

@jlyon @aschmoe From the customer:

> The above is the screen I get, and even if I try putting in my correct email and a new password, it still doesn’t accept it.
>  
> Carrie

**Comment by jlyon** [comment]
They should go to my.proudcity.com, click on the signup link at the bottom of that page and use their email address in there. @kevindherman

**Comment by kevindherman** [comment]
This can be closed out.
