### ISSUE TITLE
/government is mispelled as /govenment

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#346]
/government is missing the "r" and is actually /govenment.

https://hinsdale-ma.proudcity.com/govenment/
https://west-mead-pa.proudcity.com/govenment/

The URL is correct on westcarrollton.org/government

**Comment by jlyon** [comment]
Fixed this on these two sites.  To fix it in the future, hit the edit button next to permalink, make the change, and hit Publish.

https://test.westmead.org/wp-admin/post.php?post=149&action=edit
![screenshot from 2016-05-19 22 07 12](https://cloud.githubusercontent.com/assets/550909/15417775/2f8d7a28-1e0e-11e6-8ad5-935a72da04a1.png)
