### ISSUE TITLE
Error logging out from dashboard

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#348]
![screenshot 2016-05-11 11 05 52](https://cloud.githubusercontent.com/assets/6032426/15185803/91cf3a34-1768-11e6-8c3c-e2782181fa75.png)

**Comment by jlyon** [comment]
This was an issue was a problem with logging out, which has been fixed (needed to add urls to new Logout redirect url within the Auth0 dashboard).
