### ISSUE TITLE
Services map not showing all locations

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#352]
On /businesses we created a bunch of layers for local businesses on the services map. However, not all the locations are showing up, usually being cut off around 10 per layer. 

Manufacturing should have about 25 locations but only 10 are showing up on the map. Here's an example of a location that appears to be entered correctly and is not showing up on the map.

https://west-mead-pa.proudcity.com/locations/actco-tool-manufacturing-co/:
![screenshot 2016-05-13 10 07 09]
(https://cloud.githubusercontent.com/assets/6032426/15250469/ea523ae0-18f2-11e6-8cf3-8ee0af5050d6.png)

![screenshot 2016-05-13 10 07 35](https://cloud.githubusercontent.com/assets/6032426/15250472/ea55f086-18f2-11e6-9b55-a06990fda87b.png)

**Comment by jlyon** [comment]
Fixed this and applied as Hotfix 1.5.6 Services map not showing all locations #336.
