### ISSUE TITLE
Change feedback form to Gravityform

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#353]
Where does the typeform go?

**Comment by jlyon** [comment]
Changed the form to a Gravityform.

Applied as Hotfix 1.5.7 Change feedback form to Gravityform #352

**Comment by aschmoe** [comment]
@jlyon did this get applied ? https://warr-acres-ok.proudcity.com/ looks like it still has old typeform...

**Comment by jlyon** [comment]
It should have, but I think Warr Acres might not have been in /var/local/sites.txt then.  They'll get it tomorrow.
