### ISSUE TITLE
WC: Payment link is auto-populating name field with date requested

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#354]
The payment link is auto-populating the name field with date requested in the Senior Citizen Center Reservation Form.

https://www.westcarrollton.org/wp-admin/admin.php?page=gf_edit_forms&view=settings&subview=notification&id=10&nid=56e1da26e94a3

I manipulated the payment link from the first link you built so I'm thinking the tokens are off:

https://www.westcarrollton.org/parks-rec-application-payment/?amount=20&type=Senior+Citizens+Center+Reservation+Application+Payment&fname={Applicant Name (First):17.3}&lname={Applicant Name (Last):17.6}&url=https://www.westcarrollton.org/wp-admin/admin.php?page=gf_entries%26view=entry%26id={form_id}%26lid={en

**Comment by jlyon** [comment]
@kevindherman are we all set on this after our token screenshare a few weeks ago?

**Comment by kevindherman** [comment]
@jlyon all good.
