### ISSUE TITLE
WM: disable issues wrench icon in header

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#355]

**Comment by jlyon** [comment]
@aschmoe could you look at this one?
```
if (get_option('311_service', 'link') == 'link' &&  empty( get_option('311_link_create', '') ) ) {
  // hide create button
}

if (get_option('311_service', 'link') == 'link' &&  empty( get_option('311_link_status', '') ) ) {
  // hide lookup button
}``

**Comment by aschmoe** [comment]
@kevindherman this is resolved on https://test.westmead.org

**Comment by kevindherman** [comment]
Thanks, I'll let her know.

On Mon, May 16, 2016 at 3:20 PM, Alex Schmoe <notifications@github.com>
wrote:

> @kevindherman <https://github.com/kevindherman> this is resolved on
> https://test.westmead.org
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/355#issuecomment-219520037>
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
