### ISSUE TITLE
Hide SO Panels widgets

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#359]
* Image
* Slider

**Comment by jlyon** [comment]
Also hid (mostly used in action bar/footer, which uses the other panels interface in Customizer):

* Footer logo widget
* Powered by ProudCity widget
* Social links

@aschmoe @kevindherman: Do you think we should rename "Jumbotron hero unit" to something else (maybe that includes "header")?

**Comment by aschmoe** [comment]
@jlyon used to be called 'Page Header' just revert to that?
