### ISSUE TITLE
Open external links in a new tab?

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#36]
https://css-tricks.com/snippets/jquery/open-external-links-in-new-window/

**Comment by jlyon** [comment]
We want this by default, right? Should it be an option?

**Comment by jlyon** [comment]
Make it an option

**Comment by jlyon** [comment]
@kevindherman  set this up on WC.

Added a new "Open external links in a new tab" option on https://west-carrollton-oh.proudcity.com/wp-admin/admin.php?page=proudsettings

**Comment by kevindherman** [comment]
Great.

On Wed, Feb 3, 2016 at 2:24 AM, Jeff Lyon <notifications@github.com> wrote:

> @kevindherman <https://github.com/kevindherman> set this up on WC.
>
> Added a new "Open external links in a new tab" option on
> https://west-carrollton-oh.proudcity.com/wp-admin/admin.php?page=proudsettings
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/36#issuecomment-179062785>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by jlyon** [comment]
issues w translate, add to calendar

**Comment by jlyon** [comment]
fixed issue w addtocalendar, translate was something else.
