### ISSUE TITLE
WM: SSL not setup on test

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#360]
![screenshot 2016-05-16 15 21 48](https://cloud.githubusercontent.com/assets/6032426/15301104/0ae6e52e-1b7a-11e6-83fa-75e4fe8afbe7.png)

**Comment by jlyon** [comment]
Yes, this was intentional because it's a pain to setup SSL for a domain that is only going to be used for one week.  If this is a big issue, I can set up SSL on WM test.

In general, I think we want to get away from changing the url to test.example.com.  Just have the test phase point to their *.proudcity.com domain.  I think that makes sense with our pricing model too.

**Comment by kevindherman** [comment]
Cool, that all sounds good to me.

**Comment by kevindherman** [comment]
@jlyon do you think the 404 error is actually this? https://trello.com/c/XprE0NZT/38-404-error

**Comment by jlyon** [comment]
could have been. ill just add ssl to their test site to avoid these kinds of issues.

**Comment by kevindherman** [comment]
Ok.

In the future I'll make sure they stay on proudcity.com for the test phase.

On Mon, May 16, 2016 at 3:51 PM, Jeff Lyon <notifications@github.com> wrote:

> could have been. ill just add ssl to their test site to avoid these kinds
> of issues.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/360#issuecomment-219527724>
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by kevindherman** [comment]
This got moved to done in Trello so I think we're fine to not do anything.

On Mon, May 16, 2016 at 4:01 PM, Kevin Herman <kevin@proudcity.com> wrote:

> Ok.
>
> In the future I'll make sure they stay on proudcity.com for the test
> phase.
>
> On Mon, May 16, 2016 at 3:51 PM, Jeff Lyon <notifications@github.com>
> wrote:
>
>> could have been. ill just add ssl to their test site to avoid these kinds
>> of issues.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/proudcity/wp-proudcity/issues/360#issuecomment-219527724>
>>
>
>
>
> --
> Kevin Herman
> ProudCity
> 917.873.4666
> ProudCity.com
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by jlyon** [comment]
Set this up on https
