### ISSUE TITLE
Google translate not working in IE 11

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#363]
WA: I have noticed an inconsistency with the Translate link at the bottom of the pages.  It works on my phone, but does not work on my desktop computer.  I know this has to do with Google, but when I click on it I only get an empty box (screen shot attached).

![translate](https://cloud.githubusercontent.com/assets/6032426/15332900/81e32578-1c35-11e6-96a6-7ef2dac6cd92.jpg)

KH: I wasn't able to replicate this in Chrome so I think it's an IE 11 issue.

**Comment by jlyon** [comment]
@aschmoe assigning...
