### ISSUE TITLE
Forms missing credit card option

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#366]
This might be because the paypal integration isn't setup on the test but I noticed it was missing during the demo.

![screenshot 2016-05-17 14 03 06](https://cloud.githubusercontent.com/assets/6032426/15333583/3a03040a-1c38-11e6-912a-cf9b8f9ed8a1.png)

**Comment by jlyon** [comment]
Enabled the PayPal payments pro addon plugin. This option is there now.
