### ISSUE TITLE
WA: Search results page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#367]
If you hit enter after putting search terms into the search box the search results page doesn't come up like the other sites.

![screenshot 2016-05-17 14 05 17](https://cloud.githubusercontent.com/assets/6032426/15333679/c3bf4cb2-1c38-11e6-9739-c1765b8afd50.png)
![screenshot 2016-05-17 14 05 03](https://cloud.githubusercontent.com/assets/6032426/15333680/c3c46468-1c38-11e6-957c-25550ece69dc.png)

**Comment by jlyon** [comment]
@aschmoe can you look into this?

**Comment by aschmoe** [comment]
@jlyon @kevindherman someone replaced [proud_search_shortcode] with some lorem ipsum on the seach page.  I've changed it back on WA, and Example... guessing pretty much every other site has this issue, so will go through them I guess.

**Comment by jlyon** [comment]
Bummer...
