### ISSUE TITLE
Example: Clean up  /government

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#375]
https://example.proudcity.com/government/

Something needs to happen here. It's a little too complicated with the Documents link as an icon button in the left sidebar with all of the agencies being buttons too. And ideas @aschmoe @lukefretwell?

**Comment by jlyon** [comment]
I think adding the search box to the left sidebar would go a long ways (see https://warr-acres-ok.proudcity.com/government/).  Need to add search to the new Agency list widget. @aschmoe ?

**Comment by lukefretwell** [comment]
@jlyon @aschmoe I'd just add 'Documents' to the icons section maybe under a separate 'Resources' section that could include other items. Seeing this page now makes me think we could make it more like 'Residents,' 'Visitors,' etc., where you could have a nice photo of city hall and 'we're serving you' message. If not, I'd just move documents to a separate section.

**Comment by kevindherman** [comment]
I'm hesitant to remove documents from government all together. Documents,
forms and the payments attached to them is a huge deal and big selling
point for us.

On Fri, May 20, 2016 at 11:03 AM, Luke Fretwell <notifications@github.com>
wrote:

> @jlyon <https://github.com/jlyon> @aschmoe <https://github.com/aschmoe>
> I'd just add 'Documents' to the icons section maybe under a separate
> 'Resources' section that could include other items. Seeing this page now
> makes me think we could make it more like 'Residents,' 'Visitors,' etc.,
> where you could have a nice photo of city hall and 'we're serving you'
> message. If not, I'd just move documents to a separate section.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/375#issuecomment-220630794>
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
