### ISSUE TITLE
WC: Form submission error

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#376]
This lady was trying to send in a shelter reservation and it was stating that it is has already been used, and wouldn't let her submit her request?  Do you know why she would be getting this error?

Thanks.

Carrie

![img_0594](https://cloud.githubusercontent.com/assets/6032426/15435419/067cb2a8-1e8a-11e6-8686-c70edf021290.PNG)
![img_0595](https://cloud.githubusercontent.com/assets/6032426/15435420/06806f7e-1e8a-11e6-959a-0553dfbf2eac.PNG)
![img_0596](https://cloud.githubusercontent.com/assets/6032426/15435418/067ca75e-1e8a-11e6-8b40-d5d2ec70bb32.PNG)

**Comment by aschmoe** [comment]
@kevindherman there seems to be an issue where label - values cannot be equivalent for those options.  Tell them we're looking into the cause of issue, but that a TEMP solution is like the one shown below.

![forms west carrollton wordpress](https://cloud.githubusercontent.com/assets/1634686/15440615/462d8b06-1e8b-11e6-9d13-e39eadd56617.png)
