### ISSUE TITLE
WC: Dropdown in form broken

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#377]
This could be related to issue #376.

The dropdown option in the Family Camp Out Registration Form won't all for me to select an item in the preview: https://www.westcarrollton.org/wp-admin/admin.php?page=gf_edit_forms&id=18

I came across in trying to setup the 2% service to work with each item in the dropdown.

![screenshot 2016-05-20 14 34 40](https://cloud.githubusercontent.com/assets/6032426/15437992/139c6312-1e98-11e6-926b-b4ba2ea2fc50.png)

![screenshot 2016-05-20 14 34 19](https://cloud.githubusercontent.com/assets/6032426/15437991/139c2bc2-1e98-11e6-9390-646dd3975f42.png)

**Comment by aschmoe** [comment]
@kevindherman see #376 I've changed the value on this form for now so that it is submittable
