### ISSUE TITLE
WC: SSL is down

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#378]
The SSL is broken for West Carrollton.

![screenshot 2016-05-23 10 28 47](https://cloud.githubusercontent.com/assets/6032426/15474175/a5aacd76-20d1-11e6-92e2-8d2b1bbc2929.png)

**Comment by kevindherman** [comment]
@jlyon @aschmoe this is isolated to WC.

**Comment by jlyon** [comment]
Fixed
