### ISSUE TITLE
DL: Simple heading not full width

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#380]
I was changing all the agencies that didn't have images to the simple heading and then they stopped going full width:

https://de-leon-tx.proudcity.com/departments/economic-development-corporation-edc/

![screenshot 2016-05-25 17 47 42](https://cloud.githubusercontent.com/assets/6032426/15557446/05272a6c-22a1-11e6-8752-69865321fa95.png)

![screenshot 2016-05-25 17 48 00](https://cloud.githubusercontent.com/assets/6032426/15557447/052d7e1c-22a1-11e6-942e-275e225b7145.png)

**Comment by aschmoe** [comment]
Have to set the wrapper element to full width.

**Comment by jlyon** [comment]
Fixed this.  It looks like this was a Panels template that they set up. If you are starting a custom panels layout, you need to edit the row by clicking the wrench icon above the row
![screenshot from 2016-05-25 15 18 30](https://cloud.githubusercontent.com/assets/550909/15558067/1951522a-228c-11e6-91b9-43717b6e8161.png), selecting Layout, and choosing Full Width under Row Layout:
![screenshot from 2016-05-25 15 18 42](https://cloud.githubusercontent.com/assets/550909/15558083/34153040-228c-11e6-86c7-d5b390f63162.png)

**Comment by kevindherman** [comment]
I think this is a permission thing for support@ then because I don't have a
row layout option under 'layout', just padding.


On Wed, May 25, 2016 at 6:20 PM, Jeff Lyon <notifications@github.com> wrote:

> Fixed this. It looks like this was a Panels template that they set up. If
> you are starting a custom panels layout, you need to edit the row by
> clicking the wrench icon above the row
> [image: screenshot from 2016-05-25 15 18 30]
> <https://cloud.githubusercontent.com/assets/550909/15558067/1951522a-228c-11e6-91b9-43717b6e8161.png>,
> selecting Layout, and choosing Full Width under Row Layout:
> [image: screenshot from 2016-05-25 15 18 42]
> <https://cloud.githubusercontent.com/assets/550909/15558083/34153040-228c-11e6-86c7-d5b390f63162.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/380#issuecomment-221725331>
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by jlyon** [comment]
I'm able to see this as support@.  Are you sure you're clicking on the row options (the wrench icon above the row), and not the widget options (what comes up if you click on the edit link in the widget)?

**Comment by kevindherman** [comment]
Ahhhhh, I was editing the widget not the row. Thanks guys.

On Thu, May 26, 2016 at 4:46 PM, Jeff Lyon <notifications@github.com> wrote:

> I'm able to see this as support@. Are you sure you're clicking on the row
> options (the wrench icon above the row), and not the widget options (what
> comes up if you click on the edit link in the widget)?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/380#issuecomment-221989456>
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
