### ISSUE TITLE
WA: search icon from nav pulls up blank page (no search box)

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#386]
https://warr-acres-ok.proudcity.com/#/city/answers

![searchblank](https://cloud.githubusercontent.com/assets/6032426/15610566/dc63f9c6-23f3-11e6-9d51-fc64e4804de2.jpg)

**Comment by aschmoe** [comment]
@kevindherman I think this was a function of some code updates being pushed but not others.  Seems to be resolved.
