### ISSUE TITLE
WA: deleted contact on Dept page reappearing

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#388]
"In the “Parks Department” I have removed the contact email and the Facebook account from the “Edit Department” several times.  However they continue to return every time I go back to the department to view it.  I tried again from home (other time was at the police department) and they are now gone, but the background image of the park bench with leaves does not show up.  If I click on the only link in the menu “Park Facilities” it goes to another page which shows all of the parks on the map (another place where listing locations by category would be useful).  The email address shows up again here under the phone number on the left side.  This is the same email address that I have deleted several times in the department section."

**Comment by jlyon** [comment]
Fixed this issue with the Agency Contact fields and Social fields.
