### ISSUE TITLE
WA: feedback link

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#390]
"The “Feedback” links go to a page titled Feedback.  However, the page does not show anything.  When editing the page there is some HTML type coding that appears in the text box referring to “gravityform”.  I was going to create a form, but it looks like there is already supposed to be something there that is not working."

The gravity form has now been replaced but was only being used on the test bar or new site bar. This is a good catch that the feedback in the footer should have a permanent form.

**Comment by aschmoe** [comment]
@kevindherman for some reason the form was disabled, is good 2 go now
