### ISSUE TITLE
Add fax number to contact info on dept page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#391]
"In the Department contact information section there is no field for Fax number.  This is something that we are asked for very frequently."

Dated but makes sense. Can we add a fax field? I don't think that option is necessary to add on /contacts, maybe just on the specific dept page.

**Comment by jlyon** [comment]
Added fax to the Agency edit form, and added it to the agency  contact widget (agency pages and subpages). I didn't add it to the to the contact table (https://www.westcarrollton.org/contact/) because it's already a little full.

**Comment by kevindherman** [comment]
@jlyon  This request came from Warr Acres, has the fax # option been added to their site or just West Carrollton?

**Comment by jlyon** [comment]
will be added to the platform after the release (tom morn)
