### ISSUE TITLE
WA: jumbrotron slideshow

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#392]
"I tried converting the Jumbotron hero unit to a slider for the “Home” page, but the images are stretched larger than the screen, and the user has to scroll down to see anything."

I know this is how it currently works and we're working on other slider options but I wanted to document this feedback. Alex, do you have any suggestions on a response?

**Comment by aschmoe** [comment]
@kevindherman pretty sure I have fixed this in working on the agency, lets reach back out after release

**Comment by kevindherman** [comment]
@aschmoe will that make it an available option on all jumbotron widgets?

**Comment by aschmoe** [comment]
@kevindherman not sure I entirely follow but slideshow is an option on all of the jumbotron headers.

I feel like he had it positioned elsewhere on the page, and the styling wasn't there for that.

**Comment by kevindherman** [comment]
@aschmoe this has been fixed in the release so we're all good.
