### ISSUE TITLE
WC: location search result goes to blank page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#394]
When you do a search for farmers market one of the options pulls up the slug for location that was created for the map. If you select that search result option, you go to a blank page.

![screenshot 2016-05-27 13 49 08](https://cloud.githubusercontent.com/assets/6032426/15616460/e38642a4-2411-11e6-9b25-62acfe918136.png)

https://www.westcarrollton.org/locations/west-carrollton-farmers-market/

![screenshot 2016-05-27 13 49 20](https://cloud.githubusercontent.com/assets/6032426/15616464/e9b5e56c-2411-11e6-8fc6-bd696260f315.png)

Maybe the solution is to disable locations in the search results.

**Comment by aschmoe** [comment]
#194
