### ISSUE TITLE
WA: form & email notification

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#395]
https://warr-acres-ok.proudcity.com/wp-admin/admin.php?page=gf_edit_forms&id=10

Thanks for the update on emails.  I was wondering if that was the case.  I was able to get the email from the problem reporting form, but the fields do not work at the top. In the settings for the form, under notifications there are several fields that have a drop down to the right to select from the posted form fields. I have some filled in with fields from the posted form and the BCC is just filled in with an email address.  The “Send to Email” and the “Subject” are the only fields that come through.  The email comes from ProudCity  notify@proudcity.com instead of using the fields.  It also did not send the notification to the BCC email address.  The “Message” section works great, and I was able to add the fields submitted using the form.
 
On the same form, “problem reporting” after typing in the field for “Location of concern” and hitting the TAB to go to the next field it jumps to the bottom of the form skipping all the other fields.

**Comment by jlyon** [comment]
I got the first half of this fixed:

fixed (on https://warr-acres-ok.proudcity.com/wp-admin/admin.php?page=gf_edit_forms&id=10):
- set email from to notify@proudcity.com
- fromname works
- replyto works (so you hit reply and it will go to the person that submitted the form)
- all of the fields in the email message are set correctly (including file uploads)

still working on:
- [ ] want to fix it so the from email is forced to be notify@proudcity.com
- [ ] BCC not working correctly
- [ ] On the same form, “problem reporting” after typing in the field for “Location of concern” and hitting the TAB to go to the next field it jumps to the bottom of the form skipping all the other fields.

**Comment by jlyon** [comment]
> BCC issue

This seems to be an issue with gravity forms. I created a help ticket with them. Will track on #411.  Workaround for now: Add all email addresses to the To field, comma delimited.
