### ISSUE TITLE
Address fields for new event missing labels

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#396]
The address fields on the newly added event content type are missing their labels.

https://french-creek-pa.proudcity.com/wp-admin/post-new.php?post_type=event

![screenshot 2016-05-31 11 09 25](https://cloud.githubusercontent.com/assets/6032426/15679570/5cb99430-2720-11e6-88f1-26e03ca7b832.png)

**Comment by jlyon** [comment]
Fixed this in release 1.7.0
