### ISSUE TITLE
Gravityforms: Hide unique entry option for select list, checkboxes, radios

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#397]
https://www.westcarrollton.org/park-shelter-reservation/

Getting the below error:

![screenshot 2016-05-31 16 35 51](https://cloud.githubusercontent.com/assets/6032426/15689726/58232dcc-274e-11e6-97d5-14bc81651134.png)

Also getting the same #395 with after filling in first name and hitting tab it skips to the bottom.

**Comment by kevindherman** [comment]
@jlyon I noticed that "no duplicates" was selected on this field. 

I'm assuming Erika thought that this meant that the user could only select one field and it actually means something else. Is that accurate?

**Comment by jlyon** [comment]
> I'm assuming Erika thought that this meant that the user could only select one field and it actually means something else. Is that accurate?

Yes, it means that that value doesn't exist within all the records, so as soon as 
Weidner Park was selected twice it would throw an error.  (It seems like it shouldn't even be an option for select lists).

**Comment by kevindherman** [comment]
@jlyon yeah, that is confusing. If it can be removed/disabled I think that would be a good idea.

**Comment by jlyon** [comment]
Yah, seems like there isn't a way to do this with css. There might be a way to do it with the gravityforms api, but I'm putting it on the backburner for now.
