### ISSUE TITLE
SR: Add image widget

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#398]
Came up in a live demo: There is no image widget.

- [x] re-enable `$widgets['SiteOrigin_Widget_Image_Widget']` in `wp-proud-core/plugin_override/so-pagebuilder`
- [x] fixed proud-admin styling issues

**Comment by jlyon** [comment]
https://proudcity.zendesk.com/agent/tickets/99

**Comment by jlyon** [comment]
I unhid the SO image widget.  It shows up in the list as image:

**Comment by kevindherman** [comment]
@jlyon great, I'll pass this info along in zendesk.

**Comment by kevindherman** [comment]
@jlyon @aschmoe can this get added to https://san-rafael-ca-parks.proudcity.com/

I thought it was added but the person who made the original request said it's not there.
