### ISSUE TITLE
Not all location layers showing as options on services map

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#406]
https://warr-acres-ok.proudcity.com/wp-admin/post.php?post=2211&action=edit

When selecting which layers to display on the services map, not all the layers are provided:

![screenshot 2016-06-01 19 36 54](https://cloud.githubusercontent.com/assets/6032426/15729413/ea83017c-2831-11e6-882e-97d7c042f0bd.png)

https://warr-acres-ok.proudcity.com/wp-admin/edit-tags.php?taxonomy=location-taxonomy&post_type=proud_location

![screenshot 2016-06-01 19 49 48](https://cloud.githubusercontent.com/assets/6032426/15729424/0af9b16c-2832-11e6-9a1a-cc3887aeab3f.png)

**Comment by jlyon** [comment]
Fixed.  It was only showing all categories that had locations in them.  Now it shows all layers entered into the system.

![screenshot from 2016-06-01 20 47 11](https://cloud.githubusercontent.com/assets/550909/15733356/112bdf44-283a-11e6-8dde-164e7a1e3e84.png)
