### ISSUE TITLE
Create sliding multi level menu for sub pages

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#409]

**Comment by aschmoe** [comment]
![programs parks recreation](https://cloud.githubusercontent.com/assets/1634686/15733855/0c55f072-283f-11e6-8f7e-130982830fcc.png)
![edit page parks recreation wordpress](https://cloud.githubusercontent.com/assets/1634686/15733867/2bf62014-283f-11e6-8128-6b9fc66f1bb3.png)

**Comment by jlyon** [comment]
@aschmoe I think this and #357 would make a good menus screenshare and/or blogpost
