### ISSUE TITLE
Force send gravityforms emailsfrom email is forced to be notify@proudcity.com

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#411]
This is required by SES

**Comment by kevindherman** [comment]
@jlyon not sure if this is the correct ticket but I noticed San Rafael came up in the description name for this notify@proudcity.com alert I got:

![screenshot 2017-07-10 14 10 36](https://user-images.githubusercontent.com/6032426/28032751-abd0f9a8-6579-11e7-99e8-b5c4f85653a2.png)
