### ISSUE TITLE
Gravityforms [issue]: Manually set tab index

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#412]
From #395
## Created issue on gravityhelp.com:

Steps to reproduce:
1. Go to https://warr-acres-ok.proudcity.com/problem-reporting/
2. Put mouse in Location of concern field
3. Hit tab
Result: You are broght to the bottom of the form.

If you click into Description and hit tab, you are brought into the first name field as expected.

Is there a way to set the tabindex of a field? I didn't see it in the General/Appearance/Advanced tabs for any of the fields. Thanks!

**Comment by jlyon** [comment]
they got back and said to look into https://www.gravityhelp.com/documentation/article/set-tabindex/. will take a look tomorrow

**Comment by jlyon** [comment]
response from gravityhelp

---
Hi Jeff,

See if the following article helps: https://www.gravityhelp.com/documentation/article/set-tabindex/

Regards,

**Comment by jlyon** [comment]
Related to feedback posted on Zendesk:

---
##- Please type your reply above this line -##
You have been assigned to this ticket (#46).

Webmaster	
Webmaster
Jun 2, 09:23

Webmaster was not signed in when this comment was submitted. Learn more
Feedback form accessed by using "FEEDBACK" at bottom of test site... each time I click <NEXT> the form goes to the next question but goes to the bottom of the page. I had to scroll up to see the next question.

You are an agent. Add a comment by replying to this email or view ticket in Zendesk.

Ticket #	46
Status	Open
Requester	Webmaster
CCs	-
Group	Support
Assignee	ProudCity
Priority	-
Type	Ticket
Channel	Web Form

**Comment by kevindherman** [comment]
@jlyon @aschmoe did they have get back to us on the fix?

**Comment by jlyon** [comment]
@jlyon look at

**Comment by jlyon** [comment]
The issue on https://warr-acres-ok.proudcity.com/problem-reporting/ seems to be fixed now (I tab through the form as expected):

1. Go to https://warr-acres-ok.proudcity.com/problem-reporting/
2. Put mouse in Location of concern field
3. Hit tab
Result: Brought to the next field. I can keep clicking tab and only progress to the next field.

**Comment by kevindherman** [comment]
@jlyon  /problem-reporting works as it should but https://warr-acres-ok.proudcity.com/feedback/ is still problematic.
