### ISSUE TITLE
Content list filters not working properly

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#414]
#The content list filter is showing any options even though the document list widget has filters enabled: https://french-creek-pa.proudcity.com/documents/

![screenshot 2016-06-02 10 18 44](https://cloud.githubusercontent.com/assets/6032426/15748173/c2524b2a-28ab-11e6-9f0b-12be5fd96051.png)

**Comment by kevindherman** [comment]
@jlyon here are more details I noticed on this issue when working on Crawford County: https://crawford-county-pa.proudcity.com/documents/

![screenshot 2016-06-08 11 38 44](https://cloud.githubusercontent.com/assets/6032426/15900542/d82189ae-2d6d-11e6-9de4-ce477887bb8e.png)
![screenshot 2016-06-08 11 38 32](https://cloud.githubusercontent.com/assets/6032426/15900543/d82879c6-2d6d-11e6-9172-adb56318e770.png)
![screenshot 2016-06-08 11 38 25](https://cloud.githubusercontent.com/assets/6032426/15900541/d8214ade-2d6d-11e6-8fb0-51120e8113ea.png)

**Comment by aschmoe** [comment]
@kevindherman fixed this, pushed as hotfix
