### ISSUE TITLE
Look into WP multisite

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#416]
http://codex.wordpress.org/Create_A_Network

**Comment by jlyon** [comment]
###Sharing content
* See https://wordpress.org/support/topic/share-some-data-between-2-blogs-on-one-install
* https://wordpress.org/plugins/threewp-broadcast/

**Comment by aschmoe** [comment]
@jylon think we've effectively researched and determined elasticsearch is our binding agent, not multisite.  Closing
