### ISSUE TITLE
Hero unit color style produces opposite result as expected

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#417]
In the “Hero Unit” there are two options for the colors of the Style of the text box: Black text on light background and White text on dark background.  These function opposite of what is selected.  Our main page is selected white text on dark background, but what is displayed is black text on light background.

![screenshot 2016-06-02 15 31 47](https://cloud.githubusercontent.com/assets/6032426/15758147/376de484-28d7-11e6-8e8a-a4c6179bbb80.png)
![screenshot 2016-06-02 15 31 26](https://cloud.githubusercontent.com/assets/6032426/15758146/376d6388-28d7-11e6-8e90-99e2e3be7811.png)

**Comment by jlyon** [comment]
Reassigning to Alex
