### ISSUE TITLE
Add new event fields not showing

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#419]
During SF user testing found that the form fields for adding a new event don't display making it hard to know where to add address info.

Also, get the following error when selecting that the event has no physical location:

Your event details are incorrect and cannot be published, please correct these errors first:
Dates must have correct formatting. Please use the date picker provided.

Link: https://example.proudcity.com/wp-admin/post-new.php?post_type=event

Screenshot:

<img width="716" alt="screen shot 2016-06-06 at 2 25 10 pm" src="https://cloud.githubusercontent.com/assets/1569463/15838461/fd8cf24a-2bf2-11e6-8b77-6b7a47763cbe.png">

**Comment by jlyon** [comment]
The issue with the hidden fields was fixed in the release last Weds https://github.com/proudcity/wp-proudcity/issues/396. 

> Also, get the following error when selecting that the event has no physical location:

> Your event details are incorrect and cannot be published, please correct these errors first:
Dates must have correct formatting. Please use the date picker provided.

This is unrelated to the location, and has to do with the dates in the top-right not being submitted correctly.  Wontfix.

**Comment by lukefretwell** [comment]
@jlyon the event fields now show? Is example update to reflect this?

**Comment by aschmoe** [comment]
@lukefretwell made a hotfix that resolves the label display issue you referenced above.  

@jlyon is correct that submission works fine if dates are selected in the upper right.
