### ISSUE TITLE
Add default/example meta descriptions to top level pages on example.proudcity.com

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#422]
- [x] Home 
- [x] Residents
- [x] Businesses
- [x] Visitors
- [x] Events
- [x] Add new event
- [x] News 
- [x] Government 
- [x] City Council
- [x] Finance Dept
- [x] Fire Dept
- [x] Human Res
- [x] Parks + Rec dept
- [x] Police Dept
- [x]  Contact

**Comment by aschmoe** [comment]
@jlyon @kevindherman went through and added meta desc for main pages that use the pagebuilder... any other obvious ones I missed?

**Comment by aschmoe** [comment]
Going to move this to ready, can re-open if you have additional thoughts

**Comment by kevindherman** [comment]
@aschmoe sounds good.
