### ISSUE TITLE
DEMO Feedback in footer broken

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#424]
The feedback link in the footer of French Creek and Crawford County goes to a page not found.

**Comment by jlyon** [comment]
@aschmoe could you look at this today on https://crawford-county-pa.proudcity.com

**Comment by aschmoe** [comment]
@kevindherman 

https://crawford-county-pa.proudcity.com/feedback/

https://www.frenchcreekcog.org/feedback/
