### ISSUE TITLE
Issues with form notifications

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#425]
https://www.westcarrollton.org/documents/electrical-permit/

I filled this form out as a test and the notification emails were not received by cdamron@westcarrollton.org, clewis@westcarrollton.org and did not go to SPAM or junk folders. 

The entry is being recorded, it's just the email notification.

Is there another way to test where these notifications are going?

**Comment by kevindherman** [comment]
@jlyon they're reporting that this is a problem with parks and rec forms as well so it could be a platform issue.

**Comment by jlyon** [comment]
The email notification From and Reply to settings were not valid:
![screenshot from 2016-06-08 13 29 09](https://cloud.githubusercontent.com/assets/550909/15910193/a52f2900-2d7e-11e6-8873-829757a15d84.png)
(the From would be something like "jeff@proudcity.comnotify@proudcity.com" which isn't valid, and the Reply to has to be a single email address).

I fixed it and sent myself a couple tests that worked:
![screenshot from 2016-06-08 13 40 27](https://cloud.githubusercontent.com/assets/550909/15910235/d6534b4c-2d7e-11e6-8b4f-395f67ad3fa1.png)

I'm going through the other form notifications on WC to make sure the email values are valid now.

**Comment by kevindherman** [comment]
@jlyon so you there should never be a space after the comma if there is more than one address?

**Comment by jlyon** [comment]
* Reservatoion payment https://www.westcarrollton.org/wp-admin/admin.php?page=gf_edit_forms&view=settings&subview=notification&id=11&nid=56fb1184bfe69 To: is sent to {admin_email} (this may just not be set up yet)
* HVAC https://www.westcarrollton.org/wp-admin/admin.php?page=gf_edit_forms&view=settings&subview=notification&id=14&nid=56e091c54887c Had settings matching the electrical permit. Made the same changes.

Let me know if you want to discuss any of these.

**Comment by jlyon** [comment]
@kevindherman Yes, multiple email addresses should be separated by a comma only (no space). They claim that this shouldn't be an issue, but it was causing problems in my testing.

I pushed an update that hides the From and BCC fields.  I pulled this as a hotfix on WA only since I know everything is now properly set in the From field to try to avoid further confusion.
