### ISSUE TITLE
Document list pulling wrong category

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#428]
The customer setup several document lists to separate different years of agendas and newsletters however, each document list widget is only pulling the "2016" category even when it has selected other years. 

> I am having a problem with the “Documents list” widget. On page https://warr-acres-ok.proudcity.com/city-council-agendas/ I have it set to show the different agendas by the different years in separate Documents list widgets each with the category selected for the specific year. No matter what changes I make to the three widgets they all show the same documents in the same category instead of showing the separate categories.
> 
> I originally tried this on the newsletter page https://warr-acres-ok.proudcity.com/city-newsletter/ and it worked perfectly. Now I checked the newsletter page and it is doing the same thing as the city council agendas page. The newsletter page is showing 2016 newsletters under each year category instead of showing the newsletters for that year.

Multiple document list widgets (each one selecting a different year)
![screenshot 2016-06-13 10 06 28](https://cloud.githubusercontent.com/assets/6032426/16010302/94c0912a-314e-11e6-9c74-9f4a35864368.png)

Non 2016 category selected:
![screenshot 2016-06-13 10 06 32](https://cloud.githubusercontent.com/assets/6032426/16010301/94bf1a70-314e-11e6-9147-3c778688598b.png)

Only posting 2016 docs:
![screen shot 2016-06-13 at 10 05 43 am](https://cloud.githubusercontent.com/assets/6032426/16010316/a444a258-314e-11e6-8f2e-d57f6ef6124b.png)

**Comment by aschmoe** [comment]
@kevindherman pushed fixed for warr acres, if you could have him test and make sure that his issues are resolved I can roll out the fix for the rest of the sites.

**Comment by kevindherman** [comment]
@aschmoe both pages look good.

**Comment by kevindherman** [comment]
@aschmoe @jlyon this is cropping up on some homepages with the contest list widget pulling news when events is selected:

https://westmead.org/#/city/answers
![screen shot 2016-06-14 at 10 50 22 am](https://cloud.githubusercontent.com/assets/6032426/16047426/fc5c7b26-321d-11e6-9e8d-85c47cfbe275.png)

This bug is on all sites except Warr Acres.

**Comment by aschmoe** [comment]
@kevindherman  Pulled everywhere now

**Comment by kevindherman** [comment]
Thank you.

On Tue, Jun 14, 2016 at 12:46 PM, Alex Schmoe <notifications@github.com>
wrote:

> @kevindherman <https://github.com/kevindherman> Pulled everywhere now
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/428#issuecomment-225942757>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFwMKqB2L8OGGaPR_qXPtvrpcOyM3VYNks5qLtrKgaJpZM4I0W-X>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
