### ISSUE TITLE
Trying to unset category filter causes blank page

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#433]
in content listings, set filter, submit, try to unset filter, submit goes to blank page

**Comment by aschmoe** [comment]
@jlyon ```$_REQUEST['q']``` for some reason no longer exists on dev or prod... which was the cause.  

I've switched to using  ```$_SERVER['REQUEST_URI']```

**Comment by jlyon** [comment]
huh, cool
