### ISSUE TITLE
WA: date on events list widget theming

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#439]
The date box on the events list widget on the homepage comes close to overlapping the content to the right of in:

https://warr-acres-ok.proudcity.com/
![screen shot 2016-06-22 at 11 53 36 am](https://cloud.githubusercontent.com/assets/6032426/16273577/24ae2b80-3870-11e6-9058-c2e919ab5c4d.png)

This is in chrome on my mac.

**Comment by aschmoe** [comment]
Kevin please use the "mini list" in that case
