### ISSUE TITLE
WA: 311 action box not showing icons for all categories

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#440]
Not all of the topics in the 311 action box have an icon. 

![screen shot 2016-06-22 at 12 01 16 pm](https://cloud.githubusercontent.com/assets/6032426/16274069/0cbe089a-3872-11e6-8310-d368ae1dd9f9.png)

It looks like the way to add icons to the FAQ topics is typing FA-example-name-of-icon into the description area.

![screenshot 2016-06-22 12 03 23](https://cloud.githubusercontent.com/assets/6032426/16274173/6c2262fe-3872-11e6-882e-b8ba91b86583.png)

Can see the topics missing icons don't have a description:
![screen shot 2016-06-22 at 12 13 30 pm](https://cloud.githubusercontent.com/assets/6032426/16274223/a9314836-3872-11e6-975b-d6acc6dfb5a4.png)

Can we add a FA search widget to the CMS like the icon set widget?

**Comment by jlyon** [comment]
This one is not super obvious.  I set these up. See https://warr-acres-ok.proudcity.com/answers/.

On https://warr-acres-ok.proudcity.com/wp-admin/edit-tags.php?taxonomy=faq-topic&post_type=question, the description should be the font-awesome icon name (prefaced by "fa-"), so I edited the top-level taxonomy terms without a description in that list, looked up icons on http://fontawesome.io/icons/, and entered them in there. 

We should probably figure out a better way to do this in the future...
