### ISSUE TITLE
VT: social feed not aggregating

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#444]
The social feed on Venango isn't aggregating after 2 days:

https://venango-pa.proudcity.com/

Social feed setup page: https://venango-pa.proudcity.com/wp-admin/admin.php?page=social
![screenshot 2016-06-24 11 13 35](https://cloud.githubusercontent.com/assets/6032426/16341736/a92e4da8-39fc-11e6-9302-341bf13951c1.png)

Venango is a clone of West Mead where we also had issues with their social feed so I wonder if it's related.

**Comment by aschmoe** [comment]
@kevindherman looks like this wasn't set up right, working now.  Though the only account I have is https://www.facebook.com/Venango-Vol-Fire-Department-25-371697222206/ 

I removed 2 that were set for other cities: Cambridge Springs, and Edinboro

**Comment by kevindherman** [comment]
@aschmoe this can be closed.
