### ISSUE TITLE
WA: permalink error on answers (from dashboard)

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#445]
If I click on the listed "permalink" above any of the "answers" in the question and answer section of the dashboard it generates an error screen saying the page is not found.

![screen shot 2016-06-27 at 10 42 24 am](https://cloud.githubusercontent.com/assets/6032426/16383673/14e6cc1a-3c54-11e6-8076-5c4c11f113f3.png)
![screen shot 2016-06-27 at 10 42 36 am](https://cloud.githubusercontent.com/assets/6032426/16383672/14d91d04-3c54-11e6-9470-35a728643ecb.png)

@jlyon @aschmoe is this because the content live sin the angular app? If so, I know this is a part of something bigger that you've been thinking about and help with an explanation is probably sufficient rather than a fix.

**Comment by jlyon** [comment]
@kevindherman I just fixed this. For some reason, the page at /answers had gotten removed (I think it existed on example when we cloned this site).  I re-created the page (https://warr-acres-ok.proudcity.com/wp-admin/post.php?post=8433&action=edit), and these links now work correctly (https://warr-acres-ok.proudcity.com/question/what-is-the-sales-tax-in-the-city/)
