### ISSUE TITLE
WA: remove wrench and credit card icon

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#451]
These reappeared with the updates. Can you remove them again?

https://warr-acres-ok.proudcity.com/

**Comment by jlyon** [comment]
It looks like he (or we?) added a value on https://warr-acres-ok.proudcity.com/wp-admin/admin.php?page=integrations.  Delete this and it will disappear.
![integrations city of warr acres wordpress](https://cloud.githubusercontent.com/assets/550909/16660639/1e507116-4424-11e6-835c-6eab7c5ea1ce.jpg)

**Comment by kevindherman** [comment]
@jlyon this can be closed.
