### ISSUE TITLE
WM: favicon

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#452]
Add favicon: https://westmead.org

**Comment by jlyon** [comment]
Do we have one? If so, you can upload it on https://westmead.org/wp-admin/customize.php?return=%2Fwp-admin%2F. I think we were waiting on a version of their logo that was black (we only have white).  For now, I just cut out their big green logo that was in the system.

**Comment by kevindherman** [comment]
@jlyon attached:
![noun_163375_ 1](https://cloud.githubusercontent.com/assets/6032426/16625435/92554ed6-4372-11e6-9535-193e91d6ea0e.png)

**Comment by kevindherman** [comment]
@jlyon sorry, I misread your post. I have updated the favicon with the above b&w. This is resolved.
