### ISSUE TITLE
Feedback bar

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#456]
```
WA: He wants to have that up when they go live saying “Welcome to our new website” with the feedback button.```

Add new proud_state, "feedback" before Mon.

**Comment by jlyon** [comment]
I added this option, pulled on WA and set this up. They will need to contact us when they want it removed.

**Comment by kevindherman** [comment]
Thank you.

On Mon, Jul 11, 2016 at 8:16 PM, Jeff Lyon <notifications@github.com> wrote:

> I added this option, pulled on WA and set this up. They will need to
> contact us when they want it removed.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/456#issuecomment-231903229>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFwMKppGJyi7sf4wFgixpg8JA_f0c7RCks5qUtzDgaJpZM4JHj05>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
