### ISSUE TITLE
Auth0 2nd factor authentication errro

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#457]
After logging in from my.proudcity.com I get this popup message the the 2nd factor authentication doesn't clear.

https://proudcity.auth0.com/login/callback
![screenshot 2016-07-08 13 41 45](https://cloud.githubusercontent.com/assets/6032426/16696292/48b7e6fc-4512-11e6-91ae-09a7faae09c2.png)
![screenshot 2016-07-08 13 41 54](https://cloud.githubusercontent.com/assets/6032426/16696291/48b614d0-4512-11e6-8d6f-dc004e79801d.png)

**Comment by jlyon** [comment]
@kevindherman I got to the bottom of this. You can't just delete the page cookies, you have to delete all of your cookies. Here are the steps (in Chrome). If you need instructions for another browser, just let me know.

1. Go to settings (click on the menu icon in the top-right and then Settings)
2. Click on the "Advanced settings" link at the bottom of the page
3. Click on the "Clear browsing data" button
4. Enter the settings from the attached screenshot and click on "Clear browsing data"

Note: You may be logged out of some apps. Sorry!

![settings - clear browsing data](https://cloud.githubusercontent.com/assets/550909/16750524/426e846e-4787-11e6-9312-1863f28ae784.jpg)
