### ISSUE TITLE
WC: all event detail pages get an error

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#459]
https://www.westcarrollton.org/events/ is working as it should but when you click on any of the details they all get the same message. This is only occurring on West Carrollton.

https://www.westcarrollton.org/event/bza-meeting-2016-07-14/

![screenshot 2016-07-13 10 44 14](https://cloud.githubusercontent.com/assets/6032426/16807634/318c96de-48e7-11e6-9a6a-e8d17a311a35.png)

**Comment by jlyon** [comment]
will look into after this 9a call

**Comment by aschmoe** [comment]
@jlyon assuming this was fixed?

**Comment by jlyon** [comment]
Yes, this was fixed after the 9a call: https://www.westcarrollton.org/event/farmers-market-2-2016-07-26/
