### ISSUE TITLE
Menu Text Color and Link Color

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#460]
For lucas-tx.  Maybe we discuss next week? @aschmoe @kevindherman

Can you please make the top menu text white without changing the color of other hyperlinks? Similar to West Carrollton. I do not see a way to do that on the back end without changing all of the links.

https://proudcity.zendesk.com/agent/tickets/66

**Comment by kevindherman** [comment]
@jlyon @aschmoe was this custom on West Carrollton?

**Comment by jlyon** [comment]
See response in Zendesk
```
Hi Tim,

We'll talk to our engineering team about making this its own option. Currently we automatically choose the link color based on the darkness of the topnav background color (changing the background to match the Lucas logo makes links white, but then you can't make out the L in the logo, attached).

We'll get back to you next week.

Thanks, 
Jeff```

**Comment by aschmoe** [comment]
There is a "darkness" calculator on the background color for the top nav which switches the text white / dark, perhaps the breakpoint value needs to be tweaked.
