### ISSUE TITLE
WM: increase file size max for doc preview

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#462]
Can you increase the file size max for document preview to be more than 25MB?

West Mead has just a handful of ordinances like this one:
https://westmead.org/documents/west-mead-township-zoning-ordinance/

**Comment by kevindherman** [comment]
Can you increase the file size max for document preview to be more than 25MB?

West Mead has just a handful of ordinances like this one:
https://westmead.org/documents/west-mead-township-zoning-ordinance/

**Comment by jlyon** [comment]
We can't fix this. We use the Google file viewer and, and the 25mb limit is from them.
