### ISSUE TITLE
SR: ability to change order of answers (not just taxonomy)

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#469]
Add the ability to change the order of questions in addition to taxonomy ordering for answers. Currently you have to update the published on date which is not the most intuitive.

**Comment by jlyon** [comment]
This one might be difficult.  I think there's a way to do it with the published date, which I will look into as a quick workaround.

**Comment by kevindherman** [comment]
@jlyon you can change the order with the publish date (reverse chron), having a tool to reorder like the taxonomy would be a helpful feature down the road if it's a big effort.

**Comment by jlyon** [comment]
will leave in the backlog for now for some localhost testing. I think it's just too difficult (from a ui perspective) with 100+ answers, some in multiple categories.
