### ISSUE TITLE
SR: disable yoast on answers content

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#470]
The yoast/readability scores on answers content is almost always low. Since it's usually the first content created for the site it can be discouraging to see lots of red dots on this for the customer. Is possible to disable Yoast just on answers content?

**Comment by kevindherman** [comment]
@jlyon this was successfully removed from creating/editing Answers content but still shows on the Answers list: https://san-rafael-ca.proudcity.com/wp-admin/edit.php?post_type=question

![screenshot 2016-08-25 11 56 27](https://cloud.githubusercontent.com/assets/6032426/17976405/549b071e-6abb-11e6-84a3-a7de52ec3c6f.png)

**Comment by jlyon** [comment]
@kevindherman hid these two columns, pulled on SR only.
