### ISSUE TITLE
Fix sub menu formatting

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#475]
Sub menus on department pages creates bullets: https://san-rafael-ca.proudcity.com/departments/human-resources/

![sub folder issue](https://cloud.githubusercontent.com/assets/6032426/17975950/7c04e57e-6ab9-11e6-873a-fd7afc3e2306.JPG)

It looks like it was setup correctly as a sub item in menus:
https://san-rafael-ca.proudcity.com/wp-admin/nav-menus.php?action=edit&menu=74

The submenu is working on non-department pages: https://san-rafael-ca.proudcity.com/moving/

@aschmoe I'm not sure a sub-menu is needed on this department page so I can advise against it but still would like to understand what's going on.

**Comment by jlyon** [comment]
@aschmoe can we try to get this in the next release (tom afternoon or wed morn)?

**Comment by jlyon** [comment]
Verified that this is working on https://san-rafael-ca.proudcity.com/job-descriptions/ post-release.
