### ISSUE TITLE
Feedback form page break formatting

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#477]
From WA: 

> The "feedback" form that appears in the blue bar at the bottom of our page has a problem after the first question. When the user goes to the second or any question after that the screen scrolls down part way making the top part no longer visible. Three screen shots attached with the first being the first question where the problem does not happen. Image 2 and 3 are the next questions where the screen has scrolled down partially.

![1](https://cloud.githubusercontent.com/assets/6032426/18058814/039bdb46-6de4-11e6-8005-57d61ef06f25.jpg)
![2](https://cloud.githubusercontent.com/assets/6032426/18058815/039fb81a-6de4-11e6-9311-3454ba8350c7.jpg)
![3](https://cloud.githubusercontent.com/assets/6032426/18058813/039b291c-6de4-11e6-97b4-24c0f750c58e.jpg)

I think what's happening is that the page break on this form is bringing the new field down below the progress bar which is unique to the feedback form. 

![screenshot 2016-08-29 12 26 54](https://cloud.githubusercontent.com/assets/6032426/18058852/33f2a4fa-6de4-11e6-86ad-a734055d3597.png)

**Comment by jlyon** [comment]
@aschmoe can we try to get this in the release?

**Comment by kevindherman** [comment]
@jlyon @aschmoe there is something specific to Warr Acres that is still jumping the below the progress bar.

This isn't an issue on Port Orchard.

**Comment by kevindherman** [comment]
@aschmoe to be factored into this ticket, we need to add this type of feedback form to SR next week ahead of their launch. Their current one is just name, email and message.

**Comment by aschmoe** [comment]
@kevindherman this was a problem with failed deployment to Warr Acres specifically.

**Comment by kevindherman** [comment]
@aschmoe got it. 

Is the progress bar something you need add or is that part of gravity forms? I want to replicate the Port Orchard version plus some questions for San Rafael.

**Comment by aschmoe** [comment]
Already did that.

**Comment by kevindherman** [comment]
@aschmoe dope.
