### ISSUE TITLE
SR: elected officials on contacts now links away

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#478]
After https://san-rafael-ca.proudcity.com/people/ was created the "elected officials" pill on
https://san-rafael-ca.proudcity.com/contact/ directs people to that page for some reason with this url path: https://san-rafael-ca.proudcity.com/people/?filter_categories%5B%5D=57

**Comment by jlyon** [comment]
Fixed this.  The /people page had gotten stolen and used in the City Council agency.  I changed the slug for that page, and re-created /people.

**Comment by kevindherman** [comment]
@jlyon thank you.
