### ISSUE TITLE
SR: & change to &amp; in answers content

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#480]
The & change to &amp; once you drill down to the actual questions (see the Transportation section on our page)

![screenshot 2016-08-30 09 42 33](https://cloud.githubusercontent.com/assets/6032426/18091468/ba1424d4-6e96-11e6-8638-cbf0d98e4a25.png)

![screenshot 2016-08-30 09 42 21](https://cloud.githubusercontent.com/assets/6032426/18091467/ba11c586-6e96-11e6-92b0-15983523c3f6.png)

**Comment by jlyon** [comment]
Fixed this. Will be in the next release @kevindherman
