### ISSUE TITLE
SR: city clerk dept menu

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#481]
The menu for City Clerk is setup correctly: https://san-rafael-ca.proudcity.com/wp-admin/nav-menus.php?action=edit&menu=256
![screenshot 2016-08-30 16 57 16](https://cloud.githubusercontent.com/assets/6032426/18106703/ebd938ec-6ed2-11e6-8190-330669cc5592.png)

But the ordering and submenus are not showing correctly: https://san-rafael-ca.proudcity.com/departments/city-clerks-office/

![screenshot 2016-08-30 16 57 09](https://cloud.githubusercontent.com/assets/6032426/18106757/00e9deda-6ed3-11e6-87bb-b6e1569946d1.png)

**Comment by aschmoe** [comment]
@kevindherman pushed fix for this to SR

**Comment by kevindherman** [comment]
@aschmoe thank you.

**Comment by kevindherman** [comment]
@jlyon @aschmoe this bug is back on their City Council page: https://san-rafael-ca.proudcity.com/departments/city-council/

https://san-rafael-ca.proudcity.com/wp-admin/nav-menus.php
![screenshot 2016-09-12 16 46 33](https://cloud.githubusercontent.com/assets/6032426/18452351/7f135f9a-7908-11e6-86c6-cbd069417c4b.png)

**Comment by jlyon** [comment]
@aschmoe is this one fixed?

**Comment by aschmoe** [comment]
@jlyon yes.

**Comment by jlyon** [comment]
changed tag to ready
