### ISSUE TITLE
SR: Header: random image

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#482]
Or dissolve after 20s or so.

From call with Andrew

**Comment by jlyon** [comment]
Added as an option on the Hero unit widget.  It just selects one image per page load for now (no dissolve after 20s, we decided with Andrew that that could be a future enhancement).  It will be added in the next release @kevindherman.

**Comment by jlyon** [comment]
This didn't seem to be working properly on Beta, so I took it out of the release notes. @kevindherman

**Comment by kevindherman** [comment]
@jlyon talking to @aschmoe about this. I think something was pushed in the release because a lot of header images product-wide are showing blank.

**Comment by aschmoe** [comment]
@jlyon found the issue and deployed as a hotfix to dev + live

**Comment by kevindherman** [comment]
from an airplane... like a boss.

**Comment by jlyon** [comment]
Still needs work. Moving to in progress.

**Comment by aschmoe** [comment]
@kevindherman this was included in hotfix 1.15.1
