### ISSUE TITLE
Romulus FROM widget (instead of FORM)

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#485]
Romulus widget title has a typo, says FROM widget instead of FORM.

![screenshot 2016-08-31 17 56 15](https://cloud.githubusercontent.com/assets/6032426/18147930/ef38fcde-6fa4-11e6-8076-c4b66e3af043.png)

**Comment by jlyon** [comment]
Fixed and pushed as a hotfix (to Romulus only).
