### ISSUE TITLE
Fix captions on hero unit

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#486]
These are pulling in metadata from the image, not the caption that is set in WP UI.

To replicate:
1. Load in attached image
2. Set caption to something
3. Add to hero unit.
Result: When you hover over image, SONY DSC appears in the bottom-left wherre the caption should be.

Issue: https://proudcity.zendesk.com/agent/tickets/105

**Comment by jlyon** [comment]
Look at build_responsive_image_meta() under `/proud-widget/widgets/jumbotron-header/jumbotron-header.class.php`

**Comment by jlyon** [comment]
@kevindherman this won't get into the release, but maybe we can do it as a hotfix.

**Comment by kevindherman** [comment]
@jlyon will post to zendesk, thanks for the heads up.

**Comment by jlyon** [comment]
Ahead of the Service Center launch, I refactored the image captions (photo attribution) so:

1. It pulls the captions in properly (this issue).
2. They always appear in desktop
3. In mobile, an image icon appears. When you click on it, the caption appears.
