### ISSUE TITLE
Add general Menu widget

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#487]
SR requested: https://proudcity.zendesk.com/agent/tickets/104

**Comment by jlyon** [comment]
This functionality already existed, but I updated the title and description to make a it more obvious.  It's worth noting that the submenu will not display automatically on subpages like it will for agencies.  We might want to revisit this @kevindherman @aschmoe

**Comment by kevindherman** [comment]
@jlyon what's the name of the new widget? I'm only seeing "agency menu" and "Contact submenu".

**Comment by jlyon** [comment]
@kevindherman It's called "Submenu":
![screenshot from 2016-09-07 11 13 08](https://cloud.githubusercontent.com/assets/550909/18323718/bacb539a-74ed-11e6-9cf0-20ba1559506f.png)
