### ISSUE TITLE
Answers: Create content list

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#488]
Request:
```
Is there a way to show FAQs by default without having to click the topic. The City wants FAQs for each department page. Currently, it only works if I have a topic > sub topic > FAQs. This requires the viewer to click the department name to view the FAQs.

They only want the FAQs associated with that department to show up on that page and to remove the extra click to view them since there will only be one option.

It would be beneficial to have it default to the view in the screenshot below.
```

**Comment by jlyon** [comment]
@kevindherman this won't get into the release, but maybe we can do it as a hotfix.

@aschmoe and I looked at this, and he wasn't using two levels in his answers taxonomy. Currently the Answers app does not work unless there are two levels of taxonomy, so you might want to let him know this.  This content list will let him use his single-layer taxonomy structure when it is ready, but he won't be using the angular app anymore.

**Comment by kevindherman** [comment]
@jlyon I'll let him know about the two level issue.

**Comment by aschmoe** [comment]
@kevindherman also I wouldn't bring up the option to not use 2 levels, as the search system and navbar functionality assumes that the answers app is present, pulling out that functionality might be decent effort

**Comment by kevindherman** [comment]
@aschmoe totally. I explained the necessity to use two levels in the answers app.

**Comment by kevindherman** [comment]
@jlyon SR is working on bringing this page over: http://www.cityofsanrafael.org/faq/business-licenses/

Should I tell them to pause until this is released?

**Comment by jlyon** [comment]
@kevindherman I deployed this to the platform as a hotfix. 

To add these lists, add the "Answers list" panel to a page. You can select the category in the panel settings, as well as the number of answers to display and the format.  List will add a list of all of the titles with anchor links to the full answers below.  Accordion will display as an...accordion.

I set up an example page of both of these at https://beta.proudcity.com/answers-list-demo.

**Comment by kevindherman** [comment]
@jlyon this is really awesome.
