### ISSUE TITLE
Set up stripe on example, demo

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#49]

**Comment by aschmoe** [comment]
@lukefretwell @jlyon 

> "Also, the payment clickthrough is awkward. Is this part of Stripe in the checklist? 
> Can we fix?"

How would we like to handle?

**Comment by jlyon** [comment]
Get it working, add language

**Comment by jlyon** [comment]
revisit next wk

**Comment by jlyon** [comment]
Done in wordpress. still todo in demo on #121
