### ISSUE TITLE
Lucas: activate recaptcha

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#491]
Activate recaptcha on Lucas.

![captcha](https://cloud.githubusercontent.com/assets/6032426/18294470/6bc72ef8-7467-11e6-9605-5cb636d1af22.png)

**Comment by jlyon** [comment]
I added his key.  Added https://github.com/proudcity/wp-proudcity/issues/493 to look at the permissions issue in the future.

**Comment by kevindherman** [comment]
Thank you @jlyon. Good call on permissions, this is something I could handle in the future.
