### ISSUE TITLE
Lucas: sub categories for documents

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#492]
The sub-categories for documents doesn't work. So for instance, if you would like to have a City Council Minutes Category and then sub-categories for past years the current tagging systems doesn't work. See the below example for 2015 meeting minutes, after you save the category as a child, the type is pulled out when saved on the doc and /documents page filters.

![screenshot 2016-09-06 19 19 31](https://cloud.githubusercontent.com/assets/6032426/18294517/c2b60b8a-7467-11e6-923f-7a5ad2545ce0.png)
![screenshot 2016-09-06 19 19 41](https://cloud.githubusercontent.com/assets/6032426/18294519/c2b77d12-7467-11e6-978b-b973631253c1.png)
![screenshot 2016-09-06 19 20 25](https://cloud.githubusercontent.com/assets/6032426/18294518/c2b7469e-7467-11e6-86b7-9ea661bd1319.png)

https://lucas-tx.proudcity.com/documents/

![screenshot 2016-09-06 19 28 29](https://cloud.githubusercontent.com/assets/6032426/18294563/20aa6ccc-7468-11e6-896a-37a311d099a4.png)

**Comment by jlyon** [comment]
Hmm, I don't think we ever intended for a multi-level taxonomy on documents. It sounds like they would like to use it, so we'll have to put some thought into this one. Won't be in this release. Tagging it for 1.15.0.

**Comment by kevindherman** [comment]
@jlyon I've worked around this issue with other customers so I agree it's worth thinking through. So far, it's for documents that are added monthly which is mostly council minutes and agendas. Annual budgets or monthly fiscal reports would also benefit from it.

**Comment by jlyon** [comment]
@kevindherman OK, cool, we'll put some thought into it over the next couple weeks.
