### ISSUE TITLE
Lucas: cancelling a single event within a recurring event

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#495]
This is a good question and there doesn't seem to be a way to create an exception or exceptions to recurring events without creating an end day and then a new recurring event. 

Hello,

Quick question:

How do I delete a single instance of a reoccurring event? I have events setup for all the council meetings but there are times that one may be cancelled. I would like to modify just that single instance without messing up the rest of the reoccurring instances of that event?

Thank you,

Tim

**Comment by jlyon** [comment]
Hmm, that does seem like a missing feature with events-manager. Someone requested it, but it doesn't seem to be too high of a priority on their roadmap: https://wordpress.org/support/topic/plugin-events-manager-request-ability-to-exclude-dates/.

**Comment by kevindherman** [comment]
@jlyon that's crappy. I'm surprised it's such a low priority.

Does this put us in a holding pattern?

**Comment by jlyon** [comment]
Yes.

**Comment by kevindherman** [comment]
@jlyon so this feature actually works after all. 

Rather than editing the recurring event item the editor needs to go to the events list and edit specific event that they want to change. So for example, if there is a daily recurring meeting, rather than making an exception on the recurring event, the editor goes to the big event list and edits the single event that needs to be changed. 

We can close this issue.
