### ISSUE TITLE
Deport: locations content type missing from dashboard

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#497]
Locations content type is missing from the deport dashboard, including location layers and taxonomy order. 

https://deport-tx.proudcity.com/wp-admin/

![screenshot 2016-09-08 11 46 22](https://cloud.githubusercontent.com/assets/6032426/18356289/261337cc-75ba-11e6-9598-f119657ecd89.png)

**Comment by jlyon** [comment]
@kevindherman Enabled on deport-tx.  They didn't have any maps currently added, so I didn't update those.  Added a Featured layer for them to get started.

**Comment by kevindherman** [comment]
@jlyon thanks.
