### ISSUE TITLE
Clean up social wall front end

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#50]
- [x] "put the social media headings at the top of the cards (perhaps white icon + city branding color background)?"  -- kill bootstrap cards style 
- [x] "remove the 'recent' + 'shuffle' feature? Think it's too much, unnecessary."
- [x] Feels bulky: show fewer, smaller images, less padding
- [x] For long text, only show the first few lines w more link
- [x] Connect w us link to link to directory of social media
- [ ] Increase height of card w now is clicked (Masonry)
- [x] improve formatting
- [x] include handle
- [x] retweets (WC feedback)
- [x] colors should change

**Comment by aschmoe** [comment]
@lukefretwell @jylon

Should we lessen the default amount of items shown?

> "put the social media headings at the top of the cards (perhaps white icon + city branding color background)?"  -- kill bootstrap cards style

This means straying from the boostrap cards style we appropriated.  Thoughts?  Would a quick mockup help?

> remove the 'recent' + 'shuffle' feature? Think it's too much, unnecessary

Pretty simple task to hide the recent / shuffle... if thats the case I will just add an additional option to have the wall as a static column'd display.  Should I nuke the option of having it animated?  Would reduce js loading a little.

**Comment by aschmoe** [comment]
@jlyon Re-tweets is separate issue since it will mean updating the aggregator, removing that for now, unless she means showing the retweet count

**Comment by jlyon** [comment]
Created #152 for retweeets
