### ISSUE TITLE
Forms: add surveys

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#500]
The ability for webforms to display public results so forms can be used for small surveys.

**Comment by jlyon** [comment]
Evaluate http://www.gravityforms.com/add-ons/survey/.

**Comment by jlyon** [comment]
I added this plugin as part of the release.  I will test on beta after the release is out.

**Comment by kevindherman** [comment]
@jlyon cool, LMK when you test. I think a few people were interested in this, definitely SR.

**Comment by jlyon** [comment]
@kevindherman I'll take a look at it on SR today.

**Comment by jlyon** [comment]
@kevindherman I finally enabled this on SR. It adds a new Survey field type.  On the setting for the field, you can set the type you would like (likert, rating, etc).  It also adds a survey results tab to the form settings page that has some nice charts and stuff. 

If other cities would like to use it, tell them to contact us to enable it.
