### ISSUE TITLE
SR: file download within webform

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#504]
This "Claim Form" for SR, has an option to attach a diagram that supports the claim. I know how to add the file upload field but what's the best way for the user to download the optional diagram to fill out and reattach to the form? 

I have attached the file that they would like users to have the option of downloading and attaching:

![upload_9_8_2016_at_4_41_33_pm](https://cloud.githubusercontent.com/assets/6032426/18491423/5ce0051e-79d4-11e6-9164-8003e353a3ef.png)

**Comment by aschmoe** [comment]
Create the file or a ducument within the system, 

Then on form: link out to file with instructions, have the corresponding upload field.

**Comment by kevindherman** [comment]
@aschmoe  That's what I was thining but think it'll be a little shotty until this is added: https://github.com/proudcity/wp-proudcity/issues/502

**Comment by kevindherman** [comment]
Note to self, when #502 is ready I'll add it to this page: https://san-rafael-ca.proudcity.com/claim-form-e-file/

**Comment by kevindherman** [comment]
The embed document widget is being used on this page if you want to see how we're currently do this:  https://san-rafael-ca.proudcity.com/claim-form-e-file/
