### ISSUE TITLE
SR: granicus iFrame

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#505]
The iFrame they provided isn't showing when using the new iFrame widget. Is it the iFrame or the widget?

iFrame:
<iframe title="Content hosted by Granicus.com" height="1000" longdesc="This frame provides a link to the City of San Rafael’s archived meeting content." src="http://cityofsanrafael.granicus.com/ViewPublisher.php?view_id=2" frameborder="0" width="100%" name="contentframe">Your browser does not support inline frames. To access archived media, click <a href="http://cityofsanrafael.granicus.com/ViewPublisher.php?view_id=2"> here</a></iframe>

https://san-rafael-ca.proudcity.com/meetings/

Backend:
![screenshot 2016-09-13 17 09 36](https://cloud.githubusercontent.com/assets/6032426/18491564/f0e6130c-79d4-11e6-8de9-802c24fcf9fd.png)

**Comment by aschmoe** [comment]
@kevindherman no promises, but about 99% sure the issue is you're linking to non secure iframe content when you need ```https```... this might be a good time to get them aware and thinking about this type of thing.

"Doesn't work?  Hmm secure content?"

**Comment by kevindherman** [comment]
@aschmoe is that common for iFrames?

**Comment by aschmoe** [comment]
Common for everything outside proud city.  If externally linked images,
unframed whatever aren't using https, there will be blood... Or just
missing content

**Comment by kevindherman** [comment]
this is complete.
