### ISSUE TITLE
/documents pager broken

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#506]
I enabled the pager on https://lucas-tx.proudcity.com/documents/ because they have a ton of documents. 

The pager adds a previous and next option that seems to be in reverse and without numbers:

![screenshot 2016-09-14 12 23 11](https://cloud.githubusercontent.com/assets/6032426/18520523/305da8e6-7a76-11e6-8263-f2ce6e7ec70a.png)

More importantly, the previous button goes to page not found: https://lucas-tx.proudcity.com/documents/page/2/

![screenshot 2016-09-14 12 25 06](https://cloud.githubusercontent.com/assets/6032426/18520548/4afc5f44-7a76-11e6-817b-98a9041a43c5.png)

**Comment by kevindherman** [comment]
@jlyon in looking over SR's /documents I realized this is a global issue.

**Comment by aschmoe** [comment]
@kevindherman this is now fixed

**Comment by kevindherman** [comment]
@jlyon @aschmoe I reopened this. I'm getting the same page not found error when I activate the pager and select the "previous" button. 

I tested on Lucas, Port Orchard and San Rafael.

**Comment by aschmoe** [comment]
Yeah this was closed errantly
