### ISSUE TITLE
311 Actions app: Allow embedded iframe, external link

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#509]
- [x] Add iframe field to 311 Category content type
- [x] Add actions app mode: iFrame
- [x] Allow custom label/icon/iframe url for Issue lookup tab

**Comment by jlyon** [comment]
@kevindherman This will be enabled on SR after the release and can be added to other sites.

There is a new Issue post type. Here you can create the issue categories that appear on the actions app.  The categories can either be an external link, an iframe (which is what I'm using in the example Romulus embed on SR), or a gravityform.  The gravityform option will be our there's a little more work needed here, but I think it's pretty close, esp with gravityflow).  They can have a different Romulus form for each category.

-- 
For future reference:
Steps needed to enable custom categories on 311:
1. Enable wp-proud-issue
2. Set the 311 Integration to  "Custom categories" on /wp-admin/admin.php?page=integrations

**Comment by kevindherman** [comment]
@jlyon fantastic.

Once the gravityform items are smoothed out I'll reach back out to current customers. Perhaps we should strategize this feature subsidizing gravityflow for everyone.
