### ISSUE TITLE
SR: News enhancements - card images as links, adding duplicate post title, default card image, hide featured images

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#516]
Here are a couple questions and feedback from SR about news items that came in through Zendeks:

a couple questions about the news feed... 1 - when you click the images on the news page (https://san-rafael-ca.proudcity.com/news/) it takes you to an error page. how do we make it take you to the news story? and 2 - for news feeds like this one (https://san-rafael-ca.proudcity.com/departments/city-managers-office/) did i do the "more" link correctly? wasn't sure what i was supposed to do for that. 
THANKS!

more news questions! one of the articles i posted was title "labor negotiations" and the url that was automatically created matched the labor negotiations webpage so the link took you there. how do we prevent that from happening?

also, we like the card view, but not all news articles have images associated. what can we do to make this look good?

KH Comments:
1 - This is a bug. 
2- Yes, this is done correctly.
3- Duplicated URL's has come up before, is there a good way to avoid this? 
4- Card view without images, should the image default to the city logo if there isn't an image?

**Comment by kevindherman** [comment]
One more news related question:

Is there a way for the featured image to not show in the header of a news post? For example, they want a featured image to show up in card on /news however, they don't want it at the top of the post because it's used lower in the article: 

https://san-rafael-ca.proudcity.com/get-know-colin-mcdonnell/

**Comment by aschmoe** [comment]
![news - your city](https://cloud.githubusercontent.com/assets/1634686/18651535/c511f560-7e80-11e6-89db-fd7d588a03a6.jpg)

@kevindherman what do you think of this for the default image?

**Comment by kevindherman** [comment]
@aschmoe that's a good default for the platform. I talked to Rebecca yesterday about this and she's going to ask Andrew for an icon that they can use as the default, likely a simple version of the logo.

**Comment by aschmoe** [comment]
@kevindherman I will add option for themes to override the image

**Comment by aschmoe** [comment]
@kevindherman re:Duplicated URL's has come up before, is there a good way to avoid this?

I've added some functionality that warns if the user is using a page title that is already in use (this was much easier than checking the permalink) ... do you think this will be a reasonable interim solution?
![edit post your city wordpress](https://cloud.githubusercontent.com/assets/1634686/18686505/015236c4-7f31-11e6-9e1d-af75f629dda9.jpg)

**Comment by kevindherman** [comment]
@aschmoe I think it's ok as an interim solution.

Is this a hotfix or going into the release tomorrow?

**Comment by aschmoe** [comment]
@kevindherman release

**Comment by aschmoe** [comment]
@kevindherman going to move this to release, and split custom default images into new issue.  The lines I posed above will be used for now.

**Comment by kevindherman** [comment]
@aschmoe @jlyon 
Alex, sounds good on the new issue for the custom default image.

These are really helpful updates guys, thank you.
