### ISSUE TITLE
SR: ability to select color options for new map layers

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#518]
This has come up in the past as feedback on the maps.

San Rafael asked about it after adding new layers to the homepage map: https://san-rafael-ca.proudcity.com/

SR is going to use the maps in a couple different ways so I think it'll help.

**Comment by kevindherman** [comment]
@jlyon this is still a work in progress, right? Danvers reported that they were putting in pin colors and icons for each pin but it's still just showing up as brown:

![screenshot 2017-02-23 15 48 37](https://cloud.githubusercontent.com/assets/6032426/23278718/746b576a-f9e0-11e6-898e-0d5b0c973862.png)


![screenshot 2017-02-23 15 48 57](https://cloud.githubusercontent.com/assets/6032426/23278709/6d88a600-f9e0-11e6-9c5c-f635ac6c31b7.png)

**Comment by jlyon** [comment]
@kevindherman yes, this is still a work in progress.  We need to try to get the Google maps working for this. I might try to spend a few minutes on this over the weekend.

**Comment by kevindherman** [comment]
@jlyon that would be awesome. It's come up with the onboarding customers so if we could get it up and running by the time they go live that would be a nice win.

**Comment by jlyon** [comment]
@kevindherman sorry, this was going to be a little more complicated that I was anticipating so it's not going to get to this in the release, but we'll try to get it done in the next couple weeks.

**Comment by jlyon** [comment]
@aschmoe where are we at with the map work?  Can it be pushed in the release tomorrow?
