### ISSUE TITLE
Display contact info on map with wp-proud-locations

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#519]
The locations contact information under the construction layer on the home page map is not showing up with the description when you click on the location icon. See photos.... 
Also, how do I change the icon on the map? Like, if I don't want that brown icon?

------------------ 
Submitted from: https://san-rafael-ca.proudcity.com/wp-admin/post.php?post=3186&action=edit
![construction map contact info 2](https://cloud.githubusercontent.com/assets/6032426/18677867/4b2abc7a-7f28-11e6-8065-0373d1720724.PNG)
![construction map contact info](https://cloud.githubusercontent.com/assets/6032426/18677868/4b2b0f86-7f28-11e6-996e-2c4b9c74a729.PNG)

**Comment by jlyon** [comment]
Fixed this.

![screenshot from 2016-09-21 15 29 13](https://cloud.githubusercontent.com/assets/550909/18731337/3631c7d0-8010-11e6-95d1-d94261146b25.png)

**Comment by jlyon** [comment]
Noticing some formatting issues. Moving back to in progress.

**Comment by jlyon** [comment]
Changed the email label to "Send email"
