### ISSUE TITLE
Evaluate new approach to the social links display (Footer).

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#520]
https://san-rafael-ca.proudcity.com has

SanRafaelFirefighters (Facebook)
LoveSanRafael (Facebook)
srpublib (Facebook)
SanRafaelCommunityCenter (Facebook)
AlbertJBoroCommunityCenter (Facebook)
terralindacommunitycenter (Facebook)
FalkirkCulturalCenter (Facebook)
109339569105169 (Facebook)
SanRafaelPolice (Twitter)
srfd (Twitter)
SRPublicLibrary (Twitter)
sanrafaelpubliclibrary (Instagram)

But the social display would only display something like

Facebook
Facebook
Facebook
Twitter
Twitter

Need an option to use the account name instead of service name

**Comment by aschmoe** [comment]
@kevindherman (this is for the social links in footer) think simply having the account name visible is enough or will clients desire more input.

**Comment by aschmoe** [comment]
@kevindherman think this is still an issue, or ability to select which social accounts display is enough?

**Comment by kevindherman** [comment]
@aschmoe I think that's enough.

**Comment by aschmoe** [comment]
This was completed
