### ISSUE TITLE
Allow ordering documents, contacts, agencies

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#521]
Is there a way to list specific document lists by alphabet instead of by date? Only want to do this on some lists.

**Comment by jlyon** [comment]
This has come up a few times:

SR wanting to order answers within categories
Ordering to contacts, agencies #507
I think there are two parts to this

 1. @aschmoe We probably want to be able to set the default sort for lists (make it alpha based on last name for contacts, etc). What do you think the best way to go about this? We could probably hardcode the sort args in the specific teaser widget's $this->settings in teasers-list-post-specific-widgets.php.
 2. Evaluate a post order plugin:
http://www.nsp-code.com/wordpress-plugins/post-types-order/: The post equivalent to what we're using w tax terms
https://perishablepress.com/6-ways-to-customize-wordpress-post-order/
https://wordpress.org/plugins/intuitive-custom-post-order/screenshots/
https://wordpress.org/plugins/simple-custom-post-order/

**Comment by aschmoe** [comment]
@jlyon there is already sort functionality built into teaser views.  We just need to add selector options.

**Comment by jlyon** [comment]
I enabled a new plugin https://wordpress.org/plugins/intuitive-custom-post-order/screenshots/ that lets you order posts on the post admin list page by dragging and dropping them.  You can also order taxonomy terms the same way. It doesn't handle hierarchical lists as well as the Taxonomy Order page, so I'm leaving that plugin enabled for now, although I would like to remove it in a future release. @kevindherman

**Comment by kevindherman** [comment]
@jlyon awesome.

I'll communicate with Lucas and PO.
