### ISSUE TITLE
PO: option to disable published date on documents

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#524]
Documents are ordered by date published however the published date on Port Orchard's ordinances and resolution documents can provide misleading information. While we work on a way to order documents lists (in this case they want numerical and in others alphabetical or reverse chron), can there be an option to hide the date published view on the front-end?

**Comment by jlyon** [comment]
hide date on all documents for PO

Long term solution #521

**Comment by kevindherman** [comment]
@jlyon can this one be a hotfix so it happens ahead of the launch?

**Comment by kevindherman** [comment]
@jlyon the feature for publish date should still exist so they can order the documents. The view of the publish date on the front end is what should be disabled.

Sorry if this wasn't clear.

**Comment by kevindherman** [comment]
Only on these two documents that were just created, PO is unable to edit the published info, the area to edit won't expand:

https://port-orchard-wa.proudcity.com/wp-admin/post.php?post=4783&action=edit
and
https://port-orchard-wa.proudcity.com/wp-admin/post.php?post=4782&action=edit

**Comment by jlyon** [comment]
Added "Display published date on documents" checkbox to /wp-admin/admin.php?page=proudsettings.  This will be pushed in the next release.

>  unable to edit the published info, the area to edit won't expand:
Creating new issue for this

**Comment by kevindherman** [comment]
@jlyon can this be a hotfix since they're going live Saturday?
