### ISSUE TITLE
PO: youtube videos embedding on backend but not frontend

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#525]
HTTPS youtube videos were embedded on this page and looks right on the backend but it's not showing up on the actual page: https://port-orchard-wa.proudcity.com/economic-development-tourism-committee/

![screenshot 2016-09-21 17 15 11](https://cloud.githubusercontent.com/assets/6032426/18729307/51f379a0-801f-11e6-936e-f553896a1ce3.png)
![screenshot 2016-09-21 17 15 20](https://cloud.githubusercontent.com/assets/6032426/18729306/51f015f8-801f-11e6-8edb-6b0157fa7362.png)
![screenshot 2016-09-21 17 15 53](https://cloud.githubusercontent.com/assets/6032426/18729308/5200a6e8-801f-11e6-9298-b8b183bdb9b0.png)

**Comment by aschmoe** [comment]
@kevindherman we will look into this issue, but the workaround is to use the iframe embed code from youtube in the "Code or Embed" widget instead.  See page above for example

**Comment by jlyon** [comment]
@kevindherman is this still an issue?

**Comment by kevindherman** [comment]
@jlyon looks good.
