### ISSUE TITLE
311 actions app: Add custom tab

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#530]
Should we just hide it for now? I think we talked about maybe making this a contact form or a link to the contact page, but that seems like overkill maybe.

@kevindherman thoughts?

**Comment by kevindherman** [comment]
@jlyon I reached out to SR to confirm disabling check status, I'm almost certain that's what we decided after circling around the topic for awhile.

**Comment by jlyon** [comment]
thanks

**Comment by kevindherman** [comment]
@jlyon talked this over with SR.

They asked about renaming the last tab "Feedback" and then having the same functionality as Report an Issue with the Romulus forms. So the issues would be more like categories:

Issues:
Infrastructure (streets, storm drains, etc.)
Traffic (signals, congestion, etc.)
Parks, trees, & landscaping
Graffiti
Parking (citations, violations, etc.)
Sewers
Homeless encampment
Zoning or housing code violation
Building code violation
 
Feedback:
Customer Service
Parks & Community Centers
Downtown Vitality
Homelessness
Website
Other

What do you think?

**Comment by kevindherman** [comment]
@jlyon confirmed with SR to have one form embedded on the new "feedback" tab that should go to the city manager's romulus form: https://public.romuluscrm.com/departments/sm57h2mx/cases/new

**Comment by jlyon** [comment]
Changed title from "SR: Last tab in 311 box"

**Comment by jlyon** [comment]
Added new Custom tab on the 311 actions widget settings page.   Enabling it brings up three more fields for title, icon and content for the last tab.

**Comment by kevindherman** [comment]
@jlyon was this pushed? I'm not seeing it on SR when trying to setup the "feedback" tab and form.

**Comment by kevindherman** [comment]
@jlyon for the report an issue tab SR asked about having a text area for disclaimer text saying the issues will be address in business hours and then provide phone numbers for emergencies and non business hour response. 

I think a small text area per issue to be placed above the form would do the trick. I don't know the technical implications so I said it might be a post launch item.

**Comment by jlyon** [comment]
@kevindherman Sorry, I meant to do this after the hotfix was pushed but forgot.  I fixed this. Will require a hard refresh (shift+refresh).

This is the new custom tab setting:
![screenshot from 2016-10-03 10 43 50](https://cloud.githubusercontent.com/assets/550909/19047369/60577718-8956-11e6-8f68-65dcf875e946.png)

**Comment by kevindherman** [comment]
@jlyon this is great and looking good.

For the question about adding a text area to the issues, SR is going to first try and add that text within Romulus so that it shows up everywhere so you can hold on that.

**Comment by jlyon** [comment]
@kevindherman Splitting out the text area issue: https://github.com/proudcity/wp-proudcity/issues/587.  This wouldn't be difficult at all.

**Comment by kevindherman** [comment]
@jlyon cool.
