### ISSUE TITLE
SR Parks: Map setup

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#531]
Pools
Parks
Facilities

**Comment by kevindherman** [comment]
@jlyon change facilities to "Community Centers"

**Comment by jlyon** [comment]
ok. seems like a lot of this was already set up, but we'll refine it.

**Comment by kevindherman** [comment]
Cool.

When you're done, let me know if there are any specifics or differences you want me to highlight in the meeting.

**Comment by jlyon** [comment]
@kevindherman This was pretty much setup, but I added a Facilities and Featured layer.  
I fixed a bunch of things on the admin page and applied as a hotfix (see #527)

Note that until wee fix the permissions, she will will not be able to manage the layers.  We will address this by the next release #540.
