### ISSUE TITLE
Email, telephone links  open blank tab

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#537]
Hello,

Whenever someone clicks on an email on the website a blank "untitled" new tab pops up. Can you please turn this off. It takes them away from the site to just a blank page.

This is on department pages. Please see the attachment for an example. It does open the email client but the blank pages still remains open and active.

Thank you,

Tim

@jlyon I don't think we should disable the feature but the new blank tab is kind of annoying.

**Comment by jlyon** [comment]
This appears to be a long-standing issue with our external link detector (that opens external links in a new tab).  It has been fixed and applied to the platform immediately as hotfix 1.15.4.
