### ISSUE TITLE
Add Mega Menu

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#539]

**Comment by kevindherman** [comment]
@jlyon to be clear, we need to estimate this and put in front of Lucas before implementing.

**Comment by jlyon** [comment]
@kevindherman We think 5h.

cc @aschmoe

**Comment by kevindherman** [comment]
two questions:

1- Would this be offered in the product after?
2- Lucas, is not turnkey, so does this factor in implementation/setup?
