### ISSUE TITLE
Documents: unable to edit the published info, the area to edit won't expand

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#544]
Reported in #524

**Comment by jlyon** [comment]
This was introduced in the work done for #326.  Fixed it and applied it to the platform immediately as a hotfix @kevindherman

**Comment by kevindherman** [comment]
@jlyon this issue has come up again here: 

http://www.cityofportorchard.us/wp-admin/post.php?post=5180&action=edit

**Comment by kevindherman** [comment]
@jlyon sorry, just seeing this will go out in the release tomorrow.
