### ISSUE TITLE
Agency: improve contact styling

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#545]
Inspiration: https://www.boston.gov/departments/animal-care-and-control

**Comment by jlyon** [comment]
![screenshot from 2016-09-23 15 49 10](https://cloud.githubusercontent.com/assets/550909/18803495/52066812-81a5-11e6-99da-675b144b8e33.png)

**Comment by jlyon** [comment]
I tried messing around with this, but decided we should maybe get feedback before I pushed this in the release.  What do you think of this screenshot @aschmoe @lukefretwell @kevindherman ?

OLD


NEW

**Comment by aschmoe** [comment]
@jlyon I'm confused, what is new, what is old?

**Comment by jlyon** [comment]
@aschmoe check now (the 'ol can't upload imgs in waffle)

**Comment by aschmoe** [comment]
@jlyon think its a definite upgrade

**Comment by jlyon** [comment]
Cool, maybe I'll just push it

**Comment by jlyon** [comment]
Didn't get into the release. Maybe can be a hotfix.

**Comment by kevindherman** [comment]
@jlyon late to the party, agree with Alex that it's an upgrade. Nice job.

**Comment by jlyon** [comment]
Pushed this. It will be in the next release:

![screenshot from 2016-10-12 18 22 53](https://cloud.githubusercontent.com/assets/550909/19333294/503e6b2a-90a9-11e6-8cec-26731d0fe7c0.png)
