### ISSUE TITLE
WA: footer widget FAQ-Widget-Random broken

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#548]
Zendesk: In footer "FAQ Widget-Random" produces a link for "See the entire answer" This link does not work properly on any of our question/answers

The link goes to page not found: https://www.warracres-ok.gov/question/how-do-i-reserve-a-park-facility-2/

Unless this is part of a larger issue we should pay attention to, we should probably just disable this footer widget and others that we don't want people using.

**Comment by jlyon** [comment]
There is a /answers page that is added when the site is first set up. It looks like it got deleted. I restored it and this redirect now works.
