### ISSUE TITLE
Answers taxonomy order not adjusting when there are more than 10 top-level categories

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#549]
The answers taxonomy is not reflected on the front-end:

![screenshot 2016-09-26 17 51 20](https://cloud.githubusercontent.com/assets/6032426/18853225/0c5a0a48-8412-11e6-9307-1b60846d67fe.png)
![screenshot 2016-09-26 17 51 30](https://cloud.githubusercontent.com/assets/6032426/18853226/0c5a7d2a-8412-11e6-8a97-f7255d78338a.png)

**Comment by jlyon** [comment]
It seems like if all categories are checked, it doesn't take the taxonomy order into account.  

Possible routes:
- WP api?
- Save the order when you save the 311 actions box settings

**Comment by kevindherman** [comment]
@jlyon sorry, for the delay. Are you asking for my feedback or are these notes to yourself?

**Comment by jlyon** [comment]
@kevindherman I fixed this.  It turned out that there was a weird bug that only happened if there were more than 10 categories chosen to be displayed.  

This will be pushed in the next release (unless you need it soon, in which case it can be a hotfix).

**Comment by kevindherman** [comment]
@jlyon if you think there will be time next week to do the release then it can happen then. If not, then hotfix this one.

**Comment by jlyon** [comment]
@kevindherman Yeah, I think we should try to do the release next week one afternoon @aschmoe
