### ISSUE TITLE
Vote app

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#550]

**Comment by jlyon** [comment]
I created a prototype of this that can be used as a tab in the actions box, or as a standalone app: https://vote.proudcity.com.

The Google API we're using doesn't have data for the current election yet, so it's pulling info from the last midterm in 2014.  Also, it doesn't look like they have polling information for every address. They have most Oakland addresses (my house works), but not much in West Carrollton or Seattle.  I still think it's somewhat useful because it provides links to the relevant SoS pages which can be a pain to find.

**Comment by jlyon** [comment]
- [ ] Clicking back to vote doesn't bring up address field 
- [ ] Do we want to show links on the homepage based on the city?

**Comment by kevindherman** [comment]
@jlyon LMK when you think it's ready to show WC and SR.

**Comment by jlyon** [comment]
I put this up on https://beta.proudcity.com/ and https://beta.proudcity.com/vote @kevindherman @lukefretwell

**Comment by kevindherman** [comment]
@jlyon is this ready to show current customers?

**Comment by jlyon** [comment]
@kevindherman yes, with the caveat that it's using a demo election, so there might not be data for all addresses (anywhere in WC, for example).  Addresses in Oakland work though.

**Comment by kevindherman** [comment]
@jlyon sweet, I'll share with SR. If they want to use it on the BETA how long would it take to implement?

**Comment by jlyon** [comment]
No time to implement  There's a new Vote option on the 311 widget that enables this. It's just a matter of when the data becomes available in Google's API. I'm pretty sure it should be really soon, but they don't have any docs about when it will be ready. We could make it more of a useful placeholder until then. Maybe something like this:

![screenshot from 2016-10-03 14 05 26](https://cloud.githubusercontent.com/assets/550909/19054072/8631d818-8972-11e6-9f0e-cfbd8ec39324.png)

**Comment by kevindherman** [comment]
@jlyon sorry, the waiting on google part of this went right over my head.

**Comment by lukefretwell** [comment]
@jlyon address search doesn't seem to work on the test site: https://beta.proudcity.com/vote/

**Comment by kevindherman** [comment]
@lukefretwell that's because the google API isn't finished.

**Comment by lukefretwell** [comment]
@jlyon comments here. This is really incredible.



## General

* text changes: Voting is important + Enter your address to find out where and how to vote and learn more about the issues on the ballot. (would make 'Enter your ... <p> tags')
* change 'Enter a location' to 'enter a location'
* think there should be some type of search button
* Would add 'New location' text to refresh icon tab
* Call this 'ProudCity Vote' 
* Would be great to have a way to share socially
* Headings should be bolder (too hard to read)
* Footer (left): Add ProudCity Vote to your website
* Footer (right): <em>Powered by ProudCity and the Google Civic Information API * Disclaimer</a></em>
* Possible to default link color to respective websites' a link color?
* Possible to default font family to respective websites' fonts?

## How to vote tab

* Add 'Register to vote' heading
* Below 'Register to vote' add 'Register' and 'Check your status' icons
* Move 'Get directions' to below address
* Link address to get directions
* Put map below address
* FYI: 'Absentee voting info' button/link goes to page not found

## Issues tab

* Add 'Issues' h1 or h2
* Text hard to read. See comments re: changing header weight.
* Don't think need pin icon. Is it possible to add the state as a header? Alternative would be to add before description (Ex: 'California: Water Bond. Funding for Water Quality, Supply, Treatment, and Storage Projects.')
* Would add button buton proposition description and label it 'Learn more'. Would use small button.

## Candidates tab

* This looks like it's old data?
* Are there candidate photos in the API?
* Is there a link to their website in the API? If so, would be great to link their name to it.

**Comment by jlyon** [comment]
The API is working for this election now. I think we should try to get this out there.  I'll push all of these changes later tonight (ran out of time).

I took care of a lot of these (see checkboxes above).  Some notes on the others:

* Would be great to have a way to share socially
@aschmoe, can we discuss tomorrow

General
* Possible to default link color to respective websites' a link color?
* Possible to default font family to respective websites' fonts?
I switched the embedded version to just using standard Boostrap.  There isn't a way to customize this stuff very easily with the Iframe embed we're using.  Maybe a good future enhancement.

How to vote tab
* Add 'Register to vote' heading
I didn't really follow this. We have a Register to Vote button under Helpful links.  I think the last day to register in most states has already past, and the last day for the rest is Oct 24, so this may be a moot point.
* Below 'Register to vote' add 'Register' and 'Check your status' icons
Do you just want to change the 'Confirm Registration' button to 'Check your status'?  We're getting these links from Google's API, so we can't easily add links.
* Put map below address
I think this would require some major reorganization, so I left it where it is. There might also be multiple pins for some people, so I think it's better to have a big map.
* FYI: 'Absentee voting info' button/link goes to page not found
Problem with Google's API, not much we can do about it

* Don't think need pin icon. Is it possible to add the state as a header? Alternative would be to add before description (Ex: 'California: Water Bond. Funding for Water Quality, Supply, Treatment, and Storage Projects.')
Tried adding state as another header. Didn't look very good.  Got rid of the icon
* Would add button buton proposition description and label it 'Learn more'. Would use small button.
The full text links aren't coming through in the 2016 election data yet. I changed this so there's no button. Clicking anywhere (like the prop title) will display the full text of the prop. Unfortunately local issues (like HH in Oakland) aren't showing up (yet).

Candidates tab
* Are there candidate photos in the API?
* Is there a link to their website in the API? If so, would be great to link their name to it.
We're displaying all the info we get from the API. We're not even getting social media accts for the 2016 election  (yet).  I changed the names to link to Google Searches.

**Comment by aschmoe** [comment]
@jlyon chatted social media directive to you, but will paste here for ease

```
.directive('shareBlock', function factory($window, $browser, $http) {
  return {
    restrict: 'A',
    template: '<a ng-click="fbScript($event)" href="https://www.facebook.com/sharer/sharer.php" target="_blank"><i class="fa fa-facebook-square fa-fw"></i> <span>Facebook</span></a>'
      + '<a ng-click="twitScript($event)" href="http://twitter.com/share"><i class="fa fa-twitter-square fa-fw"></i> <span>Twitter</span></a>'
      + '<a ng-href="{{mailTo()}}"><i class="fa fa-envelope fa-fw"></i> <span>Email</span></a>',
    controller: function($scope, $window, metaInfo) {
      
      var shareText = "Municipalities can apply to the ProudCity Pilot and get free digital services for a year.";
      
      $scope.mailTo = function() {
        return 'mailto:?subject='
              + metaInfo.title()
              + '&body=Read more: '
              + $window.location.href;
      }      

      $scope.title = function() {
        return ;
      }

      $scope.fbScript = function($e) {
        $e.preventDefault();
        $window.open(
          '//www.facebook.com/sharer.php?m2w&s=100'
            + '&p[url]='  + encodeURIComponent($window.location.href)
            + '&p[title]=' + encodeURIComponent(metaInfo.title())
            + '&p[summary]=' + encodeURIComponent(shareText)
            + '&p[images][0]=' + encodeURIComponent('https://proudcity.com/wp-content/uploads/2015/12/pc-icon-blue-square.png'),
          '_blank',
          'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=550, height=440, toolbar=0, status=0'
        );
      };

      $scope.twitScript = function($e) {
        $e.preventDefault();
        $window.open(
          '//twitter.com/intent/tweet?' 
            + 'url='  + encodeURIComponent($window.location.href)
            + '&text=' + encodeURIComponent(shareText),
          '_blank',
          'scrollbars=0, resizable=1, menubar=0, left=100, top=100, width=550, height=440, toolbar=0, status=0'
        );
      };
    }
  }
})
```

**Comment by kevindherman** [comment]
@jlyon @lukefretwell @aschmoe  I can reach out to customers today. Here's a quick inventory:

- SR: Is currently using all four tabs on the 311 box, I can suggestion removing the last "feedback" tab for the time unless we have other ideas
- PO, West Mead, De Leon, Deport and Venango: using less than four tabs, shouldn't be a problem
- West Carrollton: Uses 4 tabs but two link out, will suggest removing "Check Status" for now
- Warr Acres, Kettering and Lucas: Are not using 311 box at all, maybe they'll just want the page. Is it worth it if the 311 box isn't being used?
- Danvers & Pittsburg (leads): if it's not too hard I think it would be cool to share, at least as a page. 

Is there any reason to not reach out to anyone on the list?

**Comment by jlyon** [comment]
Just added Alex's share code and pushed it to the platform as hotfix 1.16.1. 

@aschmoe could we discuss this one really quick later today:
- [ ] Clicking back to vote doesn't bring up address field @aschmoe help?

Other todo:
- [ ] Google analytics (set up events for embedded widget)

re: inventory:
* Tabs: For the cities using all tabs, I think we would suggest removing the last tab temporarily (until after the election).  The beauty of the widgets stuff is you can temporarily enable/disable them.
* No 311 box currently: I think we suggest setting up a /vote page. We can give this as an option for all of the other cities as well.
* Leads: You can easily set up the /vote page.

**Comment by aschmoe** [comment]
@jlyon https://beta.proudcity.com/vote/#/city/vote/address you mean clicking back should focus input?

**Comment by jlyon** [comment]
@aschmoe 
1. On https://beta.proudcity.com/#/city/vote
2. Enter an address
3. Click Vote tab (in the top 311 actions box pills). It should take you back to the address input (#/city/vote/address), but it just goes back to a blank page (#/city/vote).

**Comment by jlyon** [comment]
Added Google Analytics  to vote.proudcity.com and the embedded widget (but not tracking the iframe source url).

**Comment by jlyon** [comment]
For the future: https://www.vote.org/technology
