### ISSUE TITLE
Add featured post option for news + events

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#555]

**Comment by kevindherman** [comment]
@aschmoe can this show the featured post and event title on the homepage feed as well? If that's too much I think it's more important that the teaser text.

**Comment by aschmoe** [comment]
Yeah I think thats ideal, just mockups are in this style, I'll add.

**Comment by kevindherman** [comment]
Date too.

**Comment by kevindherman** [comment]
@aschmoe just want to make sure adding the title and date to the featured post and event on the homepage isn't lost since this is in the ready column.
