### ISSUE TITLE
Fix issue display in search

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#559]
From Zendesk:

When you start typing "homeless" into the main search, the first thing that comes up is Homeless Encampment and when you click that it takes you to this blank page: https://san-rafael-ca.proudcity.com/issues/homeless-encampment/. What should we do differently here? Thanks!

I think we should either disable issues from search or direct the search result to the homepage 311 app.

**Comment by jlyon** [comment]
@aschmoe thoughts? could we make these pop up the issues 311 box? We should probably also preface the search results with "Report an issue: "

**Comment by aschmoe** [comment]
@jlyon we can definitely load them in 311... would just have to see how the paths work out.

**Comment by kevindherman** [comment]
@jlyon @aschmoe because the new answers list pulls from answers content the same blank search page is happening with that new content list.
