### ISSUE TITLE
SR & Lucas: duplicate menu items in quick menu

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#560]
https://san-rafael-ca.proudcity.com/wp-admin/post.php?post=4881&action=edit

![screenshot 2016-09-28 12 17 17](https://cloud.githubusercontent.com/assets/6032426/18922291/fd7d89cc-8575-11e6-9906-71622f844c1e.png)

**Comment by kevindherman** [comment]
Here's an example on Lucas:

https://lucas-tx.proudcity.com/wp-admin/customize.php?autofocus%5Bpanel%5D=nav_menus&return=%2Fwp-admin%2Fnav-menus.php

![screenshot 2016-09-28 12 24 05](https://cloud.githubusercontent.com/assets/6032426/18922440/a244d3fc-8576-11e6-9580-3f814d4f19fd.png)

**Comment by aschmoe** [comment]
Its 2 menus

https://san-rafael-ca.proudcity.com/wp-admin/nav-menus.php?action=edit&menu=262
https://san-rafael-ca.proudcity.com/wp-admin/nav-menus.php?action=edit&menu=265

**Comment by kevindherman** [comment]
@aschmoe @jlyon On the call jeff said we should delete one. Does it matter which one gets the axe?

**Comment by aschmoe** [comment]
@kevindherman yes it matters.  Since the duplicates appear to be solely based around agencies, it should be pretty clear which one is a "stale" older version (it is pretty clear in the examples above which needs to be deleted)

**Comment by kevindherman** [comment]
Fixed it.
