### ISSUE TITLE
PO: change /residents to /community

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#562]
PO changed /residents to /community but "residents" still shows on sub-pages: https://port-orchard-wa.proudcity.com/local-utilities/

Is there an easy way to change that without messing up all formatting around our usual residents pages?

**Comment by jlyon** [comment]
The subpages use the page title of the parent, not the menu link. Changing the page title on https://port-orchard-wa.proudcity.com/wp-admin/post.php?post=2210&action=edit fixed this.
