### ISSUE TITLE
SR Parks: data points without addresses in maps

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#564]
I know the answer is no for the google map datapoints question but can we setup locations without an address?

Wondering if the data points in the google map I created for the Parks page can be transferred into the map system on the site? Turns out we don't have actual street addresses for the parks. 
City of San Rafael Parks - https://www.google.com/maps/d/viewer?mid=1CJu6PkGTzVAdSyc5A1Krw19Gbus&usp=sharing

**Comment by jlyon** [comment]
2 options:

1. Try typing the park name in the title field.  Chances are Google knows about the park and will automatically grab the coordinates.
2. Uncheck the "Enter custom Latitude/Longitude" checkbox and enter the latitude and longitude manually (you can also see if Google automatically entered them when you did #1):
![add new location san rafael wordpress](https://cloud.githubusercontent.com/assets/550909/18934630/ba2d5c50-858f-11e6-8179-7973a76bbd2e.jpg)


3. Just embed the Google map.  Here's an example of that: https://beta.proudcity.com/3486-2/.

**Comment by kevindherman** [comment]
@jlyon thanks.

I'll hold off on option 3 until she tries 1 and 2.
