### ISSUE TITLE
External link departments not linking out for new image display style

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#569]
From Zendesk:
"Hey - I want the police and library links to go to their sites. I thought I would use the "existing site" selection but it doesn't seem to be working. How do I do this?"

Here are more details from the police page:

https://san-rafael-ca.proudcity.com/departments/police/

![screenshot 2016-09-29 11 21 59](https://cloud.githubusercontent.com/assets/6032426/18960285/397fd60c-8637-11e6-85d7-44b8965da81c.png)

And library: 

https://san-rafael-ca.proudcity.com/departments/library/

![screenshot 2016-09-29 11 24 37](https://cloud.githubusercontent.com/assets/6032426/18960331/5bb5d7bc-8637-11e6-9f18-cda09700c50a.png)

**Comment by jlyon** [comment]
Fixed this (external links will open in a new tab).

**Comment by kevindherman** [comment]
@jlyon thank you, sir.
