### ISSUE TITLE
Broken link checker

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#570]

**Comment by jlyon** [comment]
https://wordpress.org/plugins/broken-link-checker/

**Comment by jlyon** [comment]
I added a Broken Link link to the admin menu under Settings.  There are a bunch of broken links that seem to be from Kettering. We should go through and delete some of these pages @kevindherman

**Comment by kevindherman** [comment]
@jlyon how did you know some were from Kettering? Also, do you delink or trash them?

**Comment by jlyon** [comment]
I clicked through a couple of the pages that the links were on and there was a map of kettering on the page. The pages looked like they were just testing pages, so i think trash em

**Comment by kevindherman** [comment]
@jlyon looks like the non SR ones are now out of there. 

I'll pass along to the implementation team to edit the broken links.
