### ISSUE TITLE
Form Issue not showing in 311 app

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#571]
SR tried to add an abandoned vehicle issue but it's not showing up:

![screenshot 2016-09-29 13 04 28](https://cloud.githubusercontent.com/assets/6032426/18964131/85f85870-8645-11e6-9fd4-ea5c0322e546.png)
![screenshot 2016-09-29 13 04 47](https://cloud.githubusercontent.com/assets/6032426/18964132/85f96544-8645-11e6-9d9d-1c4f91233c15.png)

**Comment by aschmoe** [comment]
@kevindherman @jlyon  looks like type = form is not being displayed in the list yet

**Comment by jlyon** [comment]
Fixed this.  For now it just links out to a page with the form on it.  Full integration will happen in #262.

Note: Requires a hard refresh (hold down shift and click refresh).
