### ISSUE TITLE
DOCS: Add new city to feeds aggregator

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#58]
Just the endpoints to call, passwords to use. including how to setup the feeds widget

**Comment by aschmoe** [comment]
Please see https://github.com/proudcity/proud-recipes/blob/master/social-media-aggregator/README.md

**Comment by aschmoe** [comment]
Social feed will work as long as location data is set on the wordpress location information as 
```
City: New York
State: New York
```
![file 9](https://cloud.githubusercontent.com/assets/1634686/12504753/6422981c-c095-11e5-87d9-5c8d26afeea4.png)
