### ISSUE TITLE
Gravityflow - enable platform-wide

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#580]

**Comment by jlyon** [comment]
@kevindherman Here's the pricing for gravityflow. It's actually $400/yr for unlimited sites.  Should I go for that, or should we just do the volume or 5-site license for now?

**Comment by kevindherman** [comment]
@jlyon I emailed them to find out how they deal with upgrading licenses mid-year. 

I'm thinking we should probably do the ultimate license so that all customers (and test sites) get the full feature-set. The other option would be the volume license and we enable the feature if they're a strong lead, however, that will get annoying for $60 savings.

**Comment by kevindherman** [comment]
They responded about the mid-year license increase:

Hi Kevin,

I'm pleased you're finding it useful - that's great news.

You can upgrade any time from your account page by paying the difference between the two licenses. The renewal date will remain the same.

Do let me know if you have any further questions or comments.

Cheers,
Steve

**Comment by kevindherman** [comment]
@jlyon lets do the volume license for now and add to customers and active betas.

**Comment by jlyon** [comment]
Sounds good. I'll do this this afternoon.

**Comment by jlyon** [comment]
@kevindherman I upgraded to the 5-site license, since that's all we'll use for now. I enabled it on WC. LMK if there is another site to enable it on.

**Comment by kevindherman** [comment]
@jlyon awesome. I'll get WC going today.

PO might want it but I want to confirm they'll use it before it's setup. Pittsburg and Danvers are good candidates in the BETA list to help move along.

**Comment by kevindherman** [comment]
@jlyon can you add the paypal option for WC: http://docs.gravityflow.io/article/104-paypal
