### ISSUE TITLE
PO: updated pages don't have themes

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#582]
@jlyon pages that are edited when saved have the theme stripped out:

http://www.cityofportorchard.us/chimes-lights-committee/

https://port-orchard-wa.proudcity.com/chimes-lights-committee/

**Comment by kevindherman** [comment]
@jlyon this page too: http://www.cityofportorchard.us/finance-committee-2/

**Comment by jlyon** [comment]
It looks like we never actually finished setting up the table view for documents.  Working on it in #584.

**Comment by jlyon** [comment]
Fixed this.  It looks like they changed that to the card view.  I temporarily changed it to the table view (and then changed it back to card view):

![screenshot from 2016-10-03 18 01 32](https://cloud.githubusercontent.com/assets/550909/19059285/9420f884-8993-11e6-80eb-6898e65934f0.png)
