### ISSUE TITLE
SR: /contact-departments not listing any dept's

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#583]
![screenshot 2016-10-01 16 10 52](https://cloud.githubusercontent.com/assets/6032426/19016761/d0302d3e-87f1-11e6-8c12-57f552a359d7.png)

I've changed the agency list to 0 several times but every time I update the pate it clears the field and is blank when I go back:

![Uploading Screenshot 2016-10-01 16.12.24.png…]()

**Comment by jlyon** [comment]
This appears to work for me. Are you still seeing this?
![screenshot from 2016-10-01 14 26 25](https://cloud.githubusercontent.com/assets/550909/19017078/1f5932fc-87e3-11e6-9c2c-8c0adc800933.png)


I still need to remove the social media icons from this page.

**Comment by kevindherman** [comment]
@jlyon weird, totally fine now.
