### ISSUE TITLE
Add new location error

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#585]
Alan Montes
Oct 2, 10:49 COT

Alan Montes was not signed in when this comment was submitted. Learn more
The locations editor is acting buggy. The Name and address fields are filled with !!!!!! and in the address field it says "oops something went wrong"

**Comment by jlyon** [comment]
Sorry, this was related to the release EOD Fri. I fixed it. @kevindherman

**Comment by jlyon** [comment]
@kevindherman let's talk about this real quick post-huddle tomorrow.

**Comment by kevindherman** [comment]
@jlyon sounds good.

**Comment by jlyon** [comment]
I meant for this to be on the broken links issue. This one is all set.
