### ISSUE TITLE
Documents list: Mini List display

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#589]
@kevindherman Yes, we removed the mini list because we weren't doing anything for documents with the  mini list. 

I changed these two pages to the list view.  If they really don't like it, maybe we could get their feedback on what they would like to see and we can set up the mini list with those fields. My guess is they just didn't want the category (and maybe the download button)?  If they just want the title and date (and maybe filetype icon) we can definitely do that.

I can get this into the release tomorrow if we get feedback today.

**Comment by kevindherman** [comment]
@jlyon your assumption were right:

> My guess is they just didn't want the category (and maybe the download button)? If they just want the title and date (and maybe filetype icon) we can definitely do that.

They would like that option if possible.

**Comment by jlyon** [comment]
Re-added the mini option. This is what it will look like:

**Comment by kevindherman** [comment]
@jlyon will PO need to reselect mini list everywhere it was previously?

**Comment by jlyon** [comment]
@kevindherman just on the two pages that I checked. Anywhere that hadn't been edited will remain with the mini style.
