### ISSUE TITLE
Map: Add parking icon

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#591]
These are all parking layers but the parks icon is being triggered for some.

![screenshot 2016-10-04 18 34 45](https://cloud.githubusercontent.com/assets/6032426/19095002/6562d278-8a61-11e6-8df7-b332d5746600.png)

**Comment by jlyon** [comment]
@kevindherman Adding a new parking icon that will be blue.  Will be pushed in release.

**Comment by kevindherman** [comment]
@jlyon looks good except there are two locations that are still brown. Those two locations seem to have the same layers and information as the others, do you know what's going on with those?

**Comment by jlyon** [comment]
Those two were coming through as "charging stations". I made it so charging stations get the same parking icon.
