### ISSUE TITLE
Phone number missing from location detail

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#592]
https://san-rafael-ca.proudcity.com/wp-admin/post.php?post=8518&action=edit
![screenshot 2016-10-04 19 03 06](https://cloud.githubusercontent.com/assets/6032426/19095705/520d9772-8a65-11e6-82e3-c5937119e7e6.png)

![no contact info](https://cloud.githubusercontent.com/assets/6032426/19095712/5c6aea3a-8a65-11e6-9bbf-ffb2182c82a4.PNG)

**Comment by jlyon** [comment]
Like #590 This was fixed in #519 and will be pushed in this release @kevindherman
