### ISSUE TITLE
Agency: Add ability to turn contact name into link

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#593]
Consider the ability to have a link from the Dept Head contact area to their bio page:

https://san-rafael-ca.proudcity.com/departments/city-managers-office/
![screenshot 2016-10-05 11 55 37](https://cloud.githubusercontent.com/assets/6032426/19121033/02a281d2-8af3-11e6-8b97-28f39f0eed30.png)

Link to bio: https://san-rafael-ca.proudcity.com/contacts/jim-schutz/

Something like this would either need to be unique to SR or the ability to enable/disable because not all of our cities actually fill in the bio detail (including this example).

**Comment by jlyon** [comment]
I added a new Contact name link field that appears when a contact name has been entered. If you leave this field blank, the Contact name will just appear as text. If you add a link, the contact name will be linked.

**Comment by jlyon** [comment]
I added a new Contact name link field that appears if you add a contact name.  If it is empty, the name will appear as text, if a link it entered, the name will be a link.
