### ISSUE TITLE
Search: departments have "sorry, this menu has been initialized without a valid option" message in search results

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#594]
![screen shot 2016-10-05 at 9 36 02 am](https://cloud.githubusercontent.com/assets/6032426/19123421/9453a328-8afc-11e6-8a9d-f78d5e6afd17.png)

The "sorry, this menu has been initialized without a valid option" is coming up for other departments in the search results. This view comes up on the results page after you hit enter.

**Comment by jlyon** [comment]
This will be fixed in this release.

**Comment by jlyon** [comment]
Still seeing this on SR. I think this is some kind of issue with caching. Re-saving the Sustainability Agency didn't do it. We need to look into it more @kevindherman @aschmoe

**Comment by jlyon** [comment]
It looks like this was fixed after some caches cleared up post-release. Here's the snippet I see for sustainability on https://san-rafael-ca.proudcity.com/search-site/?term=sustainability#/

![screenshot from 2016-10-12 16 57 31](https://cloud.githubusercontent.com/assets/550909/19332003/119779ae-909d-11e6-801a-1e0cca81de15.png)

**Comment by kevindherman** [comment]
@jlyon sweet, looks good for me too.
