### ISSUE TITLE
311 actions box: Increase limit to number of Issue categories displayed, number of posts within a category that are shown

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#595]
zendesk:

Rebecca
Today 12:28
 
Actually, is there a limit to how many can be there? It looks like others are dropping off as well.

________________________________

 
Rebecca
Today 12:21

I'm trying to add an "Other" category to the report and issue area. I want it to appear last, so I tried toggling the date back, but it won't show up.

**Comment by jlyon** [comment]
@kevindherman Fixed this. Will be pushed in the release. It was limiting these lists to 10 posts. I pushed it up to 100.

**Comment by jlyon** [comment]
These seem to be loading slowly now.  Perhaps we should revisit?

**Comment by jlyon** [comment]
This does not appear to be affecting pageloads. It was likely the introduction of the broken link checker.
