### ISSUE TITLE
Crawford: file upload error

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#598]
Error after uploading PDF to this doc: https://www.crawfordcountytcc.org/wp-admin/post.php?post=319&action=edit

![screenshot 2016-10-05 15 22 53](https://cloud.githubusercontent.com/assets/6032426/19128095/ccc515da-8b0f-11e6-9685-1201c789f098.png)

**Comment by jlyon** [comment]
@kevindherman Fixed this.  There was a file permissions issue with their site.
