### ISSUE TITLE
Icon widget enhancements

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#60]
- [x] Icon picker
- [x] accordions
- [ ] drag n drop ordering
- [ ] add/remove items
- [ ] use wordpress page selector for path
- [ ] show link title as the accordion title
- [ ] Iconset doesn't publish if a link isn't provided. https://trello.com/c/MB9j3CbU/59-iconset-doesn-t-publish-if-a-link-isn-t-provided

**Comment by aschmoe** [comment]
Icon picker works, no?

**Comment by aschmoe** [comment]
No doesn't work now, will fix

**Comment by jlyon** [comment]
this is what i see on west carrollton
![screenshot from 2016-01-22 03 10 51](https://cloud.githubusercontent.com/assets/550909/12509228/ce974650-c0b5-11e5-94ae-9bba0bf46d92.png)

**Comment by aschmoe** [comment]
K fixed now WC + beta
