### ISSUE TITLE
Icon Button Cards: break into two columns on mobile

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#605]
Change `card-columns-xs-1` to `card-columns-xs-2`

![home - san rafael 1](https://cloud.githubusercontent.com/assets/550909/19141879/f606020e-8b4d-11e6-9951-937f6660efcf.jpg)

**Comment by jlyon** [comment]
@aschmoe Shall we do this in the release?  I think it would make a difference on mobile (noticed this during the demo yest).

**Comment by aschmoe** [comment]
@jlyon sure, feel like there was a reason (long titles) why I didn't like this, but some testing looks like it works fine
