### ISSUE TITLE
PO: unable to login from my.proudcity.com

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#608]
after submitting credentials from my.proudcity.com they are directed to the homepage without dashboard access.

**Comment by kevindherman** [comment]
@jlyon I got more details: 
![image001](https://cloud.githubusercontent.com/assets/6032426/19160838/67928ac0-8bbf-11e6-81b9-b643011c92e0.jpg)

**Comment by jlyon** [comment]
Sorry, just fixed this @kevindherman
