### ISSUE TITLE
SR: how can you list multiple phone numbers for dept contacts?

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#610]
This would be the the contact widget on the dept homepage and /contact page.

**Comment by jlyon** [comment]
You can't currently. Should we just let them do it by separating them with a comma?

**Comment by kevindherman** [comment]
@jlyon I think that would work. Do you think that will format weird on the contact page?

**Comment by kevindherman** [comment]
@jlyon @aschmoe I got some more guidance on this page. So some of the larger departments have divisions within them that have their own contact info and hours. For example, business licenses has a public counter with a direct line, manager and hours of operation. 

Division contact info could be listed on the department's contact page but that would probably get buried and wouldn't feed to the /contact-departments page.  

Is there a solution that would play well with contacts? Anything above just listing as content would be customization.
