### ISSUE TITLE
French Creek: auth0 error, can't login

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#611]
french creek cog login does not work, all other three work correctly for west mead, crawford county tcc and venango township. i am logging in with google.
ProudCity
Oops!, something went wrong

Callback URL mismatch.
The url "https://www.frenchcreekcog.org/index.php?auth0=1" is not in the list of allowed callback URLs: https://example-agency.proudcity.com/index.php?auth0=1, https://west-carrollton-oh.proudcity.com/index.php?auth0=1, https://www.westcarrollton.org/index.php?auth0=1, https://topeka-ks.proudcity.com/index.php?auth0=1, https://weston-wi.proudcity.com/index.php?auth0=1, https://example.proudcity.com/index.php?auth0=1, https://palo-alto-ca.proudcity.com/index.php?auth0=1, https://albemarle-county-va.proudcity.com/index.php?auth0=1, https://automattic.proudcity.com/index.php?auth0=1, https://cleveland-heights-oh.proudcity.com/index.php?auth0=1, https://massachusetts.proudcity.com/index.php?auth0=1, http://localhost:8080/index.php?auth0=1, https://beta.proudcity.com/index.php?auth0=1, https://san-ramon-ca.proudcity.com/index.php?auth0=1, https://pittsburg-ks.proudcity.com/index.php?auth0=1, https://san-rafael-ca.proudcity.com/index.php?auth0=1, https://evanston-il.proudcity.com/index.php?auth0=1, https://ventura-ca.proudcity.com/index.php?auth0=1, https://venangotwp.org/index.php?auth0=1, https://de-leon-tx.proudcity.com/index.php?auth0=1, https://hinsdale-ma.proudcity.com/index.php?auth0=1, https://www.warracres-ok.gov/index.php?auth0=1, https://westmead.org/index.php?auth0=1, https://dept-wildlife-la.proudcity.com/index.php?auth0=1, https://french-creek-pa.proudcity.com/index.php?auth0=1, https://deport-tx.proudcity.com/index.php?auth0=1, https://san-rafael-ca-parks.proudcity.com/index.php?auth0=1, https://frenchcreekcog.org/index.php?auth0=1, https://www.crawfordcountytcc.org/index.php?auth0=1, https://oakland-ca.proudcity.com/index.php?auth0=1, https://monrovia-ca.proudcity.com/index.php?auth0=1, https://morris-nj.proudcity.com/index.php?auth0=1, https://morris-nj-planning.proudcity.com/index.php?auth0=1, https://danvers-ma.proudcity.com/index.php?auth0=1, https://lucas-tx.proudcity.com/index.php?auth0=1, https://www.cityofportorchard.us/index.php?auth0=1, https://rosalia-wa.proudcity.com/index.php?auth0=1, https://woodcock-pa.proudcity.com/index.php?auth0=1, https://kettering-oh.proudcity.com/index.php?auth0=1, https://ephrata-wa.proudcity.com/index.php?auth0=1, https://opendatasoft.proudcity.com/index.php?auth0=1.
Please go to the Application Settings page and make sure you are sending a valid callback url from your application.

**Comment by jlyon** [comment]
fixed this
