### ISSUE TITLE
SR Parks: add social accounts for social wall

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#613]
Please provide these social media links so that I can include them in the social media feed. These are the only links we'll include in the subsite for now. 
https://www.facebook.com/sanrafaelcommunityservices.recreation/ 
and https://twitter.com/livelifelocally

**Comment by aschmoe** [comment]
@kevindherman this changed a bit, no?  Are we still looking to make these specific additions?

**Comment by kevindherman** [comment]
@aschmoe I think they still want to have the ability to use the social wall and have them listed in the footer.
