### ISSUE TITLE
PO: link to /subscribe from footer

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#614]
How do you add the "subscribe to more lists" link in the footer like on San Rafael? It's the last step for setting up Port Orchard's subscribe page: https://www.cityofportorchard.us/subscribe/

![screenshot 2016-10-12 11 30 43](https://cloud.githubusercontent.com/assets/6032426/19316454/7becbe64-906f-11e6-8c91-e9d4fcbcf733.png)

**Comment by jlyon** [comment]
I added a HTML field to the Form. From /wp-admin/admin.php?page=gf_edit_forms&id=1:

![screenshot from 2016-10-12 17 44 26](https://cloud.githubusercontent.com/assets/550909/19332718/904f9406-90a3-11e6-9487-7c5b0dc31eaf.png)

Let me know if you want me to set this up on PO @kevindherman

**Comment by kevindherman** [comment]
@jlyon thanks, just added it.

**Comment by kevindherman** [comment]
@jlyon is it possible to move the subscribe to other lists text/link to be under the submit button?

**Comment by kevindherman** [comment]
@jlyon while you're tinkering with the footer, can you add Disclaimer & Privacy Policy next to Directory | Feedback linking to this page: https://www.cityofportorchard.us/disclaimer-privacy-policy/

I don't have access to editing that area in the footer.

**Comment by kevindherman** [comment]
@jlyon can you move the subscribe to more lists to under the subscribe button in this release?

**Comment by kevindherman** [comment]
@jlyon what's blocking this item? If this isn't something we want to do that's fine, I just need to communicate back to them since this ticket has been open for awhile.
