### ISSUE TITLE
SR: social wall not pulling all data

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#615]
From ZenDesk:

"how does the social wall work? it doesn't seem to be posting everything."

@aschmoe is there an issue or is it only pulling certain information? I realize this is vague, let me know what followup information would be helpful if the answer is clear.

**Comment by kevindherman** [comment]
@aschmoe the city instagram and the city facebook are the ones that aren't pulling.

**Comment by kevindherman** [comment]
@aschmoe The SR social wall is pulling some wrong information. The bottom right post points to their library's account but the actual post with  #gayboysofinstagram isn't their account. Super weird.

![screenshot 2016-10-24 16 48 25](https://cloud.githubusercontent.com/assets/6032426/19663517/4646a654-9a0a-11e6-8692-afe4824500f2.png)

**Comment by aschmoe** [comment]
@kevindherman this was the post pulled in https://www.facebook.com/srpublib/posts/10155494652884498 and when I tried to go to their main page I was hit with a robots text box ... might want to have them query FB about if they had suspicious activity or something.

**Comment by aschmoe** [comment]
@kevindherman in the mean time I will remove that post

**Comment by aschmoe** [comment]
@kevindherman the offending post has been removed here's the photo attached to that post if they want to contact FB https://scontent.xx.fbcdn.net/v/t1.0-9/p720x720/14713639_10155494652884498_945203179915937461_n.jpg?oh=f0c962feb5701064b19b8294f8411872&oe=588A72B4

**Comment by aschmoe** [comment]
@kevindherman tracking this in #678, closing
