### ISSUE TITLE
Make Draggable ordering the default for Issues, Answers, Payments

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#618]
From ZenDesk:

I am attempting to put the Report an Issue items in alphabetical order, and for some reason, Noise Complaint is just not moving out of the 1 spot. Also, I attempted using the drag and drop selection for ordering them, but it only puts them in that order for the admin, it doesn't transition to that order on the actual site, so i had to go change the publish date on all of them.

**Comment by jlyon** [comment]
@kevindherman  Draggable ordering is now the default for 
Issues
Answers
Contacts
Payments

Should we also make it the default for:
Departments (currently using alphabetical)
Documents (currently using published date)

**Comment by jlyon** [comment]
Pushed a fix for a lingering issue with this as Hotfix 1.17.1
