### ISSUE TITLE
City logos/ Customization

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#62]
To finalize: put image in proudly serving box, or in the header?

What do we do about imgs w bgs?

- [x] Logo formatting
- [x] Color options
- [x] Make base font size smaller and/or different (open Sans)?
- [ ] Allow selection header/body fonts (from small list)?
- [ ] Nav link color

**Comment by jlyon** [comment]
Do we want logos for agencies?

**Comment by kevindherman** [comment]
Can it be an option on the agencies page? Logo or Image?

**Comment by jlyon** [comment]
make header big by default, shrink as user scrolls down

**Comment by jlyon** [comment]
figure out footer image stuff

**Comment by jlyon** [comment]
putting advanced customization options in #122, closing this
