### ISSUE TITLE
PO: Pagefreezer

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#620]
Hello Brandy, Kevin,

We tried crawling the website but it did not work. We are suspecting that our crawlers are still blocked, and currently trying to confirm that.

In the meantime, can you check if our crawlers are blocked on your end?

Richard
PageFreezer.com Support Team
support@pagefreezer.com | http://support.pagefreezer.com | (888) 916 3999

Take advantage of our free online training sessions every Thursday morning at 11:00am PST. Sign up now at: 
https://www.pagefreezer.com/free-training/

RP (PageFreezer)
Oct 12, 16:01 PDT

Hello Brandy,

We found that we were no longer able to capture your website. It seems like our crawlers are not able to access the website. Can you contact your website administrator and have our IP addresses whitelisted for access?

173.225.16.66
173.225.16.67
173.225.16.68
173.225.16.69
173.225.16.74
173.225.16.75
216.168.59.178
216.168.59.179
216.168.59.180

If you have any questions, please let us know. Thank you.

Richard
PageFreezer.com Support Team
support@pagefreezer.com | http://support.pagefreezer.com | (888) 916 3999

Take advantage of our free online training sessions every Thursday morning at 11:00am PST. Sign up now at: 
https://www.pagefreezer.com/free-training/

**Comment by jlyon** [comment]
Moving to done. Tracking the rest in #637
