### ISSUE TITLE
Make Draggable ordering the default for Documents, Departments

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#623]

**Comment by kevindherman** [comment]
@jlyon this came in from PO in ZenDesk:

I was asked to re-order the Land Use applications at: https://www.cityofportorchard.us/planning-forms-applications/ 
When I go to my documents, and drag the applications in the order I would like, 'Save Order', it does not change the order of the applications on the site. Form #003 should go first, Form #005 second, etc. We are trying to put them in numerical order. Please let me know what I am doing wrong! 
Thanks,

**Comment by jlyon** [comment]
Putting this into the release today.

**Comment by jlyon** [comment]
@kevindherman I made the draggable order the default sort for Documents and Departments.  Please spread the word.

**Comment by kevindherman** [comment]
@jlyon I'm getting positive feedback on the document ordering but not the same for the departments, including SR who is hoping to get the alphabetical default back for dept's.

What are you thoughts?
