### ISSUE TITLE
Editor is not appearing on Page, Answer, etc edit screens

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#635]
@jlyon this was originally reported during the downtime when I was flying back on Thursday. The below message and screenshot is from today after clearing their cache. 

Hi Kevin,

Sorry I didn’t see this message sooner, but I still don’t have any editing rights in some of the pages: Street Resurfacing, Projects out to Bid and Upcoming Projects.

![image001 1](https://cloud.githubusercontent.com/assets/6032426/19655695/e5ceeee0-99ea-11e6-81dc-c20b4d27a5c8.jpg)

**Comment by jlyon** [comment]
@kevindherman This has been fixed and deployed immediately platform-wide as Hotfix 1.17.2.

**Comment by jlyon** [comment]
@kevindherman Some users may need to do a hard refresh (hold down Shift and hit Refresh) to see the changes.
