### ISSUE TITLE
WC: header image cropping issue

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#636]

**Comment by aschmoe** [comment]
@kevindherman I'm pretty sure we've changed nothing about how that's being done.

Perhaps going from "Full Header" to "Header" has restricted the view-port.  I think an option to align image [ ] top [x] middle [ ] bottom might be nice here

**Comment by kevindherman** [comment]
@aschmoe yeah I can't figure out how to fix it within the existing settings. I think that alignment option could help.

**Comment by aschmoe** [comment]
@kevindherman made this an option in the widget
