### ISSUE TITLE
PO: PageFreezer trouble archiving Angular pages

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#637]
@jlyon @aschmoe what do you think of the Angular issue?

Hi Brandy and Kevin,

The website archive is almost fully working. There are some missing images due to the fact that we currently do not support "srcset" attribute.

Also, "Answers", "Payments", "Issues" and "Search" functions do not work. The site uses Angular JS, and JavaScript files were minified (hidden), which is preventing our system from replicating these functions correctly. We had to disable Angular JS in the archive settings in order for it to work.

Otherwise, all pages/contents are captured, including PDF documents.

Kevin, is there something on your end that you can do differently in the development of the website? I am just thinking out loud here.

Thank you both for your continued patience on this.

Cheers,

**Comment by aschmoe** [comment]
@kevindherman we're not going to ditch angular, I feel a little skeptical that their system could replicate the functionality even if it was un-min'd, and the answers action box is heavily reliant on API calls, so not sure that really works for page freezer anyways.  

Probably best option would be to have some plain-html listing of all the answers that could service as the "record" for FAQs in a system like page freezer.

**Comment by kevindherman** [comment]
@aschmoe yeah, definitely didn't think we would ditch angular for this. The plain listing option makes sense to me.

**Comment by kevindherman** [comment]
@aschmoe @jlyon is that something we could/want to have in the next release?

**Comment by kevindherman** [comment]
@jlyon @aschmoe they said the plain-html record would work for them and to let them know when it's done for Port Orchard. If it's a quick, it would help to do as a hotfix. PO for some reason actually gets a lot of FOIA requests.

**Comment by kevindherman** [comment]
@jlyon @aschmoe I'm changing this from PageFreezer to PO. It would be great to have this as part of the release tomorrow.

**Comment by jlyon** [comment]
I'll look at this today.

**Comment by kevindherman** [comment]
@jlyon could this item be a hotfix? I want to make sure this works for PO because SR is going to setup pagefreezer soon and I want to make sure it's seamless for them.

**Comment by kevindherman** [comment]
From PageFreezer:

Hi Kevin,

Hope all is well and that you had a great Thanksgiving!

I wanted to update you on our development teams efforts in finding a solution for City of Port Orchard - the issue will be resolved before the New Year. We are updating our web crawlers so that they can pick up AJAX code which is what has been the main issue. 

I will follow up with you again soon.

Cheers, 

Ira

@jlyon @aschmoe ^

**Comment by aschmoe** [comment]
@kevindherman we made it so each question has a static HTML page.

These can be found through the XML sitemap https://www.cityofportorchard.us/question-sitemap.xml

**Comment by aschmoe** [comment]
@kevindherman 

> The website archive is almost fully working. There are some missing images due to the fact that we currently do not support "srcset" attribute.

Does this too have a solution coming?

**Comment by kevindherman** [comment]
@aschmoe I passed along the static page and question to PageFreezer. Will post back with more info.

**Comment by kevindherman** [comment]
@aschmoe from PageFreezer:

Hi Kevin,

The site maps will help - thank you. However the main issue is Ajax code which we are working on.

Regarding srcset images - we have a new crawler that should be able to capture it - the dev team is working on this and will be part of the overall fix.

Cheers,
