### ISSUE TITLE
Service Center: Add map

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#644]
#/city/maps

- [x] Standalone widget
- [x] Google places (to replace foursquare)
- [x] Make pins clickable
 - on /maps, it should pull out in a sidebar
 - card view for local services, or should this link to something like /city/maps/schools/[post-slug]? 
 - Make sure all fields appear
- [x] Clear out map layers/pins when visiting multiple maps
- [x] Rm dependency on (ng-map??), because we're not really using it

**Comment by jlyon** [comment]
@aschmoe forgot about Google places (to replace foursquare)

**Comment by aschmoe** [comment]
> Rm dependency on (ng-map??), because we're not really using it
We are using this (currently at least).

**Comment by aschmoe** [comment]
> Rm dependency on (ng-map??), because we're not really using it
@jlyon this has been removed
