### ISSUE TITLE
Add "Posted on" before news published date

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#649]
From WA:

I see where it does there, but that is after you open the news item. Where we need it is on our home page. There is a list of news items just below the main image area. These have the title and then the date posted just under it. If the news post is for an event, such as our Free CPR Classes, it makes it look like the CPR classes are on August 12, 2016 which is when the post was created. I would prefer for these to just not have the date visible if possible.

I think in most cases the published on date for the news feed is important so perhaps it should always say "posted on" like the full post. 

https://www.warracres-ok.gov/free-cpr-classes/
![screenshot 2016-10-27 11 04 42](https://cloud.githubusercontent.com/assets/6032426/19772861/8c2d2ba2-9c35-11e6-89be-f97a01f6b202.png)

homepage:
![screenshot 2016-10-27 11 00 59](https://cloud.githubusercontent.com/assets/6032426/19772883/9c4ca148-9c35-11e6-988b-924df0876c37.png)

**Comment by jlyon** [comment]
Added
