### ISSUE TITLE
WA: authenticated users unable to view private pages

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#650]
From ZenDesk:

we setup a page at https://www.warracres-ok.gov/staffinput/ that is supposed to be visible to any of our people who have a login to edit, post etc. It is visible to me, but the court clerk (courtclerk@warracres-ok.gov) was not able to view the page. Her being able to view this page was the primary reason it was created.

When I navigated to the page when logged in as support I was able to view the page so I'm not sure what permission is blocking that specific account. I asked to confirm that the user was logged in and got a snarky response, so lets assume that they were.

**Comment by jlyon** [comment]
@kevindherman I don't see courtclerk@warracres-ok.gov as a user.  Cityclerk@warracres-ok.gov is a user.

**Comment by kevindherman** [comment]
@jlyon I'll see if they were maybe using wrong account or if they do need that extra user. I'll post back.

**Comment by jlyon** [comment]
Any word back @kevindherman ?

**Comment by kevindherman** [comment]
@jlyon he wrote the wrong email in the ticket, he meant cityclerk@warracres-ok.gov. I'm waiting for him to confirm if it's still and issue.

**Comment by jlyon** [comment]
kewl

**Comment by kevindherman** [comment]
@jlyon he confirmed that cityclerk@warracres-ok.gov is still unable to view the page when logged in.

**Comment by jlyon** [comment]
@kevindherman I was able to login as  cityclerk@warracres-ok.gov, and I am unable to replicate the issue.  I can see https://www.warracres-ok.gov/staffinput/:
![staffinput - city of warr acres](https://cloud.githubusercontent.com/assets/550909/20816732/9efb1622-b7d8-11e6-9deb-d5ce00d896cf.jpg)

If they are still having the issue, could they send a screenshot of what they are seeing when they visit https://www.warracres-ok.gov/staffinput/ as  cityclerk@warracres-ok.gov?

**Comment by jlyon** [comment]
@kevindherman is this still an issue? Did they just give up on this?

**Comment by kevindherman** [comment]
@jlyon I'm going to go with gave up.
