### ISSUE TITLE
SR: new icon bug

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#655]
All of the new button icons from our designer are showing up as boxes.

![icon buttons](https://cloud.githubusercontent.com/assets/6032426/19934396/ddc3f098-a0ec-11e6-9116-b23d2a63d239.JPG)

**Comment by aschmoe** [comment]
@kevindherman do we have a page for this?

**Comment by kevindherman** [comment]
@aschmoe I'll get one for ya.

**Comment by kevindherman** [comment]
@aschmoe here's one page https://san-rafael-ca.proudcity.com/departments/planning/

**Comment by aschmoe** [comment]
@kevindherman looks like there was a versioning issue with themes, and they were seeing the main GovIcons set.  This has been rectified and they should again be seeing the SR custom icons in the selector.

**However** unfortunately they will have to go back through and re-select icons that appear this way from the edit page

**Comment by kevindherman** [comment]
@aschmoe got it.

I'll let them know. Thanks.
