### ISSUE TITLE
SR: adjusting column width in tables

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#656]
How do you adjust the width of a column in a table? For instance, on this table, how could I center the column so that both columns are equal in width?

https://san-rafael-ca.proudcity.com/use-permit/

**Comment by jlyon** [comment]
1. Click into the table cell (or select all the cells in the table).
2. Click on the Table icon > Cell > Table cell properties:
![screenshot from 2016-11-02 15 25 41](https://cloud.githubusercontent.com/assets/550909/19949747/c24c9f94-a110-11e6-9e31-b5f7f0c82731.png)
3. Set the width to "50%" in the modal:
![screenshot from 2016-11-02 15 25 17](https://cloud.githubusercontent.com/assets/550909/19949754/d12f458e-a110-11e6-9253-0a75449b304c.png)
