### ISSUE TITLE
SR Evaluate why SR had older tag: 1.0.2 checked out after release

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#657]
@jlyon SR theme had older tag checked out presumably since the last release.  This easily could have been carelessness on my part, but we should make sure releases are deploying latest theme changes

**Comment by jlyon** [comment]
@aschmoe this is the SR custom theme, right?

**Comment by aschmoe** [comment]
@jlyon yeah this was custom

**Comment by jlyon** [comment]
k added to release manual test steps. moving this to ready.
