### ISSUE TITLE
SR: featured image on post not attaching

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#663]
When I try to set a featured image to this news post it doesn't add the image after I select an image and hit "set featured image" from the media library.

https://san-rafael-ca.proudcity.com/street-sweeping-leaf-vacuuming-november-5-2016/

![screenshot 2016-11-04 10 55 20](https://cloud.githubusercontent.com/assets/6032426/20010106/4fdf7f58-a27d-11e6-9972-d60865d0a8a7.png)

and then it's still blank:
![screenshot 2016-11-04 10 00 51](https://cloud.githubusercontent.com/assets/6032426/20010112/582ce3a8-a27d-11e6-8c0f-1415bd1a9668.png)

**Comment by aschmoe** [comment]
This was pushed as hotfix
