### ISSUE TITLE
Some icons are very small

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#669]
Some icons on Lucas are very small: https://lucas-tx.proudcity.com/

![screenshot 2016-11-08 11 03 58](https://cloud.githubusercontent.com/assets/6032426/20106449/330582aa-a5a3-11e6-92ba-59bda4d613b7.png)

**Comment by kevindherman** [comment]
@aschmoe I have a hunch these are the govicons since it's isolated to Lucas.

**Comment by aschmoe** [comment]
@kevindherman deploying this as a hotfix

**Comment by kevindherman** [comment]
@aschmoe thanks.
