### ISSUE TITLE
SR: Add numbers and symbols into iconset

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#672]
Is this possible?

SR wants to create steps similar to Boston and I thought numbers in the iconset could do the trick:

https://www.boston.gov/departments/parking-clerk/how-pay-parking-ticket

**Comment by aschmoe** [comment]
@kevindherman I don't think iconsets are the right way to do this.  Do we feel like this is a useful widget to to have globally?  If not I could probably come up with some html that would work for them

**Comment by jlyon** [comment]
@aschmoe I dont know if a widget is the way to go for this? Maybe just a class that they can add to a `<ol>`?

**Comment by aschmoe** [comment]
yeah thats what I mean, just some html / css

**Comment by kevindherman** [comment]
@aschmoe @jlyon the content probably won't be ready for the launch so I don't think a custom route  makes sense here. 

The iconset suggestion was because that functionality is there and then they could add it when they're tinkering with the content/layout down the road.
