### ISSUE TITLE
Drag and Drop: Allow a custom number of items per page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#673]
How do you use the drag and drop re-ordering feature if a content item (documents, answers, etc.) is on a different content list page. 

For example, PO has 27 pages of documents, how can you reorder between those pages:
https://www.cityofportorchard.us/wp-admin/edit.php?post_type=document

![screenshot 2016-11-14 15 59 22](https://cloud.githubusercontent.com/assets/6032426/20282619/7aa43cca-aa83-11e6-9423-5cc62061ce63.png)

**Comment by jlyon** [comment]
There's no great way to do this currently.  There is an "Admin bar" where you can increase the number of items per page that we could unhide (we were hiding it in an effort to keep the interface uncluttered).

**Comment by kevindherman** [comment]
@jlyon I think that would do the trick, at least on pages that have long sortable content lists: documents, answers and probably departments.

**Comment by jlyon** [comment]
Add a screen options button in the top-right that lets you specify the number of items to show per page.

**Comment by kevindherman** [comment]
@jlyon this is perfect.
