### ISSUE TITLE
Lucas: remove payment icon from top nav

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#674]
Hello,

Can you please update the top navigation icons as follows:

-Remove payment icon as they are not taking online payments at this time. 
-Link the wrench icon to https://lucas-tx.proudcity.com/report-an-issue/

**Comment by kevindherman** [comment]
@jlyon @aschmoe I thought this ticket existing somewhere but I couldn't find it. Sorry if it's duplicated.

**Comment by jlyon** [comment]
This is all set @kevindherman

**Comment by kevindherman** [comment]
@jlyon thanks, this was one of my hotfixes. They're hoping to launch in 2 weeks.

**Comment by jlyon** [comment]
great
