### ISSUE TITLE
SR: instagram not on social wall

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#678]
@aschmoe from SR:

"does the social wall watch instagram? i don't see the sanrafaelawesome instagram posts"

**Comment by kevindherman** [comment]
@aschmoe this is still an issue. I've moved it up the priority list for today.

**Comment by aschmoe** [comment]
Looks like we need to get our instagram app out of sandbox mode, here are some notes on what to do

https://github.com/stevenschobert/instafeed.js/issues/345#issuecomment-259041265

**Comment by jlyon** [comment]
hmm. https://github.com/rarcega/instagram-scraper-node maybe?

--
Jeff Lyon
Director of Web Development
Albatross Digital

www.albatrossdigital.com | jeff@albatrossdigital.com | 541.760.1838

**Comment by aschmoe** [comment]
Implemented a scraping approach instagram
