### ISSUE TITLE
Service Center: Facebook: Mobile solution

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#680]

**Comment by jlyon** [comment]
@kevindherman 

Facebook has Call to Action buttons that appear at the top of Facebook pages in both Desktop and Mobile: https://www.facebook.com/business/help/312169205649942/?ref=u2u.  I added this to https://www.facebook.com/CityofSanRafael.

These buttons have limited options for the label. These seemed like the best option for the Service center:
- Use App
- Learn More

Questions:
- Which label do we want to use?
- Where should this link to? It currently links to the Facebook app page. Should it go somewhere else, or should it vary based on how it is being viewed? Somthing like
 - Desktop: Full website or standalone (https://san-rafael-ca.proudcity.com/standalone)?
 - Mobile responsive:
  - Facebook tab: https://san-rafael-ca.proudcity.com/fbtab (maybe with an extra back button at the top?)
  - Mobile app: https://san-rafael-ca.proudcity.com/app
- Facebook mobile app: 
  - Facebook tab (FB adds a back button bar to the top): https://san-rafael-ca.proudcity.com/fbtab (this is what is currently setup)

**Comment by kevindherman** [comment]
@jlyon I'm pulling in @aschmoe for his thoughts.

I think "use app" label makes more sense than "learn more". I also think that the page should vary on how it is being viewed, your breakdown makes sense to me.

**Comment by jlyon** [comment]
I fixed this redirect so it points to a ProudCity endpoint that checks if it's desktop or mobile: https://rest.proudcity.com/mobile-redirect?desktop=https%3A%2F%2Fwww.facebook.com%2FCityofSanRafael%2Fapp%2F1358980630789577&mobile=https%3A%2F%2Fwww.cityofsanrafael.org%2Fstandalone.

* If desktop: redirects to FB app page
* If mobile: redirects to Standalone Service center (Question: do we like https://www.cityofsanrafael.org/standalone or https://www.cityofsanrafael.org/fbtab more for this)?

cc @kevindherman @aschmoe

**Comment by kevindherman** [comment]
I'm second guessing "use app" for users that are already in the fb app. Although it may be redundant in some places, "Service Center" is more direct.

**Comment by jlyon** [comment]
We don't get to set a custom label.  The two options we have (from Facebook) are:
Use App
Learn More

**Comment by kevindherman** [comment]
@jlyon I think you're right. Thanks for clarifying.
