### ISSUE TITLE
SR: yoast SEO snippet

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#682]
Yoest SEO Snippet not pulling title, page, sitename automatically.

https://san-rafael-ca.proudcity.com/wp-admin/post.php?post=2224&action=edit

![screenshot 2016-11-28 13 55 29](https://cloud.githubusercontent.com/assets/6032426/20681638/726ef690-b572-11e6-8c19-1b12dff1ea24.png)

**Comment by jlyon** [comment]
@kevindherman  Hmm, this appears to be working when I visit this page logged in as support.  Is this still happening for you? If so, what browser and username?

**Comment by kevindherman** [comment]
@jlyon weird, working as it should now. This can be closed.
