### ISSUE TITLE
SR Parks: swap in their logo for main city logo

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#686]
https://san-rafael-ca-parks.proudcity.com/

![new community services logo 08](https://cloud.githubusercontent.com/assets/6032426/20728639/aa3dd76e-b64c-11e6-8547-a737f2d0273c.jpg)
![srcc_logo_225x119](https://cloud.githubusercontent.com/assets/6032426/20728638/aa3bb920-b64c-11e6-8eb5-7dc241226de8.png)

**Comment by aschmoe** [comment]
@kevindherman we're going to need new colors for the community services site then
![sr-community-logo](https://cloud.githubusercontent.com/assets/1634686/20735834/8fe9c07a-b657-11e6-8b1d-d68ac5d6a0d4.png)

**Comment by kevindherman** [comment]
@aschmoe do you have color suggestions/mockups like this I can show them to pick between to speed things up?

**Comment by kevindherman** [comment]
@aschmoe can you provide some guidance on this today? I need to get something in front of them as soon as possible.

**Comment by aschmoe** [comment]
@kevindherman the only look that works is all white, no transparency on the menu see https://san-rafael-ca-parks.proudcity.com/ now

**Comment by kevindherman** [comment]
@aschmoe thanks, I'll share. I feel like what we had before with the city logo and the dept name looked better.

**Comment by kevindherman** [comment]
@aschmoe this can be closed,.

**Comment by jlyon** [comment]
Moving to readfy.
