### ISSUE TITLE
SR Parks: social in footer

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#687]
There are 4 facebook pages listed in the footer of the parks site:
https://san-rafael-ca-parks.proudcity.com/departments/childcare/

![screenshot 2016-11-29 16 47 09](https://cloud.githubusercontent.com/assets/6032426/20730307/9a4d7b5a-b653-11e6-9e7b-87e19ceefcbe.png)

**Comment by aschmoe** [comment]
@kevindherman I updated it to only show 

facebook:sanrafaelcommunityservices.recreation
twitter:LiveLifeLocally
