### ISSUE TITLE
PO: making images ADA compliant

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#688]
@aschmoe I don't feel like I'm well versed in how this is supposed to work. Is this a bug or do the tags work in a way I don't understand?

From Zendesk:

Hello. I am going through our website to make it ADA accessible, and one of the suggestions is to add text equivalent to every image. I am trying to add text to the picture of our City Clerk: https://www.cityofportorchard.us/contacts/brandy-rinearson/
I have added the language 'City Clerk Brandy Rinearson' in the caption, alt. text, and description when I am editing the picture; however, no text is showing on the picture. I have added text to other pictures.

**Comment by jlyon** [comment]
Images just need alt text for Section 508 compliance.  The picture on https://www.cityofportorchard.us/contacts/brandy-rinearson/ has the alt text "City Clerk Brandy Rinearson", so you should be all set.

**Comment by aschmoe** [comment]
@kevindherman sounds like she is good to go on compliance (with in the included alt text), but you may want to ask her if the issue is that she wants captions
