### ISSUE TITLE
PO: header cut off on dept pages

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#689]
This looks like it's potentially and IE issue because I'm unable to replicate in Chrome or FF. I asked to get a IE version from their end.
https://www.cityofportorchard.us/departments/city-council/

Zendesk:

Please see the attached screenshot. I have received several complaints that the top of the page cuts off 'City Council', 'Mayor', etc. I have 2 monitors. When the website is open on the smaller monitor, the words are cut off and when it is opened on the larger monitor it is fine. Other people, no matter the monitor size, the words are cut.

[Screenshot.pdf](https://github.com/proudcity/wp-proudcity/files/622352/Screenshot.pdf)

**Comment by aschmoe** [comment]
@kevindherman you responded to them about this right?

**Comment by kevindherman** [comment]
@aschmoe yeah but then followed up about removing the "issues" icon since they don't use it to try and create more space. Could you give that a shot as part of the interim solution?

**Comment by aschmoe** [comment]
@kevindherman removed the issues button, still a problem... if they shorten "Municipal Code" to "Code" the problem seems to be resolved now.

**Comment by aschmoe** [comment]
Tracking the greater issue at hand in #702
