### ISSUE TITLE
WC: Document library

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#69]
- [x] post type
- [x] documents page
- [x] documents widget - specific taxonomy

**Comment by jlyon** [comment]
@kevindherman set this up:

* https://west-carrollton-oh.proudcity.com/city-council-agendas/
* https://west-carrollton-oh.proudcity.com/city-council-minutes/

**Comment by kevindherman** [comment]
@jlyon can you walk me through this today? I think I'm missing something and want to get Erika adding the content.

**Comment by jlyon** [comment]
Sorry, looks like I broke this when I was setting up some of the frontend for /contact.  I fixed it and the Limit to Category options should be self-explanitory now.  From: 
![screenshot from 2016-02-01 11 32 52](https://cloud.githubusercontent.com/assets/550909/12728621/92681b58-c8d7-11e5-8b27-d704fa7cc58c.png)
https://west-carrollton-oh.proudcity.com/wp-admin/post.php?post=2793&action=edit

Let me know if this still isn't clear and we can have a call abt it, or talk about it on our call later
