### ISSUE TITLE
Featured image not showing on dept page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#690]
For some reason the featured image on the sanitation page has disappeared. The Hero Unit looks right, and the image is set as a featured image, but it is gone. 
https://san-rafael-ca.proudcity.com/departments/sanitation-district/

**Comment by jlyon** [comment]
@kevindherman I re-uploaded the image and it seemed to fix it.  There must have been some  issue generating the resized version of the image, maybe because the source image was pretty large (although 2.5mb shouldn't have caused any problems).

**Comment by kevindherman** [comment]
@jlyon thank you.
