### ISSUE TITLE
Formatting of Agency contact info (Social media, hours)

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#691]
The placement of the twitter logo looks funny on this page. Is there a way to shift it? See attached screen shot and URL 
https://san-rafael-ca.proudcity.com/departments/business-license-division/

![screenshot 2016-11-30 12 34 29](https://cloud.githubusercontent.com/assets/6032426/20763794/8e133b3a-b6f9-11e6-81e8-418ef0906710.png)

**Comment by jlyon** [comment]
Fixed:
![screenshot from 2016-12-01 15 44 22](https://cloud.githubusercontent.com/assets/550909/20817532/2d192648-b7dd-11e6-947e-12ce3bbb1b41.png)
