### ISSUE TITLE
Lucas: live editor on departments

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#692]
Live editor on departments pulls a blank screen:

https://lucas-tx.proudcity.com/departments/parks-and-facilities/

![screenshot 2016-11-30 16 29 57](https://cloud.githubusercontent.com/assets/6032426/20772134/589f64d0-b71a-11e6-9c1b-79701a1d12bd.png)

**Comment by jlyon** [comment]
I'm seeing this as well. for some reason the live editor is having a memory issue on this page.  I tried bumping up the memory on the server, but I'm still getting the error.  Can he use the standard Edit page for now (https://lucas-tx.proudcity.com/wp-admin/post.php?post=5520&action=edit)? @kevindherman

**Comment by kevindherman** [comment]
@jlyon I'll pass this along. I'm sure it won't be a problem for now.
