### ISSUE TITLE
Add Approveme E-signature plugin

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#697]

**Comment by kevindherman** [comment]
@jlyon what's your recommendation for swapping in the new signature field? I just opened up an old form (https://san-rafael-ca.proudcity.com/wp-admin/admin.php?page=gf_edit_forms&id=21) and I'm not sure of the switch. Just need a hand guiding them through this update. 

Thanks.

**Comment by kevindherman** [comment]
@jlyon I just saw the post about connecting on the steps. Lets do this as an after meeting today.
