### ISSUE TITLE
SR Parks: edit primary links link times out

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#705]
When I click on primary links to edit the main nav the page times out:

![screenshot 2016-12-05 17 36 27](https://cloud.githubusercontent.com/assets/6032426/20905378/880806fa-bb11-11e6-9665-b2d0abc7e3b1.png)

**Comment by kevindherman** [comment]
@jlyon @aschmoe this is only happening on the parks site. I was able to get to the page I wanted by pasting in the url path: /wp-admin/nav-menus.php

Still can't navigate to that page directly though.

**Comment by kevindherman** [comment]
The primary concern is that she did something weird and now the contact-us page isn't in the primary nav: https://san-rafael-ca-parks.proudcity.com/contact-us/

However, when editing the primary nav menu page the contact-us page is showing:
https://san-rafael-ca-parks.proudcity.com/wp-admin/nav-menus.php?action=edit&menu=13

![screenshot 2016-12-06 13 23 15](https://cloud.githubusercontent.com/assets/6032426/20938019/56a314a0-bbb7-11e6-8200-8c522b5714ab.png)

**Comment by aschmoe** [comment]
@kevindherman she had managed to make contact us a child of the some parent thing that didn't exist... somehow.  I've since dragged it about, clearing the screw-up, and now works fine.
