### ISSUE TITLE
SR: events page too many redirects error

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#707]
From Zendesk:

I was playing around earlier and was getting a lot of error messages saying "too many redirects." I thought it was just something wrong with our internet, but it is also happening on my phone. I have attached a photo below and it specifically happened while trying to get to the /events/ page.

Michele just worked on a bunch of redirects...not sure that matters though.

![redirects](https://cloud.githubusercontent.com/assets/6032426/20931655/c6be62e8-bb9f-11e6-9d01-cc6de1cd0d28.JPG)

**Comment by kevindherman** [comment]
@jlyon this has been fixed and can be closed.

**Comment by jlyon** [comment]
For future reference: Needed to resave https://www.whitesulphurspringswv.org/wp-admin/options-permalink.php
