### ISSUE TITLE
SR: hitting tab when filling out web form shoots to bottom of page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#713]
Hitting tab when filling out the subscribe web form shoots to bottom of page rather than going to the next field. This seems to be isolated to https://san-rafael-ca.proudcity.com/subscribe/

Could it have to do with the conditional logic?

**Comment by jlyon** [comment]
@kevindherman I think it's because the same fields (from the email signup) appear on the page twice.

I think we need to add a tabindex parameter to the form embed widget. See #412.

**Comment by kevindherman** [comment]
@jlyon got it. 

Lets try and prioritize #412 since it's not just WA now.
