### ISSUE TITLE
SR: broken featured image

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#718]
Rebecca is trying to make it so the person's head in this head image isn't covered by the title text:
https://san-rafael-ca.proudcity.com/departments/homelessness/

![screenshot 2016-12-08 16 50 50](https://cloud.githubusercontent.com/assets/6032426/21029185/80223fee-bd66-11e6-8651-ef667c49db01.png)

Every time she tries to crop and add a new image, the featured image previews as broken:
https://san-rafael-ca.proudcity.com/wp-admin/post.php?post=6563&action=edit

![screenshot 2016-12-08 16 49 26](https://cloud.githubusercontent.com/assets/6032426/21029219/a50c6c9e-bd66-11e6-9bc0-a9f0f2d2ef1d.png)

@aschmoe could this be related to image update this afternoon?

**Comment by kevindherman** [comment]
@aschmoe finding a couple of the department header images are broken:

https://san-rafael-ca.proudcity.com/departments/city-managers-office/
https://san-rafael-ca.proudcity.com/departments/economic-development/

**Comment by aschmoe** [comment]
This was a migration issue with the stateless infrastructure, please reopen if happens again
