### ISSUE TITLE
Select event category when adding calendar widget

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#719]
Add the ability to select event categories when adding the calendar widget like the event list does.

**Comment by jlyon** [comment]
This one might be a little hard because the calendar widget is its own plugin.  How high of a pri is this @kevindherman ?

**Comment by kevindherman** [comment]
@jlyon not a launch blocker. It would be great if it can make it into a not so distant release.

**Comment by kevindherman** [comment]
@jlyon would be nice to get this into the release if possible

**Comment by jlyon** [comment]
Added.  There's an issue with the fullcalendar plugin we're using where it displays the color code in the title in the top-left when setting the category. Maybe a fix for another day, or just forget about it. @kevindherman 

![screenshot from 2017-03-02 13 24 23](https://cloud.githubusercontent.com/assets/550909/23527692/d2365122-ff4b-11e6-80b6-100876fc018e.png)
