### ISSUE TITLE
WC: Logo

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#72]

**Comment by jlyon** [comment]
- [ ] Jumpy on scroll
- [ ] Rm sidebars on WC logo

**Comment by jlyon** [comment]
@aschmoe think you can look at the animation part?  I couldn't make this look good with any kind of animation on the image (looked too cartoony).  Maybe just make the image fly up off the top of the screen?

**Comment by kevindherman** [comment]
@aschmoe  when the logo shows the larger banner covers page headers when logged in as admin. Not critical for launch but should fix it so when signed in you can see what page and news headers look like.

**Comment by jlyon** [comment]
@aschmoe do we still need to look into kevin's comment?

**Comment by aschmoe** [comment]
@jlyon no, that was a refresh issue.

**Comment by jlyon** [comment]
@aschmoe I made this change b/c the logo was getting warped.  any red flags?
https://github.com/proudcity/proudcity-patterns/commit/0463e7172ad6220083d566077b6fa05e9ca995eb

**Comment by aschmoe** [comment]
![screenshot_2016-02-06-10-31-54](https://cloud.githubusercontent.com/assets/1634686/12868539/6e838454-ccbd-11e5-88cf-73ce2809af7b.png)

**Comment by aschmoe** [comment]
@jlyon no should be fine.
