### ISSUE TITLE
K: what does red font awesome text mean?

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#722]
What does the red font awesome text mean? 
![screenshot 2016-12-09 10 29 02](https://cloud.githubusercontent.com/assets/6032426/21054298/0c3c0c96-bdfb-11e6-9b8c-c5d13d07d764.png)

I told them for the FAQ topic icons they could go to http://fontawesome.io/icons/ to view the icons list if that helps provide insight.

**Comment by jlyon** [comment]
@kevindherman  This is the icon that's used in the service center.  We should probably make the input for these more like the map layers now that we can...

![west carrollton](https://cloud.githubusercontent.com/assets/550909/22493062/42998190-e7e2-11e6-9a85-ac845ba68cc4.jpg)

**Comment by kevindherman** [comment]
@jlyon by making more like the map layer, would that be pre-determined for the common categories?

**Comment by jlyon** [comment]
Yah, just like it currently is
