### ISSUE TITLE
SR: search result order

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#724]
@aschmoe the Mayor asked about the search result order for these:

![pastedimage 1](https://cloud.githubusercontent.com/assets/6032426/21059707/cc7edef0-be11-11e6-9322-ef2593854336.png)
![pastedimage](https://cloud.githubusercontent.com/assets/6032426/21059708/cc7ed93c-be11-11e6-9909-4ce21b02a35b.png)

**Comment by aschmoe** [comment]
@kevindherman the search system now respects menu order as one "weighting" option.  It should be noted that sometimes search relevancy may trump the order, but if the search relevancy is close enough and the menu order is *different* enough. 

Mayor is now fixed
