### ISSUE TITLE
K & K Parks: update quick menu

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#728]
Need to update the menu and confirm both sites are up to date with releases.
https://kettering-oh.proudcity.com/ and 
https://kettering-oh-parks.proudcity.com/

![screenshot 2016-12-12 10 31 31](https://cloud.githubusercontent.com/assets/6032426/21104908/46241108-c056-11e6-8362-c57c9ac5863d.png)

**Comment by jlyon** [comment]
Fixed @kevindherman
