### ISSUE TITLE
WC: newsletter

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#73]
- [x] Settings pg
- [x] Widget that is in footer

**Comment by jlyon** [comment]
add /subscribe

**Comment by jlyon** [comment]
@kevindherman added this: https://west-carrollton-oh.proudcity.com/subscribe/

**Comment by kevindherman** [comment]
Sweet, I'll pass along to WC.

On Mon, Feb 8, 2016 at 7:33 PM, Jeff Lyon <notifications@github.com> wrote:

> @kevindherman <https://github.com/kevindherman> added this:
> https://west-carrollton-oh.proudcity.com/subscribe/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/73#issuecomment-181640659>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
