### ISSUE TITLE
SR: local services

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#731]
From RW:

Yeah, I guess so. I'm not sure which ones we have and which ones we don't. For meters, can we say 'Active' when open and 'Free' when closed?

Also, I typed in an address and got the following message for trash:
![unnamed 1](https://cloud.githubusercontent.com/assets/6032426/21152761/b6903bc6-c135-11e6-9aab-6c37276f65a8.jpg)

**Comment by jlyon** [comment]
@kevindherman I believe this has already been taken care of (I responded directly via email).

**Comment by kevindherman** [comment]
@jlyon yup
