### ISSUE TITLE
SR: document download error

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#732]
There isn't a preview on this document, but I think that's because it's a large file:

https://www.cityofsanrafael.org/documents/general-plan-2020/

The main concern is that if you click download you get this error:

![screenshot 2016-12-13 15 24 47](https://cloud.githubusercontent.com/assets/6032426/21157794/b7bddbb2-c148-11e6-9db8-5e8187ad40f4.png)

@jlyon I'm assuming this is from the new infrastructure work because the error URL mentions google storage: https://storage.googleapis.com/proudcity/sanrafaelca/uploads/2016/11/general-plan-2020-complete.pdf

**Comment by kevindherman** [comment]
From ZenDesk:

Most of the documents on the general plan page (https://www.cityofsanrafael.org/general-plan/) are having the same issue, General Plan, Sustainability, land use, transportation, open space…housing, spacing and noise DO work. That’s all that I have had a chance to test today.

**Comment by jlyon** [comment]
@kevindherman I believe this is fixed now, correct? Moving to ready.

**Comment by kevindherman** [comment]
@jlyon yup, fixed.
