### ISSUE TITLE
SR: icons not showing

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#733]
Not all the icons are showing on SR:

![screenshot 2016-12-14 09 04 47](https://cloud.githubusercontent.com/assets/6032426/21184907/83221c26-c1dc-11e6-8d18-ebc09f681301.png)

**Comment by kevindherman** [comment]
@aschmoe @jlyon this is not an issue when logged in, only as anon user.

**Comment by jlyon** [comment]
@kevindherman @aschmoe I added a forced redirect when you try to access the site via http. This should now be fixed.
