### ISSUE TITLE
Lucas: new user

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#734]
Hello,

Can you please setup an account for Bill Baxter? He is the IT Support representative for the City and they do website updates occasionally. His email is: wbaxter@baxterit.com

Thank you,

Tim

**Comment by kevindherman** [comment]
@jlyon and these two:

Alicia Gipson agipson@lucastexas.us
Cathey Bonczar cbonczar@lucastexas.us

**Comment by jlyon** [comment]
Created these three accounts.
