### ISSUE TITLE
Add ability to select specific agencies in agency list widget

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#736]
Add check boxes to the agency list widget that allow you to select the agencies to be shown so it's not all or nothing. 

This will be helpful for Kettering PRCA in mid January.

**Comment by jlyon** [comment]
@kevindherman we added the "Hide on department lists" checkbox to the agency edit page for SR.  This seems like a better long-term solution though. Can we switch over the SR listings once this gets pushed (I'm working on it for this release)?

**Comment by jlyon** [comment]
Actually I think this will be a little more complex so it won't get into the release. I think the comment above still applies, though.

**Comment by kevindherman** [comment]
@jlyon I wasn't expecting this in this release. It's a little different than the hide from department list feature.

The dept list widget has a card view that displays the featured image which is what I want to replicate but with the ability to select specific departments.

**Comment by jlyon** [comment]
@kevindherman I think that's the same widget that displays on https://www.cityofsanrafael.org/departments/. Once this gets pushed it seems like we could get rid of the hide button, and just manage the agencies we want to show in the widget settings, right?

**Comment by kevindherman** [comment]
I think the main /departments list should still be the default but if you add an agency list widget to another page you can select via check boxes (rather than a number) which ones show.

**Comment by kevindherman** [comment]
@aschmoe @jlyon  if a department selects "do not list" so that they don't show up on the /governments page they are also excluded from the agency list widget selector. 

Can the selector allow for all departments or does the do not list feature need to be rethought with the new widget?

**Comment by aschmoe** [comment]
@kevindherman quick clarification: they show up in the backend widget options, but not in the resulting list, correct?

I believe the plan was basically to communicate to clients that the new feature exists, get them using that (un-checking do not show, using the new widget options where appropriate), then we can phase out the old setting.

This could be done by email or similar or direct communication.
