### ISSUE TITLE
WC: List jobs

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#74]

**Comment by aschmoe** [comment]
This work is done: https://west-carrollton-oh.proudcity.com/jobs/

**Comment by aschmoe** [comment]
@jlyon would be wise to hide the default jobs widgets now.

**Comment by jlyon** [comment]
@aschmoe looks good.

Hid the 2 job manager widgets: https://github.com/proudcity/wp-proud-core/commit/17141a2936e5fdfe57a84d4e9ec6a18a866ce70b
