### ISSUE TITLE
K & K Parks: cross site search GA question

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#742]
If Kettering opt's into elasticsearch so that the two sites can search each other, how are answers events recorded in google analytics?

So if someone is searching on Parks and clicks on a result that is an answer on the main site, is that event triggered in GA on the main site or the parks site?

**Comment by aschmoe** [comment]
@kevindherman the event search click would be logged in the main site, then you are taken to the subsite which will log a page view.
