### ISSUE TITLE
SR: facebook service center question

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#744]
I got this question and I feel like @jlyon and @aschmoe were discussing this yesterday. Was this part of the release?

Hey Kevin - the 'Use App' button on our Facebook account takes you to this page: https://san-rafael-ca.proudcity.com/fbtab/#/city/answers - should we redirect to the new URL?

**Comment by jlyon** [comment]
@kevindherman this was updated awhile ago. This button now points to the FB app: https://www.facebook.com/CityofSanRafael/app/1358980630789577/
