### ISSUE TITLE
SR: Getting Library Events block

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#745]
Need to display block with library events

**Comment by jlyon** [comment]
code to add
```
<h3 class=”margin-top-none”>Upcoming Library Events</h3>
<script class="ai1ec-widget-placeholder" data-widget="ai1ec_agenda_widget" data-events_seek_type="events" data-events_per_page="5" data-days_per_page="5" data-show_subscribe_buttons="false">
  (function(){var d=document,s=d.createElement('script'),
  i='ai1ec-script';if(d.getElementById(i))return;s.async=1;
  s.id=i;s.src='//srpubliclibrary.org/?ai1ec_js_widget';
  d.getElementsByTagName('head')[0].appendChild(s);})();
</script>
<a class=”btn btn-primary btn-sm” target=”_blank” href=”https://srpubliclibrary.org”></a>
```

JS error I was getting that prevented loading:
```
Refused to execute script from 'https://srpubliclibrary.org/?ai1ec_js_widget=ai1ec_agenda_widget&render=tru…request_type=jsonp&ai1ec=&ai1ec_source=ai1ec_agenda_widget&_=1481928936290' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.
```

**Comment by jlyon** [comment]
Added to https://beta.proudcity.com/events/ for further testing @aschmoe, just in case it's https related.

**Comment by jlyon** [comment]
Looks like it's a problem with their server config, or that plugin. The content type header should be application/javascript, but it's application/json.

If fixing it on their server will be a huge pain, we can proxy it, either in the js api, or in wp.

**Comment by aschmoe** [comment]
Messed around with this for a bit: think maybe our server config doesn't allow jsonp to be executed.

In the end I just made a widget to query directly the sflibrary site.

**Comment by jlyon** [comment]
I thought it was their server config (wrong headers), not ours, but I might be wrong @aschmoe

**Comment by aschmoe** [comment]
@jlyon yeah, possibly, worked fine for me locally though... perhaps HTTPS throws extra complications onto the fire
