### ISSUE TITLE
De Leon: 502 server error after submitting form

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#749]
Receiving 502 server error after submitting form:
http://www.cityofdeleon.org/documents/utility-service-vacation-onoff-request/

![screenshot 2016-12-16 10 18 08](https://cloud.githubusercontent.com/assets/6032426/21267624/1f1dcdee-c379-11e6-9805-2ecec69eb42c.png)

**Comment by jlyon** [comment]
@kevindherman This has been fixed and pushed platform wide as hotfix 1.21.3

**Comment by kevindherman** [comment]
@jlyon thank you.
