### ISSUE TITLE
De Leon: external link department not saving

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#755]
When updating the external link to https://www.facebook.com/profile.php?id=100011389654239&fref=ts the page won't save. 
Step 1 and update:
![screenshot 2016-12-19 09 47 20](https://cloud.githubusercontent.com/assets/6032426/21316783/4d389cd2-c5d0-11e6-8037-dc3321f69875.png)

Doesn't save: 
![screenshot 2016-12-19 09 47 34](https://cloud.githubusercontent.com/assets/6032426/21316784/4d3d1672-c5d0-11e6-8b47-49adb3c202a7.png)

Show's as a single page:
![screenshot 2016-12-19 09 47 41](https://cloud.githubusercontent.com/assets/6032426/21316785/4d3d27ca-c5d0-11e6-9c9a-7385781c9a85.png)

https://www.cityofdeleon.org/departments/de-leon-volunteer-fire-department/

**Comment by aschmoe** [comment]
@kevindherman this is fixed for Deleon (and everywhere else).

**Comment by kevindherman** [comment]
@aschmoe  thank you.

**Comment by jlyon** [comment]
Moving to ready.

**Comment by kevindherman** [comment]
@jlyon this is fixed.
