### ISSUE TITLE
SR: search box formatting

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#756]
ZenDesk:

Chrome & not logged in. It did happen intermittently so maybe not an issue. Version shows as Version 54.0.2840.99 m  which means very little to me. It did appear to just update to a newer version when I went to the version section so maybe that was the issue - t seems odd that our site wouldn’t update Chrome automatically upon turning on the computer. Anyways, it looks fine on my computer now.

![image001 1](https://cloud.githubusercontent.com/assets/6032426/21316976/20d84330-c5d1-11e6-9284-a39cd71e95bc.png)
![image002](https://cloud.githubusercontent.com/assets/6032426/21316975/20d7e6ba-c5d1-11e6-99e3-5f3921cba1d5.png)

**Comment by aschmoe** [comment]
Moving to blocked unless we get more information

**Comment by jlyon** [comment]
Can we change this to wontfix @kevindherman  @aschmoe

**Comment by kevindherman** [comment]
@jlyon fine with me.

**Comment by aschmoe** [comment]
@jlyon no complaints here
