### ISSUE TITLE
De Leon: redirect https://de-leon-tx.proudcity.com/

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#758]
Redirect to https://de-leon-tx.proudcity.com/  https://www.cityofdeleon.org/

Could the .proudcity.com be it's own instance right now since it has the test bar and the official domain does not?
![screenshot 2016-12-19 12 11 45](https://cloud.githubusercontent.com/assets/6032426/21321820/6918544c-c5e4-11e6-8888-392ee979ff04.png)
 
https://www.dropbox.com/s/7mkwkh3hggb4nl2/Screenshot%202016-12-19%2012.11.45.png?dl=0

**Comment by jlyon** [comment]
@kevindherman Currently https://de-leon-tx.proudcity.com/  redirects to https://www.cityofdeleon.org/.  Should I get rid of this redirect?

**Comment by kevindherman** [comment]
@jlyon no that's perfect. Previously the test site domain wasn't redirecting and it appeared as what I thought was a separate instance.
