### ISSUE TITLE
SR: scrape to remove West Carrollton

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#759]
Noticed West Carrollton came up in SR search. Can we scrape their site to make sure these random pages from the clone are removed?

![screenshot 2016-12-19 13 41 27](https://cloud.githubusercontent.com/assets/6032426/21324732/022d3ace-c5f1-11e6-927f-d030e17f8def.png)

https://www.cityofsanrafael.org/location/west-carrollton-library/

![screenshot 2016-12-19 13 42 49](https://cloud.githubusercontent.com/assets/6032426/21324743/0d79d8f6-c5f1-11e6-9b30-169fb649a1c6.png)

**Comment by aschmoe** [comment]
@kevindherman easiest way to find these is to just use that search and track them down.

**Comment by kevindherman** [comment]
@aschmoe I found a bunch of them in locations and contacts:

https://www.cityofsanrafael.org/wp-admin/edit.php?post_type=location&ids=2558

![screenshot 2016-12-19 16 54 11](https://cloud.githubusercontent.com/assets/6032426/21330504/cb9d8af2-c60b-11e6-965b-549ea1da17f1.png)

I'm guessing a bunch of those addresses West Carrollton auto populated in the town field and are actually in San Rafael. I'll flag for SR so I don't delete something that shouldn't be.

**Comment by kevindherman** [comment]
Still getting two instances. I'm not sure how to delete them because when I click on the result it says page not found.

**Comment by jlyon** [comment]
@kevindherman @aschmoe It looks like this was sorted out, right (I'm not seeing and WC addresses on https://www.cityofsanrafael.org/wp-admin/edit.php?post_type=location&ids=2558)?

**Comment by kevindherman** [comment]
@jlyon there are still showing up in search but aren't listed in locations so I'm not sure where they are coming from:

![screenshot 2016-12-23 11 40 54](https://cloud.githubusercontent.com/assets/6032426/21458488/bf66dc4c-c904-11e6-832a-6c354a648b75.png)

**Comment by jlyon** [comment]
@aschmoe could this be a elasticserach index thing, or should i try to scan a db dump?

**Comment by aschmoe** [comment]
I deleted them, and they are gone.  @kevindherman 

Moving to trash doesn't seem to update it to unpublished in the meta values, so I will need to look into that.

**Comment by jlyon** [comment]
Posted a note in https://proudcity.zendesk.com/agent/tickets/253 and marked as solved @kevindherman

**Comment by kevindherman** [comment]
@jlyon got it. Thanks.
