### ISSUE TITLE
Emergency or priority alert banner

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#76]
- [x] Settings
- [x] Text
- [x] Rich text exitor

**Comment by jlyon** [comment]
Make it its own field with text+link

**Comment by jlyon** [comment]
Added this to WC: https://west-carrollton-oh.proudcity.com/wp-admin/admin.php?page=alertbar @kevindherman

**Comment by kevindherman** [comment]
@jlyon Got the attached screenshot when publishing a test alert. Can you update the permissions?

![screenshot 2016-02-03 09 25 58](https://cloud.githubusercontent.com/assets/6032426/12784987/363cfb46-ca58-11e5-96ac-c15593742d09.png)

**Comment by jlyon** [comment]
@kevindherman fixed these permissions

**Comment by kevindherman** [comment]
Dope. Will pass along to the client.

On Thu, Feb 4, 2016 at 5:26 PM, Jeff Lyon <notifications@github.com> wrote:

> @kevindherman <https://github.com/kevindherman> fixed these permissions
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/76#issuecomment-180078687>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
