### ISSUE TITLE
Kube: scripts for certain plugins

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#762]
@jylon would be nice to have a system (that maybe already exists) to run deploy scripts on plugin update. 

```
wp-proud-elastic-search #1.22.0
wp elasticpress put-mapping
wp elasticpress index
```
or similar

**Comment by jlyon** [comment]
@aschmoe Yes, `bin/kube-cmd.sh` in proudcity-kubernetes:
```
bash kube-cmd.sh $NAMESPACE $APP "wp option get blogname"
```

`kube-cmd-all.sh` runs the command on all apps in the namespace
