### ISSUE TITLE
SR: add an event notification

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#763]
How do you setup email notifications for the "add an event" form on /events? I know an alert bubble pops up in the dashboard but is there an email alert as well?

**Comment by jlyon** [comment]
@kevindherman there are currently no events set up. Is this something they requested?  We could look into adding it, but these alerts get to be kind of a pain to test and keep up.

**Comment by kevindherman** [comment]
@jlyon we can table this one.

**Comment by jlyon** [comment]
Changing to wontfix.  This will be fixed when we set this up as a webform
