### ISSUE TITLE
Form email notifications

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#764]
Zendesk:

We don't seem to be getting the email notifications when an online form is submitted. I asked IT to make sure the sender email is not blocked by out spam filter. They claim they have done this and we are still not getting the notifications. Not sure if this is on your end or ours. I'll do some more testing on our side (I'll add a non-city email to the form and see if that helps).

**Comment by kevindherman** [comment]
followup post to zendesk:

FYI, we just did two tests with the 'Report an Abandoned Vehicle' and the 'Citizen of the Year Nomination Form' by putting non-city emails in the notification field and we did not received the notifications.

**Comment by jlyon** [comment]
@kevindherman this should be fixed. I posted a reply in Zendesk.
