### ISSUE TITLE
Payments tab appearing when it should not

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#766]
@aschmoe can you look at this one?  Payments is unchecked on https://www.lucastexas.us/wp-admin/admin.php?page=service-center-settings.

Thx,
J

---

Hello,

The payment info is all of a sudden showing on the "answers" page.

https://www.lucastexas.us/#/city/answers

They do not use payment so it is data from another city in there. Please remove the payments tab.

Thank you,

Tim

**Comment by aschmoe** [comment]
@jlyon looks like this commit undid that work https://github.com/proudcity/wp-proud-actions-app/commit/dea477722509358987eab551b17925cbe1496635#diff-489784dd7f19bb14a8bd6d5ebef7aee1L402

I'm fixing it back then updating

**Comment by jlyon** [comment]
Moving to ready
