### ISSUE TITLE
Service center: exernal linked issues, reports are missing icons

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#770]
Additionally clicking on the other tabs makes a 1 or 0 flash briefly

**Comment by aschmoe** [comment]
![west carrollton](https://cloud.githubusercontent.com/assets/1634686/21663775/21e8c5d8-d297-11e6-9679-2f68a1b01b8b.jpg)

Westcarrollton

**Comment by jlyon** [comment]
Fixed this.
