### ISSUE TITLE
PO: signature box placement on webform

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#773]
From ZenDesk:

I made a change in the online Utilities Request form by adding one word to the 'Owner/Agent' line. When it was saved, I viewed the form and it looked good. Once I logged out and notified Utility Billing of the change, they noticed that the Signature Box was all the way at the top of the form, covering the first line. The signature box was not moved, or touched when I made the change. The link is: https://www.cityofportorchard.us/documents/utilities-request-form/ We need the signature box put in the correct spot on the bottom of the form but I am unable to do so. Attached is what the form looks like, and the second page is what my view is through the dashboard.

[Doc4.pdf](https://github.com/proudcity/wp-proudcity/files/696863/Doc4.pdf)

It working fine in Chrome but broken on explorer, FF and mobile.

**Comment by jlyon** [comment]
Hmm, I'm not able to replicate this in:
- old android
- Firefox 43
- IE 10
- iOS

![firefox-43](https://cloud.githubusercontent.com/assets/550909/22086410/70cd489e-dd8d-11e6-8e09-18abe3281726.png)
![ie10](https://cloud.githubusercontent.com/assets/550909/22086411/70e3efea-dd8d-11e6-9a0f-436278d70cbb.png)
![old-android](https://cloud.githubusercontent.com/assets/550909/22086412/70ea2752-dd8d-11e6-965d-cfb7edcc761c.png)
![ios](https://cloud.githubusercontent.com/assets/550909/22086413/70eaec28-dd8d-11e6-9ed6-19d8ba32948b.png)

**Comment by kevindherman** [comment]
@jlyon I'll check in with them.
