### ISSUE TITLE
Elasticsearch was publicly accessible

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#779]
Need to come up with a strategy for authorizing certain indexing from external sources

**Comment by aschmoe** [comment]
Seems like best option:
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin

The offical (needs kibana):
https://www.elastic.co/downloads/x-pack

From
http://stackoverflow.com/questions/9956062/authentication-in-elasticsearch

**Comment by aschmoe** [comment]
maybe better than ^^

https://github.com/floragunncom/search-guard

Possibly easiest just ngnix
http://www.minvolai.com/blog/2014/08/Setting-up-a-Secure-Single-Node-Elasticsearch-server-behind-Nginx/Setting-up-a-Secure-Single-Node-Elasticsearch-server-behind-Nginx/

**Comment by jlyon** [comment]
I moved this to ready @aschmoe .
