### ISSUE TITLE
HTTP added to url when dialing phone number from mobile

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#780]
ZenDesk:

I was using the new website to get a city phone number and when I tried to dial from the website, it brings up the number with an http:// in front. Here is the screenshot from my phone.

![image2](https://cloud.githubusercontent.com/assets/6032426/21888633/19181b6e-d893-11e6-8b3e-6106a6de28a6.PNG)
![image1](https://cloud.githubusercontent.com/assets/6032426/21888632/1917211e-d893-11e6-809e-5fb9c8a6833e.PNG)

**Comment by jlyon** [comment]
Fixed this @kevindherman
