### ISSUE TITLE
Service Center Local: Move local services icons above map

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#782]
Rebecca got some user feedback about the "more services" options being hidden. 

![screenshot 2017-01-13 14 54 31](https://cloud.githubusercontent.com/assets/6032426/22027910/60e7fa9a-dca3-11e6-9de1-e3ac3256c463.png)

@jlyon @aschmoe do you think just moving them above the map would help with that?

**Comment by jlyon** [comment]
Hmm.  I moved it to above the map. Let's see if that improves things.  It might be that we need to include the label text with the buttons.
