### ISSUE TITLE
K: constant contact

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#783]
Kettering uses Constant Contact and prefers to stay with it. Do we see this as an integration opportunity or how should we handle this?

**Comment by jlyon** [comment]
Yah, there's a gravityforms plugin https://wordpress.org/plugins/gravity-forms-constant-contact/. I'll add it in the next release. We'll probably need a temp u/p or an api key (don't share in Github) from them to configure it.

**Comment by kevindherman** [comment]
@jlyon great. I'll switch the label from question to enhancement.

**Comment by jlyon** [comment]
- [ ] Move K to Kube
- [ ] Add to plugins env var
- [ ] Enable plugin

**Comment by kevindherman** [comment]
@jlyon this will also be for K Parks.

**Comment by kevindherman** [comment]
@jlyon where does this stand?

**Comment by kevindherman** [comment]
@jlyon @aschmoe where should I move this to make sure it's part of the release this week?

**Comment by jlyon** [comment]
I will set this up this afternoon @kevindherman

**Comment by kevindherman** [comment]
@jlyon thank you.

**Comment by jlyon** [comment]
@kevindherman all set w plugin. Need u/p to finish setting up (and also maybe info about which list the contacts should go into for each, I can't remember how Constant Contact is set up).

**Comment by kevindherman** [comment]
@jlyon sent you the u/p.

**Comment by kevindherman** [comment]
@jlyon sent you the u/p.

The name of the constant contact list to integrate with the subscribe form is "The Starter".

**Comment by jlyon** [comment]
Need to add permission `gravityforms_constantcontact`.  This will be done in the next release @kevindherman
