### ISSUE TITLE
C: FAQ child topic showing as parent

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#784]
The FAQ child topic for "paying a bill" is showing as a parent after creating a new answer.

Topic: https://colma-ca.proudcity.com/wp-admin/edit-tags.php?taxonomy=faq-topic&post_type=question
![screenshot 2017-01-17 17 01 18](https://cloud.githubusercontent.com/assets/6032426/22041948/edbcb180-dcd6-11e6-8e50-7d6d591d8e46.png)

New answer: https://colma-ca.proudcity.com/wp-admin/post.php?post=3385&action=edit
![screenshot 2017-01-17 17 02 58](https://cloud.githubusercontent.com/assets/6032426/22041944/e95cf564-dcd6-11e6-8442-c041e467daf6.png)

**Comment by kevindherman** [comment]
@jlyon this is a blocker for their current sprint so it's important to get into the release.

**Comment by jlyon** [comment]
@kevindherman This is actually just how WordPress works.  Once you check a topic, it will pull that topic to the top of the topics list, regardless of whether or not it is a parent or child.  

If you create a new Answer, Pay a Bill shows up as a child of Payments:
