### ISSUE TITLE
Add breadcrumbs above secondary menu

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#785]
Add breadcrumb above submenu to give context within the IA when on second or third or deeper menu items:

![screenshot 2017-01-18 12 28 13](https://cloud.githubusercontent.com/assets/6032426/22075378/ce044512-dd79-11e6-8c24-5f3a7588669b.png)

**Comment by aschmoe** [comment]
@jlyon @kevindherman quick weigh-in


1 
![parking permits for movers - san rafael](https://cloud.githubusercontent.com/assets/1634686/24012699/29ca6f86-0a3c-11e7-9311-b958517cadc9.jpg)


2 
![parking permits for movers - san rafael 1](https://cloud.githubusercontent.com/assets/1634686/24012704/2f9c28d2-0a3c-11e7-9bab-842e862d6dd0.jpg)

3 
![parking permits for movers - san rafael 2](https://cloud.githubusercontent.com/assets/1634686/24012708/341c05d0-0a3c-11e7-98ec-8971374187d6.jpg)

**Comment by jlyon** [comment]
My vote is for the version without the gray bar (and maybe a little less padding between the crumbs and the menu

**Comment by kevindherman** [comment]
@aschmoe could you post a mobile view? I'm curious to see if the non gray version is confusing in a smaller space. If it doesn't change anything I agree with @jlyon  on the non gray option.
