### ISSUE TITLE
K & K Parks: add issues content types

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#786]
@kevindherman enabled and configured the homepage actions box to use it.

**Comment by kevindherman** [comment]
@jlyon cleared my cash, reset browsed and used an incognito window and I'm not getting the issues content type in the dashboard:

![screenshot 2017-01-19 10 51 24](https://cloud.githubusercontent.com/assets/6032426/22113781/7588dad0-de35-11e6-9d15-664e7338124a.png)

**Comment by kevindherman** [comment]
@jlyon can you also add this to Danvers?

**Comment by jlyon** [comment]
@kevindherman sorry, Issues got added to kettering-oh-parks but not kettering-oh (which it looks like your screenshot is from). Issues+Locations should be enabled on kettering-oh-parks, kettering-oh, danvers-ma now.

**Comment by kevindherman** [comment]
@jlyon all good on both Kettering sites but not Danvers.
