### ISSUE TITLE
Re-add ProudScore Widget (Heart) to Actions footer

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#788]
- [x] SR
- [x] example

**Comment by jlyon** [comment]
@kevindherman Do you remember, did SR intentionally remove the Heart widget in the Actions bar above the footer on their site?

**Comment by kevindherman** [comment]
@jlyon I don't remember but I'm comfortable with this customer to move forward with what we think is best.

**Comment by jlyon** [comment]
K this has been re-added.  @aschmoe do you think we should revisit the formatting for this?

**Comment by aschmoe** [comment]
You talking colors?

**Comment by aschmoe** [comment]
@jlyon
