### ISSUE TITLE
Change "agencies" to "departments" throughout

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#793]
It would be great to change all references in the backend and widgets to consistently be departments or dept if space sensitive rather than "agency". We use both on the platform and departments is more commonly used  in trainings/conversations.

**Comment by jlyon** [comment]
Fixed all of the widgets in this release.  @kevindherman have you noticed anywhere else that Agency is appearing?


code for release
```
echo "INSERT INTO wp_say_what_strings (orig_string, domain, replacement_string, context) VALUES ('Agency contact info','wp-agency','Department contact info',''),('Agency hours','wp-agency','Department hours',''),('Agency menu','wp-agency','Department menu',''),('Agency social media','wp-agency','Department social media','');" | dwp db cli
```

**Comment by kevindherman** [comment]
@jlyon  I think just these two additional places, I'll keep my eyes peeled for more.

- search "agency" from dept dashboard:
![screenshot 2017-02-01 11 26 33](https://cloud.githubusercontent.com/assets/6032426/22515714/6c73b12c-e871-11e6-91d1-15d9d9efa1c7.png)

- view agency when editing a dept page:
![screenshot 2017-02-01 11 28 12](https://cloud.githubusercontent.com/assets/6032426/22515762/9b7e8a00-e871-11e6-87cd-463fa86ca577.png)

**Comment by jlyon** [comment]
Great, fixed this.  Updated code
```
echo "INSERT INTO wp_say_what_strings (orig_string, domain, replacement_string, context) VALUES ('Agency contact info','wp-agency','Department contact info',''),('Agency hours','wp-agency','Department hours',''),('Agency menu','wp-agency','Department menu',''),('Agency social media','wp-agency','Department social media',''),('View Agency','wp-agency','View Department',''),('Search agency','wp-agency','Search departments','');" | dwp db cli
```
