### ISSUE TITLE
Add title field to agency contact widget

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#794]
Add title filed on agency contact widget so that titles can be displayed on their own row under name instead of how he's trying to do it here:

https://www.lucastexas.us/departments/public-works-engineering/
![screenshot 2017-01-19 10 58 02](https://cloud.githubusercontent.com/assets/6032426/22114141/69e81712-de36-11e6-83f8-e9dd85ad8f28.png)

**Comment by jlyon** [comment]
@kevindherman added this. It will appear like this (this is with a name link entry)
