### ISSUE TITLE
Danvers: add location content type for maps

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#796]
The locations content type for filling in map locations and layers is missing on Danvers.

This was the case with Kettering (which was fixed in the release), should it be added as a default same with issues content #786 ?

**Comment by jlyon** [comment]
@kevindherman enabled Locations and Issues on Danvers, but didn't do any of the configuration.  I updated the example site and these will be enabled and configured for all new sites moving forward (#775).

**Comment by kevindherman** [comment]
@jlyon I'm not seeing locations and issues content types on Danvers. Was this pushed?

**Comment by jlyon** [comment]
@kevindherman I'm seeing them. Are you still not seeing them?
