### ISSUE TITLE
SR: social wall formatting on dept pages

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#800]
Make the social wall 3 columns wide rather than 2 on narrower dept pages: 

https://www.cityofsanrafael.org/departments/fire/
![screenshot 2017-01-23 13 27 00](https://cloud.githubusercontent.com/assets/6032426/22217082/a3244ece-e16f-11e6-97f6-67845a320d06.png)

**Comment by jlyon** [comment]
They might want to use of of the other widget displays:
![edit department san rafael wordpress](https://cloud.githubusercontent.com/assets/550909/22227223/1ec9a326-e17f-11e6-9c6a-e0f6f1863275.jpg)

Although, the feed currently doesn't look great:
![feed-example](https://cloud.githubusercontent.com/assets/550909/22227217/1b2a9bc6-e17f-11e6-9867-606c2d595673.png)

**Comment by kevindherman** [comment]
@jlyon @aschmoe I mentioned it but I think you're right that it still doesn't look great. It's not a high priority item but if social wall work is being done, it should be considered.
