### ISSUE TITLE
SR: error when logging in from my.proudcity.com

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#802]
One of the SR users who's one of the stronger members of their team has been reporting site speed and an error message when logging in. We were able to solve the error because she had a login url bookmarked that wasn't my.proudcity.com however, she reveived this error yesterday from the correct login page:

![image001](https://cloud.githubusercontent.com/assets/6032426/22247890/150cdc0a-e20a-11e6-9e2c-19587eba25b4.jpg)

I'm not sure what do at this point since it seems isolated. @jlyon any suggestions or info I could use in a zendesk response?

**Comment by kevindherman** [comment]
@jlyon I checked in this morning and things seem to be back to normal following yesterday's infrastructure work.

**Comment by jlyon** [comment]
@kevindherman Great, moving to Ready.
