### ISSUE TITLE
SR: search is down

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#803]
Search on SR is down:

https://www.cityofsanrafael.org/search-site/?term=mayor#/city/answers
![screenshot 2017-01-25 11 45 30](https://cloud.githubusercontent.com/assets/6032426/22299947/e3868510-e2f3-11e6-9a1e-3d254ba19b23.png)

![screenshot 2017-01-25 11 44 49](https://cloud.githubusercontent.com/assets/6032426/22299946/e381ac5c-e2f3-11e6-9b46-f3f1ade49816.png)

**Comment by aschmoe** [comment]
@kevindherman @jlyon  we had some outage issues yesterday, and guess this was one result, fixed now

**Comment by aschmoe** [comment]
Created #804 to track future solution

**Comment by kevindherman** [comment]
@aschmoe thanks for the quick fix.
