### ISSUE TITLE
Make Elasticsearch resilient to restart

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#804]
The container holds all the elasticsearch data so on restart, everything is dropped.

2 approaches:

- Persistent docker volume
- Run wp elasticpress put-mapping, wp elasticpress index on containers on some trigger

**Comment by jlyon** [comment]
https://kubernetes.io/docs/user-guide/volumes/#gcepersistentdisk

tutorial (for mysql): https://cloud.google.com/container-engine/docs/tutorials/persistent-disk/
