### ISSUE TITLE
K: random instagram on wall

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#806]
The social wall on Kettering is pulling a random @ketteringcollege account:

kettering-oh.proudcity.com
![screenshot 2017-01-25 14 49 22](https://cloud.githubusercontent.com/assets/6032426/22306596/c510a7e0-e30d-11e6-8197-ad859ca72c84.png)

**Comment by aschmoe** [comment]
@kevindherman removed
