### ISSUE TITLE
Danvers: /contact page edits

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#807]
- [ ] remove people column on department contact page like https://www.cityofsanrafael.org/contact-departments/
- [ ] remove social column on all /contact tables (dept, staff and electeds)

**Comment by jlyon** [comment]
#1 is currently broken by some of the Agency list work that @aschmoe was doing. 

In general you, can set these up yourself, we just have to make sure that we're using the specific content list (Department list, Contact list, etc), and not the generic "Content list".  I added

**Comment by jlyon** [comment]
Nvm, this wasn't broken, I was just adding the wrong widget. After replacing Content list with Agency list on https://danvers-ma.proudcity.com/contact/, I was able to hide the Person and Social columns.

This should be all set @kevindherman

**Comment by kevindherman** [comment]
The number of contacts listed was changed the 3, updated to 50.

Everything else looks good.

Can close.
