### ISSUE TITLE
Danvers: San Rafael circle and excerpt /government layout

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#808]
Is it possible to use the circle featured image and department excerpt style from San Rafael on Danvers?

https://www.cityofsanrafael.org/departments/

![screenshot 2017-01-26 15 06 32](https://cloud.githubusercontent.com/assets/6032426/22348266/10ff868c-e3d9-11e6-8178-ccb3397de4bf.png)

**Comment by aschmoe** [comment]
@kevindherman yup, use the media list view option
