### ISSUE TITLE
K & K Parks: report an issue link on service center broken

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#809]
The report an issue tab on service center doesn't link anywhere. I keep selecting it and nothing happens.

![screenshot 2017-01-26 15 20 24](https://cloud.githubusercontent.com/assets/6032426/22348851/40f16ed0-e3db-11e6-82f9-a26d87d51f6c.png)

I checked the settings on the homepage widget, standalone and that there is content and all checked out.

**Comment by jlyon** [comment]
@kevindherman I needed to select Custom categories at the bottom of https://kettering-oh.proudcity.com/wp-admin/admin.php?page=service-center-settings.  

Did this for K and K Parks.  New sites will come with custom categories for issues already configured and custom locations too.

**Comment by jlyon** [comment]
Actually I only did this for K. K Parks was already set up, but they dont have any issue categories.  Are they just trying to pull the service center from the city site?

**Comment by kevindherman** [comment]
@jlyon thanks.

K Parks is setting up their own service center, just haven't gotten to issues yet. The way they've set up the answers is a little different than most use cases, worth taking a look.
