### ISSUE TITLE
Add Custom text area option to Issues post type

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#811]
Currently there are options for form, iframe or link out. However, sometimes there is a need for a text only area for situations where providing a phone number is the only or preferred option such as a water main break. This type of issue could technically live under answers but from an IA/user perspective I think it makes sense under report an issue. 

Could a text only option be added? For the text only option, the "Please provide __________ detail" formatting is not necessary.

It was also suggested to add a text area above the link out option to help provide context or direction before being sent off the site.

**Comment by jlyon** [comment]
@kevindherman  I added a Custom option to issues. I'm going to leave the link functionality the way it is. If they want to add text before the person is linked out, they can use the Custom type and include the text and link in the Editor.
