### ISSUE TITLE
Issue with /application-payment getting redirected

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#820]
This is getting redirected to the service-center's /app callback.

**Comment by jlyon** [comment]
I fixed this by changing the mobile app path from /app to /mobile-app so there shouldn't be any similar conflicts @kevindherman .

**Comment by kevindherman** [comment]
@jlyon is this for the special link/application workflow?

**Comment by jlyon** [comment]
@kevindherman  this is re: the email Erika sent

**Comment by kevindherman** [comment]
@jlyon got it. thanks.
