### ISSUE TITLE
New Widget: contact info block

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#822]
Same as agency, but allow user input

**Comment by jlyon** [comment]
Maybe tackle #829 before this?

**Comment by aschmoe** [comment]
@jlyon roger

**Comment by kevindherman** [comment]
@aschmoe do you think this is a potential hotfix to play into our Kettering Parks strategy?

**Comment by jlyon** [comment]
@kevindherman added as Custom contact block.
![screenshot from 2017-02-03 14 48 34](https://cloud.githubusercontent.com/assets/550909/22611530/ed1975a0-ea1f-11e6-9c50-e0c7373b4505.png)

**Comment by jlyon** [comment]
@kevindherman  pushed in hotfix 1.24.3
