### ISSUE TITLE
New Widget: Image/link collection

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#823]
Much in the same fashion as the icon list, but with images, both in card format + media list format, see agencies

**Comment by jlyon** [comment]
@kevindherman  pushed in hotfix 1.24.3

**Comment by kevindherman** [comment]
@jlyon @aschmoe after I added the new image set widget to a department it stripped out the styling:
https://kettering-oh.proudcity.com/departments/office-city-manager/
![screenshot 2017-02-06 10 15 01](https://cloud.githubusercontent.com/assets/6032426/22652681/5a9a4294-ec55-11e6-9195-2d5dd1f782c3.png)

**Comment by aschmoe** [comment]
@kevindherman fixed this on kettering, deploying as hotfix elsewhere this AM
