### ISSUE TITLE
Omit service_center_tab post type from search results

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#833]
This post type was created in #825.

**Comment by aschmoe** [comment]
see https://github.com/proudcity/wp-proud-actions-app/blob/master/wp-proud-actions-app.php#L59

Is this the correct post type?

**Comment by aschmoe** [comment]
@jlyon ^^

**Comment by jlyon** [comment]
@aschmoe post type is `service_center_tab`: https://github.com/proudcity/wp-proud-actions-app/blob/master/wp-proud-actions-app.php#L119

**Comment by aschmoe** [comment]
@jlyon isn't that what that line says?

**Comment by jlyon** [comment]
Ahh, great
