### ISSUE TITLE
SR: conditional subscribe page feedback

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#834]
From ZenDesk:

> 
There have been some comments made that it's not intuitive on the subscribe page that checking a box will get you more options. I modified the language so that it's a little more clear, but is there anything else we can do, like add like + symbols next to the check boxes? https://www.cityofsanrafael.org/subscribe/

@jlyon @aschmoe  I played around with having the general updates being pre-selected but I think it's maybe less obvious that the other conditional fields open up options down the page. This lead me to believe that the language is probably the most helpful as she's already suggested. What do you guys think?

**Comment by aschmoe** [comment]
@kevindherman seems like an overwhelming amount of options to choose from, not sure of a solution beyond explicit language

**Comment by kevindherman** [comment]
@aschmoe yeah, I think you're right.

**Comment by jlyon** [comment]
Yah, I agree that some really obvious language is probably the only solution. @kevindherman @aschmoe
