### ISSUE TITLE
Platform-wide: department content displaying under left column

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#835]
Standard text area content is being shifted to the left column on department pages platform-wide.

https://www.cityofsanrafael.org/departments/city-attorney/

![screenshot 2017-02-02 11 41 20](https://cloud.githubusercontent.com/assets/6032426/22558724/bd5ffb56-e93c-11e6-9e03-2dd8229ceea7.png)

![screenshot 2017-02-02 11 43 23](https://cloud.githubusercontent.com/assets/6032426/22558746/d2028d08-e93c-11e6-9a4e-c4a71c707223.png)

**Comment by kevindherman** [comment]
@jlyon @aschmoe this appears to be isolated to department pages. Standard pages look good.

https://www.cityofsanrafael.org/digital-san-rafael/
![screenshot 2017-02-02 11 47 04](https://cloud.githubusercontent.com/assets/6032426/22558886/5afbf900-e93d-11e6-9834-8b518c18ba10.png)

**Comment by jlyon** [comment]
This has been deployed as hotfix 1.24.1 @kevindherman
