### ISSUE TITLE
Danvers: report an issue tab timing out

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#836]
After selecting "report an issue" on the service center from the Danvers homepage, the wheel just keep spinning.

![screenshot 2017-02-02 14 45 01](https://cloud.githubusercontent.com/assets/6032426/22565490/4ea2053c-e956-11e6-8872-ebb13d8d5e9c.png)

I made sure of the following:

1- issue content exists
2- report an issue checkbox selected on homepage service center settings
3- report an issue checkbox selected on standalone service center settings

**Comment by kevindherman** [comment]
found issue #809 and fixed this item.

**Comment by jlyon** [comment]
Moving to ready
