### ISSUE TITLE
K: file upload in job listings

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#838]
Add ability to attach multiple documents to a job listing. I think this could be accomplished by having a file load under the text area or just adding page builder so people can use the document widget.

They could use add media but that gets away from the best practices with documents that we're trying to steer customers away from.

**Comment by jlyon** [comment]
@kevindherman I enabled the page builder tab on K Jobs: https://kettering-oh.proudcity.com/wp-admin/post.php?post=5878&action=edit.  I think it might just be better to use the Add Media button in the editor in this specific case, but I'll defer to you if you've been making a hard rule to not use that.  Lmk if you want me to disable the Page Builder on K Jobs.

We're using a contrib plugin for the Jobs Listings, so I don't want to add additional fields to that post type for maintainability.
