### ISSUE TITLE
Fix url links in agency contact field

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#839]
From ZenDesk:

Hello,

The Contact Us links (under the department phone numbers) are not linking, and are awkwardly hanging out in the content of the page. I don't think this is normal.

It is on every page, but here is an example page: 
https://www.cityofsanrafael.org/building-permits/

Please see pictures attached.

Thank you!

![crm](https://cloud.githubusercontent.com/assets/6032426/22662396/d62efb5e-ec76-11e6-8b69-a0f9d9d197e1.JPG)

**Comment by kevindherman** [comment]
We got another ticket for this issue this morning.

**Comment by jlyon** [comment]
@kevindherman sorry, forgot about their http:// links with all of the agency contact updates last week.  This is fixed (it's a Contact us link).
