### ISSUE TITLE
WC: contact

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#84]
- [x] Agency table style list
- [x] Contact menu widget (staff taxonomies + Agency taxonomies)
- [x] https://trello.com/c/kITpzmH9/61-contacts-feedback
- [x] Make Departments pill active
- [x]  Add search box

**Comment by jlyon** [comment]
@aschmoe looks like some code got removed in https://github.com/proudcity/wp-proud-core/commit/9f4a9164bcbd5df8e8a127f12776d44180cdce85 that's messing up the headers on https://west-carrollton-oh.proudcity.com/people/?filter_categories%5B%5D=57.

```
-            case 'agency':
 -              echo sprintf( '<thead><tr><th>%s</th><th>%s</th><th>%s</th><th>%s</th><th>%s</th></tr></thead>',
 -                __( 'Agency', 'proud-agency' ),
 -                __( 'Person', 'proud-agency' ),
 -                __( 'Phone', 'proud-teaser' ),
 -                __( 'Email', 'proud-teaser' ),
 -                __( 'Social', 'proud-teaser' )
 -              );
 -              break;
              case 'staff-member':
 -              echo sprintf( '<thead><tr><th>%s</th><th>%s</th><th>%s</th><th>%s</th><th>%s</th><th>%s</th></tr></thead>',
 +              echo sprintf( '<thead><tr><th>%s</th><th>%s</th><th>%s</th></tr></thead>',
                  __( 'Name', 'proud-teaser' ),
                  __( 'Position', 'proud-teaser' ),
 -                __( 'Agency', 'proud-agency' ),
 -                __( 'Phone', 'proud-teaser' ),
 -                __( 'Email', 'proud-teaser' ),
 -                __( 'Social', 'proud-teaser' )
 +                __( 'Phone', 'proud-teaser' )
```

Also, it looks like something happened to the template for agency tables (https://west-carrollton-oh.proudcity.com/contact/).

**Comment by aschmoe** [comment]
Yeah things got a little confused, though I had re-added everything, but apparently not.  Should be good now.
