### ISSUE TITLE
Colma: needs "custom categories" option for issue provider

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#840]
https://colma-ca.proudcity.com/wp-admin/admin.php?page=service-center-settings
![screenshot 2017-02-07 15 32 29](https://cloud.githubusercontent.com/assets/6032426/22710303/cf75205c-ed4a-11e6-80d4-0d278303fe57.png)

Should have the custom categories option like Danvers:
https://danvers-ma.proudcity.com/wp-admin/admin.php?page=service-center-settings
![screenshot 2017-02-07 15 34 19](https://cloud.githubusercontent.com/assets/6032426/22710336/e98559d0-ed4a-11e6-83dc-46ce510acd48.png)

**Comment by jlyon** [comment]
@kevindherman enabled Issues and Locations on Colma, but didn't do any configuration.

**Comment by kevindherman** [comment]
@jlyon thank you.
