### ISSUE TITLE
Migrate proudcity.com

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#844]
- [ ] can we enable wp-stateless, put it in docker, or do we need a persistant volume
- [ ] can this just be an instance of wp-proudcity with WORDPRESS_PLUGINS sys var? (it would be nice to convert some weird stuff we're doing into our core distro, ie forms)

**Comment by aschmoe** [comment]
@jlyon care to elaborate on "it would be nice to convert some weird stuff we're doing into our core distro, ie forms"?

**Comment by jlyon** [comment]
@aschmoe It would be nice to use the same plugins that we're using on the platform on our site. In my ideal world, our site would use the proud theme and so pagebuilder, but it's probably not worth the effort to set that all up. But it would be nice to switch the form builder over to Gravityforms.

I think some of this is for our dashboard convo on Tue, depending on what/how we want to host /start, which uses a lot of Bootstrap stuff.
