### ISSUE TITLE
Migrate feeds.proudcity.com

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#846]

**Comment by jlyon** [comment]
feeds1.proudcity.com

- [ ] Review/test
- [ ] Evaluate if/can we put it behind api umbrella #852
- [ ] Update endpoint in wp code
- [ ] Backup live mongo db
- [ ] Switch to live mongo db

**Comment by jlyon** [comment]
@aschmoe have you had a chance to look at this?

**Comment by aschmoe** [comment]
@jlyon I merged in all the latest from my work, rebuilt the docker image, everything is running well on feeds1 as far as I can tell.

Could you elaborate a little on what "putting it behind api umbrella" means?

**Comment by jlyon** [comment]
@aschmoe 
1. Get API umbrella working (I've broken it trying to configure it)
2. Set it up as a feed from API umbrella (api.proudcity.com/feeds/...)

**Comment by jlyon** [comment]
Addeed manual steps to RELEASE issue.
