### ISSUE TITLE
Kettering: /contact city staff and elected official pills error

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#849]
If you click "City Staff Contacts" or "Elected Officials" on the contact page, you get a page not found error.

Step 1: https://kettering-oh.proudcity.com/contact/
Step 2: select elected officials or city staff
https://kettering-oh.proudcity.com/people?filter_categories%5B%5D=58
![screenshot 2017-02-08 13 42 09](https://cloud.githubusercontent.com/assets/6032426/22751912/6bdda180-ee04-11e6-8a83-d8303bc0f5ef.png)
Step 3: checked the contact submenu widget on /contact and it appears to be correct:
![screenshot 2017-02-08 13 43 21](https://cloud.githubusercontent.com/assets/6032426/22751954/976e6a3c-ee04-11e6-91c0-ea56e6aef6e3.png)

**Comment by aschmoe** [comment]
@kevindherman fixed this by restoring the "People" page from the trash

**Comment by jlyon** [comment]
Moving to ready
