### ISSUE TITLE
Thumbnails not working on server

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#851]
@aschmoe I'm using https://github.com/brenden/node-webshot.git, which uses phantomjs to render the page and then take a screenshot. It all works great locally, but it doesn't look like it's working on the api server.

Did you run into issues running Phantom on a headless (no ui) server?

**Comment by jlyon** [comment]
well that was easy
```
apt-get install libfontconfig
npm install -g phantomjs
```

**Comment by aschmoe** [comment]
@jlyon nice
