### ISSUE TITLE
Dashboard: integrate zendesk web widgets

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#854]
@kevindherman did you look into this?   It seems like it's chat on steroids. https://support.zendesk.com/hc/en-us/articles/203908456-Using-Web-Widget-to-embed-customer-service-in-your-website  It seems like it might be worth looking into for the new dashboard

**Comment by kevindherman** [comment]
@jlyon the knowledgebase stuff looks like it'll be the most helpful.
