### ISSUE TITLE
Service Center: Make date replace work with number values

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#855]
- [ ] See K
- [ ] Also debug DM

**Comment by jlyon** [comment]
@kevindherman Kettering local services should be all set now.  

Broke out danvers into #865

**Comment by kevindherman** [comment]
@jlyon I noticed leaf collection and city council district (shows day of the week) being funky on K.

https://kettering-oh.proudcity.com/#/city/local/location/39.6957723,-84.1620074
![screenshot 2017-02-16 09 27 01](https://cloud.githubusercontent.com/assets/6032426/23024940/31291296-f42a-11e6-8487-3d0f3282e993.png)

**Comment by jlyon** [comment]
@kevindherman I think you need a hard refresh (Shift+refresh)

**Comment by kevindherman** [comment]
@jlyon worked, sorry about that.
