### ISSUE TITLE
Change local services to "my services"

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#858]
@jlyon is this an easy item? Stacy felt like "My Services" was more inviting for an interactive section than "local" which I agree with. However, I wasn't sure if this was a term we wanted to coin. 

What do you all think?

**Comment by jlyon** [comment]
This would have to be a platform-wide change (at least the way things are set up currently). I think we originally had it as "My San Rafael", and Rebecca thought that "Local Services" was a better description.  I personally like My Services.

**Comment by kevindherman** [comment]
The other name was "Today in San Rafael" but that might end up getting really long for some of our other customers. 

I think the My Services is best for a universal name.

**Comment by jlyon** [comment]
@kevindherman you want to float it by SR and we can make the change in this release?

**Comment by kevindherman** [comment]
@jlyon they're cool with it.

**Comment by jlyon** [comment]
@kevindherman Got it
