### ISSUE TITLE
esig: Theme esig page

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#861]
url https://www.cityofsanrafael.org/e-signature-document/?esigpreview=1&document_id=9

BAsically you place the esig on its own page.  It seems like it's breaking the `Proud` js.   The esig is embedded in its own page https://www.cityofsanrafael.org/wp-admin/post.php?post=13802&action=edit.  I think it would be fine to just hide the header/footer on esig pages

**Comment by jlyon** [comment]
plugin-compatibility.php, line 81
```
add_action("template_redirect", "esig_remove_template_include_filter", -100);
```

https://www.cityofsanrafael.org/monthly-parking-card-application-signature/

```
if (!class_exists('WP_E_Digital_Signature')) :
#in e-signature.php:
            require_once ESIGN_PLUGIN_PATH . '/includes/Esign_core_load.php';

```

**Comment by aschmoe** [comment]
@jlyon this was fixed last release right?
