### ISSUE TITLE
Danvers: department list widget not displaying selected dept's

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#867]
On the public works dept page the department list widget is using the display specific department feature. However, after the release last night the departments being listed on the front-end do not match the selected departments in the widget.

https://danvers-ma.proudcity.com/departments/department-public-works/
![screenshot 2017-02-16 09 37 04](https://cloud.githubusercontent.com/assets/6032426/23025460/10ce005e-f42c-11e6-9e86-142e6afa6fce.png)

Departments selected:
![screenshot 2017-02-16 09 36 41](https://cloud.githubusercontent.com/assets/6032426/23025459/10becf44-f42c-11e6-95ed-2b9bf453ad96.png)

I also noticed that "agency" is showing instead of "department" so I wonder if something with that widget reverted.

**Comment by jlyon** [comment]
@kevindherman not sure if this one is fixed...

**Comment by kevindherman** [comment]
@jlyon this is fixed. closing.
