### ISSUE TITLE
Disable Social, Departments by default on /contact page table

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#871]
- [x] remove person column on department pill
- [x] remove social column
- [x] remove department column in city staff contacts pill

**Comment by kevindherman** [comment]
@jlyon @aschmoe I think we might want to consider making this universal. Most of our customers are following this strategy with departments and people columns.

**Comment by jlyon** [comment]
@kevindherman set this up. Leaving open to edit template at the release.
