### ISSUE TITLE
Mobile iconset formatting

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#872]
ZenDesk:

icon sets are looking weird on different devices. attached is a screen shot from my surface, rendering for a tablet view using Chrome.

<img width="855" alt="weird buttons" src="https://cloud.githubusercontent.com/assets/6032426/23081713/0b6a7f4a-f524-11e6-9c76-b6267d6a7460.PNG">

**Comment by aschmoe** [comment]
duplicate #896
