### ISSUE TITLE
Document list widget title not showing

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#873]
The widget titles aren't showing on the front end for the document list widget on Port Orchard. 

https://www.cityofportorchard.us/financial-forms/

![screenshot 2017-02-17 16 30 18](https://cloud.githubusercontent.com/assets/6032426/23084024/87a8bb26-f52e-11e6-9bc2-e000b932925b.png)
![screenshot 2017-02-17 16 30 09](https://cloud.githubusercontent.com/assets/6032426/23084025/87ae00cc-f52e-11e6-9793-7498a121e983.png)

**Comment by kevindherman** [comment]
@jlyon @aschmoe this appears to be universal. SR just asked about their homepage news and events feed in ZenDesk which are also missing their widget title display on the frontend.

https://www.cityofsanrafael.org/
![screenshot 2017-02-21 11 46 14](https://cloud.githubusercontent.com/assets/6032426/23174802/8cd27f1a-f82b-11e6-81a9-700251735e43.png)
![screenshot 2017-02-21 11 46 33](https://cloud.githubusercontent.com/assets/6032426/23174803/8cda521c-f82b-11e6-93e3-ed6c2de4ea2c.png)

**Comment by jlyon** [comment]
@kevindherman pushed this hotfix from @aschmoe
