### ISSUE TITLE
Improve parsing of local services hours text

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#874]
I think the local services for Danvers might be on the wrong timezone because it's showing that townhall is closed even though it's 11:53 am on Tuesday.

![screenshot 2017-02-21 11 51 00](https://cloud.githubusercontent.com/assets/6032426/23175095/6951f236-f82c-11e6-8a84-3040fb739050.png)

The hours are correct on:
https://danvers-ma.proudcity.com/wp-admin/admin.php?page=service-center-settings
![screenshot 2017-02-21 11 52 21](https://cloud.githubusercontent.com/assets/6032426/23175086/6277393a-f82c-11e6-83c3-6fd65d1e7284.png)

**Comment by jlyon** [comment]
@kevindherman fixed this.

**Comment by kevindherman** [comment]
@jlyon is this being pushed in the release or was a hotfix? I'm still seeing that the Town Hall is closed (middle of the day).

**Comment by jlyon** [comment]
@kevindherman this was a combination of our time matching algorithm being too specific, and some issues with the way they copy/pasted the times (from Word?).

They had
```
Sunday: Closed
Monday: 8AM–5PM
Tuesday:  8AM–5PM
Wednesday:  8AM–5PM
Thursday: 8AM–7:30PM
Friday: 8AM–1:30PM
Saturday: Closed
```

I changed it to
```
Sunday: Closed
Monday: 8:00AM - 5:00PM
Tuesday: 8:00AM - 5:00PM
Wednesday: 8:00AM - 5:00PM
Thursday: 8:00AM - 7:30PM
Friday: 8:00AM - 1:30PM
Saturday: Closed
```

Changes I needed to make:
* Times need to have the minutes (":00")
* They had a weird long dash `–`, that you can't read in php. I changed it to a normal `-`.

We also were only looking for lowercase am/pm, so I changed the pattern to match AM/PM too.  This will be fixed after the release is pushed.
