### ISSUE TITLE
SR: redirects and broken links

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#877]
We got this message from SR in ZenDesk:

> i've noticed that some of our redirects are no longer working. for example, www.cityofsanrafael.org/smart goes to page not found, when it used to direct to https://www.cityofsanrafael.org/departments/smart

When troubleshooting it I noticed a lot of broken links, many due to, HTTP. Should there be so many broken links or is something off? I feel like there is a coachable moment here but I lack the knowledge. @jlyon @aschmoe could you give me a hand with the redirect and broken links?

It looks like the /smart redirect was deleted so I added it back.

**Comment by jlyon** [comment]
@kevindherman it looks like these were legitimate broken links, not due to http vs https.  For example:

* http://www.cityofsanrafael.org/fire-prevent-home/ redirects to https://www.cityofsanrafael.org/fire-pevent-home/, which doesn't exist
* http://www.cityofsanrafael.org/library-home/ redirects to https://www.cityofsanrafael.org/library-home/, which doesn't exist

A lot of these look like images, which we can ignore.

I just re-ran the broken link checker, so we'll see what this list looks like in the morning https://www.cityofsanrafael.org/wp-admin/tools.php?page=view-broken-links

**Comment by kevindherman** [comment]
@jlyon thank you.

Just checked the broken links and there are still a lot (242). I'll let them know.

**Comment by jlyon** [comment]
@kevindherman It seems like a lot of them (the first 4 pages or so) are from https://www.cityofsanrafael.org/job-descriptions/, and aren't real broken links.  I think it's looking at an old revision, or the fact that the content on the page is in a text field from the page builder is throwing the broken link checker off.

**Comment by kevindherman** [comment]
@jlyon should I go through and dismiss all the job listings or should we figure out a long term fix?

**Comment by kevindherman** [comment]
@jlyon got this email about this issue from SR this morning, what do you think is the best way to resolve?

Kevin,

The reason those links are broken is because when I originally created the page, I created a new page for each job description and then hyperlinked the job classification. I recently went back over it and added the media directly into the text because it was effecting search hits. Once I did that I deleted the pages - which caused broken links. 

However, I accidentally deleted the links from the source last night. I created a "live chat" but never heard back. Is there any way to retrieve that job descriptions page? I have a temp page in there for now.

**Comment by kevindherman** [comment]
Found the trashed page and we'll re-publish it so this should work itself out.

**Comment by jlyon** [comment]
@kevindherman Trash to the rescue! Let me know if you need any help with this.

**Comment by jlyon** [comment]
Moving to ready for now.
