### ISSUE TITLE
Demo tweaks

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#88]
https://trello.com/c/1TD40mLf/386-marketing-action-items-01-29-16

**Comment by jlyon** [comment]
- [ ] responsive to iframe

**Comment by jlyon** [comment]
![screenshot from 2016-02-01 13 31 37](https://cloud.githubusercontent.com/assets/550909/12732018/78719e8e-c8e8-11e5-9edf-9cf511430dc7.png)
![screenshot from 2016-02-01 13 30 52](https://cloud.githubusercontent.com/assets/550909/12732019/7874b9f2-c8e8-11e5-9593-70b25ff9b3db.png)

**Comment by lukefretwell** [comment]
## Step 1

Text above form:

Get access to your free BETA site and test drive how Corvallis can deliver better digital government services.

<below button>

#### Questions?

Call us at (510) 671-0593 or email info@proudcity.com.

===

### Other comments

- [ ] remove 'Learn more about ...' link on step 2
- [ ] make spacing same on steps 1 and 2 (I like 2)
- [ ] think can remove PC logo on step 2
- [ ] make video on right of form?

**Comment by jlyon** [comment]
Pushed all of these changes live: https://demo.proudcity.com/get/Oregon/Corvallis/answers

@aschmoe can you make 2 tweaks?
- [ ] Make sure button work (in right sidebar, below chat, currently commented out)
- [ ] When you scroll down and footer becomes visible, open the modal

**Comment by aschmoe** [comment]
@jylon done
