### ISSUE TITLE
New tab option for Iconset links

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#880]
@jlyon is there a way to have iconset links open in a new tab?

**Comment by jlyon** [comment]
We'll get this in the release on Wed 

cc @aschmoe

**Comment by jlyon** [comment]
@kevindherman Added a checkbox to both the Icon Set and Icon button widgets.

![screenshot from 2017-03-02 14 40 54](https://cloud.githubusercontent.com/assets/550909/23530385/4db2c074-ff56-11e6-892c-06dffea91549.png)
