### ISSUE TITLE
K & K Parks: remove social column /contact

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#881]
The social column can be removed from all pills on both the main site and parks.

**Comment by jlyon** [comment]
@kevindherman I set this up.  The Department list still is showing the social icons (there was a typo in the code). I fixed this in #885, and it will be pushed in this release.

**Comment by jlyon** [comment]
General steps:
1. Change the specific list -- Agency list (should be Dept list), Contact list
2. Check the hide column for Social fields.
