### ISSUE TITLE
K & K Parks: remove add events from event detail

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#882]
I have removed the "add event" icon from the /events page for both Kettering and Kettering Parks but it still shows up underneath the more events list on individual event detail pages. @jlyon can you remove the add event from all pages on both Kettering sites?

![screenshot 2017-02-27 11 33 49](https://cloud.githubusercontent.com/assets/6032426/23369908/e2a06eca-fce0-11e6-980d-e003d210bdfe.png)

**Comment by jlyon** [comment]
@kevindherman removed this. Steps:
1. Customize, browse to an event in the preview area
2. Click widgets > Event sidebar
3. Rm icon link

Do you think we should remove this from the general city template?

![customize- board of zoning appeals - canceled - kettering](https://cloud.githubusercontent.com/assets/550909/23376734/1ee90c10-fce2-11e6-9c2a-044527684e32.jpg)

**Comment by kevindherman** [comment]
@jlyon thanks. Is it removed on both sites?

I think we should keep it as a default for other sites for now. Although it's not commonly used, this is the first time someone has ever asked to remove it entirely.
