### ISSUE TITLE
Remove reported issues map layer on foursquare map if SeeClickFix is not used

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#883]
@jlyon can the reported issue layer be removed from the homepage map on Kettering even though they're using the foursquare pins at this time?

**Comment by jlyon** [comment]
Yes, we'll get this into the release on Wed @kevindherman

**Comment by jlyon** [comment]
@kevindherman If "Issues (311) provider" is not set to SeeClickFix on /wp-admin/admin.php?page=service-center-settings, and FourSquare pins are used, the Reported issues tab will not appear on the map.
