### ISSUE TITLE
K: adding the service center to other city facebook pages

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#884]
@jlyon is it possible to add the Service Center to multiple city facebook pages? 

Kettering asked if we could add it to their Police and Fire Dept facebook pages if possible.

**Comment by jlyon** [comment]
@kevindherman  yes, definitely possible.  I can either put together steps (like K parks), or if they add me, I can set them up for them.  

The tabs will be the same on all of the different FB pages.

**Comment by kevindherman** [comment]
@jlyon Stacy said she gave you permissions to both the fire and police pages so you should be able to do that when you get a moment.

**Comment by jlyon** [comment]
Hmm, not seeing these invites wtf. @kevindherman

**Comment by jlyon** [comment]
Waiting on FB access

**Comment by kevindherman** [comment]
@jlyon they now want to hold off on this.

**Comment by jlyon** [comment]
Moving back to backlog @kevindherman
