### ISSUE TITLE
WC: random code showing on pages

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#888]
There is random code showing on a couple of the West Carrollton pages and they're concerned about security. 

Here's an example:
https://www.westcarrollton.org/national-night-out/

![screenshot 2017-03-01 11 37 57](https://cloud.githubusercontent.com/assets/6032426/23470106/8c5bc85e-fe73-11e6-8b49-2d570b7022f2.png)

Also, two pages on police now have subscribe boxes that Erika doesn't remember adding.
https://www.westcarrollton.org/crime-stoppers/ and https://www.westcarrollton.org/speed-trailer/
![screenshot 2017-03-01 11 38 34](https://cloud.githubusercontent.com/assets/6032426/23470201/cfbb90d4-fe73-11e6-8ba7-3f7c488d30b8.png)

Both of the pages with the random subscribe boxes are not using pagebuilder which seems odd to me.

I'm wondering if both of these have something to do with some widgets reverting to old settings that were previously blocked before an update @aschmoe made a week or so ago.

**Comment by kevindherman** [comment]
https://www.westcarrollton.org/fire-captains/
https://www.westcarrollton.org/open-burn-rules/
https://www.westcarrollton.org/open-burn-rules/
 
https://www.westcarrollton.org/fire-captains/
 
https://www.westcarrollton.org/citizens-police-academy/
 
https://www.westcarrollton.org/national-night-out/

https://www.westcarrollton.org/open-burn-rules/
 
https://www.westcarrollton.org/fire-captains/
 
https://www.westcarrollton.org/citizens-police-academy/
 
https://www.westcarrollton.org/national-night-out/

https://www.westcarrollton.org/frequently-asked-questions/
 
https://www.westcarrollton.org/available-real-estate/
 
https://www.westcarrollton.org/resources-available/
 
https://www.westcarrollton.org/w-central-ave-strategic-plan-rfp/
 
https://www.westcarrollton.org/rental-registration-program/------no subscribe should be on this page!
 
https://www.westcarrollton.org/engineering-division/-no subscribe should be on this page!
 
https://www.westcarrollton.org/water-division/-no subscribe should be on this page
 
https://www.westcarrollton.org/property-tax-information/ - no subscribe should be on this page
 
https://www.westcarrollton.org/tax-forms/ no subscribe should be on this page

**Comment by jlyon** [comment]
@kevindherman 
WordPress core had a security vulnerability that allowed the public to insert code into the database.  The WordPress security release was applied in our Feb 1 release (Release 1.24.0). Unfortunately, there was a one-day lag between when the security vulnerability was released and when the ProudCity Platform was updated.  In the future, we will ensure that all future security releases are applied immediately.

There were 120 instances of posts that had been updated.  Most just had a small piece of code (`<script></script>`) added that did nothing and was not visible. We have reverted all of these posts back to their previous revision, and all of the pages you sent no longer have code appearing on them.  Some of the pages with with Subscribe form (with -no at the end of their urls) have been reverted back to their old urls (https://www.westcarrollton.org/engineering-division/-no to https://www.westcarrollton.org/engineering-division, etc).  Please let us know if you notice any other anomalies and we will look into it ASAP.

In addition, we will be migrating your site over to a new, more secure version of our platform in the next week.  This will require a DNS change.  We will be in touch with you about the exact timing in the next couple days.

cc @aschmoe

**Comment by jlyon** [comment]
I just finished going through our other live sites and did not find any similar editing patterns.

**Comment by kevindherman** [comment]
@jlyon @aschmoe an additional problem may be that pagebuilder was disabled on a lot of pages like /government

https://www.westcarrollton.org/government/
![screenshot 2017-03-01 14 35 12](https://cloud.githubusercontent.com/assets/6032426/23477624/912eb95e-fe8c-11e6-86f6-ba157eb77560.png)
![screenshot 2017-03-01 14 37 01](https://cloud.githubusercontent.com/assets/6032426/23477625/9133fe32-fe8c-11e6-8191-097ad0bd035b.png)

**Comment by jlyon** [comment]
@kevindherman Oops, this was from my fix I think.  I'll go through these now.

**Comment by jlyon** [comment]
@kevindherman @aschmoe 

I fixed these pages 
https://www.westcarrollton.org/government/
https://www.westcarrollton.org/businesses
https://www.westcarrollton.org/news/

All of the other top-level and the sub-level pages that I could find (within Contact) were unaffected.  I tried going into as many subpages as I could too
