### ISSUE TITLE
De Leon: new accounts for social wall

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#890]
@aschmoe can you add these accounts to De Leon's main social wall? I can then add them to specific dept pages listed below. 

Fire Department:
https://www.cityofdeleon.org/departments/de-leon-volunteer-fire-department/
https://www.facebook.com/deleonVFD/

Animal Shelter:
https://www.cityofdeleon.org/departments/animal-shelter/
https://www.facebook.com/CODanimalshelter/

Police Department:
https://www.cityofdeleon.org/departments/police-department/
https://www.facebook.com/deleonpd/

**Comment by aschmoe** [comment]
@kevindherman just did this, sorry missed it.

**Comment by jlyon** [comment]
@kevindherman it looks like something happened to their homepage (it was like this before the release)

**Comment by kevindherman** [comment]
@jlyon Alex pointed this out to me yesterday. I reached out to see if it was done on purpose and if I could help.
