### ISSUE TITLE
SR: duplicate news post title issue

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#899]
From ZenDesk:

> Hey - we keep running into an issue with the news feed posts where we have duplicate post titles and have to edit the URL. One that could fix this would be for the date of the post to be in the URL. Just food for thought... do what you want with it...

**Comment by jlyon** [comment]
@kevindherman @aschmoe this would be pretty easy to set up, either just for SR or in our global site-wide template.  Thoughts?

**Comment by kevindherman** [comment]
@jlyon @aschmoe I think global.
