### ISSUE TITLE
SR Parks: add to calendar feature

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#903]
@jlyon  Confirmed this ZenDesk ticket:

https://www.livelifelocally.org/events/pool-schedule-april-7/

When using the Add To Calendar feature on a specific event entry, I get this error message for all of the calendars:

![screenshot 2017-03-07 14 41 02](https://cloud.githubusercontent.com/assets/6032426/23674594/6190047a-0344-11e7-9307-36851752379d.png)

I did not get this error on SR's main site or Kettering so I think it's isolated.

**Comment by jlyon** [comment]
Moving to done.  Seems like this was isolated to that one event or fixed in a future release.  It's working on https://www.livelifelocally.org/event/mothers-day-brunch-falkirk/.
