### ISSUE TITLE
PO: IP address per form submission

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#905]
Is there a way to track IP addresses per form submission?

From ZenDesk:

Looking at the survey form, is there a way to find out submittal results by IP address or other type of identification? We are trying to find out if one person is doing the survey multiple times.

------------------
Submitted from: https://www.cityofportorchard.us/wp-admin/admin.php?page=gf_edit_forms&id=20

**Comment by aschmoe** [comment]
@kevindherman one solution would be to include an email field and mark that field "no duplicates"

If this isn't a sufficient measure, we can look into a more advanced solution

**Comment by kevindherman** [comment]
@aschmoe I'll float it by them, should be ok.

**Comment by jlyon** [comment]
The IP address is automatically stored for each entry. If they're just trying to figure out if the same IP is submitting the form multiple times for existing data, go to entries, click on the gear in the header (1), and then add the User IP field (2). 

To limit the number of entries, you could use Alex's email method, or check the Limit entries box on the Form Settings (ie https://www.cityofportorchard.us/wp-admin/admin.php?page=gf_edit_forms&view=settings&subview=settings&id=19) (3).

1. 
![entries port orchard wordpress 1](https://cloud.githubusercontent.com/assets/550909/23843796/83dc101a-077b-11e7-9499-09b819d1c03c.jpg)

2. 
![entries port orchard wordpress](https://cloud.githubusercontent.com/assets/550909/23843806/8c021122-077b-11e7-9506-fa5e16221f9f.jpg)


3. 
![form settings forms port orchard wordpress wordpress](https://cloud.githubusercontent.com/assets/550909/23843815/91145076-077b-11e7-9dea-8a4588261b00.jpg)

**Comment by aschmoe** [comment]
Pretty sure that limit is a "this form can be submitted 10 times total"...
not limit per user

**Comment by kevindherman** [comment]
I assumed the limit was also for the entire form like @aschmoe.
