### ISSUE TITLE
Charge form widget to say "ProudCity Forms widget"

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#906]
Current the widget says:

![screenshot 2017-03-09 16 48 41](https://cloud.githubusercontent.com/assets/6032426/23772285/637b4880-04e8-11e7-97fb-4666b94cd9ae.png)

It would be great to update it to match the product "ProudCity Forms"

**Comment by aschmoe** [comment]
@kevindherman we talking the sub-text or the main title?

**Comment by kevindherman** [comment]
@aschmoe just the sub text.

**Comment by aschmoe** [comment]
@kevindherman this was done but now looking at it, I see now I've introduced a typo.  Will fix this up
