### ISSUE TITLE
ACH payments in gravityforms

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#907]
https://www.gravityhelp.com/documentation/
https://www.gravityhelp.com/documentation/category/form-object/
https://www.gravityhelp.com/documentation/article/gform_add_field_buttons/#example-one

**Comment by jlyon** [comment]
@kevindherman any update on the direction here?

**Comment by kevindherman** [comment]
@jlyon hitting the breaks on this for now.

**Comment by jlyon** [comment]
cool

**Comment by kevindherman** [comment]
@jlyon I posted to trello their strategy and a question about how to proceed on that project.

**Comment by jlyon** [comment]
responded in https://trello.com/c/EFyThl54/1292-san-rafael-payments
