### ISSUE TITLE
PO: media upload issue

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#909]
This came in from Port Orchard on ZenDesk:

Hello - I am trying to update Subtitle VIII on the following page: https://www.cityofportorchard.us/regulations/ but when I go to upload the document/media I receive the attached error message. This is the same document that is currently uploaded to the site, just updated slightly, and I did not have any issues with the original file.

[Error Message.pdf](https://github.com/proudcity/wp-proudcity/files/842510/Error.Message.pdf)

@jlyon @aschmoe is this related to any kubernetes work being done? I noticed the URL path on these uploads are different from the usual: https://storage.googleapis.com/proudcity/portorchardwa/uploads/2016/08/Subtitle-VIII.pdf

**Comment by jlyon** [comment]
Looks like she tried again and it worked. My guess it was an internet issue on her end.

The https://storage.googleapis.com path is the new one for all sites moving forward.

Moving to ready.
