### ISSUE TITLE
Colma: hitting tab skips fields on webform

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#910]
From Colma:

https://colma-ca.proudcity.com/building-department-inspection-request-form/

Tab order not as expected. User starts at field Permit Number > enter data in Permit Number > hits TAB key.

User expectation would be a jump to the next data field, in this case Project Address. Instead, focus jumps to the data field for Subscribe field at bottom of the page. Tested behavior in Chrome, IE, Firefox.

@aschmoe You worked on a similar issue in the past, right?

**Comment by aschmoe** [comment]
@kevindherman looks like the tab tries to go to contact form in footer.  I will add a starting index of like 100 to that contact form to combat this.  Will be in release or maybe hotfix tomorrow

**Comment by jlyon** [comment]
fixed this.  customize, edit the footer widgets, advanced, set the tabindex to 100.  i made this update to the base template too (https://city-template.proudcity.com):
![customize- home - colma](https://cloud.githubusercontent.com/assets/550909/23934704/5b43906c-0904-11e7-89ae-8288a27be64e.jpg)

cc @kevindherman @aschmoe
