### ISSUE TITLE
Production site DNS updates

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#911]
@kevindherman 

I finally compiled a list of DNS info and who controls it: https://docs.google.com/a/proudcity.com/spreadsheets/d/1wvj3xW5vmkZ1VshpH00ED57I74VNRa5jZwlD9R5x2RM/edit?usp=sharing

If you think it is enough advance notice, I would like to migrate as many of the sites in the Immediate section (rows 3-9) as we can Thurs after the release so we can get off of Amazon and start to set up the Dashboard.  This would be all of the column B = Us entries. For the sites we don't control, we should try to coordinate a time for the DNS switchover.  Ideally it would be EOD, but it really just needs to be some time where people won't be actively making edits.  There shouldn't be any downtime.

cc @aschmoe 

---

Email template (will need to be modified for sites whose DNS we don't control)

---
We will be migrating your site over to our new hosting platform Thursday after hours after our bi-weekly release.  The new hosting platform has improved backup and reliability protocols and should also provide improved the page load speeds.

There will be no downtime or noticable changes to your site during this migration (outside of the standard release updates), however you may receive an email alert from your domain ame control panel.  Please contact us if you notice any issues.

Thank you,
The ProudCity Team

**Comment by kevindherman** [comment]
@jlyon still waiting on the yellow people to coordinate times.

**Comment by jlyon** [comment]
@kevindherman took care of most of these migrations, updated https://docs.google.com/spreadsheets/d/1wvj3xW5vmkZ1VshpH00ED57I74VNRa5jZwlD9R5x2RM/edit#gid=2008170864.  WA and SR are the only ones that we still need to schedule
