### ISSUE TITLE
pattern.getproudcity.com

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#917]
ip address: 192.241.208.128.  I think this is on digitalocean?

here's a list of sites on this server:
![screenshot from 2017-03-15 15 57 53](https://cloud.githubusercontent.com/assets/550909/23974402/508f75b6-0998-11e7-9b8e-8d02636b50a2.png)

cc @aschmoe

**Comment by jlyon** [comment]
@aschmoe I put this on workhorse.albatrossdigital.com in /var/www/html/labspace/proudcity/pattern and provisioned it with a let's encrypt ssl cert.

Will you just double-check the apps on www.proudcity.com that are using it?

**Comment by aschmoe** [comment]
@jlyon seems to be working fine
