### ISSUE TITLE
Migrate service center to gcloud

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#919]
my.proudcity.com too

**Comment by jlyon** [comment]
@aschmoe This has been added to firebase hosting. 

- Overview: https://firebase.google.com/docs/hosting/quickstart.
- Dashboard: https://console.firebase.google.com/project/service-center-cbe20/hosting/main

Basically there's a new firebase.json file that configures most of the stuff you'll need. You'll need to:
```
firebase init
```
and then
```
cd ./service-center
firebase deploy
```
It will push the dist dir to https://service-center-cbe20.firebaseapp.com, which also currently maps to service-center-dev.proudcity.com, and will also map to service-center.proudcity.com later tonight (they need to provision an ssl cert, so there's downtime, so it's after-hours)

**Comment by jlyon** [comment]
@todo:
- [ ] set up service-center-beta subdomain

**Comment by aschmoe** [comment]
@jlyon no problem initt'in etc but navigating to that project url gives me a "Sorry" page, and nothing shows up in my https://console.firebase.google.com/ page

**Comment by jlyon** [comment]
@aschmoe I set up service-center-beta.pc.com as a separate Firebase project and pushed the latest code from `master`: https://console.firebase.google.com/project/service-center-beta/hosting/main.

I updated README with better instructions: https://github.com/proudcity/service-center/blob/master/README.md
