### ISSUE TITLE
De Leon: make homepage search box like SR

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#923]
How can I make De Leon's search box on the homepage wide like San Rafael's?

![screenshot 2017-03-17 11 54 45](https://cloud.githubusercontent.com/assets/6032426/24051510/a3467590-0b08-11e7-89d6-994d568f9f14.png)
![screenshot 2017-03-17 11 54 52](https://cloud.githubusercontent.com/assets/6032426/24051509/a3449be4-0b08-11e7-97dd-0641f2706762.png)

**Comment by jlyon** [comment]
@aschmoe ?

**Comment by aschmoe** [comment]
@jlyon @kevindherman looks like thats the width of the "Header" size of the page header.  If they were to switch to "Full Height" it would be expanded.  For SR theme I believe it was requested that both sizes have the larger width.... we could probably just extend that logic to the main theme, but might end up with some department pages ect that had way too much horizontal real estate on those "Header" sizes

**Comment by kevindherman** [comment]
@aschmoe @jlyon I switched it to the full header which did the trick.

Thanks guys.
