### ISSUE TITLE
Kettering: facebook link in footer is broken

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#928]
The facebook link in the footer of Kettering (https://kettering-oh.proudcity.com/#/city/answers) is broken and should link to: https://www.facebook.com/City-of-Kettering-Ohio-Government-170816296316644/

![screenshot 2017-03-22 11 20 12](https://cloud.githubusercontent.com/assets/6032426/24205422/c224e0ae-0ef1-11e7-8926-004aa9b14ca1.png)

**Comment by aschmoe** [comment]
@kevindherman another example of the facebook-lack-of-named-profile-numeric-ID thing `https://www.facebook.com/City-of-Kettering-Ohio-Government-170816296316644/`  any time there is a number in that url, the facebook account ID is the number, not the text

I've updated the values
