### ISSUE TITLE
Calendar week starts on Monday, not Sunday

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#929]
Most calendars displays Sun-Mon-Tues-Wed-Thurs-Fri-Sat but our frontend and backend calendars display mon-tues-wed-fri-sat-sun. Can we switch to the more common format?

**Comment by jlyon** [comment]
Need to look into this one a little bit. For my notes: the setting should be on https://www.cityofportorchard.us/wp-admin/edit.php?post_type=event&page=events-manager-options#formats

**Comment by jlyon** [comment]
@kevindherman I fixed this on PO, and will update the rest during the release tonight.

Week now starts on Sunday on:
https://www.cityofportorchard.us/wp-admin/post-new.php?post_type=event
https://www.cityofportorchard.us/


Option was on /wp-admin/options-general.php
```
wp option update start_of_week 0 --allow-root
```

**Comment by jlyon** [comment]
This code didn't make it into the release update file. For next release
