### ISSUE TITLE
LocationFeature server (koop)

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#930]
@aschmoe I installed https://koopjs.github.io/ on koop.poudcity.com (repo: https://github.com/proudcity/koop-docker). It's in the koop namespace on kube.

I added https://www.npmjs.com/package/koop-geojson-file, and that example file I showed you on gist yesterday is at https://koop.proudcity.com/geojson/test/ with the featureserver at https://koop.proudcity.com/geojson/test/FeatureServer (see docs at the bottom of https://www.npmjs.com/package/koop-geojson-file).

docs
- Koop http://koopjs.github.io/docs/
- FeatureServer endpoints: https://github.com/koopjs/koop-output-geoservices
- Demo featureserver: http://koop.dc.esri.com/openData/dc/q/zoning

**Comment by aschmoe** [comment]
@jlyon looks like we'll need to do some cors stuff 

```No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access.```

**Comment by jlyon** [comment]
@aschmoe looks like the featureserver wasn't added. I just added it (build #6)
