### ISSUE TITLE
WA: post migration file issues

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#933]
Zendesk:

we have experienced problems with the site since the move to the Google hosted servers. Several documents are not available for preview or download: https://www.warracres-ok.gov/documents/ward-1-map/, https://www.warracres-ok.gov/documents/ward-2-map/, https://www.warracres-ok.gov/documents/ward-3-map/, https://www.warracres-ok.gov/documents/ward-4-map/, https://www.warracres-ok.gov/documents/sanitation-schedule-map/, https://www.warracres-ok.gov/documents/sanitation-schedule-map/

Also our logo (city seal) does not appear in the footer of the page. There is an image placeholder, but the image does not appear.

Newest posted newsletter preview does not appear, but link to download works; https://www.warracres-ok.gov/documents/march-2017-newsletter/

Links that sometimes work frequently return a hierarchical menu page instead of the actual page (see attached image). There is no consistency as to which links or when this happens.

Email:

We have experienced an exponential number of complaints because of problems since the move to the google hosted servers.  I submitted several of these issues via dashboard ticket this morning, and am still going through to see what I can find instead of waiting for a citizen to complain.
 
Another issue that the citizens may or may not be aware of is that the google hosted services are not invisible.  Images and other files show with links that include the google path which is something that I do not ever want to see.  An example is one I uploaded this morning for an example.  The image is a menu screen shot that I took because of one of the problems we are seeing.  The link to the image is https://storage.googleapis.com/proudcity/warracresok/uploads/2017/03/menu.jpg.  Which shows in the media library as menu.jpg.
 
Many of our documents and forms are not showing in the preview, and the download goes to an error message.  This includes while I am logged in to my.proudcity as well as when I am not logged in.  I just found another that was not in the list submitted with the trouble ticket https://storage.googleapis.com/proudcity/warracresok/uploads/2017/03/PC-3-14-17-agenda.pdf 
 
I am receiving an incredible number of complaints from citizens about things not working, and do not have time to go through the entire site to locate all the problems.  Please find out what is causing these issues and see what other problems exist so I can stop fielding complaints.

**Comment by kevindherman** [comment]
@aschmoe @jlyon the search and replace that Jeff did the other day should take care of most of the broken links and preview. However, I am not sure how to respond to the google path issue he brings up. What do you think the response to that should be?

**Comment by aschmoe** [comment]
@kevindherman @jlyon this was run earlier.  Initial testing indicates problem is fixed

**Comment by kevindherman** [comment]
thank you @aschmoe. Can you also help craft a response to the google url path?

**Comment by aschmoe** [comment]
@kevindherman 

"Google storage allows us to serve your website's content very quickly.  Unfortunately, there is not currently a straight forward way to route a more explicit url (like https://content.warracres-ok.gov) to the cloud storage, because of the constraints of HTTPS (which provides security for your citizenry).  We are researching how best to offer this functionality, but it will not be immediately available and may require additional monthly fees due to the complexity."

Think that kind of sums the problem up.

**Comment by jlyon** [comment]
Moving to ready @kevindherman @aschmoe
