### ISSUE TITLE
Kettering: redirect question

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#935]
I don't know why they did this but would having these double redirects mess with the site? For example, /jobs redirects to /jobs or /contact redirect to /contact?

![screenshot 2017-03-23 12 14 11](https://cloud.githubusercontent.com/assets/6032426/24257869/5dd35258-0fc2-11e7-9e82-58e59ea426bc.png)

https://kettering-oh.proudcity.com/wp-admin/edit.php?post_type=redirect_rule&paged=3&ids=7417

**Comment by aschmoe** [comment]
@kevindherman as we discussed that redirect is from job -> jobs, and should be fine
