### ISSUE TITLE
K Parks: CSS formatting

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#938]
Kettering Parks is having IE CSS issues. This seems to be isolated to explorer, still waiting on the version:

![pk](https://cloud.githubusercontent.com/assets/6032426/24406162/7b974246-1395-11e7-9268-6778feb859f9.png)

**Comment by kevindherman** [comment]
Drew from Kettering posted this so I think we're good here.

"The PlayKettering formatting hopefully is fixed now.  I suspect it was only a problem for us internal to the City network.  All the CSS for that site references http://playkettering.org without the www and we did not have an internal DNS record for the domain itself without any hostname."

Lets keep this open for monitoring but no need for a fire drill. 

@jlyon @aschmoe ^

**Comment by jlyon** [comment]
@kevindherman moving to ready, feel free to move back to in progress if something still needs to be done here.
