### ISSUE TITLE
Danvers: form export produces blank file

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#940]
Export entries form feature isn't actually exporting data in the csv it spits out.

If you use the export entries, select a form (test feedback in this example), select all fields, select a date range or not from this page doesn't yield any results on the attached report.

https://danvers-ma.proudcity.com/wp-admin/admin.php?page=gf_export
![screenshot 2017-03-28 13 54 15](https://cloud.githubusercontent.com/assets/6032426/24419704/0db911fe-13be-11e7-9270-0f50ea620070.png)

Blank Report:
![screenshot 2017-03-28 13 56 15](https://cloud.githubusercontent.com/assets/6032426/24419780/58f57644-13be-11e7-94cf-5292a0c961e0.png)

**Comment by jlyon** [comment]
@kevindherman this link you need to select some fields with the checkboxes:
![import-export danvers wordpress 1](https://cloud.githubusercontent.com/assets/550909/24599035/425641ea-1803-11e7-972a-b7d476a26d51.jpg)

The Feedback form doesn't have any entries yet, but if you select fields, you will at least see the headings in the csv file:
![screenshot from 2017-04-03 00 19 01](https://cloud.githubusercontent.com/assets/550909/24599053/57ca4f26-1803-11e7-9bca-8bfa18c285d4.png)

**Comment by kevindherman** [comment]
@jlyon I think you were looking at the wrong feedback form. The feedback form that's setup to the snippet right now is "TEST Feedback" which has had entries:

![screenshot 2017-04-03 08 42 32](https://cloud.githubusercontent.com/assets/6032426/24609671/9fae3780-1849-11e7-855a-47667fa1bbfe.png)

I tried select all or specific fields from that export page and I'm still getting a blank xcel sheet.

**Comment by jlyon** [comment]
@kevindherman I am seeing the empty file when trying to export that form's data.

@aschmoe you mind trying to take a crack at this one?

**Comment by aschmoe** [comment]
@kevindherman this just worked for me fine on the "Test Feedback" form... maybe try again?

**Comment by kevindherman** [comment]
@aschmoe working for me now too. Weird but I'll take it!
