### ISSUE TITLE
K Parks: iframe not resizing to mobile

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#941]
http://playkettering.org/kfwc-track-schedule/

If you shrink this page down to mobile the iframe calendar doesn't reformat nicely. They said it wasn't a problem on their old WP site. Is there something I can do to coach them along on this or get from the other vendor>?

![upload_3_28_2017_at_1_45_33_pm](https://cloud.githubusercontent.com/assets/6032426/24419568/90bc0990-13bd-11e7-8f42-3a44613de167.png)

**Comment by kevindherman** [comment]
I followed up with Ryan on the difference of how we embed versus how it was done previously:

It was direct into the "text" editor, no frame, just html'ed (not a word). I know the calendar is designed to switch from month view to day view when transferring from web to mobile views.

**Comment by jlyon** [comment]
Yes, this is not an iframe, it is a straight javascript embed.  They definitely have some responsive stuff in the CSS the widget is including (https://schedule.reachcm.com/IvoryRailroad/css/kettering.v1-5.css), but it doesn't seem to be totally working.

I set this up on a standalone page on our testing server (note that this includes AD in the url), and you get the same issue: http://workhorse.albatrossdigital.com/labspace/test.html

![workhorse albatrossdigital com-labspace-test html](https://cloud.githubusercontent.com/assets/550909/24732522/4155fd1a-1a26-11e7-8c17-c87ce046833a.jpg)

**Comment by jlyon** [comment]
@kevindherman ok to close?

**Comment by kevindherman** [comment]
@jlyon yeah. It might come up down the road if the other vendor makes changes but I think that's a ways away.
