### ISSUE TITLE
Make search box bigger, allow custom text to draw attention

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#943]
In BETA and general user feedback we've been hearing that end-users aren't utilizing the main search feature as much as admins (people who live on the site) do. 

Kettering thinks part of the problem for them is that the search was really bad on their previous site so people were trained not to use it. Other cities, like Danvers, have mentioned that people don't realize it's there right away. However, at first glance, the San Rafael site search numbers seem pretty good. 

![screenshot 2017-04-04 14 40 31](https://cloud.githubusercontent.com/assets/6032426/24673103/1ef90190-1945-11e7-895f-7f48d110da93.png)
![screenshot 2017-04-04 14 40 36](https://cloud.githubusercontent.com/assets/6032426/24673102/1ef85da8-1945-11e7-9feb-81e378d7e8d5.png)
![screenshot 2017-04-04 14 40 41](https://cloud.githubusercontent.com/assets/6032426/24673104/1efa39b6-1945-11e7-921e-3cfd0715dbef.png)

Here are a few ideas to get the conversation started on highlighting this feature:

1- tinker with "How can we help you?" language. @lukefretwell maybe you think of something clearer?
2-encourage service oriented tag lines like SR 
3- Other?

@jlyon @aschmoe @lukefretwell let me know what you guys think.

**Comment by jlyon** [comment]
Rebecca has definitely mentioned this a number of times. I don't have many ideas outside of making the search box larger or, like you mentioned Kevin, playing with the placeholder text.

**Comment by kevindherman** [comment]
@jlyon @aschmoe Danvers requested the phrase "Ask us anything". Can that text be added just for them ahead of the launch? Could be a good test to see if that helps or not.

**Comment by jlyon** [comment]
@kevindherman ok to push this as part of the release tomorrow?

**Comment by kevindherman** [comment]
@jlyon Danvers brought it up this morning, can it be a hotfix for them?

Kettering said they also liked "Ask us anything" and Colma is trying to figure it out.

**Comment by kevindherman** [comment]
@jlyon sorry, I responded to this before looking at Trello. Hotfix is preferred but release is fine, especially if it helps get everything done.

**Comment by jlyon** [comment]
@aschmoe add attribute to shortcode.  make it f'in big like Bing.

**Comment by kevindherman** [comment]
@jlyon @aschmoe where do I customize the text?
