### ISSUE TITLE
K Parks: events only able to save as draft

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#944]
https://www.livelifelocally.org/wp-admin/post.php?post=2775&action=edit

![screenshot 2017-04-05 16 08 11](https://cloud.githubusercontent.com/assets/6032426/24724742/49f0411c-1a1a-11e7-9b1b-a011b50f4673.png)

**Comment by jlyon** [comment]
@kevindherman Clicking the blue Publish button at the bottom of that box will publish the event

**Comment by kevindherman** [comment]
Alex worked on it earlier, it was a permission issue.
