### ISSUE TITLE
K parks: events listing day/month/year format

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#945]
Events are displaying the date as day/month/year, can this be switched to month/day/year?

https://www.livelifelocally.org/events

Also, on the backend:
![screenshot 2017-04-05 16 08 11](https://cloud.githubusercontent.com/assets/6032426/24724868/b6e82b68-1a1a-11e7-946a-a04afcb85982.png)

**Comment by jlyon** [comment]
@kevindherman I updated this format to m/d/y
