### ISSUE TITLE
Change language for news, events and documents Dates to just "Posted [date]"

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#947]
I've been getting feedback from a couple customers about the public publish date on news, events and documents. 

I'm thinking news should have "published on [date]" and then events and documents probably don't need anything. If documents need a date, I think "published on" would help with the confusion.

@jlyon @aschmoe @lukefretwell thoughts?

**Comment by aschmoe** [comment]
@kevindherman I think thats fine though I may lean towards a shorter "Posted [date]" but I don't feel strongly.

**Comment by kevindherman** [comment]
@aschmoe shorter is better.

**Comment by kevindherman** [comment]
@aschmoe @jlyon I'm seeming "posted on" for news but seeing just the date for events and documents. I thought the plan was to remove dates all together from events and documents.

**Comment by aschmoe** [comment]
Why would you remove the date from events?

**Comment by aschmoe** [comment]
@kevindherman ^^

**Comment by kevindherman** [comment]
Remove the date published from events. The date published is usually long before the event that they are promoting and having two dates confuses users.

**Comment by aschmoe** [comment]
Maybe I'm missing something but we don't display the date published on events.

**Comment by kevindherman** [comment]
@aschmoe I understand the confusion now. For events, the published date shows up on most of the views except list view which is used on /events. However, on the homepage for example, where the mini list is used, it shows the published date. I think the published date should be removed from all event (and document) content.

**Comment by aschmoe** [comment]
@kevindherman every display I see has the event date not published date... could you show me where this is happening?

**Comment by kevindherman** [comment]
@aschmoe thanks for clearing this up on the call.
