### ISSUE TITLE
contact list order

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#95]
The contact list currently orders by first name, can it switch to order by last name? Can the mayor be defaulted to be at the top of the list?

**Comment by aschmoe** [comment]
@kevin easiest path forward for now is to use https://west-carrollton-oh.proudcity.com/wp-admin/edit.php?post_type=staff-member&page=staff-member-order and I will make sure things are sorted by that.

**Comment by kevindherman** [comment]
ok.

On Wed, Feb 3, 2016 at 1:57 PM, Alex Schmoe <notifications@github.com>
wrote:

> @kevin <https://github.com/kevin> easiest path forward for now is to use
> https://west-carrollton-oh.proudcity.com/wp-admin/edit.php?post_type=staff-member&page=staff-member-order
> and I will make sure things are sorted by that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/95#issuecomment-179403856>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by aschmoe** [comment]
This is ready, so order away
