### ISSUE TITLE
Service Center: change "select answer type" to select question type

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#954]
Danvers suggested changing "Select answer type" to "select question type" to help make it clearer that this is where questions are. 

A little nitpicky but I think it makes sense because you Get Answers from asking questions. 

Thoughts?

![screenshot 2017-04-11 14 41 07](https://cloud.githubusercontent.com/assets/6032426/24925136/47f08bba-1ec5-11e7-9841-4d1c672b0c83.png)

**Comment by lukefretwell** [comment]
Suggestions:

* Make home search bar bigger to fill entire opaque box (see https://www.google.com for reference - ~ 600px - see also https://www.utah.gov/).
* The "Select answer type" text in Service Center seems like a call to action, but when I try to click nothing happens. I'd a) delete that text or b) remove the icon before it and add a colon after, so it's referencing action items below.
