### ISSUE TITLE
Kettering Parks: broken links

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#955]
Zendesk:

"Some of our broken links seem to be unusual. I had cleared out the list last week, now there are a lot of links to things like people and news, which we have not used on the site since we've been building it."

@jlyon @aschmoe any ideas?

**Comment by jlyon** [comment]
@kevindherman examples of links?

**Comment by kevindherman** [comment]
@jlyon from zendesk:

"see screenshot below. We do not have a residents or visitors section on our site."
![image](https://cloud.githubusercontent.com/assets/6032426/25045350/e935e14c-20f9-11e7-9d12-2efcf4ba16d4.png)

**Comment by jlyon** [comment]
@kevindherman I just reset the broken link checked on playkettering.org and ketteringoh.org. It's looking a lot better on https://www.playkettering.org/wp-admin/tools.php?page=view-broken-links.
