### ISSUE TITLE
colma: upload error for documents

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#956]
Here is the error I am getting when trying to load a large file document. See attached. This was 86MB's and took about 7-8 minutes to load.

This also happened with a file that was 40mb.

![document_loading_error](https://cloud.githubusercontent.com/assets/6032426/24935041/533bcf8e-1eed-11e7-9c2d-4279863795d9.JPG)

**Comment by jlyon** [comment]
Could you try uploading the file from https://github.com/proudcity/wp-proudcity/issues/953?

**Comment by kevindherman** [comment]
@jlyon he did it from the media > media library (add new button) in this screenshot. I'll make it clear to go media > add new: https://colma-ca.proudcity.com/wp-admin/media-new.php

issue #953 references https://colma-ca.proudcity.com/wp-admin/upload.php which I missed which is likely why we got the same results.

**Comment by jlyon** [comment]
@kevindherman to get report of how it worked from the other upload url and/or to get urls to the other big files and @jlyon will load them in.

**Comment by kevindherman** [comment]
@jlyon here's another document upload issue. This one uploaded but won't preview even though it's less than 50mb. https://colma-ca.proudcity.com/documents/town-hall-renovation-project-plans/

**Comment by jlyon** [comment]
@kevindherman the limit for supported doucuments is 20mb.  I think we set the limit for showing the embed higher because a bigger doc worked for one client, but anything over 20mb, we can't guarantee that the preview will come up.  This is a limitation of the gdoc viewer.  

This doc is 28mb.

**Comment by kevindherman** [comment]
@jlyon that explains it, I've been saying the preview works up to 50mb.
