### ISSUE TITLE
dashboard: submit ticket

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#96]

**Comment by kevindherman** [comment]
Can you have  the submit a ticket open a new tab or window?

**Comment by jlyon** [comment]
Made these open in a new window @kevindherman

**Comment by kevindherman** [comment]
Sweet, thank you.

Eventually lets look into the WP-Zendesk plugin:
https://wordpress.org/plugins/zendesk/

On Wed, Feb 3, 2016 at 3:37 PM, Jeff Lyon <notifications@github.com> wrote:

> Assigned #96 <https://github.com/proudcity/wp-proudcity/issues/96> to
> @kevindherman <https://github.com/kevindherman>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/96#event-538160161>.
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by jlyon** [comment]
added #103
