### ISSUE TITLE
Colma: service center town hall hours not accurate

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#964]
The front end is showing that Town Hall is closed under my services when they're open:

https://colma-ca.proudcity.com/
![screenshot 2017-04-17 13 00 04](https://cloud.githubusercontent.com/assets/6032426/25096394/fc9b04bc-236d-11e7-9110-e6f8201563c9.png)
![screenshot 2017-04-17 13 00 29](https://cloud.githubusercontent.com/assets/6032426/25096393/fc9ae4c8-236d-11e7-9e83-418a5f3f4e68.png)

**Comment by jlyon** [comment]
Fixed the timezone @kevindherman. This should be all set now.

**Comment by kevindherman** [comment]
@jlyon bug or did I do something wrong?

**Comment by jlyon** [comment]
@kevindherman we just need to set the timezone for sites.  For new sites, it defaults to US PT.
