### ISSUE TITLE
Nav: change Departments to Government

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#97]
Nav: change Departments to Government

**Comment by jlyon** [comment]
@kevin: this is done.  The post type is still Department and the url pattern to department pages is still /department/[name].  Lemmie know if you want to change either of these.

**Comment by kevindherman** [comment]
All good, thank you.

On Wed, Feb 3, 2016 at 2:23 PM, Jeff Lyon <notifications@github.com> wrote:

> @kevin <https://github.com/kevin>: this is done. The post type is still
> Department and the url pattern to department pages is still
> /department/[name]. Lemmie know if you want to change either of these.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/97#issuecomment-179413842>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com
