### ISSUE TITLE
Danville: stale content reminder

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#971]
I believe this came up with the Cabarrus County proposal. Danville asked about a way to have automatic reminders on stale content for certain content types, specifically, department news. 

@jlyon do you think it's safe to say that type of feature could be included in a future release?

**Comment by jlyon** [comment]
@kevindherman Yes, this could be added in a future release, or could be a you pay us to do the dev and we'll give you a discount to put it back in the platform deal.
