### ISSUE TITLE
Service center app is down

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#972]
The service center isn't displaying on San Rafael's facebook:

![screenshot 2017-04-20 12 02 09](https://cloud.githubusercontent.com/assets/6032426/25240617/496d9868-25c1-11e7-976d-8c4da8bfafdb.png)

I also noticed that it's not displaying on the dashboard preview for mobile devices which could be related:

![screenshot 2017-04-20 12 01 59](https://cloud.githubusercontent.com/assets/6032426/25240640/5b2e7a9a-25c1-11e7-941c-1efb1892a8ed.png)

**Comment by aschmoe** [comment]
@kevindherman deployed fix for this for all sites

**Comment by aschmoe** [comment]
@kevindherman actually had to roll that back, there was an issue with the deploy script.  We're looking into it

**Comment by jlyon** [comment]
Fixed in Hotfix 1.23.0. #966
