### ISSUE TITLE
Kettering: clicking event detail goes to error page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#973]
Clicking on an event details yields a "this page isn't working" error.

Step 1: click board of zoning event from event feed on the homepage:
https://www.ketteringoh.org/#/city/answers
 
Step 2: result
https://www.ketteringoh.org/event/board-zoning-appeals-2-2017-04-24/
![screenshot 2017-04-20 15 44 06](https://cloud.githubusercontent.com/assets/6032426/25249544/33896ad0-25e0-11e7-8c7e-930d4a11107b.png)

This happened from /events as well. 

San Rafael, Play Kettering and a couple others I checked appear to be ok so this seems to be isolated.

**Comment by jlyon** [comment]
@kevindherman: @aschmoe  noticed that this is now fixed.  Neither of us did anything to it, however I did have a hotfix earlier this morning that cleared the caches, which may have fixed the issue.

Moving this to blocked so we can continue to monitor, but I think we are good for now.

**Comment by jlyon** [comment]
Moving to ready.
