### ISSUE TITLE
Styleguide font tweaks

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#98]
- [x] Make heading fonts smaller
- [x] Play with narrow headings
- [ ] Readjust paddings?

**Comment by jlyon** [comment]
Pushed to https://west-carrollton-oh.proudcity.com.  Thoughts @kevindherman @lukefretwell @aschmoe?

**Comment by kevindherman** [comment]
Look haut.

On Wed, Feb 3, 2016 at 1:33 PM, Jeff Lyon <notifications@github.com> wrote:

> Pushed to https://west-carrollton-oh.proudcity.com. Thoughts @kevindherman
> <https://github.com/kevindherman> @lukefretwell
> <https://github.com/lukefretwell> @aschmoe <https://github.com/aschmoe>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/98#issuecomment-179393752>
> .
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by jlyon** [comment]
Do we want to mess with padding?

**Comment by aschmoe** [comment]
Your talking header hero?  I can do that real quick

On Thu, Feb 4, 2016 at 9:38 PM, Jeff Lyon <notifications@github.com> wrote:

> Do we want to mess with padding?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/98#issuecomment-180207432>
> .
>



-- 
Alex Schmoe
Senior Web Developer
Albatross Digital

www.albatrossdigital.com | alex@albatrossdigital.com | W 720.663.0581 | C
206.240.1801

**Comment by aschmoe** [comment]
Woops wrong thing.

**Comment by aschmoe** [comment]
@jlyon sorry guess I'm unsure of exactly what you mean then

**Comment by jlyon** [comment]
closing
