### ISSUE TITLE
Webform file upload from end user yielding an error on entries page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#981]
K Parks updated some fields on this form and now all the entries prior to those changes that had file uploads from the end user are broken on the entries page. 

Entries: https://www.playkettering.org/wp-admin/admin.php?page=gf_entries&id=21

So everyone after Reese (working attachments) has the new fields you added. Reese and before (broken attachments) is prior to you updating the fields.

![screenshot 2017-05-03 11 47 56](https://cloud.githubusercontent.com/assets/6032426/25669122/a2134f00-2ff6-11e7-9271-905458d2a956.png)

Everything below the red line give this error when you click the attachment:

https://www.playkettering.org/index.php?gf-download=2017%2F05%2FSammuel-Reese-Camp-Health-Form.pdf&form-id=21&field-id=2&hash=47e911af69f4246e4339ec834bc2b03eb9e3dd41362ac58cf411cacc24f6aa81
![screenshot 2017-05-03 11 50 12](https://cloud.githubusercontent.com/assets/6032426/25669153/b38a92ac-2ff6-11e7-8920-61ec811ecb94.png)

**Comment by jlyon** [comment]
Possibly related to #989? 

@kevindherman did something happen (ie people re-uploaded the form, or something)?  I'm able to download a file for every PDF link on https://www.playkettering.org/wp-admin/admin.php?page=gf_entries&id=21:

**Comment by kevindherman** [comment]
@jlyon  Someone moved the problematic ones to the trash folder.

**Comment by kevindherman** [comment]
@jlyon he confirmed that he moved the problematic submissions to "trash" but did not delete so he could contact those people to get the information. The difference between the working and non working submissions is that he changed a field or two on the form. Should that throw off previously submitted files?

**Comment by jlyon** [comment]
@kevinherman yes changing (especially removing) fields will affect the data that is stored in the fields.

**Comment by kevindherman** [comment]
@jlyon thanks. One more question before closing this issue. Is there a way to easily recover those files or are they now gone?

**Comment by kevindherman** [comment]
@jlyon this is coming up on entries after the field change on this form:

https://www.playkettering.org/wp-admin/admin.php?page=gf_entries&id=21

I can't figure out what the difference between the ones working and not working, can you?

From ZenDesk:

Hi Kevin,

I'm running into a few of these that don't seem to be connected properly. Can you see if its something on our end or what the problem is? I have not updated the form or made any changes. As an example, Audrey Nelson, Victoria Contreras don't work but Lucille Pruitt and Caleb Thorpe worked just fine. Any thoughts???

Thank You,

**Comment by kevindherman** [comment]
@aschmoe something similar appears to be happening on SR Parks for this form:

https://www.livelifelocally.org/photo-contest-get-your-play-on/

If I select one of the entries from here: https://www.livelifelocally.org/wp-admin/admin.php?page=gf_entries&view=entry&id=12&lid=225&order=ASC&filter&paged=1&pos=0&field_id&operator
![screenshot 2017-07-11 09 57 06](https://user-images.githubusercontent.com/6032426/28071893-5131231e-661f-11e7-94d6-64112ea0e60c.png)

And then click on the file image I am redirected to an error page:
https://www.livelifelocally.org/index.php?gf-download=2017%2F07%2FIMG_4831.JPG&form-id=12&field-id=6&hash=337c0b66cc62b7d6848cfd56823b61735df3d7f72b51ff0780244e45c9a68c5f
![screenshot 2017-07-11 09 57 50](https://user-images.githubusercontent.com/6032426/28071925-6a443a6c-661f-11e7-8cb3-9c91063b8386.png)

Are these files lost?

**Comment by kevindherman** [comment]
@jlyon @aschmoe the form in question is pretty new, created on July 3rd it that helps.

**Comment by aschmoe** [comment]
@kevindherman so issue was they were using the "multi file" select option which I have not looked into.  For the time being I have switched to a single file option.

Any files previously uploaded have been lost permanently.

**Comment by kevindherman** [comment]
@aschmoe thanks. I'll let them know about the temporary fix.
