### ISSUE TITLE
Colma: search results page bug

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#983]
If you search "vacation" on Coma and hit enter you get a long jumbled description under the first result: https://colma-ca.proudcity.com/search-site/?term=vacation
![screenshot 2017-05-03 17 27 30](https://cloud.githubusercontent.com/assets/6032426/25682372/f41b76d6-3025-11e7-9ad8-704c77d739a3.png)

**Comment by aschmoe** [comment]
@kevindherman as we've previously discussed, changing the SEO snippet description will fix that.  I've done that for this page

**Comment by aschmoe** [comment]
![edit page town of colma wordpress](https://cloud.githubusercontent.com/assets/1634686/25764299/02ac2214-319c-11e7-8f24-b773eee85b7d.jpg)
