### ISSUE TITLE
Colma: weather in service center

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#984]
Colma is reporting that the weather seems off. @jlyon can you double check that the right city is entered into the service center weather?

See their notes:
[ProudCity_Bug_Report_-_Weather_Service_Data.pdf](https://github.com/proudcity/wp-proudcity/files/974747/ProudCity_Bug_Report_-_Weather_Service_Data.pdf)

**Comment by jlyon** [comment]
Hmm, seems like it's pulling the correct forecast (https://openweathermap.org/city/5338703 is where the View Forecast button goes), but that openweathermap does seem to be 10 degrees warmer that what I get in a Google search.

**Comment by kevindherman** [comment]
@jlyon weird that it's 10 degrees different, that's a lot.
