### ISSUE TITLE
K Parks: image set upload image broken

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#986]
When selecting "upload image" on the image set the button does not click through to upload media. nothing happens.

https://www.livelifelocally.org/wp-admin/post.php?post=1650&action=edit
![screenshot 2017-05-04 15 16 33](https://cloud.githubusercontent.com/assets/6032426/25721047/1706ba36-30dd-11e7-8d05-3b39eaf264ed.png)

**Comment by aschmoe** [comment]
@kevindherman this has been fixed
