### ISSUE TITLE
K: Large uploads not successfully working

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#989]
@kevindherman I am seeing 4 recently uploaded files that are all large that didn't get uploaded properly: 
- https://www.ketteringoh.org/wp-admin/post.php?post=8379&action=edit
- https://www.ketteringoh.org/wp-admin/post.php?post=8378&action=edit
- https://www.ketteringoh.org/wp-admin/post.php?post=8377&action=edit
- https://www.ketteringoh.org/wp-admin/post.php?post=8376&action=edit
Unfortunately these files didn't make it to the server successfully

They're all pretty large. Do you think we could have them put them in a directory and zip them up so we can load them in for them and do some debugging so it doesn't crop up again in the future? wetransfer.com is good for quick one-off large file transfers.

Also, did they upload from the main Media add dialog (like when adding a document) or page (https://www.ketteringoh.org/wp-admin/upload.php), or the Add New page? We have found that large file uploads (> 20 mb) work better on the Add New page: https://www.ketteringoh.org/wp-admin/media-new.php

**Comment by jlyon** [comment]
Related #956

**Comment by kevindherman** [comment]
@jlyon here are the files: https://wetransfer.com/downloads/f4354e730f5ed2cee26a2f9d034a1c0f20170508133609/42f3e70023424a2bfac16ed9529bbc2420170508133609/d47dbe

**Comment by kevindherman** [comment]
@jlyon I was able to upload both of the documents in the wetransfer on Add New page: https://www.ketteringoh.org/wp-admin/media-new.php

However, once the upload was complete, I got a http error: 

![screenshot 2017-05-08 11 09 52](https://cloud.githubusercontent.com/assets/6032426/25810861/639ff506-33df-11e7-9cd1-3e5604341a89.png)

I ignored the error and swapped the newly uploaded pdf's onto their respective documents and successfully tested the download from the doc pages. 

I'll report back to the client that it is working but I think it's worth checking in on the http error.

**Comment by jlyon** [comment]
@kevindherman I just tried uploading both files on the Add New page and didn't get any errors.  I'll dig into it a little more tonight.

**Comment by kevindherman** [comment]
I was using chrome if the helps.
