### ISSUE TITLE
Answers optimizations

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#99]
- [x] GA click tracking
- [ ] Redirect when you go to https://west-carrollton-oh.proudcity.com/city/answers/jobs/?
- [ ] Redirect w you go to city/answers/jobs/what-benefits-does-the-city-offer?
- [x] Redirect + formatting w you go to https://west-carrollton-oh.proudcity.com/question/what-benefits-does-the-city-offer/
- [ ] https://west-carrollton-oh.proudcity.com/city/payments/court-payments
- [x] Do we need to do anything for JS app in google? (my thought=no)
- [x] Do we want to change GA tracking url (from /city/answers/[tax]/[slug] to /answers/[slug])? @aschmoe

**Comment by kevindherman** [comment]
I noticed that on the /residents and /businesses pages that the
sub-categories are showing but on the homepage it's the intended collapsed
view of just the top categories. This should be consistent.

On Wed, Feb 3, 2016 at 3:12 PM, Jeff Lyon <notifications@github.com> wrote:

>
>    - GA click tracking
>    - Redirect when you go to
>    https://west-carrollton-oh.proudcity.com/city/answers/jobs/?
>    - Redirect w you go to
>    city/answers/jobs/what-benefits-does-the-city-offer?
>    - Redirect + formatting w you go to
>    https://west-carrollton-oh.proudcity.com/question/what-benefits-does-the-city-offer/
>    - https://west-carrollton-oh.proudcity.com/city/payments/court-payments
>    - Do we need to do anything for JS app in google? (my thought=no)
>
> @aschmoe <https://github.com/aschmoe>, let's discuss today or tom
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/proudcity/wp-proudcity/issues/99>.
>



-- 
Kevin Herman
ProudCity
917.873.4666
ProudCity.com

**Comment by jlyon** [comment]
@kevindherman Fixed this so you are redirect if you happen upon an Answer or payment:
* https://west-carrollton-oh.proudcity.com/payments/court-payments
* https://west-carrollton-oh.proudcity.com/question/where-is-the-farmers-market/

I think we talked about the consistency issue last week (it's by design, but can easily be changed in the panels interface).

**Comment by kevindherman** [comment]
@jlyon this is great.

**Comment by aschmoe** [comment]
> Do we want to change GA tracking url (from /city/answers/[tax]/[slug] to 
> /answers/[slug])?

Lets just leave it for now.

**Comment by jlyon** [comment]
yes, we want to change it to /answers/[slug] if it's not too difficult.

**Comment by aschmoe** [comment]
Means more difficulty porting changes between app + demo site, which is why
I originally left the URL pattern

**Comment by jlyon** [comment]
oh sorry, i didn't see the formatting when i read it. i think we will want to change it to /answers/[slug] so that we can easily match the GA entry with the WP post without having to run it through anything.  I don't think the actual url (after #) matters, just what it goes into GA as.  I also don't think the GA tracking on the demo for answers really matters if that makes a difference.

**Comment by jlyon** [comment]
@aschmoe can we talk abt this today?

**Comment by jlyon** [comment]
1. set page reported to GA as /question/[slug]
2. send an event: answersFaq, value = /city/answers/[term_slug]/[post_slug]
@aschmoe

**Comment by aschmoe** [comment]
@jlyon these are added.  Added another event for clicking the categories on the home faq page as well

**Comment by jlyon** [comment]
Looks good. I think the only thing left is to remove the "/city" from the   pageview trigger sent for payments (/city/payments/court-payments).  Sorry, I think I might have said that it was fine the way it was yest, but I think we should have it match the WP paths for consistency.

**Comment by aschmoe** [comment]
It is already

**Comment by jlyon** [comment]
Word I must have been looking at the eventLabel. Moving this to ready.
