### ISSUE TITLE
SR: payout detail - transaction detail not loading

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#993]
The transaction detail says loading on the the payout detail page and on the print out page:

https://new.proudcity.com/sites/589041206d53977d90792ca2/payments/payouts/po_1AJnutDTdWfQObqTpBfWN7Cw
![screenshot 2017-05-17 15 29 56](https://cloud.githubusercontent.com/assets/6032426/26172298/e8b87604-3b15-11e7-96a6-abefea2f01a3.png)

[ProudCity Dashboard.pdf](https://github.com/proudcity/wp-proudcity/files/1008916/ProudCity.Dashboard.pdf)

I got to this page from new.proudcity.com > San Rafael > Payments > Payouts > selected the most recent for $423.48 and got the above pages logged in as both support@ and info@.

**Comment by jlyon** [comment]
@kevindherman  this looks like this was because this was a manual payout, not an automatic one.  It doesn't seem like that should matter, but I'm getting an error from  Stripe: `Balance transaction history can only be filtered on automatic transfers, not manual.`
