### ISSUE TITLE
SR Parks: add romulus widget

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#994]
It used to be available. See screenshot:
![missingwidgetromulus](https://cloud.githubusercontent.com/assets/6032426/26215140/2c816050-3bcd-11e7-9781-ce478a7324a8.PNG)

**Comment by aschmoe** [comment]
@kevindherman re-added this plugin

**Comment by kevindherman** [comment]
@aschmoe thank you.
