### ISSUE TITLE
RSS on jobs page

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#995]
The RSS widget is on the backend, I just don't know how to set it up. What information, specifically the URL, do I add for the /jobs and /news pages?

- https://www.ketteringoh.org/jobs
- https://www.ketteringoh.org/news/

**Comment by aschmoe** [comment]
@kevindherman 

https://www.ketteringoh.org/feed/?post_type=job_listing
https://www.ketteringoh.org/feed/?post_type=post
