### ISSUE TITLE
WC: content not publishing

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#999]
There is a lot of content that is showing on the backend but is not publishing: 
https://www.westcarrollton.org/wp-admin/post.php?post=3558&action=edit

Now it's a blank white screen: https://www.westcarrollton.org/agendas-minutes-upcoming-cases/

From ZenDesk:

Hello,

I have just finished adding documents to a page and after logging off, I opened the page and everything was gone. The edited page is here:

https://www.westcarrollton.org/agendas-minutes-upcoming-cases/

I logged off at approximately 4:27 to 4:29.

Is it possible to recover that information? Please let me know.

Will be back in the office on Tuesday, May 30, 2017.

**Comment by aschmoe** [comment]
@kevindherman seeing this now as working... @jlyon did you do something?

**Comment by kevindherman** [comment]
@aschmoe @jlyon I'm now seeing content as well. I did notice that some of the files link to a page not found message.

**Comment by jlyon** [comment]
@kevindherman ok to close this?

**Comment by kevindherman** [comment]
@jlyon yup.
